Repository astral-sh/ruff, pull requests merged in 2023-08, with the labels that each got.

#6218 Skip trivia when searching for named exception
  crates/ruff/resources/test/fixtures/pyflakes/F841_3.py
  crates/ruff/src/rules/pyflakes/fixes.rs
  crates/ruff/src/rules/pyflakes/snapshots/ruff__rules__pyflakes__tests__F841_F841_3.py.snap
Labels: bug

#6220 Avoid PERF401 false positive on list access in loop
  crates/ruff/resources/test/fixtures/perflint/PERF401.py
  crates/ruff/src/rules/perflint/rules/manual_list_comprehension.rs
  crates/ruff/src/rules/perflint/rules/manual_list_copy.rs
Labels: bug

#6146 Add DTZ002 documentation
  crates/ruff/src/rules/flake8_datetimez/rules/call_datetime_today.rs
  crates/ruff/src/rules/flake8_datetimez/rules/call_datetime_without_tzinfo.rs
Labels: documentation

#6221 Remove use of `SmallVec` in `unnecessary-literal-union`
  crates/ruff/src/rules/flake8_pyi/rules/unnecessary_literal_union.rs
Labels: internal

#6219 Avoid detecting continuations at non-start-of-line
  crates/ruff/resources/test/fixtures/pycodestyle/E70.py
  crates/ruff/src/rules/pycodestyle/snapshots/ruff__rules__pycodestyle__tests__E703_E70.py.snap
  crates/ruff_python_index/src/indexer.rs
Labels: bug

#6143 Add `PT021`, `PT022` and `PT023` docs
  crates/ruff/src/rules/flake8_pytest_style/rules/assertion.rs
  crates/ruff/src/rules/flake8_pytest_style/rules/fail.rs
  crates/ruff/src/rules/flake8_pytest_style/rules/fixture.rs
  crates/ruff/src/rules/flake8_pytest_style/rules/marks.rs
  crates/ruff/src/rules/flake8_pytest_style/rules/raises.rs
Labels: documentation

#6167 add `DebugText` for self-documenting f-strings
  crates/ruff/src/rules/flynt/helpers.rs
  crates/ruff_python_ast/src/comparable.rs
  crates/ruff_python_ast/src/nodes.rs
  crates/ruff_python_codegen/src/generator.rs
  crates/ruff_python_parser/src/snapshots/ruff_python_parser__parser__tests__try.snap
  crates/ruff_python_parser/src/snapshots/ruff_python_parser__parser__tests__try_star.snap
  crates/ruff_python_parser/src/snapshots/ruff_python_parser__string__tests__fstring_constant_range.snap
  crates/ruff_python_parser/src/snapshots/ruff_python_parser__string__tests__fstring_escaped_character.snap
  crates/ruff_python_parser/src/snapshots/ruff_python_parser__string__tests__fstring_escaped_newline.snap
  crates/ruff_python_parser/src/snapshots/ruff_python_parser__string__tests__fstring_line_continuation.snap
  crates/ruff_python_parser/src/snapshots/ruff_python_parser__string__tests__fstring_parse_self_documenting_base.snap
  crates/ruff_python_parser/src/snapshots/ruff_python_parser__string__tests__fstring_parse_self_documenting_base_more.snap
  crates/ruff_python_parser/src/snapshots/ruff_python_parser__string__tests__fstring_parse_self_documenting_format.snap
  crates/ruff_python_parser/src/snapshots/ruff_python_parser__string__tests__fstring_unescaped_newline.snap
  crates/ruff_python_parser/src/snapshots/ruff_python_parser__string__tests__parse_f_string_concat_3.snap
  crates/ruff_python_parser/src/snapshots/ruff_python_parser__string__tests__parse_fstring.snap
  crates/ruff_python_parser/src/snapshots/ruff_python_parser__string__tests__parse_fstring_equals.snap
  crates/ruff_python_parser/src/snapshots/ruff_python_parser__string__tests__parse_fstring_nested_spec.snap
  crates/ruff_python_parser/src/snapshots/ruff_python_parser__string__tests__parse_fstring_not_equals.snap
  crates/ruff_python_parser/src/snapshots/ruff_python_parser__string__tests__parse_fstring_not_nested_spec.snap
  crates/ruff_python_parser/src/snapshots/ruff_python_parser__string__tests__parse_fstring_self_doc_prec_space.snap
  crates/ruff_python_parser/src/snapshots/ruff_python_parser__string__tests__parse_fstring_self_doc_trailing_space.snap
  crates/ruff_python_parser/src/snapshots/ruff_python_parser__string__tests__parse_fstring_yield_expr.snap
  crates/ruff_python_parser/src/snapshots/ruff_python_parser__string__tests__raw_fstring.snap
  crates/ruff_python_parser/src/snapshots/ruff_python_parser__string__tests__triple_quoted_raw_fstring.snap
  crates/ruff_python_parser/src/string.rs
Labels: parser

#6231 Consistent `CommentPlacement` conversion signatures
  crates/ruff_python_formatter/src/comments/placement.rs
  crates/ruff_python_formatter/src/comments/visitor.rs
Labels: formatter

#6238 Fix `logger-objects` documentation
  crates/ruff/src/settings/options.rs
Labels: documentation

#6239 Don't require docstrings in `.pyi` files
  crates/ruff/src/checkers/ast/mod.rs
  crates/ruff/src/rules/pydocstyle/rules/not_missing.rs
Labels: bug

#6206 Add empty lines before nested functions and classes
  crates/ruff_python_formatter/src/module/mod_module.rs
  crates/ruff_python_formatter/src/statement/stmt_class_def.rs
  crates/ruff_python_formatter/src/statement/stmt_function_def.rs
  crates/ruff_python_formatter/src/statement/suite.rs
  crates/ruff_python_formatter/tests/snapshots/black_compatibility@simple_cases__function2.py.snap
  crates/ruff_python_formatter/tests/snapshots/format@statement__function.py.snap
  crates/ruff_python_formatter/tests/snapshots/format@statement__if.py.snap
  crates/ruff_python_formatter/tests/snapshots/format@statement__try.py.snap
Labels: formatter

#6247 Allow generic tuple and list calls in __all__
  crates/ruff/resources/test/fixtures/pylint/invalid_all_format.py
  crates/ruff_python_ast/src/all.rs
Labels: bug

#6235 Remove `Parse` trait
  crates/ruff/src/autofix/edits.rs
  crates/ruff/src/importer/insertion.rs
  crates/ruff/src/rules/eradicate/detection.rs
  crates/ruff/src/rules/isort/rules/add_required_imports.rs
  crates/ruff/src/rules/mccabe/rules/function_is_too_complex.rs
  crates/ruff/src/rules/pylint/rules/too_many_branches.rs
  crates/ruff/src/rules/pylint/rules/too_many_return_statements.rs
  crates/ruff/src/rules/pylint/rules/too_many_statements.rs
  crates/ruff_benchmark/benches/parser.rs
  crates/ruff_dev/src/print_ast.rs
  crates/ruff_python_ast/tests/identifier.rs
  crates/ruff_python_ast/tests/stmt_if.rs
  crates/ruff_python_codegen/src/generator.rs
  crates/ruff_python_codegen/src/lib.rs
  crates/ruff_python_formatter/src/expression/expr_name.rs
  crates/ruff_python_formatter/src/statement/suite.rs
  crates/ruff_python_parser/src/context.rs
  crates/ruff_python_parser/src/function.rs
  crates/ruff_python_parser/src/lib.rs
  crates/ruff_python_parser/src/parse.rs
  crates/ruff_python_parser/src/parser.rs
  crates/ruff_python_parser/src/string.rs
  crates/ruff_python_parser/src/typing.rs
  crates/ruff_python_trivia/src/whitespace.rs
  fuzz/fuzz_targets/ruff_parse_simple.rs
Labels: internal

#6248 Run ecosystem checks on changes to ecosystem test script
  .github/workflows/ci.yaml
Labels: internal

#6243 Tweak pre-commit message
  CONTRIBUTING.md
Labels: documentation

#6209 Implement Black's rules around newlines before and after class docstrings
  crates/ruff_python_formatter/resources/test/fixtures/ruff/statement/class_definition.py
  crates/ruff_python_formatter/src/statement/suite.rs
  crates/ruff_python_formatter/tests/snapshots/black_compatibility@simple_cases__class_methods_new_line.py.snap
  crates/ruff_python_formatter/tests/snapshots/format@statement__class_definition.py.snap
Labels: formatter

#6274 Add formatter support for call and class definition `Arguments`
  crates/ruff_python_ast/src/node.rs
  crates/ruff_python_formatter/resources/test/fixtures/ruff/expression/call.py
  crates/ruff_python_formatter/resources/test/fixtures/ruff/statement/class_definition.py
  crates/ruff_python_formatter/src/builders.rs
  crates/ruff_python_formatter/src/comments/placement.rs
  crates/ruff_python_formatter/src/comments/visitor.rs
  crates/ruff_python_formatter/src/expression/expr_call.rs
  crates/ruff_python_formatter/src/generated.rs
  crates/ruff_python_formatter/src/other/arguments.rs
  crates/ruff_python_formatter/src/other/mod.rs
  crates/ruff_python_formatter/src/statement/stmt_class_def.rs
  crates/ruff_python_formatter/src/statement/stmt_function_def.rs
  crates/ruff_python_formatter/tests/snapshots/format@expression__call.py.snap
  crates/ruff_python_formatter/tests/snapshots/format@expression__dict.py.snap
  crates/ruff_python_formatter/tests/snapshots/format@expression__lambda.py.snap
  crates/ruff_python_formatter/tests/snapshots/format@expression__list.py.snap
  crates/ruff_python_formatter/tests/snapshots/format@statement__class_definition.py.snap
  crates/ruff_python_formatter/tests/snapshots/format@statement__delete.py.snap
  crates/ruff_python_formatter/tests/snapshots/format@statement__raise.py.snap
Labels: formatter

#6279 Remove `CallArguments` abstraction
  crates/ruff/src/checkers/ast/analyze/expression.rs
  crates/ruff/src/rules/flake8_bandit/rules/bad_file_permissions.rs
  crates/ruff/src/rules/flake8_bandit/rules/hashlib_insecure_hash_functions.rs
  crates/ruff/src/rules/flake8_bandit/rules/snmp_weak_cryptography.rs
  crates/ruff/src/rules/flake8_bandit/rules/unsafe_yaml_load.rs
  crates/ruff/src/rules/flake8_logging_format/rules/logging_call.rs
  crates/ruff/src/rules/flake8_pytest_style/rules/fail.rs
  crates/ruff/src/rules/flake8_pytest_style/rules/patch.rs
  crates/ruff/src/rules/pylint/rules/logging.rs
  crates/ruff/src/rules/tryceratops/rules/error_instead_of_exception.rs
  crates/ruff_python_ast/src/helpers.rs
  crates/ruff_python_ast/src/nodes.rs
  crates/ruff_python_semantic/src/analyze/logging.rs
Labels: internal

#6280 Move `find_keyword` helpers onto `Arguments` struct
  crates/ruff/src/checkers/ast/analyze/expression.rs
  crates/ruff/src/rules/airflow/rules/task_variable_name.rs
  crates/ruff/src/rules/flake8_bandit/rules/jinja2_autoescape_false.rs
  crates/ruff/src/rules/flake8_bandit/rules/logging_config_insecure_listen.rs
  crates/ruff/src/rules/flake8_bandit/rules/request_with_no_cert_validation.rs
  crates/ruff/src/rules/flake8_bandit/rules/request_without_timeout.rs
  crates/ruff/src/rules/flake8_bandit/rules/shell_injection.rs
  crates/ruff/src/rules/flake8_bandit/rules/snmp_insecure_version.rs
  crates/ruff/src/rules/flake8_blind_except/rules/blind_except.rs
  crates/ruff/src/rules/flake8_bugbear/rules/assert_raises_exception.rs
  crates/ruff/src/rules/flake8_bugbear/rules/no_explicit_stacklevel.rs
  crates/ruff/src/rules/flake8_bugbear/rules/zip_without_explicit_strict.rs
  crates/ruff/src/rules/flake8_datetimez/rules/call_datetime_fromtimestamp.rs
  crates/ruff/src/rules/flake8_datetimez/rules/call_datetime_now_without_tzinfo.rs
  crates/ruff/src/rules/flake8_datetimez/rules/call_datetime_strptime_without_zone.rs
  crates/ruff/src/rules/flake8_datetimez/rules/call_datetime_without_tzinfo.rs
  crates/ruff/src/rules/flake8_datetimez/rules/helpers.rs
  crates/ruff/src/rules/flake8_django/rules/locals_in_render_function.rs
  crates/ruff/src/rules/flake8_print/rules/print_call.rs
  crates/ruff/src/rules/flake8_pytest_style/rules/fixture.rs
  crates/ruff/src/rules/flake8_pytest_style/rules/raises.rs
  crates/ruff/src/rules/flake8_use_pathlib/rules/os_sep_split.rs
  crates/ruff/src/rules/pandas_vet/rules/read_table.rs
  crates/ruff/src/rules/pylint/helpers.rs
  crates/ruff/src/rules/pylint/rules/invalid_envvar_default.rs
  crates/ruff/src/rules/pylint/rules/invalid_envvar_value.rs
  crates/ruff/src/rules/pylint/rules/subprocess_popen_preexec_fn.rs
  crates/ruff/src/rules/pylint/rules/type_bivariance.rs
  crates/ruff/src/rules/pylint/rules/type_name_incorrect_variance.rs
  crates/ruff/src/rules/pylint/rules/type_param_name_mismatch.rs
  crates/ruff/src/rules/pyupgrade/rules/convert_typed_dict_functional_to_class.rs
  crates/ruff/src/rules/pyupgrade/rules/redundant_open_modes.rs
  crates/ruff/src/rules/pyupgrade/rules/replace_stdout_stderr.rs
  crates/ruff/src/rules/pyupgrade/rules/replace_universal_newlines.rs
  crates/ruff_python_ast/src/helpers.rs
Labels: internal

#6283 Avoid `PTH206` with `maxsplit`
  crates/ruff/resources/test/fixtures/flake8_use_pathlib/PTH206.py
  crates/ruff/src/rules/flake8_use_pathlib/rules/os_sep_split.rs
Labels: bug

#6264 Add `PT025` and `PT026` docs
  crates/ruff/src/rules/flake8_pytest_style/rules/fixture.rs
  crates/ruff/src/rules/flake8_pytest_style/rules/marks.rs
Labels: documentation

#6215 [`flake8-pyi`] Implement PYI051
  crates/ruff/resources/test/fixtures/flake8_pyi/PYI051.py
  crates/ruff/resources/test/fixtures/flake8_pyi/PYI051.pyi
  crates/ruff/src/checkers/ast/analyze/expression.rs
  crates/ruff/src/codes.rs
  crates/ruff/src/rules/flake8_pyi/mod.rs
  crates/ruff/src/rules/flake8_pyi/rules/mod.rs
  crates/ruff/src/rules/flake8_pyi/rules/redundant_literal_union.rs
  crates/ruff/src/rules/flake8_pyi/snapshots/ruff__rules__flake8_pyi__tests__PYI051_PYI051.py.snap
  crates/ruff/src/rules/flake8_pyi/snapshots/ruff__rules__flake8_pyi__tests__PYI051_PYI051.pyi.snap
  ruff.schema.json
Labels: rule

#6172 Break global and nonlocal statements over continuation lines
  crates/ruff_python_formatter/resources/test/fixtures/ruff/statement/global.py
  crates/ruff_python_formatter/resources/test/fixtures/ruff/statement/nonlocal.py
  crates/ruff_python_formatter/src/statement/stmt_global.rs
  crates/ruff_python_formatter/src/statement/stmt_nonlocal.rs
  crates/ruff_python_formatter/tests/snapshots/format@statement__global.py.snap
  crates/ruff_python_formatter/tests/snapshots/format@statement__nonlocal.py.snap
Labels: formatter

#6161 Add formatting of type parameters in class and function definitions
  crates/ruff_python_ast/src/function.rs
  crates/ruff_python_ast/src/node.rs
  crates/ruff_python_formatter/generate.py
  crates/ruff_python_formatter/resources/test/fixtures/ruff/expression/list.py
  crates/ruff_python_formatter/resources/test/fixtures/ruff/statement/class_definition.py
  crates/ruff_python_formatter/resources/test/fixtures/ruff/statement/function.py
  crates/ruff_python_formatter/src/comments/placement.rs
  crates/ruff_python_formatter/src/comments/visitor.rs
  crates/ruff_python_formatter/src/generated.rs
  crates/ruff_python_formatter/src/lib.rs
  crates/ruff_python_formatter/src/statement/stmt_class_def.rs
  crates/ruff_python_formatter/src/statement/stmt_function_def.rs
  crates/ruff_python_formatter/src/type_param/mod.rs
  crates/ruff_python_formatter/src/type_param/type_param_clause.rs
  crates/ruff_python_formatter/src/type_param/type_param_param_spec.rs
  crates/ruff_python_formatter/src/type_param/type_param_type_var.rs
  crates/ruff_python_formatter/src/type_param/type_param_type_var_tuple.rs
  crates/ruff_python_formatter/src/type_param/type_params.rs
  crates/ruff_python_formatter/tests/snapshots/black_compatibility@py_312__type_params.py.snap
  crates/ruff_python_formatter/tests/snapshots/format@expression__list.py.snap
  crates/ruff_python_formatter/tests/snapshots/format@statement__class_definition.py.snap
  crates/ruff_python_formatter/tests/snapshots/format@statement__function.py.snap
Labels: formatter

#6162 Add formatting of type alias statements
  crates/ruff_python_formatter/resources/test/fixtures/ruff/statement/type_alias.py
  crates/ruff_python_formatter/src/lib.rs
  crates/ruff_python_formatter/src/statement/stmt_type_alias.rs
  crates/ruff_python_formatter/tests/snapshots/black_compatibility@py_312__type_aliases.py.snap
  crates/ruff_python_formatter/tests/snapshots/format@statement__type_alias.py.snap
Labels: formatter

#6171 [`pylint`] Implement Pylint `bad-format-character` (`E1300`)
  crates/ruff/resources/test/fixtures/pylint/bad_string_format_character.py
  crates/ruff/src/checkers/ast/analyze/expression.rs
  crates/ruff/src/codes.rs
  crates/ruff/src/rules/pylint/mod.rs
  crates/ruff/src/rules/pylint/rules/bad_string_format_character.rs
  crates/ruff/src/rules/pylint/rules/mod.rs
  crates/ruff/src/rules/pylint/snapshots/ruff__rules__pylint__tests__PLE1300_bad_string_format_character.py.snap
  crates/ruff_python_literal/src/format.rs
  ruff.schema.json
Labels: rule

#6204 [`flake8-pyi`] Implement `custom_type_var_return_type` (`PYI019`)
  crates/ruff/resources/test/fixtures/flake8_pyi/PYI019.py
  crates/ruff/resources/test/fixtures/flake8_pyi/PYI019.pyi
  crates/ruff/src/checkers/ast/analyze/statement.rs
  crates/ruff/src/codes.rs
  crates/ruff/src/rules/flake8_pyi/mod.rs
  crates/ruff/src/rules/flake8_pyi/rules/custom_type_var_return_type.rs
  crates/ruff/src/rules/flake8_pyi/rules/mod.rs
  crates/ruff/src/rules/flake8_pyi/snapshots/ruff__rules__flake8_pyi__tests__PYI019_PYI019.py.snap
  crates/ruff/src/rules/flake8_pyi/snapshots/ruff__rules__flake8_pyi__tests__PYI019_PYI019.pyi.snap
  ruff.schema.json
Labels: rule

#6290 Tweak background on theme button
  playground/src/Editor/ShareButton.tsx
  playground/src/Editor/ThemeButton.tsx
  playground/src/index.css
Labels: playground

#6291 Increase icon opacity on-hover
  playground/src/Editor/SideBar.tsx
Labels: playground

#6292 Add an icon for FIR
  playground/src/Editor/Icons.tsx
  playground/src/Editor/SecondarySideBar.tsx
Labels: playground

#6295 Add a simple tooltip to the sidebar
  playground/src/Editor/PrimarySideBar.tsx
  playground/src/Editor/SecondarySideBar.tsx
  playground/src/Editor/ShareButton.tsx
  playground/src/Editor/SideBar.tsx
Labels: playground

#6304 Update `UP032` to support `await` expressions
  crates/ruff/resources/test/fixtures/pyupgrade/UP032_0.py
  crates/ruff/src/rules/pyupgrade/rules/f_strings.rs
  crates/ruff/src/rules/pyupgrade/snapshots/ruff__rules__pyupgrade__tests__UP032_0.py.snap
Labels: rule

#6309 Move `ExprCall`'s `NeedsParentheses` impl into `expr_call.rs`
  crates/ruff_python_formatter/src/expression/expr_call.rs
  crates/ruff_python_formatter/src/other/arguments.rs
Labels: internal

#6311 Return a slice in `StmtClassDef#bases`
  crates/ruff/src/rules/flake8_builtins/rules/builtin_attribute_shadowing.rs
  crates/ruff/src/rules/flake8_pie/rules/non_unique_enums.rs
  crates/ruff/src/rules/flake8_pyi/rules/unused_private_type_definition.rs
  crates/ruff/src/rules/flake8_type_checking/helpers.rs
  crates/ruff_python_ast/src/nodes.rs
  crates/ruff_python_semantic/src/analyze/function_type.rs
Labels: internal

#6310 Improve comments around `Arguments` handling in classes
  crates/ruff_python_formatter/src/statement/stmt_class_def.rs
Labels: internal

#6300 Make formatter ecosystem check failure output better understandable
  .github/workflows/ci.yaml
  crates/ruff_dev/src/format_dev.rs
  scripts/formatter_ecosystem_checks.sh
Labels: internal, formatter

#6317 Omit formatter PRs from releases by default
  .github/release.yml
Labels: release

#6315 Generalize bracketed end-of-line comment handling
  crates/ruff_python_formatter/src/comments/placement.rs
Labels: formatter

#6319 Add API to chain comment placement operations
  crates/ruff_python_formatter/src/comments/placement.rs
  crates/ruff_python_formatter/src/comments/visitor.rs
Labels: formatter

#6320 Generalize comment-after-bracket handling to lists, sets, etc.
  crates/ruff_formatter/src/builders.rs
  crates/ruff_python_formatter/resources/test/fixtures/ruff/expression/dict_comp.py
  crates/ruff_python_formatter/resources/test/fixtures/ruff/expression/generator_exp.py
  crates/ruff_python_formatter/resources/test/fixtures/ruff/expression/list.py
  crates/ruff_python_formatter/src/comments/placement.rs
  crates/ruff_python_formatter/src/expression/expr_dict.rs
  crates/ruff_python_formatter/src/expression/expr_dict_comp.rs
  crates/ruff_python_formatter/src/expression/expr_generator_exp.rs
  crates/ruff_python_formatter/src/expression/expr_list.rs
  crates/ruff_python_formatter/src/expression/expr_list_comp.rs
  crates/ruff_python_formatter/src/expression/expr_set.rs
  crates/ruff_python_formatter/src/expression/expr_set_comp.rs
  crates/ruff_python_formatter/src/expression/expr_tuple.rs
  crates/ruff_python_formatter/src/expression/parentheses.rs
  crates/ruff_python_formatter/tests/snapshots/format@expression__dict.py.snap
  crates/ruff_python_formatter/tests/snapshots/format@expression__dict_comp.py.snap
  crates/ruff_python_formatter/tests/snapshots/format@expression__generator_exp.py.snap
  crates/ruff_python_formatter/tests/snapshots/format@expression__list.py.snap
  crates/ruff_python_formatter/tests/snapshots/format@expression__tuple.py.snap
  crates/ruff_python_formatter/tests/snapshots/format@statement__raise.py.snap
Labels: formatter

#6316 [`flake8-pyi`] Implement PYI055
  crates/ruff/resources/test/fixtures/flake8_pyi/PYI055.py
  crates/ruff/resources/test/fixtures/flake8_pyi/PYI055.pyi
  crates/ruff/src/checkers/ast/analyze/expression.rs
  crates/ruff/src/codes.rs
  crates/ruff/src/rules/flake8_pyi/mod.rs
  crates/ruff/src/rules/flake8_pyi/rules/mod.rs
  crates/ruff/src/rules/flake8_pyi/rules/unnecessary_type_union.rs
  crates/ruff/src/rules/flake8_pyi/snapshots/ruff__rules__flake8_pyi__tests__PYI051_PYI051.py.snap
  crates/ruff/src/rules/flake8_pyi/snapshots/ruff__rules__flake8_pyi__tests__PYI055_PYI055.py.snap
  crates/ruff/src/rules/flake8_pyi/snapshots/ruff__rules__flake8_pyi__tests__PYI055_PYI055.pyi.snap
  ruff.schema.json
Labels: rule

#6325 Include comparisons to builtin types in `type-comparison` rule
  crates/ruff/resources/test/fixtures/pycodestyle/E721.py
  crates/ruff/src/rules/pycodestyle/rules/type_comparison.rs
  crates/ruff/src/rules/pycodestyle/snapshots/ruff__rules__pycodestyle__tests__E721_E721.py.snap
Labels: rule

#6326 Match left-hand side `types()` call in `types-comparison`
  crates/ruff/src/checkers/ast/analyze/expression.rs
  crates/ruff/src/rules/pycodestyle/rules/type_comparison.rs
  crates/ruff/src/rules/pycodestyle/snapshots/ruff__rules__pycodestyle__tests__E721_E721.py.snap
Labels: bug

#6328 Make the `Nodes` vector generic on node type
  crates/ruff_python_semantic/src/analyze/branch_detection.rs
  crates/ruff_python_semantic/src/model.rs
  crates/ruff_python_semantic/src/node.rs
Labels: internal

#6330 Replace `Formatter<PyFormatContext<'_>>` with `PyFormatter`
  crates/ruff_python_formatter/generate.py
  crates/ruff_python_formatter/src/comments/format.rs
  crates/ruff_python_formatter/src/expression/expr_bin_op.rs
  crates/ruff_python_formatter/src/expression/expr_bool_op.rs
  crates/ruff_python_formatter/src/expression/expr_compare.rs
  crates/ruff_python_formatter/src/expression/expr_dict.rs
  crates/ruff_python_formatter/src/expression/expr_line_magic.rs
  crates/ruff_python_formatter/src/expression/expr_tuple.rs
  crates/ruff_python_formatter/src/expression/expr_yield.rs
  crates/ruff_python_formatter/src/expression/mod.rs
  crates/ruff_python_formatter/src/expression/number.rs
  crates/ruff_python_formatter/src/expression/string.rs
  crates/ruff_python_formatter/src/generated.rs
  crates/ruff_python_formatter/src/other/comprehension.rs
  crates/ruff_python_formatter/src/other/parameters.rs
  crates/ruff_python_formatter/src/statement/mod.rs
  crates/ruff_python_formatter/src/statement/stmt_assign.rs
  crates/ruff_python_formatter/src/statement/stmt_for.rs
  crates/ruff_python_formatter/src/statement/stmt_function_def.rs
  crates/ruff_python_formatter/src/statement/stmt_line_magic.rs
  crates/ruff_python_formatter/src/statement/stmt_try.rs
  crates/ruff_python_formatter/src/statement/stmt_with.rs
  crates/ruff_python_formatter/src/type_param/type_param_clause.rs
Labels: internal, formatter

#6331 Formatter: Add SourceType to context to enable special formatting for stub files
  crates/ruff/src/rules/pycodestyle/rules/type_comparison.rs
  crates/ruff_benchmark/benches/formatter.rs
  crates/ruff_cli/src/lib.rs
  crates/ruff_dev/src/format_dev.rs
  crates/ruff_python_ast/src/lib.rs
  crates/ruff_python_formatter/Cargo.toml
  crates/ruff_python_formatter/src/cli.rs
  crates/ruff_python_formatter/src/lib.rs
  crates/ruff_python_formatter/src/main.rs
  crates/ruff_python_formatter/src/options.rs
  crates/ruff_python_formatter/tests/fixtures.rs
  crates/ruff_wasm/src/lib.rs
Labels: formatter

#6340 Add missing enable check for `bad-string-format-character`
  crates/ruff/src/checkers/ast/analyze/expression.rs
  crates/ruff/src/rules/pylint/snapshots/ruff__rules__pylint__tests__PLE1300_bad_string_format_character.py.snap
Labels: bug

#6341 Rename `CommentPlacement#then_with` to `or_else`
  crates/ruff_python_formatter/src/comments/placement.rs
  crates/ruff_python_formatter/src/comments/visitor.rs
Labels: internal

#6324 Flag `comparison-with-itself` on builtin calls
  crates/ruff/resources/test/fixtures/pylint/comparison_with_itself.py
  crates/ruff/src/rules/pylint/rules/comparison_with_itself.rs
  crates/ruff/src/rules/pylint/snapshots/ruff__rules__pylint__tests__PLR0124_comparison_with_itself.py.snap
Labels: rule

#6343 More similarity index digits
  crates/ruff_dev/src/format_dev.rs
Labels: formatter

#6342 Avoid auto-fixing UP032 if comments are present around format call arguments
  crates/ruff/resources/test/fixtures/pyupgrade/UP032_0.py
  crates/ruff/src/rules/pyupgrade/rules/f_strings.rs
  crates/ruff/src/rules/pyupgrade/snapshots/ruff__rules__pyupgrade__tests__UP032_0.py.snap
Labels: bug, autofix

#6346 Remove `ruff_python_ast` prefix in fixes.rs
  crates/ruff/src/rules/flake8_comprehensions/fixes.rs
Labels: internal

#6350 Avoid panic with positional-only arguments in `PYI019`
  crates/ruff/resources/test/fixtures/flake8_pyi/PYI019.py
  crates/ruff/resources/test/fixtures/flake8_pyi/PYI019.pyi
  crates/ruff/src/rules/flake8_pyi/rules/custom_type_var_return_type.rs
  crates/ruff/src/rules/flake8_pyi/snapshots/ruff__rules__flake8_pyi__tests__PYI019_PYI019.py.snap
  crates/ruff/src/rules/flake8_pyi/snapshots/ruff__rules__flake8_pyi__tests__PYI019_PYI019.pyi.snap
Labels: bug

#6361 Respect typing_extensions imports of Annotated for B006.
  crates/ruff/resources/test/fixtures/flake8_bugbear/B006_B008.py
  crates/ruff/src/rules/flake8_bugbear/snapshots/ruff__rules__flake8_bugbear__tests__B006_B006_B008.py.snap
  crates/ruff_python_semantic/src/analyze/typing.rs
Labels: bug

#6375 Avoid allocation in no-signature
  crates/ruff/src/rules/pydocstyle/rules/no_signature.rs
Labels: internal

#6223 Add `DTZ003` and `DTZ004` docs
  crates/ruff/src/rules/flake8_datetimez/rules/call_datetime_today.rs
  crates/ruff/src/rules/flake8_datetimez/rules/call_datetime_utcfromtimestamp.rs
  crates/ruff/src/rules/flake8_datetimez/rules/call_datetime_utcnow.rs
  crates/ruff/src/rules/flake8_datetimez/rules/call_datetime_without_tzinfo.rs
Labels: documentation

#6362 Add `PT011` and `PT012` docs
  crates/ruff/src/rules/flake8_pytest_style/rules/raises.rs
Labels: documentation

#6373 Add documentation to `subprocess-with[out]-shell-equals-true` rules
  crates/ruff/src/rules/flake8_bandit/rules/shell_injection.rs
Labels: documentation

#6345 Store expression hierarchy in semantic model snapshots
  crates/ruff/src/checkers/ast/mod.rs
  crates/ruff/src/rules/flake8_pytest_style/rules/assertion.rs
  crates/ruff/src/rules/pandas_vet/rules/inplace_argument.rs
  crates/ruff/src/rules/pylint/rules/compare_to_empty_string.rs
  crates/ruff_python_semantic/src/model.rs
Labels: internal

#6376 Use `parenthesized_with_dangling_comments` in arguments formatter
  crates/ruff_python_formatter/resources/test/fixtures/ruff/expression/call.py
  crates/ruff_python_formatter/src/other/arguments.rs
  crates/ruff_python_formatter/tests/snapshots/format@expression__call.py.snap
Labels: formatter

#6380 Avoid hard line break after dangling open-parenthesis comments
  crates/ruff_python_formatter/resources/test/fixtures/ruff/expression/list.py
  crates/ruff_python_formatter/src/comments/format.rs
  crates/ruff_python_formatter/src/comments/mod.rs
  crates/ruff_python_formatter/src/expression/parentheses.rs
  crates/ruff_python_formatter/tests/snapshots/black_compatibility@simple_cases__multiline_consecutive_open_parentheses_ignore.py.snap
  crates/ruff_python_formatter/tests/snapshots/format@expression__list.py.snap
Labels: formatter

#6348 Make the `statement` vector private on `SemanticModel`
  crates/ruff/src/checkers/ast/analyze/deferred_scopes.rs
  crates/ruff/src/checkers/ast/mod.rs
  crates/ruff/src/rules/flake8_pyi/rules/unused_private_type_definition.rs
  crates/ruff/src/rules/flake8_type_checking/rules/runtime_import_in_type_checking_block.rs
  crates/ruff/src/rules/flake8_type_checking/rules/typing_only_runtime_import.rs
  crates/ruff/src/rules/perflint/rules/unnecessary_list_cast.rs
  crates/ruff/src/rules/pyflakes/rules/unused_import.rs
  crates/ruff/src/rules/pyflakes/rules/unused_variable.rs
  crates/ruff_python_semantic/src/binding.rs
  crates/ruff_python_semantic/src/model.rs
Labels: internal

#6393 Remove `RefEquality`
  crates/ruff/src/rules/pyupgrade/rules/yield_in_for_loop.rs
  crates/ruff_python_ast/src/types.rs
  crates/ruff_python_semantic/src/statements.rs
Labels: internal

#6374 Use dedicated AST nodes on `MemberKind`
  crates/ruff/src/checkers/ast/analyze/deferred_scopes.rs
  crates/ruff/src/checkers/ast/mod.rs
  crates/ruff/src/docstrings/extraction.rs
  crates/ruff/src/rules/flake8_annotations/fixes.rs
  crates/ruff/src/rules/flake8_annotations/helpers.rs
  crates/ruff/src/rules/flake8_annotations/rules/definition.rs
  crates/ruff/src/rules/flake8_pyi/rules/iter_method_return_iterable.rs
  crates/ruff/src/rules/pydocstyle/helpers.rs
  crates/ruff/src/rules/pydocstyle/rules/blank_before_after_class.rs
  crates/ruff/src/rules/pydocstyle/rules/blank_before_after_function.rs
  crates/ruff/src/rules/pydocstyle/rules/capitalized.rs
  crates/ruff/src/rules/pydocstyle/rules/if_needed.rs
  crates/ruff/src/rules/pydocstyle/rules/multi_line_summary_start.rs
  crates/ruff/src/rules/pydocstyle/rules/no_signature.rs
  crates/ruff/src/rules/pydocstyle/rules/non_imperative_mood.rs
  crates/ruff/src/rules/pydocstyle/rules/not_missing.rs
  crates/ruff/src/rules/pydocstyle/rules/sections.rs
  crates/ruff/src/rules/pyflakes/rules/yield_outside_function.rs
  crates/ruff_python_ast/src/cast.rs
  crates/ruff_python_ast/src/identifier.rs
  crates/ruff_python_ast/src/lib.rs
  crates/ruff_python_semantic/src/analyze/visibility.rs
  crates/ruff_python_semantic/src/definition.rs
Labels: internal

#6322 Avoid omitting parentheses for trailing attributes on call expressions
  crates/ruff_python_formatter/resources/test/fixtures/ruff/expression/compare.py
  crates/ruff_python_formatter/src/expression/mod.rs
  crates/ruff_python_formatter/tests/snapshots/format@expression__compare.py.snap
Labels: formatter

#6394 Fix formatting of chained boolean operations
  crates/ruff_python_formatter/resources/test/fixtures/ruff/expression/boolean_operation.py
  crates/ruff_python_formatter/src/expression/expr_bool_op.rs
  crates/ruff_python_formatter/src/expression/mod.rs
  crates/ruff_python_formatter/tests/snapshots/format@expression__binary_implicit_string.py.snap
  crates/ruff_python_formatter/tests/snapshots/format@expression__boolean_operation.py.snap
Labels: formatter

#6379 Rename `JoinedStr` to `FString` in the AST
  crates/ruff/src/checkers/ast/analyze/expression.rs
  crates/ruff/src/checkers/ast/mod.rs
  crates/ruff/src/rules/flake8_bandit/rules/hardcoded_sql_expression.rs
  crates/ruff/src/rules/flake8_bugbear/rules/f_string_docstring.rs
  crates/ruff/src/rules/flake8_bugbear/rules/useless_expression.rs
  crates/ruff/src/rules/flake8_errmsg/rules/string_in_exception.rs
  crates/ruff/src/rules/flake8_gettext/rules/f_string_in_gettext_func_call.rs
  crates/ruff/src/rules/flake8_implicit_str_concat/rules/explicit.rs
  crates/ruff/src/rules/flake8_logging_format/rules/logging_call.rs
  crates/ruff/src/rules/flake8_pytest_style/rules/helpers.rs
  crates/ruff/src/rules/flynt/helpers.rs
  crates/ruff/src/rules/flynt/rules/static_join_to_fstring.rs
  crates/ruff/src/rules/pyflakes/rules/f_string_missing_placeholders.rs
  crates/ruff/src/rules/pyflakes/rules/repeated_keys.rs
  crates/ruff/src/rules/pylint/rules/assert_on_string_literal.rs
  crates/ruff/src/rules/pylint/rules/invalid_envvar_default.rs
  crates/ruff/src/rules/pylint/rules/invalid_envvar_value.rs
  crates/ruff/src/rules/pylint/rules/single_string_slots.rs
  crates/ruff/src/rules/pyupgrade/rules/native_literals.rs
  crates/ruff/src/rules/pyupgrade/rules/printf_string_formatting.rs
  crates/ruff/src/rules/pyupgrade/rules/unnecessary_encode_utf8.rs
  crates/ruff/src/rules/ruff/rules/invalid_index_type.rs
  crates/ruff/src/rules/ruff/rules/unreachable.rs
  crates/ruff/src/rules/tryceratops/rules/raise_vanilla_args.rs
  crates/ruff_python_ast/src/comparable.rs
  crates/ruff_python_ast/src/helpers.rs
  crates/ruff_python_ast/src/node.rs
  crates/ruff_python_ast/src/nodes.rs
  crates/ruff_python_ast/src/relocate.rs
  crates/ruff_python_ast/src/visitor.rs
  crates/ruff_python_ast/src/visitor/preorder.rs
  crates/ruff_python_codegen/src/generator.rs
  crates/ruff_python_formatter/src/expression/expr_f_string.rs
  crates/ruff_python_formatter/src/expression/mod.rs
  crates/ruff_python_formatter/src/expression/string.rs
  crates/ruff_python_formatter/src/generated.rs
  crates/ruff_python_parser/src/snapshots/ruff_python_parser__parser__tests__parse_f_string.snap
  crates/ruff_python_parser/src/snapshots/ruff_python_parser__parser__tests__try.snap
  crates/ruff_python_parser/src/snapshots/ruff_python_parser__parser__tests__try_star.snap
  crates/ruff_python_parser/src/snapshots/ruff_python_parser__string__tests__fstring_constant_range.snap
  crates/ruff_python_parser/src/snapshots/ruff_python_parser__string__tests__fstring_escaped_character.snap
  crates/ruff_python_parser/src/snapshots/ruff_python_parser__string__tests__fstring_escaped_newline.snap
  crates/ruff_python_parser/src/snapshots/ruff_python_parser__string__tests__fstring_line_continuation.snap
  crates/ruff_python_parser/src/snapshots/ruff_python_parser__string__tests__fstring_parse_self_documenting_format.snap
  crates/ruff_python_parser/src/snapshots/ruff_python_parser__string__tests__fstring_unescaped_newline.snap
  crates/ruff_python_parser/src/snapshots/ruff_python_parser__string__tests__parse_f_string_concat_1.snap
  crates/ruff_python_parser/src/snapshots/ruff_python_parser__string__tests__parse_f_string_concat_2.snap
  crates/ruff_python_parser/src/snapshots/ruff_python_parser__string__tests__parse_f_string_concat_3.snap
  crates/ruff_python_parser/src/snapshots/ruff_python_parser__string__tests__parse_fstring_nested_spec.snap
  crates/ruff_python_parser/src/snapshots/ruff_python_parser__string__tests__parse_fstring_not_nested_spec.snap
  crates/ruff_python_parser/src/snapshots/ruff_python_parser__string__tests__parse_u_f_string_concat_1.snap
  crates/ruff_python_parser/src/snapshots/ruff_python_parser__string__tests__parse_u_f_string_concat_2.snap
  crates/ruff_python_parser/src/snapshots/ruff_python_parser__string__tests__raw_fstring.snap
  crates/ruff_python_parser/src/snapshots/ruff_python_parser__string__tests__triple_quoted_raw_fstring.snap
  crates/ruff_python_parser/src/string.rs
  crates/ruff_python_semantic/src/analyze/type_inference.rs
Labels: internal

#6381 Fixup comment handling on opening parenthesis in function definition
  crates/ruff_python_formatter/resources/test/fixtures/ruff/statement/function.py
  crates/ruff_python_formatter/src/comments/placement.rs
  crates/ruff_python_formatter/src/other/parameters.rs
  crates/ruff_python_formatter/tests/snapshots/format@statement__function.py.snap
Labels: formatter

#6397 Assume Python 3.8 instead of 3.10 for target version
  BREAKING_CHANGES.md
  README.md
  docs/configuration.md
Labels: breaking, configuration

#6402 Add a `with_dangling_comments` to the parenthesized formatter
  crates/ruff_python_formatter/src/expression/expr_dict.rs
  crates/ruff_python_formatter/src/expression/expr_dict_comp.rs
  crates/ruff_python_formatter/src/expression/expr_generator_exp.rs
  crates/ruff_python_formatter/src/expression/expr_list.rs
  crates/ruff_python_formatter/src/expression/expr_list_comp.rs
  crates/ruff_python_formatter/src/expression/expr_set.rs
  crates/ruff_python_formatter/src/expression/expr_set_comp.rs
  crates/ruff_python_formatter/src/expression/expr_tuple.rs
  crates/ruff_python_formatter/src/expression/parentheses.rs
  crates/ruff_python_formatter/src/other/arguments.rs
  crates/ruff_python_formatter/src/other/parameters.rs
Labels: internal, formatter

#6401 Avoid attempting to fix `.format(...)` calls with too-few-arguments
  crates/ruff/resources/test/fixtures/pyupgrade/UP030_0.py
  crates/ruff/resources/test/fixtures/pyupgrade/UP030_1.py
  crates/ruff/resources/test/fixtures/pyupgrade/UP030_2.py
  crates/ruff/src/checkers/ast/analyze/expression.rs
  crates/ruff/src/rules/pyupgrade/mod.rs
  crates/ruff/src/rules/pyupgrade/rules/format_literals.rs
  crates/ruff/src/rules/pyupgrade/snapshots/ruff__rules__pyupgrade__tests__UP030_0.py.snap
  crates/ruff/src/rules/pyupgrade/snapshots/ruff__rules__pyupgrade__tests__UP030_2.py.snap
Labels: bug

#6404 Rename `ArgumentSeparator` to `ParameterSeparator`
  crates/ruff_python_formatter/src/comments/placement.rs
  crates/ruff_python_formatter/src/other/parameters.rs
Labels: formatter

#6314 Add support for simple generic type variables to UP040
  crates/ruff/resources/test/fixtures/pyupgrade/UP040.py
  crates/ruff/src/rules/pyupgrade/rules/use_pep695_type_alias.rs
  crates/ruff/src/rules/pyupgrade/snapshots/ruff__rules__pyupgrade__tests__non_pep695_type_alias_py312.snap
Labels: autofix

#6386 Fix zulip unstable formatting with end-of-line comments
  crates/ruff_python_formatter/resources/test/fixtures/ruff/expression/binary.py
  crates/ruff_python_formatter/resources/test/fixtures/ruff/statement/delete.py
  crates/ruff_python_formatter/src/builders.rs
  crates/ruff_python_formatter/tests/snapshots/format@expression__binary.py.snap
  crates/ruff_python_formatter/tests/snapshots/format@expression__call.py.snap
  crates/ruff_python_formatter/tests/snapshots/format@expression__dict.py.snap
  crates/ruff_python_formatter/tests/snapshots/format@expression__lambda.py.snap
  crates/ruff_python_formatter/tests/snapshots/format@expression__list.py.snap
  crates/ruff_python_formatter/tests/snapshots/format@statement__delete.py.snap
  crates/ruff_python_formatter/tests/snapshots/format@statement__function.py.snap
  crates/ruff_python_formatter/tests/snapshots/format@statement__raise.py.snap
Labels: formatter

#6389 Expand parents whenever open-parenthesis comments are present
  crates/ruff_python_formatter/src/comments/format.rs
  crates/ruff_python_formatter/tests/snapshots/black_compatibility@simple_cases__multiline_consecutive_open_parentheses_ignore.py.snap
  crates/ruff_python_formatter/tests/snapshots/black_compatibility@simple_cases__torture.py.snap
  crates/ruff_python_formatter/tests/snapshots/format@expression__call.py.snap
  crates/ruff_python_formatter/tests/snapshots/format@expression__dict_comp.py.snap
  crates/ruff_python_formatter/tests/snapshots/format@expression__list.py.snap
  crates/ruff_python_formatter/tests/snapshots/format@statement__function.py.snap
Labels: formatter

#6286 Add formatting for `StmtMatch`
  crates/ruff_python_formatter/resources/test/fixtures/ruff/statement/match.py
  crates/ruff_python_formatter/src/comments/placement.rs
  crates/ruff_python_formatter/src/comments/visitor.rs
  crates/ruff_python_formatter/src/other/match_case.rs
  crates/ruff_python_formatter/src/statement/stmt_match.rs
  crates/ruff_python_formatter/tests/snapshots/black_compatibility@py_310__pattern_matching_complex.py.snap
  crates/ruff_python_formatter/tests/snapshots/black_compatibility@py_310__pattern_matching_extras.py.snap
  crates/ruff_python_formatter/tests/snapshots/black_compatibility@py_310__pattern_matching_generic.py.snap
  crates/ruff_python_formatter/tests/snapshots/black_compatibility@py_310__pattern_matching_simple.py.snap
  crates/ruff_python_formatter/tests/snapshots/black_compatibility@py_310__pattern_matching_style.py.snap
  crates/ruff_python_formatter/tests/snapshots/black_compatibility@py_310__remove_newline_after_match.py.snap
  crates/ruff_python_formatter/tests/snapshots/format@statement__match.py.snap
Labels: formatter

#6403 Move `empty_parenthesized` into the `parentheses.rs`
  crates/ruff_python_formatter/src/builders.rs
  crates/ruff_python_formatter/src/expression/expr_dict.rs
  crates/ruff_python_formatter/src/expression/expr_list.rs
  crates/ruff_python_formatter/src/expression/expr_tuple.rs
  crates/ruff_python_formatter/src/expression/parentheses.rs
  crates/ruff_python_formatter/src/other/arguments.rs
  crates/ruff_python_formatter/src/other/parameters.rs
Labels: formatter

#6430 Improve documentation for `PLE1300`
  crates/ruff/src/rules/pylint/rules/bad_string_format_character.rs
Labels: documentation

#6413 Treat comments on open parentheses in return annotations as dangling
  crates/ruff_python_formatter/resources/test/fixtures/ruff/statement/function.py
  crates/ruff_python_formatter/src/comments/placement.rs
  crates/ruff_python_formatter/src/statement/stmt_function_def.rs
  crates/ruff_python_formatter/tests/snapshots/format@statement__function.py.snap
Labels: formatter

#6435 Fix false-positive in submodule resolution
  crates/ruff/resources/test/fixtures/pyflakes/F401_0.py
  crates/ruff/resources/test/fixtures/pyflakes/F823.py
  crates/ruff/src/rules/pyflakes/snapshots/ruff__rules__pyflakes__tests__F401_F401_0.py.snap
  crates/ruff/src/rules/pyupgrade/rules/use_pep695_type_alias.rs
  crates/ruff_python_semantic/src/binding.rs
  crates/ruff_python_semantic/src/model.rs
Labels: bug

#6358 Add support for help end IPython escape commands
  crates/ruff_python_parser/src/lexer.rs
  crates/ruff_python_parser/src/parser.rs
  crates/ruff_python_parser/src/python.lalrpop
  crates/ruff_python_parser/src/python.rs
  crates/ruff_python_parser/src/snapshots/ruff_python_parser__parser__tests__jupyter_magic.snap
  crates/ruff_python_parser/src/token.rs
Labels: parser

#6422 Add `enter` and `leave_node` methods to Preoder visitor
  crates/ruff_python_ast/src/visitor/preorder.rs
  crates/ruff_python_formatter/src/comments/visitor.rs
Labels: internal

#6395 Rename `Magic*` to `IpyEscape*`
  crates/ruff/resources/test/fixtures/jupyter/ipy_escape_command.ipynb
  crates/ruff/resources/test/fixtures/jupyter/ipy_escape_command_expected.ipynb
  crates/ruff/src/jupyter/notebook.rs
  crates/ruff/src/jupyter/snapshots/ruff__jupyter__notebook__tests__ipy_escape_command.snap
  crates/ruff/src/rules/ruff/rules/unreachable.rs
  crates/ruff_python_ast/src/comparable.rs
  crates/ruff_python_ast/src/helpers.rs
  crates/ruff_python_ast/src/node.rs
  crates/ruff_python_ast/src/nodes.rs
  crates/ruff_python_ast/src/relocate.rs
  crates/ruff_python_ast/src/visitor.rs
  crates/ruff_python_ast/src/visitor/preorder.rs
  crates/ruff_python_codegen/src/generator.rs
  crates/ruff_python_formatter/src/expression/expr_ipy_escape_command.rs
  crates/ruff_python_formatter/src/expression/expr_line_magic.rs
  crates/ruff_python_formatter/src/expression/mod.rs
  crates/ruff_python_formatter/src/generated.rs
  crates/ruff_python_formatter/src/statement/mod.rs
  crates/ruff_python_formatter/src/statement/stmt_ipy_escape_command.rs
  crates/ruff_python_formatter/src/statement/stmt_line_magic.rs
  crates/ruff_python_parser/src/lexer.rs
  crates/ruff_python_parser/src/parser.rs
  crates/ruff_python_parser/src/python.lalrpop
  crates/ruff_python_parser/src/python.rs
  crates/ruff_python_parser/src/snapshots/ruff_python_parser__parser__tests__ipython_escape_commands.snap
  crates/ruff_python_parser/src/token.rs
Labels: internal

#6448 Use latest Python version by default in tests
  crates/ruff/src/rules/flake8_bugbear/mod.rs
  crates/ruff/src/rules/flake8_pyi/snapshots/ruff__rules__flake8_pyi__tests__PYI050_PYI050.py.snap
  crates/ruff/src/rules/flake8_pyi/snapshots/ruff__rules__flake8_pyi__tests__PYI050_PYI050.pyi.snap
  crates/ruff/src/rules/flake8_use_pathlib/mod.rs
  crates/ruff/src/rules/isort/snapshots/ruff__rules__isort__tests__if_elif_else.py.snap
  crates/ruff/src/rules/perflint/mod.rs
  crates/ruff/src/rules/pylint/mod.rs
  crates/ruff/src/rules/pyupgrade/mod.rs
  crates/ruff/src/rules/pyupgrade/snapshots/ruff__rules__pyupgrade__tests__UP040.py.snap
  crates/ruff/src/rules/ruff/mod.rs
  crates/ruff/src/settings/mod.rs
  crates/ruff/src/settings/types.rs
Labels: internal

#6456 Improve counting of message arguments when msg is provided as a keyword
  crates/ruff/resources/test/fixtures/pylint/logging_too_few_args.py
  crates/ruff/resources/test/fixtures/pylint/logging_too_many_args.py
  crates/ruff/src/rules/pylint/rules/logging.rs
  crates/ruff_python_ast/src/nodes.rs
Labels: bug

#6457 Avoid applying `PYI055` to runtime-evaluated annotations
  crates/ruff/resources/test/fixtures/flake8_pyi/PYI055.py
  crates/ruff/resources/test/fixtures/flake8_pyi/PYI055.pyi
  crates/ruff/src/rules/flake8_pyi/rules/unnecessary_type_union.rs
  crates/ruff/src/rules/flake8_pyi/snapshots/ruff__rules__flake8_pyi__tests__PYI055_PYI055.py.snap
  crates/ruff/src/rules/flake8_pyi/snapshots/ruff__rules__flake8_pyi__tests__PYI055_PYI055.pyi.snap
Labels: bug

#6458 Document `FormatSpec` fields
  crates/ruff_python_literal/src/format.rs
Labels: documentation

#6451 Use SimpleTokenizer in `max_lines`
  crates/ruff_python_formatter/src/comments/placement.rs
Labels: internal

#6426 Add `AnyNodeRef.visit_preorder`
  crates/ruff_python_ast/src/node.rs
  crates/ruff_python_ast/src/visitor/preorder.rs
Labels: internal

#6441 Preserve dangling f-string comments
  crates/ruff_python_formatter/resources/test/fixtures/ruff/expression/fstring.py
  crates/ruff_python_formatter/resources/test/fixtures/ruff/expression/joined_string.py
  crates/ruff_python_formatter/src/comments/placement.rs
  crates/ruff_python_formatter/src/comments/visitor.rs
  crates/ruff_python_formatter/tests/snapshots/format@expression__fstring.py.snap
  crates/ruff_python_formatter/tests/snapshots/format@expression__joined_string.py.snap
Labels: formatter

#6178 Track formatting all comments
  crates/ruff_python_formatter/src/comments/mod.rs
  crates/ruff_python_formatter/src/expression/expr_formatted_value.rs
  crates/ruff_python_formatter/src/lib.rs
  crates/ruff_python_formatter/src/other/match_case.rs
Labels: formatter

#6420 Formatter: Add test cases for comments after opening parentheses
  crates/ruff_python_formatter/resources/test/fixtures/ruff/parentheses/call_chains.py
  crates/ruff_python_formatter/resources/test/fixtures/ruff/parentheses/nested.py
  crates/ruff_python_formatter/resources/test/fixtures/ruff/parentheses/opening_parentheses_comment_empty.py
  crates/ruff_python_formatter/resources/test/fixtures/ruff/parentheses/opening_parentheses_comment_value.py
  crates/ruff_python_formatter/tests/snapshots/format@parentheses__call_chains.py.snap
  crates/ruff_python_formatter/tests/snapshots/format@parentheses__nested.py.snap
  crates/ruff_python_formatter/tests/snapshots/format@parentheses__opening_parentheses_comment_empty.py.snap
  crates/ruff_python_formatter/tests/snapshots/format@parentheses__opening_parentheses_comment_value.py.snap
Labels: formatter

#6131 [`flake8-bugbear`] Add autofix for B006
  crates/ruff/resources/test/fixtures/flake8_bugbear/B006_B008.py
  crates/ruff/src/checkers/ast/analyze/parameters.rs
  crates/ruff/src/checkers/ast/analyze/statement.rs
  crates/ruff/src/rules/flake8_bugbear/rules/mutable_argument_default.rs
  crates/ruff/src/rules/flake8_bugbear/snapshots/ruff__rules__flake8_bugbear__tests__B006_B006_B008.py.snap
  crates/ruff/src/rules/flake8_bugbear/snapshots/ruff__rules__flake8_bugbear__tests__B008_B006_B008.py.snap
Labels: rule

#6468 Respect scoping rules when identifying builtins
  crates/ruff/resources/test/fixtures/pycodestyle/E721.py
  crates/ruff/src/rules/pycodestyle/snapshots/ruff__rules__pycodestyle__tests__E721_E721.py.snap
  crates/ruff_python_semantic/src/model.rs
Labels: bug

#6482 Extend `target-version` documentation
  crates/ruff/src/settings/options.rs
  ruff.schema.json
Labels: documentation

#6490 Allow `os._exit` accesses in `SLF001`
  crates/ruff/resources/test/fixtures/flake8_self/SLF001.py
  crates/ruff/src/rules/flake8_self/rules/private_member_access.rs
  crates/ruff/src/rules/pylint/rules/logging.rs
Labels: bug

#6487 [`pylint`] Implement `subprocess-run-check` (`W1510`)
  crates/ruff/resources/test/fixtures/pylint/subprocess_run_without_check.py
  crates/ruff/src/checkers/ast/analyze/expression.rs
  crates/ruff/src/codes.rs
  crates/ruff/src/rules/pylint/mod.rs
  crates/ruff/src/rules/pylint/rules/mod.rs
  crates/ruff/src/rules/pylint/rules/subprocess_run_without_check.rs
  crates/ruff/src/rules/pylint/snapshots/ruff__rules__pylint__tests__PLW1510_subprocess_run_without_check.py.snap
  ruff.schema.json
Labels: rule

#6486 [`pylint`] Implement `bad-dunder-name` (`W3201`)
  crates/ruff/resources/test/fixtures/pylint/bad_dunder_method_name.py
  crates/ruff/src/checkers/ast/analyze/statement.rs
  crates/ruff/src/codes.rs
  crates/ruff/src/rules/pylint/mod.rs
  crates/ruff/src/rules/pylint/rules/bad_dunder_method_name.rs
  crates/ruff/src/rules/pylint/rules/mod.rs
  crates/ruff/src/rules/pylint/snapshots/ruff__rules__pylint__tests__PLW3201_bad_dunder_method_name.py.snap
  ruff.schema.json
Labels: rule

#6491 Respect tab width in line-length heuristic
  crates/ruff/resources/test/fixtures/pycodestyle/E501_2.py
  crates/ruff/src/line_width.rs
  crates/ruff/src/rules/pycodestyle/helpers.rs
  crates/ruff/src/rules/pycodestyle/mod.rs
  crates/ruff/src/rules/pycodestyle/snapshots/ruff__rules__pycodestyle__tests__tab_size_1.snap
  crates/ruff/src/rules/pycodestyle/snapshots/ruff__rules__pycodestyle__tests__tab_size_2.snap
  crates/ruff/src/rules/pycodestyle/snapshots/ruff__rules__pycodestyle__tests__tab_size_4.snap
  crates/ruff/src/rules/pycodestyle/snapshots/ruff__rules__pycodestyle__tests__tab_size_8.snap
Labels: bug

#6383 Enable short URLs in the playground
  playground/README.md
  playground/api/.dev.vars
  playground/api/README.md
  playground/api/package-lock.json
  playground/api/package.json
  playground/api/src/index.ts
  playground/api/tsconfig.json
  playground/api/wrangler.toml
  playground/package-lock.json
  playground/package.json
  playground/src/Editor/Editor.tsx
  playground/src/Editor/api.ts
  playground/src/Editor/settings.ts
Labels: playground

#6492 Respect dummy-variable-rgx for unused bound exceptions
  crates/ruff/resources/test/fixtures/pyflakes/F841_0.py
  crates/ruff/src/checkers/ast/analyze/bindings.rs
  crates/ruff/src/rules/pyflakes/rules/unused_variable.rs
  crates/ruff/src/rules/pyflakes/snapshots/ruff__rules__pyflakes__tests__f841_dummy_variable_rgx.snap
Labels: bug

#6493 Ensure that B006 autofix respects docstrings
  crates/ruff/resources/test/fixtures/flake8_bugbear/B006_B008.py
  crates/ruff/src/checkers/ast/analyze/statement.rs
  crates/ruff/src/rules/flake8_bugbear/rules/mutable_argument_default.rs
  crates/ruff/src/rules/flake8_bugbear/snapshots/ruff__rules__flake8_bugbear__tests__B006_B006_B008.py.snap
Labels: bug, autofix

#6494 Force parentheses for named expressions in more contexts
  crates/ruff_python_formatter/resources/test/fixtures/ruff/expression/named_expr.py
  crates/ruff_python_formatter/src/expression/expr_named_expr.rs
  crates/ruff_python_formatter/tests/snapshots/format@expression__named_expr.py.snap
Labels: formatter

#6488 Avoid breaking call chains unnecessarily
  crates/ruff_python_formatter/resources/test/fixtures/ruff/parentheses/call_chains.py
  crates/ruff_python_formatter/src/expression/expr_attribute.rs
  crates/ruff_python_formatter/tests/snapshots/format@parentheses__call_chains.py.snap
Labels: formatter

#6360 Add formatting for `MatchCase`
  crates/ruff_python_formatter/resources/test/fixtures/ruff/statement/match.py
  crates/ruff_python_formatter/src/comments/placement.rs
  crates/ruff_python_formatter/src/other/match_case.rs
  crates/ruff_python_formatter/src/pattern/mod.rs
  crates/ruff_python_formatter/src/statement/stmt_match.rs
  crates/ruff_python_formatter/tests/snapshots/black_compatibility@py_310__pattern_matching_complex.py.snap
  crates/ruff_python_formatter/tests/snapshots/black_compatibility@py_310__pattern_matching_extras.py.snap
  crates/ruff_python_formatter/tests/snapshots/black_compatibility@py_310__pattern_matching_simple.py.snap
  crates/ruff_python_formatter/tests/snapshots/black_compatibility@py_310__remove_newline_after_match.py.snap
  crates/ruff_python_formatter/tests/snapshots/format@statement__match.py.snap
Labels: formatter

#6508 Fix typo in MeasureMode comment
  crates/ruff_formatter/src/printer/mod.rs
Labels: internal

#6484 Avoid omitting optional parentheses for argument-less parentheses
  crates/ruff_python_formatter/resources/test/fixtures/ruff/expression/split_empty_brackets.py
  crates/ruff_python_formatter/resources/test/fixtures/ruff/statement/assign.py
  crates/ruff_python_formatter/src/expression/mod.rs
  crates/ruff_python_formatter/src/statement/stmt_assign.rs
  crates/ruff_python_formatter/tests/snapshots/format@expression__compare.py.snap
  crates/ruff_python_formatter/tests/snapshots/format@expression__split_empty_brackets.py.snap
  crates/ruff_python_formatter/tests/snapshots/format@statement__assign.py.snap
Labels: formatter

#6436 Allow return type annotations to use their own parentheses
  crates/ruff_python_formatter/resources/test/fixtures/ruff/statement/function.py
  crates/ruff_python_formatter/resources/test/fixtures/ruff/statement/return_annotation.py
  crates/ruff_python_formatter/src/expression/mod.rs
  crates/ruff_python_formatter/src/expression/parentheses.rs
  crates/ruff_python_formatter/src/statement/stmt_function_def.rs
  crates/ruff_python_formatter/tests/snapshots/black_compatibility@simple_cases__return_annotation_brackets.py.snap
  crates/ruff_python_formatter/tests/snapshots/format@statement__function.py.snap
  crates/ruff_python_formatter/tests/snapshots/format@statement__return_annotation.py.snap
Labels: formatter

#6438 Add test case for walrus operators in return types
  crates/ruff_python_formatter/resources/test/fixtures/ruff/statement/function.py
  crates/ruff_python_formatter/src/expression/expr_named_expr.rs
  crates/ruff_python_formatter/tests/snapshots/format@statement__function.py.snap
Labels: formatter

#6463 Document default behavior of `W505` in setting
  crates/ruff/src/rules/pycodestyle/settings.rs
  ruff.schema.json
Labels: documentation

#6479 Add `PT008` and `PT009` docs
  crates/ruff/src/rules/flake8_pytest_style/rules/assertion.rs
  crates/ruff/src/rules/flake8_pytest_style/rules/patch.rs
Labels: documentation

#6519 Avoid JSON parse error on playground load
  playground/src/Editor/Editor.tsx
  playground/src/Editor/Header.tsx
Labels: playground

#6378 [`flake8-tidy-imports`] Add `TID253`
  crates/ruff/resources/test/fixtures/flake8_tidy_imports/TID253.py
  crates/ruff/src/checkers/ast/analyze/statement.rs
  crates/ruff/src/codes.rs
  crates/ruff/src/rules/flake8_tidy_imports/mod.rs
  crates/ruff/src/rules/flake8_tidy_imports/options.rs
  crates/ruff/src/rules/flake8_tidy_imports/rules/banned_module_level_imports.rs
  crates/ruff/src/rules/flake8_tidy_imports/rules/mod.rs
  crates/ruff/src/rules/flake8_tidy_imports/settings.rs
  crates/ruff/src/rules/flake8_tidy_imports/snapshots/ruff__rules__flake8_tidy_imports__tests__banned_module_level_imports.snap
  ruff.schema.json
Labels: rule

#6526 Use top-level semantic detection for E402
  crates/ruff/resources/test/fixtures/pycodestyle/E402.py
  crates/ruff/src/checkers/ast/analyze/statement.rs
  crates/ruff/src/rules/pycodestyle/rules/imports.rs
  crates/ruff/src/rules/pycodestyle/snapshots/ruff__rules__pycodestyle__tests__E402_E402.py.snap
Labels: bug

#6520 Clarifying `target-version` in `flake8-future-annotations` docs
  crates/ruff/src/rules/flake8_future_annotations/rules/future_required_type_annotation.rs
  crates/ruff/src/rules/flake8_future_annotations/rules/future_rewritable_type_annotation.rs
  crates/ruff/src/rules/pylint/rules/too_many_arguments.rs
  crates/ruff/src/rules/pylint/rules/too_many_branches.rs
  crates/ruff/src/rules/pylint/rules/too_many_return_statements.rs
  crates/ruff/src/rules/pylint/rules/too_many_statements.rs
Labels: documentation

#6527 Use a unified policy abstraction for the `flake8-tidy-imports` rules
  crates/ruff/src/checkers/ast/analyze/statement.rs
  crates/ruff/src/rules/flake8_tidy_imports/matchers.rs
  crates/ruff/src/rules/flake8_tidy_imports/mod.rs
  crates/ruff/src/rules/flake8_tidy_imports/rules/banned_api.rs
  crates/ruff/src/rules/flake8_tidy_imports/rules/banned_module_level_imports.rs
Labels: internal

#6523 importer: skip whitespace between comments at start of file
  crates/ruff/resources/test/fixtures/isort/required_imports/comments_and_newlines.py
  crates/ruff/src/importer/insertion.rs
  crates/ruff/src/rules/isort/mod.rs
  crates/ruff/src/rules/isort/snapshots/ruff__rules__isort__tests__required_import_comments_and_newlines.py.snap
  crates/ruff/src/rules/isort/snapshots/ruff__rules__isort__tests__required_import_with_alias_comments_and_newlines.py.snap
Labels: isort

#6529 Add docs for `DTZ005` and `DTZ006`
  crates/ruff/src/rules/flake8_datetimez/rules/call_datetime_fromtimestamp.rs
  crates/ruff/src/rules/flake8_datetimez/rules/call_datetime_now_without_tzinfo.rs
Labels: documentation

#6533 Fix minor document errors
  crates/ruff/src/rules/flake8_bandit/rules/suspicious_function_call.rs
  crates/ruff/src/rules/flake8_simplify/rules/ast_bool_op.rs
Labels: documentation

#6538 Support `IfExp` with dual string arms in `invalid-envvar-value`
  crates/ruff/resources/test/fixtures/pylint/invalid_envvar_default.py
  crates/ruff/resources/test/fixtures/pylint/invalid_envvar_value.py
  crates/ruff/src/rules/pylint/rules/invalid_envvar_value.rs
  crates/ruff/src/rules/pylint/rules/invalid_str_return.rs
  crates/ruff/src/rules/pylint/snapshots/ruff__rules__pylint__tests__PLE1507_invalid_envvar_value.py.snap
  crates/ruff_python_semantic/src/analyze/type_inference.rs
Labels: bug

#6542 Add some additional projects to the ecosystem CI
  scripts/check_ecosystem.py
Labels: internal

#6544 Remove unnecessary `expr_name` function
  crates/ruff/src/rules/flake8_comprehensions/rules/helpers.rs
  crates/ruff/src/rules/flake8_comprehensions/rules/unnecessary_call_around_sorted.rs
  crates/ruff/src/rules/flake8_comprehensions/rules/unnecessary_collection_call.rs
  crates/ruff/src/rules/flake8_comprehensions/rules/unnecessary_comprehension.rs
  crates/ruff/src/rules/flake8_comprehensions/rules/unnecessary_double_cast_or_process.rs
  crates/ruff/src/rules/flake8_comprehensions/rules/unnecessary_literal_dict.rs
  crates/ruff/src/rules/flake8_comprehensions/rules/unnecessary_map.rs
  crates/ruff/src/rules/flake8_comprehensions/rules/unnecessary_subscript_reversal.rs
Labels: internal

#6546 Remove `SemanticModel#find_binding`
  crates/ruff/src/rules/flake8_self/rules/private_member_access.rs
  crates/ruff/src/rules/pandas_vet/helpers.rs
  crates/ruff/src/rules/pandas_vet/rules/inplace_argument.rs
  crates/ruff_python_semantic/src/model.rs
Labels: internal

#6547 Remove lex and parsing from formatter benchmark
  Cargo.lock
  crates/ruff_benchmark/Cargo.toml
  crates/ruff_benchmark/benches/formatter.rs
Labels: internal

#6503 Always run check-formatter-ecosystem on main
  .github/workflows/ci.yaml
Labels: internal

#6549 Remove `allow(pedantic)` from formatter
  crates/ruff/src/checkers/ast/analyze/bindings.rs
  crates/ruff/src/line_width.rs
  crates/ruff/src/rules/pep8_naming/settings.rs
  crates/ruff/src/rules/pyupgrade/rules/format_literals.rs
  crates/ruff_formatter/src/arguments.rs
  crates/ruff_formatter/src/buffer.rs
  crates/ruff_formatter/src/builders.rs
  crates/ruff_formatter/src/format_element.rs
  crates/ruff_formatter/src/format_element/document.rs
  crates/ruff_formatter/src/format_element/tag.rs
  crates/ruff_formatter/src/format_extensions.rs
  crates/ruff_formatter/src/formatter.rs
  crates/ruff_formatter/src/group_id.rs
  crates/ruff_formatter/src/lib.rs
  crates/ruff_formatter/src/macros.rs
  crates/ruff_formatter/src/printer/call_stack.rs
  crates/ruff_formatter/src/printer/mod.rs
  crates/ruff_formatter/src/printer/printer_options/mod.rs
  crates/ruff_formatter/src/printer/queue.rs
  crates/ruff_formatter/src/printer/stack.rs
  crates/ruff_python_ast/src/visitor.rs
  crates/ruff_python_literal/src/escape.rs
  crates/ruff_python_parser/src/parser.rs
  crates/ruff_python_parser/src/string.rs
  crates/ruff_python_trivia/src/tokenizer.rs
Labels: internal

#6550 Printer: Reserve buffer upfront
  crates/ruff_formatter/src/lib.rs
  crates/ruff_formatter/src/printer/mod.rs
Labels: formatter

#6551 Override fmt_dangling_comments for frequent nodes
  crates/ruff_formatter/src/lib.rs
  crates/ruff_python_formatter/src/expression/expr_compare.rs
  crates/ruff_python_formatter/src/expression/expr_name.rs
Labels: formatter

#6517 Avoid marking inner-parenthesized comments as dangling bracket comments
  crates/ruff_python_formatter/resources/test/fixtures/ruff/expression/call.py
  crates/ruff_python_formatter/src/comments/placement.rs
  crates/ruff_python_formatter/tests/snapshots/format@expression__call.py.snap
Labels: formatter

#6513 Replace dynamic implicit concatenation detection with parser flag
  crates/ruff/src/checkers/ast/analyze/definitions.rs
  crates/ruff/src/rules/pydocstyle/helpers.rs
  crates/ruff/src/rules/pyupgrade/rules/native_literals.rs
  crates/ruff_python_ast/src/str.rs
  crates/ruff_python_formatter/src/expression/expr_bin_op.rs
  crates/ruff_python_formatter/src/expression/expr_constant.rs
  crates/ruff_python_formatter/src/expression/string.rs
  crates/ruff_python_formatter/src/statement/suite.rs
Labels: internal

#6518 Expand `SimpleTokenizer` to all keywords and single-character tokens
  crates/ruff_python_trivia/src/snapshots/ruff_python_trivia__tokenizer__tests__tokenize_characters.snap
  crates/ruff_python_trivia/src/tokenizer.rs
Labels: internal

#6562 Formatter: Fix posonlyargs for `expr_lambda`
  crates/ruff_python_formatter/resources/test/fixtures/ruff/expression/lambda.py
  crates/ruff_python_formatter/src/expression/expr_lambda.rs
  crates/ruff_python_formatter/tests/snapshots/black_compatibility@py_38__pep_570.py.snap
  crates/ruff_python_formatter/tests/snapshots/format@expression__lambda.py.snap
Labels: formatter

#6567 Clarify FBT documentation and refine rule names
  crates/ruff/src/checkers/ast/analyze/expression.rs
  crates/ruff/src/checkers/ast/analyze/statement.rs
  crates/ruff/src/codes.rs
  crates/ruff/src/registry/rule_set.rs
  crates/ruff/src/rules/flake8_boolean_trap/helpers.rs
  crates/ruff/src/rules/flake8_boolean_trap/mod.rs
  crates/ruff/src/rules/flake8_boolean_trap/rules/boolean_default_value_positional_argument.rs
  crates/ruff/src/rules/flake8_boolean_trap/rules/boolean_positional_value_in_call.rs
  crates/ruff/src/rules/flake8_boolean_trap/rules/boolean_type_hint_positional_argument.rs
  crates/ruff/src/rules/flake8_boolean_trap/rules/check_boolean_default_value_in_function_definition.rs
  crates/ruff/src/rules/flake8_boolean_trap/rules/mod.rs
  crates/ruff/src/rules/flake8_boolean_trap/snapshots/ruff__rules__flake8_boolean_trap__tests__FBT001_FBT.py.snap
  crates/ruff/src/rules/flake8_boolean_trap/snapshots/ruff__rules__flake8_boolean_trap__tests__FBT002_FBT.py.snap
Labels: documentation

#6570 Expand documentation around flake8-type-checking rules for SQLAlchemy
  crates/ruff/resources/test/fixtures/flake8_type_checking/runtime_evaluated_base_classes_4.py
  crates/ruff/src/rules/flake8_type_checking/mod.rs
  crates/ruff/src/rules/flake8_type_checking/rules/typing_only_runtime_import.rs
  crates/ruff/src/rules/flake8_type_checking/settings.rs
  crates/ruff/src/rules/flake8_type_checking/snapshots/ruff__rules__flake8_type_checking__tests__typing-only-standard-library-import_runtime_evaluated_base_classes_4.py.snap
  ruff.schema.json
Labels: documentation

#6554 [`flake8-pytest-style`] Implement `pytest-unittest-raises-assertion` (`PT027`)
  crates/ruff/resources/test/fixtures/flake8_pytest_style/PT027_0.py
  crates/ruff/resources/test/fixtures/flake8_pytest_style/PT027_1.py
  crates/ruff/src/checkers/ast/analyze/expression.rs
  crates/ruff/src/codes.rs
  crates/ruff/src/rules/flake8_pytest_style/mod.rs
  crates/ruff/src/rules/flake8_pytest_style/rules/assertion.rs
  crates/ruff/src/rules/flake8_pytest_style/snapshots/ruff__rules__flake8_pytest_style__tests__PT027_0.snap
  crates/ruff/src/rules/flake8_pytest_style/snapshots/ruff__rules__flake8_pytest_style__tests__PT027_1.snap
  crates/ruff/src/rules/tryceratops/rules/raise_vanilla_args.rs
  ruff.schema.json
Labels: rule

#6559 Formatter ecosystem checks: Use twine instead of build
  scripts/formatter_ecosystem_checks.sh
Labels: internal, formatter

#6531 Add `PT006` and `PT007` docs
  crates/ruff/src/rules/flake8_pytest_style/rules/parametrize.rs
Labels: documentation

#6572 Add deprecated unittest assertions to PT009
  crates/ruff/resources/test/fixtures/flake8_pytest_style/PT009.py
  crates/ruff/src/rules/flake8_pytest_style/rules/unittest_assert.rs
  crates/ruff/src/rules/flake8_pytest_style/snapshots/ruff__rules__flake8_pytest_style__tests__PT009.snap
  crates/ruff/src/rules/pyupgrade/rules/deprecated_unittest_alias.rs
Labels: bug

#6521 Add PT002 ~ PT005 docs
  crates/ruff/src/rules/flake8_pytest_style/rules/fixture.rs
Labels: documentation

#6573 Add regular expression example for `per-file-ignores`
  docs/configuration.md
Labels: documentation

#6578 Avoid unused argument rules when functions call `locals()`
  crates/ruff/resources/test/fixtures/flake8_unused_arguments/ARG.py
  crates/ruff/src/rules/flake8_unused_arguments/rules/unused_arguments.rs
Labels: bug

#6579 Bump rule count to 600+ in the docs
  README.md
  docs/tutorial.md
Labels: documentation

#6580 Import `pytest` in `flake8-pytest-style` docs
  crates/ruff/src/rules/flake8_pytest_style/rules/assertion.rs
  crates/ruff/src/rules/flake8_pytest_style/rules/fixture.rs
  crates/ruff/src/rules/flake8_pytest_style/rules/marks.rs
  crates/ruff/src/rules/flake8_pytest_style/rules/parametrize.rs
  crates/ruff/src/rules/flake8_pytest_style/rules/raises.rs
Labels: documentation

#6507 Indent statements in suppressed ranges
  Cargo.lock
  Cargo.toml
  crates/ruff/Cargo.toml
  crates/ruff_formatter/Cargo.toml
  crates/ruff_python_formatter/Cargo.toml
  crates/ruff_python_formatter/resources/test/fixtures/ruff/.editorconfig
  crates/ruff_python_formatter/resources/test/fixtures/ruff/fmt_on_off/comments.py
  crates/ruff_python_formatter/resources/test/fixtures/ruff/fmt_on_off/fmt_off_docstring.options.json
  crates/ruff_python_formatter/resources/test/fixtures/ruff/fmt_on_off/indent.options.json
  crates/ruff_python_formatter/resources/test/fixtures/ruff/fmt_on_off/indent.py
  crates/ruff_python_formatter/resources/test/fixtures/ruff/fmt_on_off/mixed_space_and_tab.options.json
  crates/ruff_python_formatter/resources/test/fixtures/ruff/fmt_on_off/mixed_space_and_tab.py
  crates/ruff_python_formatter/src/lib.rs
  crates/ruff_python_formatter/src/verbatim.rs
  crates/ruff_python_formatter/tests/snapshots/format@fmt_on_off__comments.py.snap
  crates/ruff_python_formatter/tests/snapshots/format@fmt_on_off__fmt_off_docstring.py.snap
  crates/ruff_python_formatter/tests/snapshots/format@fmt_on_off__indent.py.snap
  crates/ruff_python_formatter/tests/snapshots/format@fmt_on_off__mixed_space_and_tab.py.snap
Labels: formatter

#6590 Replace `inline(always)` with `inline`
  crates/ruff_formatter/src/arguments.rs
  crates/ruff_python_ast/src/visitor/preorder.rs
  crates/ruff_python_formatter/src/comments/mod.rs
Labels: internal

#6501 Use one line between top-level items if formatting a stub file
  crates/ruff_python_formatter/resources/test/fixtures/ruff/statement/top_level.py
  crates/ruff_python_formatter/resources/test/fixtures/ruff/statement/top_level.pyi
  crates/ruff_python_formatter/src/options.rs
  crates/ruff_python_formatter/src/statement/suite.rs
  crates/ruff_python_formatter/tests/fixtures.rs
  crates/ruff_python_formatter/tests/snapshots/format@statement__top_level.py.snap
  crates/ruff_python_formatter/tests/snapshots/format@statement__top_level.pyi.snap
Labels: formatter

#6583 Add trailing comma for single-element import-from groups
  crates/ruff_python_formatter/src/builders.rs
  crates/ruff_python_formatter/src/statement/stmt_import_from.rs
  crates/ruff_python_formatter/tests/snapshots/black_compatibility@simple_cases__comments2.py.snap
  crates/ruff_python_formatter/tests/snapshots/black_compatibility@simple_cases__import_spacing.py.snap
  crates/ruff_python_formatter/tests/snapshots/format@statement__import.py.snap
  crates/ruff_python_formatter/tests/snapshots/format@statement__import_from.py.snap
Labels: formatter

#6596 Fix PT005 doc
  crates/ruff/src/rules/flake8_pytest_style/rules/fixture.rs
Labels: documentation

#6602 Fix docs for `PLW1508`
  crates/ruff/src/rules/pylint/rules/invalid_envvar_default.rs
Labels: documentation

#6604 Remove pylint's duplicate_value.rs
  crates/ruff/src/rules/pylint/rules/duplicate_value.rs
Labels: internal
