Repository astral-sh/ruff, pull requests merged in 2023-09, with the labels that each got.

#7008 Exclude pragma comments from measured line width
  crates/ruff_python_formatter/resources/test/fixtures/ruff/trailing_comments.py
  crates/ruff_python_formatter/src/comments/format.rs
  crates/ruff_python_formatter/tests/snapshots/black_compatibility@simple_cases__comments6.py.snap
  crates/ruff_python_formatter/tests/snapshots/black_compatibility@simple_cases__expression.py.snap
  crates/ruff_python_formatter/tests/snapshots/black_compatibility@simple_cases__power_op_spacing.py.snap
  crates/ruff_python_formatter/tests/snapshots/black_compatibility@simple_cases__torture.py.snap
  crates/ruff_python_formatter/tests/snapshots/format@trailing_comments.py.snap
Labels: formatter

#7035 Add a `NotebookError` type to avoid returning `Diagnostics` on error
  crates/ruff/src/jupyter/notebook.rs
  crates/ruff/src/lib.rs
  crates/ruff/src/rules/pycodestyle/rules/mod.rs
  crates/ruff/src/test.rs
  crates/ruff_cli/src/diagnostics.rs
Labels: internal

#7040 Refactor ruff_cli's run method to return on each branch
  crates/ruff_cli/src/commands/config.rs
  crates/ruff_cli/src/lib.rs
Labels: internal

#7039 Create `ruff_notebook` crate
  CONTRIBUTING.md
  Cargo.lock
  crates/ruff/Cargo.toml
  crates/ruff/src/autofix/mod.rs
  crates/ruff/src/lib.rs
  crates/ruff/src/linter.rs
  crates/ruff/src/logging.rs
  crates/ruff/src/message/grouped.rs
  crates/ruff/src/message/mod.rs
  crates/ruff/src/message/text.rs
  crates/ruff/src/rules/isort/block.rs
  crates/ruff/src/snapshots/ruff__linter__tests__import_sorting.snap
  crates/ruff/src/snapshots/ruff__linter__tests__ipy_escape_command.snap
  crates/ruff/src/snapshots/ruff__linter__tests__unused_variable.snap
  crates/ruff/src/source_kind.rs
  crates/ruff/src/test.rs
  crates/ruff_cli/Cargo.toml
  crates/ruff_cli/src/diagnostics.rs
  crates/ruff_dev/Cargo.toml
  crates/ruff_dev/src/round_trip.rs
  crates/ruff_diagnostics/src/lib.rs
  crates/ruff_diagnostics/src/source_map.rs
  crates/ruff_notebook/Cargo.toml
  crates/ruff_notebook/resources/test/fixtures/jupyter/R.ipynb
  crates/ruff_notebook/resources/test/fixtures/jupyter/add_missing_cell_id.ipynb
  crates/ruff_notebook/resources/test/fixtures/jupyter/after_fix.ipynb
  crates/ruff_notebook/resources/test/fixtures/jupyter/before_fix.ipynb
  crates/ruff_notebook/resources/test/fixtures/jupyter/cell/cell_magic.json
  crates/ruff_notebook/resources/test/fixtures/jupyter/cell/code_and_magic.json
  crates/ruff_notebook/resources/test/fixtures/jupyter/cell/markdown.json
  crates/ruff_notebook/resources/test/fixtures/jupyter/cell/only_code.json
  crates/ruff_notebook/resources/test/fixtures/jupyter/cell/only_magic.json
  crates/ruff_notebook/resources/test/fixtures/jupyter/invalid_extension.ipynb
  crates/ruff_notebook/resources/test/fixtures/jupyter/ipy_escape_command.ipynb
  crates/ruff_notebook/resources/test/fixtures/jupyter/ipy_escape_command_expected.ipynb
  crates/ruff_notebook/resources/test/fixtures/jupyter/isort.ipynb
  crates/ruff_notebook/resources/test/fixtures/jupyter/isort_expected.ipynb
  crates/ruff_notebook/resources/test/fixtures/jupyter/no_cell_id.ipynb
  crates/ruff_notebook/resources/test/fixtures/jupyter/no_trailing_newline.ipynb
  crates/ruff_notebook/resources/test/fixtures/jupyter/not_json.ipynb
  crates/ruff_notebook/resources/test/fixtures/jupyter/unused_variable.ipynb
  crates/ruff_notebook/resources/test/fixtures/jupyter/unused_variable_expected.ipynb
  crates/ruff_notebook/resources/test/fixtures/jupyter/valid.ipynb
  crates/ruff_notebook/resources/test/fixtures/jupyter/wrong_schema.ipynb
  crates/ruff_notebook/src/index.rs
  crates/ruff_notebook/src/lib.rs
  crates/ruff_notebook/src/notebook.rs
  crates/ruff_notebook/src/schema.rs
Labels: internal

#7029 Fixed panic in `missing_copyright_notice`
  crates/ruff/src/rules/flake8_copyright/mod.rs
  crates/ruff/src/rules/flake8_copyright/rules/missing_copyright_notice.rs
  crates/ruff/src/rules/flake8_copyright/snapshots/ruff__rules__flake8_copyright__tests__char_boundary.snap
  crates/ruff_source_file/src/locator.rs
Labels: bug

#7034 Add dependabot for `cargo` dependencies
  .github/dependabot.yml
Labels: internal

#7047 Fix placement for comments within f-strings concatenations
  crates/ruff_python_formatter/resources/test/fixtures/ruff/expression/fstring.py
  crates/ruff_python_formatter/src/comments/placement.rs
  crates/ruff_python_formatter/tests/snapshots/format@expression__fstring.py.snap
Labels: formatter

#7057 Fix `getattr` calls on int literals
  crates/ruff/resources/test/fixtures/flake8_bugbear/B009_B010.py
  crates/ruff/src/rules/flake8_bugbear/rules/getattr_with_constant.rs
  crates/ruff/src/rules/flake8_bugbear/snapshots/ruff__rules__flake8_bugbear__tests__B009_B009_B010.py.snap
  crates/ruff/src/rules/flake8_bugbear/snapshots/ruff__rules__flake8_bugbear__tests__B010_B009_B010.py.snap
Labels: bug, fuzzer

#7063 Avoid duplicate fixes for multi-import imports in RUF017
  crates/ruff/resources/test/fixtures/ruff/RUF017.py
  crates/ruff/src/rules/ruff/rules/quadratic_list_summation.rs
  crates/ruff/src/rules/ruff/snapshots/ruff__rules__ruff__tests__RUF017_RUF017.py.snap
Labels: bug, fuzzer

#7065 Rename `ruff_python_formatter/README.md` to `CONTRIBUTING.md`
  crates/ruff_python_formatter/CONTRIBUTING.md
Labels: formatter

#7062 Update LibCST
  Cargo.lock
  Cargo.toml
  crates/ruff/resources/test/fixtures/pyflakes/F504.py
  crates/ruff/src/rules/pyflakes/snapshots/ruff__rules__pyflakes__tests__F504_F504.py.snap
Labels: bug, dependencies

#7079 Avoid attempting to fix invalid `Optional` annotations
  crates/ruff/resources/test/fixtures/pyupgrade/UP007.py
  crates/ruff/src/rules/pyupgrade/rules/use_pep604_annotation.rs
  crates/ruff/src/rules/pyupgrade/snapshots/ruff__rules__pyupgrade__tests__UP007.py.snap
Labels: bug, fuzzer

#7080 Supported starred exceptions in length-one tuple detection
  crates/ruff/resources/test/fixtures/flake8_bugbear/B013.py
  crates/ruff/src/rules/flake8_bugbear/rules/redundant_tuple_in_exception_handler.rs
  crates/ruff/src/rules/flake8_bugbear/snapshots/ruff__rules__flake8_bugbear__tests__B013_B013.py.snap
  crates/ruff_python_ast/src/helpers.rs
Labels: bug, fuzzer

#7081 Support length-2 lists in dictionary comprehension rewrites
  crates/ruff/resources/test/fixtures/flake8_comprehensions/C417.py
  crates/ruff/src/rules/flake8_comprehensions/fixes.rs
  crates/ruff/src/rules/flake8_comprehensions/snapshots/ruff__rules__flake8_comprehensions__tests__C417_C417.py.snap
Labels: bug, fuzzer

#7083 Use symbol import for NPY003 replacement
  crates/ruff/resources/test/fixtures/numpy/NPY003.py
  crates/ruff/src/rules/numpy/rules/deprecated_function.rs
  crates/ruff/src/rules/numpy/snapshots/ruff__rules__numpy__tests__numpy-deprecated-function_NPY003.py.snap
Labels: bug, fuzzer

#7089 Change `Option<Result>` to `Result<Option>` in importer
  crates/ruff/src/importer/mod.rs
Labels: internal

#7090 Add newline if B006 fix is at end-of-file
  crates/ruff/resources/test/fixtures/flake8_bugbear/B006_B008.py
  crates/ruff/src/rules/flake8_bugbear/rules/mutable_argument_default.rs
  crates/ruff/src/rules/flake8_bugbear/snapshots/ruff__rules__flake8_bugbear__tests__B006_B006_B008.py.snap
Labels: bug, fuzzer

#7091 Parenthesize expressins when converting to B009
  crates/ruff/resources/test/fixtures/flake8_bugbear/B009_B010.py
  crates/ruff/src/rules/flake8_bugbear/rules/getattr_with_constant.rs
  crates/ruff/src/rules/flake8_bugbear/snapshots/ruff__rules__flake8_bugbear__tests__B009_B009_B010.py.snap
  crates/ruff/src/rules/flake8_bugbear/snapshots/ruff__rules__flake8_bugbear__tests__B010_B009_B010.py.snap
Labels: bug, fuzzer

#7093 Fix incorrect flake8-copyright link in faq
  docs/faq.md
Labels: documentation

#7110 Expand F841 fixes to handle parenthesized targets
  crates/ruff/resources/test/fixtures/pyflakes/F841_3.py
  crates/ruff/src/rules/pyflakes/rules/unused_variable.rs
  crates/ruff/src/rules/pyflakes/snapshots/ruff__rules__pyflakes__tests__F841_F841_3.py.snap
Labels: bug, fuzzer

#7111 Handle parenthesized calls in PD002
  crates/ruff/resources/test/fixtures/pandas_vet/PD002.py
  crates/ruff/src/rules/pandas_vet/rules/inplace_argument.rs
  crates/ruff/src/rules/pandas_vet/snapshots/ruff__rules__pandas_vet__tests__PD002_PD002.py.snap
Labels: bug, fuzzer

#7113 Avoid adding duplicate `capture_output` keyword to `subprocess.run`
  crates/ruff/resources/test/fixtures/pyupgrade/UP022.py
  crates/ruff/src/rules/pyupgrade/rules/replace_stdout_stderr.rs
  crates/ruff/src/rules/pyupgrade/snapshots/ruff__rules__pyupgrade__tests__UP022.py.snap
Labels: bug, fuzzer

#7112 Avoid adding duplicate `text` keyword to `subprocess.run`
  crates/ruff/resources/test/fixtures/pyupgrade/UP021.py
  crates/ruff/src/rules/pyupgrade/rules/replace_universal_newlines.rs
  crates/ruff/src/rules/pyupgrade/snapshots/ruff__rules__pyupgrade__tests__UP021.py.snap
Labels: bug, fuzzer

#7108 Deduplicate information in configuration documentation
  docs/configuration.md
Labels: documentation

#7114 Support parenthesized expressions in UP028
  crates/ruff/resources/test/fixtures/pyupgrade/UP028_0.py
  crates/ruff/resources/test/fixtures/pyupgrade/UP028_1.py
  crates/ruff/src/rules/pyupgrade/rules/yield_in_for_loop.rs
  crates/ruff/src/rules/pyupgrade/snapshots/ruff__rules__pyupgrade__tests__UP028_0.py.snap
Labels: bug, fuzzer

#7116 Add space after return when inlining number for RET504
  crates/ruff/resources/test/fixtures/flake8_return/RET504.py
  crates/ruff/src/rules/flake8_return/rules/function.rs
  crates/ruff/src/rules/flake8_return/snapshots/ruff__rules__flake8_return__tests__RET504_RET504.py.snap
Labels: bug, fuzzer

#7115 Fix precedence of annotated assignments in generator
  crates/ruff_python_codegen/src/generator.rs
Labels: bug, fuzzer

#7117 Add parentheses when simplifying conditions in SIM222
  crates/ruff/resources/test/fixtures/flake8_simplify/SIM222.py
  crates/ruff/src/rules/flake8_simplify/rules/ast_bool_op.rs
  crates/ruff/src/rules/flake8_simplify/snapshots/ruff__rules__flake8_simplify__tests__SIM222_SIM222.py.snap
  crates/ruff_python_codegen/src/generator.rs
Labels: bug, fuzzer

#7118 Retain parentheses when fixing `SIM210`
  crates/ruff/resources/test/fixtures/flake8_simplify/SIM210.py
  crates/ruff/src/checkers/ast/analyze/expression.rs
  crates/ruff/src/rules/flake8_simplify/rules/ast_ifexp.rs
  crates/ruff/src/rules/flake8_simplify/snapshots/ruff__rules__flake8_simplify__tests__SIM210_SIM210.py.snap
  crates/ruff/src/rules/flake8_simplify/snapshots/ruff__rules__flake8_simplify__tests__SIM211_SIM211.py.snap
Labels: bug, fuzzer

#7054 Formatter: Detect line endings
  Cargo.lock
  crates/ruff_cli/src/commands/format.rs
  crates/ruff_formatter/src/printer/printer_options/mod.rs
  crates/ruff_python_formatter/Cargo.toml
  crates/ruff_python_formatter/src/lib.rs
  crates/ruff_python_formatter/src/options.rs
Labels: cli, formatter

#7013 Make `SourceKind` a required parameter
  crates/ruff/src/checkers/imports.rs
  crates/ruff/src/linter.rs
  crates/ruff/src/logging.rs
  crates/ruff/src/rules/isort/block.rs
  crates/ruff/src/rules/pyflakes/mod.rs
  crates/ruff/src/source_kind.rs
  crates/ruff/src/test.rs
  crates/ruff_cli/src/commands/add_noqa.rs
  crates/ruff_cli/src/diagnostics.rs
  crates/ruff_wasm/src/lib.rs
Labels: internal

#7119 Avoid triggering N806 on `TypeAlias` assignments
  crates/ruff/resources/test/fixtures/pep8_naming/N806.py
  crates/ruff/src/rules/pep8_naming/helpers.rs
  crates/ruff/src/rules/pep8_naming/rules/non_lowercase_variable_in_function.rs
  crates/ruff/src/rules/pep8_naming/snapshots/ruff__rules__pep8_naming__tests__N806_N806.py.snap
Labels: bug

#7109 Preserve parentheses around partial call chains
  crates/ruff_python_formatter/resources/test/fixtures/ruff/parentheses/call_chains.py
  crates/ruff_python_formatter/src/expression/expr_attribute.rs
  crates/ruff_python_formatter/src/expression/mod.rs
  crates/ruff_python_formatter/tests/snapshots/format@parentheses__call_chains.py.snap
Labels: formatter

#7129 Better formatter CLI verbose output
  crates/ruff_cli/Cargo.toml
  crates/ruff_cli/src/commands/format.rs
  crates/ruff_formatter/src/printer/mod.rs
Labels: formatter

#7144 Reduce `comments.clone` calls
  crates/ruff_python_formatter/src/comments/format.rs
Labels: performance, formatter

#7137 Use generator for UP007 autofix
  crates/ruff/resources/test/fixtures/pyupgrade/UP007.py
  crates/ruff/src/rules/pyupgrade/rules/use_pep604_annotation.rs
  crates/ruff/src/rules/pyupgrade/snapshots/ruff__rules__pyupgrade__tests__UP007.py.snap
Labels: bug, fuzzer

#7149 Avoid fixing UP022 when `capture_output` is provided
  crates/ruff/resources/test/fixtures/pyupgrade/UP022.py
  crates/ruff/src/rules/pyupgrade/rules/replace_stdout_stderr.rs
  crates/ruff/src/rules/pyupgrade/snapshots/ruff__rules__pyupgrade__tests__UP022.py.snap
Labels: bug, fuzzer

#7148 Insert required space when fixing B013
  crates/ruff/resources/test/fixtures/flake8_bugbear/B013.py
  crates/ruff/src/rules/flake8_bugbear/rules/redundant_tuple_in_exception_handler.rs
  crates/ruff/src/rules/flake8_bugbear/snapshots/ruff__rules__flake8_bugbear__tests__B013_B013.py.snap
Labels: bug, fuzzer

#7150 Add required space when fixing SIM118
  crates/ruff/resources/test/fixtures/flake8_simplify/SIM118.py
  crates/ruff/src/rules/flake8_simplify/rules/key_in_dict.rs
  crates/ruff/src/rules/flake8_simplify/snapshots/ruff__rules__flake8_simplify__tests__SIM118_SIM118.py.snap
Labels: bug, fuzzer

#7152 Add required space when fixing C402
  crates/ruff/resources/test/fixtures/flake8_comprehensions/C402.py
  crates/ruff/src/rules/flake8_comprehensions/fixes.rs
  crates/ruff/src/rules/flake8_comprehensions/snapshots/ruff__rules__flake8_comprehensions__tests__C402_C402.py.snap
Labels: bug, fuzzer

#6737 Use insta_cmd
  Cargo.lock
  crates/ruff_cli/Cargo.toml
  crates/ruff_cli/tests/black_compatibility_test.rs
  crates/ruff_cli/tests/integration_test.rs
  crates/ruff_cli/tests/snapshots/integration_test__explain_status_codes_f401.snap
  crates/ruff_cli/tests/snapshots/integration_test__stdin_json.snap
Labels: internal

#7153 Rename parser mode from `Jupyter` to `Ipython`
  crates/ruff_dev/src/print_ast.rs
  crates/ruff_dev/src/print_tokens.rs
  crates/ruff_python_codegen/src/generator.rs
  crates/ruff_python_parser/src/lexer.rs
  crates/ruff_python_parser/src/lib.rs
  crates/ruff_python_parser/src/parser.rs
  crates/ruff_python_parser/src/python.lalrpop
  crates/ruff_python_parser/src/python.rs
  crates/ruff_python_parser/src/token.rs
Labels: parser

#7151 Split within `not`, rather than outside of `not`, for PT018
  crates/ruff/resources/test/fixtures/flake8_pytest_style/PT018.py
  crates/ruff/src/rules/flake8_pytest_style/rules/assertion.rs
  crates/ruff/src/rules/flake8_pytest_style/snapshots/ruff__rules__flake8_pytest_style__tests__PT018.snap
Labels: bug, fuzzer

#7160 Fix B006 when function docstring is followed by whitespace but no newline
  crates/ruff/resources/test/fixtures/flake8_bugbear/B006_1.py
  crates/ruff/resources/test/fixtures/flake8_bugbear/B006_2.py
  crates/ruff/resources/test/fixtures/flake8_bugbear/B006_3.py
  crates/ruff/src/rules/flake8_bugbear/mod.rs
  crates/ruff/src/rules/flake8_bugbear/rules/mutable_argument_default.rs
  crates/ruff/src/rules/flake8_bugbear/snapshots/ruff__rules__flake8_bugbear__tests__B006_B006_1.py.snap
  crates/ruff/src/rules/flake8_bugbear/snapshots/ruff__rules__flake8_bugbear__tests__B006_B006_2.py.snap
  crates/ruff/src/rules/flake8_bugbear/snapshots/ruff__rules__flake8_bugbear__tests__B006_B006_3.py.snap
Labels: bug

#7167 Add required space when fixing SIM300
  crates/ruff/resources/test/fixtures/flake8_simplify/SIM300.py
  crates/ruff/src/cst/helpers.rs
  crates/ruff/src/rules/flake8_comprehensions/fixes.rs
  crates/ruff/src/rules/flake8_pytest_style/rules/assertion.rs
  crates/ruff/src/rules/flake8_simplify/rules/fix_if.rs
  crates/ruff/src/rules/flake8_simplify/rules/yoda_conditions.rs
  crates/ruff/src/rules/flake8_simplify/snapshots/ruff__rules__flake8_simplify__tests__SIM300_SIM300.py.snap
Labels: bug, fuzzer

#7170 Fix named expression precedence in generator
  crates/ruff/resources/test/fixtures/pycodestyle/E731.py
  crates/ruff/src/rules/pycodestyle/snapshots/ruff__rules__pycodestyle__tests__E731_E731.py.snap
  crates/ruff_python_codegen/src/generator.rs
Labels: bug, fuzzer

#7168 Remove autofix for ambiguous unicode rules
  crates/ruff/src/rules/ruff/rules/ambiguous_unicode_character.rs
  crates/ruff/src/rules/ruff/snapshots/ruff__rules__ruff__tests__confusables.snap
Labels: autofix

#7171 Add required space when fixing UP024
  crates/ruff/resources/test/fixtures/pyupgrade/UP024_0.py
  crates/ruff/src/autofix/edits.rs
  crates/ruff/src/rules/flake8_bugbear/rules/redundant_tuple_in_exception_handler.rs
  crates/ruff/src/rules/flake8_simplify/rules/key_in_dict.rs
  crates/ruff/src/rules/flake8_simplify/rules/yoda_conditions.rs
  crates/ruff/src/rules/pycodestyle/rules/invalid_escape_sequence.rs
  crates/ruff/src/rules/pyupgrade/rules/os_error_alias.rs
  crates/ruff/src/rules/pyupgrade/snapshots/ruff__rules__pyupgrade__tests__UP024_0.py.snap
Labels: bug, fuzzer

#7178 Add inline documentation for `Ipy*` AST nodes
  crates/ruff_python_ast/src/nodes.rs
Labels: internal

#6552 Memoize text width
  crates/ruff_formatter/src/arguments.rs
  crates/ruff_formatter/src/builders.rs
  crates/ruff_formatter/src/format_element.rs
  crates/ruff_formatter/src/format_element/document.rs
  crates/ruff_formatter/src/macros.rs
  crates/ruff_formatter/src/printer/mod.rs
  crates/ruff_python_formatter/src/comments/format.rs
  crates/ruff_python_formatter/src/expression/expr_ipy_escape_command.rs
  crates/ruff_python_formatter/src/expression/expr_name.rs
  crates/ruff_python_formatter/src/expression/number.rs
  crates/ruff_python_formatter/src/expression/string.rs
  crates/ruff_python_formatter/src/other/identifier.rs
  crates/ruff_python_formatter/src/statement/stmt_ipy_escape_command.rs
  crates/ruff_python_formatter/src/verbatim.rs
Labels: performance, formatter

#7181 Checker: Remove unnecessary unreachable
  crates/ruff/src/checkers/ast/mod.rs
Labels: internal

#7179 build: add libcst from crates
  Cargo.lock
  Cargo.toml
Labels: internal

#6813 Formatter: Show preceding, following and enclosing nodes of comments, Attempt 2
  crates/ruff_python_formatter/src/cli.rs
  crates/ruff_python_formatter/src/comments/mod.rs
  crates/ruff_python_formatter/src/comments/visitor.rs
Labels: internal

#7064 Add alpha instructions to the `ruff_python_formatter` README
  .pre-commit-config.yaml
  crates/ruff_cli/src/args.rs
  crates/ruff_python_formatter/README.md
  docs/configuration.md
Labels: formatter

#7186 Restructure signatures of `flake8_comprehensions` fixers
  crates/ruff/src/rules/flake8_comprehensions/fixes.rs
  crates/ruff/src/rules/flake8_comprehensions/rules/unnecessary_call_around_sorted.rs
  crates/ruff/src/rules/flake8_comprehensions/rules/unnecessary_collection_call.rs
  crates/ruff/src/rules/flake8_comprehensions/rules/unnecessary_comprehension.rs
  crates/ruff/src/rules/flake8_comprehensions/rules/unnecessary_comprehension_any_all.rs
  crates/ruff/src/rules/flake8_comprehensions/rules/unnecessary_double_cast_or_process.rs
  crates/ruff/src/rules/flake8_comprehensions/rules/unnecessary_generator_dict.rs
  crates/ruff/src/rules/flake8_comprehensions/rules/unnecessary_generator_list.rs
  crates/ruff/src/rules/flake8_comprehensions/rules/unnecessary_generator_set.rs
  crates/ruff/src/rules/flake8_comprehensions/rules/unnecessary_list_call.rs
  crates/ruff/src/rules/flake8_comprehensions/rules/unnecessary_list_comprehension_dict.rs
  crates/ruff/src/rules/flake8_comprehensions/rules/unnecessary_list_comprehension_set.rs
  crates/ruff/src/rules/flake8_comprehensions/rules/unnecessary_literal_dict.rs
  crates/ruff/src/rules/flake8_comprehensions/rules/unnecessary_literal_set.rs
  crates/ruff/src/rules/flake8_comprehensions/rules/unnecessary_literal_within_dict_call.rs
  crates/ruff/src/rules/flake8_comprehensions/rules/unnecessary_literal_within_list_call.rs
  crates/ruff/src/rules/flake8_comprehensions/rules/unnecessary_literal_within_tuple_call.rs
  crates/ruff/src/rules/flake8_comprehensions/rules/unnecessary_map.rs
Labels: internal

#7185 Add required space when fixing C404
  crates/ruff/resources/test/fixtures/flake8_comprehensions/C404.py
  crates/ruff/src/rules/flake8_comprehensions/fixes.rs
  crates/ruff/src/rules/flake8_comprehensions/snapshots/ruff__rules__flake8_comprehensions__tests__C404_C404.py.snap
Labels: bug, fuzzer

#7190 Use structured types for C417 comprehension target
  crates/ruff/resources/test/fixtures/flake8_comprehensions/C417.py
  crates/ruff/src/rules/flake8_comprehensions/fixes.rs
  crates/ruff/src/rules/flake8_comprehensions/snapshots/ruff__rules__flake8_comprehensions__tests__C417_C417.py.snap
Labels: internal

#7191 Avoid attempting to fix SIM105 violations with multi-statement lines
  crates/ruff/resources/test/fixtures/flake8_simplify/SIM105_0.py
  crates/ruff/src/rules/flake8_simplify/rules/suppressible_exception.rs
  crates/ruff/src/rules/flake8_simplify/snapshots/ruff__rules__flake8_simplify__tests__SIM105_SIM105_0.py.snap
Labels: bug, fuzzer

#7184 Lexer: Add skip whitespace fastpath
  crates/ruff_python_parser/src/lexer.rs
Labels: performance, parser

#7202 Add required space to UP006 and UP007 fixes
  crates/ruff/resources/test/fixtures/pyupgrade/UP007.py
  crates/ruff/src/rules/pyupgrade/rules/use_pep604_annotation.rs
  crates/ruff/src/rules/pyupgrade/snapshots/ruff__rules__pyupgrade__tests__UP007.py.snap
Labels: bug, fuzzer

#7204 Add required space to C416 fix
  crates/ruff/resources/test/fixtures/flake8_comprehensions/C416.py
  crates/ruff/src/rules/flake8_comprehensions/fixes.rs
  crates/ruff/src/rules/flake8_comprehensions/snapshots/ruff__rules__flake8_comprehensions__tests__C416_C416.py.snap
Labels: bug, fuzzer

#7212 Use the unicode-ident crate
  Cargo.lock
  Cargo.toml
  crates/ruff_python_parser/Cargo.toml
  crates/ruff_python_parser/src/lexer.rs
  crates/ruff_python_stdlib/Cargo.toml
  crates/ruff_python_stdlib/src/identifiers.rs
  crates/ruff_python_trivia/Cargo.toml
  crates/ruff_python_trivia/src/tokenizer.rs
Labels: breaking, parser

#7213 Add Lexer emoji test case
  crates/ruff_python_parser/src/lexer.rs
Labels: internal

#7194 Add `extend-ignore-names` for `flake8-self`
  crates/ruff/resources/test/fixtures/flake8_self/SLF001_extended.py
  crates/ruff/src/rules/flake8_self/mod.rs
  crates/ruff/src/rules/flake8_self/snapshots/ruff__rules__flake8_self__tests__ignore_names.snap
  crates/ruff_workspace/src/options.rs
  ruff.schema.json
Labels: configuration

#7222 Add required space for FLY002 fixes
  crates/ruff/resources/test/fixtures/flynt/FLY002.py
  crates/ruff/src/rules/flynt/rules/static_join_to_fstring.rs
  crates/ruff/src/rules/flynt/snapshots/ruff__rules__flynt__tests__FLY002_FLY002.py.snap
Labels: bug, fuzzer

#7221 Use full range for SIM105 fixes
  crates/ruff/resources/test/fixtures/flake8_simplify/SIM105_0.py
  crates/ruff/src/rules/flake8_simplify/rules/suppressible_exception.rs
  crates/ruff/src/rules/flake8_simplify/snapshots/ruff__rules__flake8_simplify__tests__SIM105_SIM105_0.py.snap
  crates/ruff/src/rules/flake8_simplify/snapshots/ruff__rules__flake8_simplify__tests__SIM105_SIM105_1.py.snap
  crates/ruff/src/rules/flake8_simplify/snapshots/ruff__rules__flake8_simplify__tests__SIM105_SIM105_2.py.snap
Labels: bug

#7203 Do not use code location for Gitlab fingerprints.
  crates/ruff/src/message/gitlab.rs
Labels: breaking, linter

#7145 Split implicit concatenated strings before binary expressions
  Cargo.lock
  Cargo.toml
  crates/ruff_formatter/Cargo.toml
  crates/ruff_python_formatter/Cargo.toml
  crates/ruff_python_formatter/resources/test/fixtures/ruff/expression/binary.py
  crates/ruff_python_formatter/resources/test/fixtures/ruff/expression/binary_implicit_string.py
  crates/ruff_python_formatter/src/comments/format.rs
  crates/ruff_python_formatter/src/comments/mod.rs
  crates/ruff_python_formatter/src/expression/binary_like.rs
  crates/ruff_python_formatter/src/expression/expr_bin_op.rs
  crates/ruff_python_formatter/src/expression/mod.rs
  crates/ruff_python_formatter/src/expression/operator.rs
  crates/ruff_python_formatter/src/expression/parentheses.rs
  crates/ruff_python_formatter/src/expression/string.rs
  crates/ruff_python_formatter/src/lib.rs
  crates/ruff_python_formatter/tests/snapshots/format@expression__binary.py.snap
  crates/ruff_python_formatter/tests/snapshots/format@expression__binary_implicit_string.py.snap
  crates/ruff_python_formatter/tests/snapshots/format@expression__bytes.py.snap
  crates/ruff_python_formatter/tests/snapshots/format@expression__string.py.snap
  crates/ruff_wasm/src/lib.rs
Labels: formatter

#7226 Preserve generator parentheses in single argument call expressions
  crates/ruff_python_formatter/resources/test/fixtures/ruff/expression/generator_exp.py
  crates/ruff_python_formatter/src/expression/expr_generator_exp.rs
  crates/ruff_python_formatter/src/other/arguments.rs
  crates/ruff_python_formatter/tests/snapshots/format@expression__call.py.snap
  crates/ruff_python_formatter/tests/snapshots/format@expression__generator_exp.py.snap
Labels: formatter

#7193 Formatter: Implicit concatenation in compare expressions
  crates/ruff_python_formatter/resources/test/fixtures/ruff/expression/compare.py
  crates/ruff_python_formatter/src/expression/binary_like.rs
  crates/ruff_python_formatter/src/expression/expr_bin_op.rs
  crates/ruff_python_formatter/src/expression/expr_compare.rs
  crates/ruff_python_formatter/tests/snapshots/format@expression__binary_implicit_string.py.snap
  crates/ruff_python_formatter/tests/snapshots/format@expression__compare.py.snap
Labels: formatter

#6318 Fix inconsistent `expr_lambda` formatting
  crates/ruff_python_formatter/resources/test/fixtures/ruff/expression/lambda.py
  crates/ruff_python_formatter/src/expression/expr_lambda.rs
  crates/ruff_python_formatter/tests/snapshots/format@expression__lambda.py.snap
Labels: formatter

#7215 Add FString support to binary like formatting
  crates/ruff_python_formatter/resources/test/fixtures/ruff/expression/binary_implicit_string.py
  crates/ruff_python_formatter/resources/test/fixtures/ruff/expression/compare.py
  crates/ruff_python_formatter/src/expression/binary_like.rs
  crates/ruff_python_formatter/src/expression/string.rs
  crates/ruff_python_formatter/tests/snapshots/format@expression__binary_implicit_string.py.snap
  crates/ruff_python_formatter/tests/snapshots/format@expression__compare.py.snap
Labels: formatter

#7241 Disable default criterion features
  Cargo.lock
  crates/ruff_benchmark/Cargo.toml
Labels: internal

#7217 Add PreviewMode option to formatter
  Cargo.lock
  crates/ruff_cli/src/args.rs
  crates/ruff_cli/src/commands/format.rs
  crates/ruff_python_formatter/Cargo.toml
  crates/ruff_python_formatter/src/expression/mod.rs
  crates/ruff_python_formatter/src/lib.rs
  crates/ruff_python_formatter/src/options.rs
Labels: cli, formatter

#7219 Extract string part and normalized string
  crates/ruff_python_formatter/src/expression/string.rs
Labels: internal, formatter

#7240 Remove IO based lints from linter benchmark
  crates/ruff_benchmark/benches/linter.rs
Labels: internal

#7251 fix D417 error with function docstrings with dashed lines
  crates/ruff/resources/test/fixtures/pydocstyle/D417.py
  crates/ruff/src/rules/pydocstyle/rules/sections.rs
Labels: docstring

#7260 Avoid F401 panic with noqa import name
  crates/ruff/resources/test/fixtures/pyflakes/F401_0.py
  crates/ruff/src/noqa.rs
  crates/ruff/src/rules/pyflakes/snapshots/ruff__rules__pyflakes__tests__F401_F401_0.py.snap
Labels: bug

#7252 Avoid allocating in lex_decimal
  crates/ruff_python_parser/src/lexer.rs
Labels: parser

#7206 Format empty lines in stub files like black's preview style
  .editorconfig
  crates/ruff_python_formatter/resources/test/fixtures/ruff/module_dangling_comment1.py
  crates/ruff_python_formatter/resources/test/fixtures/ruff/module_dangling_comment2.py
  crates/ruff_python_formatter/resources/test/fixtures/ruff/stub_files/comments.pyi
  crates/ruff_python_formatter/resources/test/fixtures/ruff/stub_files/nesting.pyi
  crates/ruff_python_formatter/resources/test/fixtures/ruff/stub_files/suite.pyi
  crates/ruff_python_formatter/resources/test/fixtures/ruff/stub_files/top_level.pyi
  crates/ruff_python_formatter/src/comments/format.rs
  crates/ruff_python_formatter/src/module/mod_module.rs
  crates/ruff_python_formatter/src/statement/stmt_class_def.rs
  crates/ruff_python_formatter/src/statement/stmt_function_def.rs
  crates/ruff_python_formatter/src/statement/suite.rs
  crates/ruff_python_formatter/tests/snapshots/format@module_dangling_comment1.py.snap
  crates/ruff_python_formatter/tests/snapshots/format@module_dangling_comment2.py.snap
  crates/ruff_python_formatter/tests/snapshots/format@stub_files__comments.pyi.snap
  crates/ruff_python_formatter/tests/snapshots/format@stub_files__nesting.pyi.snap
  crates/ruff_python_formatter/tests/snapshots/format@stub_files__suite.pyi.snap
  crates/ruff_python_formatter/tests/snapshots/format@stub_files__top_level.pyi.snap
Labels: formatter

#7277 Use `pages deploy` instead of the deprecated `pages publish` command to deploy the docs website
  .github/workflows/docs.yaml
Labels: internal

#7264 Use snapshots for remaining lexer tests
  Cargo.lock
  crates/ruff_python_parser/Cargo.toml
  crates/ruff_python_parser/src/lexer.rs
  crates/ruff_python_parser/src/snapshots/ruff_python_parser__lexer__tests__comment_until_mac_eol.snap
  crates/ruff_python_parser/src/snapshots/ruff_python_parser__lexer__tests__comment_until_unix_eol.snap
  crates/ruff_python_parser/src/snapshots/ruff_python_parser__lexer__tests__comment_until_windows_eol.snap
  crates/ruff_python_parser/src/snapshots/ruff_python_parser__lexer__tests__double_dedent_with_mac_eol.snap
  crates/ruff_python_parser/src/snapshots/ruff_python_parser__lexer__tests__double_dedent_with_tabs_mac_eol.snap
  crates/ruff_python_parser/src/snapshots/ruff_python_parser__lexer__tests__double_dedent_with_tabs_unix_eol.snap
  crates/ruff_python_parser/src/snapshots/ruff_python_parser__lexer__tests__double_dedent_with_tabs_windows_eol.snap
  crates/ruff_python_parser/src/snapshots/ruff_python_parser__lexer__tests__double_dedent_with_unix_eol.snap
  crates/ruff_python_parser/src/snapshots/ruff_python_parser__lexer__tests__double_dedent_with_windows_eol.snap
  crates/ruff_python_parser/src/snapshots/ruff_python_parser__lexer__tests__escape_unicode_name.snap
  crates/ruff_python_parser/src/snapshots/ruff_python_parser__lexer__tests__indentation_with_mac_eol.snap
  crates/ruff_python_parser/src/snapshots/ruff_python_parser__lexer__tests__indentation_with_unix_eol.snap
  crates/ruff_python_parser/src/snapshots/ruff_python_parser__lexer__tests__indentation_with_windows_eol.snap
  crates/ruff_python_parser/src/snapshots/ruff_python_parser__lexer__tests__ipython_escape_command_line_continuation_mac_eol.snap
  crates/ruff_python_parser/src/snapshots/ruff_python_parser__lexer__tests__ipython_escape_command_line_continuation_unix_eol.snap
  crates/ruff_python_parser/src/snapshots/ruff_python_parser__lexer__tests__ipython_escape_command_line_continuation_windows_eol.snap
  crates/ruff_python_parser/src/snapshots/ruff_python_parser__lexer__tests__ipython_escape_command_line_continuation_with_mac_eol_and_eof.snap
  crates/ruff_python_parser/src/snapshots/ruff_python_parser__lexer__tests__ipython_escape_command_line_continuation_with_unix_eol_and_eof.snap
  crates/ruff_python_parser/src/snapshots/ruff_python_parser__lexer__tests__ipython_escape_command_line_continuation_with_windows_eol_and_eof.snap
  crates/ruff_python_parser/src/snapshots/ruff_python_parser__lexer__tests__line_comment_empty.snap
  crates/ruff_python_parser/src/snapshots/ruff_python_parser__lexer__tests__line_comment_long.snap
  crates/ruff_python_parser/src/snapshots/ruff_python_parser__lexer__tests__line_comment_single_whitespace.snap
  crates/ruff_python_parser/src/snapshots/ruff_python_parser__lexer__tests__line_comment_whitespace.snap
  crates/ruff_python_parser/src/snapshots/ruff_python_parser__lexer__tests__newline_in_brackets_mac_eol.snap
  crates/ruff_python_parser/src/snapshots/ruff_python_parser__lexer__tests__newline_in_brackets_unix_eol.snap
  crates/ruff_python_parser/src/snapshots/ruff_python_parser__lexer__tests__newline_in_brackets_windows_eol.snap
  crates/ruff_python_parser/src/snapshots/ruff_python_parser__lexer__tests__string_continuation_with_mac_eol.snap
  crates/ruff_python_parser/src/snapshots/ruff_python_parser__lexer__tests__string_continuation_with_unix_eol.snap
  crates/ruff_python_parser/src/snapshots/ruff_python_parser__lexer__tests__string_continuation_with_windows_eol.snap
  crates/ruff_python_parser/src/snapshots/ruff_python_parser__lexer__tests__triple_quoted_mac_eol.snap
  crates/ruff_python_parser/src/snapshots/ruff_python_parser__lexer__tests__triple_quoted_unix_eol.snap
  crates/ruff_python_parser/src/snapshots/ruff_python_parser__lexer__tests__triple_quoted_windows_eol.snap
Labels: internal

#7278 Update the `docs` workflow to allow publishing a specific ref
  .github/workflows/docs.yaml
Labels: internal

#7208 Enable preview mode during benchmarks
  crates/ruff_benchmark/benches/linter.rs
Labels: preview

#7265 Add range to lexer test snapshots
  crates/ruff_python_parser/src/lexer.rs
  crates/ruff_python_parser/src/snapshots/ruff_python_parser__lexer__tests__assignment.snap
  crates/ruff_python_parser/src/snapshots/ruff_python_parser__lexer__tests__comment_until_mac_eol.snap
  crates/ruff_python_parser/src/snapshots/ruff_python_parser__lexer__tests__comment_until_unix_eol.snap
  crates/ruff_python_parser/src/snapshots/ruff_python_parser__lexer__tests__comment_until_windows_eol.snap
  crates/ruff_python_parser/src/snapshots/ruff_python_parser__lexer__tests__double_dedent_with_mac_eol.snap
  crates/ruff_python_parser/src/snapshots/ruff_python_parser__lexer__tests__double_dedent_with_tabs_mac_eol.snap
  crates/ruff_python_parser/src/snapshots/ruff_python_parser__lexer__tests__double_dedent_with_tabs_unix_eol.snap
  crates/ruff_python_parser/src/snapshots/ruff_python_parser__lexer__tests__double_dedent_with_tabs_windows_eol.snap
  crates/ruff_python_parser/src/snapshots/ruff_python_parser__lexer__tests__double_dedent_with_unix_eol.snap
  crates/ruff_python_parser/src/snapshots/ruff_python_parser__lexer__tests__double_dedent_with_windows_eol.snap
  crates/ruff_python_parser/src/snapshots/ruff_python_parser__lexer__tests__empty_ipython_escape_command.snap
  crates/ruff_python_parser/src/snapshots/ruff_python_parser__lexer__tests__escape_unicode_name.snap
  crates/ruff_python_parser/src/snapshots/ruff_python_parser__lexer__tests__indentation_with_mac_eol.snap
  crates/ruff_python_parser/src/snapshots/ruff_python_parser__lexer__tests__indentation_with_unix_eol.snap
  crates/ruff_python_parser/src/snapshots/ruff_python_parser__lexer__tests__indentation_with_windows_eol.snap
  crates/ruff_python_parser/src/snapshots/ruff_python_parser__lexer__tests__ipython_escape_command.snap
  crates/ruff_python_parser/src/snapshots/ruff_python_parser__lexer__tests__ipython_escape_command_assignment.snap
  crates/ruff_python_parser/src/snapshots/ruff_python_parser__lexer__tests__ipython_escape_command_indentation.snap
  crates/ruff_python_parser/src/snapshots/ruff_python_parser__lexer__tests__ipython_escape_command_line_continuation_mac_eol.snap
  crates/ruff_python_parser/src/snapshots/ruff_python_parser__lexer__tests__ipython_escape_command_line_continuation_unix_eol.snap
  crates/ruff_python_parser/src/snapshots/ruff_python_parser__lexer__tests__ipython_escape_command_line_continuation_windows_eol.snap
  crates/ruff_python_parser/src/snapshots/ruff_python_parser__lexer__tests__ipython_escape_command_line_continuation_with_mac_eol_and_eof.snap
  crates/ruff_python_parser/src/snapshots/ruff_python_parser__lexer__tests__ipython_escape_command_line_continuation_with_unix_eol_and_eof.snap
  crates/ruff_python_parser/src/snapshots/ruff_python_parser__lexer__tests__ipython_escape_command_line_continuation_with_windows_eol_and_eof.snap
  crates/ruff_python_parser/src/snapshots/ruff_python_parser__lexer__tests__ipython_help_end_escape_command.snap
  crates/ruff_python_parser/src/snapshots/ruff_python_parser__lexer__tests__line_comment_empty.snap
  crates/ruff_python_parser/src/snapshots/ruff_python_parser__lexer__tests__line_comment_long.snap
  crates/ruff_python_parser/src/snapshots/ruff_python_parser__lexer__tests__line_comment_single_whitespace.snap
  crates/ruff_python_parser/src/snapshots/ruff_python_parser__lexer__tests__line_comment_whitespace.snap
  crates/ruff_python_parser/src/snapshots/ruff_python_parser__lexer__tests__logical_newline_line_comment.snap
  crates/ruff_python_parser/src/snapshots/ruff_python_parser__lexer__tests__newline_in_brackets_mac_eol.snap
  crates/ruff_python_parser/src/snapshots/ruff_python_parser__lexer__tests__newline_in_brackets_unix_eol.snap
  crates/ruff_python_parser/src/snapshots/ruff_python_parser__lexer__tests__newline_in_brackets_windows_eol.snap
  crates/ruff_python_parser/src/snapshots/ruff_python_parser__lexer__tests__non_logical_newline_in_string_continuation.snap
  crates/ruff_python_parser/src/snapshots/ruff_python_parser__lexer__tests__numbers.snap
  crates/ruff_python_parser/src/snapshots/ruff_python_parser__lexer__tests__operators.snap
  crates/ruff_python_parser/src/snapshots/ruff_python_parser__lexer__tests__string.snap
  crates/ruff_python_parser/src/snapshots/ruff_python_parser__lexer__tests__string_continuation_with_mac_eol.snap
  crates/ruff_python_parser/src/snapshots/ruff_python_parser__lexer__tests__string_continuation_with_unix_eol.snap
  crates/ruff_python_parser/src/snapshots/ruff_python_parser__lexer__tests__string_continuation_with_windows_eol.snap
  crates/ruff_python_parser/src/snapshots/ruff_python_parser__lexer__tests__triple_quoted_mac_eol.snap
  crates/ruff_python_parser/src/snapshots/ruff_python_parser__lexer__tests__triple_quoted_unix_eol.snap
  crates/ruff_python_parser/src/snapshots/ruff_python_parser__lexer__tests__triple_quoted_windows_eol.snap
Labels: internal

#7284 Invert condition for < and <= in outdated version block
  crates/ruff/resources/test/fixtures/pyupgrade/UP036_0.py
  crates/ruff/src/rules/pyupgrade/rules/outdated_version_block.rs
  crates/ruff/src/rules/pyupgrade/snapshots/ruff__rules__pyupgrade__tests__UP036_0.py.snap
Labels: bug

#7280 Add "Preview" section to auto-generated release notes
  .github/release.yml
Labels: documentation

#7207 Update preview and fix documentation symbols
  crates/ruff_dev/src/generate_rules_table.rs
Labels: documentation

#7274 Display the `--preview` option in the CLI help menu
  crates/ruff_cli/src/args.rs
  docs/configuration.md
Labels: preview

#7269 Bool expression comment placement
  crates/ruff_python_formatter/resources/test/fixtures/ruff/expression/binary.py
  crates/ruff_python_formatter/resources/test/fixtures/ruff/expression/boolean_operation.py
  crates/ruff_python_formatter/src/comments/placement.rs
  crates/ruff_python_formatter/src/expression/binary_like.rs
  crates/ruff_python_formatter/src/expression/expr_bin_op.rs
  crates/ruff_python_formatter/src/expression/expr_bool_op.rs
  crates/ruff_python_formatter/src/expression/expr_compare.rs
  crates/ruff_python_formatter/src/expression/expr_subscript.rs
  crates/ruff_python_formatter/tests/snapshots/format@expression__binary.py.snap
  crates/ruff_python_formatter/tests/snapshots/format@expression__boolean_operation.py.snap
  crates/ruff_python_formatter/tests/snapshots/format@expression__compare.py.snap
  crates/ruff_python_formatter/tests/snapshots/format@parentheses__nested.py.snap
Labels: formatter

#7287 Fix panic when formatting binary expression with two implicit concatenated string operands
  crates/ruff_python_formatter/resources/test/fixtures/ruff/expression/binary_implicit_string.py
  crates/ruff_python_formatter/src/expression/binary_like.rs
  crates/ruff_python_formatter/tests/snapshots/format@expression__binary_implicit_string.py.snap
Labels: formatter

#7224 Ignore `@override` method when enforcing `bad-dunder-name` rule
  crates/ruff/resources/test/fixtures/pylint/bad_dunder_method_name.py
  crates/ruff/src/rules/pylint/rules/bad_dunder_method_name.rs
  crates/ruff/src/rules/pylint/snapshots/ruff__rules__pylint__tests__PLW3201_bad_dunder_method_name.py.snap
Labels: bug

#7225 Add documentation to `duplicate-union-member`
  crates/ruff/src/rules/flake8_pyi/rules/duplicate_union_member.rs
Labels: documentation

#6863 Add `NotebookIndex` to the cache
  Cargo.lock
  crates/ruff/src/message/grouped.rs
  crates/ruff/src/message/mod.rs
  crates/ruff/src/message/text.rs
  crates/ruff/src/test.rs
  crates/ruff_cli/Cargo.toml
  crates/ruff_cli/src/cache.rs
  crates/ruff_cli/src/commands/check.rs
  crates/ruff_cli/src/diagnostics.rs
  crates/ruff_cli/src/printer.rs
  crates/ruff_notebook/src/index.rs
Labels: bug

#7311 Link discussion in formatter README
  crates/ruff_python_formatter/README.md
Labels: documentation, formatter

#7302 Introduce `ArgOrKeyword` to keep call parameter order
  Cargo.lock
  crates/ruff/src/autofix/edits.rs
  crates/ruff_python_ast/Cargo.toml
  crates/ruff_python_ast/src/helpers.rs
  crates/ruff_python_ast/src/node.rs
  crates/ruff_python_ast/src/nodes.rs
  crates/ruff_python_ast/src/visitor.rs
  crates/ruff_python_codegen/src/generator.rs
Labels: internal

#7268 Don't reorder parameters in function calls
  crates/ruff_python_ast/src/visitor.rs
  crates/ruff_python_formatter/resources/test/fixtures/ruff/expression/call.py
  crates/ruff_python_formatter/src/comments/placement.rs
  crates/ruff_python_formatter/src/other/arguments.rs
  crates/ruff_python_formatter/src/statement/stmt_function_def.rs
  crates/ruff_python_formatter/tests/snapshots/format@expression__call.py.snap
Labels: formatter

#7330 playground: Respect line-length and preview configuration
  crates/ruff_wasm/src/lib.rs
Labels: playground, formatter

#7301 Introduce `IndentWidth`
  crates/ruff_formatter/src/builders.rs
  crates/ruff_formatter/src/format_element.rs
  crates/ruff_formatter/src/format_element/document.rs
  crates/ruff_formatter/src/lib.rs
  crates/ruff_formatter/src/printer/mod.rs
  crates/ruff_formatter/src/printer/printer_options/mod.rs
  crates/ruff_python_formatter/resources/test/fixtures/black/simple_cases/docstring.options.json
  crates/ruff_python_formatter/resources/test/fixtures/ruff/docstring.options.json
  crates/ruff_python_formatter/resources/test/fixtures/ruff/fmt_on_off/fmt_off_docstring.options.json
  crates/ruff_python_formatter/resources/test/fixtures/ruff/fmt_on_off/indent.options.json
  crates/ruff_python_formatter/resources/test/fixtures/ruff/fmt_on_off/mixed_space_and_tab.options.json
  crates/ruff_python_formatter/resources/test/fixtures/ruff/tab_width.options.json
  crates/ruff_python_formatter/resources/test/fixtures/ruff/tab_width.py
  crates/ruff_python_formatter/src/comments/format.rs
  crates/ruff_python_formatter/src/expression/parentheses.rs
  crates/ruff_python_formatter/src/expression/string.rs
  crates/ruff_python_formatter/src/options.rs
  crates/ruff_python_formatter/tests/fixtures.rs
  crates/ruff_python_formatter/tests/snapshots/format@docstring.py.snap
  crates/ruff_python_formatter/tests/snapshots/format@expression__bytes.py.snap
  crates/ruff_python_formatter/tests/snapshots/format@expression__string.py.snap
  crates/ruff_python_formatter/tests/snapshots/format@fmt_on_off__fmt_off_docstring.py.snap
  crates/ruff_python_formatter/tests/snapshots/format@fmt_on_off__indent.py.snap
  crates/ruff_python_formatter/tests/snapshots/format@fmt_on_off__mixed_space_and_tab.py.snap
  crates/ruff_python_formatter/tests/snapshots/format@skip_magic_trailing_comma.py.snap
  crates/ruff_python_formatter/tests/snapshots/format@tab_width.py.snap
Labels: formatter

#7341 Display nursery rules as preview in documentation
  crates/ruff_dev/src/generate_rules_table.rs
Labels: documentation

#7335 chore: Upgrade pyproject-toml crate
  Cargo.lock
  crates/ruff/Cargo.toml
  crates/ruff_notebook/Cargo.toml
Labels: internal

#7337 chore: Upgrade strum
  Cargo.lock
  Cargo.toml
Labels: internal

#7351 Treat whitespace-only line as blank for D411
  crates/ruff/resources/test/fixtures/pydocstyle/sections.py
  crates/ruff/src/rules/pydocstyle/rules/sections.rs
  crates/ruff/src/rules/pydocstyle/snapshots/ruff__rules__pydocstyle__tests__D407_sections.py.snap
Labels: docstring

#7340 Add a benchmarking script for the formatter CLI
  scripts/benchmarks/poetry.lock
  scripts/benchmarks/pyproject.toml
  scripts/benchmarks/run_formatter.sh
Labels: formatter

#7356 Update deprecated-import lists based on recent typing-extension release
  crates/ruff/resources/test/fixtures/pyupgrade/UP035.py
  crates/ruff/src/rules/pyupgrade/rules/deprecated_import.rs
  crates/ruff/src/rules/pyupgrade/snapshots/ruff__rules__pyupgrade__tests__UP035.py.snap
Labels: rule

#7365 Parenthesize single-generator arguments when adding reverse keyword
  crates/ruff/resources/test/fixtures/flake8_comprehensions/C413.py
  crates/ruff/src/rules/flake8_comprehensions/fixes.rs
  crates/ruff/src/rules/flake8_comprehensions/snapshots/ruff__rules__flake8_comprehensions__tests__C413_C413.py.snap
Labels: bug

#7364 Move `FURB145` from nursery to preview
  crates/ruff/src/codes.rs
  crates/ruff/src/rule_selector.rs
  crates/ruff_workspace/src/configuration.rs
Labels: preview

#7279 Update release workflow to checkout the given sha
  .github/workflows/release.yaml
Labels: internal, release

#7210 Add warnings for nursery and preview rule selection
  crates/ruff_cli/tests/integration_test.rs
  crates/ruff_workspace/src/configuration.rs
Labels: preview

#7372 Invert reverse argument regardless of whether it's a boolean
  crates/ruff/resources/test/fixtures/flake8_comprehensions/C413.py
  crates/ruff/src/cst/helpers.rs
  crates/ruff/src/rules/flake8_comprehensions/fixes.rs
  crates/ruff/src/rules/flake8_comprehensions/snapshots/ruff__rules__flake8_comprehensions__tests__C413_C413.py.snap
  crates/ruff/src/rules/flake8_pytest_style/rules/assertion.rs
Labels: bug

#6179 [pylint] Implement `too-many-public-methods` rule (PLR0904)
  crates/ruff/resources/test/fixtures/pylint/too_many_public_methods.py
  crates/ruff/src/checkers/ast/analyze/statement.rs
  crates/ruff/src/codes.rs
  crates/ruff/src/rules/pylint/mod.rs
  crates/ruff/src/rules/pylint/rules/mod.rs
  crates/ruff/src/rules/pylint/rules/too_many_public_methods.rs
  crates/ruff/src/rules/pylint/settings.rs
  crates/ruff/src/rules/pylint/snapshots/ruff__rules__pylint__tests__too_many_public_methods.snap
  crates/ruff_python_semantic/src/analyze/visibility.rs
  crates/ruff_workspace/src/configuration.rs
  crates/ruff_workspace/src/options.rs
  ruff.schema.json
Labels: rule

#6659 Add support for the new f-string tokens per PEP 701
  Cargo.lock
  crates/ruff_python_parser/Cargo.toml
  crates/ruff_python_parser/src/lexer.rs
  crates/ruff_python_parser/src/lexer/cursor.rs
  crates/ruff_python_parser/src/lexer/fstring.rs
  crates/ruff_python_parser/src/snapshots/ruff_python_parser__lexer__tests__empty_fstrings.snap
  crates/ruff_python_parser/src/snapshots/ruff_python_parser__lexer__tests__fstring.snap
  crates/ruff_python_parser/src/snapshots/ruff_python_parser__lexer__tests__fstring_comments.snap
  crates/ruff_python_parser/src/snapshots/ruff_python_parser__lexer__tests__fstring_conversion.snap
  crates/ruff_python_parser/src/snapshots/ruff_python_parser__lexer__tests__fstring_escape.snap
  crates/ruff_python_parser/src/snapshots/ruff_python_parser__lexer__tests__fstring_escape_raw.snap
  crates/ruff_python_parser/src/snapshots/ruff_python_parser__lexer__tests__fstring_expression_multiline.snap
  crates/ruff_python_parser/src/snapshots/ruff_python_parser__lexer__tests__fstring_multiline.snap
  crates/ruff_python_parser/src/snapshots/ruff_python_parser__lexer__tests__fstring_named_unicode.snap
  crates/ruff_python_parser/src/snapshots/ruff_python_parser__lexer__tests__fstring_named_unicode_raw.snap
  crates/ruff_python_parser/src/snapshots/ruff_python_parser__lexer__tests__fstring_nested.snap
  crates/ruff_python_parser/src/snapshots/ruff_python_parser__lexer__tests__fstring_parentheses.snap
  crates/ruff_python_parser/src/snapshots/ruff_python_parser__lexer__tests__fstring_prefix.snap
  crates/ruff_python_parser/src/snapshots/ruff_python_parser__lexer__tests__fstring_with_format_spec.snap
  crates/ruff_python_parser/src/snapshots/ruff_python_parser__lexer__tests__fstring_with_ipy_escape_command.snap
  crates/ruff_python_parser/src/snapshots/ruff_python_parser__lexer__tests__fstring_with_lambda_expression.snap
  crates/ruff_python_parser/src/snapshots/ruff_python_parser__lexer__tests__fstring_with_named_expression.snap
  crates/ruff_python_parser/src/string.rs
  crates/ruff_python_parser/src/token.rs
Labels: parser, python312

#7041 Add support for parsing f-string as per PEP 701
  crates/ruff/src/linter.rs
  crates/ruff_benchmark/benches/formatter.rs
  crates/ruff_python_ast/src/nodes.rs
  crates/ruff_python_ast/tests/preorder.rs
  crates/ruff_python_ast/tests/visitor.rs
  crates/ruff_python_formatter/src/cli.rs
  crates/ruff_python_formatter/src/comments/mod.rs
  crates/ruff_python_formatter/src/lib.rs
  crates/ruff_python_parser/src/lib.rs
  crates/ruff_python_parser/src/parser.rs
  crates/ruff_python_parser/src/python.lalrpop
  crates/ruff_python_parser/src/python.rs
  crates/ruff_python_parser/src/snapshots/ruff_python_parser__parser__tests__fstrings.snap
  crates/ruff_python_parser/src/snapshots/ruff_python_parser__parser__tests__fstrings_with_unicode.snap
  crates/ruff_python_parser/src/snapshots/ruff_python_parser__string__tests__fstring_parse_self_documenting_base.snap
  crates/ruff_python_parser/src/snapshots/ruff_python_parser__string__tests__fstring_parse_self_documenting_base_more.snap
  crates/ruff_python_parser/src/snapshots/ruff_python_parser__string__tests__fstring_parse_self_documenting_format.snap
  crates/ruff_python_parser/src/snapshots/ruff_python_parser__string__tests__parse_empty_fstring.snap
  crates/ruff_python_parser/src/snapshots/ruff_python_parser__string__tests__parse_fstring.snap
  crates/ruff_python_parser/src/snapshots/ruff_python_parser__string__tests__parse_fstring_equals.snap
  crates/ruff_python_parser/src/snapshots/ruff_python_parser__string__tests__parse_fstring_nested_concatenation_string_spec.snap
  crates/ruff_python_parser/src/snapshots/ruff_python_parser__string__tests__parse_fstring_nested_spec.snap
  crates/ruff_python_parser/src/snapshots/ruff_python_parser__string__tests__parse_fstring_nested_string_spec.snap
  crates/ruff_python_parser/src/snapshots/ruff_python_parser__string__tests__parse_fstring_not_equals.snap
  crates/ruff_python_parser/src/snapshots/ruff_python_parser__string__tests__parse_fstring_not_nested_spec.snap
  crates/ruff_python_parser/src/snapshots/ruff_python_parser__string__tests__parse_fstring_self_doc_prec_space.snap
  crates/ruff_python_parser/src/snapshots/ruff_python_parser__string__tests__parse_fstring_self_doc_trailing_space.snap
  crates/ruff_python_parser/src/snapshots/ruff_python_parser__string__tests__parse_fstring_yield_expr.snap
  crates/ruff_python_parser/src/string.rs
  crates/ruff_shrinking/src/main.rs
  crates/ruff_wasm/src/lib.rs
Labels: parser, python312

#7211 Use narrow type for string parsing patterns
  crates/ruff_python_ast/src/nodes.rs
  crates/ruff_python_parser/src/python.lalrpop
  crates/ruff_python_parser/src/python.rs
  crates/ruff_python_parser/src/string.rs
Labels: internal, parser, python312

#7263 Disallow non-parenthesized lambda expr in f-string
  crates/ruff_python_ast/src/nodes.rs
  crates/ruff_python_parser/src/lexer.rs
  crates/ruff_python_parser/src/lexer/fstring.rs
  crates/ruff_python_parser/src/lib.rs
  crates/ruff_python_parser/src/python.lalrpop
  crates/ruff_python_parser/src/python.rs
  crates/ruff_python_parser/src/snapshots/ruff_python_parser__lexer__tests__fstring_escape.snap
  crates/ruff_python_parser/src/snapshots/ruff_python_parser__lexer__tests__fstring_escape_raw.snap
  crates/ruff_python_parser/src/snapshots/ruff_python_parser__lexer__tests__fstring_with_format_spec.snap
  crates/ruff_python_parser/src/snapshots/ruff_python_parser__lexer__tests__fstring_with_lambda_expression.snap
  crates/ruff_python_parser/src/string.rs
Labels: parser, python312

#7331 Fix curly brace escape handling in f-strings
  crates/ruff_python_parser/src/lexer.rs
  crates/ruff_python_parser/src/parser.rs
  crates/ruff_python_parser/src/snapshots/ruff_python_parser__lexer__tests__fstring_escape_braces.snap
  crates/ruff_python_parser/src/snapshots/ruff_python_parser__parser__tests__fstrings.snap
  crates/ruff_python_parser/src/string.rs
Labels: parser, python312

#7380 fix: Don't omit optional parentheses for subscripts
  crates/ruff_python_formatter/resources/test/fixtures/ruff/expression/slice.py
  crates/ruff_python_formatter/src/expression/expr_subscript.rs
  crates/ruff_python_formatter/src/expression/mod.rs
  crates/ruff_python_formatter/tests/snapshots/black_compatibility@simple_cases__expression.py.snap
  crates/ruff_python_formatter/tests/snapshots/format@expression__compare.py.snap
  crates/ruff_python_formatter/tests/snapshots/format@expression__slice.py.snap
Labels: formatter

#7373 Avoid re-parenthesizing call chains whose inner values are parenthesized
  crates/ruff_python_formatter/resources/test/fixtures/ruff/expression/attribute.py
  crates/ruff_python_formatter/resources/test/fixtures/ruff/expression/call.py
  crates/ruff_python_formatter/resources/test/fixtures/ruff/expression/subscript.py
  crates/ruff_python_formatter/src/expression/expr_attribute.rs
  crates/ruff_python_formatter/src/expression/expr_call.rs
  crates/ruff_python_formatter/src/expression/expr_subscript.rs
  crates/ruff_python_formatter/tests/snapshots/format@expression__attribute.py.snap
  crates/ruff_python_formatter/tests/snapshots/format@expression__call.py.snap
  crates/ruff_python_formatter/tests/snapshots/format@expression__subscript.py.snap
Labels: formatter

#7338 chore: Upgrade notify
  Cargo.lock
  crates/ruff_cli/Cargo.toml
Labels: internal

#7378 Allow `NUL` character in f-strings
  crates/ruff_python_parser/src/lexer.rs
  crates/ruff_python_parser/src/snapshots/ruff_python_parser__lexer__tests__fstring_with_nul_char.snap
Labels: parser, python312

#7386 fix: Group fluent subscript
  crates/ruff_python_formatter/resources/test/fixtures/ruff/expression/slice.py
  crates/ruff_python_formatter/src/expression/binary_like.rs
  crates/ruff_python_formatter/src/expression/expr_subscript.rs
  crates/ruff_python_formatter/tests/snapshots/format@expression__slice.py.snap
Labels: formatter

#7377 Catch panics in formatter
  crates/ruff/src/linter.rs
  crates/ruff_cli/src/commands/check.rs
  crates/ruff_cli/src/commands/format.rs
  crates/ruff_cli/src/lib.rs
  crates/ruff_python_formatter/src/lib.rs
Labels: formatter

#7363 Extend C416 to catch tuple unpacking
  crates/ruff/resources/test/fixtures/flake8_comprehensions/C416.py
  crates/ruff/src/rules/flake8_comprehensions/rules/unnecessary_comprehension.rs
  crates/ruff/src/rules/flake8_comprehensions/snapshots/ruff__rules__flake8_comprehensions__tests__C416_C416.py.snap
Labels: bug

#7374 Allow `NURSERY` in JSON Schema
  crates/ruff/src/rule_selector.rs
  ruff.schema.json
Labels: bug

#7391 Use dot references in docs for methods
  crates/ruff/src/rules/flake8_bugbear/rules/strip_with_multi_characters.rs
  crates/ruff/src/rules/flake8_builtins/rules/builtin_attribute_shadowing.rs
  crates/ruff/src/rules/flynt/rules/static_join_to_fstring.rs
  crates/ruff/src/rules/pylint/rules/bad_str_strip_call.rs
  crates/ruff/src/rules/pyupgrade/rules/f_strings.rs
  crates/ruff/src/rules/refurb/rules/check_and_remove_from_set.rs
  crates/ruff/src/rules/refurb/rules/slice_copy.rs
  crates/ruff_python_semantic/src/model.rs
  crates/ruff_source_file/src/locator.rs
  crates/ruff_source_file/src/newlines.rs
Labels: documentation

#7375 Show rule codes in shell tab completion
  crates/ruff/src/lib.rs
  crates/ruff/src/rule_selector.rs
  crates/ruff_cli/src/args.rs
  crates/ruff_cli/tests/integration_test.rs
  docs/configuration.md
Labels: cli

#7392 Avoid flagging single-quoted docstrings with continuations for multi-line rules
  crates/ruff/resources/test/fixtures/pydocstyle/D.py
  crates/ruff/src/docstrings/mod.rs
  crates/ruff/src/rules/pydocstyle/rules/blank_after_summary.rs
  crates/ruff/src/rules/pydocstyle/rules/newline_after_last_paragraph.rs
  crates/ruff/src/rules/pydocstyle/snapshots/ruff__rules__pydocstyle__tests__D204_D.py.snap
  crates/ruff/src/rules/pydocstyle/snapshots/ruff__rules__pydocstyle__tests__D300_D.py.snap
  crates/ruff/src/rules/pydocstyle/snapshots/ruff__rules__pydocstyle__tests__D400_D.py.snap
  crates/ruff/src/rules/pydocstyle/snapshots/ruff__rules__pydocstyle__tests__D415_D.py.snap
Labels: bug, docstring

#7393 Reflect conversion reason in UP012 messages
  crates/ruff/src/rules/pyupgrade/rules/unnecessary_encode_utf8.rs
  crates/ruff/src/rules/pyupgrade/snapshots/ruff__rules__pyupgrade__tests__UP012.py.snap
Labels: documentation

#6749 Add support for bounds, constraints, and explicit variance on generic type variables to UP040
  crates/ruff/resources/test/fixtures/pyupgrade/UP040.py
  crates/ruff/src/rules/pyupgrade/rules/use_pep695_type_alias.rs
  crates/ruff/src/rules/pyupgrade/snapshots/ruff__rules__pyupgrade__tests__UP040.py.snap
Labels: rule

#6132 [`perflint`] Add `PERF403`
  crates/ruff/resources/test/fixtures/perflint/PERF403.py
  crates/ruff/src/checkers/ast/analyze/statement.rs
  crates/ruff/src/codes.rs
  crates/ruff/src/rules/perflint/mod.rs
  crates/ruff/src/rules/perflint/rules/manual_dict_comprehension.rs
  crates/ruff/src/rules/perflint/rules/mod.rs
  crates/ruff/src/rules/perflint/snapshots/ruff__rules__perflint__tests__PERF403_PERF403.py.snap
  ruff.schema.json
Labels: rule

#7395 Add known problems to UP040 documentation
  crates/ruff/src/rules/pyupgrade/rules/use_pep695_type_alias.rs
Labels: documentation

#7396 Mark `PERF403` as a preview rule
  crates/ruff/src/codes.rs
  crates/ruff_workspace/src/configuration.rs
Labels: rule

#7397 [`flake8-logging`] Implement `LOG001`: `direct-logger-instantiation`
  crates/ruff/resources/test/fixtures/flake8_logging/LOG001.py
  crates/ruff/src/checkers/ast/analyze/expression.rs
  crates/ruff/src/codes.rs
  crates/ruff/src/rules/flake8_bugbear/rules/mutable_argument_default.rs
  crates/ruff/src/rules/flake8_logging/mod.rs
  crates/ruff/src/rules/flake8_logging/rules/direct_logger_instantiation.rs
  crates/ruff/src/rules/flake8_logging/rules/mod.rs
  crates/ruff/src/rules/flake8_logging/rules/undocumented_warn.rs
  crates/ruff/src/rules/flake8_logging/snapshots/ruff__rules__flake8_logging__tests__LOG001_LOG001.py.snap
  crates/ruff_workspace/src/configuration.rs
  ruff.schema.json
Labels: rule

#7398 Change CWE reference in documentation for S607 rule
  crates/ruff/src/rules/flake8_bandit/rules/shell_injection.rs
Labels: documentation

#7417 Fix release validation step
  .github/workflows/release.yaml
Labels: release

#7427 Format trailing operator comments as dangling
  crates/ruff_python_formatter/resources/test/fixtures/ruff/expression/unary.py
  crates/ruff_python_formatter/src/comments/placement.rs
  crates/ruff_python_formatter/src/expression/expr_unary_op.rs
  crates/ruff_python_formatter/tests/snapshots/format@expression__unary.py.snap
Labels: formatter

#7419 Move documentation to docs.astral.sh/ruff
  .github/workflows/docs.yaml
  .github/workflows/playground.yaml
  BREAKING_CHANGES.md
  CONTRIBUTING.md
  Cargo.toml
  README.md
  crates/flake8_to_ruff/README.md
  crates/ruff/src/message/snapshots/ruff__message__json__tests__output.snap
  crates/ruff/src/message/snapshots/ruff__message__json_lines__tests__output.snap
  crates/ruff/src/rules/pydocstyle/rules/blank_before_after_class.rs
  crates/ruff/src/rules/pydocstyle/rules/multi_line_summary_start.rs
  crates/ruff/src/rules/pygrep_hooks/rules/blanket_noqa.rs
  crates/ruff/src/rules/ruff/rules/unused_noqa.rs
  crates/ruff_cli/tests/snapshots/integration_test__stdin_json.snap
  crates/ruff_dev/src/generate_options.rs
  crates/ruff_dev/src/generate_rules_table.rs
  crates/ruff_python_formatter/README.md
  crates/ruff_workspace/src/options.rs
  docs/faq.md
  docs/preview.md
  mkdocs.template.yml
  pyproject.toml
  ruff.schema.json
  scripts/generate_mkdocs.py
Labels: documentation

#7430 Change playground to use `pages deploy`
  .github/workflows/playground.yaml
Labels: internal

#7360 Use CommentRanges in backwards lexing
  Cargo.lock
  crates/ruff/src/checkers/noqa.rs
  crates/ruff/src/noqa.rs
  crates/ruff/src/rules/flake8_pytest_style/rules/parametrize.rs
  crates/ruff/src/rules/flake8_simplify/rules/ast_bool_op.rs
  crates/ruff/src/rules/flake8_simplify/rules/ast_ifexp.rs
  crates/ruff/src/rules/flake8_simplify/rules/key_in_dict.rs
  crates/ruff/src/rules/pandas_vet/rules/inplace_argument.rs
  crates/ruff/src/rules/pycodestyle/helpers.rs
  crates/ruff/src/rules/pycodestyle/rules/literal_comparisons.rs
  crates/ruff/src/rules/pycodestyle/rules/not_tests.rs
  crates/ruff/src/rules/pyflakes/fixes.rs
  crates/ruff/src/rules/pyflakes/rules/unused_variable.rs
  crates/ruff/src/rules/pyupgrade/rules/yield_in_for_loop.rs
  crates/ruff_python_ast/src/parenthesize.rs
  crates/ruff_python_ast/tests/parenthesize.rs
  crates/ruff_python_formatter/src/comments/debug.rs
  crates/ruff_python_formatter/src/comments/mod.rs
  crates/ruff_python_formatter/src/comments/placement.rs
  crates/ruff_python_formatter/src/comments/visitor.rs
  crates/ruff_python_formatter/src/expression/binary_like.rs
  crates/ruff_python_formatter/src/expression/expr_attribute.rs
  crates/ruff_python_formatter/src/expression/expr_call.rs
  crates/ruff_python_formatter/src/expression/expr_if_exp.rs
  crates/ruff_python_formatter/src/expression/expr_subscript.rs
  crates/ruff_python_formatter/src/expression/expr_unary_op.rs
  crates/ruff_python_formatter/src/expression/mod.rs
  crates/ruff_python_formatter/src/expression/parentheses.rs
  crates/ruff_python_formatter/src/lib.rs
  crates/ruff_python_formatter/src/pattern/mod.rs
  crates/ruff_python_formatter/src/statement/suite.rs
  crates/ruff_python_index/src/comment_ranges.rs
  crates/ruff_python_index/src/indexer.rs
  crates/ruff_python_index/src/lib.rs
  crates/ruff_python_trivia/Cargo.toml
  crates/ruff_python_trivia/src/comment_ranges.rs
  crates/ruff_python_trivia/src/cursor.rs
  crates/ruff_python_trivia/src/lib.rs
  crates/ruff_python_trivia/src/tokenizer.rs
  crates/ruff_wasm/Cargo.toml
  crates/ruff_wasm/src/lib.rs
Labels: internal

#7409 fix: Use BestFit layout for subscript
  crates/ruff_python_formatter/resources/test/fixtures/ruff/expression/call.py
  crates/ruff_python_formatter/resources/test/fixtures/ruff/statement/assign.py
  crates/ruff_python_formatter/resources/test/fixtures/ruff/statement/return_annotation.py
  crates/ruff_python_formatter/src/expression/expr_call.rs
  crates/ruff_python_formatter/src/expression/expr_subscript.rs
  crates/ruff_python_formatter/src/lib.rs
  crates/ruff_python_formatter/tests/snapshots/format@expression__call.py.snap
  crates/ruff_python_formatter/tests/snapshots/format@statement__assign.py.snap
  crates/ruff_python_formatter/tests/snapshots/format@statement__return_annotation.py.snap
Labels: formatter

#7437 Fix build
  crates/ruff_python_formatter/src/comments/mod.rs
  crates/ruff_python_formatter/src/expression/expr_call.rs
  crates/ruff_python_formatter/src/expression/expr_subscript.rs
Labels: internal

#7399 [`flake8-logging`] Implement `LOG002`: `invalid-get-logger-argument`
  crates/ruff/resources/test/fixtures/flake8_logging/LOG002.py
  crates/ruff/src/checkers/ast/analyze/expression.rs
  crates/ruff/src/codes.rs
  crates/ruff/src/rules/flake8_logging/mod.rs
  crates/ruff/src/rules/flake8_logging/rules/invalid_get_logger_argument.rs
  crates/ruff/src/rules/flake8_logging/rules/mod.rs
  crates/ruff/src/rules/flake8_logging/snapshots/ruff__rules__flake8_logging__tests__LOG002_LOG002.py.snap
  crates/ruff_python_stdlib/src/builtins.rs
  crates/ruff_workspace/src/configuration.rs
  ruff.schema.json
Labels: rule

#7428 Avoid extra parentheses in unary expressions
  crates/ruff_python_formatter/resources/test/fixtures/ruff/expression/unary.py
  crates/ruff_python_formatter/src/expression/expr_unary_op.rs
  crates/ruff_python_formatter/tests/snapshots/format@expression__unary.py.snap
Labels: formatter

#7424 Avoid extra parentheses in `await` expressions
  crates/ruff_python_formatter/resources/test/fixtures/ruff/expression/await.py
  crates/ruff_python_formatter/src/expression/expr_await.rs
  crates/ruff_python_formatter/tests/snapshots/format@expression__await.py.snap
Labels: formatter

#7429 Avoiding grouping comprehension targets separately from conditions
  crates/ruff_python_formatter/resources/test/fixtures/ruff/expression/list_comp.py
  crates/ruff_python_formatter/src/other/comprehension.rs
  crates/ruff_python_formatter/tests/snapshots/format@expression__list_comp.py.snap
Labels: formatter

#7442 Fix broken `is_expression_parenthesized` call from rebase
  crates/ruff_python_formatter/src/expression/expr_await.rs
Labels: internal

#7432 Modify `comment_ranges` slice in `BackwardsTokenizer`
  crates/ruff_python_trivia/src/tokenizer.rs
Labels: internal

#7444 Avoid extra parentheses in `yield` expressions
  crates/ruff_python_formatter/resources/test/fixtures/ruff/expression/yield.py
  crates/ruff_python_formatter/src/expression/expr_yield.rs
  crates/ruff_python_formatter/tests/snapshots/format@expression__yield.py.snap
Labels: formatter

#7435 Refactor `tab-indentation` as a token-based rule
  crates/ruff/resources/test/fixtures/pycodestyle/W19.py
  crates/ruff/src/checkers/physical_lines.rs
  crates/ruff/src/checkers/tokens.rs
  crates/ruff/src/registry.rs
  crates/ruff/src/rules/pycodestyle/rules/tab_indentation.rs
  crates/ruff/src/rules/pycodestyle/snapshots/ruff__rules__pycodestyle__tests__W191_W19.py.snap
Labels: internal

#7461 Add padding to prevent some autofix errors
  crates/ruff/resources/test/fixtures/flake8_bugbear/B009_B010.py
  crates/ruff/resources/test/fixtures/pycodestyle/E713.py
  crates/ruff/resources/test/fixtures/pylint/repeated_isinstance_calls.py
  crates/ruff/resources/test/fixtures/pyupgrade/UP003.py
  crates/ruff/resources/test/fixtures/pyupgrade/UP012.py
  crates/ruff/src/rules/flake8_bugbear/rules/getattr_with_constant.rs
  crates/ruff/src/rules/flake8_bugbear/snapshots/ruff__rules__flake8_bugbear__tests__B009_B009_B010.py.snap
  crates/ruff/src/rules/flake8_bugbear/snapshots/ruff__rules__flake8_bugbear__tests__B010_B009_B010.py.snap
  crates/ruff/src/rules/pycodestyle/rules/not_tests.rs
  crates/ruff/src/rules/pycodestyle/snapshots/ruff__rules__pycodestyle__tests__E713_E713.py.snap
  crates/ruff/src/rules/pylint/rules/repeated_isinstance_calls.rs
  crates/ruff/src/rules/pylint/snapshots/ruff__rules__pylint__tests__PLR1701_repeated_isinstance_calls.py.snap
  crates/ruff/src/rules/pylint/snapshots/ruff__rules__pylint__tests__repeated_isinstance_calls.snap
  crates/ruff/src/rules/pyupgrade/rules/type_of_primitive.rs
  crates/ruff/src/rules/pyupgrade/rules/unnecessary_encode_utf8.rs
  crates/ruff/src/rules/pyupgrade/snapshots/ruff__rules__pyupgrade__tests__UP003.py.snap
  crates/ruff/src/rules/pyupgrade/snapshots/ruff__rules__pyupgrade__tests__UP012.py.snap
Labels: bug
