Repository astral-sh/ruff, pull requests merged in 2023-04, with the labels that each got.

#3835 When checking module visibility, don't check entire ancestry
  crates/ruff/resources/test/fixtures/pydocstyle/_unrelated/_no_pkg_priv.py
  crates/ruff/resources/test/fixtures/pydocstyle/_unrelated/pkg/D100_pub.py
  crates/ruff/resources/test/fixtures/pydocstyle/_unrelated/pkg/__init__.py
  crates/ruff/resources/test/fixtures/pydocstyle/_unrelated/pkg/_priv/__init__.py
  crates/ruff/resources/test/fixtures/pydocstyle/_unrelated/pkg/_priv/no_D100_priv.py
  crates/ruff/src/rules/pydocstyle/mod.rs
  crates/ruff/src/rules/pydocstyle/snapshots/ruff__rules__pydocstyle__tests__D100__unrelated___no_pkg_priv.py.snap
  crates/ruff/src/rules/pydocstyle/snapshots/ruff__rules__pydocstyle__tests__D100__unrelated__pkg__D100_pub.py.snap
  crates/ruff/src/rules/pydocstyle/snapshots/ruff__rules__pydocstyle__tests__D100__unrelated__pkg___priv__no_D100_priv.py.snap
  crates/ruff_python_ast/src/context.rs
  crates/ruff_python_ast/src/visibility.rs
Labels: bug

#3874 [`flake8-simplify`] Implement `dict-get-with-none-default` (`SIM910`)
  crates/ruff/resources/test/fixtures/flake8_simplify/SIM910.py
  crates/ruff/src/checkers/ast/mod.rs
  crates/ruff/src/codes.rs
  crates/ruff/src/registry.rs
  crates/ruff/src/rules/flake8_simplify/mod.rs
  crates/ruff/src/rules/flake8_simplify/rules/ast_expr.rs
  crates/ruff/src/rules/flake8_simplify/rules/mod.rs
  crates/ruff/src/rules/flake8_simplify/snapshots/ruff__rules__flake8_simplify__tests__SIM910_SIM910.py.snap
  ruff.schema.json
Labels: rule

#3920 Remove `extract_path_names` helper
  crates/ruff/src/fs.rs
  crates/ruff/src/resolver.rs
Labels: internal

#3915 [`flake8-simplify`] Add autofix for `contextlib.suppress` (`SIM105`)
  crates/ruff/src/rules/flake8_simplify/rules/suppressible_exception.rs
  crates/ruff/src/rules/flake8_simplify/snapshots/ruff__rules__flake8_simplify__tests__SIM105_SIM105.py.snap
Labels: rule, autofix

#3897 Store source code on message
  Cargo.lock
  crates/ruff/Cargo.toml
  crates/ruff/src/autofix/actions.rs
  crates/ruff/src/autofix/mod.rs
  crates/ruff/src/importer.rs
  crates/ruff/src/linter.rs
  crates/ruff/src/message/grouped.rs
  crates/ruff/src/message/mod.rs
  crates/ruff/src/message/text.rs
  crates/ruff/src/rules/flake8_return/helpers.rs
  crates/ruff/src/rules/isort/helpers.rs
  crates/ruff/src/rules/pyflakes/rules/unused_variable.rs
  crates/ruff/src/rules/pyupgrade/fixes.rs
  crates/ruff_cli/src/cache.rs
  crates/ruff_cli/src/diagnostics.rs
  crates/ruff_python_ast/src/helpers.rs
  crates/ruff_python_ast/src/source_code/line_index.rs
  crates/ruff_python_ast/src/source_code/locator.rs
  crates/ruff_python_ast/src/source_code/mod.rs
  crates/ruff_python_formatter/src/cst/helpers.rs
Labels: internal

#3904 Introduce SourceFile to avoid cloning the message filename
  crates/ruff/src/linter.rs
  crates/ruff/src/message/azure.rs
  crates/ruff/src/message/github.rs
  crates/ruff/src/message/gitlab.rs
  crates/ruff/src/message/grouped.rs
  crates/ruff/src/message/json.rs
  crates/ruff/src/message/junit.rs
  crates/ruff/src/message/mod.rs
  crates/ruff/src/message/pylint.rs
  crates/ruff/src/message/text.rs
  crates/ruff_cli/src/cache.rs
  crates/ruff_cli/src/commands/run.rs
  crates/ruff_cli/src/diagnostics.rs
  crates/ruff_python_ast/src/source_code/locator.rs
  crates/ruff_python_ast/src/source_code/mod.rs
Labels: internal

#3954 Clarify some isort differences in FAQ
  docs/faq.md
Labels: documentation

#3959 Add docs for assert rule (S101)
  crates/ruff/src/checkers/ast/mod.rs
  crates/ruff/src/rules/flake8_bandit/rules/assert_used.rs
Labels: documentation

#3960 Ignore assert errors (S101) in `TYPE_CHECKING` blocks
  crates/ruff/resources/test/fixtures/flake8_bandit/S101.py
  crates/ruff/src/checkers/ast/mod.rs
  crates/ruff/src/rules/flake8_bandit/snapshots/ruff__rules__flake8_bandit__tests__S101_S101.py.snap
Labels: rule

#3962 Add 'or if cond' to `E712` message
  crates/ruff/src/rules/pycodestyle/rules/literal_comparisons.rs
  crates/ruff/src/rules/pycodestyle/snapshots/ruff__rules__pycodestyle__tests__E712_E712.py.snap
  crates/ruff/src/rules/pycodestyle/snapshots/ruff__rules__pycodestyle__tests__constant_literals.snap
Labels: bug

#3968 Add multi-edit change to BREAKING_CHANGES.md
  BREAKING_CHANGES.md
Labels: breaking

#3969 Implement `unnecessary-literal-within-dict-call` (`C418`)
  crates/ruff/resources/test/fixtures/flake8_comprehensions/C418.py
  crates/ruff/src/checkers/ast/mod.rs
  crates/ruff/src/codes.rs
  crates/ruff/src/registry.rs
  crates/ruff/src/rules/flake8_comprehensions/fixes.rs
  crates/ruff/src/rules/flake8_comprehensions/mod.rs
  crates/ruff/src/rules/flake8_comprehensions/rules/mod.rs
  crates/ruff/src/rules/flake8_comprehensions/rules/unnecessary_literal_within_dict_call.rs
  crates/ruff/src/rules/flake8_comprehensions/rules/unnecessary_literal_within_list_call.rs
  crates/ruff/src/rules/flake8_comprehensions/rules/unnecessary_literal_within_tuple_call.rs
  crates/ruff/src/rules/flake8_comprehensions/snapshots/ruff__rules__flake8_comprehensions__tests__C418_C418.py.snap
  ruff.schema.json
Labels: rule

#3990 Add parser benchmark
  Cargo.lock
  crates/ruff_benchmark/Cargo.toml
  crates/ruff_benchmark/benches/parser.rs
Labels: internal

#4004 Ignore argument assignments when enforcing `RET504`
  crates/ruff/resources/test/fixtures/flake8_return/RET504.py
  crates/ruff/src/rules/flake8_return/rules.rs
  crates/ruff/src/rules/flake8_return/snapshots/ruff__rules__flake8_return__tests__RET504_RET504.py.snap
  crates/ruff/src/rules/flake8_return/visitor.rs
Labels: bug

#4006 Fix (doc-)line-too-long start location
  crates/ruff/src/rules/pycodestyle/helpers.rs
  crates/ruff/src/rules/pycodestyle/rules/doc_line_too_long.rs
  crates/ruff/src/rules/pycodestyle/rules/line_too_long.rs
  crates/ruff/src/rules/pycodestyle/snapshots/ruff__rules__pycodestyle__tests__E501_E501.py.snap
Labels: bug

#4052 [`flake8-bugbear`] Add `pytest.raises(Exception)` support to B017
  crates/ruff/resources/test/fixtures/flake8_bugbear/B017.py
  crates/ruff/src/rules/flake8_bugbear/rules/assert_raises_exception.rs
  crates/ruff/src/rules/flake8_bugbear/snapshots/ruff__rules__flake8_bugbear__tests__B017_B017.py.snap
Labels: rule

#4068 Use `Context` for pep8-naming helpers
  crates/ruff/src/rules/pep8_naming/helpers.rs
  crates/ruff/src/rules/pep8_naming/rules/mixed_case_variable_in_class_scope.rs
  crates/ruff/src/rules/pep8_naming/rules/mixed_case_variable_in_global_scope.rs
  crates/ruff/src/rules/pep8_naming/rules/non_lowercase_variable_in_function.rs
Labels: internal

#4042 Add docs for tryceratops rules
  crates/ruff/src/rules/tryceratops/rules/error_instead_of_exception.rs
  crates/ruff/src/rules/tryceratops/rules/raise_vanilla_args.rs
  crates/ruff/src/rules/tryceratops/rules/raise_within_try.rs
  crates/ruff/src/rules/tryceratops/rules/reraise_no_cause.rs
  crates/ruff/src/rules/tryceratops/rules/try_consider_else.rs
  crates/ruff/src/rules/tryceratops/rules/type_check_without_type_error.rs
  crates/ruff/src/rules/tryceratops/rules/verbose_raise.rs
Labels: documentation

#4040 [`flake8-import-conventions`] Implement new rule `ICN003` to ban `from ... import ...` for selected modules
  crates/ruff/resources/test/fixtures/flake8_import_conventions/custom_banned_from.py
  crates/ruff/src/checkers/ast/mod.rs
  crates/ruff/src/codes.rs
  crates/ruff/src/registry.rs
  crates/ruff/src/rules/flake8_import_conventions/mod.rs
  crates/ruff/src/rules/flake8_import_conventions/rules/check_banned_import_from.rs
  crates/ruff/src/rules/flake8_import_conventions/rules/mod.rs
  crates/ruff/src/rules/flake8_import_conventions/settings.rs
  crates/ruff/src/rules/flake8_import_conventions/snapshots/ruff__rules__flake8_import_conventions__tests__custom_banned_from.snap
  crates/ruff/src/settings/pyproject.rs
  ruff.schema.json
Labels: rule

#4074 Avoid infinite-propagation of inline comments when force-splitting imports
  crates/ruff/resources/test/fixtures/isort/propagate_inline_comments.py
  crates/ruff/src/rules/isort/mod.rs
  crates/ruff/src/rules/isort/normalize.rs
  crates/ruff/src/rules/isort/snapshots/ruff__rules__isort__tests__force_single_line_force_single_line.py.snap
  crates/ruff/src/rules/isort/snapshots/ruff__rules__isort__tests__propagate_inline_comments_propagate_inline_comments.py.snap
Labels: bug, isort

#4075 [`pylint`] Implement PLE0302 `unexpected-special-method-signature`
  crates/ruff/resources/test/fixtures/pylint/unexpected_special_method_signature.py
  crates/ruff/src/checkers/ast/mod.rs
  crates/ruff/src/codes.rs
  crates/ruff/src/registry.rs
  crates/ruff/src/rules/pylint/mod.rs
  crates/ruff/src/rules/pylint/rules/mod.rs
  crates/ruff/src/rules/pylint/rules/unexpected_special_method_signature.rs
  crates/ruff/src/rules/pylint/snapshots/ruff__rules__pylint__tests__PLE0302_unexpected_special_method_signature.py.snap
  ruff.schema.json
Labels: rule

#4067 Unify positional and keyword arguments when checking for missing arguments in docstring
  crates/ruff/resources/test/fixtures/pydocstyle/D417.py
  crates/ruff/src/docstrings/google.rs
  crates/ruff/src/docstrings/numpy.rs
  crates/ruff/src/docstrings/sections.rs
  crates/ruff/src/rules/pydocstyle/rules/sections.rs
Labels: bug, docstring

#3985 Use `memchr` to speedup newline search on x86
  Cargo.lock
  crates/ruff/src/importer.rs
  crates/ruff/src/message/gitlab.rs
  crates/ruff/src/noqa.rs
  crates/ruff_python_ast/Cargo.toml
  crates/ruff_python_ast/src/newlines.rs
  crates/ruff_python_ast/src/source_code/generator.rs
  crates/ruff_python_ast/src/source_code/locator.rs
  crates/ruff_python_ast/src/source_code/mod.rs
  crates/ruff_python_ast/src/source_code/stylist.rs
Labels: internal

#4110 Make D410/D411 autofixes mutually exclusive
  crates/ruff/src/rules/pydocstyle/rules/sections.rs
Labels: bug, docstring

#4141 Document RUF100
  crates/ruff/src/rules/ruff/rules/unused_noqa.rs
Labels: documentation

#4144 Document flake8-print
  crates/ruff/src/rules/flake8_print/rules/print_call.rs
Labels: documentation

#4142 Document flake8-commas
  crates/ruff/src/rules/flake8_commas/rules.rs
Labels: documentation

#4149 Add remaining pep8-naming docs
  crates/ruff/src/rules/pep8_naming/rules/invalid_argument_name.rs
  crates/ruff/src/rules/pep8_naming/rules/mixed_case_variable_in_class_scope.rs
  crates/ruff/src/rules/pep8_naming/rules/mixed_case_variable_in_global_scope.rs
Labels: documentation

#4147 Document `flake8-unused-arguments`
  crates/ruff/src/rules/flake8_unused_arguments/rules.rs
Labels: documentation
