Repository astral-sh/ruff, pull requests merged in 2023-02, with the labels that each got.

#2449 Only avoid PEP604 rewrites for pre-Python 3.10 code
  README.md
  ruff.schema.json
  src/checkers/ast.rs
  src/rules/pyupgrade/settings.rs
  src/rules/pyupgrade/snapshots/ruff__rules__pyupgrade__tests__future_annotations_pep_604_py310.snap
Labels: bug

#2468 Use LibCST to reverse Yoda conditions
  resources/test/fixtures/flake8_simplify/SIM300.py
  src/cst/matchers.rs
  src/rules/flake8_simplify/rules/yoda_conditions.rs
  src/rules/flake8_simplify/snapshots/ruff__rules__flake8_simplify__tests__SIM300_SIM300.py.snap
  src/violations.rs
Labels: bug

#2099 [`pyupgrade`]: Remove outdated `sys.version_info` blocks
  Cargo.toml
  README.md
  foo.py
  resources/test/fixtures/pyupgrade/UP036_0.py
  resources/test/fixtures/pyupgrade/UP036_1.py
  resources/test/fixtures/pyupgrade/UP036_2.py
  resources/test/fixtures/pyupgrade/UP036_3.py
  resources/test/fixtures/pyupgrade/UP036_4.py
  ruff.schema.json
  setup.py
  src/checkers/ast.rs
  src/registry.rs
  src/rules/pyupgrade/fixes.rs
  src/rules/pyupgrade/mod.rs
  src/rules/pyupgrade/rules/mod.rs
  src/rules/pyupgrade/rules/outdated_version_block.rs
  src/rules/pyupgrade/snapshots/ruff__rules__pyupgrade__tests__UP036_UP036_0.py.snap
  src/rules/pyupgrade/snapshots/ruff__rules__pyupgrade__tests__UP036_UP036_1.py.snap
  src/rules/pyupgrade/snapshots/ruff__rules__pyupgrade__tests__UP036_UP036_2.py.snap
  src/rules/pyupgrade/snapshots/ruff__rules__pyupgrade__tests__UP036_UP036_3.py.snap
  src/rules/pyupgrade/snapshots/ruff__rules__pyupgrade__tests__UP036_UP036_4.py.snap
  src/settings/types.rs
Labels: rule

#2476 fix: assertTrue()/assertFalse() fixer should not test for identity
  src/rules/flake8_pytest_style/rules/unittest_assert.rs
  src/rules/flake8_pytest_style/snapshots/ruff__rules__flake8_pytest_style__tests__PT009.snap
Labels: bug

#2509 Avoid renaming unused loop variables with deferred usages
  resources/test/fixtures/flake8_bugbear/B007.py
  src/checkers/ast.rs
  src/rules/flake8_bugbear/rules/unused_loop_control_variable.rs
  src/rules/flake8_bugbear/snapshots/ruff__rules__flake8_bugbear__tests__B007_B007.py.snap
Labels: bug

#2543 Exit upon showing files with `--show-files`
  ruff_cli/src/main.rs
Labels: bug

#2551 Update RustPython to pull in lexer optimizations
  Cargo.lock
  Cargo.toml
  ruff_dev/Cargo.toml
Labels: performance

#2554 Move benchmarking instructions to CONTRIBUTING.md
  CONTRIBUTING.md
  README.md
Labels: documentation

#2565 Ignore direct root-children in implicit-namespace-package
  src/checkers/filesystem.rs
  src/rules/flake8_no_pep420/rules.rs
Labels: bug

#2581 Avoid infinite renames for unused-loop-control-variable
  resources/test/fixtures/flake8_bugbear/B007.py
  src/rules/flake8_bugbear/rules/unused_loop_control_variable.rs
  src/rules/flake8_bugbear/snapshots/ruff__rules__flake8_bugbear__tests__B007_B007.py.snap
Labels: bug, autofix

#2431 [`pyupgrade`]: Removes quotes from annotations
  README.md
  resources/test/fixtures/pyupgrade/UP037.py
  ruff.schema.json
  src/checkers/ast.rs
  src/registry.rs
  src/rules/pyupgrade/mod.rs
  src/rules/pyupgrade/rules/mod.rs
  src/rules/pyupgrade/rules/quoted_annotation.rs
  src/rules/pyupgrade/snapshots/ruff__rules__pyupgrade__tests__UP037_UP037.py.snap
Labels: rule

#2593 Move `python` into its own `ruff_python` crate
  CONTRIBUTING.md
  Cargo.lock
  crates/ruff/Cargo.toml
  crates/ruff/src/ast/mod.rs
  crates/ruff/src/ast/typing.rs
  crates/ruff/src/checkers/ast.rs
  crates/ruff/src/lib.rs
  crates/ruff/src/rules/flake8_bugbear/rules/getattr_with_constant.rs
  crates/ruff/src/rules/flake8_bugbear/rules/raise_without_from_inside_except.rs
  crates/ruff/src/rules/flake8_bugbear/rules/setattr_with_constant.rs
  crates/ruff/src/rules/flake8_builtins/rules.rs
  crates/ruff/src/rules/flake8_pie/rules.rs
  crates/ruff/src/rules/flake8_simplify/rules/yoda_conditions.rs
  crates/ruff/src/rules/isort/categorize.rs
  crates/ruff/src/rules/isort/sorting.rs
  crates/ruff/src/rules/pep8_naming/helpers.rs
  crates/ruff/src/rules/pep8_naming/rules.rs
  crates/ruff/src/rules/pyflakes/fixes.rs
  crates/ruff/src/rules/pyflakes/rules/imports.rs
  crates/ruff/src/rules/pyupgrade/rules/convert_named_tuple_functional_to_class.rs
  crates/ruff/src/rules/pyupgrade/rules/convert_typed_dict_functional_to_class.rs
  crates/ruff/src/rules/pyupgrade/rules/printf_string_formatting.rs
  crates/ruff/src/settings/types.rs
  crates/ruff_python/Cargo.toml
  crates/ruff_python/src/builtins.rs
  crates/ruff_python/src/future.rs
  crates/ruff_python/src/identifiers.rs
  crates/ruff_python/src/keyword.rs
  crates/ruff_python/src/lib.rs
  crates/ruff_python/src/string.rs
  crates/ruff_python/src/sys.rs
  crates/ruff_python/src/typing.rs
  scripts/generate_known_standard_library.py
Labels: internal

#2594 Remove unnecessary `super_args.rs`
  crates/ruff/src/ast/helpers.rs
  crates/ruff/src/rules/pyupgrade/rules/mod.rs
  crates/ruff/src/rules/pyupgrade/rules/super_args.rs
  crates/ruff/src/rules/pyupgrade/rules/super_call_with_parameters.rs
Labels: internal

#2597 Allow blank line before sticky-comment functions in docstrings
  crates/ruff/resources/test/fixtures/pydocstyle/D202.py
  crates/ruff/src/rules/pydocstyle/mod.rs
  crates/ruff/src/rules/pydocstyle/rules/backslashes.rs
  crates/ruff/src/rules/pydocstyle/rules/blank_before_after_class.rs
  crates/ruff/src/rules/pydocstyle/rules/blank_before_after_function.rs
  crates/ruff/src/rules/pydocstyle/rules/mod.rs
  crates/ruff/src/rules/pydocstyle/rules/regexes.rs
  crates/ruff/src/rules/pydocstyle/snapshots/ruff__rules__pydocstyle__tests__D202_D202.py.snap
Labels: bug, docstring

#2607 Visit deferred assignments after deferred type annotations
  crates/ruff/resources/test/fixtures/pyflakes/F841_2.py
  crates/ruff/src/checkers/ast.rs
Labels: bug

#2570 [`pylint`]: bad-str-strip-call (With Autofix)
  README.md
  crates/ruff/resources/test/fixtures/pylint/bad_str_strip_call.py
  crates/ruff/src/checkers/ast.rs
  crates/ruff/src/registry.rs
  crates/ruff/src/rules/pylint/mod.rs
  crates/ruff/src/rules/pylint/rules/bad_str_strip_call.rs
  crates/ruff/src/rules/pylint/rules/mod.rs
  crates/ruff/src/rules/pylint/snapshots/ruff__rules__pylint__tests__PLE1310_bad_str_strip_call.py.snap
  ruff.schema.json
Labels: rule

#2611 fix(pep8-naming): `typing.NamedTuple` and `typing.TypedDict` treatment
  crates/ruff/resources/test/fixtures/pep8_naming/N806.py
  crates/ruff/resources/test/fixtures/pep8_naming/N815.py
  crates/ruff/resources/test/fixtures/pep8_naming/N816.py
  crates/ruff/src/rules/pep8_naming/helpers.rs
  crates/ruff/src/rules/pep8_naming/rules.rs
  crates/ruff/src/rules/pep8_naming/snapshots/ruff__rules__pep8_naming__tests__N806_N806.py.snap
  crates/ruff/src/rules/pep8_naming/snapshots/ruff__rules__pep8_naming__tests__N815_N815.py.snap
  crates/ruff/src/rules/pep8_naming/snapshots/ruff__rules__pep8_naming__tests__N816_N816.py.snap
Labels: bug

#2617 Support `ignore-names` for all relevant pep8-naming rules
  crates/ruff/resources/test/fixtures/pep8_naming/N803.py
  crates/ruff/src/checkers/ast.rs
  crates/ruff/src/rules/pep8_naming/rules.rs
Labels: bug

#2616 Add flake8-pie single_starts_ends_with
  README.md
  crates/ruff/resources/test/fixtures/flake8_pie/PIE810.py
  crates/ruff/src/checkers/ast.rs
  crates/ruff/src/registry.rs
  crates/ruff/src/rules/flake8_pie/mod.rs
  crates/ruff/src/rules/flake8_pie/rules.rs
  crates/ruff/src/rules/flake8_pie/snapshots/ruff__rules__flake8_pie__tests__PIE810_PIE810.py.snap
  ruff.schema.json
  src/registry.rs
Labels: rule

#2589 [`pylint`]: bidirectional-unicode
  README.md
  crates/ruff/resources/test/fixtures/pylint/bidirectional_unicode.py
  crates/ruff/src/checkers/ast.rs
  crates/ruff/src/registry.rs
  crates/ruff/src/rules/pylint/mod.rs
  crates/ruff/src/rules/pylint/rules/bidirectional_unicode.rs
  crates/ruff/src/rules/pylint/rules/mod.rs
  crates/ruff/src/rules/pylint/snapshots/ruff__rules__pylint__tests__PLE2402_bidirectional_unicode.py.snap
  crates/ruff/src/rules/pylint/snapshots/ruff__rules__pylint__tests__PLE2502_bidirectional_unicode.py.snap
  ruff.schema.json
Labels: rule

#2626 Accommodate pos-only arguments when checking self name
  crates/ruff/resources/test/fixtures/pep8_naming/N805.py
  crates/ruff/src/rules/pep8_naming/rules.rs
  crates/ruff/src/rules/pep8_naming/snapshots/ruff__rules__pep8_naming__tests__N805_N805.py.snap
Labels: bug

#2635 Treat @staticmethod as higher-precedence than ABC
  crates/ruff/resources/test/fixtures/pep8_naming/N804.py
  crates/ruff/src/ast/function_type.rs
Labels: bug

#2636 Avoid boolean-trap errors in `__setitem__`
  crates/ruff/resources/test/fixtures/flake8_boolean_trap/FBT.py
  crates/ruff/src/checkers/ast.rs
  crates/ruff/src/rules/flake8_boolean_trap/rules.rs
Labels: bug

#2637 Skip ternary fixes for yields and awaits
  crates/ruff/resources/test/fixtures/flake8_simplify/SIM108.py
  crates/ruff/src/rules/flake8_simplify/rules/ast_if.rs
Labels: bug

#2640 Ignore all non-`.py` wrt. implicit namespace package
  crates/ruff/resources/test/fixtures/flake8_no_pep420/test_pass_script/script
  crates/ruff/src/rules/flake8_no_pep420/mod.rs
  crates/ruff/src/rules/flake8_no_pep420/rules.rs
  crates/ruff/src/rules/flake8_no_pep420/snapshots/ruff__rules__flake8_no_pep420__tests__test_pass_script.snap
Labels: bug

#2652 Add documentation for eradicate, flake8-import-conventions, and flake8-no-pep420
  README.md
  crates/ruff/src/checkers/ast.rs
  crates/ruff/src/registry.rs
  crates/ruff/src/rules/eradicate/rules.rs
  crates/ruff/src/rules/flake8_import_conventions/mod.rs
  crates/ruff/src/rules/flake8_import_conventions/rules.rs
  crates/ruff/src/rules/flake8_import_conventions/snapshots/ruff__rules__flake8_import_conventions__tests__custom.snap
  crates/ruff/src/rules/flake8_import_conventions/snapshots/ruff__rules__flake8_import_conventions__tests__defaults.snap
  crates/ruff/src/rules/flake8_import_conventions/snapshots/ruff__rules__flake8_import_conventions__tests__from_imports.snap
  crates/ruff/src/rules/flake8_import_conventions/snapshots/ruff__rules__flake8_import_conventions__tests__override_default.snap
  crates/ruff/src/rules/flake8_import_conventions/snapshots/ruff__rules__flake8_import_conventions__tests__remove_default.snap
  crates/ruff/src/rules/flake8_no_pep420/rules.rs
  docs/rules/commented-out-code.md
  docs/rules/implicit-namespace-package.md
  docs/rules/unconventional-import-alias.md
Labels: documentation

#2653 Implement whitespace-around-keywords (E271, E272, E273, E274)
  crates/ruff/resources/test/fixtures/pycodestyle/E27.py
  crates/ruff/src/checkers/logical_lines.rs
  crates/ruff/src/registry.rs
  crates/ruff/src/rules/pycodestyle/logical_lines.rs
  crates/ruff/src/rules/pycodestyle/mod.rs
  crates/ruff/src/rules/pycodestyle/rules/mod.rs
  crates/ruff/src/rules/pycodestyle/rules/whitespace_around_keywords.rs
  crates/ruff/src/rules/pycodestyle/snapshots/ruff__rules__pycodestyle__tests__E271_E27.py.snap
  crates/ruff/src/rules/pycodestyle/snapshots/ruff__rules__pycodestyle__tests__E272_E27.py.snap
  crates/ruff/src/rules/pycodestyle/snapshots/ruff__rules__pycodestyle__tests__E273_E27.py.snap
  crates/ruff/src/rules/pycodestyle/snapshots/ruff__rules__pycodestyle__tests__E274_E27.py.snap
Labels: rule

#2663 Avoid false-positive in chained type calls
  crates/ruff/resources/test/fixtures/pyupgrade/UP003.py
  crates/ruff/src/checkers/ast.rs
  crates/ruff/src/rules/pyupgrade/rules/type_of_primitive.rs
Labels: bug

#2668 Add `--exit-non-zero-on-fix`
  README.md
  crates/ruff_cli/src/args.rs
  crates/ruff_cli/src/main.rs
Labels: configuration, cli

#2675 Support callable decorators in classmethod_decorators et al
  crates/ruff/src/ast/function_type.rs
  crates/ruff/src/ast/helpers.rs
  crates/ruff/src/rules/flake8_pytest_style/rules/helpers.rs
  crates/ruff/src/rules/pep8_naming/mod.rs
  crates/ruff/src/rules/pep8_naming/snapshots/ruff__rules__pep8_naming__tests__classmethod_decorators.snap
  crates/ruff/src/visibility.rs
Labels: bug

#2678 Only include rule links once in README
  README.md
  crates/ruff_dev/src/generate_rules_table.rs
Labels: documentation

#2697 Suppress parse errors with explicit `# noqa: E999` directives
  crates/ruff/src/checkers/ast.rs
  crates/ruff/src/linter.rs
  crates/ruff/src/noqa.rs
Labels: cli

#2682 Add flake8-pyi with one rule
  LICENSE
  README.md
  crates/ruff/resources/test/fixtures/flake8_pyi/PYI001.py
  crates/ruff/resources/test/fixtures/flake8_pyi/PYI001.pyi
  crates/ruff/src/checkers/ast.rs
  crates/ruff/src/registry.rs
  crates/ruff/src/rules/flake8_pyi/mod.rs
  crates/ruff/src/rules/flake8_pyi/rules.rs
  crates/ruff/src/rules/flake8_pyi/snapshots/ruff__rules__flake8_pyi__tests__PYI001_PYI001.py.snap
  crates/ruff/src/rules/flake8_pyi/snapshots/ruff__rules__flake8_pyi__tests__PYI001_PYI001.pyi.snap
  crates/ruff/src/rules/mod.rs
  docs/rules/prefix-type-params.md
  ruff.schema.json
Labels: rule

#2572 [`pylint`]: bad-string-format-type
  README.md
  crates/ruff/resources/test/fixtures/pylint/bad_string_format_type.py
  crates/ruff/src/ast/helpers.rs
  crates/ruff/src/checkers/ast.rs
  crates/ruff/src/registry.rs
  crates/ruff/src/rules/pylint/mod.rs
  crates/ruff/src/rules/pylint/rules/bad_string_format_type.rs
  crates/ruff/src/rules/pylint/rules/mod.rs
  crates/ruff/src/rules/pylint/snapshots/ruff__rules__pylint__tests__PLE1307_bad_string_format_type.py.snap
  docs/rules/bad-string-format-type.md
  ruff.schema.json
  src/registry.rs
Labels: rule

#2704 Remove lifetimes from Printer
  crates/ruff_cli/src/main.rs
  crates/ruff_cli/src/printer.rs
Labels: internal

#2709 Remove public Rust API
  BREAKING_CHANGES.md
  crates/ruff/src/lib.rs
  crates/ruff/src/lib_native.rs
Labels: breaking

#2657 feat(isort): Implement known-local-folder
  README.md
  crates/ruff/resources/test/fixtures/isort/pyproject.toml
  crates/ruff/resources/test/fixtures/isort/separate_local_folder_imports.py
  crates/ruff/src/rules/flake8_type_checking/rules/typing_only_runtime_import.rs
  crates/ruff/src/rules/isort/categorize.rs
  crates/ruff/src/rules/isort/mod.rs
  crates/ruff/src/rules/isort/rules/organize_imports.rs
  crates/ruff/src/rules/isort/settings.rs
  crates/ruff/src/rules/isort/snapshots/ruff__rules__isort__tests__separate_local_folder_imports.py.snap
  ruff.schema.json
Labels: isort, configuration

#2728 Avoid flagging typed exceptions in tuples
  crates/ruff/resources/test/fixtures/flake8_bandit/S112.py
  crates/ruff/src/rules/flake8_bandit/helpers.rs
  crates/ruff/src/rules/flake8_bandit/rules/try_except_continue.rs
  crates/ruff/src/rules/flake8_bandit/rules/try_except_pass.rs
  crates/ruff/src/rules/flake8_bandit/snapshots/ruff__rules__flake8_bandit__tests__S112_S112.py.snap
Labels: bug

#2716 pylint: E0100 yield-in-init
  README.md
  crates/ruff/resources/test/fixtures/pylint/yield_in_init.py
  crates/ruff/src/checkers/ast.rs
  crates/ruff/src/registry.rs
  crates/ruff/src/rules/pylint/mod.rs
  crates/ruff/src/rules/pylint/rules/mod.rs
  crates/ruff/src/rules/pylint/rules/yield_in_init.rs
  crates/ruff/src/rules/pylint/snapshots/ruff__rules__pylint__tests__PLE0100_yield_in_init.py.snap
  ruff.schema.json
Labels: rule

#2746 Add colored environment variables to README
  README.md
Labels: documentation

#2739 autofix relative imports (TID252)
  README.md
  crates/ruff/resources/test/fixtures/flake8_tidy_imports/TID252.py
  crates/ruff/src/checkers/ast.rs
  crates/ruff/src/rules/flake8_tidy_imports/relative_imports.rs
  crates/ruff/src/rules/flake8_tidy_imports/snapshots/ruff__rules__flake8_tidy_imports__relative_imports__tests__ban_all_imports.snap
  crates/ruff/src/rules/flake8_tidy_imports/snapshots/ruff__rules__flake8_tidy_imports__relative_imports__tests__ban_parent_imports.snap
  crates/ruff_python/src/string.rs
  docs/rules/relative-imports.md
Labels: autofix

#2755 Only update docs on release
  .github/workflows/docs.yaml
Labels: documentation, release

#2771 Ignore colon-after-lambda in compound statement rules
  crates/ruff/resources/test/fixtures/pycodestyle/E70.py
  crates/ruff/src/rules/pycodestyle/rules/compound_statements.rs
Labels: bug

#2773 Remove multiple-statements-on-one-line-def (E704)
  BREAKING_CHANGES.md
  crates/ruff/src/checkers/tokens.rs
  crates/ruff/src/flake8_to_ruff/parser.rs
  crates/ruff/src/registry.rs
  crates/ruff/src/rules/pycodestyle/mod.rs
  crates/ruff/src/rules/pycodestyle/rules/compound_statements.rs
  crates/ruff/src/rules/pycodestyle/rules/mod.rs
  crates/ruff/src/rules/pycodestyle/snapshots/ruff__rules__pycodestyle__tests__E704_E70.py.snap
Labels: breaking

#2782 Use consistent formatting for lint-failure messages
  crates/ruff_cli/src/commands.rs
Labels: cli

#2783 Respect continuations in `noqa` enforcement
  crates/ruff/src/directives.rs
Labels: bug

#2785 Improve unused-variable autofixes for with statements
  crates/ruff/resources/test/fixtures/pyflakes/F841_3.py
  crates/ruff/src/rules/pyflakes/rules/unused_variable.rs
  crates/ruff/src/rules/pyflakes/snapshots/ruff__rules__pyflakes__tests__F841_F841_3.py.snap
Labels: bug

#2786 Support unused variable removal in multi-assignment statements
  crates/ruff/resources/test/fixtures/pyflakes/F841_3.py
  crates/ruff/src/rules/pyflakes/rules/unused_variable.rs
  crates/ruff/src/rules/pyflakes/snapshots/ruff__rules__pyflakes__tests__F841_F841_0.py.snap
  crates/ruff/src/rules/pyflakes/snapshots/ruff__rules__pyflakes__tests__F841_F841_1.py.snap
  crates/ruff/src/rules/pyflakes/snapshots/ruff__rules__pyflakes__tests__F841_F841_3.py.snap
  crates/ruff/src/rules/pyflakes/snapshots/ruff__rules__pyflakes__tests__f841_dummy_variable_rgx.snap
Labels: autofix

#2790 Add docs for f-string-missing-placeholders and unused-variable
  README.md
  crates/ruff/src/rules/pyflakes/rules/f_string_missing_placeholders.rs
  crates/ruff/src/rules/pyflakes/rules/unused_variable.rs
  docs/rules/f-string-missing-placeholders.md
  docs/rules/unused-variable.md
Labels: documentation

#2791 Add documentation on enabling autocompletion
  README.md
Labels: documentation

#2792 Split commands.rs into separate files
  crates/ruff_cli/src/commands.rs
  crates/ruff_cli/src/commands/add_noqa.rs
  crates/ruff_cli/src/commands/clean.rs
  crates/ruff_cli/src/commands/mod.rs
  crates/ruff_cli/src/commands/rule.rs
  crates/ruff_cli/src/commands/run.rs
  crates/ruff_cli/src/commands/run_stdin.rs
  crates/ruff_cli/src/commands/show_files.rs
  crates/ruff_cli/src/commands/show_settings.rs
  crates/ruff_cli/src/main.rs
Labels: internal

#2693 [`flake8-comprehensions`] autofix C414 and C417 + bugfix
  README.md
  crates/ruff/resources/test/fixtures/flake8_comprehensions/C414.py
  crates/ruff/resources/test/fixtures/flake8_comprehensions/C417.py
  crates/ruff/src/checkers/ast.rs
  crates/ruff/src/rules/flake8_comprehensions/fixes.rs
  crates/ruff/src/rules/flake8_comprehensions/rules/unnecessary_double_cast_or_process.rs
  crates/ruff/src/rules/flake8_comprehensions/rules/unnecessary_map.rs
  crates/ruff/src/rules/flake8_comprehensions/snapshots/ruff__rules__flake8_comprehensions__tests__C414_C414.py.snap
  crates/ruff/src/rules/flake8_comprehensions/snapshots/ruff__rules__flake8_comprehensions__tests__C417_C417.py.snap
  docs/rules/unnecessary-double-cast-or-process.md
  docs/rules/unnecessary-map.md
Labels: autofix

#2804 [`flake8-comprehensions`] bugfix for C413 autofix
  README.md
  crates/ruff/resources/test/fixtures/flake8_comprehensions/C413.py
  crates/ruff/src/rules/flake8_comprehensions/fixes.rs
  crates/ruff/src/rules/flake8_comprehensions/rules/unnecessary_call_around_sorted.rs
  crates/ruff/src/rules/flake8_comprehensions/snapshots/ruff__rules__flake8_comprehensions__tests__C413_C413.py.snap
  docs/rules/unnecessary-call-around-sorted.md
Labels: bug, autofix

#2796 Add E722 bare-except documentation
  README.md
  crates/ruff/src/rules/pycodestyle/rules/bare_except.rs
  docs/rules/bare-except.md
Labels: documentation

#2586 Implemented flake8-django plugin rules
  README.md
  crates/ruff/resources/test/fixtures/flake8_django/DJ001.py
  crates/ruff/resources/test/fixtures/flake8_django/DJ008.py
  crates/ruff/resources/test/fixtures/flake8_django/DJ013.py
  crates/ruff/src/checkers/ast.rs
  crates/ruff/src/registry.rs
  crates/ruff/src/rules/flake8_django/mod.rs
  crates/ruff/src/rules/flake8_django/rules/helpers.rs
  crates/ruff/src/rules/flake8_django/rules/mod.rs
  crates/ruff/src/rules/flake8_django/rules/model_dunder_str.rs
  crates/ruff/src/rules/flake8_django/rules/model_string_field_nullable.rs
  crates/ruff/src/rules/flake8_django/rules/receiver_decorator_checker.rs
  crates/ruff/src/rules/flake8_django/snapshots/ruff__rules__flake8_django__tests__DJ001_DJ001.py.snap
  crates/ruff/src/rules/flake8_django/snapshots/ruff__rules__flake8_django__tests__DJ008_DJ008.py.snap
  crates/ruff/src/rules/flake8_django/snapshots/ruff__rules__flake8_django__tests__DJ013_DJ013.py.snap
  crates/ruff/src/rules/mod.rs
  docs/rules/model-dunder-str.md
  docs/rules/model-string-field-nullable.md
  docs/rules/receiver-decorator-checker.md
  ruff.schema.json
Labels: plugin

#2805 [`flake8-pyi`]: add rules for unrecognized platform check (PYI007, PYI008)
  README.md
  crates/ruff/resources/test/fixtures/flake8_pyi/PYI007.py
  crates/ruff/resources/test/fixtures/flake8_pyi/PYI007.pyi
  crates/ruff/resources/test/fixtures/flake8_pyi/PYI008.py
  crates/ruff/resources/test/fixtures/flake8_pyi/PYI008.pyi
  crates/ruff/src/checkers/ast.rs
  crates/ruff/src/registry.rs
  crates/ruff/src/rules/flake8_pyi/mod.rs
  crates/ruff/src/rules/flake8_pyi/rules/mod.rs
  crates/ruff/src/rules/flake8_pyi/rules/prefix_type_params.rs
  crates/ruff/src/rules/flake8_pyi/rules/unrecognized_platform.rs
  crates/ruff/src/rules/flake8_pyi/snapshots/ruff__rules__flake8_pyi__tests__PYI007_PYI007.py.snap
  crates/ruff/src/rules/flake8_pyi/snapshots/ruff__rules__flake8_pyi__tests__PYI007_PYI007.pyi.snap
  crates/ruff/src/rules/flake8_pyi/snapshots/ruff__rules__flake8_pyi__tests__PYI008_PYI008.py.snap
  crates/ruff/src/rules/flake8_pyi/snapshots/ruff__rules__flake8_pyi__tests__PYI008_PYI008.pyi.snap
  docs/rules/unrecognized-platform-check.md
  docs/rules/unrecognized-platform-name.md
  ruff.schema.json
Labels: rule

#2799 Add PD002 use-of-inplace-argument documentation
  README.md
  crates/ruff/src/rules/pandas_vet/rules/inplace_argument.rs
  docs/rules/use-of-inplace-argument.md
Labels: documentation

#2707 Show applied fixes by file and diagnostic
  Cargo.lock
  README.md
  crates/ruff/src/autofix/mod.rs
  crates/ruff/src/lib_wasm.rs
  crates/ruff/src/linter.rs
  crates/ruff/src/settings/configuration.rs
  crates/ruff/src/settings/mod.rs
  crates/ruff/src/settings/options.rs
  crates/ruff_cli/Cargo.toml
  crates/ruff_cli/src/args.rs
  crates/ruff_cli/src/diagnostics.rs
  crates/ruff_cli/src/main.rs
  crates/ruff_cli/src/printer.rs
  ruff.schema.json
Labels: cli

#2823 [`flake8-simplify`]: combine-if-conditions
  README.md
  crates/ruff/resources/test/fixtures/flake8_simplify/SIM114.py
  crates/ruff/src/checkers/ast.rs
  crates/ruff/src/registry.rs
  crates/ruff/src/rules/flake8_simplify/mod.rs
  crates/ruff/src/rules/flake8_simplify/rules/ast_if.rs
  crates/ruff/src/rules/flake8_simplify/rules/mod.rs
  crates/ruff/src/rules/flake8_simplify/snapshots/ruff__rules__flake8_simplify__tests__SIM114_SIM114.py.snap
  docs/rules/combine-if-conditions.md
  docs/rules/if-with-same-arms.md
  ruff.schema.json
Labels: rule

#2826 Implement `ComparableStmt`
  crates/ruff/resources/test/fixtures/flake8_simplify/SIM114.py
  crates/ruff/src/ast/comparable.rs
  crates/ruff/src/rules/flake8_simplify/rules/ast_if.rs
  crates/ruff/src/rules/flake8_simplify/snapshots/ruff__rules__flake8_simplify__tests__SIM114_SIM114.py.snap
Labels: internal

#2831 Use smarter inversion for comparison checks
  crates/ruff/resources/test/fixtures/flake8_simplify/SIM111.py
  crates/ruff/src/rules/flake8_simplify/rules/ast_for.rs
  crates/ruff/src/rules/flake8_simplify/snapshots/ruff__rules__flake8_simplify__tests__SIM111_SIM111.py.snap.new
Labels: autofix

#2838 Update pre-commit instructions
  README.md
Labels: documentation

#2858 Handle multiple receiver decorators in receiver-decorator
  crates/ruff/resources/test/fixtures/flake8_django/DJ013.py
  crates/ruff/src/checkers/ast.rs
  crates/ruff/src/rules/flake8_django/rules/receiver_decorator_checker.rs
  crates/ruff/src/rules/flake8_django/snapshots/ruff__rules__flake8_django__tests__DJ013_DJ013.py.snap
Labels: bug

#2862 Avoid false-positives with multi-byte characters in B005
  crates/ruff/resources/test/fixtures/flake8_bugbear/B005.py
  crates/ruff/src/rules/flake8_bugbear/rules/strip_with_multi_characters.rs
  crates/ruff/src/rules/flake8_bugbear/rules/useless_contextlib_suppress.rs
  crates/ruff/src/rules/flake8_bugbear/rules/useless_expression.rs
  crates/ruff/src/rules/flake8_bugbear/snapshots/ruff__rules__flake8_bugbear__tests__B005_B005.py.snap
Labels: bug

#2863 Avoid false-positives for runtime-types in type checking blocks
  crates/ruff/resources/test/fixtures/flake8_type_checking/TCH004_13.py
  crates/ruff/src/checkers/ast.rs
  crates/ruff/src/rules/flake8_type_checking/mod.rs
  crates/ruff/src/rules/flake8_type_checking/snapshots/ruff__rules__flake8_type_checking__tests__runtime-import-in-type-checking-block_TCH004_13.py.snap
Labels: bug

#2864 Avoid noqa removal upon unhandled syntax errors
  crates/ruff/src/linter.rs
Labels: bug

#2896 Add headers to configutation options
  README.md
Labels: documentation

#2900 Ignore non-imperative-mood in Google docstring convention
  crates/ruff/src/rules/pydocstyle/settings.rs
Labels: bug

#2904 docs: fix `ruff generate-shell-completion`
  README.md
Labels: documentation

#2873 Add `StaticTextSlice` kind to `FormatElement` enum
  crates/ruff_formatter/src/builders.rs
  crates/ruff_formatter/src/format_element.rs
  crates/ruff_formatter/src/format_element/document.rs
  crates/ruff_formatter/src/printer/mod.rs
Labels: autoformatter

#2874 Allow printing of consecutive empty lines
  crates/ruff_formatter/src/printer/mod.rs
Labels: autoformatter

#2913 Simplify release workflows
  .github/workflows/flake8-to-ruff.yaml
  .github/workflows/ruff.yaml
Labels: release

#2927 Respect self as positional-only argument in annotation rules
  crates/ruff/resources/test/fixtures/flake8_annotations/annotation_presence.py
  crates/ruff/src/rules/flake8_annotations/rules.rs
  crates/ruff/src/rules/flake8_annotations/snapshots/ruff__rules__flake8_annotations__tests__defaults.snap
  crates/ruff_python_formatter/src/trivia.rs
Labels: bug

#2928 Apply nullable-model-string-field to all classes
  crates/ruff/resources/test/fixtures/flake8_django/DJ001.py
  crates/ruff/src/checkers/ast.rs
  crates/ruff/src/rules/flake8_django/rules/nullable_model_string_field.rs
  crates/ruff/src/rules/flake8_django/snapshots/ruff__rules__flake8_django__tests__DJ001_DJ001.py.snap
Labels: bug

#2930 Upload `ruff` binaries to GitHub release
  .github/workflows/ruff.yaml
Labels: release

#2931 Deduplicate files provided on the command-line
  crates/ruff/src/resolver.rs
Labels: bug

#2946 Fix add-required-import with multi-line offsets
  crates/ruff/resources/test/fixtures/isort/required_imports/multiline_docstring.py
  crates/ruff/src/rules/isort/helpers.rs
  crates/ruff/src/rules/isort/mod.rs
  crates/ruff/src/rules/isort/snapshots/ruff__rules__isort__tests__required_import_multiline_docstring.py.snap
Labels: bug

#2968 Regenerate expected Black snapshots
  crates/ruff_python_formatter/resources/test/fixtures/black/simple_cases/attribute_access_on_number_literals.py
  crates/ruff_python_formatter/resources/test/fixtures/black/simple_cases/comments3.py
  crates/ruff_python_formatter/resources/test/fixtures/black/simple_cases/comments5.py
  crates/ruff_python_formatter/resources/test/fixtures/black/simple_cases/comments8.py
  crates/ruff_python_formatter/resources/test/fixtures/black/simple_cases/comments9.py
  crates/ruff_python_formatter/resources/test/fixtures/black/simple_cases/docstring_preview.py
  crates/ruff_python_formatter/resources/test/fixtures/black/simple_cases/expression.diff
  crates/ruff_python_formatter/resources/test/fixtures/black/simple_cases/function.py
  crates/ruff_python_formatter/resources/test/fixtures/black/simple_cases/one_element_subscript.py
  crates/ruff_python_formatter/resources/test/fixtures/black/simple_cases/prefer_rhs_split_reformatted.py
  crates/ruff_python_formatter/resources/test/fixtures/black/simple_cases/remove_await_parens.py
  crates/ruff_python_formatter/resources/test/fixtures/black/simple_cases/remove_except_parens.py
  crates/ruff_python_formatter/resources/test/fixtures/black/simple_cases/remove_for_brackets.py
  crates/ruff_python_formatter/resources/test/fixtures/black/simple_cases/remove_newline_after_code_block_open.py
  crates/ruff_python_formatter/resources/test/fixtures/black/simple_cases/return_annotation_brackets.py
  crates/ruff_python_formatter/resources/test/fixtures/black/simple_cases/skip_magic_trailing_comma.py
  crates/ruff_python_formatter/resources/test/fixtures/black/simple_cases/trailing_commas_in_leading_parts.py
  crates/ruff_python_formatter/resources/test/fixtures/black/simple_cases/whitespace.py
  crates/ruff_python_formatter/src/snapshots/expect/ruff_python_formatter__tests__simple_cases__comment_after_escaped_newline.py.snap.expect
  crates/ruff_python_formatter/src/snapshots/expect/ruff_python_formatter__tests__simple_cases__comments2.py.snap.expect
  crates/ruff_python_formatter/src/snapshots/expect/ruff_python_formatter__tests__simple_cases__comments3.py.snap.expect
  crates/ruff_python_formatter/src/snapshots/expect/ruff_python_formatter__tests__simple_cases__comments5.py.snap.expect
  crates/ruff_python_formatter/src/snapshots/expect/ruff_python_formatter__tests__simple_cases__comments8.py.snap.expect
  crates/ruff_python_formatter/src/snapshots/expect/ruff_python_formatter__tests__simple_cases__comments9.py.snap.expect
  crates/ruff_python_formatter/src/snapshots/expect/ruff_python_formatter__tests__simple_cases__docstring_preview.py.snap.expect
  crates/ruff_python_formatter/src/snapshots/expect/ruff_python_formatter__tests__simple_cases__empty_lines.py.snap.expect
  crates/ruff_python_formatter/src/snapshots/expect/ruff_python_formatter__tests__simple_cases__expression.py.snap.expect
  crates/ruff_python_formatter/src/snapshots/expect/ruff_python_formatter__tests__simple_cases__fmtonoff.py.snap.expect
  crates/ruff_python_formatter/src/snapshots/expect/ruff_python_formatter__tests__simple_cases__function.py.snap.expect
  crates/ruff_python_formatter/src/snapshots/expect/ruff_python_formatter__tests__simple_cases__function2.py.snap.expect
  crates/ruff_python_formatter/src/snapshots/expect/ruff_python_formatter__tests__simple_cases__function_trailing_comma.py.snap.expect
  crates/ruff_python_formatter/src/snapshots/expect/ruff_python_formatter__tests__simple_cases__one_element_subscript.py.snap.expect
  crates/ruff_python_formatter/src/snapshots/expect/ruff_python_formatter__tests__simple_cases__power_op_spacing.py.snap.expect
  crates/ruff_python_formatter/src/snapshots/expect/ruff_python_formatter__tests__simple_cases__prefer_rhs_split_reformatted.py.snap.expect
  crates/ruff_python_formatter/src/snapshots/expect/ruff_python_formatter__tests__simple_cases__remove_await_parens.py.snap.expect
  crates/ruff_python_formatter/src/snapshots/expect/ruff_python_formatter__tests__simple_cases__remove_except_parens.py.snap.expect
  crates/ruff_python_formatter/src/snapshots/expect/ruff_python_formatter__tests__simple_cases__remove_for_brackets.py.snap.expect
  crates/ruff_python_formatter/src/snapshots/expect/ruff_python_formatter__tests__simple_cases__remove_newline_after_code_block_open.py.snap.expect
  crates/ruff_python_formatter/src/snapshots/expect/ruff_python_formatter__tests__simple_cases__remove_parens.py.snap.expect
  crates/ruff_python_formatter/src/snapshots/expect/ruff_python_formatter__tests__simple_cases__return_annotation_brackets.py.snap.expect
  crates/ruff_python_formatter/src/snapshots/expect/ruff_python_formatter__tests__simple_cases__skip_magic_trailing_comma.py.snap.expect
  crates/ruff_python_formatter/src/snapshots/expect/ruff_python_formatter__tests__simple_cases__trailing_commas_in_leading_parts.py.snap.expect
  crates/ruff_python_formatter/src/snapshots/expect/ruff_python_formatter__tests__simple_cases__tupleassign.py.snap.expect
  crates/ruff_python_formatter/src/snapshots/expect/ruff_python_formatter__tests__simple_cases__whitespace.py.snap.expect
  crates/ruff_python_formatter/src/snapshots/ruff_python_formatter__tests__simple_cases__bracketmatch.py.snap
Labels: autoformatter

#2975 Use `line_suffix` for end-of-line comments
  crates/ruff_python_formatter/src/format/expr.rs
  crates/ruff_python_formatter/src/format/stmt.rs
  crates/ruff_python_formatter/src/lib.rs
  crates/ruff_python_formatter/src/snapshots/ruff_python_formatter__tests__simple_cases__power_op_spacing.py.snap
Labels: autoformatter

#2960 [`numpy`] numpy-legacy-random
  README.md
  crates/ruff/resources/test/fixtures/numpy/NPY002.py
  crates/ruff/src/checkers/ast.rs
  crates/ruff/src/codes.rs
  crates/ruff/src/registry.rs
  crates/ruff/src/rules/numpy/mod.rs
  crates/ruff/src/rules/numpy/rules/mod.rs
  crates/ruff/src/rules/numpy/rules/numpy_legacy_random.rs
  crates/ruff/src/rules/numpy/snapshots/ruff__rules__numpy__tests__numpy-legacy-random_NPY002.py.snap
  ruff.schema.json
Labels: rule

#2979 Unify comment terminology with that of `rome_formatter`
  crates/ruff_python_formatter/src/builders.rs
  crates/ruff_python_formatter/src/format/expr.rs
  crates/ruff_python_formatter/src/format/stmt.rs
  crates/ruff_python_formatter/src/trivia.rs
Labels: autoformatter

#2983 Move editor integrations into MkDocs
  README.md
  docs/.gitignore
  docs/editor-integrations.md
  scripts/generate_mkdocs.py
Labels: documentation

#2984 Move FAQ into MkDocs
  README.md
  docs/.gitignore
  docs/faq.md
  scripts/generate_mkdocs.py
Labels: documentation

#2986 Split list of users into top-level and dedicated section
  README.md
  _typos.toml
Labels: documentation

#2998 Ignore namedtuple methods in flake8-self
  crates/ruff/resources/test/fixtures/flake8_self/SLF001.py
  crates/ruff/src/lib_wasm.rs
  crates/ruff/src/rules/flake8_self/mod.rs
  crates/ruff/src/rules/flake8_self/rules/private_member_access.rs
  crates/ruff/src/rules/flake8_self/settings.rs
  crates/ruff/src/rules/flake8_self/snapshots/ruff__rules__flake8_self__tests__private-member-access_SLF001.py.snap
  crates/ruff/src/settings/configuration.rs
  crates/ruff/src/settings/defaults.rs
  crates/ruff/src/settings/mod.rs
  crates/ruff/src/settings/options.rs
  ruff.schema.json
Labels: bug, configuration

#3002 Support positional messages in assertion rewrites
  crates/ruff/src/rules/flake8_pytest_style/rules/unittest_assert.rs
  crates/ruff/src/rules/flake8_pytest_style/snapshots/ruff__rules__flake8_pytest_style__tests__PT009.snap
Labels: bug

#3027 [docs] Add some docs for `flake8-simplify`
  crates/ruff/src/rules/flake8_simplify/rules/ast_bool_op.rs
  crates/ruff/src/rules/flake8_simplify/rules/ast_with.rs
Labels: documentation

#3028 [docs] Add docs for `flake8-implicit-str-concat` rules
  crates/ruff/src/rules/flake8_implicit_str_concat/rules.rs
Labels: documentation

#2977 Add configuration option for C408 to allow dict calls with keyword arguments.
  crates/ruff/src/checkers/ast.rs
  crates/ruff/src/lib_wasm.rs
  crates/ruff/src/rules/flake8_comprehensions/mod.rs
  crates/ruff/src/rules/flake8_comprehensions/rules/unnecessary_collection_call.rs
  crates/ruff/src/rules/flake8_comprehensions/settings.rs
  crates/ruff/src/rules/flake8_comprehensions/snapshots/ruff__rules__flake8_comprehensions__tests__C408_C408.py_allow_dict_calls_with_keyword_arguments.snap
  crates/ruff/src/settings/configuration.rs
  crates/ruff/src/settings/defaults.rs
  crates/ruff/src/settings/mod.rs
  crates/ruff/src/settings/options.rs
  ruff.schema.json
Labels: configuration

#3032 Avoid false-positives for break in with
  crates/ruff/resources/test/fixtures/pylint/useless_else_on_loop.py
  crates/ruff/src/rules/pylint/rules/useless_else_on_loop.rs
Labels: bug

#3062 Avoid assert() to assert statement conversion in expressions
  crates/ruff/resources/test/fixtures/flake8_pytest_style/PT009.py
  crates/ruff/src/rules/flake8_pytest_style/rules/assertion.rs
  crates/ruff/src/rules/flake8_pytest_style/snapshots/ruff__rules__flake8_pytest_style__tests__PT009.snap
Labels: bug

#3068 feat(B029): Add B029 from flake8-bugbear
  crates/ruff/resources/test/fixtures/flake8_bugbear/B029.py
  crates/ruff/src/checkers/ast.rs
  crates/ruff/src/codes.rs
  crates/ruff/src/registry.rs
  crates/ruff/src/rules/flake8_bugbear/mod.rs
  crates/ruff/src/rules/flake8_bugbear/rules/except_with_empty_tuple.rs
  crates/ruff/src/rules/flake8_bugbear/rules/mod.rs
  crates/ruff/src/rules/flake8_bugbear/snapshots/ruff__rules__flake8_bugbear__tests__B029_B029.py.snap
  ruff.schema.json
Labels: rule

#3074 Add `StmtKind::Try`; fix trailing newlines
  crates/ruff_python_formatter/src/format/excepthandler.rs
  crates/ruff_python_formatter/src/format/mod.rs
  crates/ruff_python_formatter/src/format/stmt.rs
  crates/ruff_python_formatter/src/lib.rs
  crates/ruff_python_formatter/src/newlines.rs
  crates/ruff_python_formatter/src/trivia.rs
Labels: autoformatter

#3075 Avoid boolean-trap rules for positional-only builtin calls
  crates/ruff/resources/test/fixtures/flake8_boolean_trap/FBT.py
  crates/ruff/src/rules/flake8_boolean_trap/rules.rs
Labels: bug

#3076 Omit while-True loops from implicit return enforcement
  crates/ruff/resources/test/fixtures/flake8_return/RET503.py
  crates/ruff/src/rules/flake8_return/rules.rs
Labels: bug

#3077 Add support for trailing colons in slice expressions
  crates/ruff_python_formatter/src/format/comprehension.rs
  crates/ruff_python_formatter/src/format/expr.rs
  crates/ruff_python_formatter/src/lib.rs
  crates/ruff_python_formatter/src/snapshots/ruff_python_formatter__tests__simple_cases__slices.py.snap
  crates/ruff_python_formatter/src/trivia.rs
Labels: autoformatter

#3079 Enable some already-passing Black tests
  crates/ruff_python_formatter/src/lib.rs
  crates/ruff_python_formatter/src/snapshots/ruff_python_formatter__tests__simple_cases__one_element_subscript.py.snap
  crates/ruff_python_formatter/src/snapshots/ruff_python_formatter__tests__simple_cases__remove_newline_after_code_block_open.py.snap
  crates/ruff_python_formatter/src/snapshots/ruff_python_formatter__tests__simple_cases__tricky_unicode_symbols.py.snap
Labels: autoformatter

#3080 Enable `tupleassign` test
  crates/ruff_python_formatter/src/format/expr.rs
  crates/ruff_python_formatter/src/lib.rs
  crates/ruff_python_formatter/src/newlines.rs
  crates/ruff_python_formatter/src/snapshots/ruff_python_formatter__tests__simple_cases__tupleassign.py.snap
Labels: autoformatter

#3087 Use LibCST to fix chained assertions
  crates/ruff/resources/test/fixtures/flake8_pytest_style/PT018.py
  crates/ruff/src/rules/flake8_pytest_style/rules/assertion.rs
  crates/ruff/src/rules/flake8_pytest_style/snapshots/ruff__rules__flake8_pytest_style__tests__PT018.snap
Labels: bug, autofix

#3085 feat(B032): add b032 flake8_bugbear
  crates/ruff/resources/test/fixtures/flake8_bugbear/B032.py
  crates/ruff/src/checkers/ast.rs
  crates/ruff/src/codes.rs
  crates/ruff/src/registry.rs
  crates/ruff/src/rules/flake8_bugbear/mod.rs
  crates/ruff/src/rules/flake8_bugbear/rules/mod.rs
  crates/ruff/src/rules/flake8_bugbear/rules/unintentional_type_annotation.rs
  crates/ruff/src/rules/flake8_bugbear/snapshots/ruff__rules__flake8_bugbear__tests__B032_B032.py.snap
  ruff.schema.json
Labels: rule

#3102 Avoid prefer-list-builtin for lambdas with `*args` or `**kwargs`
  crates/ruff/resources/test/fixtures/flake8_pie/PIE807.py
  crates/ruff/src/rules/flake8_pie/rules.rs
Labels: bug

#3104 Include file permissions in cache key
  crates/ruff_cli/src/cache.rs
  crates/ruff_cli/src/diagnostics.rs
Labels: bug

#3107 Support shell expansion for --config argument
  Cargo.lock
  crates/ruff_cli/Cargo.toml
  crates/ruff_cli/src/resolve.rs
Labels: cli

#3022 [pylint] redefined-loop-name (W2901)
  crates/ruff/resources/test/fixtures/pylint/redefined_loop_name.py
  crates/ruff/src/ast/helpers.rs
  crates/ruff/src/ast/types.rs
  crates/ruff/src/checkers/ast.rs
  crates/ruff/src/codes.rs
  crates/ruff/src/registry.rs
  crates/ruff/src/rules/pylint/mod.rs
  crates/ruff/src/rules/pylint/rules/mod.rs
  crates/ruff/src/rules/pylint/rules/redefined_loop_name.rs
  crates/ruff/src/rules/pylint/snapshots/ruff__rules__pylint__tests__PLW2901_redefined_loop_name.py.snap
  ruff.schema.json
Labels: rule

#3084 feat: pylint codes E1205-E106
  crates/ruff/resources/test/fixtures/pylint/logging_too_few_args.py
  crates/ruff/resources/test/fixtures/pylint/logging_too_many_args.py
  crates/ruff/src/ast/logging.rs
  crates/ruff/src/ast/mod.rs
  crates/ruff/src/checkers/ast.rs
  crates/ruff/src/codes.rs
  crates/ruff/src/registry.rs
  crates/ruff/src/rules/flake8_logging_format/rules.rs
  crates/ruff/src/rules/pylint/mod.rs
  crates/ruff/src/rules/pylint/rules/logging.rs
  crates/ruff/src/rules/pylint/rules/mod.rs
  crates/ruff/src/rules/pylint/snapshots/ruff__rules__pylint__tests__PLE1205_logging_too_many_args.py.snap
  crates/ruff/src/rules/pylint/snapshots/ruff__rules__pylint__tests__PLE1206_logging_too_few_args.py.snap
  ruff.schema.json
Labels: rule

#3111 Skip EXE001 and EXE002 rules on Windows
  Cargo.lock
  crates/ruff/Cargo.toml
  crates/ruff/src/rules/flake8_executable/helpers.rs
  crates/ruff/src/rules/flake8_executable/rules/shebang_missing.rs
  crates/ruff/src/rules/flake8_executable/rules/shebang_not_executable.rs
Labels: bug

#3121 Mark `typing.assert_never` as no return
  crates/ruff/resources/test/fixtures/flake8_return/RET503.py
  crates/ruff/src/rules/flake8_return/rules.rs
  crates/ruff/src/rules/flake8_return/snapshots/ruff__rules__flake8_return__tests__RET503_RET503.py.snap
Labels: bug

#3128 Use file-specific quote for C408
  crates/ruff/src/rules/flake8_comprehensions/fixes.rs
Labels: bug

#3129 Avoid match statement misidentification in token rules
  Cargo.lock
  Cargo.toml
  crates/ruff/resources/test/fixtures/pycodestyle/E70.py
  crates/ruff/src/ast/helpers.rs
  crates/ruff/src/ast/operations.rs
  crates/ruff/src/autofix/helpers.rs
  crates/ruff/src/checkers/logical_lines.rs
  crates/ruff/src/directives.rs
  crates/ruff/src/rules/flake8_annotations/fixes.rs
  crates/ruff/src/rules/isort/comments.rs
  crates/ruff/src/rules/isort/helpers.rs
  crates/ruff/src/rules/pyflakes/fixes.rs
  crates/ruff/src/rules/pyflakes/rules/unused_variable.rs
  crates/ruff/src/rules/pylint/rules/bad_string_format_type.rs
  crates/ruff/src/rules/pyupgrade/fixes.rs
  crates/ruff/src/rules/pyupgrade/rules/f_strings.rs
  crates/ruff/src/rules/pyupgrade/rules/native_literals.rs
  crates/ruff/src/rules/pyupgrade/rules/outdated_version_block.rs
  crates/ruff/src/rules/pyupgrade/rules/printf_string_formatting.rs
  crates/ruff/src/rules/pyupgrade/rules/redundant_open_modes.rs
  crates/ruff/src/rustpython_helpers.rs
  crates/ruff/src/source_code/indexer.rs
  crates/ruff/src/source_code/stylist.rs
  crates/ruff_dev/src/print_tokens.rs
  crates/ruff_python_formatter/src/core/rustpython_helpers.rs
Labels: bug

#3130 Upgrade RustPython to handle trailing commas in map patterns
  Cargo.lock
  Cargo.toml
Labels: bug

#3136 Avoid useless-else-on-loop for break within match
  crates/ruff/resources/test/fixtures/pylint/useless_else_on_loop.py
  crates/ruff/src/rules/pylint/rules/useless_else_on_loop.rs
Labels: bug

#3145 Add pre-commit note to docs
  README.md
Labels: documentation

#3146 Avoid suggesting 'is' for constant literals
  crates/ruff/resources/test/fixtures/pycodestyle/constant_literals.py
  crates/ruff/src/rules/pycodestyle/rules/literal_comparisons.rs
  crates/ruff/src/rules/pycodestyle/snapshots/ruff__rules__pycodestyle__tests__constant_literals.snap
Labels: bug

#3150 Move configuration out of README and into permanent docs
  README.md
  crates/ruff_dev/src/generate_cli_help.rs
  crates/ruff_dev/src/main.rs
  crates/ruff_dev/src/utils.rs
  docs/.gitignore
  docs/configuration.md
  docs/faq.md
  docs/installation-and-usage.md
  mkdocs.template.yml
  scripts/generate_mkdocs.py
Labels: documentation

#3153 Omit non-.py[i] files from module naming rules
  crates/ruff/resources/test/fixtures/pep8_naming/N999/module/valid_name/file-with-dashes
  crates/ruff/src/rules/pep8_naming/mod.rs
  crates/ruff/src/rules/pep8_naming/rules/invalid_module_name.rs
  crates/ruff/src/rules/pep8_naming/snapshots/ruff__rules__pep8_naming__tests__N999_N999__module__valid_name__file-with-dashes.snap
Labels: bug

#3154 Split up some docs sections
  README.md
  docs/.gitignore
  docs/configuration.md
  docs/installation-and-usage.md
  docs/installation.md
  docs/usage.md
  scripts/generate_mkdocs.py
Labels: documentation

#3155 Change via to using
  docs/configuration.md
Labels: documentation

#3157 Add note about prioritizing naming convention over preservation
  CONTRIBUTING.md
Labels: documentation

#3158 Un-modify `tupleassign` and `function2` tests
  crates/ruff_python_formatter/resources/test/fixtures/black/simple_cases/function2.py.expect
  crates/ruff_python_formatter/resources/test/fixtures/black/simple_cases/tupleassign.py.expect
  crates/ruff_python_formatter/src/snapshots/ruff_python_formatter__tests__black_test__function2_py.snap
  crates/ruff_python_formatter/src/snapshots/ruff_python_formatter__tests__black_test__tupleassign_py.snap
Labels: autoformatter

#3160 Don't touch tuple brackets after `in`
  crates/ruff_python_formatter/src/parentheses.rs
  crates/ruff_python_formatter/src/snapshots/ruff_python_formatter__tests__black_test__remove_for_brackets_py.snap.new
Labels: autoformatter

#3169 Bind star patterns in match statements
  crates/ruff/resources/test/fixtures/pyflakes/F821_9.py
  crates/ruff/src/checkers/ast.rs
Labels: bug

#3173 Add support for basic `Constant::Str` formatting
  Cargo.lock
  crates/ruff/src/docstrings/constants.rs
  crates/ruff/src/docstrings/mod.rs
  crates/ruff/src/rules/pydocstyle/helpers.rs
  crates/ruff/src/rules/pydocstyle/rules/multi_line_summary_start.rs
  crates/ruff_python/src/string.rs
  crates/ruff_python_formatter/Cargo.toml
  crates/ruff_python_formatter/src/core/helpers.rs
  crates/ruff_python_formatter/src/core/mod.rs
  crates/ruff_python_formatter/src/format/expr.rs
  crates/ruff_python_formatter/src/format/mod.rs
  crates/ruff_python_formatter/src/format/strings.rs
  crates/ruff_python_formatter/src/snapshots/ruff_python_formatter__tests__black_test__bracketmatch_py.snap
  crates/ruff_python_formatter/src/snapshots/ruff_python_formatter__tests__black_test__collections_py.snap
  crates/ruff_python_formatter/src/snapshots/ruff_python_formatter__tests__black_test__comments2_py.snap
  crates/ruff_python_formatter/src/snapshots/ruff_python_formatter__tests__black_test__empty_lines_py.snap
  crates/ruff_python_formatter/src/snapshots/ruff_python_formatter__tests__black_test__expression_py.snap
  crates/ruff_python_formatter/src/snapshots/ruff_python_formatter__tests__black_test__fmtonoff2_py.snap
  crates/ruff_python_formatter/src/snapshots/ruff_python_formatter__tests__black_test__fmtonoff5_py.snap
  crates/ruff_python_formatter/src/snapshots/ruff_python_formatter__tests__black_test__function_py.snap
  crates/ruff_python_formatter/src/snapshots/ruff_python_formatter__tests__black_test__function_trailing_comma_py.snap
  crates/ruff_python_formatter/src/snapshots/ruff_python_formatter__tests__black_test__string_prefixes_py.snap
  crates/ruff_python_formatter/src/snapshots/ruff_python_formatter__tests__black_test__trailing_comma_optional_parens1_py.snap
  crates/ruff_python_formatter/src/snapshots/ruff_python_formatter__tests__black_test__trailing_comma_optional_parens2_py.snap
Labels: autoformatter

#3176 Add support for reformatting byte strings
  crates/ruff/src/rules/flake8_bugbear/rules/raise_without_from_inside_except.rs
  crates/ruff/src/rules/flake8_simplify/rules/yoda_conditions.rs
  crates/ruff/src/rules/isort/sorting.rs
  crates/ruff/src/rules/pep8_naming/helpers.rs
  crates/ruff/src/rules/pep8_naming/rules/camelcase_imported_as_acronym.rs
  crates/ruff/src/rules/pep8_naming/rules/camelcase_imported_as_constant.rs
  crates/ruff/src/rules/pep8_naming/rules/camelcase_imported_as_lowercase.rs
  crates/ruff/src/rules/pep8_naming/rules/constant_imported_as_non_constant.rs
  crates/ruff/src/rules/pep8_naming/rules/lowercase_imported_as_non_lowercase.rs
  crates/ruff/src/rules/pydocstyle/helpers.rs
  crates/ruff/src/rules/pydocstyle/rules/multi_line_summary_start.rs
  crates/ruff/src/rules/pyflakes/fixes.rs
  crates/ruff_python/src/bytes.rs
  crates/ruff_python/src/lib.rs
  crates/ruff_python/src/str.rs
  crates/ruff_python_formatter/src/core/helpers.rs
  crates/ruff_python_formatter/src/format/expr.rs
  crates/ruff_python_formatter/src/format/strings.rs
  crates/ruff_python_formatter/src/snapshots/ruff_python_formatter__tests__black_test__expression_py.snap
  crates/ruff_python_formatter/src/snapshots/ruff_python_formatter__tests__black_test__string_prefixes_py.snap
Labels: autoformatter

#3178 Update RustPython to support *tuple annotations
  Cargo.lock
  Cargo.toml
  crates/ruff/resources/test/fixtures/flake8_annotations/annotation_presence.py
Labels: bug

#3180 Use `writeln` with --show-settings
  crates/ruff_cli/src/commands/show_settings.rs
Labels: bug

#3183 Implement integer literal formatting
  crates/ruff_python_formatter/src/format/expr.rs
  crates/ruff_python_formatter/src/format/mod.rs
  crates/ruff_python_formatter/src/format/numbers.rs
  crates/ruff_python_formatter/src/snapshots/ruff_python_formatter__tests__black_test__attribute_access_on_number_literals_py.snap
Labels: autoformatter

#3184 Implement float literal formatting
  crates/ruff_python_formatter/src/format/expr.rs
  crates/ruff_python_formatter/src/format/numbers.rs
  crates/ruff_python_formatter/src/snapshots/ruff_python_formatter__tests__black_test__attribute_access_on_number_literals_py.snap
Labels: autoformatter

#3186 Implement complex literal formatting
  crates/ruff_python_formatter/src/format/expr.rs
  crates/ruff_python_formatter/src/format/numbers.rs
  crates/ruff_python_formatter/src/snapshots/ruff_python_formatter__tests__black_test__attribute_access_on_number_literals_py.snap
Labels: autoformatter

#3194 Make Locator available in AST-to-CST conversion pass
  crates/ruff_python_formatter/src/cst.rs
  crates/ruff_python_formatter/src/lib.rs
Labels: autoformatter

#3195 Introduce a new CST element for slice segments
  crates/ruff_python_formatter/resources/test/fixtures/black/simple_cases/slices.py
  crates/ruff_python_formatter/resources/test/fixtures/black/simple_cases/slices.py.expect
  crates/ruff_python_formatter/src/attachment.rs
  crates/ruff_python_formatter/src/core/visitor.rs
  crates/ruff_python_formatter/src/cst.rs
  crates/ruff_python_formatter/src/format/expr.rs
  crates/ruff_python_formatter/src/snapshots/ruff_python_formatter__tests__black_test__expression_py.snap
  crates/ruff_python_formatter/src/trivia.rs
Labels: autoformatter

#3196 Handle end-of-line comments on `excepthandler` and `alias`
  crates/ruff_python_formatter/src/format/alias.rs
  crates/ruff_python_formatter/src/format/excepthandler.rs
  crates/ruff_python_formatter/src/snapshots/ruff_python_formatter__tests__black_test__comments2_py.snap
  crates/ruff_python_formatter/src/snapshots/ruff_python_formatter__tests__black_test__comments4_py.snap
Labels: autoformatter

#3209 Avoid boolean-trap rules for ConfigParser get() methods
  crates/ruff/resources/test/fixtures/flake8_boolean_trap/FBT.py
  crates/ruff/src/rules/flake8_boolean_trap/rules.rs
  crates/ruff/src/rules/flake8_boolean_trap/snapshots/ruff__rules__flake8_boolean_trap__tests__FBT001_FBT.py.snap
Labels: bug

#3217 Avoid rewriting any PEP 604 runtime annotations
  crates/ruff/resources/test/fixtures/pyupgrade/UP007.py
  crates/ruff/src/checkers/ast.rs
  crates/ruff/src/rules/pyupgrade/snapshots/ruff__rules__pyupgrade__tests__UP007.py.snap
Labels: bug, autofix

#3219 Add TextMate to editor-integrations.md
  docs/editor-integrations.md
Labels: documentation

#3220 Avoid flagging logging-too-few-args with no arguments
  crates/ruff/resources/test/fixtures/pylint/logging_too_few_args.py
  crates/ruff/src/rules/pylint/rules/logging.rs
Labels: bug

#3230 [flake8-pyi]: PYI009, PYI010, PYI021
  crates/ruff/resources/test/fixtures/flake8_pyi/PYI009.py
  crates/ruff/resources/test/fixtures/flake8_pyi/PYI009.pyi
  crates/ruff/resources/test/fixtures/flake8_pyi/PYI010.py
  crates/ruff/resources/test/fixtures/flake8_pyi/PYI010.pyi
  crates/ruff/resources/test/fixtures/flake8_pyi/PYI021.py
  crates/ruff/resources/test/fixtures/flake8_pyi/PYI021.pyi
  crates/ruff/src/checkers/ast.rs
  crates/ruff/src/codes.rs
  crates/ruff/src/registry.rs
  crates/ruff/src/rules/flake8_bandit/rules/assert_used.rs
  crates/ruff/src/rules/flake8_bandit/rules/hardcoded_password_default.rs
  crates/ruff/src/rules/flake8_pyi/mod.rs
  crates/ruff/src/rules/flake8_pyi/rules/docstring_in_stubs.rs
  crates/ruff/src/rules/flake8_pyi/rules/mod.rs
  crates/ruff/src/rules/flake8_pyi/rules/non_empty_stub_body.rs
  crates/ruff/src/rules/flake8_pyi/rules/pass_statement_stub_body.rs
  crates/ruff/src/rules/flake8_pyi/snapshots/ruff__rules__flake8_pyi__tests__PYI009_PYI009.py.snap
  crates/ruff/src/rules/flake8_pyi/snapshots/ruff__rules__flake8_pyi__tests__PYI009_PYI009.pyi.snap
  crates/ruff/src/rules/flake8_pyi/snapshots/ruff__rules__flake8_pyi__tests__PYI010_PYI010.py.snap
  crates/ruff/src/rules/flake8_pyi/snapshots/ruff__rules__flake8_pyi__tests__PYI010_PYI010.pyi.snap
  crates/ruff/src/rules/flake8_pyi/snapshots/ruff__rules__flake8_pyi__tests__PYI021_PYI021.py.snap
  crates/ruff/src/rules/flake8_pyi/snapshots/ruff__rules__flake8_pyi__tests__PYI021_PYI021.pyi.snap
  crates/ruff/src/rules/pandas_vet/rules/check_attr.rs
  crates/ruff/src/rules/pandas_vet/rules/check_call.rs
  crates/ruff/src/rules/pyupgrade/rules/os_error_alias.rs
  ruff.schema.json
Labels: rule

#3232 Add builders for common comment rendering
  crates/ruff_python_formatter/src/builders.rs
  crates/ruff_python_formatter/src/format/alias.rs
  crates/ruff_python_formatter/src/format/builders.rs
  crates/ruff_python_formatter/src/format/comments.rs
  crates/ruff_python_formatter/src/format/excepthandler.rs
  crates/ruff_python_formatter/src/format/expr.rs
  crates/ruff_python_formatter/src/format/mod.rs
  crates/ruff_python_formatter/src/format/numbers.rs
  crates/ruff_python_formatter/src/format/stmt.rs
  crates/ruff_python_formatter/src/lib.rs
  crates/ruff_python_formatter/src/main.rs
  crates/ruff_python_formatter/src/newlines.rs
  crates/ruff_python_formatter/src/parentheses.rs
Labels: autoformatter

#3233 Implement basic rendering of remaining AST nodes
  crates/ruff_python_formatter/src/attachment.rs
  crates/ruff_python_formatter/src/cst.rs
  crates/ruff_python_formatter/src/format/expr.rs
  crates/ruff_python_formatter/src/format/match_case.rs
  crates/ruff_python_formatter/src/format/mod.rs
  crates/ruff_python_formatter/src/format/pattern.rs
  crates/ruff_python_formatter/src/format/stmt.rs
  crates/ruff_python_formatter/src/trivia.rs
Labels: autoformatter

#3225 feat(E275): add Missing whitespace after keyword
  crates/ruff/src/checkers/logical_lines.rs
  crates/ruff/src/codes.rs
  crates/ruff/src/registry.rs
  crates/ruff/src/rules/pycodestyle/helpers.rs
  crates/ruff/src/rules/pycodestyle/mod.rs
  crates/ruff/src/rules/pycodestyle/rules/missing_whitespace_after_keyword.rs
  crates/ruff/src/rules/pycodestyle/rules/mod.rs
  crates/ruff/src/rules/pycodestyle/snapshots/ruff__rules__pycodestyle__tests__E275_E27.py.snap
Labels: rule

#3229 [pydocstyle]: Implement `ignore-decorators`
  crates/ruff/src/checkers/ast.rs
  crates/ruff/src/flake8_to_ruff/converter.rs
  crates/ruff/src/rules/pydocstyle/helpers.rs
  crates/ruff/src/rules/pydocstyle/mod.rs
  crates/ruff/src/rules/pydocstyle/settings.rs
  crates/ruff/src/rules/pydocstyle/snapshots/ruff__rules__pydocstyle__tests__D400_D.py.snap
  crates/ruff/src/rules/pydocstyle/snapshots/ruff__rules__pydocstyle__tests__D415_D.py.snap
  ruff.schema.json
Labels: configuration

#3238 [flake8-pyi]: PYI011, PYI014
  crates/ruff/resources/test/fixtures/flake8_pyi/PYI011.py
  crates/ruff/resources/test/fixtures/flake8_pyi/PYI011.pyi
  crates/ruff/resources/test/fixtures/flake8_pyi/PYI014.py
  crates/ruff/resources/test/fixtures/flake8_pyi/PYI014.pyi
  crates/ruff/src/checkers/ast.rs
  crates/ruff/src/codes.rs
  crates/ruff/src/registry.rs
  crates/ruff/src/rules/flake8_pyi/mod.rs
  crates/ruff/src/rules/flake8_pyi/rules/mod.rs
  crates/ruff/src/rules/flake8_pyi/rules/simple_defaults.rs
  crates/ruff/src/rules/flake8_pyi/snapshots/ruff__rules__flake8_pyi__tests__PYI011_PYI011.py.snap
  crates/ruff/src/rules/flake8_pyi/snapshots/ruff__rules__flake8_pyi__tests__PYI011_PYI011.pyi.snap
  crates/ruff/src/rules/flake8_pyi/snapshots/ruff__rules__flake8_pyi__tests__PYI014_PYI014.py.snap
  crates/ruff/src/rules/flake8_pyi/snapshots/ruff__rules__flake8_pyi__tests__PYI014_PYI014.pyi.snap
  ruff.schema.json
Labels: rule

#3236 [flake8-django] DJ003, DJ006, DJ007
  crates/ruff/resources/test/fixtures/flake8_django/DJ003.py
  crates/ruff/resources/test/fixtures/flake8_django/DJ006.py
  crates/ruff/resources/test/fixtures/flake8_django/DJ007.py
  crates/ruff/src/checkers/ast.rs
  crates/ruff/src/codes.rs
  crates/ruff/src/registry.rs
  crates/ruff/src/rules/flake8_django/mod.rs
  crates/ruff/src/rules/flake8_django/rules/all_with_model_form.rs
  crates/ruff/src/rules/flake8_django/rules/exclude_with_model_form.rs
  crates/ruff/src/rules/flake8_django/rules/helpers.rs
  crates/ruff/src/rules/flake8_django/rules/locals_in_render_function.rs
  crates/ruff/src/rules/flake8_django/rules/mod.rs
  crates/ruff/src/rules/flake8_django/snapshots/ruff__rules__flake8_django__tests__DJ003_DJ003.py.snap
  crates/ruff/src/rules/flake8_django/snapshots/ruff__rules__flake8_django__tests__DJ006_DJ006.py.snap
  crates/ruff/src/rules/flake8_django/snapshots/ruff__rules__flake8_django__tests__DJ007_DJ007.py.snap
  crates/ruff/src/rules/pycodestyle/rules/missing_whitespace_after_keyword.rs
  ruff.schema.json
Labels: rule

#3240 Bump lint rule count to 500+
  README.md
Labels: documentation

#3227 [pylint] W0603: global-statement
  crates/ruff/resources/test/fixtures/pylint/global_statement.py
  crates/ruff/src/checkers/ast.rs
  crates/ruff/src/codes.rs
  crates/ruff/src/registry.rs
  crates/ruff/src/rules/pylint/mod.rs
  crates/ruff/src/rules/pylint/rules/global_statement.rs
  crates/ruff/src/rules/pylint/rules/mod.rs
  crates/ruff/src/rules/pylint/snapshots/ruff__rules__pylint__tests__PLW0603_global_statement.py.snap
  ruff.schema.json
Labels: rule

#3241 Expand the range of the COM812 autofix to include the preceding token
  crates/ruff/resources/test/fixtures/flake8_commas/COM81.py
  crates/ruff/src/checkers/tokens.rs
  crates/ruff/src/rules/flake8_commas/rules.rs
  crates/ruff/src/rules/flake8_commas/snapshots/ruff__rules__flake8_commas__tests__COM81.py.snap
Labels: bug

#3244 Avoid flagging Pylint logging rules with starred arguments
  crates/ruff/resources/test/fixtures/pylint/logging_too_few_args.py
  crates/ruff/resources/test/fixtures/pylint/logging_too_many_args.py
  crates/ruff/src/rules/pylint/rules/logging.rs
  crates/ruff/src/rules/pylint/snapshots/ruff__rules__pylint__tests__PLE1205_logging_too_many_args.py.snap
Labels: bug

#3223 Create dedicated `Body` nodes in the formatter CST
  crates/ruff_python_formatter/src/attachment.rs
  crates/ruff_python_formatter/src/core/helpers.rs
  crates/ruff_python_formatter/src/core/locator.rs
  crates/ruff_python_formatter/src/core/visitor.rs
  crates/ruff_python_formatter/src/cst.rs
  crates/ruff_python_formatter/src/format/builders.rs
  crates/ruff_python_formatter/src/format/comments.rs
  crates/ruff_python_formatter/src/format/match_case.rs
  crates/ruff_python_formatter/src/format/stmt.rs
  crates/ruff_python_formatter/src/lib.rs
  crates/ruff_python_formatter/src/newlines.rs
  crates/ruff_python_formatter/src/parentheses.rs
  crates/ruff_python_formatter/src/snapshots/ruff_python_formatter__tests__black_test__comments2_py.snap
  crates/ruff_python_formatter/src/snapshots/ruff_python_formatter__tests__black_test__comments6_py.snap
  crates/ruff_python_formatter/src/snapshots/ruff_python_formatter__tests__black_test__comments9_py.snap
  crates/ruff_python_formatter/src/snapshots/ruff_python_formatter__tests__black_test__composition_no_trailing_comma_py.snap
  crates/ruff_python_formatter/src/snapshots/ruff_python_formatter__tests__black_test__composition_py.snap
  crates/ruff_python_formatter/src/snapshots/ruff_python_formatter__tests__black_test__fmtonoff4_py.snap
  crates/ruff_python_formatter/src/snapshots/ruff_python_formatter__tests__black_test__fmtonoff5_py.snap
  crates/ruff_python_formatter/src/snapshots/ruff_python_formatter__tests__black_test__fmtskip6_py.snap
  crates/ruff_python_formatter/src/snapshots/ruff_python_formatter__tests__black_test__function_py.snap
  crates/ruff_python_formatter/src/snapshots/ruff_python_formatter__tests__black_test__remove_await_parens_py.snap
  crates/ruff_python_formatter/src/trivia.rs
Labels: autoformatter

#3260 Deduplicate SIM116 errors
  crates/ruff/resources/test/fixtures/flake8_simplify/SIM116.py
  crates/ruff/src/checkers/ast.rs
  crates/ruff/src/rules/flake8_simplify/rules/ast_if.rs
  crates/ruff/src/rules/flake8_simplify/snapshots/ruff__rules__flake8_simplify__tests__SIM116_SIM116.py.snap
Labels: bug

#3261 Don't flag keyword-based logging format strings
  crates/ruff/resources/test/fixtures/pylint/logging_too_few_args.py
  crates/ruff/resources/test/fixtures/pylint/logging_too_many_args.py
  crates/ruff/src/rules/pylint/rules/logging.rs
Labels: bug

#3262 Enable more non-panicking formatter tests
  crates/ruff_python_formatter/src/lib.rs
  crates/ruff_python_formatter/src/snapshots/ruff_python_formatter__tests__black_test__comments3_py.snap
  crates/ruff_python_formatter/src/snapshots/ruff_python_formatter__tests__black_test__comments5_py.snap
  crates/ruff_python_formatter/src/snapshots/ruff_python_formatter__tests__black_test__comments_non_breaking_space_py.snap
  crates/ruff_python_formatter/src/snapshots/ruff_python_formatter__tests__black_test__comments_py.snap
  crates/ruff_python_formatter/src/snapshots/ruff_python_formatter__tests__black_test__docstring_preview_py.snap
  crates/ruff_python_formatter/src/snapshots/ruff_python_formatter__tests__black_test__docstring_py.snap
  crates/ruff_python_formatter/src/snapshots/ruff_python_formatter__tests__black_test__fmtonoff_py.snap
  crates/ruff_python_formatter/src/snapshots/ruff_python_formatter__tests__black_test__fmtskip8_py.snap
Labels: autoformatter
