Repository astral-sh/ruff, pull requests merged in 2023-12, with the labels that each got.

#8932 Apply some minor changes to `unnecessary-list-index-lookup`
  crates/ruff_linter/src/rules/pylint/rules/unnecessary_list_index_lookup.rs
  crates/ruff_linter/src/rules/pylint/snapshots/ruff_linter__rules__pylint__tests__PLR1736_unnecessary_list_index_lookup.py.snap
Labels: internal

#8933 Use correct range for `TRIO115` fix
  crates/ruff_linter/src/rules/flake8_trio/rules/zero_sleep_call.rs
  crates/ruff_linter/src/rules/flake8_trio/snapshots/ruff_linter__rules__flake8_trio__tests__TRIO115_TRIO115.py.snap
Labels: bug

#8293 Implement multiline dictionary and list hugging for preview style
  crates/ruff_python_formatter/resources/test/fixtures/black/simple_cases/preview_hug_parens_with_braces_and_square_brackets.options.json
  crates/ruff_python_formatter/resources/test/fixtures/black/simple_cases/preview_hug_parens_with_braces_and_square_brackets.py
  crates/ruff_python_formatter/resources/test/fixtures/black/simple_cases/preview_hug_parens_with_braces_and_square_brackets.py.expect
  crates/ruff_python_formatter/resources/test/fixtures/ruff/expression/hug.py
  crates/ruff_python_formatter/src/builders.rs
  crates/ruff_python_formatter/src/expression/mod.rs
  crates/ruff_python_formatter/src/expression/parentheses.rs
  crates/ruff_python_formatter/src/other/arguments.rs
  crates/ruff_python_formatter/tests/snapshots/black_compatibility@simple_cases__preview_hug_parens_with_braces_and_square_brackets.py.snap
  crates/ruff_python_formatter/tests/snapshots/format@expression__hug.py.snap
  crates/ruff_python_formatter/tests/snapshots/format@expression__split_empty_brackets.py.snap
Labels: formatter, preview

#8934 Add support for `@functools.singledispatch`
  crates/ruff_linter/resources/test/fixtures/flake8_type_checking/singledispatch.py
  crates/ruff_linter/src/checkers/ast/mod.rs
  crates/ruff_linter/src/rules/flake8_type_checking/helpers.rs
  crates/ruff_linter/src/rules/flake8_type_checking/mod.rs
  crates/ruff_linter/src/rules/flake8_type_checking/snapshots/ruff_linter__rules__flake8_type_checking__tests__typing-only-third-party-import_singledispatch.py.snap
Labels: bug

#8937 Fix doc formatting for zero-sleep-call
  crates/ruff_linter/src/rules/flake8_trio/rules/zero_sleep_call.rs
Labels: documentation

#8036 [`pylint`] Implement `unnecessary-dict-index-lookup` (`PLR1733`)
  crates/ruff_linter/resources/test/fixtures/pylint/unnecessary_dict_index_lookup.py
  crates/ruff_linter/src/checkers/ast/analyze/expression.rs
  crates/ruff_linter/src/checkers/ast/analyze/statement.rs
  crates/ruff_linter/src/codes.rs
  crates/ruff_linter/src/rules/pylint/mod.rs
  crates/ruff_linter/src/rules/pylint/rules/mod.rs
  crates/ruff_linter/src/rules/pylint/rules/unnecessary_dict_index_lookup.rs
  crates/ruff_linter/src/rules/pylint/snapshots/ruff_linter__rules__pylint__tests__PLR1733_unnecessary_dict_index_lookup.py.snap
  ruff.schema.json
Labels: rule, preview

#8944 Enable Preview mode for formatter benchmarks
  crates/ruff_benchmark/benches/formatter.rs
Labels: internal

#8948 [`flake8-pyi`] Check for kwarg and vararg `NoReturn` type annotations
  crates/ruff_linter/resources/test/fixtures/flake8_pyi/PYI050.pyi
  crates/ruff_linter/src/rules/flake8_pyi/rules/no_return_argument_annotation.rs
  crates/ruff_linter/src/rules/flake8_pyi/snapshots/ruff_linter__rules__flake8_pyi__tests__PYI050_PYI050.pyi.snap
Labels: rule

#8952 Detect implicit returns in auto-return-types
  crates/ruff_linter/resources/test/fixtures/flake8_annotations/auto_return_type.py
  crates/ruff_linter/src/rules/flake8_annotations/helpers.rs
  crates/ruff_linter/src/rules/flake8_annotations/snapshots/ruff_linter__rules__flake8_annotations__tests__auto_return_type.snap
  crates/ruff_linter/src/rules/flake8_annotations/snapshots/ruff_linter__rules__flake8_annotations__tests__auto_return_type_py38.snap
  crates/ruff_linter/src/rules/flake8_annotations/snapshots/ruff_linter__rules__flake8_annotations__tests__defaults.snap
  crates/ruff_linter/src/rules/flake8_annotations/snapshots/ruff_linter__rules__flake8_annotations__tests__ignore_fully_untyped.snap
  crates/ruff_linter/src/rules/flake8_annotations/snapshots/ruff_linter__rules__flake8_annotations__tests__mypy_init_return.snap
  crates/ruff_python_ast/src/helpers.rs
Labels: bug

#8954 Ignore `@overload` and `@override` methods for too-many-arguments checks
  crates/ruff_linter/resources/test/fixtures/pylint/too_many_arguments.py
  crates/ruff_linter/src/checkers/ast/analyze/statement.rs
  crates/ruff_linter/src/rules/pylint/rules/too_many_arguments.rs
Labels: bug

#8928 [`pylint`] Add `add_argument` utility and autofix for `PLW1514`
  crates/ruff_linter/resources/test/fixtures/pylint/unspecified_encoding.py
  crates/ruff_linter/src/fix/edits.rs
  crates/ruff_linter/src/rules/pylint/mod.rs
  crates/ruff_linter/src/rules/pylint/rules/unspecified_encoding.rs
  crates/ruff_linter/src/rules/pylint/snapshots/ruff_linter__rules__pylint__tests__PLW1514_unspecified_encoding.py.snap
  crates/ruff_linter/src/rules/pylint/snapshots/ruff_linter__rules__pylint__tests__unspecified_encoding_python39_or_lower.snap
Labels: autofix

#8950 ruff_python_formatter: light refactoring of code snippet formatting in docstrings
  crates/ruff_python_formatter/resources/test/fixtures/ruff/docstring_code_examples.py
  crates/ruff_python_formatter/src/expression/string/docstring.rs
  crates/ruff_python_formatter/tests/snapshots/format@docstring_code_examples.py.snap
Labels: internal, docstring, formatter

#8955 Added the command to run ruff using pkgx to the installation.md
  docs/installation.md
Labels: documentation

#8957 Add erroneous for-loop test case for CFG
  crates/ruff_linter/resources/test/fixtures/control-flow-graph/for.py
  crates/ruff_linter/src/rules/ruff/rules/snapshots/ruff_linter__rules__ruff__rules__unreachable__tests__for.py.md.snap
  crates/ruff_linter/src/rules/ruff/rules/snapshots/ruff_linter__rules__ruff__rules__unreachable__tests__match.py.md.snap.new
Labels: internal

#8960 Remove todo branches from control-flow graph
  crates/ruff_linter/src/rules/ruff/rules/unreachable.rs
Labels: internal

#8947 Implement the `fix_power_op_line_length` preview style
  crates/ruff_python_formatter/src/expression/binary_like.rs
  crates/ruff_python_formatter/src/expression/parentheses.rs
  crates/ruff_python_formatter/tests/snapshots/black_compatibility@cases__preview_power_op_spacing.py.snap
Labels: formatter, preview

#8963 Fix error in `t-suffixed-type-alias` (`PYI043`) example
  crates/ruff_linter/src/rules/flake8_pyi/rules/type_alias_naming.rs
Labels: documentation

#8965 Avoid underflow in `get_model` matching
  crates/ruff_linter/resources/test/fixtures/pep8_naming/N806.py
  crates/ruff_linter/src/rules/pep8_naming/helpers.rs
  crates/ruff_linter/src/rules/pep8_naming/snapshots/ruff_linter__rules__pep8_naming__tests__N806_N806.py.snap
Labels: bug

#8971 Avoid syntax error via invalid ur string prefix
  crates/ruff_linter/resources/test/fixtures/pycodestyle/W605_0.py
  crates/ruff_linter/resources/test/fixtures/pycodestyle/W605_1.py
  crates/ruff_linter/resources/test/fixtures/pycodestyle/W605_2.py
  crates/ruff_linter/src/rules/pycodestyle/mod.rs
  crates/ruff_linter/src/rules/pycodestyle/rules/invalid_escape_sequence.rs
  crates/ruff_linter/src/rules/pycodestyle/snapshots/ruff_linter__rules__pycodestyle__tests__W605_W605_0.py.snap
  crates/ruff_linter/src/rules/pycodestyle/snapshots/ruff_linter__rules__pycodestyle__tests__W605_W605_1.py.snap
  crates/ruff_linter/src/rules/pycodestyle/snapshots/ruff_linter__rules__pycodestyle__tests__W605_W605_2.py.snap
Labels: bug

#8982 Fix start >= end error in over-indentation
  crates/ruff_linter/resources/test/fixtures/pydocstyle/D208.py
  crates/ruff_linter/src/rules/pydocstyle/rules/indent.rs
  crates/ruff_linter/src/rules/pydocstyle/snapshots/ruff_linter__rules__pydocstyle__tests__D208_D208.py.snap
Labels: bug, fuzzer

#8984 Avoid unstable formatting in ellipsis-only body with trailing comment
  crates/ruff_python_formatter/resources/test/fixtures/ruff/statement/ellipsis.pyi
  crates/ruff_python_formatter/src/statement/suite.rs
  crates/ruff_python_formatter/tests/snapshots/format@statement__ellipsis.pyi.snap
Labels: bug, formatter

#8987 Move `ParenthesizedExpr` to `ruff_python_parser`
  crates/ruff_python_ast/src/nodes.rs
  crates/ruff_python_parser/src/parser.rs
  crates/ruff_python_parser/src/python.lalrpop
  crates/ruff_python_parser/src/python.rs
Labels: internal

#8988 Create dedicated `is_*_enabled` functions for each preview style
  crates/ruff_python_formatter/src/context.rs
  crates/ruff_python_formatter/src/expression/binary_like.rs
  crates/ruff_python_formatter/src/expression/mod.rs
  crates/ruff_python_formatter/src/lib.rs
  crates/ruff_python_formatter/src/options.rs
  crates/ruff_python_formatter/src/other/arguments.rs
  crates/ruff_python_formatter/src/preview.rs
Labels: internal

#8997 Rename semantic model flag `LITERAL` to `TYPING_LITERAL`
  crates/ruff_linter/src/checkers/ast/mod.rs
  crates/ruff_python_semantic/src/model.rs
Labels: internal

#8995 [`pylint`] Implement `too-many-positional` (`PLR0917`)
  crates/ruff_linter/resources/test/fixtures/pylint/too_many_positional.py
  crates/ruff_linter/resources/test/fixtures/pylint/too_many_positional_params.py
  crates/ruff_linter/src/checkers/ast/analyze/statement.rs
  crates/ruff_linter/src/codes.rs
  crates/ruff_linter/src/rules/pylint/mod.rs
  crates/ruff_linter/src/rules/pylint/rules/mod.rs
  crates/ruff_linter/src/rules/pylint/rules/too_many_positional.rs
  crates/ruff_linter/src/rules/pylint/settings.rs
  crates/ruff_linter/src/rules/pylint/snapshots/ruff_linter__rules__pylint__tests__PLR0917_too_many_positional.py.snap
  crates/ruff_linter/src/rules/pylint/snapshots/ruff_linter__rules__pylint__tests__max_positional_args.snap
  crates/ruff_workspace/src/options.rs
  ruff.schema.json
Labels: rule, preview

#8998 Default `max-positional-args` to `max-args`
  crates/ruff_workspace/src/options.rs
  ruff.schema.json
Labels: configuration

#9000 Ignore `@overrides` and `@overloads` for `too-many-positional`
  crates/ruff_linter/src/checkers/ast/analyze/statement.rs
  crates/ruff_linter/src/rules/pylint/rules/too_many_positional.rs
Labels: bug

#9011 Fix example for PLR0203
  crates/ruff_linter/src/rules/pylint/rules/no_method_decorator.rs
Labels: documentation

#9003 add support for formatting reStructuredText code snippets
  crates/ruff_python_formatter/Cargo.toml
  crates/ruff_python_formatter/resources/test/fixtures/ruff/docstring_code_examples.py
  crates/ruff_python_formatter/src/expression/string/docstring.rs
  crates/ruff_python_formatter/tests/normalizer.rs
  crates/ruff_python_formatter/tests/snapshots/format@docstring_code_examples.py.snap
Labels: docstring, formatter

#9002 Include version number in release archive names
  .github/workflows/release.yaml
Labels: release

#9012 Apply unnecessary index rule prior to enumerate rewrite
  crates/ruff_linter/src/rules/pylint/rules/unnecessary_dict_index_lookup.rs
  crates/ruff_linter/src/rules/pylint/rules/unnecessary_list_index_lookup.rs
Labels: bug

#9015 Respect trailing comma in unnecessary-dict-kwargs
  crates/ruff_linter/resources/test/fixtures/flake8_pie/PIE804.py
  crates/ruff_linter/src/checkers/ast/analyze/expression.rs
  crates/ruff_linter/src/rules/flake8_pie/rules/unnecessary_dict_kwargs.rs
  crates/ruff_linter/src/rules/flake8_pie/snapshots/ruff_linter__rules__flake8_pie__tests__PIE804_PIE804.py.snap
Labels: bug

#9021 Enforce valid format options in spec tests
  crates/ruff_python_formatter/resources/test/fixtures/black/cases/ignore_pyi.pyi
  crates/ruff_python_formatter/resources/test/fixtures/black/cases/line_ranges_fmt_off_decorator.py
  crates/ruff_python_formatter/resources/test/fixtures/black/cases/line_ranges_fmt_off_decorator.py.expect
  crates/ruff_python_formatter/resources/test/fixtures/black/cases/linelength6.options.json
  crates/ruff_python_formatter/resources/test/fixtures/black/cases/power_op_newline.options.json
  crates/ruff_python_formatter/resources/test/fixtures/import_black_tests.py
  crates/ruff_python_formatter/src/options.rs
  crates/ruff_python_formatter/tests/snapshots/black_compatibility@cases__ignore_pyi.pyi.snap
  crates/ruff_python_formatter/tests/snapshots/black_compatibility@cases__line_ranges_fmt_off_decorator.py.snap
  crates/ruff_python_formatter/tests/snapshots/black_compatibility@cases__power_op_newline.py.snap
Labels: internal

#9027 Avoid removing parentheses on ctypes.WinError
  crates/ruff_linter/resources/test/fixtures/flake8_raise/RSE102.py
  crates/ruff_linter/src/rules/flake8_raise/rules/unnecessary_paren_on_raise_exception.rs
  crates/ruff_linter/src/rules/flake8_raise/snapshots/ruff_linter__rules__flake8_raise__tests__unnecessary-paren-on-raise-exception_RSE102.py.snap
Labels: bug

#8996 Add openSUSE Tumbleweed into install doc
  docs/installation.md
Labels: documentation

#9033 Document use of math.isnan for self-comparisons
  crates/ruff_linter/src/rules/pylint/rules/comparison_with_itself.rs
Labels: documentation

#9034 Avoid `ANN2xx` autofix for abstract methods with empty body
  crates/ruff_linter/resources/test/fixtures/flake8_annotations/auto_return_type.py
  crates/ruff_linter/src/rules/flake8_annotations/rules/definition.rs
  crates/ruff_linter/src/rules/flake8_annotations/snapshots/ruff_linter__rules__flake8_annotations__tests__auto_return_type.snap
  crates/ruff_linter/src/rules/flake8_annotations/snapshots/ruff_linter__rules__flake8_annotations__tests__auto_return_type_py38.snap
Labels: rule

#9035 Fix detection of changed files in CI
  .github/workflows/ci.yaml
Labels: ci

#9037 Enable `printf-string-formatting` fix with comments on right-hand side
  crates/ruff_linter/resources/test/fixtures/pyupgrade/UP031_0.py
  crates/ruff_linter/src/rules/pyupgrade/rules/printf_string_formatting.rs
  crates/ruff_linter/src/rules/pyupgrade/snapshots/ruff_linter__rules__pyupgrade__tests__UP031_0.py.snap
Labels: autofix

#9038 Fix determine changes detection of "code" changes
  .github/workflows/ci.yaml
Labels: ci

#9039 Ensure that from-style imports are always ordered first in `__future__`
  crates/ruff_linter/resources/test/fixtures/isort/force_sort_within_sections_future.py
  crates/ruff_linter/resources/test/fixtures/isort/future_from.py
  crates/ruff_linter/src/rules/isort/mod.rs
  crates/ruff_linter/src/rules/isort/order.rs
  crates/ruff_linter/src/rules/isort/snapshots/ruff_linter__rules__isort__tests__force_sort_within_sections_force_sort_within_sections_future.py.snap
  crates/ruff_linter/src/rules/isort/snapshots/ruff_linter__rules__isort__tests__future_from.py.snap
Labels: bug, isort

#9020 Use double quotes for all docstrings, including single-quoted docstrings
  crates/ruff_python_formatter/resources/test/fixtures/ruff/docstring.options.json
  crates/ruff_python_formatter/resources/test/fixtures/ruff/docstring.py
  crates/ruff_python_formatter/src/expression/string/mod.rs
  crates/ruff_python_formatter/tests/snapshots/format@docstring.py.snap
Labels: formatter

#9041 Avoid invalid combination of `force-sort-within-types` and `lines-between-types`
  crates/ruff_linter/resources/test/fixtures/isort/force_sort_within_sections_lines_between.py
  crates/ruff_linter/src/rules/isort/mod.rs
  crates/ruff_linter/src/rules/isort/snapshots/ruff_linter__rules__isort__tests__force_sort_within_sections_force_sort_within_sections_lines_between.py.snap
  crates/ruff_workspace/src/options.rs
Labels: bug, isort

#9030 ruff_python_formatter: support reformatting Markdown code blocks
  crates/ruff_python_formatter/resources/test/fixtures/ruff/docstring_code_examples.py
  crates/ruff_python_formatter/src/expression/string/docstring.rs
  crates/ruff_python_formatter/tests/normalizer.rs
  crates/ruff_python_formatter/tests/snapshots/format@docstring_code_examples.py.snap
Labels: docstring, formatter

#8822 Add "preserve" quote-style to mimic Black's skip-string-normalization
  crates/ruff_python_formatter/resources/test/fixtures/ruff/quote_style.options.json
  crates/ruff_python_formatter/resources/test/fixtures/ruff/quote_style.py
  crates/ruff_python_formatter/src/context.rs
  crates/ruff_python_formatter/src/expression/string/docstring.rs
  crates/ruff_python_formatter/src/expression/string/mod.rs
  crates/ruff_python_formatter/src/options.rs
  crates/ruff_python_formatter/tests/snapshots/format@quote_style.py.snap
  crates/ruff_workspace/src/configuration.rs
  crates/ruff_workspace/src/options.rs
  ruff.schema.json
Labels: formatter

#9050 ruff_python_formatter: add test for extraneous info string text
  crates/ruff_python_formatter/resources/test/fixtures/ruff/docstring_code_examples.py
  crates/ruff_python_formatter/tests/snapshots/format@docstring_code_examples.py.snap
Labels: internal, docstring, formatter

#9051 Fix handling of trailing target comment
  crates/ruff_python_formatter/resources/test/fixtures/ruff/statement/assign.py
  crates/ruff_python_formatter/src/statement/stmt_assign.rs
  crates/ruff_python_formatter/tests/snapshots/format@statement__assign.py.snap
Labels: bug, formatter

#9054 Make `math-constant` rule more targeted
  crates/ruff_linter/resources/test/fixtures/refurb/FURB152.py
  crates/ruff_linter/src/rules/refurb/rules/math_constant.rs
  crates/ruff_linter/src/rules/refurb/snapshots/ruff_linter__rules__refurb__tests__FURB152_FURB152.py.snap
Labels: bug

#9069 Fix typo in documentation
  crates/ruff_linter/src/rules/refurb/rules/delete_full_slice.rs
  crates/ruff_python_formatter/CONTRIBUTING.md
Labels: documentation

#9071 Upgrade `ahash`
  Cargo.lock
Labels: internal

#9072 Add fix for unexpected-spaces-around-keyword-parameter-equals
  crates/ruff_linter/src/rules/pycodestyle/rules/logical_lines/whitespace_around_named_parameter_equals.rs
  crates/ruff_linter/src/rules/pycodestyle/snapshots/ruff_linter__rules__pycodestyle__tests__E251_E25.py.snap
Labels: autofix

#9073 Fix: Fixed a line in docs to make it more clear
  crates/ruff_linter/src/rules/flake8_pytest_style/rules/assertion.rs
Labels: documentation

#9075 Add fix for comment-related whitespace rules
  crates/ruff_linter/resources/test/fixtures/pycodestyle/E26.py
  crates/ruff_linter/src/rules/pycodestyle/rules/logical_lines/whitespace_before_comment.rs
  crates/ruff_linter/src/rules/pycodestyle/snapshots/ruff_linter__rules__pycodestyle__tests__E262_E26.py.snap
  crates/ruff_linter/src/rules/pycodestyle/snapshots/ruff_linter__rules__pycodestyle__tests__E265_E26.py.snap
  crates/ruff_linter/src/rules/pycodestyle/snapshots/ruff_linter__rules__pycodestyle__tests__E266_E26.py.snap
  crates/ruff_linter/src/rules/pycodestyle/snapshots/ruff_linter__rules__pycodestyle__tests__shebang.snap
Labels: autofix, preview

#9060 Detect `unused-asyncio-dangling-task` (`RUF006`) on unused assignments
  crates/ruff_linter/resources/test/fixtures/ruff/RUF006.py
  crates/ruff_linter/src/checkers/ast/analyze/bindings.rs
  crates/ruff_linter/src/checkers/ast/analyze/statement.rs
  crates/ruff_linter/src/rules/ruff/rules/asyncio_dangling_task.rs
  crates/ruff_linter/src/rules/ruff/snapshots/ruff_linter__rules__ruff__tests__RUF006_RUF006.py.snap
Labels: bug

#9076 Avoid trailing comma for single-argument with positional separator
  crates/ruff_python_formatter/resources/test/fixtures/ruff/statement/function.py
  crates/ruff_python_formatter/src/other/parameters.rs
  crates/ruff_python_formatter/tests/snapshots/format@statement__function.py.snap
Labels: bug, formatter

#9077 [`refurb`] Implement `hashlib-digest-hex` (`FURB181`)
  crates/ruff_linter/resources/test/fixtures/refurb/FURB181.py
  crates/ruff_linter/src/checkers/ast/analyze/expression.rs
  crates/ruff_linter/src/codes.rs
  crates/ruff_linter/src/rules/refurb/mod.rs
  crates/ruff_linter/src/rules/refurb/rules/hashlib_digest_hex.rs
  crates/ruff_linter/src/rules/refurb/rules/mod.rs
  crates/ruff_linter/src/rules/refurb/snapshots/ruff_linter__rules__refurb__tests__FURB181_FURB181.py.snap
  ruff.schema.json
Labels: rule, preview

#9094 Allow `matplotlib.use` calls to intersperse imports
  crates/ruff_linter/resources/test/fixtures/pycodestyle/E402.py
  crates/ruff_linter/src/checkers/ast/mod.rs
  crates/ruff_linter/src/rules/pycodestyle/snapshots/ruff_linter__rules__pycodestyle__tests__E402_E402.py.snap
  crates/ruff_linter/src/rules/pycodestyle/snapshots/ruff_linter__rules__pycodestyle__tests__preview__E402_E402.py.snap
  crates/ruff_python_semantic/src/analyze/imports.rs
Labels: rule

#9099 E274: allow tab indentation before keyword
  crates/ruff_linter/resources/test/fixtures/pycodestyle/E27.py
  crates/ruff_linter/src/rules/pycodestyle/rules/logical_lines/mod.rs
Labels: bug

#9098 ruff_python_formatter: implement "dynamic" line width mode for docstring code formatting
  crates/ruff_python_formatter/resources/test/fixtures/ruff/docstring_code_examples.options.json
  crates/ruff_python_formatter/resources/test/fixtures/ruff/docstring_code_examples_dynamic_line_width.options.json
  crates/ruff_python_formatter/resources/test/fixtures/ruff/docstring_code_examples_dynamic_line_width.py
  crates/ruff_python_formatter/src/context.rs
  crates/ruff_python_formatter/src/expression/string/docstring.rs
  crates/ruff_python_formatter/src/lib.rs
  crates/ruff_python_formatter/src/options.rs
  crates/ruff_python_formatter/src/statement/suite.rs
  crates/ruff_python_formatter/tests/fixtures.rs
  crates/ruff_python_formatter/tests/snapshots/format@docstring_code_examples.py.snap
  crates/ruff_python_formatter/tests/snapshots/format@docstring_code_examples_dynamic_line_width.py.snap
Labels: formatter

#9107 F841: support fixing unused assignments in tuples by renaming variables
  crates/ruff_linter/src/rules/pyflakes/rules/unused_variable.rs
  crates/ruff_linter/src/rules/pyflakes/snapshots/ruff_linter__rules__pyflakes__tests__F841_F841_0.py.snap
  crates/ruff_linter/src/rules/pyflakes/snapshots/ruff_linter__rules__pyflakes__tests__F841_F841_1.py.snap
  crates/ruff_linter/src/rules/pyflakes/snapshots/ruff_linter__rules__pyflakes__tests__F841_F841_3.py.snap
  crates/ruff_linter/src/rules/pyflakes/snapshots/ruff_linter__rules__pyflakes__tests__preview__F841_F841_4.py.snap
Labels: autofix

#9108 Remove `ExprFormattedValue` formatting impl
  crates/ruff_python_formatter/src/expression/expr_formatted_value.rs
Labels: internal

#8450 `PIE804`: Prevent keyword arguments duplication
  crates/ruff_linter/resources/test/fixtures/flake8_pie/PIE804.py
  crates/ruff_linter/src/rules/flake8_pie/rules/unnecessary_dict_kwargs.rs
  crates/ruff_linter/src/rules/flake8_pie/snapshots/ruff_linter__rules__flake8_pie__tests__PIE804_PIE804.py.snap
Labels: bug

#9109 Add named expression handling to `find_assigned_value`
  crates/ruff_linter/resources/test/fixtures/flake8_trio/TRIO115.py
  crates/ruff_linter/src/rules/flake8_trio/snapshots/ruff_linter__rules__flake8_trio__tests__TRIO115_TRIO115.py.snap
  crates/ruff_python_semantic/src/analyze/typing.rs
  crates/ruff_python_semantic/src/model.rs
Labels: bug

#8943 `prefer_splitting_right_hand_side_of_assignments` preview style
  crates/ruff_python_formatter/resources/test/fixtures/ruff/statement/assignment_split_value_first.options.json
  crates/ruff_python_formatter/resources/test/fixtures/ruff/statement/assignment_split_value_first.py
  crates/ruff_python_formatter/src/expression/mod.rs
  crates/ruff_python_formatter/src/preview.rs
  crates/ruff_python_formatter/src/statement/stmt_ann_assign.rs
  crates/ruff_python_formatter/src/statement/stmt_assign.rs
  crates/ruff_python_formatter/src/statement/stmt_aug_assign.rs
  crates/ruff_python_formatter/src/statement/stmt_return.rs
  crates/ruff_python_formatter/src/statement/stmt_type_alias.rs
  crates/ruff_python_formatter/tests/snapshots/black_compatibility@cases__pep604_union_types_line_breaks.py.snap
  crates/ruff_python_formatter/tests/snapshots/black_compatibility@cases__preview_long_strings.py.snap
  crates/ruff_python_formatter/tests/snapshots/black_compatibility@cases__preview_long_strings__regression.py.snap
  crates/ruff_python_formatter/tests/snapshots/black_compatibility@cases__preview_prefer_rhs_split.py.snap
  crates/ruff_python_formatter/tests/snapshots/format@expression__optional_parentheses_comments.py.snap
  crates/ruff_python_formatter/tests/snapshots/format@preview.py.snap
  crates/ruff_python_formatter/tests/snapshots/format@statement__ann_assign.py.snap
  crates/ruff_python_formatter/tests/snapshots/format@statement__assign.py.snap
  crates/ruff_python_formatter/tests/snapshots/format@statement__assignment_split_value_first.py.snap
Labels: formatter, preview

#9078 Feature: Add SARIF output support
  Cargo.lock
  crates/ruff_cli/src/printer.rs
  crates/ruff_linter/Cargo.toml
  crates/ruff_linter/src/message/mod.rs
  crates/ruff_linter/src/message/sarif.rs
  crates/ruff_linter/src/settings/types.rs
  docs/configuration.md
  ruff.schema.json
Labels: linter

#9111 Add `as_slice` method for all string nodes
  crates/ruff_linter/src/checkers/ast/analyze/expression.rs
  crates/ruff_linter/src/rules/flake8_bandit/rules/hardcoded_sql_expression.rs
  crates/ruff_linter/src/rules/flake8_pytest_style/rules/helpers.rs
  crates/ruff_linter/src/rules/pylint/rules/assert_on_string_literal.rs
  crates/ruff_linter/src/rules/tryceratops/rules/raise_vanilla_args.rs
  crates/ruff_python_ast/src/comparable.rs
  crates/ruff_python_ast/src/helpers.rs
  crates/ruff_python_ast/src/node.rs
  crates/ruff_python_ast/src/nodes.rs
  crates/ruff_python_ast/src/visitor.rs
  crates/ruff_python_ast/src/visitor/transformer.rs
  crates/ruff_python_codegen/src/generator.rs
  crates/ruff_python_formatter/src/expression/string/mod.rs
Labels: internal

#9116 Bump version to v0.1.8
  CHANGELOG.md
  Cargo.lock
  README.md
  crates/flake8_to_ruff/Cargo.toml
  crates/ruff_cli/Cargo.toml
  crates/ruff_linter/Cargo.toml
  crates/ruff_shrinking/Cargo.toml
  docs/integrations.md
  pyproject.toml
  scripts/benchmarks/pyproject.toml
Labels: release

#9119 Fix blog post URL in changelog
  CHANGELOG.md
Labels: documentation

#9124 Fix `can_omit_optional_parentheses` for expressions with a right most fstring
  crates/ruff_python_formatter/resources/test/fixtures/ruff/expression/binary.py
  crates/ruff_python_formatter/src/expression/mod.rs
  crates/ruff_python_formatter/tests/snapshots/format@expression__binary.py.snap
Labels: bug, formatter

#9125 `can_omit_optional_parentheses`: Exit early for unparenthesized expressions
  crates/ruff_python_formatter/src/expression/mod.rs
Labels: internal, formatter

#9129 ruff_python_formatter: fix 'dynamic' mode with doctests
  crates/ruff_python_formatter/resources/test/fixtures/ruff/docstring_code_examples_dynamic_line_width.py
  crates/ruff_python_formatter/src/expression/string/docstring.rs
  crates/ruff_python_formatter/tests/snapshots/format@docstring_code_examples_dynamic_line_width.py.snap
Labels: docstring, formatter

#9058 Split string formatting to individual nodes
  crates/ruff_python_formatter/generate.py
  crates/ruff_python_formatter/src/context.rs
  crates/ruff_python_formatter/src/expression/binary_like.rs
  crates/ruff_python_formatter/src/expression/expr_bytes_literal.rs
  crates/ruff_python_formatter/src/expression/expr_f_string.rs
  crates/ruff_python_formatter/src/expression/expr_string_literal.rs
  crates/ruff_python_formatter/src/expression/mod.rs
  crates/ruff_python_formatter/src/generated.rs
  crates/ruff_python_formatter/src/lib.rs
  crates/ruff_python_formatter/src/other/bytes_literal.rs
  crates/ruff_python_formatter/src/other/f_string.rs
  crates/ruff_python_formatter/src/other/f_string_part.rs
  crates/ruff_python_formatter/src/other/mod.rs
  crates/ruff_python_formatter/src/other/string_literal.rs
  crates/ruff_python_formatter/src/statement/suite.rs
  crates/ruff_python_formatter/src/string/docstring.rs
  crates/ruff_python_formatter/src/string/mod.rs
Labels: internal

#9140 Deduplicate edits when quoting annotations
  crates/ruff_linter/resources/test/fixtures/flake8_type_checking/quote.py
  crates/ruff_linter/src/rules/flake8_type_checking/rules/runtime_import_in_type_checking_block.rs
  crates/ruff_linter/src/rules/flake8_type_checking/rules/typing_only_runtime_import.rs
  crates/ruff_linter/src/rules/flake8_type_checking/snapshots/ruff_linter__rules__flake8_type_checking__tests__quote_runtime-import-in-type-checking-block_quote.py.snap
  crates/ruff_linter/src/rules/flake8_type_checking/snapshots/ruff_linter__rules__flake8_type_checking__tests__quote_typing-only-third-party-import_quote.py.snap
Labels: bug

#9142 Enable annotation quoting for multi-line expressions
  crates/ruff_diagnostics/src/edit.rs
  crates/ruff_linter/resources/test/fixtures/flake8_type_checking/quote.py
  crates/ruff_linter/src/rules/flake8_type_checking/helpers.rs
  crates/ruff_linter/src/rules/flake8_type_checking/rules/runtime_import_in_type_checking_block.rs
  crates/ruff_linter/src/rules/flake8_type_checking/rules/typing_only_runtime_import.rs
  crates/ruff_linter/src/rules/flake8_type_checking/snapshots/ruff_linter__rules__flake8_type_checking__tests__quote_typing-only-third-party-import_quote.py.snap
Labels: bug

#9127 Extend `can_omit_optional_parentheses` documentation
  crates/ruff_python_formatter/src/expression/mod.rs
Labels: internal

#9128 Add new `with` and `match` sequence test cases
  crates/ruff_python_formatter/resources/test/fixtures/ruff/statement/match.py
  crates/ruff_python_formatter/resources/test/fixtures/ruff/statement/with.py
  crates/ruff_python_formatter/src/statement/stmt_with.rs
  crates/ruff_python_formatter/tests/snapshots/format@statement__match.py.snap
  crates/ruff_python_formatter/tests/snapshots/format@statement__with.py.snap
Labels: internal

#9117 Document link between import sorting and formatter
  docs/formatter.md
Labels: documentation

#9031 release: switch to Cargo's default
  CONTRIBUTING.md
  Cargo.toml
  crates/ruff_python_parser/src/lexer/cursor.rs
Labels: internal

#9146 Prevent invalid utf8 indexing in cell magic detection
  crates/ruff_notebook/resources/test/fixtures/jupyter/cell/unicode_magic_gh9145.json
  crates/ruff_notebook/src/cell.rs
  crates/ruff_notebook/src/notebook.rs
Labels: bug

#9147 Fix panic in D208 with multibyte indent
  crates/ruff_linter/resources/test/fixtures/pydocstyle/D.py
  crates/ruff_linter/src/rules/pydocstyle/rules/indent.rs
  crates/ruff_linter/src/rules/pydocstyle/snapshots/ruff_linter__rules__pydocstyle__tests__D208_D.py.snap
  crates/ruff_linter/src/rules/pydocstyle/snapshots/ruff_linter__rules__pydocstyle__tests__D213_D.py.snap
Labels: bug, fuzzer

#9151 Add base-class inheritance detection to flake8-django rules
  crates/ruff_linter/resources/test/fixtures/flake8_django/DJ012.py
  crates/ruff_linter/src/checkers/ast/analyze/statement.rs
  crates/ruff_linter/src/rules/flake8_django/rules/all_with_model_form.rs
  crates/ruff_linter/src/rules/flake8_django/rules/exclude_with_model_form.rs
  crates/ruff_linter/src/rules/flake8_django/rules/helpers.rs
  crates/ruff_linter/src/rules/flake8_django/rules/model_without_dunder_str.rs
  crates/ruff_linter/src/rules/flake8_django/rules/unordered_body_content_in_model.rs
  crates/ruff_linter/src/rules/flake8_django/snapshots/ruff_linter__rules__flake8_django__tests__DJ012_DJ012.py.snap
  crates/ruff_linter/src/rules/flake8_type_checking/helpers.rs
  crates/ruff_python_semantic/src/analyze/class.rs
  crates/ruff_python_semantic/src/analyze/mod.rs
Labels: bug

#9157 Update ecosystem check headers to show unchanged project count
  python/ruff-ecosystem/ruff_ecosystem/check.py
  python/ruff-ecosystem/ruff_ecosystem/format.py
Labels: ci

#9158 Fix ecosystem format line changed counts
  python/ruff-ecosystem/ruff_ecosystem/types.py
Labels: ci

#9143 Add a rule to detect string members in runtime-evaluated unions
  crates/ruff_linter/resources/test/fixtures/flake8_type_checking/TCH006_1.py
  crates/ruff_linter/resources/test/fixtures/flake8_type_checking/TCH006_2.py
  crates/ruff_linter/src/checkers/ast/analyze/expression.rs
  crates/ruff_linter/src/codes.rs
  crates/ruff_linter/src/rules/flake8_type_checking/mod.rs
  crates/ruff_linter/src/rules/flake8_type_checking/rules/mod.rs
  crates/ruff_linter/src/rules/flake8_type_checking/rules/runtime_string_union.rs
  crates/ruff_linter/src/rules/flake8_type_checking/snapshots/ruff_linter__rules__flake8_type_checking__tests__runtime-string-union_TCH006_1.py.snap
  crates/ruff_linter/src/rules/flake8_type_checking/snapshots/ruff_linter__rules__flake8_type_checking__tests__runtime-string-union_TCH006_2.py.snap
  ruff.schema.json
Labels: rule, preview

#9167 Fix typo in SemanticModel.parent_expression docstring
  crates/ruff_python_semantic/src/model.rs
Labels: documentation

#9168 Avoid nested quotations in auto-quoting fix
  crates/ruff_linter/resources/test/fixtures/flake8_type_checking/quote.py
  crates/ruff_linter/src/rules/flake8_type_checking/helpers.rs
  crates/ruff_linter/src/rules/flake8_type_checking/rules/runtime_import_in_type_checking_block.rs
  crates/ruff_linter/src/rules/flake8_type_checking/rules/typing_only_runtime_import.rs
  crates/ruff_linter/src/rules/flake8_type_checking/snapshots/ruff_linter__rules__flake8_type_checking__tests__quote_typing-only-third-party-import_quote.py.snap
Labels: bug

#9175 Iterate over lambdas in deferred type annotations
  crates/ruff_linter/resources/test/fixtures/pyflakes/F401_20.py
  crates/ruff_linter/src/checkers/ast/mod.rs
  crates/ruff_linter/src/rules/pyflakes/mod.rs
  crates/ruff_linter/src/rules/pyflakes/snapshots/ruff_linter__rules__pyflakes__tests__F401_F401_20.py.snap
Labels: bug

#9171 Implement `reimplemented_operator` (FURB118)
  crates/ruff_linter/resources/test/fixtures/refurb/FURB118.py
  crates/ruff_linter/src/checkers/ast/analyze/deferred_lambdas.rs
  crates/ruff_linter/src/checkers/ast/analyze/statement.rs
  crates/ruff_linter/src/codes.rs
  crates/ruff_linter/src/rules/refurb/mod.rs
  crates/ruff_linter/src/rules/refurb/rules/mod.rs
  crates/ruff_linter/src/rules/refurb/rules/reimplemented_operator.rs
  crates/ruff_linter/src/rules/refurb/snapshots/ruff_linter__rules__refurb__tests__FURB118_FURB118.py.snap
  ruff.schema.json
Labels: rule, preview

#9187 Avoid `mutable-class-default` violations for Pydantic subclasses
  crates/ruff_linter/resources/test/fixtures/ruff/RUF012.py
  crates/ruff_linter/src/rules/ruff/rules/helpers.rs
Labels: bug

#9176 [`flake8-bugbear`] Add fix for `zip-without-explicit-strict` (`B905`)
  crates/ruff_linter/src/rules/flake8_bugbear/rules/zip_without_explicit_strict.rs
  crates/ruff_linter/src/rules/flake8_bugbear/snapshots/ruff_linter__rules__flake8_bugbear__tests__B905.py.snap
Labels: autofix

#9188 Add site-packages to default exclusions
  BREAKING_CHANGES.md
  README.md
  crates/ruff_workspace/src/settings.rs
  docs/configuration.md
Labels: breaking, configuration

#9192 Reverse order of arguments for `operator.contains`
  crates/ruff_linter/resources/test/fixtures/refurb/FURB118.py
  crates/ruff_linter/src/rules/refurb/rules/reimplemented_operator.rs
  crates/ruff_linter/src/rules/refurb/snapshots/ruff_linter__rules__refurb__tests__FURB118_FURB118.py.snap
Labels: bug

#9163 [`pylint`] Implement `too-many-locals` (`PLR0914`)
  crates/ruff_linter/resources/test/fixtures/pylint/too_many_locals.py
  crates/ruff_linter/src/checkers/ast/analyze/deferred_scopes.rs
  crates/ruff_linter/src/codes.rs
  crates/ruff_linter/src/rules/pylint/mod.rs
  crates/ruff_linter/src/rules/pylint/rules/mod.rs
  crates/ruff_linter/src/rules/pylint/rules/too_many_locals.rs
  crates/ruff_linter/src/rules/pylint/settings.rs
  crates/ruff_linter/src/rules/pylint/snapshots/ruff_linter__rules__pylint__tests__too_many_locals.snap
  crates/ruff_workspace/src/options.rs
  ruff.schema.json
Labels: rule, preview

#9154 Implement `no_blank_line_before_class_docstring` preview style
  crates/ruff_python_formatter/resources/test/fixtures/ruff/blank_line_before_class_docstring.options.json
  crates/ruff_python_formatter/resources/test/fixtures/ruff/blank_line_before_class_docstring.py
  crates/ruff_python_formatter/src/preview.rs
  crates/ruff_python_formatter/src/statement/suite.rs
  crates/ruff_python_formatter/tests/snapshots/black_compatibility@cases__preview_no_blank_line_before_docstring.py.snap
  crates/ruff_python_formatter/tests/snapshots/black_compatibility@cases__raw_docstring.py.snap
  crates/ruff_python_formatter/tests/snapshots/format@blank_line_before_class_docstring.py.snap
  crates/ruff_python_formatter/tests/snapshots/format@preview.py.snap
  crates/ruff_python_formatter/tests/snapshots/format@statement__class_definition.py.snap
Labels: formatter, preview

#9198 [flake8-pyi] Expand PYI018 to cover ParamSpecs and TypeVarTuples
  crates/ruff_linter/resources/test/fixtures/flake8_pyi/PYI018.py
  crates/ruff_linter/resources/test/fixtures/flake8_pyi/PYI018.pyi
  crates/ruff_linter/src/rules/flake8_pyi/rules/unused_private_type_definition.rs
  crates/ruff_linter/src/rules/flake8_pyi/snapshots/ruff_linter__rules__flake8_pyi__tests__PYI018_PYI018.py.snap
  crates/ruff_linter/src/rules/flake8_pyi/snapshots/ruff_linter__rules__flake8_pyi__tests__PYI018_PYI018.pyi.snap
Labels: rule

#9205 Add error suppression hint for multi-line strings
  crates/ruff_linter/src/rules/pycodestyle/rules/doc_line_too_long.rs
  crates/ruff_linter/src/rules/pycodestyle/rules/line_too_long.rs
Labels: documentation

#9206 Add support for `NoReturn` in auto-return-typing
  crates/ruff_linter/resources/test/fixtures/flake8_annotations/auto_return_type.py
  crates/ruff_linter/src/rules/flake8_annotations/helpers.rs
  crates/ruff_linter/src/rules/flake8_annotations/snapshots/ruff_linter__rules__flake8_annotations__tests__auto_return_type.snap
  crates/ruff_linter/src/rules/flake8_annotations/snapshots/ruff_linter__rules__flake8_annotations__tests__auto_return_type_py38.snap
  crates/ruff_python_ast/src/helpers.rs
Labels: bug

#9208 Add fix to automatically remove `print` and `pprint` statements
  crates/ruff_linter/src/rules/flake8_print/rules/print_call.rs
  crates/ruff_linter/src/rules/flake8_print/snapshots/ruff_linter__rules__flake8_print__tests__T201_T201.py.snap
  crates/ruff_linter/src/rules/flake8_print/snapshots/ruff_linter__rules__flake8_print__tests__T203_T203.py.snap
Labels: autofix

#9213 Prefer `Never` to `NoReturn` in auto-typing
  crates/ruff_linter/src/rules/flake8_annotations/helpers.rs
  crates/ruff_linter/src/rules/flake8_annotations/snapshots/ruff_linter__rules__flake8_annotations__tests__auto_return_type.snap
Labels: autofix

#9214 Allow removal of `typing` from `exempt-modules`
  crates/ruff_linter/resources/test/fixtures/flake8_type_checking/exempt_type_checking_1.py
  crates/ruff_linter/resources/test/fixtures/flake8_type_checking/exempt_type_checking_2.py
  crates/ruff_linter/resources/test/fixtures/flake8_type_checking/exempt_type_checking_3.py
  crates/ruff_linter/src/importer/mod.rs
  crates/ruff_linter/src/rules/flake8_type_checking/mod.rs
  crates/ruff_linter/src/rules/flake8_type_checking/rules/typing_only_runtime_import.rs
  crates/ruff_linter/src/rules/flake8_type_checking/snapshots/ruff_linter__rules__flake8_type_checking__tests__typing-only-standard-library-import_exempt_type_checking_1.py.snap
  crates/ruff_linter/src/rules/flake8_type_checking/snapshots/ruff_linter__rules__flake8_type_checking__tests__typing-only-standard-library-import_exempt_type_checking_2.py.snap
  crates/ruff_linter/src/rules/flake8_type_checking/snapshots/ruff_linter__rules__flake8_type_checking__tests__typing-only-standard-library-import_exempt_type_checking_3.py.snap
  crates/ruff_python_semantic/src/model.rs
Labels: bug

#9215 Avoid `asyncio-dangling-task` violations on shadowed bindings
  crates/ruff_linter/resources/test/fixtures/ruff/RUF006.py
  crates/ruff_linter/src/checkers/ast/analyze/bindings.rs
  crates/ruff_linter/src/checkers/ast/analyze/deferred_scopes.rs
  crates/ruff_linter/src/rules/ruff/rules/asyncio_dangling_task.rs
Labels: bug

#9209 Fix: Avoid parenthesizing subscript targets and values
  crates/ruff_python_formatter/resources/test/fixtures/ruff/statement/assignment_split_value_first.py
  crates/ruff_python_formatter/src/statement/stmt_assign.rs
  crates/ruff_python_formatter/tests/snapshots/format@statement__assignment_split_value_first.py.snap
Labels: formatter, preview

#9220 Add `target_version` to formatter options
  crates/ruff_linter/src/settings/types.rs
  crates/ruff_python_formatter/src/lib.rs
  crates/ruff_python_formatter/src/options.rs
  crates/ruff_python_formatter/tests/fixtures.rs
  crates/ruff_python_formatter/tests/snapshots/format@blank_line_before_class_docstring.py.snap
  crates/ruff_python_formatter/tests/snapshots/format@docstring.py.snap
  crates/ruff_python_formatter/tests/snapshots/format@docstring_code_examples.py.snap
  crates/ruff_python_formatter/tests/snapshots/format@docstring_code_examples_crlf.py.snap
  crates/ruff_python_formatter/tests/snapshots/format@docstring_code_examples_dynamic_line_width.py.snap
  crates/ruff_python_formatter/tests/snapshots/format@expression__bytes.py.snap
  crates/ruff_python_formatter/tests/snapshots/format@expression__string.py.snap
  crates/ruff_python_formatter/tests/snapshots/format@fmt_on_off__fmt_off_docstring.py.snap
  crates/ruff_python_formatter/tests/snapshots/format@fmt_on_off__indent.py.snap
  crates/ruff_python_formatter/tests/snapshots/format@fmt_on_off__mixed_space_and_tab.py.snap
  crates/ruff_python_formatter/tests/snapshots/format@preview.py.snap
  crates/ruff_python_formatter/tests/snapshots/format@quote_style.py.snap
  crates/ruff_python_formatter/tests/snapshots/format@skip_magic_trailing_comma.py.snap
  crates/ruff_python_formatter/tests/snapshots/format@statement__assignment_split_value_first.py.snap
  crates/ruff_python_formatter/tests/snapshots/format@tab_width.py.snap
  crates/ruff_workspace/src/configuration.rs
  crates/ruff_workspace/src/settings.rs
Labels: configuration, formatter

#9221 Set target versions in Black tests
  crates/ruff_python_formatter/resources/test/fixtures/black/cases/comment_type_hint.py
  crates/ruff_python_formatter/resources/test/fixtures/black/cases/comment_type_hint.py.expect
  crates/ruff_python_formatter/resources/test/fixtures/black/cases/comments2.py
  crates/ruff_python_formatter/resources/test/fixtures/black/cases/comments2.py.expect
  crates/ruff_python_formatter/resources/test/fixtures/black/cases/fmtskip2.py
  crates/ruff_python_formatter/resources/test/fixtures/black/cases/fmtskip2.py.expect
  crates/ruff_python_formatter/resources/test/fixtures/black/cases/funcdef_return_type_trailing_comma.options.json
  crates/ruff_python_formatter/resources/test/fixtures/black/cases/parenthesized_context_managers.options.json
  crates/ruff_python_formatter/resources/test/fixtures/black/cases/pattern_matching_complex.options.json
  crates/ruff_python_formatter/resources/test/fixtures/black/cases/pattern_matching_extras.options.json
  crates/ruff_python_formatter/resources/test/fixtures/black/cases/pattern_matching_generic.options.json
  crates/ruff_python_formatter/resources/test/fixtures/black/cases/pattern_matching_simple.options.json
  crates/ruff_python_formatter/resources/test/fixtures/black/cases/pattern_matching_style.options.json
  crates/ruff_python_formatter/resources/test/fixtures/black/cases/pep604_union_types_line_breaks.options.json
  crates/ruff_python_formatter/resources/test/fixtures/black/cases/pep_570.options.json
  crates/ruff_python_formatter/resources/test/fixtures/black/cases/pep_572.options.json
  crates/ruff_python_formatter/resources/test/fixtures/black/cases/pep_572_py310.options.json
  crates/ruff_python_formatter/resources/test/fixtures/black/cases/pep_572_py39.options.json
  crates/ruff_python_formatter/resources/test/fixtures/black/cases/pep_572_remove_parens.options.json
  crates/ruff_python_formatter/resources/test/fixtures/black/cases/pep_646.options.json
  crates/ruff_python_formatter/resources/test/fixtures/black/cases/pep_654.options.json
  crates/ruff_python_formatter/resources/test/fixtures/black/cases/pep_654_style.options.json
  crates/ruff_python_formatter/resources/test/fixtures/black/cases/preview_allow_empty_first_line.options.json
  crates/ruff_python_formatter/resources/test/fixtures/black/cases/preview_allow_empty_first_line.py
  crates/ruff_python_formatter/resources/test/fixtures/black/cases/preview_allow_empty_first_line.py.expect
  crates/ruff_python_formatter/resources/test/fixtures/black/cases/preview_context_managers_38.options.json
  crates/ruff_python_formatter/resources/test/fixtures/black/cases/preview_context_managers_39.options.json
  crates/ruff_python_formatter/resources/test/fixtures/black/cases/preview_context_managers_autodetect_310.options.json
  crates/ruff_python_formatter/resources/test/fixtures/black/cases/preview_context_managers_autodetect_311.options.json
  crates/ruff_python_formatter/resources/test/fixtures/black/cases/preview_context_managers_autodetect_39.options.json
  crates/ruff_python_formatter/resources/test/fixtures/black/cases/preview_dummy_implementations.py
  crates/ruff_python_formatter/resources/test/fixtures/black/cases/preview_dummy_implementations.py.expect
  crates/ruff_python_formatter/resources/test/fixtures/black/cases/preview_form_feeds.py.expect
  crates/ruff_python_formatter/resources/test/fixtures/black/cases/preview_hug_parens_with_braces_and_square_brackets.py
  crates/ruff_python_formatter/resources/test/fixtures/black/cases/preview_hug_parens_with_braces_and_square_brackets.py.expect
  crates/ruff_python_formatter/resources/test/fixtures/black/cases/preview_hug_parens_with_braces_and_square_brackets_no_ll1.options.json
  crates/ruff_python_formatter/resources/test/fixtures/black/cases/preview_hug_parens_with_braces_and_square_brackets_no_ll1.py
  crates/ruff_python_formatter/resources/test/fixtures/black/cases/preview_hug_parens_with_braces_and_square_brackets_no_ll1.py.expect
  crates/ruff_python_formatter/resources/test/fixtures/black/cases/preview_pattern_matching_long.options.json
  crates/ruff_python_formatter/resources/test/fixtures/black/cases/preview_pattern_matching_trailing_comma.options.json
  crates/ruff_python_formatter/resources/test/fixtures/black/cases/py310_pep572.options.json
  crates/ruff_python_formatter/resources/test/fixtures/black/cases/python37.options.json
  crates/ruff_python_formatter/resources/test/fixtures/black/cases/python38.options.json
  crates/ruff_python_formatter/resources/test/fixtures/black/cases/python39.options.json
  crates/ruff_python_formatter/resources/test/fixtures/black/cases/remove_newline_after_match.options.json
  crates/ruff_python_formatter/resources/test/fixtures/black/cases/remove_with_brackets.options.json
  crates/ruff_python_formatter/resources/test/fixtures/black/cases/starred_for_target.options.json
  crates/ruff_python_formatter/resources/test/fixtures/black/cases/type_params.options.json
  crates/ruff_python_formatter/resources/test/fixtures/import_black_tests.py
  crates/ruff_python_formatter/tests/snapshots/black_compatibility@cases__comments2.py.snap
  crates/ruff_python_formatter/tests/snapshots/black_compatibility@cases__preview_allow_empty_first_line.py.snap
  crates/ruff_python_formatter/tests/snapshots/black_compatibility@cases__preview_dummy_implementations.py.snap
  crates/ruff_python_formatter/tests/snapshots/black_compatibility@cases__preview_form_feeds.py.snap
  crates/ruff_python_formatter/tests/snapshots/black_compatibility@cases__preview_hug_parens_with_braces_and_square_brackets.py.snap
  crates/ruff_python_formatter/tests/snapshots/black_compatibility@cases__preview_hug_parens_with_braces_and_square_brackets_no_ll1.py.snap
Labels: internal, formatter

#9232 Clarify release workflow steps in CONTRIB guide
  CONTRIBUTING.md
Labels: internal

#9218 Add a fix for `never-union`
  crates/ruff_linter/resources/test/fixtures/ruff/RUF020.py
  crates/ruff_linter/src/checkers/ast/analyze/expression.rs
  crates/ruff_linter/src/rules/ruff/rules/never_union.rs
  crates/ruff_linter/src/rules/ruff/snapshots/ruff_linter__rules__ruff__tests__RUF020_RUF020.py.snap
Labels: autofix, preview

#9219 Make parent non-Optional in traverse_union
  crates/ruff_linter/src/rules/flake8_pyi/rules/duplicate_union_member.rs
  crates/ruff_linter/src/rules/flake8_pyi/rules/redundant_literal_union.rs
  crates/ruff_linter/src/rules/flake8_pyi/rules/redundant_numeric_union.rs
  crates/ruff_linter/src/rules/flake8_pyi/rules/unnecessary_literal_union.rs
  crates/ruff_linter/src/rules/flake8_pyi/rules/unnecessary_type_union.rs
  crates/ruff_python_semantic/src/analyze/typing.rs
Labels: internal

#9238 Wrap subscripted dicts in parens for f-string conversion
  crates/ruff_linter/resources/test/fixtures/pyupgrade/UP032_0.py
  crates/ruff_linter/src/rules/pyupgrade/rules/f_strings.rs
  crates/ruff_linter/src/rules/pyupgrade/snapshots/ruff_linter__rules__pyupgrade__tests__UP032_0.py.snap
Labels: bug

#9223 Show preview changes for tests with options
  crates/ruff_python_formatter/tests/fixtures.rs
  crates/ruff_python_formatter/tests/snapshots/format@docstring_code_examples_dynamic_line_width.py.snap
  crates/ruff_python_formatter/tests/snapshots/format@expression__string.py.snap
  crates/ruff_python_formatter/tests/snapshots/format@preview.py.snap
  crates/ruff_python_formatter/tests/snapshots/format@quote_style.py.snap
Labels: internal, formatter

#9239 Use named preview test functions
  crates/ruff_python_formatter/src/preview.rs
  crates/ruff_python_formatter/src/statement/clause.rs
  crates/ruff_python_formatter/src/statement/suite.rs
Labels: internal

#9210 Parenthesize long type annotations in annotated assignments
  crates/ruff_python_formatter/resources/test/fixtures/ruff/statement/long_type_annotations.py
  crates/ruff_python_formatter/src/expression/mod.rs
  crates/ruff_python_formatter/src/preview.rs
  crates/ruff_python_formatter/src/statement/stmt_ann_assign.rs
  crates/ruff_python_formatter/src/statement/stmt_assign.rs
  crates/ruff_python_formatter/tests/snapshots/black_compatibility@cases__pep604_union_types_line_breaks.py.snap
  crates/ruff_python_formatter/tests/snapshots/format@statement__ann_assign.py.snap
  crates/ruff_python_formatter/tests/snapshots/format@statement__long_type_annotations.py.snap
Labels: formatter, preview

#9222 Parenthesize multi-context managers
  crates/ruff_python_formatter/resources/test/fixtures/ruff/statement/with.options.json
  crates/ruff_python_formatter/resources/test/fixtures/ruff/statement/with_39.options.json
  crates/ruff_python_formatter/resources/test/fixtures/ruff/statement/with_39.py
  crates/ruff_python_formatter/src/expression/mod.rs
  crates/ruff_python_formatter/src/other/with_item.rs
  crates/ruff_python_formatter/src/preview.rs
  crates/ruff_python_formatter/src/statement/stmt_with.rs
  crates/ruff_python_formatter/tests/snapshots/black_compatibility@cases__preview_context_managers_39.py.snap
  crates/ruff_python_formatter/tests/snapshots/black_compatibility@cases__preview_context_managers_autodetect_310.py.snap
  crates/ruff_python_formatter/tests/snapshots/black_compatibility@cases__preview_context_managers_autodetect_311.py.snap
  crates/ruff_python_formatter/tests/snapshots/black_compatibility@cases__preview_context_managers_autodetect_39.py.snap
  crates/ruff_python_formatter/tests/snapshots/format@statement__with.py.snap
  crates/ruff_python_formatter/tests/snapshots/format@statement__with_39.py.snap
Labels: formatter, preview

#9240 Improve `dummy_implementations` preview style formatting
  crates/ruff_python_formatter/resources/test/fixtures/ruff/newlines.py
  crates/ruff_python_formatter/src/statement/clause.rs
  crates/ruff_python_formatter/src/statement/suite.rs
  crates/ruff_python_formatter/tests/snapshots/black_compatibility@cases__preview_dummy_implementations.py.snap
  crates/ruff_python_formatter/tests/snapshots/format@newlines.py.snap
  crates/ruff_python_formatter/tests/snapshots/format@statement__top_level.py.snap
Labels: formatter, preview

#9248 Fix scoping for generators in named expressions in classes
  crates/ruff_linter/resources/test/fixtures/pyflakes/F821_24.py
  crates/ruff_linter/src/checkers/ast/mod.rs
  crates/ruff_linter/src/rules/pyflakes/mod.rs
  crates/ruff_linter/src/rules/pyflakes/snapshots/ruff_linter__rules__pyflakes__tests__F821_F821_24.py.snap
Labels: bug

#9249 ci: group dependabot updates
  .github/dependabot.yml
Labels: ci

#9258 Remove separate `push` method
  crates/ruff_linter/src/checkers/logical_lines.rs
Labels: internal

#9259 Remove unnecessary rule enabled check
  crates/ruff_linter/src/rules/pylint/rules/and_or_ternary.rs
Labels: internal

#9261 Remove special pre-visit for module docstrings
  crates/ruff_linter/resources/test/fixtures/pycodestyle/E402_0.py
  crates/ruff_linter/resources/test/fixtures/pycodestyle/E402_1.py
  crates/ruff_linter/resources/test/fixtures/pyflakes/F404_0.py
  crates/ruff_linter/resources/test/fixtures/pyflakes/F404_1.py
  crates/ruff_linter/resources/test/fixtures/pyupgrade/UP025.py
  crates/ruff_linter/src/checkers/ast/mod.rs
  crates/ruff_linter/src/rules/pycodestyle/mod.rs
  crates/ruff_linter/src/rules/pycodestyle/snapshots/ruff_linter__rules__pycodestyle__tests__E402_E402_0.py.snap
  crates/ruff_linter/src/rules/pycodestyle/snapshots/ruff_linter__rules__pycodestyle__tests__E402_E402_1.py.snap
  crates/ruff_linter/src/rules/pycodestyle/snapshots/ruff_linter__rules__pycodestyle__tests__preview__E402_E402_0.py.snap
  crates/ruff_linter/src/rules/pyflakes/mod.rs
  crates/ruff_linter/src/rules/pyflakes/snapshots/ruff_linter__rules__pyflakes__tests__F404_F404_0.py.snap
  crates/ruff_linter/src/rules/pyflakes/snapshots/ruff_linter__rules__pyflakes__tests__F404_F404_1.py.snap
  crates/ruff_linter/src/rules/pyupgrade/snapshots/ruff_linter__rules__pyupgrade__tests__UP025.py.snap
  crates/ruff_python_semantic/src/model.rs
Labels: bug

#9263 Avoid `asyncio-dangling-task` for nonlocal and global bindings
  crates/ruff_linter/resources/test/fixtures/ruff/RUF006.py
  crates/ruff_linter/src/rules/ruff/rules/asyncio_dangling_task.rs
Labels: bug

#9264 Remove lexing and parsing from the linter benchmark
  crates/ruff_benchmark/benches/linter.rs
  crates/ruff_cli/src/diagnostics.rs
  crates/ruff_linter/src/linter.rs
  crates/ruff_linter/src/rules/pyflakes/mod.rs
  crates/ruff_linter/src/test.rs
  crates/ruff_python_parser/src/lexer.rs
  crates/ruff_python_parser/src/string.rs
  crates/ruff_wasm/src/lib.rs
Labels: internal

#9277 Avoid adding return types to stub methods
  crates/ruff_linter/resources/test/fixtures/flake8_annotations/auto_return_type.py
  crates/ruff_linter/src/rules/flake8_annotations/rules/definition.rs
Labels: bug

#9290 [`refurb`] Avoid false positives for `math-constant` (`FURB152`)
  crates/ruff_linter/resources/test/fixtures/refurb/FURB152.py
  crates/ruff_linter/src/rules/refurb/rules/math_constant.rs
  crates/ruff_linter/src/rules/refurb/snapshots/ruff_linter__rules__refurb__tests__FURB152_FURB152.py.snap
Labels: bug

#9265 [`refurb`] Implement `bit-count` (`FURB161`)
  crates/ruff_linter/resources/test/fixtures/refurb/FURB161.py
  crates/ruff_linter/src/checkers/ast/analyze/expression.rs
  crates/ruff_linter/src/codes.rs
  crates/ruff_linter/src/rules/flake8_pyi/rules/future_annotations_in_stub.rs
  crates/ruff_linter/src/rules/refurb/mod.rs
  crates/ruff_linter/src/rules/refurb/rules/bit_count.rs
  crates/ruff_linter/src/rules/refurb/rules/mod.rs
  crates/ruff_linter/src/rules/refurb/snapshots/ruff_linter__rules__refurb__tests__FURB161_FURB161.py.snap
  ruff.schema.json
Labels: rule, preview

#9280 Normalise Hex and unicode escape sequences in string
  crates/ruff_python_formatter/resources/test/fixtures/ruff/expression/bytes.py
  crates/ruff_python_formatter/resources/test/fixtures/ruff/expression/string.py
  crates/ruff_python_formatter/src/other/bytes_literal.rs
  crates/ruff_python_formatter/src/other/f_string.rs
  crates/ruff_python_formatter/src/other/string_literal.rs
  crates/ruff_python_formatter/src/preview.rs
  crates/ruff_python_formatter/src/string/mod.rs
  crates/ruff_python_formatter/tests/snapshots/black_compatibility@cases__preview_format_unicode_escape_seq.py.snap
  crates/ruff_python_formatter/tests/snapshots/format@expression__bytes.py.snap
  crates/ruff_python_formatter/tests/snapshots/format@expression__string.py.snap
Labels: formatter, preview

#9300 Respect `unused-noqa` via `per-file-ignores`
  crates/ruff_linter/resources/test/fixtures/ruff/ruff_per_file_ignores.py
  crates/ruff_linter/src/checkers/noqa.rs
  crates/ruff_linter/src/linter.rs
  crates/ruff_linter/src/rules/ruff/mod.rs
  crates/ruff_linter/src/rules/ruff/snapshots/ruff_linter__rules__ruff__tests__ruff_per_file_ignores.snap
Labels: bug

#9296 Add PyVista into the `Who's Using Ruff?` section
  README.md
Labels: documentation

#9299 [flake8-bandit/S506] Dont report violation when SafeLoader is imported from yaml.loader
  crates/ruff_linter/resources/test/fixtures/flake8_bandit/S506.py
  crates/ruff_linter/src/rules/flake8_bandit/rules/unsafe_yaml_load.rs
Labels: bug

#9301 Escape trailing placeholders in rule documentation
  crates/ruff_dev/src/generate_rules_table.rs
Labels: bug

#9302 Expand target name for better rule documentation
  crates/ruff_linter/src/rules/refurb/rules/reimplemented_operator.rs
Labels: documentation

#9294 Exclude failing sphinx file in ecosytem checks
  python/ruff-ecosystem/ruff_ecosystem/defaults.py
Labels: ci

#9286 Allow config-file overrides in ecosystem checks
  python/ruff-ecosystem/pyproject.toml
  python/ruff-ecosystem/ruff_ecosystem/check.py
  python/ruff-ecosystem/ruff_ecosystem/defaults.py
  python/ruff-ecosystem/ruff_ecosystem/format.py
  python/ruff-ecosystem/ruff_ecosystem/main.py
  python/ruff-ecosystem/ruff_ecosystem/projects.py
Labels: ci

#9174 [`pylint`] Implement `empty-comment` (`PLR2044`)
  Cargo.lock
  crates/ruff_linter/resources/test/fixtures/pylint/empty_comment.py
  crates/ruff_linter/src/checkers/physical_lines.rs
  crates/ruff_linter/src/checkers/tokens.rs
  crates/ruff_linter/src/codes.rs
  crates/ruff_linter/src/registry.rs
  crates/ruff_linter/src/rules/pylint/mod.rs
  crates/ruff_linter/src/rules/pylint/rules/empty_comment.rs
  crates/ruff_linter/src/rules/pylint/rules/mod.rs
  crates/ruff_linter/src/rules/pylint/snapshots/ruff_linter__rules__pylint__tests__PLR2044_empty_comment.py.snap
  crates/ruff_python_trivia/Cargo.toml
  crates/ruff_python_trivia/src/comment_ranges.rs
  ruff.schema.json
Labels: rule, preview

#9308 Change PLR0917 error message to match other PLR09XX messages
  crates/ruff_linter/src/rules/pylint/rules/too_many_positional.rs
  crates/ruff_linter/src/rules/pylint/snapshots/ruff_linter__rules__pylint__tests__PLR0917_too_many_positional.py.snap
  crates/ruff_linter/src/rules/pylint/snapshots/ruff_linter__rules__pylint__tests__max_positional_args.snap
Labels: bug

#9306 [`pyupgrade`] Document more fix unsafety for UP007
  crates/ruff_linter/src/rules/pyupgrade/rules/use_pep604_annotation.rs
Labels: documentation

#9309 Respect attribute chains when resolving builtin call paths
  crates/ruff_linter/resources/test/fixtures/pyflakes/F821_25.py
  crates/ruff_linter/src/rules/pyflakes/mod.rs
  crates/ruff_linter/src/rules/pyflakes/snapshots/ruff_linter__rules__pyflakes__tests__F821_F821_25.py.snap
  crates/ruff_python_semantic/src/analyze/typing.rs
  crates/ruff_python_semantic/src/model.rs
Labels: bug

#9310 Respect mixed `return` and `raise` cases in return-type analysis
  crates/ruff_linter/resources/test/fixtures/flake8_annotations/auto_return_type.py
  crates/ruff_linter/src/rules/flake8_annotations/helpers.rs
  crates/ruff_linter/src/rules/flake8_annotations/snapshots/ruff_linter__rules__flake8_annotations__tests__auto_return_type.snap
  crates/ruff_linter/src/rules/flake8_annotations/snapshots/ruff_linter__rules__flake8_annotations__tests__auto_return_type_py38.snap
  crates/ruff_python_ast/src/helpers.rs
  crates/ruff_python_semantic/src/analyze/mod.rs
  crates/ruff_python_semantic/src/analyze/terminal.rs
Labels: bug

#9316 Use `Display` for formatter parse errors
  crates/ruff_cli/src/commands/format.rs
  crates/ruff_cli/tests/format.rs
  crates/ruff_python_formatter/src/lib.rs
  crates/ruff_python_parser/src/lexer.rs
  crates/ruff_python_parser/src/parser.rs
Labels: cli, formatter

#9317 Respect runtime-required decorators on functions
  crates/ruff_linter/resources/test/fixtures/flake8_type_checking/runtime_evaluated_decorators_3.py
  crates/ruff_linter/src/checkers/ast/annotation.rs
  crates/ruff_linter/src/rules/flake8_type_checking/helpers.rs
  crates/ruff_linter/src/rules/flake8_type_checking/mod.rs
  crates/ruff_linter/src/rules/flake8_type_checking/snapshots/ruff_linter__rules__flake8_type_checking__tests__typing-only-standard-library-import_runtime_evaluated_decorators_3.py.snap
  crates/ruff_workspace/src/options.rs
  ruff.schema.json
Labels: configuration

#9318 Fix typo in truncation comment
  python/ruff-ecosystem/ruff_ecosystem/check.py
Labels: internal

#9314 Report errors when repositories cannot be cloned during ecosystem checks
  python/ruff-ecosystem/ruff_ecosystem/projects.py
Labels: ci

#9320 Use consistent re-export from `ruff_source_file`
  crates/ruff_linter/src/linter.rs
  crates/ruff_python_ast/src/whitespace.rs
  crates/ruff_python_trivia/src/textwrap.rs
  crates/ruff_source_file/src/lib.rs
Labels: internal

#9322 Remove source path from parser errors
  crates/ruff_benchmark/benches/formatter.rs
  crates/ruff_benchmark/benches/linter.rs
  crates/ruff_benchmark/benches/parser.rs
  crates/ruff_cli/src/diagnostics.rs
  crates/ruff_dev/src/print_ast.rs
  crates/ruff_dev/src/round_trip.rs
  crates/ruff_linter/src/fix/edits.rs
  crates/ruff_linter/src/importer/insertion.rs
  crates/ruff_linter/src/linter.rs
  crates/ruff_linter/src/logging.rs
  crates/ruff_linter/src/rules/eradicate/detection.rs
  crates/ruff_linter/src/rules/isort/rules/add_required_imports.rs
  crates/ruff_linter/src/rules/mccabe/rules/function_is_too_complex.rs
  crates/ruff_linter/src/rules/pylint/rules/too_many_branches.rs
  crates/ruff_linter/src/rules/pylint/rules/too_many_return_statements.rs
  crates/ruff_linter/src/rules/pylint/rules/too_many_statements.rs
  crates/ruff_linter/src/rules/ruff/rules/unreachable.rs
  crates/ruff_python_ast/tests/identifier.rs
  crates/ruff_python_ast/tests/parenthesize.rs
  crates/ruff_python_ast/tests/preorder.rs
  crates/ruff_python_ast/tests/stmt_if.rs
  crates/ruff_python_ast/tests/visitor.rs
  crates/ruff_python_codegen/src/generator.rs
  crates/ruff_python_codegen/src/lib.rs
  crates/ruff_python_formatter/src/cli.rs
  crates/ruff_python_formatter/src/comments/mod.rs
  crates/ruff_python_formatter/src/expression/expr_name.rs
  crates/ruff_python_formatter/src/expression/parentheses.rs
  crates/ruff_python_formatter/src/lib.rs
  crates/ruff_python_formatter/src/statement/suite.rs
  crates/ruff_python_formatter/src/string/docstring.rs
  crates/ruff_python_formatter/tests/fixtures.rs
  crates/ruff_python_parser/src/context.rs
  crates/ruff_python_parser/src/function.rs
  crates/ruff_python_parser/src/invalid.rs
  crates/ruff_python_parser/src/lib.rs
  crates/ruff_python_parser/src/parser.rs
  crates/ruff_python_parser/src/string.rs
  crates/ruff_python_parser/src/typing.rs
  crates/ruff_python_semantic/src/analyze/type_inference.rs
  crates/ruff_python_trivia/src/whitespace.rs
  crates/ruff_shrinking/src/main.rs
  crates/ruff_wasm/src/lib.rs
  fuzz/fuzz_targets/ruff_parse_idempotency.rs
  fuzz/fuzz_targets/ruff_parse_simple.rs
Labels: internal

#9321 Add row and column numbers to formatted parse errors
  crates/ruff_cli/src/commands/format.rs
  crates/ruff_cli/src/diagnostics.rs
  crates/ruff_cli/tests/format.rs
  crates/ruff_dev/src/format_dev.rs
  crates/ruff_linter/src/linter.rs
  crates/ruff_linter/src/logging.rs
  crates/ruff_python_formatter/src/lib.rs
  crates/ruff_python_formatter/src/string/docstring.rs
  crates/ruff_python_parser/src/parser.rs
Labels: bug, cli

#9315 Improve responsiveness when invoked via Python
  python/ruff/__main__.py
Labels: cli

#9330 Remove some unused dependencies
  Cargo.lock
  crates/ruff_cli/Cargo.toml
  crates/ruff_dev/Cargo.toml
  crates/ruff_python_ast/Cargo.toml
  crates/ruff_python_index/Cargo.toml
  crates/ruff_wasm/Cargo.toml
  fuzz/Cargo.toml
Labels: internal

#9331 Avoid panic when comment is preceded by Unicode
  crates/ruff_linter/resources/test/fixtures/pylint/empty_comment.py
  crates/ruff_linter/src/rules/pylint/rules/empty_comment.rs
  crates/ruff_linter/src/rules/pylint/snapshots/ruff_linter__rules__pylint__tests__PLR2044_empty_comment.py.snap
Labels: bug, fuzzer

#9332 Fix continuation detection following multi-line strings
  crates/ruff_linter/resources/test/fixtures/pycodestyle/W293.py
  crates/ruff_linter/src/rules/pycodestyle/mod.rs
  crates/ruff_linter/src/rules/pycodestyle/snapshots/ruff_linter__rules__pycodestyle__tests__W293_W293.py.snap
  crates/ruff_python_index/src/indexer.rs
Labels: bug, fuzzer

#9325 Make `DisplayParseError` an error type
  crates/ruff_cli/Cargo.toml
  crates/ruff_cli/src/commands/format.rs
  crates/ruff_cli/src/diagnostics.rs
  crates/ruff_linter/src/linter.rs
  crates/ruff_linter/src/logging.rs
Labels: internal

#9329 Remove `flake8-to-ruff`
  .github/workflows/flake8-to-ruff.yaml
  Cargo.lock
  crates/flake8_to_ruff/Cargo.toml
  crates/flake8_to_ruff/README.md
  crates/flake8_to_ruff/examples/cryptography/pyproject.toml
  crates/flake8_to_ruff/examples/cryptography/setup.cfg
  crates/flake8_to_ruff/examples/jupyterhub.ini
  crates/flake8_to_ruff/examples/manim.ini
  crates/flake8_to_ruff/examples/poetry.ini
  crates/flake8_to_ruff/examples/python-discord.ini
  crates/flake8_to_ruff/examples/requests.ini
  crates/flake8_to_ruff/pyproject.toml
  crates/flake8_to_ruff/src/black.rs
  crates/flake8_to_ruff/src/converter.rs
  crates/flake8_to_ruff/src/external_config.rs
  crates/flake8_to_ruff/src/isort.rs
  crates/flake8_to_ruff/src/main.rs
  crates/flake8_to_ruff/src/parser.rs
  crates/flake8_to_ruff/src/pep621.rs
  crates/flake8_to_ruff/src/plugin.rs
  crates/flake8_to_ruff/src/pyproject.rs
  pyproject.toml
Labels: internal

#9335 Treat all `typing_extensions` members as typing aliases
  crates/ruff_linter/resources/test/fixtures/ruff/RUF013_2.py
  crates/ruff_linter/src/rules/flake8_pyi/snapshots/ruff_linter__rules__flake8_pyi__tests__PYI050_PYI050.py.snap
  crates/ruff_linter/src/rules/flake8_pyi/snapshots/ruff_linter__rules__flake8_pyi__tests__PYI050_PYI050.pyi.snap
  crates/ruff_linter/src/rules/ruff/mod.rs
  crates/ruff_linter/src/rules/ruff/snapshots/ruff_linter__rules__ruff__tests__RUF013_RUF013_2.py.snap
  crates/ruff_python_semantic/src/model.rs
  crates/ruff_python_stdlib/src/typing.rs
Labels: bug
