Repository astral-sh/ruff, pull requests merged in 2023-11, with the labels that each got.

#8399 Add PEP reference to `D212`, `D213` docs
  crates/ruff_linter/src/rules/pydocstyle/rules/multi_line_summary_start.rs
Labels: documentation

#8358 Run ecosystem checks with preview mode enabled
  .github/workflows/ci.yaml
  python/ruff-ecosystem/ruff_ecosystem/check.py
  python/ruff-ecosystem/ruff_ecosystem/cli.py
  python/ruff-ecosystem/ruff_ecosystem/format.py
  python/ruff-ecosystem/ruff_ecosystem/projects.py
Labels: internal

#8414 Include rust-toolchain in source distribution
  .github/workflows/release.yaml
  pyproject.toml
Labels: release

#8413 Update the contributing guide with basic `ruff-ecosystem` instructions
  CONTRIBUTING.md
Labels: documentation

#8410 Use production builds of Ruff for pre-commit
  .pre-commit-config.yaml
Labels: internal

#8412 Change default format for ecosystem checks to `markdown`
  python/ruff-ecosystem/README.md
  python/ruff-ecosystem/ruff_ecosystem/cli.py
Labels: internal

#8416 Add new ecosystem comparison modes for the formatter
  python/ruff-ecosystem/README.md
  python/ruff-ecosystem/ruff_ecosystem/cli.py
  python/ruff-ecosystem/ruff_ecosystem/format.py
  python/ruff-ecosystem/ruff_ecosystem/main.py
  python/ruff-ecosystem/ruff_ecosystem/projects.py
Labels: internal

#8419 Add support for `ruff-ecosystem` format comparisons with `black`
  python/ruff-ecosystem/README.md
  python/ruff-ecosystem/ruff_ecosystem/check.py
  python/ruff-ecosystem/ruff_ecosystem/cli.py
  python/ruff-ecosystem/ruff_ecosystem/format.py
  python/ruff-ecosystem/ruff_ecosystem/main.py
  python/ruff-ecosystem/ruff_ecosystem/markdown.py
  python/ruff-ecosystem/ruff_ecosystem/projects.py
  python/ruff-ecosystem/ruff_ecosystem/types.py
Labels: internal

#8420 Pull updates for refs in cached repos in ecosystem checks
  python/ruff-ecosystem/ruff_ecosystem/projects.py
Labels: internal

#8363 Add `--line-length` option to `format` command
  crates/ruff_cli/src/args.rs
  crates/ruff_python_formatter/README.md
  docs/configuration.md
Labels: cli, formatter

#8432 Add caveat around action comments within docstrings
  docs/linter.md
Labels: documentation

#8433 Avoid triggering single-element test for starred expressions
  crates/ruff_linter/resources/test/fixtures/refurb/FURB171.py
  crates/ruff_linter/src/rules/refurb/rules/single_item_membership_test.rs
Labels: bug, fuzzer

#8434 Avoid triggering `NamedTuple` rewrite with starred annotation
  crates/ruff_linter/resources/test/fixtures/pyupgrade/UP014.py
  crates/ruff_linter/src/rules/pyupgrade/rules/convert_named_tuple_functional_to_class.rs
Labels: bug, fuzzer

#8407 Fix bug where `PLE1307` was raised when formatting `%c` with characters
  crates/ruff_linter/resources/test/fixtures/pylint/bad_string_format_type.py
  crates/ruff_linter/src/rules/pylint/rules/bad_string_format_type.rs
Labels: bug

#8440 Remove unicode flag from comparable
  crates/ruff_python_ast/src/comparable.rs
Labels: internal

#8448 Fix documentation for `RuleTable`
  crates/ruff_linter/src/settings/rule_table.rs
Labels: internal

#8439 Add flake8-trio support
  LICENSE
  README.md
  crates/ruff_linter/resources/test/fixtures/flake8_trio/TRIO100.py
  crates/ruff_linter/src/checkers/ast/analyze/statement.rs
  crates/ruff_linter/src/codes.rs
  crates/ruff_linter/src/registry.rs
  crates/ruff_linter/src/rules/flake8_trio/mod.rs
  crates/ruff_linter/src/rules/flake8_trio/rules/mod.rs
  crates/ruff_linter/src/rules/flake8_trio/rules/timeout_without_await.rs
  crates/ruff_linter/src/rules/flake8_trio/snapshots/ruff_linter__rules__flake8_trio__tests__TRIO100_TRIO100.py.snap
  crates/ruff_linter/src/rules/mod.rs
  docs/faq.md
  ruff.schema.json
Labels: rule

#8398 Detect and ignore Jupyter automagics
  crates/ruff_notebook/resources/test/fixtures/jupyter/cell/automagic.json
  crates/ruff_notebook/resources/test/fixtures/jupyter/cell/automagic_after_code.json
  crates/ruff_notebook/resources/test/fixtures/jupyter/cell/automagic_before_code.json
  crates/ruff_notebook/resources/test/fixtures/jupyter/cell/automagics.json
  crates/ruff_notebook/src/notebook.rs
Labels: bug

#7702 Implement NumPy 2.0 migration rule
  crates/ruff_linter/resources/test/fixtures/numpy/NPY201.py
  crates/ruff_linter/src/checkers/ast/analyze/expression.rs
  crates/ruff_linter/src/codes.rs
  crates/ruff_linter/src/rules/numpy/mod.rs
  crates/ruff_linter/src/rules/numpy/rules/mod.rs
  crates/ruff_linter/src/rules/numpy/rules/numpy_2_0_deprecation.rs
  crates/ruff_linter/src/rules/numpy/snapshots/ruff_linter__rules__numpy__tests__numpy2-deprecation_NPY201.py.snap
  ruff.schema.json
Labels: rule

#8455 Formatter: Remove unnecessary `group`
  crates/ruff_python_ast/src/nodes.rs
  crates/ruff_python_formatter/src/other/parameter_with_default.rs
Labels: internal

#8458 Use `fixedOverflowWidgets` for playground popover
  playground/src/Editor/SourceEditor.tsx
  playground/src/index.css
Labels: playground

#8459 Re-run `scripts/update_ambiguous_characters.py`
  scripts/update_ambiguous_characters.py
Labels: internal

#8460 Upgrade `PyYAML` to `6.0.1` to avoid build error
  docs/requirements-insiders.txt
  docs/requirements.txt
Labels: dependencies

#8431 Avoid parenthesizing unsplittable because of comments
  crates/ruff_python_formatter/resources/test/fixtures/ruff/expression/optional_parentheses_comments.py
  crates/ruff_python_formatter/src/expression/expr_await.rs
  crates/ruff_python_formatter/src/expression/expr_yield.rs
  crates/ruff_python_formatter/src/expression/mod.rs
  crates/ruff_python_formatter/tests/snapshots/black_compatibility@simple_cases__remove_await_parens.py.snap
  crates/ruff_python_formatter/tests/snapshots/format@expression__optional_parentheses_comments.py.snap
  crates/ruff_python_formatter/tests/snapshots/format@expression__unsplittable.py.snap
  crates/ruff_python_formatter/tests/snapshots/format@parentheses__expression_parentheses_comments.py.snap
Labels: formatter, style

#8461 Provide example for exclusive linting or formatting Notebooks
  docs/configuration.md
Labels: documentation

#8463 Use characters instead of `u32` in confusable map
  crates/ruff_linter/src/rules/ruff/rules/ambiguous_unicode_character.rs
  crates/ruff_linter/src/rules/ruff/rules/confusables.rs
  scripts/update_ambiguous_characters.py
Labels: internal

#8475 Remove trailing periods from NumPy 2.0 code actions
  crates/ruff_linter/src/rules/numpy/rules/numpy_2_0_deprecation.rs
  crates/ruff_linter/src/rules/numpy/snapshots/ruff_linter__rules__numpy__tests__numpy2-deprecation_NPY201.py.snap
Labels: bug

#8462 `D300`: prevent autofix when both triples are in body
  crates/ruff_linter/resources/test/fixtures/pydocstyle/D300.py
  crates/ruff_linter/src/rules/pydocstyle/rules/triple_quotes.rs
  crates/ruff_linter/src/rules/pydocstyle/snapshots/ruff_linter__rules__pydocstyle__tests__preview__D300_D300.py.snap
Labels: bug

#8476 Add pyupgrade UP041 to replace TimeoutError aliases
  crates/ruff_linter/resources/test/fixtures/pyupgrade/UP041.py
  crates/ruff_linter/src/checkers/ast/analyze/expression.rs
  crates/ruff_linter/src/checkers/ast/analyze/statement.rs
  crates/ruff_linter/src/codes.rs
  crates/ruff_linter/src/rules/pyupgrade/mod.rs
  crates/ruff_linter/src/rules/pyupgrade/rules/mod.rs
  crates/ruff_linter/src/rules/pyupgrade/rules/timeout_error_alias.rs
  crates/ruff_linter/src/rules/pyupgrade/snapshots/ruff_linter__rules__pyupgrade__tests__UP041.py.snap
  ruff.schema.json
Labels: rule

#8478 Add changelog for v0.1.4
  CHANGELOG.md
Labels: release

#8479 Add missing pyupgrade entry to changelog
  CHANGELOG.md
Labels: internal

#8485 [`E721`] Flag comparisons to `memoryview`
  crates/ruff_linter/resources/test/fixtures/pycodestyle/E721.py
  crates/ruff_linter/src/rules/pycodestyle/rules/type_comparison.rs
  crates/ruff_linter/src/rules/pycodestyle/snapshots/ruff_linter__rules__pycodestyle__tests__E721_E721.py.snap
  crates/ruff_linter/src/rules/pycodestyle/snapshots/ruff_linter__rules__pycodestyle__tests__preview__E721_E721.py.snap
Labels: bug

#8466 Fix multiline lambda expression statement formating
  crates/ruff_python_formatter/resources/test/fixtures/ruff/expression/lambda.py
  crates/ruff_python_formatter/src/other/parameters.rs
  crates/ruff_python_formatter/tests/snapshots/format@expression__lambda.py.snap
Labels: formatter

#8495 Avoid `D301` autofix for `u` prefixed strings
  crates/ruff_linter/resources/test/fixtures/pydocstyle/D301.py
  crates/ruff_linter/src/rules/pydocstyle/rules/backslashes.rs
  crates/ruff_linter/src/rules/pydocstyle/snapshots/ruff_linter__rules__pydocstyle__tests__D301_D301.py.snap
Labels: bug

#8480 Added tabs for configuration files in the documentation
  .pre-commit-config.yaml
  crates/ruff_dev/src/generate_options.rs
  docs/configuration.md
  docs/faq.md
  docs/formatter.md
  docs/linter.md
  docs/preview.md
  docs/tutorial.md
  mkdocs.template.yml
Labels: documentation

#8488 Add instructions for configuration of Emacs
  docs/integrations.md
Labels: documentation

#8490 [`TRIO`] Add `TRIO105`: `SyncTrioCall`
  crates/ruff_linter/resources/test/fixtures/flake8_trio/TRIO105.py
  crates/ruff_linter/src/checkers/ast/analyze/expression.rs
  crates/ruff_linter/src/codes.rs
  crates/ruff_linter/src/rules/flake8_trio/method_name.rs
  crates/ruff_linter/src/rules/flake8_trio/mod.rs
  crates/ruff_linter/src/rules/flake8_trio/rules/mod.rs
  crates/ruff_linter/src/rules/flake8_trio/rules/sync_call.rs
  crates/ruff_linter/src/rules/flake8_trio/rules/timeout_without_await.rs
  crates/ruff_linter/src/rules/flake8_trio/snapshots/ruff_linter__rules__flake8_trio__tests__TRIO105_TRIO105.py.snap
  crates/ruff_python_ast/src/helpers.rs
  ruff.schema.json
Labels: rule, preview

#8499 Allow collapsed-ellipsis bodies in other statements
  crates/ruff_linter/resources/test/fixtures/pycodestyle/E70.py
  crates/ruff_linter/src/rules/pycodestyle/rules/compound_statements.rs
  crates/ruff_linter/src/rules/pycodestyle/snapshots/ruff_linter__rules__pycodestyle__tests__E703_E70.py.snap
Labels: bug

#8500 Add notes on fix safety to a few rules
  crates/ruff_linter/src/rules/flake8_bugbear/rules/assert_false.rs
  crates/ruff_linter/src/rules/flake8_trio/rules/sync_call.rs
  crates/ruff_linter/src/rules/pyupgrade/rules/use_pep695_type_alias.rs
  crates/ruff_linter/src/rules/ruff/rules/unnecessary_iterable_allocation_for_first_element.rs
  crates/ruff_linter/src/rules/tryceratops/rules/verbose_raise.rs
Labels: documentation

#8487 [`refurb`] Implement `type-none-comparison` (`FURB169`)
  crates/ruff_linter/resources/test/fixtures/refurb/FURB169.py
  crates/ruff_linter/src/checkers/ast/analyze/expression.rs
  crates/ruff_linter/src/codes.rs
  crates/ruff_linter/src/rules/refurb/helpers.rs
  crates/ruff_linter/src/rules/refurb/mod.rs
  crates/ruff_linter/src/rules/refurb/rules/isinstance_type_none.rs
  crates/ruff_linter/src/rules/refurb/rules/mod.rs
  crates/ruff_linter/src/rules/refurb/rules/type_none_comparison.rs
  crates/ruff_linter/src/rules/refurb/snapshots/ruff_linter__rules__refurb__tests__FURB169_FURB169.py.snap
  ruff.schema.json
Labels: rule, preview

#8486 [`TRIO`] Add `TRIO115`: TrioZeroSleepCall
  crates/ruff_linter/resources/test/fixtures/flake8_trio/TRIO115.py
  crates/ruff_linter/src/checkers/ast/analyze/expression.rs
  crates/ruff_linter/src/codes.rs
  crates/ruff_linter/src/rules/flake8_trio/mod.rs
  crates/ruff_linter/src/rules/flake8_trio/rules/mod.rs
  crates/ruff_linter/src/rules/flake8_trio/rules/zero_sleep_call.rs
  crates/ruff_linter/src/rules/flake8_trio/snapshots/ruff_linter__rules__flake8_trio__tests__TRIO115_TRIO115.py.snap
  ruff.schema.json
Labels: rule

#8491 Flag all comparisons against builtin types in E721
  crates/ruff_linter/resources/test/fixtures/pycodestyle/E721.py
  crates/ruff_linter/src/rules/pycodestyle/rules/type_comparison.rs
  crates/ruff_linter/src/rules/pycodestyle/snapshots/ruff_linter__rules__pycodestyle__tests__E721_E721.py.snap
  crates/ruff_linter/src/rules/pycodestyle/snapshots/ruff_linter__rules__pycodestyle__tests__preview__E721_E721.py.snap
Labels: rule

#8502 Fix tab configuration docs
  docs/configuration.md
Labels: documentation

#8506 Fix typo in example
  crates/ruff_linter/src/rules/ruff/rules/quadratic_list_summation.rs
Labels: documentation

#8513 Recommend `project.requires-python` over `target-version`
  crates/ruff_workspace/src/options.rs
  ruff.schema.json
Labels: documentation

#8517 Add dedicated method to find typed binding
  crates/ruff_linter/resources/test/fixtures/refurb/FURB131.py
  crates/ruff_linter/src/rules/perflint/rules/manual_dict_comprehension.rs
  crates/ruff_linter/src/rules/perflint/rules/manual_list_comprehension.rs
  crates/ruff_linter/src/rules/perflint/rules/manual_list_copy.rs
  crates/ruff_linter/src/rules/refurb/rules/check_and_remove_from_set.rs
  crates/ruff_linter/src/rules/refurb/rules/delete_full_slice.rs
  crates/ruff_linter/src/rules/refurb/rules/repeated_append.rs
  crates/ruff_linter/src/rules/refurb/rules/unnecessary_enumerate.rs
  crates/ruff_linter/src/rules/refurb/snapshots/ruff_linter__rules__refurb__tests__FURB131_FURB131.py.snap
  crates/ruff_python_semantic/src/model.rs
Labels: internal

#8512 docs: Add missing toml config tabs
  docs/faq.md
Labels: documentation

#8532 Avoid raising `TRIO115` violations for `trio.sleep(...)` calls with non-number values
  crates/ruff_linter/resources/test/fixtures/flake8_trio/TRIO115.py
  crates/ruff_linter/src/rules/flake8_trio/rules/zero_sleep_call.rs
  crates/ruff_linter/src/rules/flake8_trio/snapshots/ruff_linter__rules__flake8_trio__tests__TRIO115_TRIO115.py.snap
Labels: bug

#8501 Add singleton escape hatch to B008 documentation
  crates/ruff_linter/src/rules/flake8_bugbear/rules/function_call_in_argument_default.rs
  crates/ruff_linter/src/rules/flake8_bugbear/snapshots/ruff_linter__rules__flake8_bugbear__tests__B008_B006_B008.py.snap
  crates/ruff_linter/src/rules/flake8_bugbear/snapshots/ruff_linter__rules__flake8_bugbear__tests__extend_immutable_calls_arg_default.snap
Labels: documentation

#8524 Reject more syntactically invalid Python programs
  crates/ruff_linter/src/rules/eradicate/detection.rs
  crates/ruff_python_formatter/resources/test/fixtures/ruff/expression/yield.py
  crates/ruff_python_formatter/tests/snapshots/format@expression__yield.py.snap
  crates/ruff_python_parser/src/invalid.rs
  crates/ruff_python_parser/src/lexer.rs
  crates/ruff_python_parser/src/lib.rs
  crates/ruff_python_parser/src/python.lalrpop
  crates/ruff_python_parser/src/python.rs
  crates/ruff_python_parser/src/snapshots/ruff_python_parser__invalid__tests__ok_assignment_expr.snap
  crates/ruff_python_parser/src/snapshots/ruff_python_parser__invalid__tests__ok_attribute_normal.snap
  crates/ruff_python_parser/src/snapshots/ruff_python_parser__invalid__tests__ok_attribute_weird.snap
  crates/ruff_python_parser/src/snapshots/ruff_python_parser__invalid__tests__ok_ipy_escape_command.snap
  crates/ruff_python_parser/src/snapshots/ruff_python_parser__invalid__tests__ok_list.snap
  crates/ruff_python_parser/src/snapshots/ruff_python_parser__invalid__tests__ok_name.snap
  crates/ruff_python_parser/src/snapshots/ruff_python_parser__invalid__tests__ok_slice_normal.snap
  crates/ruff_python_parser/src/snapshots/ruff_python_parser__invalid__tests__ok_slice_weird.snap
  crates/ruff_python_parser/src/snapshots/ruff_python_parser__invalid__tests__ok_starred.snap
  crates/ruff_python_parser/src/snapshots/ruff_python_parser__invalid__tests__ok_subscript_normal.snap
  crates/ruff_python_parser/src/snapshots/ruff_python_parser__invalid__tests__ok_subscript_weird.snap
  crates/ruff_python_parser/src/snapshots/ruff_python_parser__invalid__tests__ok_tuple.snap
Labels: bug

#8538 Allow RUFF_NO_CACHE environment variable (like RUFF_CACHE_DIR)
  crates/ruff_cli/src/args.rs
  docs/configuration.md
Labels: cli

#8545 Update pre-commit documentation
  README.md
  docs/integrations.md
  docs/tutorial.md
Labels: documentation

#8533 [`flake8-bandit`] Implement `mako-templates` (`S702`)
  crates/ruff_linter/resources/test/fixtures/flake8_bandit/S702.py
  crates/ruff_linter/src/checkers/ast/analyze/expression.rs
  crates/ruff_linter/src/codes.rs
  crates/ruff_linter/src/rules/flake8_bandit/mod.rs
  crates/ruff_linter/src/rules/flake8_bandit/rules/mako_templates.rs
  crates/ruff_linter/src/rules/flake8_bandit/rules/mod.rs
  crates/ruff_linter/src/rules/flake8_bandit/snapshots/ruff_linter__rules__flake8_bandit__tests__S702_S702.py.snap
  ruff.schema.json
Labels: rule

#8548 Improve detail link contrast in dark mode
  docs/stylesheets/extra.css
Labels: documentation

#8550 Only flag flake8-trio rule when trio is present
  crates/ruff_linter/resources/test/fixtures/flake8_trio/TRIO109.py
  crates/ruff_linter/src/rules/flake8_trio/rules/async_function_with_timeout.rs
  crates/ruff_linter/src/rules/flake8_trio/snapshots/ruff_linter__rules__flake8_trio__tests__TRIO109_TRIO109.py.snap
  crates/ruff_python_semantic/src/model.rs
Labels: bug

#8373 Add hidden `--extension` to override inference of source type from file extension
  crates/ruff_cli/src/args.rs
  crates/ruff_cli/src/commands/check.rs
  crates/ruff_cli/src/diagnostics.rs
  crates/ruff_cli/tests/integration_test.rs
  crates/ruff_linter/src/settings/mod.rs
  crates/ruff_linter/src/settings/types.rs
  crates/ruff_workspace/src/configuration.rs
Labels: cli

#8562 Doc: Fix link to isort `known-first-party`
  docs/faq.md
Labels: documentation

#8558 Add missing config tabs
  docs/configuration.md
Labels: documentation

#8494 Avoid `FURB113` autofix if comments are present
  crates/ruff_linter/resources/test/fixtures/refurb/FURB113.py
  crates/ruff_linter/src/rules/refurb/rules/repeated_append.rs
  crates/ruff_linter/src/rules/refurb/snapshots/ruff_linter__rules__refurb__tests__FURB113_FURB113.py.snap
Labels: bug

#8574 Avoid inserting trailing commas within f-strings
  crates/ruff_linter/resources/test/fixtures/flake8_commas/COM81.py
  crates/ruff_linter/src/rules/flake8_commas/rules/trailing_commas.rs
  crates/ruff_linter/src/rules/flake8_commas/snapshots/ruff_linter__rules__flake8_commas__tests__COM81.py.snap
Labels: bug

#8575 Fix permalink to convention setting
  docs/faq.md
Labels: documentation

#7746 Slice source code instead of generating it for `EM` fixes
  crates/ruff_linter/resources/test/fixtures/flake8_errmsg/EM.py
  crates/ruff_linter/src/rules/flake8_errmsg/rules/string_in_exception.rs
  crates/ruff_linter/src/rules/flake8_errmsg/snapshots/ruff_linter__rules__flake8_errmsg__tests__custom.snap
  crates/ruff_linter/src/rules/flake8_errmsg/snapshots/ruff_linter__rules__flake8_errmsg__tests__defaults.snap
Labels: bug

#8595 Make unpacked assignment a flag rather than a `BindingKind`
  crates/ruff_linter/src/checkers/ast/mod.rs
  crates/ruff_linter/src/renamer.rs
  crates/ruff_linter/src/rules/pandas_vet/helpers.rs
  crates/ruff_linter/src/rules/pyflakes/rules/unused_variable.rs
  crates/ruff_linter/src/rules/pylint/rules/non_ascii_name.rs
  crates/ruff_python_semantic/src/binding.rs
Labels: internal

#8596 Write unchanged, excluded files to stdout when read via stdin
  crates/ruff_cli/src/commands/check_stdin.rs
  crates/ruff_cli/src/commands/format_stdin.rs
  crates/ruff_cli/src/stdin.rs
  crates/ruff_cli/tests/format.rs
Labels: bug, cli

#8582 Consider the new f-string tokens for `flake8-commas`
  crates/ruff_linter/resources/test/fixtures/flake8_commas/COM81.py
  crates/ruff_linter/src/checkers/tokens.rs
  crates/ruff_linter/src/rules/flake8_commas/rules/trailing_commas.rs
  crates/ruff_linter/src/rules/flake8_commas/snapshots/ruff_linter__rules__flake8_commas__tests__COM81.py.snap
Labels: bug

#8597 Document context manager breaking deviation vs. Black
  docs/formatter/black.md
Labels: documentation

#8590 Preserve trailing semicolon for Notebooks
  crates/ruff_cli/resources/test/fixtures/trailing_semicolon.ipynb
  crates/ruff_cli/tests/format.rs
  crates/ruff_python_formatter/src/comments/format.rs
  crates/ruff_python_formatter/src/context.rs
  crates/ruff_python_formatter/src/expression/mod.rs
  crates/ruff_python_formatter/src/expression/parentheses.rs
  crates/ruff_python_formatter/src/statement/stmt_ann_assign.rs
  crates/ruff_python_formatter/src/statement/stmt_assign.rs
  crates/ruff_python_formatter/src/statement/stmt_aug_assign.rs
  crates/ruff_python_formatter/src/statement/stmt_expr.rs
  crates/ruff_python_formatter/src/statement/suite.rs
Labels: formatter

#8586 Allow overriding pydocstyle convention rules
  crates/ruff_cli/tests/integration_test.rs
  crates/ruff_workspace/src/configuration.rs
  crates/ruff_workspace/src/options.rs
  ruff.schema.json
Labels: bug, docstring

#8607 Add check for is comparison with mutable initialisers to rule F632
  crates/ruff_linter/resources/test/fixtures/pycodestyle/constant_literals.py
  crates/ruff_linter/src/rules/pycodestyle/mod.rs
  crates/ruff_linter/src/rules/pycodestyle/snapshots/ruff_linter__rules__pycodestyle__tests__constant_literals.snap
  crates/ruff_linter/src/rules/pycodestyle/snapshots/ruff_linter__rules__pycodestyle__tests__preview__F632_constant_literals.py.snap
  crates/ruff_linter/src/rules/pyflakes/rules/invalid_literal_comparisons.rs
  crates/ruff_python_ast/src/helpers.rs
Labels: rule, preview

#8611 Fix docs typo for `ruff format` preview configuration
  docs/preview.md
Labels: documentation

#8621 Implement autofix for `unnecessary-lambda` (`PLW0108`)
  crates/ruff_linter/src/rules/pylint/rules/unnecessary_lambda.rs
  crates/ruff_linter/src/rules/pylint/snapshots/ruff_linter__rules__pylint__tests__PLW0108_unnecessary_lambda.py.snap
Labels: autofix

#8622 Implement autofix for `multiple-spaces-after-keyword` and `multiple-spaces-before-keyword`
  crates/ruff_linter/src/rules/pycodestyle/rules/logical_lines/whitespace_around_keywords.rs
  crates/ruff_linter/src/rules/pycodestyle/snapshots/ruff_linter__rules__pycodestyle__tests__E271_E27.py.snap
  crates/ruff_linter/src/rules/pycodestyle/snapshots/ruff_linter__rules__pycodestyle__tests__E272_E27.py.snap
Labels: autofix

#8623 Implement autofix for `multiple-spaces-after-operator` and `multiple-spaces-before-operator`
  crates/ruff_linter/src/rules/pycodestyle/rules/logical_lines/space_around_operator.rs
  crates/ruff_linter/src/rules/pycodestyle/snapshots/ruff_linter__rules__pycodestyle__tests__E221_E22.py.snap
  crates/ruff_linter/src/rules/pycodestyle/snapshots/ruff_linter__rules__pycodestyle__tests__E222_E22.py.snap
  crates/ruff_linter/src/rules/pycodestyle/snapshots/ruff_linter__rules__pycodestyle__tests__E241_E24.py.snap
Labels: autofix

#8628 Improve docs for RUF001, RUF002 and RUF003
  crates/ruff_linter/src/rules/ruff/rules/ambiguous_unicode_character.rs
Labels: documentation

#8625 Remove unecessary commentary in PD901 message
  crates/ruff_linter/src/rules/pandas_vet/rules/assignment_to_df.rs
  crates/ruff_linter/src/rules/pandas_vet/snapshots/ruff_linter__rules__pandas_vet__tests__PD901_fail_df_var.snap
Labels: documentation

#7501 Fix FBT001 false negative with unions and optional
  crates/ruff_linter/resources/test/fixtures/flake8_boolean_trap/FBT.py
  crates/ruff_linter/src/rules/flake8_boolean_trap/mod.rs
  crates/ruff_linter/src/rules/flake8_boolean_trap/rules/boolean_type_hint_positional_argument.rs
  crates/ruff_linter/src/rules/flake8_boolean_trap/snapshots/ruff_linter__rules__flake8_boolean_trap__tests__preview__FBT001_FBT.py.snap
Labels: preview

#8634 Omit unrolled augmented assignments in `PIE794`
  crates/ruff_linter/resources/test/fixtures/flake8_pie/PIE794.py
  crates/ruff_linter/src/rules/flake8_pie/rules/duplicate_class_field_definition.rs
  crates/ruff_linter/src/rules/flake8_pie/snapshots/ruff_linter__rules__flake8_pie__tests__PIE794_PIE794.py.snap
Labels: bug

#8637 Use function range for `no-self-use`
  crates/ruff_linter/src/rules/pylint/rules/no_self_use.rs
  crates/ruff_linter/src/rules/pylint/snapshots/ruff_linter__rules__pylint__tests__PLR6301_no_self_use.py.snap
Labels: bug

#8636 Redirect from rule codes to rule pages in docs
  docs/requirements-insiders.txt
  docs/requirements.txt
  mkdocs.insiders.yml
  mkdocs.template.yml
  scripts/generate_mkdocs.py
Labels: documentation

#8638 Document conventions in the FAQ
  crates/ruff_workspace/src/options.rs
  docs/faq.md
  ruff.schema.json
Labels: documentation

#8639 Avoid recommending Self usages in metaclasses
  crates/ruff_linter/resources/test/fixtures/flake8_pyi/PYI034.py
  crates/ruff_linter/resources/test/fixtures/flake8_pyi/PYI034.pyi
  crates/ruff_linter/src/rules/flake8_pyi/rules/non_self_return_type.rs
  crates/ruff_linter/src/rules/flake8_pyi/snapshots/ruff_linter__rules__flake8_pyi__tests__PYI034_PYI034.py.snap
  crates/ruff_linter/src/rules/flake8_pyi/snapshots/ruff_linter__rules__flake8_pyi__tests__PYI034_PYI034.pyi.snap
Labels: bug

#8656 ruff_python_formatter: copy and inline shared traits
  crates/ruff_python_formatter/src/lib.rs
  crates/ruff_python_formatter/src/shared_traits.rs
Labels: internal

#8654 Allow whitespace around colon in slices for `whitespace-before-punctuation` (`E203`)
  crates/ruff_linter/resources/test/fixtures/pycodestyle/E20.py
  crates/ruff_linter/src/rules/pycodestyle/rules/logical_lines/extraneous_whitespace.rs
  crates/ruff_linter/src/rules/pycodestyle/snapshots/ruff_linter__rules__pycodestyle__tests__E201_E20.py.snap
  crates/ruff_linter/src/rules/pycodestyle/snapshots/ruff_linter__rules__pycodestyle__tests__E202_E20.py.snap
  crates/ruff_linter/src/rules/pycodestyle/snapshots/ruff_linter__rules__pycodestyle__tests__E203_E20.py.snap
Labels: bug

#8608 Generalize PIE807 to handle dict literals
  crates/ruff_linter/resources/test/fixtures/flake8_pie/PIE807.py
  crates/ruff_linter/src/checkers/ast/analyze/deferred_lambdas.rs
  crates/ruff_linter/src/codes.rs
  crates/ruff_linter/src/rules/flake8_pie/mod.rs
  crates/ruff_linter/src/rules/flake8_pie/rules/mod.rs
  crates/ruff_linter/src/rules/flake8_pie/rules/reimplemented_container_builtin.rs
  crates/ruff_linter/src/rules/flake8_pie/rules/reimplemented_list_builtin.rs
  crates/ruff_linter/src/rules/flake8_pie/snapshots/ruff_linter__rules__flake8_pie__tests__PIE807_PIE807.py.snap
  crates/ruff_linter/src/rules/flake8_pie/snapshots/ruff_linter__rules__flake8_pie__tests__preview__PIE807_PIE807.py.snap
Labels: rule

#8658 Fix lingering generated reference for MkDocs
  .github/workflows/ci.yaml
Labels: internal

#8659 Treat `class C: ...` and `class C(): ...` equivalently
  crates/ruff_python_ast/src/comparable.rs
  crates/ruff_python_formatter/tests/normalizer.rs
Labels: internal

#8660 Use AST transformer for `relocate`
  crates/ruff_python_ast/src/relocate.rs
Labels: internal

#8630 Add new rule to check for useless quote escapes
  crates/ruff_linter/resources/test/fixtures/flake8_quotes/doubles_escaped_unnecessary.py
  crates/ruff_linter/resources/test/fixtures/flake8_quotes/singles_escaped_unnecessary.py
  crates/ruff_linter/src/checkers/tokens.rs
  crates/ruff_linter/src/codes.rs
  crates/ruff_linter/src/rules/flake8_quotes/mod.rs
  crates/ruff_linter/src/rules/flake8_quotes/rules/avoidable_escaped_quote.rs
  crates/ruff_linter/src/rules/flake8_quotes/snapshots/ruff_linter__rules__flake8_quotes__tests__require_doubles_over_singles_escaped_unnecessary.py.snap
  crates/ruff_linter/src/rules/flake8_quotes/snapshots/ruff_linter__rules__flake8_quotes__tests__require_singles_over_doubles_escaped_unnecessary.py.snap
  ruff.schema.json
  scripts/check_docs_formatted.py
Labels: rule

#8643 Add autotyping-like return type inference for annotation rules
  crates/ruff_linter/resources/test/fixtures/flake8_annotations/auto_return_type.py
  crates/ruff_linter/src/rules/flake8_annotations/helpers.rs
  crates/ruff_linter/src/rules/flake8_annotations/mod.rs
  crates/ruff_linter/src/rules/flake8_annotations/rules/definition.rs
  crates/ruff_linter/src/rules/flake8_annotations/snapshots/ruff_linter__rules__flake8_annotations__tests__allow_overload.snap
  crates/ruff_linter/src/rules/flake8_annotations/snapshots/ruff_linter__rules__flake8_annotations__tests__auto_return_type.snap
  crates/ruff_linter/src/rules/flake8_annotations/snapshots/ruff_linter__rules__flake8_annotations__tests__defaults.snap
  crates/ruff_linter/src/rules/flake8_annotations/snapshots/ruff_linter__rules__flake8_annotations__tests__ignore_fully_untyped.snap
  crates/ruff_linter/src/rules/flake8_annotations/snapshots/ruff_linter__rules__flake8_annotations__tests__mypy_init_return.snap
  crates/ruff_linter/src/rules/flake8_annotations/snapshots/ruff_linter__rules__flake8_annotations__tests__simple_magic_methods.snap
  crates/ruff_linter/src/rules/flake8_annotations/snapshots/ruff_linter__rules__flake8_annotations__tests__suppress_none_returning.snap
  crates/ruff_linter/src/rules/pylint/rules/invalid_str_return.rs
  crates/ruff_linter/src/rules/pylint/rules/too_many_return_statements.rs
  crates/ruff_linter/src/rules/pylint/rules/useless_return.rs
  crates/ruff_linter/src/rules/pyupgrade/rules/use_pep604_annotation.rs
  crates/ruff_linter/src/rules/pyupgrade/rules/use_pep604_isinstance.rs
  crates/ruff_python_ast/src/helpers.rs
  crates/ruff_python_semantic/src/analyze/type_inference.rs
Labels: autofix

#8670 Remove repeated and erroneous scoped settings headers in docs
  crates/ruff_dev/src/generate_options.rs
  crates/ruff_macros/src/config.rs
  crates/ruff_workspace/src/options.rs
  crates/ruff_workspace/src/options_base.rs
Labels: bug, documentation

#8675 F-strings doesn't contain bytes literal for `PLW0129`
  crates/ruff_linter/src/rules/pylint/rules/assert_on_string_literal.rs
Labels: bug

#8657 isort: Support disabling sections with ``no-sections = true``
  crates/ruff_linter/resources/test/fixtures/isort/no_sections.py
  crates/ruff_linter/src/rules/flake8_type_checking/rules/typing_only_runtime_import.rs
  crates/ruff_linter/src/rules/isort/categorize.rs
  crates/ruff_linter/src/rules/isort/mod.rs
  crates/ruff_linter/src/rules/isort/settings.rs
  crates/ruff_linter/src/rules/isort/snapshots/ruff_linter__rules__isort__tests__no_sections_no_sections.py.snap
  crates/ruff_workspace/src/options.rs
  ruff.schema.json
Labels: isort

#8664 Implement FURB136
  crates/ruff_linter/resources/test/fixtures/refurb/FURB136.py
  crates/ruff_linter/src/checkers/ast/analyze/expression.rs
  crates/ruff_linter/src/codes.rs
  crates/ruff_linter/src/rules/refurb/mod.rs
  crates/ruff_linter/src/rules/refurb/rules/if_expr_min_max.rs
  crates/ruff_linter/src/rules/refurb/rules/mod.rs
  crates/ruff_linter/src/rules/refurb/snapshots/ruff_linter__rules__refurb__tests__FURB136_FURB136.py.snap
  crates/ruff_workspace/src/configuration.rs
  ruff.schema.json
Labels: rule

#8668 Add autofix for PIE800
  crates/ruff_linter/resources/test/fixtures/flake8_pie/PIE800.py
  crates/ruff_linter/src/checkers/ast/analyze/expression.rs
  crates/ruff_linter/src/rules/flake8_pie/mod.rs
  crates/ruff_linter/src/rules/flake8_pie/rules/unnecessary_spread.rs
  crates/ruff_linter/src/rules/flake8_pie/snapshots/ruff_linter__rules__flake8_pie__tests__PIE800_PIE800.py.snap
  crates/ruff_linter/src/rules/flake8_pie/snapshots/ruff_linter__rules__flake8_pie__tests__preview__PIE800_PIE800.py.snap
Labels: autofix, preview

#8707 Treat display as a builtin in IPython
  crates/ruff_linter/resources/test/fixtures/pyflakes/F821_21.py
  crates/ruff_linter/resources/test/fixtures/pyflakes/F821_22.ipynb
  crates/ruff_linter/src/checkers/ast/mod.rs
  crates/ruff_linter/src/linter.rs
  crates/ruff_linter/src/rules/flake8_builtins/helpers.rs
  crates/ruff_linter/src/rules/flake8_builtins/rules/builtin_argument_shadowing.rs
  crates/ruff_linter/src/rules/flake8_builtins/rules/builtin_attribute_shadowing.rs
  crates/ruff_linter/src/rules/flake8_builtins/rules/builtin_variable_shadowing.rs
  crates/ruff_linter/src/rules/pyflakes/mod.rs
  crates/ruff_linter/src/rules/pyflakes/snapshots/ruff_linter__rules__pyflakes__tests__F821_F821_21.py.snap
  crates/ruff_linter/src/rules/pyflakes/snapshots/ruff_linter__rules__pyflakes__tests__F821_F821_22.ipynb.snap
  crates/ruff_linter/src/test.rs
  crates/ruff_python_stdlib/src/builtins.rs
Labels: bug

#8709 Run unicode prefix rule over tokens
  crates/ruff_linter/resources/test/fixtures/pyupgrade/UP025.py
  crates/ruff_linter/src/checkers/ast/analyze/expression.rs
  crates/ruff_linter/src/checkers/tokens.rs
  crates/ruff_linter/src/registry.rs
  crates/ruff_linter/src/rules/pyupgrade/rules/unicode_kind_prefix.rs
  crates/ruff_linter/src/rules/pyupgrade/snapshots/ruff_linter__rules__pyupgrade__tests__UP025.py.snap
Labels: bug

#8711 Add fix for `future-required-type-annotation`
  crates/ruff_linter/src/importer/mod.rs
  crates/ruff_linter/src/rules/flake8_future_annotations/rules/future_required_type_annotation.rs
  crates/ruff_linter/src/rules/flake8_future_annotations/snapshots/ruff_linter__rules__flake8_future_annotations__tests__fa102_no_future_import_uses_lowercase.py.snap
  crates/ruff_linter/src/rules/flake8_future_annotations/snapshots/ruff_linter__rules__flake8_future_annotations__tests__fa102_no_future_import_uses_union.py.snap
  crates/ruff_linter/src/rules/flake8_future_annotations/snapshots/ruff_linter__rules__flake8_future_annotations__tests__fa102_no_future_import_uses_union_inner.py.snap
  crates/ruff_linter/src/rules/refurb/rules/repeated_append.rs
  crates/ruff_python_semantic/src/definition.rs
Labels: autofix

#8712 Trim trailing empty strings when converting to f-strings
  crates/ruff_linter/resources/test/fixtures/pyupgrade/UP032_0.py
  crates/ruff_linter/src/rules/pyupgrade/rules/f_strings.rs
  crates/ruff_linter/src/rules/pyupgrade/snapshots/ruff_linter__rules__pyupgrade__tests__UP032_0.py.snap
Labels: bug

#8714 Improve N803 example
  crates/ruff_linter/src/rules/pep8_naming/rules/invalid_argument_name.rs
Labels: documentation

#8726 Remove `pyproject.toml` from fixtures directory
  crates/ruff_linter/resources/test/fixtures/README.md
  crates/ruff_linter/resources/test/fixtures/pyproject.toml
  crates/ruff_workspace/src/pyproject.rs
Labels: internal

#8697 Update UP032 to unescape curly braces in literal parts of converted strings
  crates/ruff_linter/resources/test/fixtures/pyupgrade/UP032_0.py
  crates/ruff_linter/src/rules/pyupgrade/helpers.rs
  crates/ruff_linter/src/rules/pyupgrade/rules/f_strings.rs
  crates/ruff_linter/src/rules/pyupgrade/snapshots/ruff_linter__rules__pyupgrade__tests__UP032_0.py.snap
Labels: bug

#8710 Avoid missing namespace violations in scripts with shebangs
  crates/ruff_linter/resources/test/fixtures/flake8_no_pep420/test_pass_shebang/example.py
  crates/ruff_linter/src/checkers/filesystem.rs
  crates/ruff_linter/src/checkers/tokens.rs
  crates/ruff_linter/src/linter.rs
  crates/ruff_linter/src/rules/flake8_executable/rules/mod.rs
  crates/ruff_linter/src/rules/flake8_no_pep420/mod.rs
  crates/ruff_linter/src/rules/flake8_no_pep420/rules/implicit_namespace_package.rs
  crates/ruff_linter/src/rules/flake8_no_pep420/snapshots/ruff_linter__rules__flake8_no_pep420__tests__test_fail_shebang.snap
  crates/ruff_linter/src/rules/flake8_no_pep420/snapshots/ruff_linter__rules__flake8_no_pep420__tests__test_pass_shebang.snap
Labels: bug

#8730 Avoid syntax error via importing trio.lowlevel
  crates/ruff_linter/resources/test/fixtures/flake8_trio/TRIO115.py
  crates/ruff_linter/src/rules/flake8_trio/rules/zero_sleep_call.rs
  crates/ruff_linter/src/rules/flake8_trio/snapshots/ruff_linter__rules__flake8_trio__tests__TRIO115_TRIO115.py.snap
Labels: bug

#8729 Improve debug printing for resolving origin of config settings
  crates/ruff_cli/src/resolve.rs
Labels: cli

#8735 Fix typo
  crates/ruff_linter/src/rules/pylint/rules/too_many_public_methods.rs
Labels: documentation

#8699 Update `D208` to preserve indentation offsets when fixing overindented lines
  crates/ruff_linter/resources/test/fixtures/pydocstyle/D.py
  crates/ruff_linter/src/rules/pydocstyle/rules/indent.rs
  crates/ruff_linter/src/rules/pydocstyle/snapshots/ruff_linter__rules__pydocstyle__tests__D208_D.py.snap
  crates/ruff_linter/src/rules/pydocstyle/snapshots/ruff_linter__rules__pydocstyle__tests__D213_D.py.snap
  crates/ruff_linter/src/rules/pydocstyle/snapshots/ruff_linter__rules__pydocstyle__tests__D400_D.py.snap
  crates/ruff_linter/src/rules/pydocstyle/snapshots/ruff_linter__rules__pydocstyle__tests__D415_D.py.snap
  crates/ruff_linter/src/rules/pydocstyle/snapshots/ruff_linter__rules__pydocstyle__tests__preview__D300_D.py.snap
Labels: rule, docstring

#8740 Add River in "Who's Using Ruff?" section
  README.md
Labels: internal

#8676 Fix instability with await fluent style
  crates/ruff_python_formatter/resources/test/fixtures/ruff/expression/await.py
  crates/ruff_python_formatter/src/expression/expr_await.rs
  crates/ruff_python_formatter/src/expression/parentheses.rs
  crates/ruff_python_formatter/tests/snapshots/black_compatibility@simple_cases__remove_await_parens.py.snap
  crates/ruff_python_formatter/tests/snapshots/format@expression__await.py.snap
Labels: formatter

#8742 Remove erroneous bad-dunder-name reference
  crates/ruff_linter/src/rules/pylint/rules/bad_dunder_method_name.rs
  crates/ruff_linter/src/rules/pylint/snapshots/ruff_linter__rules__pylint__tests__PLW3201_bad_dunder_method_name.py.snap
Labels: bug

#8743 Remove incorrect deprecation label for stdout and stderr
  crates/ruff_linter/src/rules/pyupgrade/rules/replace_stdout_stderr.rs
  crates/ruff_linter/src/rules/pyupgrade/snapshots/ruff_linter__rules__pyupgrade__tests__UP022.py.snap
Labels: bug

#8727 [`refurb`] Implement `math-constant` (`FURB152`)
  crates/ruff_linter/resources/test/fixtures/refurb/FURB152.py
  crates/ruff_linter/src/checkers/ast/analyze/expression.rs
  crates/ruff_linter/src/codes.rs
  crates/ruff_linter/src/rules/refurb/mod.rs
  crates/ruff_linter/src/rules/refurb/rules/math_constant.rs
  crates/ruff_linter/src/rules/refurb/rules/mod.rs
  crates/ruff_linter/src/rules/refurb/snapshots/ruff_linter__rules__refurb__tests__FURB152_FURB152.py.snap
  crates/ruff_workspace/src/configuration.rs
  ruff.schema.json
Labels: rule

#8744 Bump version to v0.1.6
  CHANGELOG.md
  Cargo.lock
  README.md
  crates/flake8_to_ruff/Cargo.toml
  crates/ruff_cli/Cargo.toml
  crates/ruff_linter/Cargo.toml
  crates/ruff_shrinking/Cargo.toml
  docs/integrations.md
  pyproject.toml
  scripts/benchmarks/pyproject.toml
Labels: release

#8706 Add Implementation for Pylint E1132: Repeated Keyword
  crates/ruff_linter/resources/test/fixtures/pylint/repeated_keyword_argument.py
  crates/ruff_linter/src/checkers/ast/analyze/expression.rs
  crates/ruff_linter/src/codes.rs
  crates/ruff_linter/src/rules/pylint/mod.rs
  crates/ruff_linter/src/rules/pylint/rules/mod.rs
  crates/ruff_linter/src/rules/pylint/rules/repeated_keyword_argument.rs
  crates/ruff_linter/src/rules/pylint/snapshots/ruff_linter__rules__pylint__tests__PLE1132_repeated_keyword_argument.py.snap
  ruff.schema.json
Labels: rule, preview

#8763 Use pinned toolchain version in Dockerfile
  Dockerfile
Labels: internal

#8766 [`flake8-pyi`] Improve motivation for `custom-type-var-return-type` (`PYI019`)
  crates/ruff_linter/src/rules/flake8_pyi/rules/custom_type_var_return_type.rs
Labels: documentation

#8767 [`flake8-pyi`] Respect local enum subclasses in `simple-defaults` (`PYI052`)
  crates/ruff_linter/resources/test/fixtures/flake8_pyi/PYI052.py
  crates/ruff_linter/resources/test/fixtures/flake8_pyi/PYI052.pyi
  crates/ruff_linter/src/rules/flake8_pyi/rules/simple_defaults.rs
  crates/ruff_linter/src/rules/flake8_pyi/snapshots/ruff_linter__rules__flake8_pyi__tests__PYI052_PYI052.pyi.snap
Labels: bug

#8768 Respect local subclasses in `flake8-type-checking`
  crates/ruff_linter/resources/test/fixtures/flake8_type_checking/runtime_evaluated_base_classes_5.py
  crates/ruff_linter/src/rules/flake8_pyi/rules/simple_defaults.rs
  crates/ruff_linter/src/rules/flake8_type_checking/helpers.rs
  crates/ruff_linter/src/rules/flake8_type_checking/mod.rs
  crates/ruff_linter/src/rules/flake8_type_checking/snapshots/ruff_linter__rules__flake8_type_checking__tests__typing-only-third-party-import_runtime_evaluated_base_classes_5.py.snap
Labels: bug

#8769 Retain extra ellipses in protocols and abstract methods
  crates/ruff_linter/resources/test/fixtures/flake8_pie/PIE790.py
  crates/ruff_linter/src/rules/flake8_pie/rules/unnecessary_placeholder.rs
  crates/ruff_linter/src/rules/flake8_pie/snapshots/ruff_linter__rules__flake8_pie__tests__PIE790_PIE790.py.snap
  crates/ruff_linter/src/rules/flake8_pie/snapshots/ruff_linter__rules__flake8_pie__tests__preview__PIE790_PIE790.py.snap
Labels: bug

#8772 Avoid repeated triggers in nested `tryceratops` diagnostics
  crates/ruff_linter/resources/test/fixtures/tryceratops/TRY400.py
  crates/ruff_linter/resources/test/fixtures/tryceratops/TRY401.py
  crates/ruff_linter/src/rules/tryceratops/helpers.rs
  crates/ruff_linter/src/rules/tryceratops/rules/error_instead_of_exception.rs
  crates/ruff_linter/src/rules/tryceratops/rules/verbose_log_message.rs
  crates/ruff_linter/src/rules/tryceratops/snapshots/ruff_linter__rules__tryceratops__tests__error-instead-of-exception_TRY400.py.snap
  crates/ruff_linter/src/rules/tryceratops/snapshots/ruff_linter__rules__tryceratops__tests__verbose-log-message_TRY401.py.snap
Labels: bug

#8651 [`flake8-bandit`] Implement `django-raw-sql` (`S611`)
  crates/ruff_linter/resources/test/fixtures/flake8_bandit/S611.py
  crates/ruff_linter/src/checkers/ast/analyze/expression.rs
  crates/ruff_linter/src/codes.rs
  crates/ruff_linter/src/rules/flake8_bandit/mod.rs
  crates/ruff_linter/src/rules/flake8_bandit/rules/django_raw_sql.rs
  crates/ruff_linter/src/rules/flake8_bandit/rules/mod.rs
  crates/ruff_linter/src/rules/flake8_bandit/snapshots/ruff_linter__rules__flake8_bandit__tests__S611_S611.py.snap
  ruff.schema.json
Labels: rule

#8775 Ruff ecosystem: pass no-preview cli arg by default
  .github/workflows/ci.yaml
  python/ruff-ecosystem/ruff_ecosystem/projects.py
Labels: ci

#8793 Mark `pydantic_settings.BaseSettings` as having default copy semantics
  crates/ruff_linter/resources/test/fixtures/ruff/RUF012.py
  crates/ruff_linter/src/rules/ruff/rules/helpers.rs
Labels: bug

#8802 Update Arch Linux package URL in installation.md
  docs/installation.md
Labels: documentation

#8805 fix: mark `__main__` as first-party import
  crates/ruff_linter/resources/test/fixtures/isort/main_first_party.py
  crates/ruff_linter/src/rules/isort/categorize.rs
  crates/ruff_linter/src/rules/isort/mod.rs
  crates/ruff_linter/src/rules/isort/snapshots/ruff_linter__rules__isort__tests__sections_main_first_party.py.snap
Labels: bug

#8801 [`flake8-simplify`] Omit select context managers from `SIM117`
  crates/ruff_linter/resources/test/fixtures/flake8_simplify/SIM117.py
  crates/ruff_linter/src/rules/flake8_simplify/rules/ast_with.rs
  crates/ruff_linter/src/rules/flake8_simplify/snapshots/ruff_linter__rules__flake8_simplify__tests__SIM117_SIM117.py.snap
Labels: rule

#8806 Replace generated reference to MkDocs
  CONTRIBUTING.md
Labels: documentation

#8791 Update `ruff check` and `ruff format` to default to the current directory
  crates/ruff_cli/resources/test/fixtures/include-test/a.py
  crates/ruff_cli/resources/test/fixtures/include-test/b.py
  crates/ruff_cli/resources/test/fixtures/include-test/nested-project/e.py
  crates/ruff_cli/resources/test/fixtures/include-test/nested-project/pyproject.toml
  crates/ruff_cli/resources/test/fixtures/include-test/pyproject.toml
  crates/ruff_cli/resources/test/fixtures/include-test/subdirectory/c.py
  crates/ruff_cli/resources/test/fixtures/include-test/subdirectory/d.py
  crates/ruff_cli/src/args.rs
  crates/ruff_cli/src/commands/format.rs
  crates/ruff_cli/src/lib.rs
  crates/ruff_cli/tests/format.rs
  crates/ruff_cli/tests/integration_test.rs
  crates/ruff_cli/tests/resolve_files.rs
  docs/configuration.md
  docs/formatter.md
  docs/linter.md
Labels: cli

#8810 Respect dictionary unpacking in `NamedTuple` assignments
  crates/ruff_linter/resources/test/fixtures/pyflakes/F821_23.py
  crates/ruff_linter/src/checkers/ast/mod.rs
  crates/ruff_linter/src/rules/pyflakes/mod.rs
  crates/ruff_linter/src/rules/pyflakes/snapshots/ruff_linter__rules__pyflakes__tests__F821_F821_23.py.snap
Labels: bug

#8809 Avoid `PERF101` if there's an append in loop body
  crates/ruff_linter/resources/test/fixtures/perflint/PERF101.py
  crates/ruff_linter/src/checkers/ast/analyze/statement.rs
  crates/ruff_linter/src/rules/perflint/rules/unnecessary_list_cast.rs
  crates/ruff_linter/src/rules/perflint/snapshots/ruff_linter__rules__perflint__tests__PERF101_PERF101.py.snap
Labels: bug

#8663 isort: Add support for the ``from-first`` setting
  crates/ruff_linter/resources/test/fixtures/isort/from_first.py
  crates/ruff_linter/src/rules/isort/mod.rs
  crates/ruff_linter/src/rules/isort/order.rs
  crates/ruff_linter/src/rules/isort/settings.rs
  crates/ruff_linter/src/rules/isort/snapshots/ruff_linter__rules__isort__tests__from_first_from_first.py.snap
  crates/ruff_workspace/src/options.rs
  ruff.schema.json
Labels: isort

#8812 [`pylint`] Add `allow-dunder-method-names` setting for `bad-dunder-method-name` (`PLW3201`)
  crates/ruff_linter/resources/test/fixtures/pylint/bad_dunder_method_name.py
  crates/ruff_linter/src/rules/pylint/mod.rs
  crates/ruff_linter/src/rules/pylint/rules/bad_dunder_method_name.rs
  crates/ruff_linter/src/rules/pylint/settings.rs
  crates/ruff_workspace/src/options.rs
  ruff.schema.json
Labels: configuration

#8733 Factor out a builder to handle common integration test arguments
  crates/ruff_cli/tests/format.rs
  crates/ruff_cli/tests/integration_test.rs
Labels: internal

#8813 Move notebook cell logic in separate file
  crates/ruff_notebook/src/cell.rs
  crates/ruff_notebook/src/lib.rs
  crates/ruff_notebook/src/notebook.rs
Labels: internal

#8816 Avoid `D100` for Jupyter Notebooks
  crates/ruff_linter/resources/test/fixtures/pydocstyle/D100.ipynb
  crates/ruff_linter/src/rules/pydocstyle/mod.rs
  crates/ruff_linter/src/rules/pydocstyle/rules/not_missing.rs
  crates/ruff_linter/src/rules/pydocstyle/snapshots/ruff_linter__rules__pydocstyle__tests__D100_D100.ipynb.snap
Labels: rule

#8814 Add `CellOffsets` abstraction
  crates/ruff_linter/src/checkers/imports.rs
  crates/ruff_linter/src/linter.rs
  crates/ruff_linter/src/rules/isort/block.rs
  crates/ruff_notebook/src/cell.rs
  crates/ruff_notebook/src/lib.rs
  crates/ruff_notebook/src/notebook.rs
Labels: internal

#8815 Avoid `B015`,`B018` for last expression in a cell
  crates/ruff_linter/resources/test/fixtures/flake8_bugbear/B015.ipynb
  crates/ruff_linter/resources/test/fixtures/flake8_bugbear/B018.ipynb
  crates/ruff_linter/src/checkers/ast/mod.rs
  crates/ruff_linter/src/linter.rs
  crates/ruff_linter/src/rules/flake8_bugbear/helpers.rs
  crates/ruff_linter/src/rules/flake8_bugbear/mod.rs
  crates/ruff_linter/src/rules/flake8_bugbear/rules/useless_comparison.rs
  crates/ruff_linter/src/rules/flake8_bugbear/rules/useless_expression.rs
  crates/ruff_linter/src/rules/flake8_bugbear/snapshots/ruff_linter__rules__flake8_bugbear__tests__B015_B015.ipynb.snap
  crates/ruff_linter/src/rules/flake8_bugbear/snapshots/ruff_linter__rules__flake8_bugbear__tests__B018_B018.ipynb.snap
  crates/ruff_notebook/src/cell.rs
Labels: rule

#8821 Avoid `E703` for last expression in a cell
  crates/ruff_linter/resources/test/fixtures/pycodestyle/E703.ipynb
  crates/ruff_linter/src/checkers/tokens.rs
  crates/ruff_linter/src/linter.rs
  crates/ruff_linter/src/rules/pycodestyle/mod.rs
  crates/ruff_linter/src/rules/pycodestyle/rules/compound_statements.rs
  crates/ruff_linter/src/rules/pycodestyle/snapshots/ruff_linter__rules__pycodestyle__tests__E703_E703.ipynb.snap
Labels: rule

#8829 [flake8-bandit] Implement tarfile-unsafe-members (S202)
  crates/ruff_linter/resources/test/fixtures/flake8_bandit/S202.py
  crates/ruff_linter/src/checkers/ast/analyze/expression.rs
  crates/ruff_linter/src/codes.rs
  crates/ruff_linter/src/rules/flake8_bandit/mod.rs
  crates/ruff_linter/src/rules/flake8_bandit/rules/mod.rs
  crates/ruff_linter/src/rules/flake8_bandit/rules/tarfile_unsafe_members.rs
  crates/ruff_linter/src/rules/flake8_bandit/snapshots/ruff_linter__rules__flake8_bandit__tests__S202_S202.py.snap
  ruff.schema.json
Labels: rule

#8826 Explicit `as_str` (no deref), add no allocation methods
  crates/ruff_linter/src/checkers/ast/analyze/expression.rs
  crates/ruff_linter/src/checkers/ast/mod.rs
  crates/ruff_linter/src/rules/flake8_annotations/rules/definition.rs
  crates/ruff_linter/src/rules/flake8_bandit/rules/hardcoded_password_string.rs
  crates/ruff_linter/src/rules/flake8_bandit/rules/hardcoded_sql_expression.rs
  crates/ruff_linter/src/rules/flake8_bandit/rules/hardcoded_tmp_directory.rs
  crates/ruff_linter/src/rules/flake8_bandit/rules/suspicious_function_call.rs
  crates/ruff_linter/src/rules/flake8_bugbear/rules/getattr_with_constant.rs
  crates/ruff_linter/src/rules/flake8_bugbear/rules/setattr_with_constant.rs
  crates/ruff_linter/src/rules/flake8_datetimez/rules/call_datetime_strptime_without_zone.rs
  crates/ruff_linter/src/rules/flake8_logging_format/rules/logging_call.rs
  crates/ruff_linter/src/rules/flake8_pie/rules/unnecessary_dict_kwargs.rs
  crates/ruff_linter/src/rules/flake8_pytest_style/rules/parametrize.rs
  crates/ruff_linter/src/rules/flake8_simplify/rules/ast_expr.rs
  crates/ruff_linter/src/rules/pylint/helpers.rs
  crates/ruff_linter/src/rules/pylint/rules/bad_open_mode.rs
  crates/ruff_linter/src/rules/pylint/rules/bad_str_strip_call.rs
  crates/ruff_linter/src/rules/pylint/rules/repeated_keyword_argument.rs
  crates/ruff_linter/src/rules/pylint/rules/unspecified_encoding.rs
  crates/ruff_linter/src/rules/pyupgrade/rules/convert_named_tuple_functional_to_class.rs
  crates/ruff_linter/src/rules/pyupgrade/rules/convert_typed_dict_functional_to_class.rs
  crates/ruff_linter/src/rules/pyupgrade/rules/printf_string_formatting.rs
  crates/ruff_linter/src/rules/pyupgrade/rules/redundant_open_modes.rs
  crates/ruff_linter/src/rules/pyupgrade/rules/unnecessary_encode_utf8.rs
  crates/ruff_linter/src/rules/ruff/rules/implicit_optional.rs
  crates/ruff_linter/src/rules/ruff/typing.rs
  crates/ruff_python_ast/src/all.rs
  crates/ruff_python_ast/src/nodes.rs
Labels: internal

#8828 Remove `#[allow(unused_variables)]` from visitor methods
  crates/ruff_python_ast/src/visitor.rs
  crates/ruff_python_ast/src/visitor/transformer.rs
Labels: internal

#8837 Auto-generate formatter nodes for string parts
  crates/ruff_python_formatter/src/generated.rs
  crates/ruff_python_formatter/src/other/bytes_literal.rs
  crates/ruff_python_formatter/src/other/f_string.rs
  crates/ruff_python_formatter/src/other/mod.rs
  crates/ruff_python_formatter/src/other/string_literal.rs
Labels: formatter

#8838 Allow space-before-colon after end-of-slice
  crates/ruff_linter/resources/test/fixtures/pycodestyle/E20.py
  crates/ruff_linter/src/rules/pycodestyle/rules/logical_lines/extraneous_whitespace.rs
  crates/ruff_linter/src/rules/pycodestyle/snapshots/ruff_linter__rules__pycodestyle__tests__E202_E20.py.snap
  crates/ruff_linter/src/rules/pycodestyle/snapshots/ruff_linter__rules__pycodestyle__tests__E203_E20.py.snap
Labels: bug

#8839 [`pylint`] Extend `self-assigning-variable` to multi-target assignments
  crates/ruff_linter/resources/test/fixtures/pylint/self_assigning_variable.py
  crates/ruff_linter/src/checkers/ast/analyze/statement.rs
  crates/ruff_linter/src/rules/pylint/rules/self_assigning_variable.rs
  crates/ruff_linter/src/rules/pylint/snapshots/ruff_linter__rules__pylint__tests__PLW0127_self_assigning_variable.py.snap
Labels: bug

#8853 Add advice for fixing RUF008 when mutability is not desired
  crates/ruff_linter/src/rules/ruff/rules/mutable_class_default.rs
Labels: documentation

#8861 ruff_python_formatter: move docstring handling to a submodule
  crates/ruff_python_formatter/src/expression/string/docstring.rs
  crates/ruff_python_formatter/src/expression/string/mod.rs
Labels: internal

#8842 [`refurb`] Implement `redundant-log-base` (`FURB163`)
  crates/ruff_linter/resources/test/fixtures/refurb/FURB163.py
  crates/ruff_linter/src/checkers/ast/analyze/expression.rs
  crates/ruff_linter/src/codes.rs
  crates/ruff_linter/src/rules/refurb/mod.rs
  crates/ruff_linter/src/rules/refurb/rules/mod.rs
  crates/ruff_linter/src/rules/refurb/rules/redundant_log_base.rs
  crates/ruff_linter/src/rules/refurb/snapshots/ruff_linter__rules__refurb__tests__FURB163_FURB163.py.snap
  ruff.schema.json
Labels: rule, preview

#8866 [`pydocstyle`] Avoid non-character breaks in `over-indentation` (`D208`)
  crates/ruff_linter/resources/test/fixtures/pydocstyle/D208.py
  crates/ruff_linter/src/rules/pydocstyle/mod.rs
  crates/ruff_linter/src/rules/pydocstyle/rules/indent.rs
  crates/ruff_linter/src/rules/pydocstyle/snapshots/ruff_linter__rules__pydocstyle__tests__D208_D208.py.snap
Labels: bug, docstring

#8841 [`isort`] Add support for length-sort settings
  crates/ruff_linter/resources/test/fixtures/isort/length_sort_from_imports.py
  crates/ruff_linter/resources/test/fixtures/isort/length_sort_non_ascii_members.py
  crates/ruff_linter/resources/test/fixtures/isort/length_sort_non_ascii_modules.py
  crates/ruff_linter/resources/test/fixtures/isort/length_sort_straight_and_from_imports.py
  crates/ruff_linter/resources/test/fixtures/isort/length_sort_straight_imports.py
  crates/ruff_linter/resources/test/fixtures/isort/length_sort_with_relative_imports.py
  crates/ruff_linter/resources/test/fixtures/isort/length_sort_with_star_import.py
  crates/ruff_linter/src/rules/isort/mod.rs
  crates/ruff_linter/src/rules/isort/order.rs
  crates/ruff_linter/src/rules/isort/settings.rs
  crates/ruff_linter/src/rules/isort/snapshots/ruff_linter__rules__isort__tests__length_sort__length_sort_from_imports.py.snap
  crates/ruff_linter/src/rules/isort/snapshots/ruff_linter__rules__isort__tests__length_sort__length_sort_non_ascii_members.py.snap
  crates/ruff_linter/src/rules/isort/snapshots/ruff_linter__rules__isort__tests__length_sort__length_sort_non_ascii_modules.py.snap
  crates/ruff_linter/src/rules/isort/snapshots/ruff_linter__rules__isort__tests__length_sort__length_sort_straight_and_from_imports.py.snap
  crates/ruff_linter/src/rules/isort/snapshots/ruff_linter__rules__isort__tests__length_sort__length_sort_straight_imports.py.snap
  crates/ruff_linter/src/rules/isort/snapshots/ruff_linter__rules__isort__tests__length_sort__length_sort_with_relative_imports.py.snap
  crates/ruff_linter/src/rules/isort/snapshots/ruff_linter__rules__isort__tests__length_sort_straight__length_sort_from_imports.py.snap
  crates/ruff_linter/src/rules/isort/snapshots/ruff_linter__rules__isort__tests__length_sort_straight__length_sort_straight_and_from_imports.py.snap
  crates/ruff_linter/src/rules/isort/snapshots/ruff_linter__rules__isort__tests__length_sort_straight__length_sort_straight_imports.py.snap
  crates/ruff_linter/src/rules/isort/sorting.rs
  crates/ruff_workspace/src/options.rs
  ruff.schema.json
Labels: isort

#8600 remove several uses of `unsafe`
  crates/ruff_formatter/src/arguments.rs
  crates/ruff_formatter/src/builders.rs
  crates/ruff_formatter/src/format_element.rs
  crates/ruff_formatter/src/macros.rs
  crates/ruff_macros/src/newtype_index.rs
  crates/ruff_python_formatter/src/comments/map.rs
  crates/ruff_python_formatter/src/expression/binary_like.rs
  crates/ruff_python_literal/src/escape.rs
  crates/ruff_python_parser/src/string.rs
  crates/ruff_source_file/src/newlines.rs
Labels: internal

#8878 Update `ruff-dev` to use `SourceKind`
  crates/ruff_dev/src/print_ast.rs
  crates/ruff_dev/src/print_tokens.rs
Labels: internal
