Repository astral-sh/ruff, pull requests merged in 2023-10, with the labels that each got.

#7729 Add Python 3.12 support to FAQ
  docs/faq.md
Labels: documentation

#7739 Perform insertions before replacements
  crates/ruff_diagnostics/src/fix.rs
  crates/ruff_linter/resources/test/fixtures/ruff/RUF017_0.py
  crates/ruff_linter/resources/test/fixtures/ruff/RUF017_1.py
  crates/ruff_linter/src/rules/ruff/mod.rs
  crates/ruff_linter/src/rules/ruff/snapshots/ruff_linter__rules__ruff__tests__RUF017_RUF017_0.py.snap
  crates/ruff_linter/src/rules/ruff/snapshots/ruff_linter__rules__ruff__tests__RUF017_RUF017_1.py.snap
Labels: bug, fuzzer

#7740 Skip all bracketed expressions when locating comparison ops
  crates/ruff_linter/resources/test/fixtures/pyflakes/F632.py
  crates/ruff_linter/src/rules/pyflakes/snapshots/ruff_linter__rules__pyflakes__tests__F632_F632.py.snap
  crates/ruff_python_parser/src/lib.rs
Labels: bug, fuzzer

#7743 Remove string allocation in relative import formatting
  crates/ruff_python_formatter/src/statement/stmt_import_from.rs
Labels: performance, formatter

#7745 Decrease PEP 593 error to a debug warning
  crates/ruff_linter/src/checkers/ast/mod.rs
Labels: cli

#7750 Add documentation for remaining undocumented lint rules
  crates/ruff_linter/src/codes.rs
  crates/ruff_linter/src/rules/flake8_annotations/rules/definition.rs
  crates/ruff_linter/src/rules/flake8_bandit/rules/shell_injection.rs
  crates/ruff_linter/src/rules/flake8_pyi/rules/any_eq_ne_annotation.rs
  crates/ruff_linter/src/rules/flake8_pyi/rules/docstring_in_stubs.rs
  crates/ruff_linter/src/rules/flake8_pyi/rules/future_annotations_in_stub.rs
  crates/ruff_linter/src/rules/flake8_pyi/rules/numeric_literal_too_long.rs
  crates/ruff_linter/src/rules/flake8_pyi/rules/pass_in_class_body.rs
  crates/ruff_linter/src/rules/flake8_pyi/rules/quoted_annotation_in_stub.rs
  crates/ruff_linter/src/rules/flake8_pyi/rules/simple_defaults.rs
  crates/ruff_linter/src/rules/flake8_pyi/rules/string_or_bytes_too_long.rs
  crates/ruff_linter/src/rules/flake8_pyi/rules/stub_body_multiple_statements.rs
  crates/ruff_linter/src/rules/flake8_pyi/rules/type_alias_naming.rs
  crates/ruff_linter/src/rules/pygrep_hooks/rules/blanket_type_ignore.rs
Labels: documentation

#7751 Require documentation for all lint rules
  crates/ruff_linter/src/codes.rs
  crates/ruff_linter/src/registry.rs
  crates/ruff_macros/src/map_codes.rs
Labels: internal

#7741 Fix PLE251 rules with f-string escaping
  crates/ruff_linter/resources/test/fixtures/pylint/invalid_characters.py
  crates/ruff_linter/src/rules/pylint/rules/invalid_string_characters.rs
  crates/ruff_linter/src/rules/pylint/snapshots/ruff_linter__rules__pylint__tests__PLE2510_invalid_characters.py.snap
  crates/ruff_linter/src/rules/pylint/snapshots/ruff_linter__rules__pylint__tests__PLE2512_invalid_characters.py.snap
  crates/ruff_linter/src/rules/pylint/snapshots/ruff_linter__rules__pylint__tests__PLE2513_invalid_characters.py.snap
  crates/ruff_linter/src/rules/pylint/snapshots/ruff_linter__rules__pylint__tests__PLE2515_invalid_characters.py.snap
Labels: bug

#7759 Use `locator.slice(range)` over `locator.contents()[range]`
  crates/ruff_linter/src/checkers/noqa.rs
  crates/ruff_linter/src/rules/flake8_simplify/rules/ast_if.rs
  crates/ruff_linter/src/rules/flake8_simplify/rules/reimplemented_builtin.rs
  crates/ruff_linter/src/rules/pyupgrade/rules/outdated_version_block.rs
Labels: internal

#7749 Enable formatting for Jupyter notebooks
  crates/ruff_cli/src/commands/add_noqa.rs
  crates/ruff_cli/src/commands/format.rs
  crates/ruff_cli/src/commands/format_stdin.rs
  crates/ruff_cli/src/diagnostics.rs
  crates/ruff_cli/tests/integration_test.rs
  crates/ruff_diagnostics/src/source_map.rs
  crates/ruff_linter/src/source_kind.rs
Labels: formatter

#7762 Add formatter TOML configuration to the README
  crates/ruff_python_formatter/README.md
Labels: documentation, formatter

#7763 Re-add formatter to GitHub release notes
  .github/release.yml
Labels: internal

#7764 Upgrade LibCST to support Python 3.12
  Cargo.lock
  Cargo.toml
  crates/ruff_linter/resources/test/fixtures/flake8_simplify/SIM117.py
  crates/ruff_linter/src/rules/flake8_simplify/snapshots/ruff_linter__rules__flake8_simplify__tests__SIM117_SIM117.py.snap
Labels: internal

#7766 crlf -> cr-lf in docs
  crates/ruff_workspace/src/options.rs
Labels: documentation

#7767 Document one-call chaining deviation
  crates/ruff_python_formatter/README.md
Labels: documentation

#6478 Use crates.io unicode_names2 0.6.0
  Cargo.lock
  Cargo.toml
  crates/ruff_linter/Cargo.toml
  crates/ruff_python_parser/Cargo.toml
  crates/ruff_python_parser/src/parser.rs
  crates/ruff_python_parser/src/snapshots/ruff_python_parser__parser__tests__unicode_aliases.snap
Labels: internal

#7768 Extend `reimplemented-starmap` (`FURB140`) to catch calls with a single and starred argument
  crates/ruff_linter/resources/test/fixtures/refurb/FURB140.py
  crates/ruff_linter/src/rules/refurb/rules/reimplemented_starmap.rs
  crates/ruff_linter/src/rules/refurb/snapshots/ruff_linter__rules__refurb__tests__FURB140_FURB140.py.snap
  crates/ruff_python_ast/src/comparable.rs
Labels: rule

#7774 Fix documented examples for `unnecessary-subscript-reversal`
  crates/ruff_linter/src/checkers/ast/analyze/expression.rs
  crates/ruff_linter/src/rules/flake8_comprehensions/rules/unnecessary_subscript_reversal.rs
Labels: documentation

#7775 Preserve trailing comments in C414 fixes
  crates/ruff_linter/resources/test/fixtures/flake8_comprehensions/C414.py
  crates/ruff_linter/src/rules/flake8_comprehensions/fixes.rs
  crates/ruff_linter/src/rules/flake8_comprehensions/snapshots/ruff_linter__rules__flake8_comprehensions__tests__C414_C414.py.snap
Labels: bug, autofix

#7780 Avoid curly brace escape in f-string format spec
  crates/ruff_python_parser/src/lexer.rs
  crates/ruff_python_parser/src/snapshots/ruff_python_parser__lexer__tests__fstring_with_format_spec.snap
Labels: bug

#7781 Check sequence type before triggering `unnecessary-enumerate` (`FURB148`) `len` suggestion
  crates/ruff_linter/resources/test/fixtures/refurb/FURB148.py
  crates/ruff_linter/src/rules/refurb/rules/unnecessary_enumerate.rs
  crates/ruff_linter/src/rules/refurb/snapshots/ruff_linter__rules__refurb__tests__FURB148_FURB148.py.snap
  crates/ruff_python_semantic/src/analyze/typing.rs
Labels: bug

#7786 Respect `msgspec.Struct` default-copy semantics
  crates/ruff_linter/resources/test/fixtures/ruff/RUF012.py
  crates/ruff_linter/src/rules/ruff/rules/helpers.rs
  crates/ruff_linter/src/rules/ruff/rules/mutable_class_default.rs
Labels: bug

#7791 Fix publish of playground
  .github/workflows/playground.yaml
Labels: internal, release

#7798 Fix issues with SIM101 (adjacent isinstance() calls)
  crates/ruff_linter/resources/test/fixtures/flake8_simplify/SIM101.py
  crates/ruff_linter/src/rules/flake8_simplify/rules/ast_bool_op.rs
  crates/ruff_linter/src/rules/flake8_simplify/snapshots/ruff_linter__rules__flake8_simplify__tests__SIM101_SIM101.py.snap
Labels: bug

#7802 Use correct start location for class/function clause header
  crates/ruff_python_formatter/resources/test/fixtures/ruff/fmt_skip/decorators.py
  crates/ruff_python_formatter/src/statement/clause.rs
  crates/ruff_python_formatter/tests/snapshots/format@fmt_skip__decorators.py.snap
Labels: bug, formatter

#7789 Show per-cell diffs when analyzing notebooks over `stdin`
  crates/ruff_cli/src/diagnostics.rs
Labels: bug, cli

#7813 Move diffing logic into `SourceKind::diff`
  crates/ruff_cli/src/diagnostics.rs
  crates/ruff_linter/src/source_kind.rs
Labels: internal

#7812 Consider nursery rules to be in-preview for `ruff rule`
  crates/ruff_cli/src/commands/rule.rs
Labels: bug

#7817 Use a dedicated struct for "nested if" rule
  crates/ruff_linter/src/rules/flake8_simplify/rules/ast_if.rs
  crates/ruff_linter/src/rules/flake8_simplify/rules/fix_if.rs
Labels: internal

#7820 Split up `ast_if.rs` into distinct rule files
  crates/ruff_linter/src/rules/flake8_simplify/rules/ast_if.rs
  crates/ruff_linter/src/rules/flake8_simplify/rules/collapsible_if.rs
  crates/ruff_linter/src/rules/flake8_simplify/rules/fix_if.rs
  crates/ruff_linter/src/rules/flake8_simplify/rules/if_else_block_instead_of_dict_get.rs
  crates/ruff_linter/src/rules/flake8_simplify/rules/if_else_block_instead_of_dict_lookup.rs
  crates/ruff_linter/src/rules/flake8_simplify/rules/if_else_block_instead_of_if_exp.rs
  crates/ruff_linter/src/rules/flake8_simplify/rules/if_with_same_arms.rs
  crates/ruff_linter/src/rules/flake8_simplify/rules/mod.rs
  crates/ruff_linter/src/rules/flake8_simplify/rules/needless_bool.rs
Labels: internal

#7822 Correct error in tuple example in ruff formatter docs
  crates/ruff_python_formatter/README.md
Labels: documentation

#7824 Fix playground `Quick Fix` action
  playground/src/Editor/SourceEditor.tsx
Labels: playground

#7809 Report precise location for invalid conversion flag
  crates/ruff_python_parser/src/python.lalrpop
  crates/ruff_python_parser/src/python.rs
Labels: bug

#7827 Add trailing comment deviation to README
  crates/ruff_python_formatter/README.md
Labels: documentation

#7828 Fix typo
  crates/ruff_linter/src/rules/pygrep_hooks/rules/blanket_type_ignore.rs
Labels: internal

#7829 Remove unused ts directive
  playground/src/Editor/SourceEditor.tsx
Labels: playground

#7787 Fix lexing single-quoted f-string with multi-line format spec
  crates/ruff_python_parser/src/lexer.rs
  crates/ruff_python_parser/src/parser.rs
  crates/ruff_python_parser/src/snapshots/ruff_python_parser__lexer__tests__fstring_with_multiline_format_spec.snap
  crates/ruff_python_parser/src/snapshots/ruff_python_parser__parser__tests__fstrings.snap
Labels: bug

#7830 Remove unused empty file
  crates/ruff_linter/src/settings/defaults.rs
Labels: internal

#7831 Fix typo in docs of PLR6301
  crates/ruff_linter/src/rules/pylint/rules/no_self_use.rs
Labels: documentation

#7832 Fix invalid code in `FURB177` example
  crates/ruff_linter/src/rules/refurb/rules/implicit_cwd.rs
Labels: documentation

#7846 Document `reimplemented-starmap` performance effects
  crates/ruff_linter/src/rules/refurb/rules/reimplemented_starmap.rs
Labels: documentation

#7825 Make serde a default feature of ruff_python_formatter
  crates/ruff_python_formatter/Cargo.toml
Labels: internal

#7815 [`refurb`] Implement `single-item-membership-test` (`FURB171`)
  crates/ruff_linter/resources/test/fixtures/refurb/FURB171.py
  crates/ruff_linter/src/checkers/ast/analyze/expression.rs
  crates/ruff_linter/src/codes.rs
  crates/ruff_linter/src/rules/pycodestyle/helpers.rs
  crates/ruff_linter/src/rules/pycodestyle/rules/literal_comparisons.rs
  crates/ruff_linter/src/rules/pycodestyle/rules/not_tests.rs
  crates/ruff_linter/src/rules/refurb/mod.rs
  crates/ruff_linter/src/rules/refurb/rules/mod.rs
  crates/ruff_linter/src/rules/refurb/rules/single_item_membership_test.rs
  crates/ruff_linter/src/rules/refurb/snapshots/ruff_linter__rules__refurb__tests__FURB171_FURB171.py.snap
  crates/ruff_python_ast/src/helpers.rs
  ruff.schema.json
Labels: rule

#7848 Improvements to RUF015
  crates/ruff_linter/resources/test/fixtures/ruff/RUF015.py
  crates/ruff_linter/src/rules/ruff/rules/unnecessary_iterable_allocation_for_first_element.rs
  crates/ruff_linter/src/rules/ruff/snapshots/ruff_linter__rules__ruff__tests__RUF015_RUF015.py.snap
  crates/ruff_python_stdlib/src/builtins.rs
Labels: bug

#7842 Only show warnings for empty preview selectors when enabling rules
  Cargo.lock
  crates/ruff_cli/tests/integration_test.rs
  crates/ruff_workspace/Cargo.toml
  crates/ruff_workspace/src/configuration.rs
Labels: preview

#7855 Fix diff (old and new were reversed)
  crates/ruff_cli/tests/integration_test.rs
  crates/ruff_linter/src/source_kind.rs
Labels: bug

#7857 Disallow f-strings in match pattern literal
  crates/ruff_python_parser/src/parser.rs
  crates/ruff_python_parser/src/python.lalrpop
  crates/ruff_python_parser/src/python.rs
  crates/ruff_python_parser/src/snapshots/ruff_python_parser__parser__tests__fstrings.snap
Labels: bug

#7874 Add `sqlalchemy` methods to boolean-trap exclusion list
  crates/ruff_linter/resources/test/fixtures/flake8_boolean_trap/FBT.py
  crates/ruff_linter/src/rules/flake8_boolean_trap/helpers.rs
  crates/ruff_linter/src/rules/flake8_boolean_trap/snapshots/ruff_linter__rules__flake8_boolean_trap__tests__FBT001_FBT.py.snap
  crates/ruff_linter/src/rules/flake8_boolean_trap/snapshots/ruff_linter__rules__flake8_boolean_trap__tests__FBT003_FBT.py.snap
Labels: bug

#7876 Fix commented-out `coalesce` keyword
  crates/ruff_linter/src/rules/flake8_boolean_trap/helpers.rs
  crates/ruff_linter/src/rules/flake8_boolean_trap/snapshots/ruff_linter__rules__flake8_boolean_trap__tests__FBT003_FBT.py.snap
Labels: internal

#7856 New rule: Prevent assignment expressions in assert statements
  crates/ruff_linter/resources/test/fixtures/ruff/RUF018.py
  crates/ruff_linter/src/checkers/ast/analyze/expression.rs
  crates/ruff_linter/src/codes.rs
  crates/ruff_linter/src/rules/ruff/mod.rs
  crates/ruff_linter/src/rules/ruff/rules/assignment_in_assert.rs
  crates/ruff_linter/src/rules/ruff/rules/mod.rs
  crates/ruff_linter/src/rules/ruff/snapshots/ruff_linter__rules__ruff__tests__RUF018_RUF018.py.snap
  crates/ruff_workspace/src/configuration.rs
  ruff.schema.json
Labels: rule

#7875 Remove min and max range on `line-length` JSON schema
  crates/ruff_workspace/src/options.rs
  ruff.schema.json
Labels: internal

#7880 add autofix for `PYI030`
  crates/ruff_linter/src/rules/flake8_pyi/rules/unnecessary_literal_union.rs
  crates/ruff_linter/src/rules/flake8_pyi/snapshots/ruff_linter__rules__flake8_pyi__tests__PYI030_PYI030.py.snap
  crates/ruff_linter/src/rules/flake8_pyi/snapshots/ruff_linter__rules__flake8_pyi__tests__PYI030_PYI030.pyi.snap
Labels: autofix

#7885 Allow bindings to be created and referenced within annotations
  crates/ruff_linter/resources/test/fixtures/pyflakes/F821_18.py
  crates/ruff_linter/resources/test/fixtures/pyflakes/F821_19.py
  crates/ruff_linter/src/checkers/ast/mod.rs
  crates/ruff_linter/src/rules/pyflakes/mod.rs
  crates/ruff_linter/src/rules/pyflakes/snapshots/ruff_linter__rules__pyflakes__tests__F821_F821_18.py.snap
  crates/ruff_linter/src/rules/pyflakes/snapshots/ruff_linter__rules__pyflakes__tests__F821_F821_19.py.snap
Labels: bug

#7790 Update fix summary message in `check --diff` to include unsafe fix hints
  crates/ruff_cli/src/printer.rs
  crates/ruff_cli/tests/integration_test.rs
Labels: cli

#7841 Add settings for promoting and demoting fixes
  Cargo.lock
  crates/ruff_cli/tests/integration_test.rs
  crates/ruff_diagnostics/Cargo.toml
  crates/ruff_diagnostics/src/fix.rs
  crates/ruff_linter/src/linter.rs
  crates/ruff_linter/src/settings/mod.rs
  crates/ruff_workspace/src/configuration.rs
  crates/ruff_workspace/src/options.rs
  ruff.schema.json
Labels: configuration

#7887 add autofix for `PLC0208`
  crates/ruff_linter/resources/test/fixtures/pylint/iteration_over_set.py
  crates/ruff_linter/src/rules/pylint/rules/iteration_over_set.rs
  crates/ruff_linter/src/rules/pylint/snapshots/ruff_linter__rules__pylint__tests__PLC0208_iteration_over_set.py.snap
Labels: autofix

#7859 Remove spaces from import statements
  crates/ruff_python_formatter/resources/test/fixtures/ruff/statement/import.py
  crates/ruff_python_formatter/resources/test/fixtures/ruff/statement/import_from.py
  crates/ruff_python_formatter/src/other/identifier.rs
  crates/ruff_python_formatter/tests/snapshots/format@statement__import.py.snap
  crates/ruff_python_formatter/tests/snapshots/format@statement__import_from.py.snap
Labels: formatter

#7867 Less scary `ruff format` message
  crates/ruff_cli/src/lib.rs
  crates/ruff_cli/tests/format.rs
  crates/ruff_cli/tests/integration_test.rs
Labels: formatter

#7911 Visit pattern match guard as a boolean test
  crates/ruff_linter/src/checkers/ast/mod.rs
Labels: bug

#7916 [SIM115] Allow `open` followed by `close`
  crates/ruff_linter/resources/test/fixtures/flake8_simplify/SIM115.py
  crates/ruff_linter/src/rules/flake8_simplify/rules/open_file_with_context_handler.rs
Labels: bug

#7910 add autofix for `PLR1714`
  crates/ruff_linter/src/rules/pylint/rules/repeated_equality_comparison.rs
  crates/ruff_linter/src/rules/pylint/snapshots/ruff_linter__rules__pylint__tests__PLR1714_repeated_equality_comparison.py.snap
Labels: autofix

#7900 Drop formatting specific rules from the default set
  README.md
  crates/flake8_to_ruff/src/converter.rs
  crates/ruff_linter/src/settings/mod.rs
  crates/ruff_wasm/src/lib.rs
  crates/ruff_workspace/src/configuration.rs
  crates/ruff_workspace/src/options.rs
  docs/configuration.md
  docs/faq.md
Labels: breaking

#7901 Add documentation for fixes
  .pre-commit-config.yaml
  docs/configuration.md
  mkdocs.template.yml
Labels: documentation

#7924 Add an example of an unsafe fix
  docs/configuration.md
Labels: documentation

#7894 Fix `E251` false positive inside f-strings
  crates/ruff_linter/resources/test/fixtures/pycodestyle/E25.py
  crates/ruff_linter/src/rules/pycodestyle/rules/logical_lines/whitespace_around_named_parameter_equals.rs
Labels: bug

#7870 Format comment before parameter default correctly
  crates/ruff_python_formatter/resources/test/fixtures/ruff/statement/function.py
  crates/ruff_python_formatter/src/other/parameter_with_default.rs
  crates/ruff_python_formatter/tests/snapshots/format@statement__function.py.snap
Labels: bug, formatter

#7921 Use `OneIndexed` in `NotebookIndex`
  crates/ruff_linter/src/logging.rs
  crates/ruff_linter/src/message/grouped.rs
  crates/ruff_linter/src/message/text.rs
  crates/ruff_notebook/Cargo.toml
  crates/ruff_notebook/src/index.rs
  crates/ruff_notebook/src/notebook.rs
Labels: internal

#7886 add autofix for `PYI055`
  crates/ruff_linter/resources/test/fixtures/flake8_pyi/PYI055.py
  crates/ruff_linter/resources/test/fixtures/flake8_pyi/PYI055.pyi
  crates/ruff_linter/src/rules/flake8_pyi/rules/unnecessary_type_union.rs
  crates/ruff_linter/src/rules/flake8_pyi/snapshots/ruff_linter__rules__flake8_pyi__tests__PYI055_PYI055.py.snap
  crates/ruff_linter/src/rules/flake8_pyi/snapshots/ruff_linter__rules__flake8_pyi__tests__PYI055_PYI055.pyi.snap
Labels: autofix

#7895 Simplify `key in dct and dct[key]` to `dct.get(key)`
  crates/ruff_linter/resources/test/fixtures/ruff/RUF019.py
  crates/ruff_linter/src/checkers/ast/analyze/expression.rs
  crates/ruff_linter/src/codes.rs
  crates/ruff_linter/src/rules/ruff/mod.rs
  crates/ruff_linter/src/rules/ruff/rules/mod.rs
  crates/ruff_linter/src/rules/ruff/rules/unnecessary_key_check.rs
  crates/ruff_linter/src/rules/ruff/snapshots/ruff_linter__rules__ruff__tests__RUF019_RUF019.py.snap
  ruff.schema.json
Labels: rule

#7811 [pylint] Implement consider-using-ternary (R1706)
  crates/ruff_linter/resources/test/fixtures/pylint/and_or_ternary.py
  crates/ruff_linter/src/checkers/ast/analyze/expression.rs
  crates/ruff_linter/src/codes.rs
  crates/ruff_linter/src/rules/pylint/mod.rs
  crates/ruff_linter/src/rules/pylint/rules/and_or_ternary.rs
  crates/ruff_linter/src/rules/pylint/rules/mod.rs
  crates/ruff_linter/src/rules/pylint/snapshots/ruff_linter__rules__pylint__tests__PLR1706_and_or_ternary.py.snap
  crates/ruff_workspace/src/configuration.rs
  ruff.schema.json
Labels: rule

#7935 Fix i686 host builds
  Cargo.lock
  Cargo.toml
Labels: internal

#7954 Respect subscripted base classes in type-checking rules
  crates/ruff_linter/resources/test/fixtures/flake8_type_checking/runtime_evaluated_base_classes_3.py
  crates/ruff_linter/src/rules/flake8_type_checking/helpers.rs
Labels: bug

#7933 Fix false positive in `PLR6301`
  crates/ruff_linter/resources/test/fixtures/pylint/no_self_use.py
  crates/ruff_linter/src/checkers/ast/analyze/deferred_scopes.rs
  crates/ruff_linter/src/rules/pylint/rules/no_self_use.rs
  crates/ruff_linter/src/rules/pylint/snapshots/ruff_linter__rules__pylint__tests__PLR6301_no_self_use.py.snap
Labels: bug

#7962 Resolve `cache-dir` relative to project root
  crates/ruff_workspace/src/configuration.rs
Labels: bug

#7968 Treat type aliases as typing-only expressions
  crates/ruff_linter/resources/test/fixtures/flake8_type_checking/TCH004_15.py
  crates/ruff_linter/src/checkers/ast/mod.rs
  crates/ruff_linter/src/rules/flake8_type_checking/mod.rs
  crates/ruff_linter/src/rules/flake8_type_checking/snapshots/ruff_linter__rules__flake8_type_checking__tests__runtime-import-in-type-checking-block_TCH004_15.py.snap
Labels: bug

#7955 Force parentheses for power operations in unary expressions
  crates/ruff_python_formatter/src/expression/expr_unary_op.rs
  crates/ruff_python_formatter/tests/snapshots/black_compatibility@simple_cases__expression.py.snap
Labels: bug, formatter

#7956 Add trailing zero between dot and exponential
  crates/ruff_python_formatter/resources/test/fixtures/ruff/expression/number.py
  crates/ruff_python_formatter/src/expression/number.rs
  crates/ruff_python_formatter/tests/snapshots/format@expression__number.py.snap
Labels: bug, formatter

#7983 Use released unicode_name2 1.2.0
  Cargo.lock
  Cargo.toml
Labels: internal

#7981 Update and extend formatter ecosystem checks
  scripts/formatter_ecosystem_checks.sh
Labels: internal, formatter

#7985 Bump regex to 1.10.2
  Cargo.lock
  Cargo.toml
Labels: internal

#7984 Remove support for providing output format via `format` option
  BREAKING_CHANGES.md
  crates/ruff_cli/src/args.rs
  crates/ruff_cli/src/lib.rs
  crates/ruff_cli/tests/format.rs
  crates/ruff_wasm/src/lib.rs
  crates/ruff_workspace/src/configuration.rs
  crates/ruff_workspace/src/options.rs
  crates/ruff_workspace/src/resolver.rs
  ruff.schema.json
Labels: breaking, configuration

#7987 Allow sunder names from `enum.Enum`
  crates/ruff_linter/resources/test/fixtures/pylint/bad_dunder_method_name.py
  crates/ruff_linter/src/rules/pylint/rules/bad_dunder_method_name.rs
Labels: bug

#7969 Update fix safety FAQ to reflect `--unsafe-fixes`
  docs/configuration.md
  docs/faq.md
Labels: documentation

#7988 Add entry for #7987 to 0.1.0 changelog
  CHANGELOG.md
Labels: internal

#7989 [docs] Clarify that new rules should be added to `RuleGroup::Preview`.
  CONTRIBUTING.md
Labels: documentation

#7991 Rename `RuleGroup::Unspecified` to `Stable`
  crates/ruff_linter/src/codes.rs
  crates/ruff_macros/src/map_codes.rs
  scripts/add_rule.py
Labels: internal

#7961 [pylint] Implement misplaced-bare-raise (E0704)
  crates/ruff_linter/resources/test/fixtures/pylint/misplaced_bare_raise.py
  crates/ruff_linter/src/checkers/ast/analyze/statement.rs
  crates/ruff_linter/src/checkers/ast/mod.rs
  crates/ruff_linter/src/codes.rs
  crates/ruff_linter/src/rules/pylint/helpers.rs
  crates/ruff_linter/src/rules/pylint/mod.rs
  crates/ruff_linter/src/rules/pylint/rules/misplaced_bare_raise.rs
  crates/ruff_linter/src/rules/pylint/rules/mod.rs
  crates/ruff_linter/src/rules/pylint/rules/return_in_init.rs
  crates/ruff_linter/src/rules/pylint/rules/yield_in_init.rs
  crates/ruff_linter/src/rules/pylint/snapshots/ruff_linter__rules__pylint__tests__PLE0704_misplaced_bare_raise.py.snap
  ruff.schema.json
Labels: rule

#7939 Implement the pylint rule PLW1514 (unspecified-encoding)
  crates/ruff_linter/resources/test/fixtures/pylint/unspecified_encoding.py
  crates/ruff_linter/src/checkers/ast/analyze/expression.rs
  crates/ruff_linter/src/codes.rs
  crates/ruff_linter/src/rules/pylint/mod.rs
  crates/ruff_linter/src/rules/pylint/rules/mod.rs
  crates/ruff_linter/src/rules/pylint/rules/unspecified_encoding.rs
  crates/ruff_linter/src/rules/pylint/snapshots/ruff_linter__rules__pylint__tests__PLW1514_unspecified_encoding.py.snap
  ruff.schema.json
Labels: rule

#8001 Use set bracket replacement for `iteration-over-set`
  crates/ruff_linter/resources/test/fixtures/pylint/iteration_over_set.py
  crates/ruff_linter/src/rules/pylint/rules/iteration_over_set.rs
  crates/ruff_linter/src/rules/pylint/snapshots/ruff_linter__rules__pylint__tests__PLC0208_iteration_over_set.py.snap
Labels: autofix

#7973 implement PLR6201 with autofix
  crates/ruff_linter/resources/test/fixtures/pylint/literal_membership.py
  crates/ruff_linter/src/checkers/ast/analyze/expression.rs
  crates/ruff_linter/src/codes.rs
  crates/ruff_linter/src/rules/pylint/mod.rs
  crates/ruff_linter/src/rules/pylint/rules/literal_membership.rs
  crates/ruff_linter/src/rules/pylint/rules/mod.rs
  crates/ruff_linter/src/rules/pylint/snapshots/ruff_linter__rules__pylint__tests__PLR6201_literal_membership.py.snap
  ruff.schema.json
Labels: rule

#7975 [pylint] Implement PLR0916 (`too-many-boolean-expressions`)
  crates/ruff_linter/resources/test/fixtures/pylint/too_many_boolean_expressions.py
  crates/ruff_linter/src/checkers/ast/analyze/statement.rs
  crates/ruff_linter/src/codes.rs
  crates/ruff_linter/src/rules/pylint/mod.rs
  crates/ruff_linter/src/rules/pylint/rules/mod.rs
  crates/ruff_linter/src/rules/pylint/rules/too_many_boolean_expressions.rs
  crates/ruff_linter/src/rules/pylint/settings.rs
  crates/ruff_linter/src/rules/pylint/snapshots/ruff_linter__rules__pylint__tests__max_boolean_expressions.snap
  crates/ruff_workspace/src/options.rs
  ruff.schema.json
  scripts/check_docs_formatted.py
Labels: rule

#7967 Add autofix for `D300`
  crates/ruff_linter/resources/test/fixtures/pydocstyle/D300.py
  crates/ruff_linter/src/rules/pydocstyle/mod.rs
  crates/ruff_linter/src/rules/pydocstyle/rules/triple_quotes.rs
  crates/ruff_linter/src/rules/pydocstyle/snapshots/ruff_linter__rules__pydocstyle__tests__D300_D.py.snap
  crates/ruff_linter/src/rules/pydocstyle/snapshots/ruff_linter__rules__pydocstyle__tests__D300_D300.py.snap
  crates/ruff_linter/src/rules/pydocstyle/snapshots/ruff_linter__rules__pydocstyle__tests__bom.snap
Labels: autofix

#8015 Avoid flagging `bad-dunder-method-name` for `_`
  crates/ruff_linter/resources/test/fixtures/pylint/bad_dunder_method_name.py
  crates/ruff_linter/src/rules/pylint/rules/bad_dunder_method_name.rs
Labels: bug

#8014 Update GitHub actions example in docs to use `--output-format`
  docs/editor-integrations.md
Labels: documentation

#8013 [docs] fix typo
  crates/ruff_workspace/src/options.rs
  ruff.schema.json
Labels: documentation

#8028 Update rule B005 docs
  crates/ruff_linter/src/rules/flake8_bugbear/rules/strip_with_multi_characters.rs
Labels: documentation

#8000 Add `[format|lint].exclude` options
  crates/flake8_to_ruff/src/converter.rs
  crates/ruff_cli/src/args.rs
  crates/ruff_cli/src/commands/add_noqa.rs
  crates/ruff_cli/src/commands/check.rs
  crates/ruff_cli/src/commands/check_stdin.rs
  crates/ruff_cli/src/commands/format.rs
  crates/ruff_cli/src/commands/format_stdin.rs
  crates/ruff_cli/src/commands/show_files.rs
  crates/ruff_cli/src/commands/show_settings.rs
  crates/ruff_cli/src/diagnostics.rs
  crates/ruff_cli/tests/format.rs
  crates/ruff_cli/tests/lint.rs
  crates/ruff_dev/src/format_dev.rs
  crates/ruff_linter/src/settings/mod.rs
  crates/ruff_python_formatter/src/builders.rs
  crates/ruff_wasm/src/lib.rs
  crates/ruff_workspace/src/configuration.rs
  crates/ruff_workspace/src/options.rs
  crates/ruff_workspace/src/pyproject.rs
  crates/ruff_workspace/src/resolver.rs
  crates/ruff_workspace/src/settings.rs
  ruff.schema.json
Labels: configuration, formatter

#8002 Add `lint.preview`
  crates/ruff_cli/src/args.rs
  crates/ruff_workspace/src/configuration.rs
  crates/ruff_workspace/src/options.rs
  ruff.schema.json
Labels: configuration, cli

#8033 Lazily evaluate all PEP 695 type alias values
  crates/ruff_linter/resources/test/fixtures/pyflakes/F401_19.py
  crates/ruff_linter/resources/test/fixtures/pyflakes/F821_20.py
  crates/ruff_linter/src/checkers/ast/deferred.rs
  crates/ruff_linter/src/checkers/ast/mod.rs
  crates/ruff_linter/src/rules/pyflakes/mod.rs
  crates/ruff_linter/src/rules/pyflakes/snapshots/ruff_linter__rules__pyflakes__tests__F401_F401_19.py.snap
  crates/ruff_linter/src/rules/pyflakes/snapshots/ruff_linter__rules__pyflakes__tests__F821_F821_20.py.snap
  crates/ruff_python_semantic/src/model.rs
Labels: bug

#8029 Avoid failed assertion when showing fixes from stdin
  crates/ruff_cli/src/diagnostics.rs
  crates/ruff_cli/src/printer.rs
  crates/ruff_cli/tests/integration_test.rs
Labels: bug, cli

#7970 add autofix for `D301`
  crates/ruff_linter/resources/test/fixtures/pydocstyle/D301.py
  crates/ruff_linter/src/rules/pydocstyle/rules/backslashes.rs
  crates/ruff_linter/src/rules/pydocstyle/snapshots/ruff_linter__rules__pydocstyle__tests__D301_D.py.snap
  crates/ruff_linter/src/rules/pydocstyle/snapshots/ruff_linter__rules__pydocstyle__tests__D301_D301.py.snap
Labels: autofix

#7946 Insert newline after nested function or class statements
  crates/ruff_python_ast/src/node.rs
  crates/ruff_python_formatter/resources/test/fixtures/ruff/newlines.py
  crates/ruff_python_formatter/src/comments/placement.rs
  crates/ruff_python_formatter/src/statement/suite.rs
  crates/ruff_python_formatter/tests/snapshots/black_compatibility@simple_cases__function2.py.snap
  crates/ruff_python_formatter/tests/snapshots/format@newlines.py.snap
  crates/ruff_python_formatter/tests/snapshots/format@statement__if.py.snap
  crates/ruff_python_formatter/tests/snapshots/format@statement__try.py.snap
Labels: formatter

#7937 Add `--diff` option `ruff format`
  crates/ruff_cli/resources/test/fixtures/formatted.py
  crates/ruff_cli/resources/test/fixtures/unformatted.ipynb
  crates/ruff_cli/resources/test/fixtures/unformatted.py
  crates/ruff_cli/src/args.rs
  crates/ruff_cli/src/commands/format.rs
  crates/ruff_cli/src/commands/format_stdin.rs
  crates/ruff_cli/tests/format.rs
Labels: cli, formatter

#8046 Avoid flagging HTTP and HTTPS literals in urllib-open
  crates/ruff_linter/resources/test/fixtures/flake8_bandit/S310.py
  crates/ruff_linter/src/rules/flake8_bandit/mod.rs
  crates/ruff_linter/src/rules/flake8_bandit/rules/suspicious_function_call.rs
  crates/ruff_linter/src/rules/flake8_bandit/snapshots/ruff_linter__rules__flake8_bandit__tests__S310_S310.py.snap
Labels: bug

#8047 Remove Python 2-only methods from URLOpen audit
  crates/ruff_linter/resources/test/fixtures/flake8_bandit/S310.py
  crates/ruff_linter/src/rules/flake8_bandit/rules/suspicious_function_call.rs
  crates/ruff_linter/src/rules/flake8_bandit/snapshots/ruff_linter__rules__flake8_bandit__tests__S310_S310.py.snap
Labels: bug

#8054 Skip over parentheses when detecting `in` keyword
  crates/ruff_python_formatter/resources/test/fixtures/ruff/expression/list_comp.py
  crates/ruff_python_formatter/src/other/comprehension.rs
  crates/ruff_python_formatter/tests/snapshots/format@expression__list_comp.py.snap
Labels: bug, formatter

#8032 Document `lint.preview` and `format.preview`
  docs/preview.md
Labels: documentation

#8006 Respect `tab-size` setting in formatter
  crates/ruff_cli/tests/format.rs
  crates/ruff_formatter/src/lib.rs
  crates/ruff_linter/src/line_width.rs
  crates/ruff_workspace/src/configuration.rs
  crates/ruff_workspace/src/options.rs
  crates/ruff_workspace/src/settings.rs
  ruff.schema.json
Labels: configuration, formatter

#8055 Accept `--target-version` in the format CLI
  crates/ruff_cli/src/args.rs
Labels: cli, formatter

#8058 [pylint] - implement `global-at-module-level` (`W0604`)
  crates/ruff_linter/resources/test/fixtures/pylint/global_at_module_level.py
  crates/ruff_linter/src/checkers/ast/analyze/statement.rs
  crates/ruff_linter/src/codes.rs
  crates/ruff_linter/src/rules/pylint/mod.rs
  crates/ruff_linter/src/rules/pylint/rules/global_at_module_level.rs
  crates/ruff_linter/src/rules/pylint/rules/mod.rs
  crates/ruff_linter/src/rules/pylint/snapshots/ruff_linter__rules__pylint__tests__PLW0604_global_at_module_level.py.snap
  ruff.schema.json
Labels: rule

#7873 Comments outside expression parentheses
  crates/ruff_formatter/src/lib.rs
  crates/ruff_python_ast/src/parenthesize.rs
  crates/ruff_python_formatter/resources/test/fixtures/ruff/expression/unary.py
  crates/ruff_python_formatter/resources/test/fixtures/ruff/parentheses/expression_parentheses_comments.py
  crates/ruff_python_formatter/resources/test/fixtures/ruff/statement/with.py
  crates/ruff_python_formatter/src/comments/placement.rs
  crates/ruff_python_formatter/src/expression/mod.rs
  crates/ruff_python_formatter/src/lib.rs
  crates/ruff_python_formatter/tests/snapshots/black_compatibility@miscellaneous__long_strings_flag_disabled.py.snap
  crates/ruff_python_formatter/tests/snapshots/format@expression__call.py.snap
  crates/ruff_python_formatter/tests/snapshots/format@expression__unary.py.snap
  crates/ruff_python_formatter/tests/snapshots/format@parentheses__expression_parentheses_comments.py.snap
  crates/ruff_python_formatter/tests/snapshots/format@statement__with.py.snap
Labels: formatter

#8066 Update tutorial to match revised Ruff defaults
  README.md
  docs/tutorial.md
  scripts/generate_mkdocs.py
Labels: documentation

#8062 Remove leftover constant tuple reference
  crates/ruff_linter/src/rules/pylint/settings.rs
  crates/ruff_python_ast/src/comparable.rs
  crates/ruff_workspace/src/options.rs
  ruff.schema.json
Labels: internal

#8077 Fix changelog links for 0.1.1
  CHANGELOG.md
Labels: internal

#8079 Avoid false-positive print separator diagnostic with starred argument
  crates/ruff_linter/resources/test/fixtures/refurb/FURB105.py
  crates/ruff_linter/src/rules/refurb/rules/print_empty_string.rs
Labels: bug

#8057 Change `line-ending` default to `auto`
  crates/ruff_cli/tests/format.rs
  crates/ruff_workspace/src/options.rs
  crates/ruff_workspace/src/settings.rs
  ruff.schema.json
Labels: breaking, formatter

#8072 Avoid if-else simplification for `TYPE_CHECKING` blocks
  crates/ruff_linter/resources/test/fixtures/flake8_simplify/SIM108.py
  crates/ruff_linter/src/checkers/ast/analyze/statement.rs
  crates/ruff_linter/src/rules/flake8_simplify/rules/collapsible_if.rs
  crates/ruff_linter/src/rules/flake8_simplify/rules/if_else_block_instead_of_dict_get.rs
  crates/ruff_linter/src/rules/flake8_simplify/rules/if_else_block_instead_of_dict_lookup.rs
  crates/ruff_linter/src/rules/flake8_simplify/rules/if_else_block_instead_of_if_exp.rs
  crates/ruff_linter/src/rules/flake8_simplify/rules/needless_bool.rs
  crates/ruff_python_semantic/src/analyze/typing.rs
Labels: bug

#8080 Add `#[automatically_derived]` to derived impls
  crates/ruff_macros/src/cache_key.rs
  crates/ruff_macros/src/combine_options.rs
  crates/ruff_macros/src/config.rs
  crates/ruff_macros/src/rule_namespace.rs
  crates/ruff_macros/src/violation.rs
Labels: internal

#8081 Fix `Options` JSON schema description
  crates/ruff_workspace/src/options.rs
  ruff.schema.json
Labels: documentation

#8086 Fix "Preview features" heading level in CHANGELOG
  CHANGELOG.md
Labels: internal

#7682 [refurb] Implement `read-whole-file` [`FURB101`]
  crates/ruff_linter/resources/test/fixtures/refurb/FURB101.py
  crates/ruff_linter/src/checkers/ast/analyze/statement.rs
  crates/ruff_linter/src/codes.rs
  crates/ruff_linter/src/rules/refurb/mod.rs
  crates/ruff_linter/src/rules/refurb/rules/mod.rs
  crates/ruff_linter/src/rules/refurb/rules/read_whole_file.rs
  crates/ruff_linter/src/rules/refurb/snapshots/ruff_linter__rules__refurb__tests__FURB101_FURB101.py.snap
  ruff.schema.json
Labels: rule

#7953 [pylint] Implement unnecessary-lambda (W0108)
  crates/ruff_linter/resources/test/fixtures/pylint/unnecessary_lambda.py
  crates/ruff_linter/src/checkers/ast/analyze/deferred_lambdas.rs
  crates/ruff_linter/src/checkers/ast/analyze/mod.rs
  crates/ruff_linter/src/checkers/ast/deferred.rs
  crates/ruff_linter/src/checkers/ast/mod.rs
  crates/ruff_linter/src/codes.rs
  crates/ruff_linter/src/rules/pylint/mod.rs
  crates/ruff_linter/src/rules/pylint/rules/mod.rs
  crates/ruff_linter/src/rules/pylint/rules/unnecessary_lambda.rs
  crates/ruff_linter/src/rules/pylint/snapshots/ruff_linter__rules__pylint__tests__PLW0108_unnecessary_lambda.py.snap
  ruff.schema.json
Labels: rule

#8098 Move remaining lambda rule to deferred pass
  crates/ruff_linter/src/checkers/ast/analyze/deferred_lambdas.rs
  crates/ruff_linter/src/checkers/ast/analyze/expression.rs
  crates/ruff_linter/src/checkers/ast/mod.rs
Labels: internal

#8097 Update fix for `literal-membership` (`PLR6201`) to be unsafe
  crates/ruff_linter/src/rules/pylint/rules/literal_membership.rs
  crates/ruff_linter/src/rules/pylint/snapshots/ruff_linter__rules__pylint__tests__PLR6201_literal_membership.py.snap
Labels: type-inference

#8056 [pylint] - Implement `non-ascii-module-import` (`C2403`)
  crates/ruff_linter/resources/test/fixtures/pylint/non_ascii_module_import.py
  crates/ruff_linter/src/checkers/ast/analyze/statement.rs
  crates/ruff_linter/src/codes.rs
  crates/ruff_linter/src/rules/pylint/mod.rs
  crates/ruff_linter/src/rules/pylint/rules/mod.rs
  crates/ruff_linter/src/rules/pylint/rules/non_ascii_module_import.rs
  crates/ruff_linter/src/rules/pylint/snapshots/ruff_linter__rules__pylint__tests__PLC2403_non_ascii_module_import.py.snap
  ruff.schema.json
Labels: rule

#8038 [pylint] - implement `non-ascii-name` (`C2401`)
  crates/ruff_linter/resources/test/fixtures/pylint/non_ascii_name.py
  crates/ruff_linter/src/checkers/ast/analyze/bindings.rs
  crates/ruff_linter/src/checkers/ast/analyze/statement.rs
  crates/ruff_linter/src/codes.rs
  crates/ruff_linter/src/rules/pylint/mod.rs
  crates/ruff_linter/src/rules/pylint/rules/mod.rs
  crates/ruff_linter/src/rules/pylint/rules/non_ascii_module_import.rs
  crates/ruff_linter/src/rules/pylint/rules/non_ascii_name.rs
  crates/ruff_linter/src/rules/pylint/snapshots/ruff_linter__rules__pylint__tests__PLC2401_non_ascii_name.py.snap
  ruff.schema.json
Labels: rule

#7415 Make SIM401 catch ternary operations
  crates/ruff_linter/resources/test/fixtures/flake8_simplify/SIM401.py
  crates/ruff_linter/src/checkers/ast/analyze/expression.rs
  crates/ruff_linter/src/rules/flake8_simplify/mod.rs
  crates/ruff_linter/src/rules/flake8_simplify/rules/if_else_block_instead_of_dict_get.rs
  crates/ruff_linter/src/rules/flake8_simplify/snapshots/ruff_linter__rules__flake8_simplify__tests__preview__SIM401_SIM401.py.snap
Labels: rule

#8110 Update versions in format benchmark script
  scripts/benchmarks/run_formatter.sh
Labels: documentation

#8111 Improve `magic-value-comparison` example in docs
  crates/ruff_linter/src/rules/pylint/rules/magic_value_comparison.rs
Labels: documentation

#8112 Detect `sys.version_info` slices in `outdated-version-block`
  crates/ruff_linter/resources/test/fixtures/pyupgrade/UP036_0.py
  crates/ruff_linter/src/rules/pyupgrade/rules/outdated_version_block.rs
  crates/ruff_linter/src/rules/pyupgrade/snapshots/ruff_linter__rules__pyupgrade__tests__UP036_0.py.snap
Labels: bug

#8113 Include `backports.strenum` in `deprecated-imports`
  crates/ruff_linter/resources/test/fixtures/pyupgrade/UP035.py
  crates/ruff_linter/src/rules/pyupgrade/rules/deprecated_import.rs
  crates/ruff_linter/src/rules/pyupgrade/snapshots/ruff_linter__rules__pyupgrade__tests__UP035.py.snap
Labels: rule

#8114 Add fix for E261
  crates/ruff_linter/src/rules/pycodestyle/rules/logical_lines/whitespace_before_comment.rs
  crates/ruff_linter/src/rules/pycodestyle/snapshots/ruff_linter__rules__pycodestyle__tests__E261_E26.py.snap
Labels: autofix

#8115 [`flake8-import-conventions`] Add links to options
  crates/ruff_linter/src/rules/flake8_import_conventions/rules/banned_import_alias.rs
  crates/ruff_linter/src/rules/flake8_import_conventions/rules/banned_import_from.rs
  crates/ruff_linter/src/rules/flake8_import_conventions/rules/unconventional_import_alias.rs
Labels: documentation

#8116 Refactor `get_mark_decorators` to return a marker name
  crates/ruff_linter/src/rules/flake8_pytest_style/rules/fixture.rs
  crates/ruff_linter/src/rules/flake8_pytest_style/rules/helpers.rs
  crates/ruff_linter/src/rules/flake8_pytest_style/rules/marks.rs
Labels: internal

#8100 Respect parenthesized generators in `has_own_parentheses`
  crates/ruff_python_formatter/resources/test/fixtures/ruff/expression/unary.py
  crates/ruff_python_formatter/src/expression/expr_tuple.rs
  crates/ruff_python_formatter/src/expression/mod.rs
  crates/ruff_python_formatter/tests/snapshots/format@expression__binary.py.snap
  crates/ruff_python_formatter/tests/snapshots/format@expression__unary.py.snap
Labels: bug, formatter

#8101 Fix range of unparenthesized tuple subject in match statement
  crates/ruff_python_formatter/resources/test/fixtures/ruff/statement/match.py
  crates/ruff_python_formatter/tests/snapshots/format@statement__match.py.snap
  crates/ruff_python_parser/src/parser.rs
  crates/ruff_python_parser/src/python.lalrpop
  crates/ruff_python_parser/src/python.rs
  crates/ruff_python_parser/src/snapshots/ruff_python_parser__parser__tests__match.snap
  crates/ruff_python_parser/src/snapshots/ruff_python_parser__parser__tests__patma.snap
Labels: bug, formatter

#8007 Rust 1.73
  .github/workflows/ci.yaml
  crates/flake8_to_ruff/src/parser.rs
  crates/ruff_cli/src/args.rs
  crates/ruff_formatter/src/builders.rs
  crates/ruff_linter/src/rules/pycodestyle/rules/logical_lines/missing_whitespace_around_operator.rs
  crates/ruff_notebook/src/notebook.rs
  crates/ruff_python_semantic/src/model.rs
  crates/ruff_workspace/src/options_base.rs
  rust-toolchain.toml
Labels: internal

#8124 Remove unnecessary mutable variable `has_parameters`
  crates/ruff_linter/src/rules/flake8_pytest_style/rules/marks.rs
Labels: internal

#8089 Add caching to formatter
  crates/ruff_cli/src/args.rs
  crates/ruff_cli/src/cache.rs
  crates/ruff_cli/src/commands/check.rs
  crates/ruff_cli/src/commands/format.rs
  crates/ruff_cli/src/diagnostics.rs
  crates/ruff_cli/tests/format.rs
  crates/ruff_cli/tests/integration_test.rs
  docs/configuration.md
Labels: cli, formatter

#8088 Warn about incompatible formatter options
  crates/ruff_cli/src/commands/format.rs
  crates/ruff_cli/src/commands/format_stdin.rs
  crates/ruff_cli/tests/format.rs
Labels: formatter

#8134 Avoid loading files for cached format results
  crates/ruff_cli/src/cache.rs
  crates/ruff_cli/src/commands/format.rs
Labels: performance

#8139 [docs] fix `extend-unsafe-fixes` and `extend-safe-fixes` example error
  crates/ruff_workspace/src/options.rs
Labels: documentation

#8143 add auto-fix for E223,224,242
  crates/ruff_linter/src/rules/pycodestyle/rules/logical_lines/space_around_operator.rs
  crates/ruff_linter/src/rules/pycodestyle/snapshots/ruff_linter__rules__pycodestyle__tests__E223_E22.py.snap
  crates/ruff_linter/src/rules/pycodestyle/snapshots/ruff_linter__rules__pycodestyle__tests__E224_E22.py.snap
  crates/ruff_linter/src/rules/pycodestyle/snapshots/ruff_linter__rules__pycodestyle__tests__E242_E24.py.snap
Labels: autofix

#8133 add auto-fix for E275
  crates/ruff_linter/src/rules/pycodestyle/rules/logical_lines/missing_whitespace.rs
  crates/ruff_linter/src/rules/pycodestyle/rules/logical_lines/missing_whitespace_after_keyword.rs
  crates/ruff_linter/src/rules/pycodestyle/snapshots/ruff_linter__rules__pycodestyle__tests__E231_E23.py.snap
  crates/ruff_linter/src/rules/pycodestyle/snapshots/ruff_linter__rules__pycodestyle__tests__E275_E27.py.snap
Labels: autofix

#8142 add auto-fix for E252
  crates/ruff_linter/src/rules/pycodestyle/rules/logical_lines/whitespace_around_named_parameter_equals.rs
  crates/ruff_linter/src/rules/pycodestyle/snapshots/ruff_linter__rules__pycodestyle__tests__E252_E25.py.snap
Labels: autofix

#8016 Add compatibility test for `ruff-lsp` to CI
  .github/workflows/ci.yaml
Labels: internal

#8131 Remove `--line-length` option from `format` command
  crates/ruff_cli/src/args.rs
  crates/ruff_python_formatter/README.md
Labels: cli, formatter

#8148 Remove experimental formatter warning
  crates/ruff_cli/src/commands/format.rs
  crates/ruff_cli/src/lib.rs
  crates/ruff_cli/tests/format.rs
  crates/ruff_cli/tests/integration_test.rs
Labels: formatter

#8150 Add formatter to `line-length` documentation
  crates/ruff_linter/src/rules/pycodestyle/rules/doc_line_too_long.rs
  crates/ruff_linter/src/rules/pycodestyle/rules/line_too_long.rs
  crates/ruff_linter/src/rules/pycodestyle/snapshots/ruff_linter__rules__pycodestyle__tests__E501_E501.py.snap
  crates/ruff_linter/src/rules/pycodestyle/snapshots/ruff_linter__rules__pycodestyle__tests__E501_E501_3.py.snap
  crates/ruff_linter/src/rules/pycodestyle/snapshots/ruff_linter__rules__pycodestyle__tests__max_doc_length.snap
  crates/ruff_linter/src/rules/pycodestyle/snapshots/ruff_linter__rules__pycodestyle__tests__max_doc_length_with_utf_8.snap
  crates/ruff_linter/src/rules/pycodestyle/snapshots/ruff_linter__rules__pycodestyle__tests__tab_size_1.snap
  crates/ruff_linter/src/rules/pycodestyle/snapshots/ruff_linter__rules__pycodestyle__tests__tab_size_2.snap
  crates/ruff_linter/src/rules/pycodestyle/snapshots/ruff_linter__rules__pycodestyle__tests__tab_size_4.snap
  crates/ruff_linter/src/rules/pycodestyle/snapshots/ruff_linter__rules__pycodestyle__tests__tab_size_8.snap
  crates/ruff_linter/src/rules/pycodestyle/snapshots/ruff_linter__rules__pycodestyle__tests__task_tags_false.snap
  crates/ruff_linter/src/rules/ruff/snapshots/ruff_linter__rules__ruff__tests__ruf100_0.snap
  crates/ruff_workspace/src/options.rs
  docs/tutorial.md
  ruff.schema.json
Labels: documentation, formatter

#8039 New `pycodestyle.max-line-length` option
  crates/ruff_cli/src/args.rs
  crates/ruff_cli/tests/lint.rs
  crates/ruff_linter/src/checkers/physical_lines.rs
  crates/ruff_linter/src/rules/flake8_simplify/rules/ast_with.rs
  crates/ruff_linter/src/rules/flake8_simplify/rules/collapsible_if.rs
  crates/ruff_linter/src/rules/flake8_simplify/rules/if_else_block_instead_of_dict_get.rs
  crates/ruff_linter/src/rules/flake8_simplify/rules/if_else_block_instead_of_if_exp.rs
  crates/ruff_linter/src/rules/flake8_simplify/rules/reimplemented_builtin.rs
  crates/ruff_linter/src/rules/isort/rules/organize_imports.rs
  crates/ruff_linter/src/rules/pycodestyle/mod.rs
  crates/ruff_linter/src/rules/pycodestyle/rules/line_too_long.rs
  crates/ruff_linter/src/rules/pycodestyle/settings.rs
  crates/ruff_linter/src/rules/pyupgrade/rules/f_strings.rs
  crates/ruff_linter/src/settings/mod.rs
  crates/ruff_workspace/src/configuration.rs
  crates/ruff_workspace/src/options.rs
  ruff.schema.json
Labels: configuration
