Repository astral-sh/ruff, pull requests merged in 2023-05, with the labels that each got.

#4157 Reference related settings in rules
  crates/ruff_dev/src/generate_rules_table.rs
Labels: documentation

#4211 [flake8-pyi] PYI020
  crates/ruff/resources/test/fixtures/flake8_pyi/PYI020.py
  crates/ruff/resources/test/fixtures/flake8_pyi/PYI020.pyi
  crates/ruff/src/checkers/ast/mod.rs
  crates/ruff/src/codes.rs
  crates/ruff/src/registry.rs
  crates/ruff/src/rules/flake8_pyi/mod.rs
  crates/ruff/src/rules/flake8_pyi/rules/mod.rs
  crates/ruff/src/rules/flake8_pyi/rules/quoted_annotation_in_stub.rs
  crates/ruff/src/rules/flake8_pyi/snapshots/ruff__rules__flake8_pyi__tests__PYI020_PYI020.py.snap
  crates/ruff/src/rules/flake8_pyi/snapshots/ruff__rules__flake8_pyi__tests__PYI020_PYI020.pyi.snap
  ruff.schema.json
Labels: rule

#4178 Update B027 to support autofixing
  crates/ruff/resources/test/fixtures/flake8_bugbear/B027_extended.py
  crates/ruff/src/rules/flake8_bugbear/mod.rs
  crates/ruff/src/rules/flake8_bugbear/rules/abstract_base_class.rs
  crates/ruff/src/rules/flake8_bugbear/snapshots/ruff__rules__flake8_bugbear__tests__B027_B027.py.snap
  crates/ruff/src/rules/flake8_bugbear/snapshots/ruff__rules__flake8_bugbear__tests__B027_B027_extended.py.snap
Labels: autofix

#4214 [`flake8-pyi`] Implement `PYI042` and `PYI043`
  crates/ruff/resources/test/fixtures/flake8_pyi/PYI042.py
  crates/ruff/resources/test/fixtures/flake8_pyi/PYI042.pyi
  crates/ruff/resources/test/fixtures/flake8_pyi/PYI043.py
  crates/ruff/resources/test/fixtures/flake8_pyi/PYI043.pyi
  crates/ruff/src/checkers/ast/mod.rs
  crates/ruff/src/codes.rs
  crates/ruff/src/registry.rs
  crates/ruff/src/registry/rule_set.rs
  crates/ruff/src/rules/flake8_pyi/mod.rs
  crates/ruff/src/rules/flake8_pyi/rules/mod.rs
  crates/ruff/src/rules/flake8_pyi/rules/type_alias_naming.rs
  crates/ruff/src/rules/flake8_pyi/snapshots/ruff__rules__flake8_pyi__tests__PYI042_PYI042.py.snap
  crates/ruff/src/rules/flake8_pyi/snapshots/ruff__rules__flake8_pyi__tests__PYI042_PYI042.pyi.snap
  crates/ruff/src/rules/flake8_pyi/snapshots/ruff__rules__flake8_pyi__tests__PYI043_PYI043.py.snap
  crates/ruff/src/rules/flake8_pyi/snapshots/ruff__rules__flake8_pyi__tests__PYI043_PYI043.pyi.snap
  ruff.schema.json
Labels: rule

#4146 Change `--fix-only` exit semantics to mirror `--fix`
  BREAKING_CHANGES.md
  crates/ruff_cli/src/lib.rs
Labels: breaking, cli

#4260 Fix `RET504` example in docs
  crates/ruff/src/rules/flake8_return/rules.rs
Labels: documentation

#4270 Check docs formatting check
  .github/workflows/ci.yaml
  crates/ruff/src/rules/flake8_bugbear/rules/function_call_argument_default.rs
  crates/ruff/src/rules/flake8_commas/rules.rs
  crates/ruff/src/rules/flake8_django/rules/exclude_with_model_form.rs
  crates/ruff/src/rules/flake8_django/rules/locals_in_render_function.rs
  crates/ruff/src/rules/flake8_pyi/rules/type_comment_in_stub.rs
  crates/ruff/src/rules/flake8_return/rules.rs
  crates/ruff/src/rules/flake8_type_checking/rules/empty_type_checking_block.rs
  crates/ruff/src/rules/flake8_type_checking/rules/runtime_import_in_type_checking_block.rs
  crates/ruff/src/rules/flake8_type_checking/rules/typing_only_runtime_import.rs
  crates/ruff/src/rules/flake8_unused_arguments/rules.rs
  crates/ruff/src/rules/pep8_naming/rules/invalid_argument_name.rs
  crates/ruff/src/rules/pycodestyle/rules/compound_statements.rs
  crates/ruff/src/rules/pycodestyle/rules/imports.rs
  crates/ruff/src/rules/pycodestyle/rules/invalid_escape_sequence.rs
  crates/ruff/src/rules/pycodestyle/rules/lambda_assignment.rs
  crates/ruff/src/rules/pycodestyle/rules/literal_comparisons.rs
  crates/ruff/src/rules/pycodestyle/rules/not_tests.rs
  crates/ruff/src/rules/pycodestyle/rules/type_comparison.rs
  crates/ruff/src/rules/pygrep_hooks/rules/deprecated_log_warn.rs
  crates/ruff/src/rules/pylint/rules/binary_op_exception.rs
  crates/ruff/src/rules/pylint/rules/continue_in_finally.rs
  crates/ruff/src/rules/pylint/rules/global_statement.rs
  crates/ruff/src/rules/pylint/rules/invalid_string_characters.rs
  crates/ruff/src/rules/pylint/rules/unnecessary_direct_lambda_call.rs
  crates/ruff/src/rules/pylint/rules/useless_return.rs
  crates/ruff/src/rules/ruff/rules/mutable_defaults_in_dataclass_fields.rs
  crates/ruff/src/rules/ruff/rules/unused_noqa.rs
  docs/requirements.txt
  scripts/check_docs_formatted.py
  scripts/pyproject.toml
Labels: documentation

#4292 Clarify some docstring-related docs
  docs/faq.md
Labels: documentation

#4313 Remove deprecated `update-check` setting
  BREAKING_CHANGES.md
  crates/ruff/src/settings/configuration.rs
  crates/ruff/src/settings/mod.rs
  crates/ruff/src/settings/options.rs
  crates/ruff_cli/src/args.rs
  crates/ruff_cli/src/lib.rs
  crates/ruff_wasm/src/lib.rs
  ruff.schema.json
Labels: breaking

#4332 Add flake8-pie documentation
  crates/ruff/src/rules/flake8_pie/rules.rs
Labels: documentation

#4334 Add docs for flake8-simplify rules
  crates/ruff/src/rules/flake8_simplify/rules/ast_expr.rs
  crates/ruff/src/rules/flake8_simplify/rules/open_file_with_context_handler.rs
  crates/ruff/src/rules/flake8_simplify/rules/return_in_try_except_finally.rs
  crates/ruff/src/rules/flake8_simplify/snapshots/ruff__rules__flake8_simplify__tests__SIM107_SIM107.py.snap
Labels: documentation

#4347 Enforce max-doc-length for multi-line docstrings
  crates/ruff/resources/test/fixtures/pycodestyle/W505.py
  crates/ruff/src/checkers/physical_lines.rs
  crates/ruff/src/doc_lines.rs
  crates/ruff/src/linter.rs
  crates/ruff/src/rules/pycodestyle/snapshots/ruff__rules__pycodestyle__tests__max_doc_length.snap
Labels: bug

#4007 JSON Emitter: Use one indexed column numbers for edits
  crates/ruff/src/message/json.rs
  crates/ruff/src/message/snapshots/ruff__message__json__tests__output.snap
  crates/ruff_cli/tests/integration_test.rs
Labels: breaking

#4366 Implement pygrep-hook's Mock-mistake diagnostic
  README.md
  crates/ruff/resources/test/fixtures/pygrep-hooks/PGH005_0.py
  crates/ruff/src/checkers/ast/mod.rs
  crates/ruff/src/codes.rs
  crates/ruff/src/registry.rs
  crates/ruff/src/rules/pygrep_hooks/mod.rs
  crates/ruff/src/rules/pygrep_hooks/rules/invalid_mock_access.rs
  crates/ruff/src/rules/pygrep_hooks/rules/mod.rs
  crates/ruff/src/rules/pygrep_hooks/snapshots/ruff__rules__pygrep_hooks__tests__PGH005_PGH005_0.py.snap
  docs/faq.md
  ruff.schema.json
Labels: rule

#4376 Remove lifetime from FormatContext
  crates/ruff_python_formatter/src/context.rs
  crates/ruff_python_formatter/src/format/alias.rs
  crates/ruff_python_formatter/src/format/arg.rs
  crates/ruff_python_formatter/src/format/arguments.rs
  crates/ruff_python_formatter/src/format/bool_op.rs
  crates/ruff_python_formatter/src/format/builders.rs
  crates/ruff_python_formatter/src/format/cmp_op.rs
  crates/ruff_python_formatter/src/format/comments.rs
  crates/ruff_python_formatter/src/format/comprehension.rs
  crates/ruff_python_formatter/src/format/excepthandler.rs
  crates/ruff_python_formatter/src/format/expr.rs
  crates/ruff_python_formatter/src/format/keyword.rs
  crates/ruff_python_formatter/src/format/match_case.rs
  crates/ruff_python_formatter/src/format/numbers.rs
  crates/ruff_python_formatter/src/format/operator.rs
  crates/ruff_python_formatter/src/format/pattern.rs
  crates/ruff_python_formatter/src/format/stmt.rs
  crates/ruff_python_formatter/src/format/strings.rs
  crates/ruff_python_formatter/src/format/unary_op.rs
  crates/ruff_python_formatter/src/format/withitem.rs
  crates/ruff_python_formatter/src/lib.rs
Labels: internal

#4378 Avoid re-using imports beyond current edit size
  crates/ruff/resources/test/fixtures/flake8_simplify/SIM105_3.py
  crates/ruff/src/autofix/actions.rs
  crates/ruff/src/rules/flake8_simplify/mod.rs
  crates/ruff/src/rules/flake8_simplify/snapshots/ruff__rules__flake8_simplify__tests__SIM105_SIM105_3.py.snap
Labels: bug

#4379 Move some recursion out of the pre-visit statement phase
  crates/ruff/src/checkers/ast/mod.rs
Labels: internal

#4387 Implement `RUF010` to detect explicit type conversions within f-strings
  crates/ruff/resources/test/fixtures/ruff/RUF010.py
  crates/ruff/src/checkers/ast/mod.rs
  crates/ruff/src/codes.rs
  crates/ruff/src/registry.rs
  crates/ruff/src/rules/ruff/mod.rs
  crates/ruff/src/rules/ruff/rules/explicit_f_string_type_conversion.rs
  crates/ruff/src/rules/ruff/rules/mod.rs
  crates/ruff/src/rules/ruff/snapshots/ruff__rules__ruff__tests__RUF010_RUF010.py.snap
  ruff.schema.json
Labels: rule

#4411 [`pylint`] Add `duplicate-bases` rule
  crates/ruff/resources/test/fixtures/pylint/duplicate_bases.py
  crates/ruff/src/checkers/ast/mod.rs
  crates/ruff/src/codes.rs
  crates/ruff/src/registry.rs
  crates/ruff/src/rules/pylint/mod.rs
  crates/ruff/src/rules/pylint/rules/duplicate_bases.rs
  crates/ruff/src/rules/pylint/rules/mod.rs
  crates/ruff/src/rules/pylint/snapshots/ruff__rules__pylint__tests__PLE0241_duplicate_bases.py.snap
  ruff.schema.json
Labels: rule

#4427 [`pyupgrade`] Remove `keep-runtime-typing` setting
  BREAKING_CHANGES.md
  crates/ruff/src/checkers/ast/mod.rs
  crates/ruff/src/rules/pyupgrade/mod.rs
  crates/ruff/src/rules/pyupgrade/settings.rs
  crates/ruff/src/settings/configuration.rs
  crates/ruff/src/settings/defaults.rs
  crates/ruff/src/settings/mod.rs
  crates/ruff/src/settings/options.rs
  crates/ruff_wasm/src/lib.rs
  ruff.schema.json
Labels: breaking, configuration

#4432 Implement flake8-async plugin
  LICENSE
  README.md
  crates/ruff/resources/test/fixtures/flake8_async/ASYNC100.py
  crates/ruff/resources/test/fixtures/flake8_async/ASYNC101.py
  crates/ruff/resources/test/fixtures/flake8_async/ASYNC102.py
  crates/ruff/src/checkers/ast/mod.rs
  crates/ruff/src/codes.rs
  crates/ruff/src/registry.rs
  crates/ruff/src/rules/flake8_async/mod.rs
  crates/ruff/src/rules/flake8_async/rules.rs
  crates/ruff/src/rules/flake8_async/snapshots/ruff__rules__flake8_async__tests__ASYNC100_ASYNC100.py.snap
  crates/ruff/src/rules/flake8_async/snapshots/ruff__rules__flake8_async__tests__ASYNC101_ASYNC101.py.snap
  crates/ruff/src/rules/flake8_async/snapshots/ruff__rules__flake8_async__tests__ASYNC102_ASYNC102.py.snap
  crates/ruff/src/rules/mod.rs
  docs/faq.md
  ruff.schema.json
Labels: rule

#4437 Add PLE rule docs
  crates/ruff/src/rules/pylint/rules/await_outside_async.rs
  crates/ruff/src/rules/pylint/rules/bad_str_strip_call.rs
  crates/ruff/src/rules/pylint/rules/bidirectional_unicode.rs
  crates/ruff/src/rules/pylint/rules/invalid_all_format.rs
  crates/ruff/src/rules/pylint/rules/invalid_all_object.rs
  crates/ruff/src/rules/pylint/rules/load_before_global_declaration.rs
  crates/ruff/src/rules/pylint/rules/nonlocal_without_binding.rs
  crates/ruff/src/rules/pylint/rules/unexpected_special_method_signature.rs
Labels: documentation

#4420 Enable automatic rewrites of `typing.Deque` and `typing.DefaultDict`
  crates/ruff/resources/test/fixtures/pyupgrade/UP006.py
  crates/ruff/src/checkers/ast/mod.rs
  crates/ruff/src/rules/pyupgrade/rules/use_pep585_annotation.rs
  crates/ruff/src/rules/pyupgrade/rules/use_pep604_annotation.rs
  crates/ruff/src/rules/pyupgrade/snapshots/ruff__rules__pyupgrade__tests__UP006.py.snap
  crates/ruff/src/rules/pyupgrade/snapshots/ruff__rules__pyupgrade__tests__future_annotations_pep_585_p37.snap
  crates/ruff/src/rules/pyupgrade/snapshots/ruff__rules__pyupgrade__tests__future_annotations_pep_585_py310.snap
  crates/ruff_python_semantic/src/analyze/typing.rs
  crates/ruff_python_stdlib/src/typing.rs
Labels: autofix

#4293 [`flake8-pyi`] Implement `unannotated-assignment-in-stub` (`PY052`)
  crates/ruff/resources/test/fixtures/flake8_pyi/PYI052.py
  crates/ruff/resources/test/fixtures/flake8_pyi/PYI052.pyi
  crates/ruff/src/checkers/ast/mod.rs
  crates/ruff/src/codes.rs
  crates/ruff/src/registry.rs
  crates/ruff/src/rules/flake8_pyi/mod.rs
  crates/ruff/src/rules/flake8_pyi/rules/mod.rs
  crates/ruff/src/rules/flake8_pyi/rules/simple_defaults.rs
  crates/ruff/src/rules/flake8_pyi/snapshots/ruff__rules__flake8_pyi__tests__PYI052_PYI052.py.snap
  crates/ruff/src/rules/flake8_pyi/snapshots/ruff__rules__flake8_pyi__tests__PYI052_PYI052.pyi.snap
  ruff.schema.json
Labels: rule

#4328 Impl `Default` for `SourceLocation`
  crates/ruff/src/message/azure.rs
  crates/ruff/src/message/github.rs
  crates/ruff/src/message/junit.rs
  crates/ruff_python_ast/src/source_code/mod.rs
Labels: internal

#4450 Specialize ConversionFlag
  Cargo.lock
  Cargo.toml
  crates/ruff/src/rules/flynt/helpers.rs
  crates/ruff/src/rules/ruff/rules/explicit_f_string_type_conversion.rs
  crates/ruff_python_ast/src/comparable.rs
  crates/ruff_python_ast/src/source_code/generator.rs
  crates/ruff_python_formatter/src/cst/mod.rs
  crates/ruff_python_formatter/src/format/expr.rs
Labels: internal

#4457 Split logical lines tests into one test per assertion
  crates/ruff/src/checkers/logical_lines.rs
  crates/ruff/src/rules/pycodestyle/rules/logical_lines/mod.rs
Labels: internal

#4449 Prototype Black's string joining/splitting
  crates/ruff_python_formatter/src/lib.rs
  crates/ruff_python_formatter/src/snapshots/ruff_python_formatter__tests__string_processing.snap
Labels: autoformatter

#4469 Add PLW docs
  crates/ruff/src/rules/pylint/rules/global_variable_not_assigned.rs
  crates/ruff/src/rules/pylint/rules/import_self.rs
  crates/ruff/src/rules/pylint/rules/nested_min_max.rs
  crates/ruff/src/rules/pylint/rules/useless_else_on_loop.rs
Labels: documentation

#4478 Move `Insertion` into its own module
  crates/ruff/src/importer.rs
  crates/ruff/src/importer/insertion.rs
  crates/ruff/src/importer/mod.rs
Labels: internal

#4490 Extend multi-line noqa directives to start-of-line
  crates/ruff/resources/test/fixtures/ruff/RUF100_0.py
  crates/ruff/src/directives.rs
  crates/ruff/src/rules/ruff/snapshots/ruff__rules__ruff__tests__ruf100_0.snap
Labels: bug

#4492 Remove unnecessary path prefixes
  crates/ruff/src/autofix/actions.rs
  crates/ruff/src/checkers/ast/mod.rs
  crates/ruff/src/logging.rs
  crates/ruff/src/message/text.rs
  crates/ruff/src/rules/pyflakes/rules/strings.rs
  crates/ruff/src/rules/pylint/rules/binary_op_exception.rs
  crates/ruff/src/rules/pyupgrade/rules/deprecated_import.rs
  crates/ruff_cache/src/cache_key.rs
  crates/ruff_macros/src/derive_message_formats.rs
  crates/ruff_macros/src/lib.rs
  crates/ruff_python_ast/src/comparable.rs
  crates/ruff_python_ast/src/source_code/line_index.rs
  crates/ruff_python_formatter/src/cst/mod.rs
Labels: internal

#4494 Fix scoping of comprehensions within classes
  crates/ruff/src/checkers/ast/mod.rs
  crates/ruff/src/rules/flake8_simplify/rules/key_in_dict.rs
  crates/ruff/src/rules/pyflakes/mod.rs
  crates/ruff/src/rules/ruff/rules/pairwise_over_zipped.rs
Labels: bug

#4439 Overhaul sdist handling
  .github/workflows/release.yaml
  crates/flake8_to_ruff/pyproject.toml
  pyproject.toml
Labels: release

#4500 [`flake8-bandit`] Implement `paramiko-call` (`S601`)
  crates/ruff/resources/test/fixtures/flake8_bandit/S601.py
  crates/ruff/src/checkers/ast/mod.rs
  crates/ruff/src/codes.rs
  crates/ruff/src/registry.rs
  crates/ruff/src/rules/flake8_bandit/mod.rs
  crates/ruff/src/rules/flake8_bandit/rules/mod.rs
  crates/ruff/src/rules/flake8_bandit/rules/paramiko_calls.rs
  crates/ruff/src/rules/flake8_bandit/snapshots/ruff__rules__flake8_bandit__tests__S601_S601.py.snap
  ruff.schema.json
Labels: rule

#4516 Updated contributing documentation
  CONTRIBUTING.md
Labels: documentation

#4453 Create dummy format CLI
  crates/ruff_cli/src/args.rs
  crates/ruff_cli/src/commands/run_stdin.rs
  crates/ruff_cli/src/lib.rs
Labels: autoformatter

#4515 [`pylint`] Add `duplicate-value` (`W0130`)
  crates/ruff/resources/test/fixtures/pylint/duplicate_value.py
  crates/ruff/src/checkers/ast/mod.rs
  crates/ruff/src/codes.rs
  crates/ruff/src/registry.rs
  crates/ruff/src/rules/pylint/mod.rs
  crates/ruff/src/rules/pylint/rules/duplicate_value.rs
  crates/ruff/src/rules/pylint/rules/mod.rs
  crates/ruff/src/rules/pylint/snapshots/ruff__rules__pylint__tests__PLW0130_duplicate_value.py.snap
  ruff.schema.json
Labels: rule

#4517 [`flake8-pyi`] Implement `PYI013`
  crates/ruff/resources/test/fixtures/flake8_pyi/PYI013.py
  crates/ruff/resources/test/fixtures/flake8_pyi/PYI013.pyi
  crates/ruff/src/checkers/ast/mod.rs
  crates/ruff/src/codes.rs
  crates/ruff/src/registry.rs
  crates/ruff/src/rules/flake8_pyi/mod.rs
  crates/ruff/src/rules/flake8_pyi/rules/ellipsis_in_non_empty_class_body.rs
  crates/ruff/src/rules/flake8_pyi/rules/mod.rs
  crates/ruff/src/rules/flake8_pyi/snapshots/ruff__rules__flake8_pyi__tests__PYI013_PYI013.py.snap
  crates/ruff/src/rules/flake8_pyi/snapshots/ruff__rules__flake8_pyi__tests__PYI013_PYI013.pyi.snap
  ruff.schema.json
Labels: rule

#4531 [`pylint`] Add `named_expr_without_context` (`W0131`)
  crates/ruff/resources/test/fixtures/pylint/named_expr_without_context.py
  crates/ruff/src/checkers/ast/mod.rs
  crates/ruff/src/codes.rs
  crates/ruff/src/registry.rs
  crates/ruff/src/rules/pylint/mod.rs
  crates/ruff/src/rules/pylint/rules/mod.rs
  crates/ruff/src/rules/pylint/rules/named_expr_without_context.rs
  crates/ruff/src/rules/pylint/snapshots/ruff__rules__pylint__tests__PLW0131_named_expr_without_context.py.snap
  ruff.schema.json
Labels: rule

#4524 Fix RUF010 auto-fix with parenthesis
  crates/ruff/resources/test/fixtures/ruff/RUF010.py
  crates/ruff/src/checkers/ast/mod.rs
  crates/ruff/src/cst/matchers.rs
  crates/ruff/src/rules/ruff/rules/explicit_f_string_type_conversion.rs
  crates/ruff/src/rules/ruff/snapshots/ruff__rules__ruff__tests__RUF010_RUF010.py.snap
Labels: bug

#4535 Parenthesize more sub-expressions in f-string conversion
  crates/ruff/resources/test/fixtures/pyupgrade/UP032_2.py
  crates/ruff/src/rules/pyupgrade/rules/f_strings.rs
  crates/ruff/src/rules/pyupgrade/snapshots/ruff__rules__pyupgrade__tests__UP032_2.py.snap
Labels: bug

#4513 Replace token iteration with Indexer/Locator lookups for relevant rules
  crates/ruff/src/checkers/tokens.rs
  crates/ruff/src/linter.rs
  crates/ruff/src/rules/eradicate/rules.rs
  crates/ruff/src/rules/flake8_pyi/rules/type_comment_in_stub.rs
  crates/ruff/src/rules/flake8_todos/rules.rs
Labels: internal

#4467 Include decorators in `Function` and `Class` definition ranges
  Cargo.lock
  Cargo.toml
  crates/ruff/src/checkers/ast/mod.rs
  crates/ruff/src/rules/flake8_builtins/rules.rs
  crates/ruff/src/rules/flake8_builtins/snapshots/ruff__rules__flake8_builtins__tests__A001_A001.py.snap
  crates/ruff/src/rules/flake8_builtins/snapshots/ruff__rules__flake8_builtins__tests__A001_A001.py_builtins_ignorelist.snap
  crates/ruff/src/rules/flake8_builtins/snapshots/ruff__rules__flake8_builtins__tests__A003_A003.py.snap
  crates/ruff/src/rules/flake8_builtins/snapshots/ruff__rules__flake8_builtins__tests__A003_A003.py_builtins_ignorelist.snap
  crates/ruff_python_ast/src/helpers.rs
  crates/ruff_python_formatter/src/cst/mod.rs
  crates/ruff_python_semantic/src/binding.rs
Labels: internal

#4584 Fix `# isort: split` comment detection in nested blocks
  crates/ruff/resources/test/fixtures/isort/split.py
  crates/ruff/src/rules/isort/block.rs
  crates/ruff/src/rules/isort/snapshots/ruff__rules__isort__tests__split.py.snap
Labels: bug, isort

#4597 Introduce `ruff_index` crate
  Cargo.lock
  crates/ruff/src/checkers/ast/mod.rs
  crates/ruff_index/Cargo.toml
  crates/ruff_index/src/idx.rs
  crates/ruff_index/src/lib.rs
  crates/ruff_index/src/slice.rs
  crates/ruff_index/src/vec.rs
  crates/ruff_macros/Cargo.toml
  crates/ruff_macros/src/lib.rs
  crates/ruff_macros/src/newtype_index.rs
  crates/ruff_python_semantic/Cargo.toml
  crates/ruff_python_semantic/src/binding.rs
  crates/ruff_python_semantic/src/definition.rs
  crates/ruff_python_semantic/src/node.rs
  crates/ruff_python_semantic/src/scope.rs
Labels: internal

#4588 Add Pyflakes docs
  crates/ruff/src/rules/pyflakes/rules/imports.rs
Labels: documentation

#4620 Remove outdated feature flag from Dockerfile.ecosystem
  scripts/Dockerfile.ecosystem
Labels: documentation

#4619 Remove source position from `FormatElement::DynamicText`
  Cargo.lock
  crates/ruff_formatter/Cargo.toml
  crates/ruff_formatter/src/builders.rs
  crates/ruff_formatter/src/format_element.rs
  crates/ruff_formatter/src/format_element/document.rs
  crates/ruff_formatter/src/format_extensions.rs
  crates/ruff_formatter/src/lib.rs
  crates/ruff_formatter/src/printer/mod.rs
  crates/ruff_formatter/src/utility_types.rs
  crates/ruff_python_formatter/src/format/alias.rs
  crates/ruff_python_formatter/src/format/arg.rs
  crates/ruff_python_formatter/src/format/builders.rs
  crates/ruff_python_formatter/src/format/excepthandler.rs
  crates/ruff_python_formatter/src/format/expr.rs
  crates/ruff_python_formatter/src/format/keyword.rs
  crates/ruff_python_formatter/src/format/numbers.rs
  crates/ruff_python_formatter/src/format/pattern.rs
  crates/ruff_python_formatter/src/format/stmt.rs
  crates/ruff_python_formatter/src/format/strings.rs
  crates/ruff_python_formatter/src/lib.rs
Labels: internal, autoformatter

#4622 Introduce `SourceCodeSlice` to reduce the size of `FormatElement`
  crates/ruff_formatter/src/builders.rs
  crates/ruff_formatter/src/format_element.rs
  crates/ruff_formatter/src/format_element/document.rs
  crates/ruff_formatter/src/lib.rs
  crates/ruff_formatter/src/printer/mod.rs
  crates/ruff_formatter/src/source_code.rs
  crates/ruff_python_formatter/src/context.rs
  crates/ruff_python_formatter/src/format/alias.rs
  crates/ruff_python_formatter/src/format/arg.rs
  crates/ruff_python_formatter/src/format/arguments.rs
  crates/ruff_python_formatter/src/format/bool_op.rs
  crates/ruff_python_formatter/src/format/builders.rs
  crates/ruff_python_formatter/src/format/cmp_op.rs
  crates/ruff_python_formatter/src/format/comments.rs
  crates/ruff_python_formatter/src/format/comprehension.rs
  crates/ruff_python_formatter/src/format/excepthandler.rs
  crates/ruff_python_formatter/src/format/expr.rs
  crates/ruff_python_formatter/src/format/keyword.rs
  crates/ruff_python_formatter/src/format/match_case.rs
  crates/ruff_python_formatter/src/format/numbers.rs
  crates/ruff_python_formatter/src/format/operator.rs
  crates/ruff_python_formatter/src/format/pattern.rs
  crates/ruff_python_formatter/src/format/stmt.rs
  crates/ruff_python_formatter/src/format/strings.rs
  crates/ruff_python_formatter/src/format/unary_op.rs
  crates/ruff_python_formatter/src/format/withitem.rs
Labels: internal, autoformatter

#4631 Remove separate `ReferenceContext` enum
  crates/ruff/src/checkers/ast/mod.rs
  crates/ruff/src/rules/flake8_type_checking/helpers.rs
  crates/ruff_python_semantic/src/binding.rs
  crates/ruff_python_semantic/src/context.rs
  crates/ruff_python_semantic/src/lib.rs
  crates/ruff_python_semantic/src/model.rs
  crates/ruff_python_semantic/src/reference.rs
Labels: internal

#4632 Move `shared_traits` to `ruff_formatter`
  crates/ruff_formatter/shared_traits.rs
  crates/ruff_python_formatter/src/cst/mod.rs
  crates/ruff_python_formatter/src/format/alias.rs
  crates/ruff_python_formatter/src/format/arg.rs
  crates/ruff_python_formatter/src/format/arguments.rs
  crates/ruff_python_formatter/src/format/bool_op.rs
  crates/ruff_python_formatter/src/format/builders.rs
  crates/ruff_python_formatter/src/format/cmp_op.rs
  crates/ruff_python_formatter/src/format/comments.rs
  crates/ruff_python_formatter/src/format/comprehension.rs
  crates/ruff_python_formatter/src/format/excepthandler.rs
  crates/ruff_python_formatter/src/format/expr.rs
  crates/ruff_python_formatter/src/format/keyword.rs
  crates/ruff_python_formatter/src/format/match_case.rs
  crates/ruff_python_formatter/src/format/numbers.rs
  crates/ruff_python_formatter/src/format/operator.rs
  crates/ruff_python_formatter/src/format/pattern.rs
  crates/ruff_python_formatter/src/format/stmt.rs
  crates/ruff_python_formatter/src/format/strings.rs
  crates/ruff_python_formatter/src/format/unary_op.rs
  crates/ruff_python_formatter/src/format/withitem.rs
  crates/ruff_python_formatter/src/lib.rs
  crates/ruff_python_formatter/src/prelude.rs
  crates/ruff_python_formatter/src/trivia.rs
Labels: internal, autoformatter

#4640 Remove deprecated --universal2 flag
  .github/workflows/flake8-to-ruff.yaml
  .github/workflows/release.yaml
Labels: release

#4643 Testing Macros: Add `extra-traits` feature to syn
  crates/ruff_testing_macros/Cargo.toml
Labels: internal

#4634 Add autofix for PYI010
  crates/ruff/src/rules/flake8_pyi/rules/non_empty_stub_body.rs
  crates/ruff/src/rules/flake8_pyi/snapshots/ruff__rules__flake8_pyi__tests__PYI010_PYI010.pyi.snap
Labels: rule, autofix

#4658 Create `PreorderVisitor` trait
  Cargo.lock
  crates/ruff_python_ast/Cargo.toml
  crates/ruff_python_ast/src/visitor.rs
  crates/ruff_python_ast/src/visitor/preorder.rs
  crates/ruff_python_ast/src/visitor/snapshots/ruff_python_ast__visitor__preorder__tests__compare.snap
  crates/ruff_python_ast/src/visitor/snapshots/ruff_python_ast__visitor__preorder__tests__decorators.snap
  crates/ruff_python_ast/src/visitor/snapshots/ruff_python_ast__visitor__preorder__tests__dict_comprehension.snap
  crates/ruff_python_ast/src/visitor/snapshots/ruff_python_ast__visitor__preorder__tests__function_arguments.snap
  crates/ruff_python_ast/src/visitor/snapshots/ruff_python_ast__visitor__preorder__tests__function_positional_only_with_default.snap
  crates/ruff_python_ast/src/visitor/snapshots/ruff_python_ast__visitor__preorder__tests__list_comprehension.snap
  crates/ruff_python_ast/src/visitor/snapshots/ruff_python_ast__visitor__preorder__tests__match_class_pattern.snap
  crates/ruff_python_ast/src/visitor/snapshots/ruff_python_ast__visitor__preorder__tests__set_comprehension.snap
Labels: internal

#4653 Improve token handling
  .github/workflows/release.yaml
Labels: internal

#4668 Implement Pylint's `yield-inside-async-function` rule (`PLE1700`)
  crates/ruff/resources/test/fixtures/pylint/yield_from_in_async_function.py
  crates/ruff/src/checkers/ast/mod.rs
  crates/ruff/src/codes.rs
  crates/ruff/src/registry.rs
  crates/ruff/src/rules/pylint/mod.rs
  crates/ruff/src/rules/pylint/rules/mod.rs
  crates/ruff/src/rules/pylint/rules/yield_from_in_async_function.rs
  crates/ruff/src/rules/pylint/snapshots/ruff__rules__pylint__tests__PLE1700_yield_from_in_async_function.py.snap
  ruff.schema.json
Labels: rule

#4683 Fix PLW3301 false positive single argument nested min/max
  crates/ruff/resources/test/fixtures/pylint/nested_min_max.py
  crates/ruff/src/rules/pylint/rules/nested_min_max.rs
  crates/ruff/src/rules/pylint/snapshots/ruff__rules__pylint__tests__PLW3301_nested_min_max.py.snap
Labels: bug

#4679 Fix UP036 auto-fix error
  crates/ruff/resources/test/fixtures/pyupgrade/UP036_5.py
  crates/ruff/src/rules/pyupgrade/mod.rs
  crates/ruff/src/rules/pyupgrade/rules/outdated_version_block.rs
  crates/ruff/src/rules/pyupgrade/snapshots/ruff__rules__pyupgrade__tests__UP036_5.py.snap
Labels: bug, autofix

#4689 Add more Pyflakes docs
  crates/ruff/src/rules/pyflakes/rules/assert_tuple.rs
  crates/ruff/src/rules/pyflakes/rules/if_tuple.rs
  crates/ruff/src/rules/pyflakes/rules/invalid_literal_comparisons.rs
  crates/ruff/src/rules/pyflakes/rules/invalid_print_syntax.rs
  crates/ruff/src/rules/pyflakes/rules/repeated_keys.rs
  crates/ruff/src/rules/pyflakes/rules/starred_expressions.rs
Labels: documentation

#4695 [`flake8-pyi`] Add `PYI032` rule with autofix
  crates/ruff/resources/test/fixtures/flake8_pyi/PYI032.py
  crates/ruff/resources/test/fixtures/flake8_pyi/PYI032.pyi
  crates/ruff/src/checkers/ast/mod.rs
  crates/ruff/src/codes.rs
  crates/ruff/src/registry.rs
  crates/ruff/src/rules/flake8_pyi/mod.rs
  crates/ruff/src/rules/flake8_pyi/rules/any_eq_ne_annotation.rs
  crates/ruff/src/rules/flake8_pyi/rules/mod.rs
  crates/ruff/src/rules/flake8_pyi/snapshots/ruff__rules__flake8_pyi__tests__PYI032_PYI032.py.snap
  crates/ruff/src/rules/flake8_pyi/snapshots/ruff__rules__flake8_pyi__tests__PYI032_PYI032.pyi.snap
  ruff.schema.json
Labels: rule

#4690 Add contributing docs specific to rule-testing patterns
  CONTRIBUTING.md
Labels: documentation

#4697 Add docs to clarify project root heuristics
  crates/ruff/src/settings/options.rs
  docs/faq.md
  ruff.schema.json
Labels: documentation

#4687 Add AIR001: task variable name should be same as task_id arg
  README.md
  crates/ruff/resources/test/fixtures/airflow/AIR001.py
  crates/ruff/src/checkers/ast/mod.rs
  crates/ruff/src/codes.rs
  crates/ruff/src/registry.rs
  crates/ruff/src/rules/airflow/mod.rs
  crates/ruff/src/rules/airflow/rules/mod.rs
  crates/ruff/src/rules/airflow/rules/task_variable_name.rs
  crates/ruff/src/rules/airflow/snapshots/ruff__rules__airflow__tests__AIR001_AIR001.py.snap
  crates/ruff/src/rules/mod.rs
  ruff.schema.json
Labels: rule

#4700 [`flake8-pyi`] Implement `PYI045`
  crates/ruff/resources/test/fixtures/flake8_pyi/PYI045.py
  crates/ruff/resources/test/fixtures/flake8_pyi/PYI045.pyi
  crates/ruff/src/checkers/ast/mod.rs
  crates/ruff/src/codes.rs
  crates/ruff/src/registry.rs
  crates/ruff/src/rules/flake8_pyi/mod.rs
  crates/ruff/src/rules/flake8_pyi/rules/iter_method_return_iterable.rs
  crates/ruff/src/rules/flake8_pyi/rules/mod.rs
  crates/ruff/src/rules/flake8_pyi/snapshots/ruff__rules__flake8_pyi__tests__PYI045_PYI045.py.snap
  crates/ruff/src/rules/flake8_pyi/snapshots/ruff__rules__flake8_pyi__tests__PYI045_PYI045.pyi.snap
  ruff.schema.json
Labels: rule

#4712 Fix docs formatting for `iter-method-returns-iterable`
  crates/ruff/src/rules/flake8_pyi/rules/iter_method_return_iterable.rs
Labels: documentation

#4715 Remove enumerated plugins in rules page
  README.md
Labels: documentation

#4714 Add ability to generate snapshot tests on code snippets
  crates/ruff/src/rules/pandas_vet/mod.rs
  crates/ruff/src/rules/pandas_vet/snapshots/ruff__rules__pandas_vet__tests__PD002_fail.snap
  crates/ruff/src/rules/pandas_vet/snapshots/ruff__rules__pandas_vet__tests__PD002_pass.snap
  crates/ruff/src/rules/pandas_vet/snapshots/ruff__rules__pandas_vet__tests__PD003_allows_other_calls.snap
  crates/ruff/src/rules/pandas_vet/snapshots/ruff__rules__pandas_vet__tests__PD003_fail.snap
  crates/ruff/src/rules/pandas_vet/snapshots/ruff__rules__pandas_vet__tests__PD003_pass.snap
  crates/ruff/src/rules/pandas_vet/snapshots/ruff__rules__pandas_vet__tests__PD004_fail.snap
  crates/ruff/src/rules/pandas_vet/snapshots/ruff__rules__pandas_vet__tests__PD004_pass.snap
  crates/ruff/src/rules/pandas_vet/snapshots/ruff__rules__pandas_vet__tests__PD007_fail.snap
  crates/ruff/src/rules/pandas_vet/snapshots/ruff__rules__pandas_vet__tests__PD007_pass_iloc.snap
  crates/ruff/src/rules/pandas_vet/snapshots/ruff__rules__pandas_vet__tests__PD007_pass_loc.snap
  crates/ruff/src/rules/pandas_vet/snapshots/ruff__rules__pandas_vet__tests__PD008_fail.snap
  crates/ruff/src/rules/pandas_vet/snapshots/ruff__rules__pandas_vet__tests__PD008_pass.snap
  crates/ruff/src/rules/pandas_vet/snapshots/ruff__rules__pandas_vet__tests__PD008_pass_on_attr.snap
  crates/ruff/src/rules/pandas_vet/snapshots/ruff__rules__pandas_vet__tests__PD009_fail.snap
  crates/ruff/src/rules/pandas_vet/snapshots/ruff__rules__pandas_vet__tests__PD009_pass.snap
  crates/ruff/src/rules/pandas_vet/snapshots/ruff__rules__pandas_vet__tests__PD010_fail_pivot.snap
  crates/ruff/src/rules/pandas_vet/snapshots/ruff__rules__pandas_vet__tests__PD010_pass.snap
  crates/ruff/src/rules/pandas_vet/snapshots/ruff__rules__pandas_vet__tests__PD011_fail_values.snap
  crates/ruff/src/rules/pandas_vet/snapshots/ruff__rules__pandas_vet__tests__PD011_pass_array.snap
  crates/ruff/src/rules/pandas_vet/snapshots/ruff__rules__pandas_vet__tests__PD011_pass_node_name.snap
  crates/ruff/src/rules/pandas_vet/snapshots/ruff__rules__pandas_vet__tests__PD011_pass_to_array.snap
  crates/ruff/src/rules/pandas_vet/snapshots/ruff__rules__pandas_vet__tests__PD011_pass_values_call.snap
  crates/ruff/src/rules/pandas_vet/snapshots/ruff__rules__pandas_vet__tests__PD011_pass_values_dict.snap
  crates/ruff/src/rules/pandas_vet/snapshots/ruff__rules__pandas_vet__tests__PD011_pass_values_import.snap
  crates/ruff/src/rules/pandas_vet/snapshots/ruff__rules__pandas_vet__tests__PD011_pass_values_unbound.snap
  crates/ruff/src/rules/pandas_vet/snapshots/ruff__rules__pandas_vet__tests__PD012_fail_read_table.snap
  crates/ruff/src/rules/pandas_vet/snapshots/ruff__rules__pandas_vet__tests__PD012_node_Name_pass.snap
  crates/ruff/src/rules/pandas_vet/snapshots/ruff__rules__pandas_vet__tests__PD012_pass_read_csv.snap
  crates/ruff/src/rules/pandas_vet/snapshots/ruff__rules__pandas_vet__tests__PD013_fail_stack.snap
  crates/ruff/src/rules/pandas_vet/snapshots/ruff__rules__pandas_vet__tests__PD013_pass.snap
  crates/ruff/src/rules/pandas_vet/snapshots/ruff__rules__pandas_vet__tests__PD013_pass_numpy.snap
  crates/ruff/src/rules/pandas_vet/snapshots/ruff__rules__pandas_vet__tests__PD013_pass_unbound.snap
  crates/ruff/src/rules/pandas_vet/snapshots/ruff__rules__pandas_vet__tests__PD015_fail_merge_on_pandas_object.snap
  crates/ruff/src/rules/pandas_vet/snapshots/ruff__rules__pandas_vet__tests__PD015_pass_merge_on_dataframe.snap
  crates/ruff/src/rules/pandas_vet/snapshots/ruff__rules__pandas_vet__tests__PD015_pass_merge_on_dataframe_with_multiple_args.snap
  crates/ruff/src/rules/pandas_vet/snapshots/ruff__rules__pandas_vet__tests__PD015_pass_other_pd_function.snap
  crates/ruff/src/rules/pandas_vet/snapshots/ruff__rules__pandas_vet__tests__PD901_fail_df_var.snap
  crates/ruff/src/rules/pandas_vet/snapshots/ruff__rules__pandas_vet__tests__PD901_pass_df_param.snap
  crates/ruff/src/rules/pandas_vet/snapshots/ruff__rules__pandas_vet__tests__PD901_pass_non_df.snap
  crates/ruff/src/rules/pandas_vet/snapshots/ruff__rules__pandas_vet__tests__PD901_pass_part_df.snap
  crates/ruff/src/test.rs
Labels: internal

#4702 [`flake8-future-annotations`] Implement `FA102`
  crates/ruff/src/checkers/ast/mod.rs
  crates/ruff/src/codes.rs
  crates/ruff/src/registry.rs
  crates/ruff/src/rules/flake8_future_annotations/mod.rs
  crates/ruff/src/rules/flake8_future_annotations/rules/missing_future_annotations_new_style.rs
  crates/ruff/src/rules/flake8_future_annotations/rules/missing_future_annotations_old_style.rs
  crates/ruff/src/rules/flake8_future_annotations/rules/mod.rs
  crates/ruff/src/rules/flake8_future_annotations/snapshots/ruff__rules__flake8_future_annotations__tests__fa102_no_future_import_uses_lowercase.py.snap
  crates/ruff/src/rules/flake8_future_annotations/snapshots/ruff__rules__flake8_future_annotations__tests__fa102_no_future_import_uses_union.py.snap
  crates/ruff/src/rules/flake8_future_annotations/snapshots/ruff__rules__flake8_future_annotations__tests__fa102_no_future_import_uses_union_inner.py.snap
  crates/ruff/src/rules/flake8_future_annotations/snapshots/ruff__rules__flake8_future_annotations__tests__fa102_ok_no_types.py.snap
  crates/ruff/src/rules/flake8_future_annotations/snapshots/ruff__rules__flake8_future_annotations__tests__fa102_ok_uses_future.py.snap
  crates/ruff_python_semantic/src/analyze/typing.rs
  ruff.schema.json
Labels: rule

#4721 Move `fixable` checks into patch blocks
  crates/ruff/src/rules/flake8_pytest_style/rules/assertion.rs
  crates/ruff/src/rules/flake8_simplify/rules/ast_bool_op.rs
  crates/ruff/src/rules/flake8_simplify/rules/ast_if.rs
  crates/ruff/src/rules/flake8_simplify/rules/ast_with.rs
  crates/ruff/src/rules/flake8_simplify/rules/suppressible_exception.rs
  crates/ruff/src/rules/pandas_vet/rules/inplace_argument.rs
  crates/ruff/src/rules/pylint/rules/manual_import_from.rs
  crates/ruff/src/rules/pylint/rules/nested_min_max.rs
  crates/ruff/src/rules/pyupgrade/rules/convert_named_tuple_functional_to_class.rs
  crates/ruff/src/rules/pyupgrade/rules/convert_typed_dict_functional_to_class.rs
  crates/ruff/src/rules/pyupgrade/rules/use_pep585_annotation.rs
Labels: internal

#4639 Add `MultiMap` implementation for storing comments
  Cargo.lock
  crates/ruff_python_formatter/Cargo.toml
  crates/ruff_python_formatter/src/comments/map.rs
  crates/ruff_python_formatter/src/comments/mod.rs
  crates/ruff_python_formatter/src/lib.rs
Labels: internal, autoformatter

#4641 Add `Comments` data structure
  crates/ruff_python_formatter/src/comments/debug.rs
  crates/ruff_python_formatter/src/comments/map.rs
  crates/ruff_python_formatter/src/comments/mod.rs
  crates/ruff_python_formatter/src/comments/node_key.rs
  crates/ruff_python_formatter/src/comments/snapshots/ruff_python_formatter__comments__debug__tests__debug.snap
Labels: internal, autoformatter

#4642 Generic "comment to node" association logic
  Cargo.lock
  Cargo.toml
  crates/ruff_formatter/src/source_code.rs
  crates/ruff_python_ast/Cargo.toml
  crates/ruff_python_ast/src/source_code/comment_ranges.rs
  crates/ruff_python_ast/src/source_code/indexer.rs
  crates/ruff_python_ast/src/source_code/mod.rs
  crates/ruff_python_ast/src/whitespace.rs
  crates/ruff_python_formatter/Cargo.toml
  crates/ruff_python_formatter/src/comments/debug.rs
  crates/ruff_python_formatter/src/comments/map.rs
  crates/ruff_python_formatter/src/comments/mod.rs
  crates/ruff_python_formatter/src/comments/placement.rs
  crates/ruff_python_formatter/src/comments/snapshots/ruff_python_formatter__comments__debug__tests__debug.snap
  crates/ruff_python_formatter/src/comments/snapshots/ruff_python_formatter__comments__tests__base_test.snap
  crates/ruff_python_formatter/src/comments/snapshots/ruff_python_formatter__comments__tests__dangling_comment.snap
  crates/ruff_python_formatter/src/comments/snapshots/ruff_python_formatter__comments__tests__empty_file.snap
  crates/ruff_python_formatter/src/comments/snapshots/ruff_python_formatter__comments__tests__leading_most_outer.snap
  crates/ruff_python_formatter/src/comments/snapshots/ruff_python_formatter__comments__tests__only_comments.snap
  crates/ruff_python_formatter/src/comments/snapshots/ruff_python_formatter__comments__tests__parenthesized_expression.snap
  crates/ruff_python_formatter/src/comments/snapshots/ruff_python_formatter__comments__tests__parenthesized_trailing_comment.snap
  crates/ruff_python_formatter/src/comments/snapshots/ruff_python_formatter__comments__tests__trailing_after_comma.snap
  crates/ruff_python_formatter/src/comments/snapshots/ruff_python_formatter__comments__tests__trailing_function_comment.snap
  crates/ruff_python_formatter/src/comments/snapshots/ruff_python_formatter__comments__tests__trailing_most_outer.snap
  crates/ruff_python_formatter/src/comments/snapshots/ruff_python_formatter__comments__tests__trailing_most_outer_nested.snap
  crates/ruff_python_formatter/src/comments/visitor.rs
  crates/ruff_python_formatter/src/context.rs
  crates/ruff_python_formatter/src/lib.rs
  crates/ruff_python_formatter/src/main.rs
Labels: internal, autoformatter

#4732 Clarify that [tool.ruff] must be omitted for ruff.toml
  docs/configuration.md
Labels: documentation

#4733 Add Rust toolchain as documentation dependency in CONTRIBUTING.md
  CONTRIBUTING.md
Labels: documentation

#4739 Refactor `flake8-type-checking` rules to take `Checker`
  crates/ruff/src/checkers/ast/mod.rs
  crates/ruff/src/rules/flake8_type_checking/rules/runtime_import_in_type_checking_block.rs
  crates/ruff/src/rules/flake8_type_checking/rules/typing_only_runtime_import.rs
Labels: internal

#4745 Flag empty strings in flake8-errmsg rules
  crates/ruff/resources/test/fixtures/flake8_errmsg/EM.py
  crates/ruff/src/rules/flake8_errmsg/rules/string_in_exception.rs
  crates/ruff/src/rules/flake8_errmsg/snapshots/ruff__rules__flake8_errmsg__tests__custom.snap
  crates/ruff/src/rules/flake8_errmsg/snapshots/ruff__rules__flake8_errmsg__tests__defaults.snap
Labels: bug

#4747 Upgrade RustPython
  Cargo.lock
  Cargo.toml
  crates/ruff/src/autofix/actions.rs
  crates/ruff/src/importer/insertion.rs
  crates/ruff/src/rules/eradicate/detection.rs
  crates/ruff/src/rules/isort/rules/add_required_imports.rs
  crates/ruff/src/rules/mccabe/rules/function_is_too_complex.rs
  crates/ruff/src/rules/pylint/rules/too_many_branches.rs
  crates/ruff/src/rules/pylint/rules/too_many_return_statements.rs
  crates/ruff/src/rules/pylint/rules/too_many_statements.rs
  crates/ruff_benchmark/benches/parser.rs
  crates/ruff_dev/src/print_ast.rs
  crates/ruff_python_ast/src/helpers.rs
  crates/ruff_python_ast/src/source_code/generator.rs
  crates/ruff_python_ast/src/source_code/mod.rs
  crates/ruff_python_ast/src/typing.rs
  crates/ruff_python_formatter/src/comments/debug.rs
Labels: internal

#4756 Add PYI024 for `flake8-pyi` plugin
  crates/ruff/resources/test/fixtures/flake8_pyi/PYI024.py
  crates/ruff/resources/test/fixtures/flake8_pyi/PYI024.pyi
  crates/ruff/src/checkers/ast/mod.rs
  crates/ruff/src/codes.rs
  crates/ruff/src/registry.rs
  crates/ruff/src/rules/flake8_pyi/mod.rs
  crates/ruff/src/rules/flake8_pyi/rules/collections_named_tuple.rs
  crates/ruff/src/rules/flake8_pyi/rules/mod.rs
  crates/ruff/src/rules/flake8_pyi/snapshots/ruff__rules__flake8_pyi__tests__PYI024_PYI024.py.snap
  crates/ruff/src/rules/flake8_pyi/snapshots/ruff__rules__flake8_pyi__tests__PYI024_PYI024.pyi.snap
  ruff.schema.json
Labels: rule
