Repository astral-sh/ruff, pull requests merged in 2023-06, with the labels that each got.

#4771 Remove erroneous method calls in flake8-unused-arguments docs
  crates/ruff/src/rules/flake8_unused_arguments/rules/unused_arguments.rs
Labels: documentation

#4748 Handle positional-only-arguments separator comments
  crates/ruff_python_formatter/src/comments/mod.rs
  crates/ruff_python_formatter/src/comments/placement.rs
  crates/ruff_python_formatter/src/comments/snapshots/ruff_python_formatter__comments__tests__non_positional_arguments_slash_on_same_line.snap
  crates/ruff_python_formatter/src/comments/snapshots/ruff_python_formatter__comments__tests__non_positional_arguments_with_defaults.snap
  crates/ruff_python_formatter/src/comments/snapshots/ruff_python_formatter__comments__tests__positional_argument_only_comment.snap
  crates/ruff_python_formatter/src/comments/snapshots/ruff_python_formatter__comments__tests__positional_argument_only_comment_without_following_node.snap
  crates/ruff_python_formatter/src/comments/snapshots/ruff_python_formatter__comments__tests__positional_argument_only_leading_comma_comment.snap
Labels: internal, autoformatter

#4751 Place comments of left and right binary expression operands
  crates/ruff_python_formatter/src/comments/mod.rs
  crates/ruff_python_formatter/src/comments/placement.rs
  crates/ruff_python_formatter/src/comments/snapshots/ruff_python_formatter__comments__tests__binary_expression_left_operand_comment.snap
  crates/ruff_python_formatter/src/comments/snapshots/ruff_python_formatter__comments__tests__binary_expression_left_operand_trailing_end_of_line_comment.snap
  crates/ruff_python_formatter/src/comments/snapshots/ruff_python_formatter__comments__tests__nested_binary_expression.snap
  crates/ruff_python_formatter/src/lib.rs
  crates/ruff_python_formatter/src/trivia.rs
Labels: internal, autoformatter

#4780 Introduce `lines_before` helper
  crates/ruff_python_formatter/src/prelude.rs
  crates/ruff_python_formatter/src/trivia.rs
Labels: internal, autoformatter

#4782 Remove collapsing `space` behaviour from `Printer`
  crates/ruff_formatter/src/format_element/document.rs
  crates/ruff_formatter/src/printer/mod.rs
Labels: internal, autoformatter

#4787 Complete the Pyflakes documention
  crates/ruff/src/rules/pyflakes/rules/break_outside_loop.rs
  crates/ruff/src/rules/pyflakes/rules/continue_outside_loop.rs
  crates/ruff/src/rules/pyflakes/rules/default_except_not_last.rs
  crates/ruff/src/rules/pyflakes/rules/forward_annotation_syntax_error.rs
  crates/ruff/src/rules/pyflakes/rules/raise_not_implemented.rs
  crates/ruff/src/rules/pyflakes/rules/redefined_while_unused.rs
  crates/ruff/src/rules/pyflakes/rules/return_outside_function.rs
  crates/ruff/src/rules/pyflakes/rules/undefined_export.rs
  crates/ruff/src/rules/pyflakes/rules/undefined_local.rs
  crates/ruff/src/rules/pyflakes/rules/undefined_name.rs
  crates/ruff/src/rules/pyflakes/rules/unused_annotation.rs
  crates/ruff/src/rules/pyflakes/rules/yield_outside_function.rs
Labels: documentation

#4706 Add Pylint rule `C0208` (`use-sequence-for-iteration`) as `PLC0208` (`iteration-over-set`)
  crates/ruff/resources/test/fixtures/pylint/iteration_over_set.py
  crates/ruff/src/checkers/ast/mod.rs
  crates/ruff/src/codes.rs
  crates/ruff/src/registry.rs
  crates/ruff/src/rules/pylint/mod.rs
  crates/ruff/src/rules/pylint/rules/iteration_over_set.rs
  crates/ruff/src/rules/pylint/rules/mod.rs
  crates/ruff/src/rules/pylint/snapshots/ruff__rules__pylint__tests__PLC0208_iteration_over_set.py.snap
  ruff.schema.json
Labels: rule

#4791 [`flake8-pyi`] Implement `PYI025`
  crates/ruff/resources/test/fixtures/flake8_pyi/PYI025.py
  crates/ruff/resources/test/fixtures/flake8_pyi/PYI025.pyi
  crates/ruff/src/checkers/ast/mod.rs
  crates/ruff/src/codes.rs
  crates/ruff/src/registry.rs
  crates/ruff/src/rules/flake8_pyi/mod.rs
  crates/ruff/src/rules/flake8_pyi/rules/mod.rs
  crates/ruff/src/rules/flake8_pyi/rules/unaliased_collections_abc_set_import.rs
  crates/ruff/src/rules/flake8_pyi/snapshots/ruff__rules__flake8_pyi__tests__PYI025_PYI025.py.snap
  crates/ruff/src/rules/flake8_pyi/snapshots/ruff__rules__flake8_pyi__tests__PYI025_PYI025.pyi.snap
  ruff.schema.json
Labels: rule

#4770 [`flake8-pyi`] Implement PYI053
  crates/ruff/resources/test/fixtures/flake8_pyi/PYI053.py
  crates/ruff/resources/test/fixtures/flake8_pyi/PYI053.pyi
  crates/ruff/src/checkers/ast/mod.rs
  crates/ruff/src/codes.rs
  crates/ruff/src/registry.rs
  crates/ruff/src/rules/flake8_pyi/mod.rs
  crates/ruff/src/rules/flake8_pyi/rules/mod.rs
  crates/ruff/src/rules/flake8_pyi/rules/simple_defaults.rs
  crates/ruff/src/rules/flake8_pyi/rules/string_or_bytes_too_long.rs
  crates/ruff/src/rules/flake8_pyi/snapshots/ruff__rules__flake8_pyi__tests__PYI053_PYI053.py.snap
  crates/ruff/src/rules/flake8_pyi/snapshots/ruff__rules__flake8_pyi__tests__PYI053_PYI053.pyi.snap
  ruff.schema.json
Labels: rule

#4775 [`flake8-pyi`] Implement PYI054
  crates/ruff/resources/test/fixtures/flake8_pyi/PYI054.py
  crates/ruff/resources/test/fixtures/flake8_pyi/PYI054.pyi
  crates/ruff/src/checkers/ast/mod.rs
  crates/ruff/src/codes.rs
  crates/ruff/src/registry.rs
  crates/ruff/src/rules/flake8_pyi/mod.rs
  crates/ruff/src/rules/flake8_pyi/rules/mod.rs
  crates/ruff/src/rules/flake8_pyi/rules/numeric_literal_too_long.rs
  crates/ruff/src/rules/flake8_pyi/rules/simple_defaults.rs
  crates/ruff/src/rules/flake8_pyi/rules/string_or_bytes_too_long.rs
  crates/ruff/src/rules/flake8_pyi/snapshots/ruff__rules__flake8_pyi__tests__PYI053_PYI053.pyi.snap
  crates/ruff/src/rules/flake8_pyi/snapshots/ruff__rules__flake8_pyi__tests__PYI054_PYI054.py.snap
  crates/ruff/src/rules/flake8_pyi/snapshots/ruff__rules__flake8_pyi__tests__PYI054_PYI054.pyi.snap
  ruff.schema.json
Labels: rule

#4764 Add PYI034 for `flake8-pyi` plugin
  crates/ruff/resources/test/fixtures/flake8_pyi/PYI034.py
  crates/ruff/resources/test/fixtures/flake8_pyi/PYI034.pyi
  crates/ruff/src/checkers/ast/mod.rs
  crates/ruff/src/codes.rs
  crates/ruff/src/registry.rs
  crates/ruff/src/rules/flake8_pyi/mod.rs
  crates/ruff/src/rules/flake8_pyi/rules/mod.rs
  crates/ruff/src/rules/flake8_pyi/rules/non_self_return_type.rs
  crates/ruff/src/rules/flake8_pyi/snapshots/ruff__rules__flake8_pyi__tests__PYI034_PYI034.py.snap
  crates/ruff/src/rules/flake8_pyi/snapshots/ruff__rules__flake8_pyi__tests__PYI034_PYI034.pyi.snap
  crates/ruff_python_ast/src/helpers.rs
  crates/ruff_python_semantic/src/analyze/visibility.rs
  crates/ruff_python_semantic/src/model.rs
  ruff.schema.json
Labels: rule

#4794 Exclude function definition from too-many-statements rule
  crates/ruff/src/rules/pylint/rules/too_many_statements.rs
  crates/ruff/src/rules/pylint/snapshots/ruff__rules__pylint__tests__PLR0915_too_many_statements.py.snap
  crates/ruff/src/rules/pylint/snapshots/ruff__rules__pylint__tests__max_statements.snap
Labels: bug

#4795 Move unused imports rule into its own module
  crates/ruff/src/checkers/ast/mod.rs
  crates/ruff/src/message/mod.rs
  crates/ruff/src/rules/pyflakes/rules/future_feature_not_defined.rs
  crates/ruff/src/rules/pyflakes/rules/imports.rs
  crates/ruff/src/rules/pyflakes/rules/mod.rs
  crates/ruff/src/rules/pyflakes/rules/undefined_name.rs
  crates/ruff/src/rules/pyflakes/rules/unused_import.rs
Labels: internal

#4796 Remove some matches on `Stmt`
  crates/ruff/src/rules/flake8_bugbear/rules/jump_statement_in_finally.rs
  crates/ruff/src/rules/flake8_simplify/rules/return_in_try_except_finally.rs
  crates/ruff/src/rules/pylint/rules/too_many_branches.rs
  crates/ruff/src/rules/pylint/rules/too_many_statements.rs
  crates/ruff/src/rules/pyupgrade/rules/super_call_with_parameters.rs
Labels: internal

#4797 Ignore error calls with `exc_info` in TRY400
  crates/ruff/resources/test/fixtures/tryceratops/TRY400.py
  crates/ruff/src/rules/flake8_logging_format/rules/logging_call.rs
  crates/ruff/src/rules/tryceratops/helpers.rs
  crates/ruff/src/rules/tryceratops/rules/error_instead_of_exception.rs
  crates/ruff/src/rules/tryceratops/rules/verbose_log_message.rs
  crates/ruff/src/rules/tryceratops/snapshots/ruff__rules__tryceratops__tests__error-instead-of-exception_TRY400.py.snap
  crates/ruff_python_semantic/src/analyze/logging.rs
Labels: rule

#4783 Add to `AnyNode` and `AnyNodeRef` conversion methods to `AstNode`
  crates/ruff_python_ast/src/node.rs
Labels: internal

#4785 Leading, Dangling, and Trailing comments formatting
  crates/ruff_formatter/src/source_code.rs
  crates/ruff_python_formatter/src/comments/format.rs
  crates/ruff_python_formatter/src/comments/mod.rs
  crates/ruff_python_formatter/src/context.rs
  crates/ruff_python_formatter/src/lib.rs
  crates/ruff_python_formatter/src/snapshots/ruff_python_formatter__tests__black_test__collections_py.snap
  crates/ruff_python_formatter/src/snapshots/ruff_python_formatter__tests__black_test__comments2_py.snap
  crates/ruff_python_formatter/src/snapshots/ruff_python_formatter__tests__black_test__comments3_py.snap
  crates/ruff_python_formatter/src/snapshots/ruff_python_formatter__tests__black_test__comments5_py.snap
  crates/ruff_python_formatter/src/snapshots/ruff_python_formatter__tests__black_test__comments6_py.snap
  crates/ruff_python_formatter/src/snapshots/ruff_python_formatter__tests__black_test__comments8_py.snap
  crates/ruff_python_formatter/src/snapshots/ruff_python_formatter__tests__black_test__comments9_py.snap
  crates/ruff_python_formatter/src/snapshots/ruff_python_formatter__tests__black_test__comments_non_breaking_space_py.snap
  crates/ruff_python_formatter/src/snapshots/ruff_python_formatter__tests__black_test__comments_py.snap
  crates/ruff_python_formatter/src/snapshots/ruff_python_formatter__tests__black_test__docstring_no_extra_empty_line_before_eof_py.snap
  crates/ruff_python_formatter/src/snapshots/ruff_python_formatter__tests__black_test__docstring_py.snap
  crates/ruff_python_formatter/src/snapshots/ruff_python_formatter__tests__black_test__empty_lines_py.snap
  crates/ruff_python_formatter/src/snapshots/ruff_python_formatter__tests__black_test__expression_py.snap
  crates/ruff_python_formatter/src/snapshots/ruff_python_formatter__tests__black_test__fmtonoff2_py.snap
  crates/ruff_python_formatter/src/snapshots/ruff_python_formatter__tests__black_test__fmtonoff3_py.snap
  crates/ruff_python_formatter/src/snapshots/ruff_python_formatter__tests__black_test__fmtonoff4_py.snap
  crates/ruff_python_formatter/src/snapshots/ruff_python_formatter__tests__black_test__fmtonoff5_py.snap
  crates/ruff_python_formatter/src/snapshots/ruff_python_formatter__tests__black_test__fmtonoff_py.snap
  crates/ruff_python_formatter/src/snapshots/ruff_python_formatter__tests__black_test__fmtskip2_py.snap
  crates/ruff_python_formatter/src/snapshots/ruff_python_formatter__tests__black_test__fmtskip3_py.snap
  crates/ruff_python_formatter/src/snapshots/ruff_python_formatter__tests__black_test__fmtskip4_py.snap
  crates/ruff_python_formatter/src/snapshots/ruff_python_formatter__tests__black_test__fmtskip6_py.snap
  crates/ruff_python_formatter/src/snapshots/ruff_python_formatter__tests__black_test__fmtskip7_py.snap
  crates/ruff_python_formatter/src/snapshots/ruff_python_formatter__tests__black_test__fmtskip8_py.snap
  crates/ruff_python_formatter/src/snapshots/ruff_python_formatter__tests__black_test__fmtskip_py.snap
  crates/ruff_python_formatter/src/snapshots/ruff_python_formatter__tests__black_test__function_py.snap
  crates/ruff_python_formatter/src/snapshots/ruff_python_formatter__tests__black_test__function_trailing_comma_py.snap
  crates/ruff_python_formatter/src/snapshots/ruff_python_formatter__tests__black_test__import_spacing_py.snap
  crates/ruff_python_formatter/src/snapshots/ruff_python_formatter__tests__black_test__one_element_subscript_py.snap
  crates/ruff_python_formatter/src/snapshots/ruff_python_formatter__tests__black_test__power_op_spacing_py.snap
  crates/ruff_python_formatter/src/snapshots/ruff_python_formatter__tests__black_test__prefer_rhs_split_reformatted_py.snap
  crates/ruff_python_formatter/src/snapshots/ruff_python_formatter__tests__black_test__remove_await_parens_py.snap
  crates/ruff_python_formatter/src/snapshots/ruff_python_formatter__tests__black_test__remove_except_parens_py.snap
  crates/ruff_python_formatter/src/snapshots/ruff_python_formatter__tests__black_test__remove_for_brackets_py.snap
  crates/ruff_python_formatter/src/snapshots/ruff_python_formatter__tests__black_test__return_annotation_brackets_py.snap
  crates/ruff_python_formatter/src/snapshots/ruff_python_formatter__tests__black_test__skip_magic_trailing_comma_py.snap
  crates/ruff_python_formatter/src/snapshots/ruff_python_formatter__tests__black_test__slices_py.snap
  crates/ruff_python_formatter/src/snapshots/ruff_python_formatter__tests__black_test__string_prefixes_py.snap
  crates/ruff_python_formatter/src/snapshots/ruff_python_formatter__tests__black_test__torture_py.snap
  crates/ruff_python_formatter/src/snapshots/ruff_python_formatter__tests__black_test__trailing_commas_in_leading_parts_py.snap
  crates/ruff_python_formatter/src/snapshots/ruff_python_formatter__tests__black_test__tupleassign_py.snap
  crates/ruff_python_formatter/src/trivia.rs
Labels: internal, autoformatter

#4786 Format the comment content
  crates/ruff_python_formatter/src/comments/format.rs
  crates/ruff_python_formatter/src/snapshots/ruff_python_formatter__tests__black_test__comments2_py.snap
  crates/ruff_python_formatter/src/snapshots/ruff_python_formatter__tests__black_test__comments8_py.snap
  crates/ruff_python_formatter/src/snapshots/ruff_python_formatter__tests__black_test__comments_non_breaking_space_py.snap
  crates/ruff_python_formatter/src/snapshots/ruff_python_formatter__tests__black_test__fmtskip7_py.snap
Labels: internal, autoformatter

#4788 Format StmtExpr
  crates/ruff_python_formatter/src/expression/mod.rs
  crates/ruff_python_formatter/src/snapshots/ruff_python_formatter__tests__black_test__comments_py.snap
  crates/ruff_python_formatter/src/snapshots/ruff_python_formatter__tests__black_test__expression_py.snap
  crates/ruff_python_formatter/src/statement/stmt_expr.rs
Labels: internal, autoformatter

#4805 Suite formatting and `JoinNodesBuilder`
  crates/ruff_python_formatter/src/builders.rs
  crates/ruff_python_formatter/src/lib.rs
  crates/ruff_python_formatter/src/prelude.rs
  crates/ruff_python_formatter/src/statement/mod.rs
  crates/ruff_python_formatter/src/statement/suite.rs
Labels: internal, autoformatter

#4504 Implement S609, linux_commands_wildcard_injection
  crates/ruff/resources/test/fixtures/flake8_bandit/S609.py
  crates/ruff/src/checkers/ast/mod.rs
  crates/ruff/src/codes.rs
  crates/ruff/src/rules/flake8_bandit/mod.rs
  crates/ruff/src/rules/flake8_bandit/rules/mod.rs
  crates/ruff/src/rules/flake8_bandit/rules/shell_injection.rs
  crates/ruff/src/rules/flake8_bandit/snapshots/ruff__rules__flake8_bandit__tests__S609_S609.py.snap
  ruff.schema.json
Labels: rule

#4811 Handle trailing body end-of-line comments
  crates/ruff_python_formatter/src/comments/mod.rs
  crates/ruff_python_formatter/src/comments/placement.rs
  crates/ruff_python_formatter/src/comments/snapshots/ruff_python_formatter__comments__tests__while_trailing_end_of_line_comment.snap
  crates/ruff_python_formatter/src/snapshots/ruff_python_formatter__tests__black_test__comments5_py.snap
  crates/ruff_python_formatter/src/snapshots/ruff_python_formatter__tests__black_test__comments6_py.snap
  crates/ruff_python_formatter/src/snapshots/ruff_python_formatter__tests__black_test__fmtonoff_py.snap
  crates/ruff_python_formatter/src/snapshots/ruff_python_formatter__tests__black_test__fmtskip6_py.snap
  crates/ruff_python_formatter/src/snapshots/ruff_python_formatter__tests__black_test__remove_await_parens_py.snap
Labels: internal, autoformatter

#4812 Handle trailing end-of-line comments in-between-bodies
  crates/ruff_python_formatter/src/comments/mod.rs
  crates/ruff_python_formatter/src/comments/placement.rs
  crates/ruff_python_formatter/src/comments/snapshots/ruff_python_formatter__comments__tests__while_trailing_else_end_of_line_comment.snap
Labels: internal, autoformatter

#4803 Format `ExprName`
  crates/ruff_python_formatter/src/expression/expr_name.rs
Labels: internal, autoformatter

#4836 Preserve quotes in F523 fixer
  crates/ruff/resources/test/fixtures/pyflakes/F523.py
  crates/ruff/src/rules/pyflakes/fixes.rs
  crates/ruff/src/rules/pyflakes/snapshots/ruff__rules__pyflakes__tests__F523_F523.py.snap
Labels: bug

#4848 Upgrade to Rust 1.70
  Cargo.toml
  rust-toolchain
Labels: internal

#4855 Invert structure of Scope#shadowed_bindings
  crates/ruff_python_semantic/src/scope.rs
Labels: internal

#4856 Remove codes import from rule_selector.rs
  crates/ruff/src/rule_selector.rs
Labels: internal

#4809 Add a formatter CLI for debugging
  crates/ruff_python_formatter/src/cli.rs
  crates/ruff_python_formatter/src/main.rs
Labels: internal, autoformatter

#4810 Format `while` Statement
  crates/ruff_python_formatter/resources/test/fixtures/ruff/statement/while.py
  crates/ruff_python_formatter/src/builders.rs
  crates/ruff_python_formatter/src/comments/format.rs
  crates/ruff_python_formatter/src/comments/mod.rs
  crates/ruff_python_formatter/src/comments/placement.rs
  crates/ruff_python_formatter/src/comments/snapshots/ruff_python_formatter__comments__tests__base_test.snap
  crates/ruff_python_formatter/src/context.rs
  crates/ruff_python_formatter/src/expression/maybe_parenthesize.rs
  crates/ruff_python_formatter/src/expression/mod.rs
  crates/ruff_python_formatter/src/lib.rs
  crates/ruff_python_formatter/src/snapshots/ruff_python_formatter__tests__black_test__comments5_py.snap
  crates/ruff_python_formatter/src/snapshots/ruff_python_formatter__tests__black_test__expression_py.snap
  crates/ruff_python_formatter/src/snapshots/ruff_python_formatter__tests__black_test__fmtskip8_py.snap
  crates/ruff_python_formatter/src/snapshots/ruff_python_formatter__tests__black_test__remove_newline_after_code_block_open_py.snap
  crates/ruff_python_formatter/src/snapshots/ruff_python_formatter__tests__ruff_test__while_py.snap
  crates/ruff_python_formatter/src/statement/stmt_while.rs
  crates/ruff_python_formatter/src/statement/suite.rs
  crates/ruff_python_formatter/src/trivia.rs
Labels: internal, autoformatter

#4808 Implement module formatting using JoinNodesBuilder
  crates/ruff_python_formatter/src/module/mod_module.rs
  crates/ruff_python_formatter/src/snapshots/ruff_python_formatter__tests__black_test__attribute_access_on_number_literals_py.snap
  crates/ruff_python_formatter/src/snapshots/ruff_python_formatter__tests__black_test__class_blank_parentheses_py.snap
  crates/ruff_python_formatter/src/snapshots/ruff_python_formatter__tests__black_test__class_methods_new_line_py.snap
  crates/ruff_python_formatter/src/snapshots/ruff_python_formatter__tests__black_test__collections_py.snap
  crates/ruff_python_formatter/src/snapshots/ruff_python_formatter__tests__black_test__comment_after_escaped_newline_py.snap
  crates/ruff_python_formatter/src/snapshots/ruff_python_formatter__tests__black_test__comments2_py.snap
  crates/ruff_python_formatter/src/snapshots/ruff_python_formatter__tests__black_test__comments4_py.snap
  crates/ruff_python_formatter/src/snapshots/ruff_python_formatter__tests__black_test__comments5_py.snap
  crates/ruff_python_formatter/src/snapshots/ruff_python_formatter__tests__black_test__comments6_py.snap
  crates/ruff_python_formatter/src/snapshots/ruff_python_formatter__tests__black_test__comments9_py.snap
  crates/ruff_python_formatter/src/snapshots/ruff_python_formatter__tests__black_test__comments_non_breaking_space_py.snap
  crates/ruff_python_formatter/src/snapshots/ruff_python_formatter__tests__black_test__comments_py.snap
  crates/ruff_python_formatter/src/snapshots/ruff_python_formatter__tests__black_test__docstring_preview_py.snap
  crates/ruff_python_formatter/src/snapshots/ruff_python_formatter__tests__black_test__docstring_py.snap
  crates/ruff_python_formatter/src/snapshots/ruff_python_formatter__tests__black_test__empty_lines_py.snap
  crates/ruff_python_formatter/src/snapshots/ruff_python_formatter__tests__black_test__expression_py.snap
  crates/ruff_python_formatter/src/snapshots/ruff_python_formatter__tests__black_test__fmtonoff2_py.snap
  crates/ruff_python_formatter/src/snapshots/ruff_python_formatter__tests__black_test__fmtonoff3_py.snap
  crates/ruff_python_formatter/src/snapshots/ruff_python_formatter__tests__black_test__fmtonoff4_py.snap
  crates/ruff_python_formatter/src/snapshots/ruff_python_formatter__tests__black_test__fmtonoff5_py.snap
  crates/ruff_python_formatter/src/snapshots/ruff_python_formatter__tests__black_test__fmtonoff_py.snap
  crates/ruff_python_formatter/src/snapshots/ruff_python_formatter__tests__black_test__fmtskip8_py.snap
  crates/ruff_python_formatter/src/snapshots/ruff_python_formatter__tests__black_test__function2_py.snap
  crates/ruff_python_formatter/src/snapshots/ruff_python_formatter__tests__black_test__function_py.snap
  crates/ruff_python_formatter/src/snapshots/ruff_python_formatter__tests__black_test__function_trailing_comma_py.snap
  crates/ruff_python_formatter/src/snapshots/ruff_python_formatter__tests__black_test__import_spacing_py.snap
  crates/ruff_python_formatter/src/snapshots/ruff_python_formatter__tests__black_test__power_op_spacing_py.snap
  crates/ruff_python_formatter/src/snapshots/ruff_python_formatter__tests__black_test__remove_await_parens_py.snap
  crates/ruff_python_formatter/src/snapshots/ruff_python_formatter__tests__black_test__remove_except_parens_py.snap
  crates/ruff_python_formatter/src/snapshots/ruff_python_formatter__tests__black_test__remove_for_brackets_py.snap
  crates/ruff_python_formatter/src/snapshots/ruff_python_formatter__tests__black_test__remove_newline_after_code_block_open_py.snap
  crates/ruff_python_formatter/src/snapshots/ruff_python_formatter__tests__black_test__remove_parens_py.snap
  crates/ruff_python_formatter/src/snapshots/ruff_python_formatter__tests__black_test__return_annotation_brackets_py.snap
  crates/ruff_python_formatter/src/snapshots/ruff_python_formatter__tests__black_test__skip_magic_trailing_comma_py.snap
  crates/ruff_python_formatter/src/snapshots/ruff_python_formatter__tests__black_test__slices_py.snap
  crates/ruff_python_formatter/src/snapshots/ruff_python_formatter__tests__black_test__string_prefixes_py.snap
  crates/ruff_python_formatter/src/snapshots/ruff_python_formatter__tests__black_test__torture_py.snap
  crates/ruff_python_formatter/src/snapshots/ruff_python_formatter__tests__black_test__trailing_comma_optional_parens1_py.snap
  crates/ruff_python_formatter/src/snapshots/ruff_python_formatter__tests__black_test__trailing_commas_in_leading_parts_py.snap
  crates/ruff_python_formatter/src/snapshots/ruff_python_formatter__tests__black_test__tricky_unicode_symbols_py.snap
  crates/ruff_python_formatter/src/snapshots/ruff_python_formatter__tests__black_test__tupleassign_py.snap
  crates/ruff_python_formatter/src/snapshots/ruff_python_formatter__tests__ruff_test__while_py.snap
Labels: internal, autoformatter

#4861 Ensure type_ignores for Module are empty
  crates/ruff_python_formatter/src/module/mod_module.rs
Labels: internal, autoformatter

#4854 implement E307 for pylint invalid str return type
  crates/ruff/resources/test/fixtures/pylint/invalid_return_type_str.py
  crates/ruff/src/checkers/ast/mod.rs
  crates/ruff/src/codes.rs
  crates/ruff/src/rules/flake8_annotations/rules/definition.rs
  crates/ruff/src/rules/pylint/mod.rs
  crates/ruff/src/rules/pylint/rules/invalid_str_return.rs
  crates/ruff/src/rules/pylint/rules/mod.rs
  crates/ruff/src/rules/pylint/snapshots/ruff__rules__pylint__tests__PLE0307_invalid_return_type_str.py.snap
  crates/ruff_python_ast/src/helpers.rs
  ruff.schema.json
Labels: rule

#4873 Use `qualified_name` terminology in more structs for consistency
  crates/ruff/src/autofix/codemods.rs
  crates/ruff/src/checkers/ast/mod.rs
  crates/ruff/src/importer/mod.rs
  crates/ruff/src/rules/flake8_type_checking/rules/runtime_import_in_type_checking_block.rs
  crates/ruff/src/rules/flake8_type_checking/rules/typing_only_runtime_import.rs
  crates/ruff/src/rules/pandas_vet/helpers.rs
  crates/ruff/src/rules/pandas_vet/rules/inplace_argument.rs
  crates/ruff/src/rules/pyflakes/rules/unused_import.rs
  crates/ruff/src/rules/pyupgrade/rules/deprecated_import.rs
  crates/ruff_python_ast/src/helpers.rs
  crates/ruff_python_semantic/src/binding.rs
  crates/ruff_python_semantic/src/model.rs
Labels: internal

#4874 Remove unused lifetime from UnusedImport type alias
  crates/ruff/src/rules/pyflakes/rules/unused_import.rs
Labels: internal

#4850 Normalize newlines in `verbatim_text`
  crates/ruff_python_formatter/src/lib.rs
Labels: internal, autoformatter

#4886 Avoid early-exit in explicit-f-string-type-conversion
  crates/ruff/resources/test/fixtures/ruff/RUF010.py
  crates/ruff/src/rules/ruff/rules/explicit_f_string_type_conversion.rs
  crates/ruff/src/rules/ruff/snapshots/ruff__rules__ruff__tests__RUF010_RUF010.py.snap
Labels: bug

#4876 Fix pre-commit typos action
  .pre-commit-config.yaml
  _typos.toml
Labels: internal

#4898 Introduce `AnyFunctionDefinition` Node
  crates/ruff_python_ast/src/function.rs
  crates/ruff_python_ast/src/lib.rs
Labels: internal

#4906 Avoid no-op fix for nested with expressions
  crates/ruff/resources/test/fixtures/pyflakes/F841_3.py
  crates/ruff/src/rules/pyflakes/rules/unused_variable.rs
  crates/ruff/src/rules/pyflakes/snapshots/ruff__rules__pyflakes__tests__F841_F841_3.py.snap
Labels: bug

#4912 Replace one-off locals property with `ScopeFlags`
  crates/ruff/src/checkers/ast/mod.rs
  crates/ruff/src/rules/pyflakes/rules/unused_variable.rs
  crates/ruff_python_semantic/src/scope.rs
Labels: internal

#4913 Add some more test coverage for `del` statements
  crates/ruff/src/rules/pyflakes/mod.rs
  crates/ruff/src/rules/pyflakes/snapshots/ruff__rules__pyflakes__tests__del_shadowed_global_import_in_global_scope.snap
  crates/ruff/src/rules/pyflakes/snapshots/ruff__rules__pyflakes__tests__del_shadowed_global_import_in_local_scope.snap
  crates/ruff/src/rules/pyflakes/snapshots/ruff__rules__pyflakes__tests__del_shadowed_local_import_in_local_scope.snap
Labels: internal

#4918 Clarify requires-python inference requirements
  crates/ruff/src/settings/options.rs
  ruff.schema.json
Labels: documentation

#4895 Correctly handle newlines after/before comments
  crates/ruff_python_formatter/resources/test/fixtures/ruff/trivia.py
  crates/ruff_python_formatter/src/builders.rs
  crates/ruff_python_formatter/src/lib.rs
  crates/ruff_python_formatter/src/snapshots/ruff_python_formatter__tests__black_test__collections_py.snap
  crates/ruff_python_formatter/src/snapshots/ruff_python_formatter__tests__black_test__fmtonoff3_py.snap
  crates/ruff_python_formatter/src/snapshots/ruff_python_formatter__tests__black_test__fmtonoff5_py.snap
  crates/ruff_python_formatter/src/snapshots/ruff_python_formatter__tests__black_test__function_trailing_comma_py.snap
  crates/ruff_python_formatter/src/snapshots/ruff_python_formatter__tests__black_test__import_spacing_py.snap
  crates/ruff_python_formatter/src/snapshots/ruff_python_formatter__tests__black_test__one_element_subscript_py.snap
  crates/ruff_python_formatter/src/snapshots/ruff_python_formatter__tests__black_test__power_op_spacing_py.snap
  crates/ruff_python_formatter/src/snapshots/ruff_python_formatter__tests__black_test__prefer_rhs_split_reformatted_py.snap
  crates/ruff_python_formatter/src/snapshots/ruff_python_formatter__tests__black_test__remove_for_brackets_py.snap
  crates/ruff_python_formatter/src/snapshots/ruff_python_formatter__tests__black_test__skip_magic_trailing_comma_py.snap
  crates/ruff_python_formatter/src/snapshots/ruff_python_formatter__tests__black_test__trailing_commas_in_leading_parts_py.snap
  crates/ruff_python_formatter/src/snapshots/ruff_python_formatter__tests__black_test__tupleassign_py.snap
  crates/ruff_python_formatter/src/snapshots/ruff_python_formatter__tests__ruff_test__expression__binary_expression_py.snap
  crates/ruff_python_formatter/src/snapshots/ruff_python_formatter__tests__ruff_test__trivia_py.snap
  crates/ruff_python_formatter/src/statement/suite.rs
  crates/ruff_python_formatter/src/trivia.rs
Labels: internal, autoformatter

#4822 Create fuzzers for testing correctness of parsing, linting and fixing
  .github/workflows/ci.yaml
  crates/ruff/src/lib.rs
  crates/ruff/src/test.rs
  fuzz/.gitignore
  fuzz/Cargo.lock
  fuzz/Cargo.toml
  fuzz/README.md
  fuzz/corpus/ruff_parse_idempotency
  fuzz/corpus/ruff_parse_simple
  fuzz/fuzz_targets/ruff_fix_validity.rs
  fuzz/fuzz_targets/ruff_parse_idempotency.rs
  fuzz/fuzz_targets/ruff_parse_simple.rs
  fuzz/init-fuzzer.sh
  fuzz/reinit-fuzzer.sh
Labels: internal

#4917 Move flake8-fixme rules to FIX prefix
  crates/ruff/src/registry.rs
  crates/ruff/src/rule_redirects.rs
  crates/ruff/src/rules/flake8_fixme/rules/todos.rs
  crates/ruff/src/rules/flake8_fixme/snapshots/ruff__rules__flake8_fixme__tests__line-contains-fixme_T00.py.snap
  crates/ruff/src/rules/flake8_fixme/snapshots/ruff__rules__flake8_fixme__tests__line-contains-hack_T00.py.snap
  crates/ruff/src/rules/flake8_fixme/snapshots/ruff__rules__flake8_fixme__tests__line-contains-todo_T00.py.snap
  crates/ruff/src/rules/flake8_fixme/snapshots/ruff__rules__flake8_fixme__tests__line-contains-xxx_T00.py.snap
  crates/ruff/src/rules/flake8_todos/rules/todos.rs
  ruff.schema.json
Labels: breaking

#4942 Avoid attributing runtime references to module-level imports
  crates/ruff/resources/test/fixtures/pyflakes/F401_17.py
  crates/ruff/src/rules/pyflakes/mod.rs
  crates/ruff/src/rules/pyflakes/snapshots/ruff__rules__pyflakes__tests__F401_F401_17.py.snap
  crates/ruff_python_semantic/src/model.rs
Labels: bug

#4943 Skip class scopes when resolving nonlocal references
  crates/ruff/resources/test/fixtures/pyflakes/F841_0.py
  crates/ruff/src/checkers/ast/mod.rs
Labels: bug

#4944 Apply `dict.get` fix before ternary rewrite
  crates/ruff/src/autofix/mod.rs
Labels: bug

#4947 Handle implicit string concatenations in conversion-flag rewrites
  crates/ruff/resources/test/fixtures/ruff/RUF010.py
  crates/ruff/src/cst/matchers.rs
  crates/ruff/src/rules/ruff/rules/explicit_f_string_type_conversion.rs
  crates/ruff/src/rules/ruff/snapshots/ruff__rules__ruff__tests__RUF010_RUF010.py.snap
Labels: bug

#4900 Upgrade RustPython
  Cargo.lock
  Cargo.toml
  crates/ruff/src/checkers/ast/mod.rs
  crates/ruff/src/rules/flake8_annotations/helpers.rs
  crates/ruff/src/rules/flake8_boolean_trap/rules/check_boolean_default_value_in_function_definition.rs
  crates/ruff/src/rules/flake8_boolean_trap/rules/check_positional_boolean_in_def.rs
  crates/ruff/src/rules/flake8_bugbear/rules/cached_instance_method.rs
  crates/ruff/src/rules/flake8_bugbear/snapshots/ruff__rules__flake8_bugbear__tests__B019_B019.py.snap
  crates/ruff/src/rules/flake8_django/rules/non_leading_receiver_decorator.rs
  crates/ruff/src/rules/flake8_django/snapshots/ruff__rules__flake8_django__tests__DJ013_DJ013.py.snap
  crates/ruff/src/rules/flake8_pyi/rules/non_self_return_type.rs
  crates/ruff/src/rules/flake8_pytest_style/rules/fixture.rs
  crates/ruff/src/rules/flake8_pytest_style/rules/helpers.rs
  crates/ruff/src/rules/flake8_pytest_style/rules/marks.rs
  crates/ruff/src/rules/flake8_pytest_style/rules/parametrize.rs
  crates/ruff/src/rules/flake8_pytest_style/snapshots/ruff__rules__flake8_pytest_style__tests__PT001_default.snap
  crates/ruff/src/rules/flake8_pytest_style/snapshots/ruff__rules__flake8_pytest_style__tests__PT001_no_parentheses.snap
  crates/ruff/src/rules/flake8_pytest_style/snapshots/ruff__rules__flake8_pytest_style__tests__PT002.snap
  crates/ruff/src/rules/flake8_pytest_style/snapshots/ruff__rules__flake8_pytest_style__tests__PT020.snap
  crates/ruff/src/rules/flake8_pytest_style/snapshots/ruff__rules__flake8_pytest_style__tests__PT023_default.snap
  crates/ruff/src/rules/flake8_pytest_style/snapshots/ruff__rules__flake8_pytest_style__tests__PT023_no_parentheses.snap
  crates/ruff/src/rules/flake8_pytest_style/snapshots/ruff__rules__flake8_pytest_style__tests__PT024.snap
  crates/ruff/src/rules/flake8_pytest_style/snapshots/ruff__rules__flake8_pytest_style__tests__PT025.snap
  crates/ruff/src/rules/flake8_pytest_style/snapshots/ruff__rules__flake8_pytest_style__tests__PT026.snap
  crates/ruff/src/rules/flake8_return/visitor.rs
  crates/ruff/src/rules/flake8_type_checking/helpers.rs
  crates/ruff/src/rules/pep8_naming/rules/invalid_first_argument_name_for_class_method.rs
  crates/ruff/src/rules/pep8_naming/rules/invalid_first_argument_name_for_method.rs
  crates/ruff/src/rules/pep8_naming/rules/invalid_function_name.rs
  crates/ruff/src/rules/pydocstyle/helpers.rs
  crates/ruff/src/rules/pylint/rules/property_with_parameters.rs
  crates/ruff/src/rules/pylint/rules/unexpected_special_method_signature.rs
  crates/ruff/src/rules/pyupgrade/rules/lru_cache_with_maxsize_none.rs
  crates/ruff/src/rules/pyupgrade/rules/lru_cache_without_parameters.rs
  crates/ruff/src/rules/ruff/rules/mutable_defaults_in_dataclass_fields.rs
  crates/ruff_python_ast/src/cast.rs
  crates/ruff_python_ast/src/comparable.rs
  crates/ruff_python_ast/src/function.rs
  crates/ruff_python_ast/src/helpers.rs
  crates/ruff_python_ast/src/node.rs
  crates/ruff_python_ast/src/source_code/generator.rs
  crates/ruff_python_ast/src/visitor.rs
  crates/ruff_python_ast/src/visitor/preorder.rs
  crates/ruff_python_formatter/src/comments/placement.rs
  crates/ruff_python_formatter/src/comments/snapshots/ruff_python_formatter__comments__tests__non_positional_arguments_slash_on_same_line.snap
  crates/ruff_python_formatter/src/comments/snapshots/ruff_python_formatter__comments__tests__non_positional_arguments_with_defaults.snap
  crates/ruff_python_formatter/src/comments/snapshots/ruff_python_formatter__comments__tests__positional_argument_only_comment.snap
  crates/ruff_python_formatter/src/comments/snapshots/ruff_python_formatter__comments__tests__positional_argument_only_comment_without_following_node.snap
  crates/ruff_python_formatter/src/comments/snapshots/ruff_python_formatter__comments__tests__positional_argument_only_leading_comma_comment.snap
  crates/ruff_python_semantic/src/analyze/function_type.rs
  crates/ruff_python_semantic/src/analyze/visibility.rs
Labels: internal, autoformatter

#4952 Implement Binary expression without `best_fitting`
  crates/ruff_python_formatter/src/expression/expr_bin_op.rs
Labels: internal, autoformatter

#4954 Add basic Constant formatting
  crates/ruff_python_formatter/src/builders.rs
  crates/ruff_python_formatter/src/expression/expr_attribute.rs
  crates/ruff_python_formatter/src/expression/expr_bool_op.rs
  crates/ruff_python_formatter/src/expression/expr_call.rs
  crates/ruff_python_formatter/src/expression/expr_compare.rs
  crates/ruff_python_formatter/src/expression/expr_constant.rs
  crates/ruff_python_formatter/src/expression/expr_dict.rs
  crates/ruff_python_formatter/src/expression/expr_dict_comp.rs
  crates/ruff_python_formatter/src/expression/expr_generator_exp.rs
  crates/ruff_python_formatter/src/expression/expr_if_exp.rs
  crates/ruff_python_formatter/src/expression/expr_lambda.rs
  crates/ruff_python_formatter/src/expression/expr_list_comp.rs
  crates/ruff_python_formatter/src/expression/expr_slice.rs
  crates/ruff_python_formatter/src/expression/expr_subscript.rs
  crates/ruff_python_formatter/src/expression/expr_tuple.rs
  crates/ruff_python_formatter/src/lib.rs
  crates/ruff_python_formatter/src/snapshots/ruff_python_formatter__tests__black_test__attribute_access_on_number_literals_py.snap
  crates/ruff_python_formatter/src/snapshots/ruff_python_formatter__tests__black_test__collections_py.snap
  crates/ruff_python_formatter/src/snapshots/ruff_python_formatter__tests__black_test__comments2_py.snap
  crates/ruff_python_formatter/src/snapshots/ruff_python_formatter__tests__black_test__comments5_py.snap
  crates/ruff_python_formatter/src/snapshots/ruff_python_formatter__tests__black_test__comments6_py.snap
  crates/ruff_python_formatter/src/snapshots/ruff_python_formatter__tests__black_test__comments_non_breaking_space_py.snap
  crates/ruff_python_formatter/src/snapshots/ruff_python_formatter__tests__black_test__comments_py.snap
  crates/ruff_python_formatter/src/snapshots/ruff_python_formatter__tests__black_test__empty_lines_py.snap
  crates/ruff_python_formatter/src/snapshots/ruff_python_formatter__tests__black_test__expression_py.snap
  crates/ruff_python_formatter/src/snapshots/ruff_python_formatter__tests__black_test__fmtonoff2_py.snap
  crates/ruff_python_formatter/src/snapshots/ruff_python_formatter__tests__black_test__fmtonoff3_py.snap
  crates/ruff_python_formatter/src/snapshots/ruff_python_formatter__tests__black_test__fmtonoff_py.snap
  crates/ruff_python_formatter/src/snapshots/ruff_python_formatter__tests__black_test__fmtskip2_py.snap
  crates/ruff_python_formatter/src/snapshots/ruff_python_formatter__tests__black_test__fmtskip3_py.snap
  crates/ruff_python_formatter/src/snapshots/ruff_python_formatter__tests__black_test__fmtskip4_py.snap
  crates/ruff_python_formatter/src/snapshots/ruff_python_formatter__tests__black_test__fmtskip7_py.snap
  crates/ruff_python_formatter/src/snapshots/ruff_python_formatter__tests__black_test__fmtskip_py.snap
  crates/ruff_python_formatter/src/snapshots/ruff_python_formatter__tests__black_test__import_spacing_py.snap
  crates/ruff_python_formatter/src/snapshots/ruff_python_formatter__tests__black_test__one_element_subscript_py.snap
  crates/ruff_python_formatter/src/snapshots/ruff_python_formatter__tests__black_test__power_op_spacing_py.snap
  crates/ruff_python_formatter/src/snapshots/ruff_python_formatter__tests__black_test__prefer_rhs_split_reformatted_py.snap
  crates/ruff_python_formatter/src/snapshots/ruff_python_formatter__tests__black_test__remove_newline_after_code_block_open_py.snap
  crates/ruff_python_formatter/src/snapshots/ruff_python_formatter__tests__black_test__remove_parens_py.snap
  crates/ruff_python_formatter/src/snapshots/ruff_python_formatter__tests__black_test__skip_magic_trailing_comma_py.snap
  crates/ruff_python_formatter/src/snapshots/ruff_python_formatter__tests__black_test__string_prefixes_py.snap
  crates/ruff_python_formatter/src/snapshots/ruff_python_formatter__tests__black_test__torture_py.snap
  crates/ruff_python_formatter/src/snapshots/ruff_python_formatter__tests__black_test__tricky_unicode_symbols_py.snap
  crates/ruff_python_formatter/src/snapshots/ruff_python_formatter__tests__ruff_test__statement__stmt_assign_py.snap
  crates/ruff_python_formatter/src/snapshots/ruff_python_formatter__tests__ruff_test__statement__while_py.snap
  crates/ruff_python_formatter/src/snapshots/ruff_python_formatter__tests__ruff_test__trivia_py.snap
  crates/ruff_python_formatter/src/statement/suite.rs
Labels: internal, autoformatter

#4921 Trailing own line comments before func or class
  crates/ruff_python_formatter/src/comments/placement.rs
  crates/ruff_python_formatter/src/snapshots/ruff_python_formatter__tests__black_test__comments9_py.snap
  crates/ruff_python_formatter/src/snapshots/ruff_python_formatter__tests__black_test__fmtonoff2_py.snap
  crates/ruff_python_formatter/src/snapshots/ruff_python_formatter__tests__black_test__fmtonoff_py.snap
Labels: internal, autoformatter

#4959 Implement StmtPass
  crates/ruff_python_formatter/src/snapshots/ruff_python_formatter__tests__ruff_test__statement__while_py.snap
  crates/ruff_python_formatter/src/statement/stmt_pass.rs
Labels: autoformatter

#4922 Simple lexer for formatter
  crates/ruff_python_formatter/src/comments/placement.rs
  crates/ruff_python_formatter/src/expression/parentheses.rs
  crates/ruff_python_formatter/src/snapshots/ruff_python_formatter__trivia__tests__Reverse.snap
  crates/ruff_python_formatter/src/snapshots/ruff_python_formatter__trivia__tests__tokenize_bogus.snap
  crates/ruff_python_formatter/src/snapshots/ruff_python_formatter__trivia__tests__tokenize_comma.snap
  crates/ruff_python_formatter/src/snapshots/ruff_python_formatter__trivia__tests__tokenize_continuation.snap
  crates/ruff_python_formatter/src/snapshots/ruff_python_formatter__trivia__tests__tokenize_parentheses.snap
  crates/ruff_python_formatter/src/snapshots/ruff_python_formatter__trivia__tests__tokenize_slash.snap
  crates/ruff_python_formatter/src/snapshots/ruff_python_formatter__trivia__tests__tokenize_substring.snap
  crates/ruff_python_formatter/src/snapshots/ruff_python_formatter__trivia__tests__tokenize_trivia.snap
  crates/ruff_python_formatter/src/trivia.rs
Labels: internal, autoformatter

#4971 Upgrade explicit-type-conversion rule (`RUF010`) to remove unnecessary `str` calls
  crates/ruff/resources/test/fixtures/ruff/RUF010.py
  crates/ruff/src/rules/ruff/rules/explicit_f_string_type_conversion.rs
  crates/ruff/src/rules/ruff/snapshots/ruff__rules__ruff__tests__RUF010_RUF010.py.snap
Labels: rule

#4957 Add Pylint rule `comparison-with-itself` (`R0124`)
  crates/ruff/resources/test/fixtures/pylint/comparison_with_itself.py
  crates/ruff/src/checkers/ast/mod.rs
  crates/ruff/src/codes.rs
  crates/ruff/src/rules/pylint/helpers.rs
  crates/ruff/src/rules/pylint/mod.rs
  crates/ruff/src/rules/pylint/rules/comparison_of_constant.rs
  crates/ruff/src/rules/pylint/rules/comparison_with_itself.rs
  crates/ruff/src/rules/pylint/rules/mod.rs
  crates/ruff/src/rules/pylint/snapshots/ruff__rules__pylint__tests__PLR0124_comparison_with_itself.py.snap
  ruff.schema.json
Labels: rule

#4930 Complete `flake8-simplify` documentation
  crates/ruff/src/rules/flake8_simplify/rules/ast_bool_op.rs
  crates/ruff/src/rules/flake8_simplify/rules/ast_expr.rs
  crates/ruff/src/rules/flake8_simplify/rules/ast_if.rs
  crates/ruff/src/rules/flake8_simplify/rules/ast_ifexp.rs
  crates/ruff/src/rules/flake8_simplify/rules/ast_unary_op.rs
  crates/ruff/src/rules/flake8_simplify/rules/key_in_dict.rs
  crates/ruff/src/rules/flake8_simplify/rules/reimplemented_builtin.rs
  crates/ruff/src/rules/flake8_simplify/rules/suppressible_exception.rs
  crates/ruff/src/rules/flake8_simplify/rules/yoda_conditions.rs
Labels: documentation

#4929 [`ruff`] Add a rule for static keys in dict comprehensions
  crates/ruff/resources/test/fixtures/ruff/RUF011.py
  crates/ruff/src/checkers/ast/mod.rs
  crates/ruff/src/codes.rs
  crates/ruff/src/rules/ruff/mod.rs
  crates/ruff/src/rules/ruff/rules/mod.rs
  crates/ruff/src/rules/ruff/rules/static_key_dict_comprehension.rs
  crates/ruff/src/rules/ruff/snapshots/ruff__rules__ruff__tests__RUF011_RUF011.py.snap
  ruff.schema.json
Labels: rule

#4909 [`flake8-slots`] Add plugin, add `SLOT000`, `SLOT001` and `SLOT002`
  LICENSE
  README.md
  crates/ruff/resources/test/fixtures/flake8_slots/SLOT000.py
  crates/ruff/resources/test/fixtures/flake8_slots/SLOT001.py
  crates/ruff/resources/test/fixtures/flake8_slots/SLOT002.py
  crates/ruff/src/checkers/ast/mod.rs
  crates/ruff/src/codes.rs
  crates/ruff/src/registry.rs
  crates/ruff/src/rules/flake8_slots/mod.rs
  crates/ruff/src/rules/flake8_slots/rules/helpers.rs
  crates/ruff/src/rules/flake8_slots/rules/mod.rs
  crates/ruff/src/rules/flake8_slots/rules/no_slots_in_namedtuple_subclass.rs
  crates/ruff/src/rules/flake8_slots/rules/no_slots_in_str_subclass.rs
  crates/ruff/src/rules/flake8_slots/rules/no_slots_in_tuple_subclass.rs
  crates/ruff/src/rules/flake8_slots/snapshots/ruff__rules__flake8_slots__tests__SLOT000_SLOT000.py.snap
  crates/ruff/src/rules/flake8_slots/snapshots/ruff__rules__flake8_slots__tests__SLOT001_SLOT001.py.snap
  crates/ruff/src/rules/flake8_slots/snapshots/ruff__rules__flake8_slots__tests__SLOT002_SLOT002.py.snap
  crates/ruff/src/rules/mod.rs
  docs/faq.md
  ruff.schema.json
Labels: rule, plugin

#4563 Handled dict and set inside f-string (#4249)
  crates/ruff/resources/test/fixtures/flake8_comprehensions/C401.py
  crates/ruff/resources/test/fixtures/flake8_comprehensions/C402.py
  crates/ruff/resources/test/fixtures/flake8_comprehensions/C403.py
  crates/ruff/resources/test/fixtures/flake8_comprehensions/C404.py
  crates/ruff/resources/test/fixtures/flake8_comprehensions/C405.py
  crates/ruff/resources/test/fixtures/flake8_comprehensions/C408.py
  crates/ruff/src/checkers/ast/mod.rs
  crates/ruff/src/rules/flake8_comprehensions/fixes.rs
  crates/ruff/src/rules/flake8_comprehensions/rules/unnecessary_collection_call.rs
  crates/ruff/src/rules/flake8_comprehensions/rules/unnecessary_generator_dict.rs
  crates/ruff/src/rules/flake8_comprehensions/rules/unnecessary_generator_set.rs
  crates/ruff/src/rules/flake8_comprehensions/rules/unnecessary_list_comprehension_dict.rs
  crates/ruff/src/rules/flake8_comprehensions/rules/unnecessary_list_comprehension_set.rs
  crates/ruff/src/rules/flake8_comprehensions/rules/unnecessary_literal_dict.rs
  crates/ruff/src/rules/flake8_comprehensions/rules/unnecessary_literal_set.rs
  crates/ruff/src/rules/flake8_comprehensions/snapshots/ruff__rules__flake8_comprehensions__tests__C401_C401.py.snap
  crates/ruff/src/rules/flake8_comprehensions/snapshots/ruff__rules__flake8_comprehensions__tests__C402_C402.py.snap
  crates/ruff/src/rules/flake8_comprehensions/snapshots/ruff__rules__flake8_comprehensions__tests__C403_C403.py.snap
  crates/ruff/src/rules/flake8_comprehensions/snapshots/ruff__rules__flake8_comprehensions__tests__C404_C404.py.snap
  crates/ruff/src/rules/flake8_comprehensions/snapshots/ruff__rules__flake8_comprehensions__tests__C405_C405.py.snap
  crates/ruff/src/rules/flake8_comprehensions/snapshots/ruff__rules__flake8_comprehensions__tests__C408_C408.py.snap
  crates/ruff/src/rules/flake8_comprehensions/snapshots/ruff__rules__flake8_comprehensions__tests__C408_C408.py_allow_dict_calls_with_keyword_arguments.snap
  crates/ruff_python_semantic/src/model.rs
  fuzz/init-fuzzer.sh
  fuzz/reinit-fuzzer.sh
Labels: bug

#4976 Support concatenated string key removals
  crates/ruff/resources/test/fixtures/pyflakes/F504.py
  crates/ruff/src/rules/pyflakes/fixes.rs
  crates/ruff/src/rules/pyflakes/rules/strings.rs
  crates/ruff/src/rules/pyflakes/snapshots/ruff__rules__pyflakes__tests__F504_F504.py.snap
Labels: bug

#4977 Respect 'is not' operators split across newlines
  crates/ruff/resources/test/fixtures/pyflakes/F632.py
  crates/ruff/src/rules/pyflakes/snapshots/ruff__rules__pyflakes__tests__F632_F632.py.snap
  crates/ruff_python_ast/src/helpers.rs
Labels: bug

#4961 Format `if` statements
  crates/ruff_python_formatter/resources/test/fixtures/ruff/statement/if_statement.py
  crates/ruff_python_formatter/src/comments/placement.rs
  crates/ruff_python_formatter/src/lib.rs
  crates/ruff_python_formatter/src/snapshots/ruff_python_formatter__tests__black_test__attribute_access_on_number_literals_py.snap
  crates/ruff_python_formatter/src/snapshots/ruff_python_formatter__tests__black_test__collections_py.snap
  crates/ruff_python_formatter/src/snapshots/ruff_python_formatter__tests__black_test__comments2_py.snap
  crates/ruff_python_formatter/src/snapshots/ruff_python_formatter__tests__black_test__comments3_py.snap
  crates/ruff_python_formatter/src/snapshots/ruff_python_formatter__tests__black_test__comments5_py.snap
  crates/ruff_python_formatter/src/snapshots/ruff_python_formatter__tests__black_test__comments9_py.snap
  crates/ruff_python_formatter/src/snapshots/ruff_python_formatter__tests__black_test__comments_py.snap
  crates/ruff_python_formatter/src/snapshots/ruff_python_formatter__tests__black_test__empty_lines_py.snap
  crates/ruff_python_formatter/src/snapshots/ruff_python_formatter__tests__black_test__expression_py.snap
  crates/ruff_python_formatter/src/snapshots/ruff_python_formatter__tests__black_test__fmtonoff5_py.snap
  crates/ruff_python_formatter/src/snapshots/ruff_python_formatter__tests__black_test__fmtonoff_py.snap
  crates/ruff_python_formatter/src/snapshots/ruff_python_formatter__tests__black_test__fmtskip5_py.snap
  crates/ruff_python_formatter/src/snapshots/ruff_python_formatter__tests__black_test__fmtskip8_py.snap
  crates/ruff_python_formatter/src/snapshots/ruff_python_formatter__tests__black_test__function2_py.snap
  crates/ruff_python_formatter/src/snapshots/ruff_python_formatter__tests__black_test__function_py.snap
  crates/ruff_python_formatter/src/snapshots/ruff_python_formatter__tests__black_test__function_trailing_comma_py.snap
  crates/ruff_python_formatter/src/snapshots/ruff_python_formatter__tests__black_test__power_op_spacing_py.snap
  crates/ruff_python_formatter/src/snapshots/ruff_python_formatter__tests__black_test__remove_newline_after_code_block_open_py.snap
  crates/ruff_python_formatter/src/snapshots/ruff_python_formatter__tests__black_test__trailing_comma_optional_parens1_py.snap
  crates/ruff_python_formatter/src/snapshots/ruff_python_formatter__tests__black_test__trailing_comma_optional_parens2_py.snap
  crates/ruff_python_formatter/src/snapshots/ruff_python_formatter__tests__black_test__trailing_comma_optional_parens3_py.snap
  crates/ruff_python_formatter/src/snapshots/ruff_python_formatter__tests__ruff_test__statement__if_statement_py.snap
  crates/ruff_python_formatter/src/statement/stmt_if.rs
Labels: internal, autoformatter

#4964 Fix binary expression formatting with leading comments
  crates/ruff_python_formatter/resources/test/fixtures/ruff/expression/binary_expression.py
  crates/ruff_python_formatter/src/expression/expr_bin_op.rs
  crates/ruff_python_formatter/src/snapshots/ruff_python_formatter__tests__ruff_test__expression__binary_expression_py.snap
Labels: internal, autoformatter

#4979 Track formatted comments
  crates/ruff_python_formatter/src/comments/debug.rs
  crates/ruff_python_formatter/src/comments/format.rs
  crates/ruff_python_formatter/src/comments/mod.rs
  crates/ruff_python_formatter/src/comments/visitor.rs
  crates/ruff_python_formatter/src/other/arg.rs
  crates/ruff_python_formatter/src/other/arguments.rs
Labels: internal, autoformatter

#4978 perf(formatter): Skip bodies without comments
  crates/ruff_python_formatter/src/comments/visitor.rs
Labels: internal, performance, autoformatter

#4989 Add documentation for `BindingKind` variants
  crates/ruff/src/checkers/ast/mod.rs
  crates/ruff/src/rules/pandas_vet/helpers.rs
  crates/ruff_python_semantic/src/binding.rs
Labels: documentation

#4990 Rename some methods on `SemanticModel`
  crates/ruff/src/checkers/ast/mod.rs
  crates/ruff/src/rules/flake8_type_checking/helpers.rs
  crates/ruff/src/rules/flake8_type_checking/rules/runtime_import_in_type_checking_block.rs
  crates/ruff/src/rules/flake8_type_checking/rules/typing_only_runtime_import.rs
  crates/ruff/src/rules/pyflakes/rules/undefined_local.rs
  crates/ruff_python_semantic/src/model.rs
Labels: internal

#4995 Use super visibility in helpers
  crates/ruff/src/rules/flake8_bandit/helpers.rs
  crates/ruff/src/rules/flake8_comprehensions/rules/helpers.rs
  crates/ruff/src/rules/flake8_django/rules/helpers.rs
  crates/ruff/src/rules/flake8_return/helpers.rs
  crates/ruff/src/rules/flynt/helpers.rs
  crates/ruff/src/rules/isort/helpers.rs
  crates/ruff/src/rules/pandas_vet/helpers.rs
  crates/ruff/src/rules/pep8_naming/helpers.rs
  crates/ruff/src/rules/pydocstyle/helpers.rs
  crates/ruff/src/rules/pylint/helpers.rs
  crates/ruff/src/rules/pyupgrade/helpers.rs
  crates/ruff/src/rules/tryceratops/helpers.rs
Labels: internal

#4997 Refactor `RET504` to only enforce assignment-then-return pattern
  crates/ruff/src/rules/flake8_return/helpers.rs
  crates/ruff/src/rules/flake8_return/rules/function.rs
  crates/ruff/src/rules/flake8_return/snapshots/ruff__rules__flake8_return__tests__RET501_RET501.py.snap
  crates/ruff/src/rules/flake8_return/snapshots/ruff__rules__flake8_return__tests__RET502_RET502.py.snap
  crates/ruff/src/rules/flake8_return/snapshots/ruff__rules__flake8_return__tests__RET504_RET504.py.snap
  crates/ruff/src/rules/flake8_return/visitor.rs
  crates/ruff_python_ast/src/helpers.rs
Labels: rule

#4998 Extend revised `RET504` implementation to `with` statements
  crates/ruff/resources/test/fixtures/flake8_return/RET504.py
  crates/ruff/src/rules/flake8_return/rules/function.rs
  crates/ruff/src/rules/flake8_return/snapshots/ruff__rules__flake8_return__tests__RET504_RET504.py.snap
  crates/ruff/src/rules/flake8_return/visitor.rs
Labels: rule

#5001 Parenthesize expressions prior to lexing in F632
  crates/ruff/resources/test/fixtures/pyflakes/F632.py
  crates/ruff/src/checkers/ast/mod.rs
  crates/ruff/src/rules/pyflakes/rules/invalid_literal_comparisons.rs
  crates/ruff/src/rules/pyflakes/snapshots/ruff__rules__pyflakes__tests__F632_F632.py.snap
  crates/ruff_python_ast/src/helpers.rs
Labels: bug

#4999 Implement autofix for revised `RET504` rule
  crates/ruff/resources/test/fixtures/flake8_return/RET504.py
  crates/ruff/src/rules/flake8_return/rules/function.rs
  crates/ruff/src/rules/flake8_return/snapshots/ruff__rules__flake8_return__tests__RET504_RET504.py.snap
  crates/ruff/src/rules/flake8_return/visitor.rs
Labels: rule, autofix

#5002 Use `Stmt::parse` in lieu of `Suite` unwraps
  crates/ruff_python_ast/src/helpers.rs
  crates/ruff_python_ast/src/source_code/generator.rs
Labels: internal

#5007 Add more details to E722 (bare-except) docs
  crates/ruff/src/rules/pycodestyle/rules/bare_except.rs
Labels: documentation

#4701 Implement copyright notice detection
  README.md
  crates/ruff/src/checkers/physical_lines.rs
  crates/ruff/src/codes.rs
  crates/ruff/src/registry.rs
  crates/ruff/src/rules/copyright/mod.rs
  crates/ruff/src/rules/copyright/rules/missing_copyright_notice.rs
  crates/ruff/src/rules/copyright/rules/mod.rs
  crates/ruff/src/rules/copyright/settings.rs
  crates/ruff/src/rules/copyright/snapshots/ruff__rules__copyright__tests__invalid_author.snap
  crates/ruff/src/rules/copyright/snapshots/ruff__rules__copyright__tests__late_notice.snap
  crates/ruff/src/rules/copyright/snapshots/ruff__rules__copyright__tests__notice.snap
  crates/ruff/src/rules/copyright/snapshots/ruff__rules__copyright__tests__notice_with_c.snap
  crates/ruff/src/rules/copyright/snapshots/ruff__rules__copyright__tests__notice_with_caps.snap
  crates/ruff/src/rules/copyright/snapshots/ruff__rules__copyright__tests__notice_with_range.snap
  crates/ruff/src/rules/copyright/snapshots/ruff__rules__copyright__tests__small_file.snap
  crates/ruff/src/rules/copyright/snapshots/ruff__rules__copyright__tests__valid_author.snap
  crates/ruff/src/rules/mod.rs
  crates/ruff/src/settings/configuration.rs
  crates/ruff/src/settings/defaults.rs
  crates/ruff/src/settings/mod.rs
  crates/ruff/src/settings/options.rs
  crates/ruff_macros/src/rule_namespace.rs
  crates/ruff_wasm/src/lib.rs
  docs/faq.md
  ruff.schema.json
  scripts/pyproject.toml
Labels: plugin

#5015 Use consistent `Cargo.toml` metadata in all crates
  Cargo.toml
  crates/flake8_to_ruff/Cargo.toml
  crates/ruff/Cargo.toml
  crates/ruff_benchmark/Cargo.toml
  crates/ruff_cache/Cargo.toml
  crates/ruff_cli/Cargo.toml
  crates/ruff_dev/Cargo.toml
  crates/ruff_diagnostics/Cargo.toml
  crates/ruff_formatter/Cargo.toml
  crates/ruff_index/Cargo.toml
  crates/ruff_macros/Cargo.toml
  crates/ruff_python_ast/Cargo.toml
  crates/ruff_python_formatter/Cargo.toml
  crates/ruff_python_semantic/Cargo.toml
  crates/ruff_python_stdlib/Cargo.toml
  crates/ruff_python_whitespace/Cargo.toml
  crates/ruff_rustpython/Cargo.toml
  crates/ruff_testing_macros/Cargo.toml
  crates/ruff_textwrap/Cargo.toml
  crates/ruff_wasm/Cargo.toml
Labels: internal

#5017 Update CONTRIBUTING.md guide
  CONTRIBUTING.md
  crates/ruff/src/checkers/ast/mod.rs
  crates/ruff/src/codes.rs
  crates/ruff/src/rules/flake8_bugbear/mod.rs
  crates/ruff/src/rules/flake8_bugbear/rules/mod.rs
  crates/ruff/src/rules/flake8_bugbear/rules/raise_literal.rs
Labels: documentation

#5013 Ignore pyproject.toml for adding noqa directives
  crates/ruff_cli/src/commands/add_noqa.rs
Labels: bug

#5032 Add a rule to remove unnecessary parentheses in class definitions
  crates/ruff/resources/test/fixtures/pyupgrade/UP039.py
  crates/ruff/src/checkers/ast/mod.rs
  crates/ruff/src/codes.rs
  crates/ruff/src/rules/pyupgrade/mod.rs
  crates/ruff/src/rules/pyupgrade/rules/mod.rs
  crates/ruff/src/rules/pyupgrade/rules/unnecessary_class_parentheses.rs
  crates/ruff/src/rules/pyupgrade/snapshots/ruff__rules__pyupgrade__tests__UP039.py.snap
  ruff.schema.json
  scripts/check_docs_formatted.py
Labels: rule

#4853 Autofixer for ISC001
  crates/ruff/resources/test/fixtures/flake8_implicit_str_concat/ISC.py
  crates/ruff/src/rules/flake8_implicit_str_concat/rules/implicit.rs
  crates/ruff/src/rules/flake8_implicit_str_concat/snapshots/ruff__rules__flake8_implicit_str_concat__tests__ISC001_ISC.py.snap
  crates/ruff/src/rules/flake8_implicit_str_concat/snapshots/ruff__rules__flake8_implicit_str_concat__tests__multiline_ISC001_ISC.py.snap
Labels: autofix

#5040 Support 'reason' argument to `pytest.fail`
  crates/ruff/resources/test/fixtures/flake8_pytest_style/PT016.py
  crates/ruff/src/rules/flake8_pytest_style/rules/fail.rs
  crates/ruff/src/rules/flake8_pytest_style/rules/unittest_assert.rs
  crates/ruff/src/rules/flake8_pytest_style/snapshots/ruff__rules__flake8_pytest_style__tests__PT016.snap
Labels: bug

#5041 Increase density of `Checker` arms
  crates/ruff/src/checkers/ast/mod.rs
Labels: internal

#4821 [`perflint`] Add `perflint` plugin, add first rule `PERF102`
  LICENSE
  crates/ruff/resources/test/fixtures/perflint/PERF102.py
  crates/ruff/src/checkers/ast/mod.rs
  crates/ruff/src/codes.rs
  crates/ruff/src/registry.rs
  crates/ruff/src/rules/mod.rs
  crates/ruff/src/rules/perflint/mod.rs
  crates/ruff/src/rules/perflint/rules/incorrect_dict_iterator.rs
  crates/ruff/src/rules/perflint/rules/mod.rs
  crates/ruff/src/rules/perflint/snapshots/ruff__rules__perflint__tests__PERF102_PERF102.py.snap
  docs/faq.md
  ruff.schema.json
Labels: rule

#5042 Use dedicated structs in `comparable.rs`
  crates/ruff_python_ast/src/comparable.rs
  crates/ruff_python_formatter/src/pattern/pattern_match_value.rs
Labels: internal

#5023 Add contributor docs to formatter
  crates/ruff_python_formatter/Docs.md
  crates/ruff_python_formatter/README.md
Labels: documentation

#5049 Remove unannotated attributes from RUF008
  crates/ruff/resources/test/fixtures/ruff/RUF008.py
  crates/ruff/resources/test/fixtures/ruff/RUF012.py
  crates/ruff/src/rules/ruff/rules/function_call_in_dataclass_default.rs
  crates/ruff/src/rules/ruff/rules/mutable_class_default.rs
  crates/ruff/src/rules/ruff/rules/mutable_dataclass_default.rs
  crates/ruff/src/rules/ruff/snapshots/ruff__rules__ruff__tests__RUF008_RUF008.py.snap
  crates/ruff/src/rules/ruff/snapshots/ruff__rules__ruff__tests__RUF012_RUF012.py.snap
Labels: rule

#5051 Use `Scope#has` in lieu of `Scope#get`
  crates/ruff_python_semantic/src/model.rs
Labels: internal

#5053 Use `.is_unbound()` in flake8-errmsg fix
  crates/ruff/src/rules/flake8_errmsg/rules/string_in_exception.rs
Labels: internal

#5058 Add a few more tests for deletion behaviors
  crates/ruff/src/rules/pyflakes/mod.rs
  crates/ruff/src/rules/pyflakes/snapshots/ruff__rules__pyflakes__tests__augmented_assignment_after_del.snap
  crates/ruff/src/rules/pyflakes/snapshots/ruff__rules__pyflakes__tests__del_shadowed_import_shadow_in_local_scope.snap
Labels: internal

#5065 Use dedicated structs for excepthandler variants
  crates/ruff_python_ast/src/comparable.rs
Labels: internal

#5068 Fix erroneous kwarg reference
  crates/ruff_python_ast/src/comparable.rs
Labels: internal

#5069 Tweak exception-handler handling in AST visitor
  crates/ruff/src/checkers/ast/mod.rs
  crates/ruff/src/rules/pyflakes/snapshots/ruff__rules__pyflakes__tests__F841_F841_0.py.snap
  crates/ruff/src/rules/pyflakes/snapshots/ruff__rules__pyflakes__tests__F841_F841_3.py.snap
  crates/ruff/src/rules/pyflakes/snapshots/ruff__rules__pyflakes__tests__f841_dummy_variable_rgx.snap
  crates/ruff/src/rules/pyflakes/snapshots/ruff__rules__pyflakes__tests__print_after_shadowing_except.snap
Labels: internal

#5063 Add documentation to `flake8-executable` rules
  crates/ruff/src/rules/flake8_executable/rules/shebang_missing.rs
  crates/ruff/src/rules/flake8_executable/rules/shebang_newline.rs
  crates/ruff/src/rules/flake8_executable/rules/shebang_not_executable.rs
  crates/ruff/src/rules/flake8_executable/rules/shebang_python.rs
  crates/ruff/src/rules/flake8_executable/rules/shebang_whitespace.rs
  scripts/check_docs_formatted.py
Labels: documentation

#5075 Use Expr::is_* methods at more call sites
  crates/ruff/src/rules/pyflakes/rules/starred_expressions.rs
  crates/ruff/src/rules/pyflakes/rules/strings.rs
  crates/ruff/src/rules/pylint/rules/logging.rs
  crates/ruff/src/rules/pyupgrade/rules/use_pep604_isinstance.rs
  crates/ruff/src/rules/ruff/rules/pairwise_over_zipped.rs
  crates/ruff_python_ast/src/helpers.rs
Labels: internal

#5083 Add a dedicated read result for unbound locals
  crates/ruff/src/checkers/ast/mod.rs
  crates/ruff_python_semantic/src/model.rs
Labels: internal

#5084 Move binding accesses into `SemanticModel` method
  crates/ruff/src/checkers/ast/mod.rs
  crates/ruff/src/rules/flake8_bugbear/rules/unused_loop_control_variable.rs
  crates/ruff/src/rules/flake8_type_checking/rules/runtime_import_in_type_checking_block.rs
  crates/ruff/src/rules/flake8_type_checking/rules/typing_only_runtime_import.rs
  crates/ruff/src/rules/flake8_unused_arguments/rules/unused_arguments.rs
  crates/ruff/src/rules/pyflakes/rules/undefined_local.rs
  crates/ruff/src/rules/pyflakes/rules/unused_annotation.rs
  crates/ruff/src/rules/pyflakes/rules/unused_import.rs
  crates/ruff/src/rules/pyflakes/rules/unused_variable.rs
  crates/ruff/src/rules/pylint/rules/global_statement.rs
  crates/ruff_python_semantic/src/binding.rs
  crates/ruff_python_semantic/src/model.rs
  crates/ruff_python_semantic/src/reference.rs
Labels: internal

#5085 Remove unused `Scope#delete` method
  crates/ruff_python_semantic/src/scope.rs
Labels: internal

#5088 update tutorial doc typo
  docs/tutorial.md
Labels: documentation

#5093 Make some of `ruff_python_semantic` `pub(crate)`
  crates/ruff_python_semantic/src/definition.rs
  crates/ruff_python_semantic/src/globals.rs
  crates/ruff_python_semantic/src/node.rs
  crates/ruff_python_semantic/src/reference.rs
  crates/ruff_python_semantic/src/scope.rs
Labels: internal

#5095 Improve names and documentation on scope API
  crates/ruff/src/checkers/ast/mod.rs
  crates/ruff/src/rules/flake8_bugbear/rules/unused_loop_control_variable.rs
  crates/ruff_python_semantic/src/scope.rs
Labels: internal

#5100 Enable UTC-import for `datetime-utc-alias` fix
  crates/ruff/src/rules/pyupgrade/rules/datetime_utc_alias.rs
  crates/ruff/src/rules/pyupgrade/snapshots/ruff__rules__pyupgrade__tests__datetime_utc_alias_py311.snap
Labels: autofix

#5103 Remove manual `await` detection
  crates/ruff/src/rules/flake8_comprehensions/rules/unnecessary_comprehension_any_all.rs
  crates/ruff/src/rules/flake8_simplify/rules/reimplemented_builtin.rs
  crates/ruff/src/rules/pyupgrade/rules/unpacked_list_comprehension.rs
Labels: internal

#5096 Complete `pyupgrade` documentation
  crates/ruff/src/rules/pyupgrade/rules/convert_named_tuple_functional_to_class.rs
  crates/ruff/src/rules/pyupgrade/rules/convert_typed_dict_functional_to_class.rs
  crates/ruff/src/rules/pyupgrade/rules/datetime_utc_alias.rs
  crates/ruff/src/rules/pyupgrade/rules/deprecated_c_element_tree.rs
  crates/ruff/src/rules/pyupgrade/rules/deprecated_import.rs
  crates/ruff/src/rules/pyupgrade/rules/deprecated_mock_import.rs
  crates/ruff/src/rules/pyupgrade/rules/deprecated_unittest_alias.rs
  crates/ruff/src/rules/pyupgrade/rules/extraneous_parentheses.rs
  crates/ruff/src/rules/pyupgrade/rules/f_strings.rs
  crates/ruff/src/rules/pyupgrade/rules/format_literals.rs
  crates/ruff/src/rules/pyupgrade/rules/lru_cache_with_maxsize_none.rs
  crates/ruff/src/rules/pyupgrade/rules/lru_cache_without_parameters.rs
  crates/ruff/src/rules/pyupgrade/rules/native_literals.rs
  crates/ruff/src/rules/pyupgrade/rules/open_alias.rs
  crates/ruff/src/rules/pyupgrade/rules/os_error_alias.rs
  crates/ruff/src/rules/pyupgrade/rules/outdated_version_block.rs
  crates/ruff/src/rules/pyupgrade/rules/printf_string_formatting.rs
  crates/ruff/src/rules/pyupgrade/rules/quoted_annotation.rs
  crates/ruff/src/rules/pyupgrade/rules/redundant_open_modes.rs
  crates/ruff/src/rules/pyupgrade/rules/replace_stdout_stderr.rs
  crates/ruff/src/rules/pyupgrade/rules/replace_universal_newlines.rs
  crates/ruff/src/rules/pyupgrade/rules/super_call_with_parameters.rs
  crates/ruff/src/rules/pyupgrade/rules/type_of_primitive.rs
  crates/ruff/src/rules/pyupgrade/rules/typing_text_str_alias.rs
  crates/ruff/src/rules/pyupgrade/rules/unicode_kind_prefix.rs
  crates/ruff/src/rules/pyupgrade/rules/unnecessary_builtin_import.rs
  crates/ruff/src/rules/pyupgrade/rules/unnecessary_coding_comment.rs
  crates/ruff/src/rules/pyupgrade/rules/unnecessary_encode_utf8.rs
  crates/ruff/src/rules/pyupgrade/rules/unnecessary_future_import.rs
  crates/ruff/src/rules/pyupgrade/rules/unpacked_list_comprehension.rs
  crates/ruff/src/rules/pyupgrade/rules/use_pep585_annotation.rs
  crates/ruff/src/rules/pyupgrade/rules/use_pep604_annotation.rs
  crates/ruff/src/rules/pyupgrade/rules/use_pep604_isinstance.rs
  crates/ruff/src/rules/pyupgrade/rules/useless_metaclass_type.rs
  crates/ruff/src/rules/pyupgrade/rules/useless_object_inheritance.rs
  crates/ruff/src/rules/pyupgrade/rules/yield_in_for_loop.rs
  crates/ruff/src/rules/pyupgrade/snapshots/ruff__rules__pyupgrade__tests__UP019.py.snap
  crates/ruff/src/rules/pyupgrade/snapshots/ruff__rules__pyupgrade__tests__UP022.py.snap
  crates/ruff/src/rules/pyupgrade/snapshots/ruff__rules__pyupgrade__tests__UP025.py.snap
  scripts/check_docs_formatted.py
Labels: documentation

#5105 Add `target-version` link to relevant rules
  crates/ruff/src/rules/flake8_future_annotations/rules/future_rewritable_type_annotation.rs
  crates/ruff/src/rules/pylint/rules/bad_str_strip_call.rs
  crates/ruff/src/rules/pylint/rules/continue_in_finally.rs
  crates/ruff/src/rules/pylint/rules/repeated_isinstance_calls.rs
  crates/ruff/src/rules/pyupgrade/rules/datetime_utc_alias.rs
  crates/ruff/src/rules/pyupgrade/rules/lru_cache_with_maxsize_none.rs
  crates/ruff/src/rules/pyupgrade/rules/lru_cache_without_parameters.rs
  crates/ruff/src/rules/pyupgrade/rules/outdated_version_block.rs
  crates/ruff/src/rules/pyupgrade/rules/unnecessary_future_import.rs
  crates/ruff/src/rules/pyupgrade/rules/use_pep585_annotation.rs
  crates/ruff/src/rules/pyupgrade/rules/use_pep604_annotation.rs
  crates/ruff/src/rules/pyupgrade/rules/use_pep604_isinstance.rs
  crates/ruff/src/rules/ruff/rules/implicit_optional.rs
Labels: documentation

#5107 Disambiguate all Python documentation references
  crates/ruff/src/rules/flake8_boolean_trap/rules/check_boolean_default_value_in_function_definition.rs
  crates/ruff/src/rules/flake8_boolean_trap/rules/check_boolean_positional_value_in_function_call.rs
  crates/ruff/src/rules/flake8_boolean_trap/rules/check_positional_boolean_in_def.rs
  crates/ruff/src/rules/flake8_pie/rules/multiple_starts_ends_with.rs
  crates/ruff/src/rules/flake8_pie/rules/no_unnecessary_pass.rs
  crates/ruff/src/rules/flake8_pie/rules/non_unique_enums.rs
  crates/ruff/src/rules/flake8_pie/rules/reimplemented_list_builtin.rs
  crates/ruff/src/rules/flake8_pie/rules/unnecessary_dict_kwargs.rs
  crates/ruff/src/rules/flake8_pie/rules/unnecessary_spread.rs
  crates/ruff/src/rules/flake8_pyi/rules/any_eq_ne_annotation.rs
  crates/ruff/src/rules/flake8_simplify/rules/ast_expr.rs
  crates/ruff/src/rules/flake8_simplify/rules/open_file_with_context_handler.rs
  crates/ruff/src/rules/flake8_simplify/rules/return_in_try_except_finally.rs
  crates/ruff/src/rules/pyflakes/rules/assert_tuple.rs
  crates/ruff/src/rules/pyflakes/rules/default_except_not_last.rs
  crates/ruff/src/rules/pyflakes/rules/future_feature_not_defined.rs
  crates/ruff/src/rules/pyflakes/rules/if_tuple.rs
  crates/ruff/src/rules/pyflakes/rules/invalid_literal_comparisons.rs
  crates/ruff/src/rules/pyflakes/rules/invalid_print_syntax.rs
  crates/ruff/src/rules/pyflakes/rules/repeated_keys.rs
  crates/ruff/src/rules/pyflakes/rules/strings.rs
  crates/ruff/src/rules/pyflakes/rules/undefined_name.rs
  crates/ruff/src/rules/pygrep_hooks/rules/deprecated_log_warn.rs
  crates/ruff/src/rules/pygrep_hooks/rules/no_eval.rs
  crates/ruff/src/rules/pylint/rules/await_outside_async.rs
  crates/ruff/src/rules/pylint/rules/bad_str_strip_call.rs
  crates/ruff/src/rules/pylint/rules/collapsible_else_if.rs
  crates/ruff/src/rules/pylint/rules/compare_to_empty_string.rs
  crates/ruff/src/rules/pylint/rules/comparison_of_constant.rs
  crates/ruff/src/rules/pylint/rules/duplicate_bases.rs
  crates/ruff/src/rules/pylint/rules/global_variable_not_assigned.rs
  crates/ruff/src/rules/pylint/rules/invalid_all_format.rs
  crates/ruff/src/rules/pylint/rules/invalid_all_object.rs
  crates/ruff/src/rules/pylint/rules/load_before_global_declaration.rs
  crates/ruff/src/rules/pylint/rules/manual_import_from.rs
  crates/ruff/src/rules/pylint/rules/nonlocal_without_binding.rs
  crates/ruff/src/rules/pylint/rules/property_with_parameters.rs
  crates/ruff/src/rules/pylint/rules/sys_exit_alias.rs
  crates/ruff/src/rules/pylint/rules/unexpected_special_method_signature.rs
  crates/ruff/src/rules/pylint/rules/unnecessary_direct_lambda_call.rs
  crates/ruff/src/rules/pylint/rules/useless_else_on_loop.rs
  crates/ruff/src/rules/tryceratops/rules/reraise_no_cause.rs
  crates/ruff/src/rules/tryceratops/rules/try_consider_else.rs
  crates/ruff/src/rules/tryceratops/rules/type_check_without_type_error.rs
Labels: documentation

#5108 Use direct links for all PEP 8 references
  crates/ruff/src/rules/flake8_implicit_str_concat/rules/implicit.rs
  crates/ruff/src/rules/flake8_simplify/rules/ast_bool_op.rs
  crates/ruff/src/rules/flake8_simplify/rules/ast_with.rs
  crates/ruff/src/rules/pycodestyle/rules/bare_except.rs
  crates/ruff/src/rules/pycodestyle/rules/compound_statements.rs
  crates/ruff/src/rules/pycodestyle/rules/imports.rs
  crates/ruff/src/rules/pycodestyle/rules/lambda_assignment.rs
  crates/ruff/src/rules/pycodestyle/rules/literal_comparisons.rs
  crates/ruff/src/rules/pycodestyle/rules/logical_lines/extraneous_whitespace.rs
  crates/ruff/src/rules/pycodestyle/rules/logical_lines/indentation.rs
  crates/ruff/src/rules/pycodestyle/rules/logical_lines/space_around_operator.rs
  crates/ruff/src/rules/pycodestyle/rules/logical_lines/whitespace_before_comment.rs
  crates/ruff/src/rules/pycodestyle/rules/trailing_whitespace.rs
  crates/ruff/src/rules/pyflakes/rules/imports.rs
  crates/ruff/src/rules/pylint/rules/magic_value_comparison.rs
  crates/ruff/src/rules/pyupgrade/rules/quoted_annotation.rs
Labels: documentation

#5109 Add autofix specification levels for a variety of rules
  crates/ruff/src/rules/eradicate/rules/commented_out_code.rs
  crates/ruff/src/rules/eradicate/snapshots/ruff__rules__eradicate__tests__ERA001_ERA001.py.snap
  crates/ruff/src/rules/flake8_bugbear/rules/assert_false.rs
  crates/ruff/src/rules/flake8_bugbear/rules/duplicate_exceptions.rs
  crates/ruff/src/rules/flake8_bugbear/snapshots/ruff__rules__flake8_bugbear__tests__B014_B014.py.snap
  crates/ruff/src/rules/flake8_executable/rules/shebang_whitespace.rs
  crates/ruff/src/rules/flake8_executable/snapshots/ruff__rules__flake8_executable__tests__EXE004_1.py.snap
  crates/ruff/src/rules/flake8_pyi/rules/duplicate_union_member.rs
  crates/ruff/src/rules/flake8_pyi/rules/quoted_annotation_in_stub.rs
  crates/ruff/src/rules/flake8_pyi/snapshots/ruff__rules__flake8_pyi__tests__PYI016_PYI016.pyi.snap
  crates/ruff/src/rules/flake8_pyi/snapshots/ruff__rules__flake8_pyi__tests__PYI020_PYI020.pyi.snap
  crates/ruff/src/rules/flake8_raise/rules/unnecessary_paren_on_raise_exception.rs
  crates/ruff/src/rules/flake8_raise/snapshots/ruff__rules__flake8_raise__tests__unnecessary-paren-on-raise-exception_RSE102.py.snap
  crates/ruff/src/rules/flake8_simplify/rules/reimplemented_builtin.rs
  crates/ruff/src/rules/flake8_simplify/rules/yoda_conditions.rs
  crates/ruff/src/rules/flake8_simplify/snapshots/ruff__rules__flake8_simplify__tests__SIM300_SIM300.py.snap
  crates/ruff/src/rules/numpy/rules/deprecated_type_alias.rs
  crates/ruff/src/rules/pycodestyle/rules/lambda_assignment.rs
  crates/ruff/src/rules/pycodestyle/rules/literal_comparisons.rs
  crates/ruff/src/rules/pycodestyle/rules/not_tests.rs
  crates/ruff/src/rules/pycodestyle/snapshots/ruff__rules__pycodestyle__tests__E713_E713.py.snap
  crates/ruff/src/rules/pycodestyle/snapshots/ruff__rules__pycodestyle__tests__E714_E714.py.snap
  crates/ruff/src/rules/pycodestyle/snapshots/ruff__rules__pycodestyle__tests__constant_literals.snap
  crates/ruff/src/rules/pyflakes/rules/invalid_literal_comparisons.rs
  crates/ruff/src/rules/pyflakes/rules/raise_not_implemented.rs
  crates/ruff/src/rules/pyflakes/rules/repeated_keys.rs
  crates/ruff/src/rules/pyflakes/snapshots/ruff__rules__pyflakes__tests__F632_F632.py.snap
  crates/ruff/src/rules/pyflakes/snapshots/ruff__rules__pyflakes__tests__F901_F901.py.snap
  crates/ruff/src/rules/pylint/rules/manual_import_from.rs
  crates/ruff/src/rules/pylint/snapshots/ruff__rules__pylint__tests__PLR0402_import_aliasing.py.snap
  crates/ruff/src/rules/pyupgrade/rules/deprecated_unittest_alias.rs
  crates/ruff/src/rules/pyupgrade/rules/f_strings.rs
  crates/ruff/src/rules/pyupgrade/rules/os_error_alias.rs
  crates/ruff/src/rules/pyupgrade/rules/outdated_version_block.rs
  crates/ruff/src/rules/pyupgrade/rules/quoted_annotation.rs
  crates/ruff/src/rules/pyupgrade/rules/redundant_open_modes.rs
  crates/ruff/src/rules/pyupgrade/rules/replace_universal_newlines.rs
  crates/ruff/src/rules/pyupgrade/rules/type_of_primitive.rs
  crates/ruff/src/rules/pyupgrade/rules/unnecessary_coding_comment.rs
  crates/ruff/src/rules/pyupgrade/rules/unnecessary_encode_utf8.rs
  crates/ruff/src/rules/pyupgrade/rules/yield_in_for_loop.rs
  crates/ruff/src/rules/pyupgrade/snapshots/ruff__rules__pyupgrade__tests__UP003.py.snap
  crates/ruff/src/rules/pyupgrade/snapshots/ruff__rules__pyupgrade__tests__UP009_0.py.snap
  crates/ruff/src/rules/pyupgrade/snapshots/ruff__rules__pyupgrade__tests__UP009_1.py.snap
  crates/ruff/src/rules/pyupgrade/snapshots/ruff__rules__pyupgrade__tests__UP012.py.snap
  crates/ruff/src/rules/pyupgrade/snapshots/ruff__rules__pyupgrade__tests__UP015.py.snap
  crates/ruff/src/rules/pyupgrade/snapshots/ruff__rules__pyupgrade__tests__UP024_0.py.snap
  crates/ruff/src/rules/pyupgrade/snapshots/ruff__rules__pyupgrade__tests__UP024_1.py.snap
  crates/ruff/src/rules/pyupgrade/snapshots/ruff__rules__pyupgrade__tests__UP024_2.py.snap
  crates/ruff/src/rules/pyupgrade/snapshots/ruff__rules__pyupgrade__tests__UP024_4.py.snap
  crates/ruff/src/rules/pyupgrade/snapshots/ruff__rules__pyupgrade__tests__UP037.py.snap
  crates/ruff/src/rules/ruff/rules/ambiguous_unicode_character.rs
  crates/ruff/src/rules/ruff/snapshots/ruff__rules__ruff__tests__confusables.snap
Labels: autofix

#5089 Fix a number of formatter errors from the cpython repository
  crates/ruff_python_ast/src/node.rs
  crates/ruff_python_formatter/resources/test/fixtures/ruff/expression/binary.py
  crates/ruff_python_formatter/resources/test/fixtures/ruff/expression/list.py
  crates/ruff_python_formatter/resources/test/fixtures/ruff/expression/tuple.py
  crates/ruff_python_formatter/resources/test/fixtures/ruff/statement/assign.py
  crates/ruff_python_formatter/resources/test/fixtures/ruff/statement/function.py
  crates/ruff_python_formatter/resources/test/fixtures/ruff/statement/if.py
  crates/ruff_python_formatter/src/comments/placement.rs
  crates/ruff_python_formatter/src/expression/expr_constant.rs
  crates/ruff_python_formatter/src/expression/expr_dict.rs
  crates/ruff_python_formatter/src/expression/expr_list.rs
  crates/ruff_python_formatter/src/other/arguments.rs
  crates/ruff_python_formatter/src/snapshots/ruff_python_formatter__tests__black_test__fmtonoff_py.snap
  crates/ruff_python_formatter/src/snapshots/ruff_python_formatter__tests__black_test__function_py.snap
  crates/ruff_python_formatter/src/snapshots/ruff_python_formatter__tests__ruff_test__expression__binary_py.snap
  crates/ruff_python_formatter/src/snapshots/ruff_python_formatter__tests__ruff_test__expression__list_py.snap
  crates/ruff_python_formatter/src/snapshots/ruff_python_formatter__tests__ruff_test__expression__tuple_py.snap
  crates/ruff_python_formatter/src/snapshots/ruff_python_formatter__tests__ruff_test__statement__assign_py.snap
  crates/ruff_python_formatter/src/snapshots/ruff_python_formatter__tests__ruff_test__statement__function_py.snap
  crates/ruff_python_formatter/src/snapshots/ruff_python_formatter__tests__ruff_test__statement__if_py.snap
  crates/ruff_python_formatter/src/snapshots/ruff_python_formatter__trivia__tests__tokenize_comma.snap
  crates/ruff_python_formatter/src/snapshots/ruff_python_formatter__trivia__tests__tokenize_continuation.snap
  crates/ruff_python_formatter/src/snapshots/ruff_python_formatter__trivia__tests__tokenize_parentheses.snap
  crates/ruff_python_formatter/src/snapshots/ruff_python_formatter__trivia__tests__tokenize_substring.snap
  crates/ruff_python_formatter/src/snapshots/ruff_python_formatter__trivia__tests__tokenize_trivia.snap
Labels: formatter

#5135 Minor formatting changes to `Checker`
  crates/ruff/src/checkers/ast/mod.rs
  crates/ruff/src/rules/pylint/rules/load_before_global_declaration.rs
Labels: rule

#5139 Skip `DJ008` enforcement in stub files
  crates/ruff/src/checkers/ast/mod.rs
Labels: bug

#5164 Add some minor tweaks to latest docs
  crates/ruff/src/rules/flake8_blind_except/rules/blind_except.rs
  crates/ruff/src/rules/flake8_raise/rules/unnecessary_paren_on_raise_exception.rs
Labels: documentation

#5147 Refactor top llvm-lines entry
  crates/ruff_macros/src/map_codes.rs
Labels: internal

#5146 Pre commit without cargo and other pre-PR improvements
  .pre-commit-config.yaml
  CONTRIBUTING.md
  crates/ruff_dev/src/generate_json_schema.rs
Labels: internal

#5152 Enable autofix for unconventional imports rule
  crates/ruff/src/rules/flake8_import_conventions/rules/unconventional_import_alias.rs
  crates/ruff/src/rules/flake8_import_conventions/snapshots/ruff__rules__flake8_import_conventions__tests__custom.snap
  crates/ruff/src/rules/flake8_import_conventions/snapshots/ruff__rules__flake8_import_conventions__tests__defaults.snap
  crates/ruff/src/rules/flake8_import_conventions/snapshots/ruff__rules__flake8_import_conventions__tests__from_imports.snap
  crates/ruff/src/rules/flake8_import_conventions/snapshots/ruff__rules__flake8_import_conventions__tests__override_default.snap
  crates/ruff/src/rules/flake8_import_conventions/snapshots/ruff__rules__flake8_import_conventions__tests__remove_default.snap
Labels: rule, autofix

#5173 Detect continuations at start-of-file
  crates/ruff_python_ast/src/source_code/indexer.rs
Labels: bug

#5174 Fix allowed-ellipsis detection
  crates/ruff/resources/test/fixtures/pycodestyle/E70.py
  crates/ruff/src/rules/pycodestyle/rules/compound_statements.rs
  crates/ruff/src/rules/pycodestyle/snapshots/ruff__rules__pycodestyle__tests__E702_E70.py.snap
Labels: bug

#5144 Add `cargo dev repeat` for profiling
  .gitignore
  crates/ruff_cli/src/args.rs
  crates/ruff_cli/src/lib.rs
  crates/ruff_dev/src/main.rs
Labels: internal

#5170 Explain dangling comments in the formatter
  crates/ruff_python_formatter/README.md
Labels: formatter

#5055 Add a script that tests formatter stability on repositories
  Cargo.lock
  Cargo.toml
  crates/ruff/Cargo.toml
  crates/ruff_cli/src/lib.rs
  crates/ruff_cli/src/resolve.rs
  crates/ruff_dev/Cargo.toml
  crates/ruff_dev/src/check_formatter_stability.rs
  crates/ruff_dev/src/main.rs
Labels: internal

#5187 Add rule documentation URL to JSON output
  Cargo.toml
  crates/ruff/src/message/json.rs
  crates/ruff/src/message/snapshots/ruff__message__json__tests__output.snap
  crates/ruff/src/message/snapshots/ruff__message__json_lines__tests__output.snap
  crates/ruff/src/registry.rs
  crates/ruff_cli/tests/integration_test.rs
Labels: cli

#5199 Remove continuations before trailing semicolons
  crates/ruff/resources/test/fixtures/pycodestyle/E70.py
  crates/ruff/src/checkers/tokens.rs
  crates/ruff/src/rules/pycodestyle/rules/compound_statements.rs
  crates/ruff/src/rules/pycodestyle/snapshots/ruff__rules__pycodestyle__tests__E702_E70.py.snap
  crates/ruff/src/rules/pycodestyle/snapshots/ruff__rules__pycodestyle__tests__E703_E70.py.snap
Labels: bug

#5203 Small binary size optimization
  Cargo.toml
Labels: performance

#5167 basic formatting for ExprDict
  crates/ruff_python_formatter/resources/test/fixtures/ruff/expression/dict.py
  crates/ruff_python_formatter/src/comments/placement.rs
  crates/ruff_python_formatter/src/expression/expr_dict.rs
  crates/ruff_python_formatter/src/snapshots/ruff_python_formatter__tests__black_test__collections_py.snap
  crates/ruff_python_formatter/src/snapshots/ruff_python_formatter__tests__black_test__comments_py.snap
  crates/ruff_python_formatter/src/snapshots/ruff_python_formatter__tests__black_test__expression_py.snap
  crates/ruff_python_formatter/src/snapshots/ruff_python_formatter__tests__black_test__fmtonoff_py.snap
  crates/ruff_python_formatter/src/snapshots/ruff_python_formatter__tests__black_test__function_py.snap
  crates/ruff_python_formatter/src/snapshots/ruff_python_formatter__tests__black_test__function_trailing_comma_py.snap
  crates/ruff_python_formatter/src/snapshots/ruff_python_formatter__tests__black_test__power_op_spacing_py.snap
  crates/ruff_python_formatter/src/snapshots/ruff_python_formatter__tests__black_test__trailing_comma_optional_parens3_py.snap
  crates/ruff_python_formatter/src/snapshots/ruff_python_formatter__tests__ruff_test__expression__binary_py.snap
  crates/ruff_python_formatter/src/snapshots/ruff_python_formatter__tests__ruff_test__expression__dict_py.snap
  crates/ruff_python_formatter/src/trivia.rs
Labels: formatter

#5194 Upgrade `RustPython` to access ranged names
  Cargo.lock
  Cargo.toml
  crates/ruff/src/checkers/ast/mod.rs
  crates/ruff/src/rules/flake8_bugbear/rules/getattr_with_constant.rs
  crates/ruff/src/rules/flake8_bugbear/rules/setattr_with_constant.rs
  crates/ruff/src/rules/flake8_gettext/rules/is_gettext_func_call.rs
  crates/ruff/src/rules/flake8_pie/rules/multiple_starts_ends_with.rs
  crates/ruff/src/rules/flake8_pytest_style/rules/raises.rs
  crates/ruff/src/rules/flake8_pytest_style/rules/unittest_assert.rs
  crates/ruff/src/rules/flake8_simplify/rules/ast_if.rs
  crates/ruff/src/rules/flake8_tidy_imports/rules/relative_imports.rs
  crates/ruff/src/rules/pycodestyle/rules/lambda_assignment.rs
  crates/ruff/src/rules/pylint/rules/duplicate_bases.rs
  crates/ruff/src/rules/pylint/rules/manual_import_from.rs
  crates/ruff/src/rules/pylint/rules/useless_import_alias.rs
  crates/ruff/src/rules/pyupgrade/rules/convert_named_tuple_functional_to_class.rs
  crates/ruff/src/rules/pyupgrade/rules/convert_typed_dict_functional_to_class.rs
  crates/ruff/src/rules/pyupgrade/rules/super_call_with_parameters.rs
  crates/ruff/src/rules/ruff/rules/implicit_optional.rs
  crates/ruff/src/rules/tryceratops/rules/useless_try_except.rs
  crates/ruff/src/rules/tryceratops/rules/verbose_log_message.rs
  crates/ruff/src/rules/tryceratops/rules/verbose_raise.rs
  crates/ruff_python_ast/src/source_code/generator.rs
  crates/ruff_python_formatter/src/comments/placement.rs
Labels: internal

#5178 Complete `flake8-bugbear` documentation
  crates/ruff/src/rules/flake8_bugbear/rules/abstract_base_class.rs
  crates/ruff/src/rules/flake8_bugbear/rules/assert_false.rs
  crates/ruff/src/rules/flake8_bugbear/rules/assignment_to_os_environ.rs
  crates/ruff/src/rules/flake8_bugbear/rules/cached_instance_method.rs
  crates/ruff/src/rules/flake8_bugbear/rules/duplicate_exceptions.rs
  crates/ruff/src/rules/flake8_bugbear/rules/except_with_empty_tuple.rs
  crates/ruff/src/rules/flake8_bugbear/rules/except_with_non_exception_classes.rs
  crates/ruff/src/rules/flake8_bugbear/rules/f_string_docstring.rs
  crates/ruff/src/rules/flake8_bugbear/rules/function_uses_loop_variable.rs
  crates/ruff/src/rules/flake8_bugbear/rules/getattr_with_constant.rs
  crates/ruff/src/rules/flake8_bugbear/rules/jump_statement_in_finally.rs
  crates/ruff/src/rules/flake8_bugbear/rules/loop_variable_overrides_iterator.rs
  crates/ruff/src/rules/flake8_bugbear/rules/mutable_argument_default.rs
  crates/ruff/src/rules/flake8_bugbear/rules/raise_literal.rs
  crates/ruff/src/rules/flake8_bugbear/rules/raise_without_from_inside_except.rs
  crates/ruff/src/rules/flake8_bugbear/rules/redundant_tuple_in_exception_handler.rs
  crates/ruff/src/rules/flake8_bugbear/rules/setattr_with_constant.rs
  crates/ruff/src/rules/flake8_bugbear/rules/star_arg_unpacking_after_keyword_arg.rs
  crates/ruff/src/rules/flake8_bugbear/rules/strip_with_multi_characters.rs
  crates/ruff/src/rules/flake8_bugbear/rules/unary_prefix_increment.rs
  crates/ruff/src/rules/flake8_bugbear/rules/unreliable_callable_check.rs
  crates/ruff/src/rules/flake8_bugbear/rules/unused_loop_control_variable.rs
  crates/ruff/src/rules/flake8_bugbear/rules/useless_comparison.rs
  crates/ruff/src/rules/flake8_bugbear/rules/useless_contextlib_suppress.rs
  crates/ruff/src/rules/flake8_bugbear/rules/useless_expression.rs
  crates/ruff/src/rules/flake8_bugbear/rules/zip_without_explicit_strict.rs
  crates/ruff/src/rules/ruff/rules/explicit_f_string_type_conversion.rs
Labels: documentation

#5219 Support parenthesized expressions when splitting compound assertions
  crates/ruff/resources/test/fixtures/flake8_pytest_style/PT018.py
  crates/ruff/src/rules/flake8_pytest_style/rules/assertion.rs
  crates/ruff/src/rules/flake8_pytest_style/snapshots/ruff__rules__flake8_pytest_style__tests__PT018.snap
Labels: bug

#5204 Fix ArgWithDefault comments handling
  Cargo.lock
  Cargo.toml
  crates/ruff_python_ast/src/node.rs
  crates/ruff_python_formatter/resources/test/fixtures/ruff/statement/function.py
  crates/ruff_python_formatter/src/cli.rs
  crates/ruff_python_formatter/src/comments/placement.rs
  crates/ruff_python_formatter/src/comments/snapshots/ruff_python_formatter__comments__tests__non_positional_arguments_slash_on_same_line.snap
  crates/ruff_python_formatter/src/comments/snapshots/ruff_python_formatter__comments__tests__non_positional_arguments_with_defaults.snap
  crates/ruff_python_formatter/src/comments/snapshots/ruff_python_formatter__comments__tests__positional_argument_only_comment.snap
  crates/ruff_python_formatter/src/comments/snapshots/ruff_python_formatter__comments__tests__positional_argument_only_comment_without_following_node.snap
  crates/ruff_python_formatter/src/comments/snapshots/ruff_python_formatter__comments__tests__positional_argument_only_leading_comma_comment.snap
  crates/ruff_python_formatter/src/comments/snapshots/ruff_python_formatter__comments__tests__trailing_after_comma.snap
  crates/ruff_python_formatter/src/comments/visitor.rs
  crates/ruff_python_formatter/src/lib.rs
  crates/ruff_python_formatter/src/other/arg_with_default.rs
  crates/ruff_python_formatter/src/other/arguments.rs
  crates/ruff_python_formatter/src/snapshots/ruff_python_formatter__tests__ruff_test__statement__function_py.snap
Labels: formatter

#5224 Fixed typo in numpy deprecated type alias rule documentation
  crates/ruff/src/rules/numpy/rules/deprecated_type_alias.rs
Labels: documentation

#4985 Correctly handle left/right breaking of binary expression
  crates/ruff_python_formatter/resources/test/fixtures/ruff/expression/binary.py
  crates/ruff_python_formatter/src/expression/expr_bin_op.rs
  crates/ruff_python_formatter/src/snapshots/ruff_python_formatter__tests__ruff_test__expression__binary_py.snap
Labels: internal, formatter

#5215 Consistently name comment own line/end-of-line `line_position()`
  crates/ruff_python_formatter/src/comments/debug.rs
  crates/ruff_python_formatter/src/comments/format.rs
  crates/ruff_python_formatter/src/comments/mod.rs
  crates/ruff_python_formatter/src/comments/placement.rs
  crates/ruff_python_formatter/src/comments/visitor.rs
  crates/ruff_python_formatter/src/expression/expr_list.rs
  crates/ruff_python_formatter/src/statement/stmt_function_def.rs
  crates/ruff_python_formatter/src/statement/stmt_if.rs
  crates/ruff_python_formatter/src/statement/stmt_while.rs
Labels: internal, formatter

#4986 Format BoolOp
  crates/ruff_python_formatter/resources/test/fixtures/ruff/expression/boolean_operation.py
  crates/ruff_python_formatter/src/expression/binary_like.rs
  crates/ruff_python_formatter/src/expression/expr_bin_op.rs
  crates/ruff_python_formatter/src/expression/expr_bool_op.rs
  crates/ruff_python_formatter/src/expression/expr_unary_op.rs
  crates/ruff_python_formatter/src/expression/mod.rs
  crates/ruff_python_formatter/src/snapshots/ruff_python_formatter__tests__black_test__comments2_py.snap
  crates/ruff_python_formatter/src/snapshots/ruff_python_formatter__tests__black_test__comments6_py.snap
  crates/ruff_python_formatter/src/snapshots/ruff_python_formatter__tests__black_test__empty_lines_py.snap
  crates/ruff_python_formatter/src/snapshots/ruff_python_formatter__tests__black_test__expression_py.snap
  crates/ruff_python_formatter/src/snapshots/ruff_python_formatter__tests__black_test__fmtskip5_py.snap
  crates/ruff_python_formatter/src/snapshots/ruff_python_formatter__tests__black_test__skip_magic_trailing_comma_py.snap
  crates/ruff_python_formatter/src/snapshots/ruff_python_formatter__tests__black_test__torture_py.snap
  crates/ruff_python_formatter/src/snapshots/ruff_python_formatter__tests__black_test__trailing_comma_optional_parens1_py.snap
  crates/ruff_python_formatter/src/snapshots/ruff_python_formatter__tests__black_test__trailing_comma_optional_parens2_py.snap
  crates/ruff_python_formatter/src/snapshots/ruff_python_formatter__tests__black_test__trailing_commas_in_leading_parts_py.snap
  crates/ruff_python_formatter/src/snapshots/ruff_python_formatter__tests__ruff_test__expression__boolean_operation_py.snap
  crates/ruff_python_formatter/src/snapshots/ruff_python_formatter__tests__ruff_test__statement__while_py.snap
Labels: internal, formatter

#5145 Unify benchmarking and profiling docs
  CONTRIBUTING.md
  crates/ruff_benchmark/README.md
Labels: documentation, internal

#5209 Improve debuggability of `place_comment`
  crates/ruff_python_formatter/src/comments/placement.rs
  crates/ruff_python_formatter/src/comments/visitor.rs
Labels: formatter

#5240 Ensure release tagging has access to repo clone
  .github/workflows/release.yaml
Labels: release

#5255 Format Identifier
  crates/ruff_python_formatter/src/other/arg.rs
  crates/ruff_python_formatter/src/other/identifier.rs
  crates/ruff_python_formatter/src/other/mod.rs
  crates/ruff_python_formatter/src/statement/stmt_function_def.rs
Labels: formatter

#5256 Restore existing bindings when unbinding caught exceptions
  crates/ruff/src/checkers/ast/mod.rs
  crates/ruff/src/renamer.rs
  crates/ruff/src/rules/pyflakes/mod.rs
  crates/ruff/src/rules/pyflakes/snapshots/ruff__rules__pyflakes__tests__load_after_multiple_unbinds_from_module_scope.snap
  crates/ruff/src/rules/pyflakes/snapshots/ruff__rules__pyflakes__tests__load_after_unbind_from_class_scope.snap
  crates/ruff/src/rules/pyflakes/snapshots/ruff__rules__pyflakes__tests__load_after_unbind_from_module_scope.snap
  crates/ruff/src/rules/pyflakes/snapshots/ruff__rules__pyflakes__tests__load_after_unbind_from_nested_module_scope.snap
  crates/ruff/src/rules/pyflakes/snapshots/ruff__rules__pyflakes__tests__print_in_body_after_double_shadowing_except.snap
  crates/ruff/src/rules/pyflakes/snapshots/ruff__rules__pyflakes__tests__print_in_body_after_shadowing_except.snap
  crates/ruff/src/rules/pyflakes/snapshots/ruff__rules__pyflakes__tests__print_in_if_else_after_shadowing_except.snap
  crates/ruff/src/rules/pyflakes/snapshots/ruff__rules__pyflakes__tests__print_in_try_else_after_shadowing_except.snap
  crates/ruff_python_semantic/src/binding.rs
  crates/ruff_python_semantic/src/model.rs
Labels: bug

#5260 Improve documentation for overlong-line rules
  crates/ruff/src/rules/pycodestyle/rules/doc_line_too_long.rs
  crates/ruff/src/rules/pycodestyle/rules/line_too_long.rs
Labels: documentation

#5211 Format function argument separator comments
  crates/ruff_python_formatter/resources/test/fixtures/ruff/statement/function.py
  crates/ruff_python_formatter/src/comments/placement.rs
  crates/ruff_python_formatter/src/other/arguments.rs
  crates/ruff_python_formatter/src/snapshots/ruff_python_formatter__tests__ruff_test__statement__function_py.snap
Labels: formatter

#5175 Special `ExprTuple` formatting option for `for`-loops
  crates/ruff_python_formatter/src/expression/expr_tuple.rs
  crates/ruff_python_formatter/src/expression/mod.rs
Labels: formatter

#5268 Avoid including nursery rules in linter-level selectors
  crates/ruff_macros/src/map_codes.rs
Labels: bug

#5163 Format StmtFor
  crates/ruff_python_formatter/resources/test/fixtures/ruff/statement/for.py
  crates/ruff_python_formatter/src/snapshots/ruff_python_formatter__tests__black_test__bracketmatch_py.snap
  crates/ruff_python_formatter/src/snapshots/ruff_python_formatter__tests__black_test__collections_py.snap
  crates/ruff_python_formatter/src/snapshots/ruff_python_formatter__tests__black_test__comments3_py.snap
  crates/ruff_python_formatter/src/snapshots/ruff_python_formatter__tests__black_test__comments5_py.snap
  crates/ruff_python_formatter/src/snapshots/ruff_python_formatter__tests__black_test__expression_py.snap
  crates/ruff_python_formatter/src/snapshots/ruff_python_formatter__tests__black_test__fmtonoff5_py.snap
  crates/ruff_python_formatter/src/snapshots/ruff_python_formatter__tests__black_test__fmtonoff_py.snap
  crates/ruff_python_formatter/src/snapshots/ruff_python_formatter__tests__black_test__fmtskip8_py.snap
  crates/ruff_python_formatter/src/snapshots/ruff_python_formatter__tests__black_test__function_py.snap
  crates/ruff_python_formatter/src/snapshots/ruff_python_formatter__tests__black_test__remove_for_brackets_py.snap
  crates/ruff_python_formatter/src/snapshots/ruff_python_formatter__tests__black_test__remove_newline_after_code_block_open_py.snap
  crates/ruff_python_formatter/src/snapshots/ruff_python_formatter__tests__ruff_test__statement__for_py.snap
  crates/ruff_python_formatter/src/statement/stmt_for.rs
Labels: formatter

#5270 Use trait for labels instead of `TypeId`
  crates/ruff_formatter/src/builders.rs
  crates/ruff_formatter/src/format_element/tag.rs
Labels: internal, formatter

#5262 Complete documentation for Ruff-specific rules
  crates/ruff/src/rules/ruff/rules/ambiguous_unicode_character.rs
  crates/ruff/src/rules/ruff/rules/collection_literal_concatenation.rs
  crates/ruff/src/rules/ruff/rules/pairwise_over_zipped.rs
Labels: documentation

#5259 Format Attribute Expression
  crates/ruff_python_formatter/resources/test/fixtures/ruff/expression/attribute.py
  crates/ruff_python_formatter/src/comments/placement.rs
  crates/ruff_python_formatter/src/expression/expr_attribute.rs
  crates/ruff_python_formatter/src/expression/parentheses.rs
  crates/ruff_python_formatter/src/snapshots/ruff_python_formatter__tests__black_test__attribute_access_on_number_literals_py.snap
  crates/ruff_python_formatter/src/snapshots/ruff_python_formatter__tests__black_test__collections_py.snap
  crates/ruff_python_formatter/src/snapshots/ruff_python_formatter__tests__black_test__comments2_py.snap
  crates/ruff_python_formatter/src/snapshots/ruff_python_formatter__tests__black_test__comments3_py.snap
  crates/ruff_python_formatter/src/snapshots/ruff_python_formatter__tests__black_test__comments5_py.snap
  crates/ruff_python_formatter/src/snapshots/ruff_python_formatter__tests__black_test__empty_lines_py.snap
  crates/ruff_python_formatter/src/snapshots/ruff_python_formatter__tests__black_test__expression_py.snap
  crates/ruff_python_formatter/src/snapshots/ruff_python_formatter__tests__black_test__fmtonoff_py.snap
  crates/ruff_python_formatter/src/snapshots/ruff_python_formatter__tests__black_test__function_py.snap
  crates/ruff_python_formatter/src/snapshots/ruff_python_formatter__tests__black_test__import_spacing_py.snap
  crates/ruff_python_formatter/src/snapshots/ruff_python_formatter__tests__black_test__power_op_spacing_py.snap
  crates/ruff_python_formatter/src/snapshots/ruff_python_formatter__tests__black_test__remove_for_brackets_py.snap
  crates/ruff_python_formatter/src/snapshots/ruff_python_formatter__tests__black_test__slices_py.snap
  crates/ruff_python_formatter/src/snapshots/ruff_python_formatter__tests__ruff_test__expression__attribute_py.snap
  crates/ruff_python_formatter/src/snapshots/ruff_python_formatter__tests__ruff_test__expression__boolean_operation_py.snap
  crates/ruff_python_formatter/src/trivia.rs
Labels: internal, formatter

#5273 Ignore Pydantic classes when evaluating `mutable-class-default` (`RUF012`)
  crates/ruff/resources/test/fixtures/ruff/RUF012.py
  crates/ruff/src/rules/ruff/rules/helpers.rs
  crates/ruff/src/rules/ruff/rules/mutable_class_default.rs
Labels: bug

#5279 Use 'Checks for uses' consistently
  crates/ruff/src/rules/flake8_pyi/rules/bad_version_info_comparison.rs
  crates/ruff/src/rules/flake8_simplify/rules/open_file_with_context_handler.rs
  crates/ruff/src/rules/pygrep_hooks/rules/no_eval.rs
  crates/ruff/src/rules/pylint/rules/await_outside_async.rs
  crates/ruff/src/rules/pylint/rules/load_before_global_declaration.rs
  crates/ruff/src/rules/pylint/rules/named_expr_without_context.rs
Labels: documentation

#5278 Use `mod tests` consistently
  crates/ruff/src/jupyter/notebook.rs
  crates/ruff/src/jupyter/snapshots/ruff__jupyter__notebook__tests__import_sorting.snap
  crates/ruff/src/rules/pyupgrade/fixes.rs
  crates/ruff/src/rules/pyupgrade/rules/printf_string_formatting.rs
  crates/ruff_cli/src/cache.rs
  crates/ruff_cli/src/diagnostics.rs
  crates/ruff_dev/src/generate_cli_help.rs
  crates/ruff_dev/src/generate_json_schema.rs
Labels: internal
