Repository astral-sh/ruff, pull requests merged in 2023-03, with the labels that each got.

#3288 Ignore unused imports in ModuleNotFoundError blocks
  crates/ruff/resources/test/fixtures/pyflakes/F401_10.py
  crates/ruff/src/ast/helpers.rs
  crates/ruff/src/checkers/ast.rs
  crates/ruff/src/rules/flake8_simplify/rules/use_contextlib_suppress.rs
  crates/ruff/src/rules/pyflakes/mod.rs
  crates/ruff/src/rules/pyflakes/snapshots/ruff__rules__pyflakes__tests__F401_F401_10.py.snap
  crates/ruff/src/rules/pyflakes/snapshots/ruff__rules__pyflakes__tests__F811_F811_12.py.snap
Labels: bug

#3296 Add a CLI flag to force-ignore noqa directives
  crates/ruff/src/lib_wasm.rs
  crates/ruff/src/linter.rs
  crates/ruff/src/rules/pandas_vet/mod.rs
  crates/ruff/src/rules/pyflakes/mod.rs
  crates/ruff/src/test.rs
  crates/ruff_cli/src/args.rs
  crates/ruff_cli/src/commands/run.rs
  crates/ruff_cli/src/commands/run_stdin.rs
  crates/ruff_cli/src/diagnostics.rs
  crates/ruff_cli/src/main.rs
Labels: cli

#3312 Treat function type annotations within classes as runtime-required
  crates/ruff/src/checkers/ast.rs
  crates/ruff/src/rules/flake8_type_checking/snapshots/ruff__rules__flake8_type_checking__tests__runtime-import-in-type-checking-block_TCH004_5.py.snap
Labels: bug

#3313 feat(E211): add rule + autofix
  crates/ruff/resources/test/fixtures/pycodestyle/E21.py
  crates/ruff/src/checkers/logical_lines.rs
  crates/ruff/src/codes.rs
  crates/ruff/src/linter.rs
  crates/ruff/src/registry.rs
  crates/ruff/src/rules/pycodestyle/helpers.rs
  crates/ruff/src/rules/pycodestyle/mod.rs
  crates/ruff/src/rules/pycodestyle/rules/extraneous_whitespace.rs
  crates/ruff/src/rules/pycodestyle/rules/indentation.rs
  crates/ruff/src/rules/pycodestyle/rules/missing_whitespace_after_keyword.rs
  crates/ruff/src/rules/pycodestyle/rules/mod.rs
  crates/ruff/src/rules/pycodestyle/rules/space_around_operator.rs
  crates/ruff/src/rules/pycodestyle/rules/whitespace_around_keywords.rs
  crates/ruff/src/rules/pycodestyle/rules/whitespace_around_named_parameter_equals.rs
  crates/ruff/src/rules/pycodestyle/rules/whitespace_before_comment.rs
  crates/ruff/src/rules/pycodestyle/rules/whitespace_before_parameters.rs
  crates/ruff/src/rules/pycodestyle/snapshots/ruff__rules__pycodestyle__tests__E211_E21.py.snap
Labels: rule

#3300 feat(e225,226,227,228): add rules
  crates/ruff/src/checkers/logical_lines.rs
  crates/ruff/src/codes.rs
  crates/ruff/src/registry.rs
  crates/ruff/src/rules/pycodestyle/helpers.rs
  crates/ruff/src/rules/pycodestyle/mod.rs
  crates/ruff/src/rules/pycodestyle/rules/missing_whitespace_around_operator.rs
  crates/ruff/src/rules/pycodestyle/rules/mod.rs
  crates/ruff/src/rules/pycodestyle/snapshots/ruff__rules__pycodestyle__tests__E225_E22.py.snap
  crates/ruff/src/rules/pycodestyle/snapshots/ruff__rules__pycodestyle__tests__E226_E22.py.snap
  crates/ruff/src/rules/pycodestyle/snapshots/ruff__rules__pycodestyle__tests__E227_E22.py.snap
  crates/ruff/src/rules/pycodestyle/snapshots/ruff__rules__pycodestyle__tests__E228_E22.py.snap
Labels: rule

#3314 Always include `@classmethod` and `@staticmethod` in decorator lists
  crates/ruff/resources/test/fixtures/pyproject.toml
  crates/ruff/src/ast/function_type.rs
  crates/ruff/src/rules/pep8_naming/settings.rs
  crates/ruff/src/rules/pydocstyle/settings.rs
  crates/ruff/src/settings/pyproject.rs
  ruff.schema.json
Labels: breaking, configuration

#3324 Extend `RET503` autofixes to "end of statement", including comments
  crates/ruff/resources/test/fixtures/flake8_return/RET503.py
  crates/ruff/src/ast/helpers.rs
  crates/ruff/src/rules/flake8_return/rules.rs
  crates/ruff/src/rules/flake8_return/snapshots/ruff__rules__flake8_return__tests__RET503_RET503.py.snap
  crates/ruff_dev/src/print_tokens.rs
Labels: bug

#3348 Treat unary operations on constants as constant-like
  crates/ruff/resources/test/fixtures/flake8_simplify/SIM300.py
  crates/ruff/resources/test/fixtures/pylint/magic_value_comparison.py
  crates/ruff/src/rules/flake8_simplify/rules/yoda_conditions.rs
  crates/ruff/src/rules/flake8_simplify/snapshots/ruff__rules__flake8_simplify__tests__SIM300_SIM300.py.snap
  crates/ruff/src/rules/pylint/rules/magic_value_comparison.rs
  crates/ruff/src/rules/pylint/snapshots/ruff__rules__pylint__tests__PLR2004_magic_value_comparison.py.snap
  crates/ruff/src/rules/pylint/snapshots/ruff__rules__pylint__tests__allow_magic_value_types.snap
Labels: bug

#3344 feat(e231): add rule + autofix
  crates/ruff/resources/test/fixtures/pycodestyle/E23.py
  crates/ruff/src/checkers/logical_lines.rs
  crates/ruff/src/codes.rs
  crates/ruff/src/registry.rs
  crates/ruff/src/rules/pycodestyle/logical_lines.rs
  crates/ruff/src/rules/pycodestyle/mod.rs
  crates/ruff/src/rules/pycodestyle/rules/missing_whitespace.rs
  crates/ruff/src/rules/pycodestyle/rules/mod.rs
  crates/ruff/src/rules/pycodestyle/snapshots/ruff__rules__pycodestyle__tests__E231_E23.py.snap
Labels: rule

#3343 Skip byte-order-mark at start of file
  crates/ruff/resources/test/fixtures/pydocstyle/bom.py
  crates/ruff/src/rules/pydocstyle/mod.rs
  crates/ruff/src/rules/pydocstyle/snapshots/ruff__rules__pydocstyle__tests__bom.snap
  crates/ruff/src/source_code/locator.rs
Labels: bug

#3362 Don't enforce typing-import rules in .pyi files
  crates/ruff/resources/test/fixtures/flake8_type_checking/TCH004_14.pyi
  crates/ruff/src/checkers/ast/mod.rs
  crates/ruff/src/rules/flake8_type_checking/mod.rs
  crates/ruff/src/rules/flake8_type_checking/snapshots/ruff__rules__flake8_type_checking__tests__runtime-import-in-type-checking-block_TCH004_14.pyi.snap
Labels: bug

#3367 Move `visibility` module into `ast` crate
  crates/ruff/src/ast/context.rs
  crates/ruff/src/ast/mod.rs
  crates/ruff/src/ast/visibility.rs
  crates/ruff/src/checkers/ast/deferred.rs
  crates/ruff/src/checkers/ast/mod.rs
  crates/ruff/src/docstrings/definition.rs
  crates/ruff/src/docstrings/extraction.rs
  crates/ruff/src/lib.rs
  crates/ruff/src/rules/flake8_annotations/helpers.rs
  crates/ruff/src/rules/flake8_annotations/rules.rs
  crates/ruff/src/rules/flake8_bugbear/rules/abstract_base_class.rs
  crates/ruff/src/rules/flake8_unused_arguments/rules.rs
  crates/ruff/src/rules/pydocstyle/rules/if_needed.rs
  crates/ruff/src/rules/pydocstyle/rules/non_imperative_mood.rs
  crates/ruff/src/rules/pydocstyle/rules/not_missing.rs
  crates/ruff/src/rules/pydocstyle/rules/sections.rs
Labels: internal

#3375 Include entire prefix when reporting rule selector errors
  crates/ruff/src/rule_selector.rs
  crates/ruff_cli/src/args.rs
Labels: bug, cli

#3391 Handle multi-line fixes for byte-string prefixing
  crates/ruff/resources/test/fixtures/pyupgrade/UP012.py
  crates/ruff/src/rules/pyupgrade/rules/unnecessary_encode_utf8.rs
  crates/ruff/src/rules/pyupgrade/snapshots/ruff__rules__pyupgrade__tests__UP012.py.snap
Labels: bug

#3392 Remap ChainMap, Counter, and OrderedDict imports to collections
  crates/ruff/resources/test/fixtures/pyupgrade/UP035.py
  crates/ruff/src/rules/pyupgrade/rules/import_replacements.rs
  crates/ruff/src/rules/pyupgrade/snapshots/ruff__rules__pyupgrade__tests__UP035.py.snap
Labels: bug

#3395 Catch RET504 usages via decorators
  crates/ruff/resources/test/fixtures/flake8_return/RET504.py
  crates/ruff/src/rules/flake8_return/visitor.rs
Labels: bug

#3398 Make `ruff_cli` binary a small wrapper around `lib`
  crates/ruff_cli/Cargo.toml
  crates/ruff_cli/src/args.rs
  crates/ruff_cli/src/bin/ruff.rs
  crates/ruff_cli/src/commands/config.rs
  crates/ruff_cli/src/lib.rs
  crates/ruff_cli/src/main.rs
  crates/ruff_dev/src/generate_all.rs
  crates/ruff_dev/src/generate_cli_help.rs
  crates/ruff_dev/src/generate_json_schema.rs
Labels: internal

#3400 [`flake8-bugbear`] Add `flake8-bugbear`'s B030 rule
  crates/ruff/resources/test/fixtures/flake8_bugbear/B030.py
  crates/ruff/src/checkers/ast/mod.rs
  crates/ruff/src/codes.rs
  crates/ruff/src/registry.rs
  crates/ruff/src/rules/flake8_bugbear/mod.rs
  crates/ruff/src/rules/flake8_bugbear/rules/except_with_non_exception_classes.rs
  crates/ruff/src/rules/flake8_bugbear/rules/mod.rs
  crates/ruff/src/rules/flake8_bugbear/snapshots/ruff__rules__flake8_bugbear__tests__B030_B030.py.snap
  ruff.schema.json
Labels: rule

#3393 Ignore multiply-assigned variables in RET504
  crates/ruff/resources/test/fixtures/flake8_return/RET504.py
  crates/ruff/src/rules/flake8_return/rules.rs
  crates/ruff/src/rules/flake8_return/snapshots/ruff__rules__flake8_return__tests__RET504_RET504.py.snap
Labels: bug

#3411 Autofix PIE810 rule violations
  crates/ruff/resources/test/fixtures/flake8_pie/PIE810.py
  crates/ruff/src/checkers/ast/mod.rs
  crates/ruff/src/rules/flake8_pie/rules.rs
  crates/ruff/src/rules/flake8_pie/snapshots/ruff__rules__flake8_pie__tests__PIE810_PIE810.py.snap
Labels: autofix

#3434 fix: method `red` not found in release builds
  crates/ruff_cli/src/lib.rs
Labels: release

#3407 docs(pycodestyle): document rules
  crates/ruff/src/rules/pycodestyle/rules/ambiguous_class_name.rs
  crates/ruff/src/rules/pycodestyle/rules/ambiguous_function_name.rs
  crates/ruff/src/rules/pycodestyle/rules/ambiguous_variable_name.rs
  crates/ruff/src/rules/pycodestyle/rules/compound_statements.rs
  crates/ruff/src/rules/pycodestyle/rules/doc_line_too_long.rs
  crates/ruff/src/rules/pycodestyle/rules/errors.rs
  crates/ruff/src/rules/pycodestyle/rules/extraneous_whitespace.rs
  crates/ruff/src/rules/pycodestyle/rules/imports.rs
  crates/ruff/src/rules/pycodestyle/rules/indentation.rs
  crates/ruff/src/rules/pycodestyle/rules/invalid_escape_sequence.rs
  crates/ruff/src/rules/pycodestyle/rules/lambda_assignment.rs
  crates/ruff/src/rules/pycodestyle/rules/line_too_long.rs
  crates/ruff/src/rules/pycodestyle/rules/literal_comparisons.rs
  crates/ruff/src/rules/pycodestyle/rules/mixed_spaces_and_tabs.rs
  crates/ruff/src/rules/pycodestyle/rules/no_newline_at_end_of_file.rs
  crates/ruff/src/rules/pycodestyle/rules/not_tests.rs
  crates/ruff/src/rules/pycodestyle/rules/space_around_operator.rs
  crates/ruff/src/rules/pycodestyle/rules/trailing_whitespace.rs
  crates/ruff/src/rules/pycodestyle/rules/type_comparison.rs
  crates/ruff/src/rules/pycodestyle/rules/whitespace_around_keywords.rs
  crates/ruff/src/rules/pycodestyle/rules/whitespace_before_comment.rs
Labels: documentation

#3448 Flag deprecated (but renamed) imports in UP035
  crates/ruff/resources/test/fixtures/pyupgrade/UP035.py
  crates/ruff/src/checkers/ast/mod.rs
  crates/ruff/src/codes.rs
  crates/ruff/src/registry.rs
  crates/ruff/src/rules/pyupgrade/mod.rs
  crates/ruff/src/rules/pyupgrade/rules/deprecated_import.rs
  crates/ruff/src/rules/pyupgrade/rules/mod.rs
  crates/ruff/src/rules/pyupgrade/snapshots/ruff__rules__pyupgrade__tests__UP035.py.snap
Labels: rule

#3433 refactor: Replace `Vec` in options metadata with static array
  crates/ruff/Cargo.toml
  crates/ruff/src/registry.rs
  crates/ruff/src/settings/options_base.rs
  crates/ruff_cli/src/commands/config.rs
  crates/ruff_dev/src/generate_docs.rs
  crates/ruff_dev/src/generate_options.rs
  crates/ruff_macros/src/config.rs
Labels: internal

#3449 pylint: W1508 invalid-envvar-default
  crates/ruff/resources/test/fixtures/pylint/invalid_envvar_default.py
  crates/ruff/src/checkers/ast/mod.rs
  crates/ruff/src/codes.rs
  crates/ruff/src/registry.rs
  crates/ruff/src/rules/pylint/mod.rs
  crates/ruff/src/rules/pylint/rules/invalid_envvar_default.rs
  crates/ruff/src/rules/pylint/rules/mod.rs
  crates/ruff/src/rules/pylint/snapshots/ruff__rules__pylint__tests__PLW1508_invalid_envvar_default.py.snap
  ruff.schema.json
Labels: rule

#3459 [FIX] PYI011: recognize `Bool` / `Float` / `Complex` numbers as simple defaults
  crates/ruff/resources/test/fixtures/flake8_pyi/PYI014.pyi
  crates/ruff/src/rules/flake8_pyi/rules/simple_defaults.rs
Labels: bug

#3467 pylint: E1507 invalid-envvar-value
  crates/ruff/resources/test/fixtures/pylint/invalid_envvar_value.py
  crates/ruff/src/checkers/ast/mod.rs
  crates/ruff/src/codes.rs
  crates/ruff/src/registry.rs
  crates/ruff/src/rules/pylint/mod.rs
  crates/ruff/src/rules/pylint/rules/invalid_envvar_value.rs
  crates/ruff/src/rules/pylint/rules/mod.rs
  crates/ruff/src/rules/pylint/snapshots/ruff__rules__pylint__tests__PLE1507_invalid_envvar_value.py.snap
  ruff.schema.json
Labels: rule

#3474 Respect ignores for runtime-import-in-type-checking-block (TCH004)
  crates/ruff/src/checkers/ast/mod.rs
Labels: bug

#3476 Remove unnecessary `Path::new` from `fs` calls
  crates/ruff/src/settings/configuration.rs
  crates/ruff/src/settings/types.rs
  crates/ruff/src/test.rs
  crates/ruff_cli/src/printer.rs
Labels: internal

#3481 Upgrade RustPython to fix Serde dependency
  Cargo.lock
  Cargo.toml
  crates/ruff_python_ast/Cargo.toml
Labels: internal

#3478 refactor(ruff_python_ast): Split `get_argument`
  crates/ruff/src/rules/flake8_bandit/rules/bad_file_permissions.rs
  crates/ruff/src/rules/flake8_bandit/rules/hashlib_insecure_hash_functions.rs
  crates/ruff/src/rules/flake8_bandit/rules/jinja2_autoescape_false.rs
  crates/ruff/src/rules/flake8_bandit/rules/logging_config_insecure_listen.rs
  crates/ruff/src/rules/flake8_bandit/rules/request_with_no_cert_validation.rs
  crates/ruff/src/rules/flake8_bandit/rules/request_without_timeout.rs
  crates/ruff/src/rules/flake8_bandit/rules/snmp_insecure_version.rs
  crates/ruff/src/rules/flake8_bandit/rules/unsafe_yaml_load.rs
  crates/ruff/src/rules/flake8_logging_format/rules.rs
  crates/ruff/src/rules/flake8_pytest_style/rules/fail.rs
  crates/ruff/src/rules/flake8_pytest_style/rules/patch.rs
  crates/ruff/src/rules/pylint/rules/logging.rs
  crates/ruff_python_ast/src/helpers.rs
Labels: internal

#3484 PYI011: allow `math` constants in defaults
  crates/ruff/resources/test/fixtures/flake8_pyi/PYI011.pyi
  crates/ruff/src/rules/flake8_pyi/rules/simple_defaults.rs
  crates/ruff/src/rules/flake8_pyi/snapshots/ruff__rules__flake8_pyi__tests__PYI011_PYI011.pyi.snap
Labels: bug

#3500 Ensure that redirect warnings appear exactly once per code
  crates/ruff/src/logging.rs
  crates/ruff/src/settings/mod.rs
Labels: bug

#3516 Allow f-strings and concatenations in os.getenv
  crates/ruff/resources/test/fixtures/pylint/invalid_envvar_default.py
  crates/ruff/resources/test/fixtures/pylint/invalid_envvar_value.py
  crates/ruff/src/rules/pylint/rules/invalid_envvar_default.rs
  crates/ruff/src/rules/pylint/rules/invalid_envvar_value.rs
  crates/ruff/src/rules/pylint/snapshots/ruff__rules__pylint__tests__PLE1507_invalid_envvar_value.py.snap
  crates/ruff/src/rules/pylint/snapshots/ruff__rules__pylint__tests__PLW1508_invalid_envvar_default.py.snap
Labels: bug

#3518 Allow string percent formatting in os.getenv
  crates/ruff/resources/test/fixtures/pylint/invalid_envvar_default.py
  crates/ruff/src/rules/pylint/rules/invalid_envvar_default.rs
  crates/ruff/src/rules/pylint/rules/invalid_envvar_value.rs
Labels: bug

#3519 Refine complexity rules for try-except-else-finally
  crates/ruff/src/rules/mccabe/rules.rs
  crates/ruff/src/rules/mccabe/snapshots/ruff__rules__mccabe__tests__max_complexity_0.snap
Labels: bug

#3521 Replicate inline comments when splitting single-line imports
  crates/ruff/resources/test/fixtures/isort/force_single_line.py
  crates/ruff/src/rules/isort/mod.rs
  crates/ruff/src/rules/isort/snapshots/ruff__rules__isort__tests__force_single_line_force_single_line.py.snap
Labels: bug

#3527 Avoid PEP 604 isinstance errors for starred tuples
  crates/ruff/resources/test/fixtures/pyupgrade/UP038.py
  crates/ruff/src/rules/pyupgrade/rules/use_pep604_isinstance.rs
Labels: bug

#3530 Avoid tracking as-imports separately with force-single-line
  crates/ruff/resources/test/fixtures/isort/force_single_line.py
  crates/ruff/src/rules/isort/mod.rs
  crates/ruff/src/rules/isort/normalize.rs
  crates/ruff/src/rules/isort/snapshots/ruff__rules__isort__tests__force_single_line_force_single_line.py.snap
Labels: bug

#3566 Rewrite mock import with starred imports
  crates/ruff/resources/test/fixtures/pyupgrade/UP026.py
  crates/ruff/src/rules/pyupgrade/rules/rewrite_mock_import.rs
  crates/ruff/src/rules/pyupgrade/snapshots/ruff__rules__pyupgrade__tests__UP026.py.snap
Labels: bug

#3572 Scope and Binding IDs
  crates/ruff/src/checkers/ast/deferred.rs
  crates/ruff/src/checkers/ast/mod.rs
  crates/ruff/src/rules/flake8_bugbear/rules/cached_instance_method.rs
  crates/ruff/src/rules/flake8_bugbear/rules/unused_loop_control_variable.rs
  crates/ruff/src/rules/flake8_simplify/rules/ast_unary_op.rs
  crates/ruff/src/rules/flake8_type_checking/helpers.rs
  crates/ruff/src/rules/flake8_unused_arguments/rules.rs
  crates/ruff/src/rules/pycodestyle/rules/lambda_assignment.rs
  crates/ruff/src/rules/pyflakes/rules/return_outside_function.rs
  crates/ruff/src/rules/pyflakes/rules/undefined_local.rs
  crates/ruff/src/rules/pyflakes/rules/unused_annotation.rs
  crates/ruff/src/rules/pyflakes/rules/unused_variable.rs
  crates/ruff/src/rules/pyflakes/rules/yield_outside_function.rs
  crates/ruff/src/rules/pylint/helpers.rs
  crates/ruff/src/rules/pylint/rules/await_outside_async.rs
  crates/ruff/src/rules/pylint/rules/consider_using_sys_exit.rs
  crates/ruff/src/rules/pylint/rules/global_statement.rs
  crates/ruff/src/rules/pylint/rules/used_prior_global_declaration.rs
  crates/ruff/src/rules/pyupgrade/rules/super_call_with_parameters.rs
  crates/ruff/src/rules/pyupgrade/rules/useless_object_inheritance.rs
  crates/ruff_python_ast/src/context.rs
  crates/ruff_python_ast/src/types.rs
Labels: internal

#3573 refactor: Move scope and binding types to `scope.rs`
  crates/ruff/src/checkers/ast/deferred.rs
  crates/ruff/src/checkers/ast/mod.rs
  crates/ruff/src/rules/flake8_bugbear/rules/cached_instance_method.rs
  crates/ruff/src/rules/flake8_bugbear/rules/unused_loop_control_variable.rs
  crates/ruff/src/rules/flake8_self/rules/private_member_access.rs
  crates/ruff/src/rules/flake8_simplify/rules/ast_unary_op.rs
  crates/ruff/src/rules/flake8_type_checking/helpers.rs
  crates/ruff/src/rules/flake8_type_checking/rules/runtime_import_in_type_checking_block.rs
  crates/ruff/src/rules/flake8_type_checking/rules/typing_only_runtime_import.rs
  crates/ruff/src/rules/flake8_unused_arguments/rules.rs
  crates/ruff/src/rules/pandas_vet/rules/check_attr.rs
  crates/ruff/src/rules/pandas_vet/rules/check_call.rs
  crates/ruff/src/rules/pep8_naming/rules/dunder_function_name.rs
  crates/ruff/src/rules/pep8_naming/rules/invalid_first_argument_name_for_class_method.rs
  crates/ruff/src/rules/pep8_naming/rules/invalid_first_argument_name_for_method.rs
  crates/ruff/src/rules/pycodestyle/rules/lambda_assignment.rs
  crates/ruff/src/rules/pyflakes/rules/return_outside_function.rs
  crates/ruff/src/rules/pyflakes/rules/undefined_export.rs
  crates/ruff/src/rules/pyflakes/rules/undefined_local.rs
  crates/ruff/src/rules/pyflakes/rules/unused_annotation.rs
  crates/ruff/src/rules/pyflakes/rules/unused_variable.rs
  crates/ruff/src/rules/pyflakes/rules/yield_outside_function.rs
  crates/ruff/src/rules/pylint/helpers.rs
  crates/ruff/src/rules/pylint/rules/await_outside_async.rs
  crates/ruff/src/rules/pylint/rules/consider_using_sys_exit.rs
  crates/ruff/src/rules/pylint/rules/global_statement.rs
  crates/ruff/src/rules/pylint/rules/used_prior_global_declaration.rs
  crates/ruff/src/rules/pyupgrade/rules/super_call_with_parameters.rs
  crates/ruff/src/rules/pyupgrade/rules/useless_object_inheritance.rs
  crates/ruff_python_ast/src/context.rs
  crates/ruff_python_ast/src/function_type.rs
  crates/ruff_python_ast/src/helpers.rs
  crates/ruff_python_ast/src/lib.rs
  crates/ruff_python_ast/src/operations.rs
  crates/ruff_python_ast/src/scope.rs
  crates/ruff_python_ast/src/types.rs
Labels: internal

#3582 Respect `type` overrides in E721
  crates/ruff/resources/test/fixtures/pycodestyle/E721.py
  crates/ruff/src/checkers/ast/mod.rs
  crates/ruff/src/rules/pycodestyle/rules/type_comparison.rs
Labels: bug

#3550 [`flake8-bugbear`] Add `no-explicit-stacklevel` (`B028`)
  crates/ruff/resources/test/fixtures/flake8_bugbear/B028.py
  crates/ruff/src/checkers/ast/mod.rs
  crates/ruff/src/codes.rs
  crates/ruff/src/registry.rs
  crates/ruff/src/rules/flake8_bugbear/mod.rs
  crates/ruff/src/rules/flake8_bugbear/rules/mod.rs
  crates/ruff/src/rules/flake8_bugbear/rules/no_explicit_stacklevel.rs
  crates/ruff/src/rules/flake8_bugbear/snapshots/ruff__rules__flake8_bugbear__tests__B028_B028.py.snap
  ruff.schema.json
Labels: rule

#3552 [`pylint`] invalid-characters-*
  crates/ruff/resources/test/fixtures/pylint/invalid_characters.py
  crates/ruff/src/checkers/tokens.rs
  crates/ruff/src/codes.rs
  crates/ruff/src/registry.rs
  crates/ruff/src/rules/pylint/mod.rs
  crates/ruff/src/rules/pylint/rules/invalid_string_characters.rs
  crates/ruff/src/rules/pylint/rules/mod.rs
  crates/ruff/src/rules/pylint/snapshots/ruff__rules__pylint__tests__PLE2510_invalid_characters.py.snap
  crates/ruff/src/rules/pylint/snapshots/ruff__rules__pylint__tests__PLE2512_invalid_characters.py.snap
  crates/ruff/src/rules/pylint/snapshots/ruff__rules__pylint__tests__PLE2513_invalid_characters.py.snap
  crates/ruff/src/rules/pylint/snapshots/ruff__rules__pylint__tests__PLE2514_invalid_characters.py.snap
  crates/ruff/src/rules/pylint/snapshots/ruff__rules__pylint__tests__PLE2515_invalid_characters.py.snap
  crates/ruff/src/settings/rule_table.rs
  ruff.schema.json
Labels: rule

#3116 [pylint] R1711: useless-return
  crates/ruff/resources/test/fixtures/pylint/useless_return.py
  crates/ruff/src/checkers/ast/mod.rs
  crates/ruff/src/codes.rs
  crates/ruff/src/registry.rs
  crates/ruff/src/rules/pylint/mod.rs
  crates/ruff/src/rules/pylint/rules/mod.rs
  crates/ruff/src/rules/pylint/rules/useless_return.rs
  crates/ruff/src/rules/pylint/snapshots/ruff__rules__pylint__tests__PLR1711_useless_return.py.snap
  ruff.schema.json
Labels: rule

#3592 Re-add the list of supported plugins to the README
  README.md
  docs/faq.md
Labels: documentation

#3588 Check exclusions prior to resolving `pyproject.toml` files
  crates/ruff/src/resolver.rs
Labels: bug

#3590 Reduce usage of ALL in ecosystem CI
  scripts/check_ecosystem.py
Labels: internal

#3596 Fix D417 false positive
  crates/ruff/resources/test/fixtures/pydocstyle/D417.py
  crates/ruff/src/rules/pydocstyle/rules/sections.rs
Labels: bug

#3589 Avoid removing comment hash for noqa's with trailing content
  crates/ruff/resources/test/fixtures/ruff/RUF100_3.py
  crates/ruff/src/checkers/noqa.rs
  crates/ruff/src/rules/ruff/snapshots/ruff__rules__ruff__tests__ruf100_3.snap
Labels: bug

#3601 Use `any_enabled` in AST checker
  crates/ruff/src/checkers/ast/mod.rs
Labels: internal

#3607 Change broken links in README to beta.ruff.rs
  BREAKING_CHANGES.md
  crates/flake8_to_ruff/README.md
  docs/faq.md
Labels: documentation

#3509 Gracefully handle lint panics
  Cargo.toml
  crates/ruff_cli/src/commands/linter.rs
  crates/ruff_cli/src/commands/run.rs
  crates/ruff_cli/src/lib.rs
  crates/ruff_cli/src/panic.rs
Labels: performance, cli

#3584 Avoid panics for implicitly-concatenated docstrings
  crates/ruff/resources/test/fixtures/pydocstyle/sections.py
  crates/ruff/src/checkers/ast/mod.rs
  crates/ruff/src/docstrings/extraction.rs
  crates/ruff/src/rules/pydocstyle/helpers.rs
  crates/ruff/src/rules/pyupgrade/rules/f_strings.rs
  crates/ruff/src/rules/pyupgrade/rules/native_literals.rs
  crates/ruff_python_ast/src/str.rs
Labels: bug, docstring

#3609 Fix infinite loop due to rules `D207` & `W605`
  crates/ruff/src/rules/pycodestyle/rules/invalid_escape_sequence.rs
  crates/ruff/src/rules/pycodestyle/snapshots/ruff__rules__pycodestyle__tests__W605_W605_0.py.snap
  crates/ruff/src/rules/pycodestyle/snapshots/ruff__rules__pycodestyle__tests__W605_W605_1.py.snap
Labels: bug

#3605 feat: update C416 with dict comprehension (autofixable)
  crates/ruff/resources/test/fixtures/flake8_comprehensions/C416.py
  crates/ruff/src/checkers/ast/mod.rs
  crates/ruff/src/rules/flake8_comprehensions/fixes.rs
  crates/ruff/src/rules/flake8_comprehensions/rules/helpers.rs
  crates/ruff/src/rules/flake8_comprehensions/rules/mod.rs
  crates/ruff/src/rules/flake8_comprehensions/rules/unnecessary_call_around_sorted.rs
  crates/ruff/src/rules/flake8_comprehensions/rules/unnecessary_collection_call.rs
  crates/ruff/src/rules/flake8_comprehensions/rules/unnecessary_comprehension.rs
  crates/ruff/src/rules/flake8_comprehensions/rules/unnecessary_double_cast_or_process.rs
  crates/ruff/src/rules/flake8_comprehensions/rules/unnecessary_map.rs
  crates/ruff/src/rules/flake8_comprehensions/rules/unnecessary_subscript_reversal.rs
  crates/ruff/src/rules/flake8_comprehensions/snapshots/ruff__rules__flake8_comprehensions__tests__C416_C416.py.snap
Labels: rule

#3635 Avoid trimming escaped whitespace in D210
  crates/ruff/src/rules/pydocstyle/helpers.rs
  crates/ruff/src/rules/pydocstyle/rules/no_surrounding_whitespace.rs
Labels: bug, docstring

#3636 Handle `UP032` autofix with adjacent keywords
  crates/ruff/resources/test/fixtures/pyupgrade/UP032.py
  crates/ruff/src/rules/pyupgrade/rules/f_strings.rs
  crates/ruff/src/rules/pyupgrade/snapshots/ruff__rules__pyupgrade__tests__UP032.py.snap
Labels: bug

#3616 Use language: system for Rust hooks
  .pre-commit-config.yaml
Labels: internal

#3600 Convert single-argument %-style format calls
  crates/ruff/resources/test/fixtures/pyupgrade/UP031_0.py
  crates/ruff/resources/test/fixtures/pyupgrade/UP031_1.py
  crates/ruff/src/rules/pyupgrade/rules/printf_string_formatting.rs
  crates/ruff/src/rules/pyupgrade/snapshots/ruff__rules__pyupgrade__tests__UP031_0.py.snap
Labels: rule

#3613 Add autofix functionality for `F523` (#3613)
  crates/ruff/resources/test/fixtures/pyflakes/F523.py
  crates/ruff/src/cst/matchers.rs
  crates/ruff/src/rules/pyflakes/fixes.rs
  crates/ruff/src/rules/pyflakes/format.rs
  crates/ruff/src/rules/pyflakes/rules/strings.rs
  crates/ruff/src/rules/pyflakes/snapshots/ruff__rules__pyflakes__tests__F523_F523.py.snap
Labels: autofix

#3239 [`flake8-bandit`]: Implement deny-list rules for suspicious member calls
  crates/ruff/resources/test/fixtures/flake8_bandit/S301.py
  crates/ruff/resources/test/fixtures/flake8_bandit/S312.py
  crates/ruff/src/checkers/ast/mod.rs
  crates/ruff/src/codes.rs
  crates/ruff/src/registry.rs
  crates/ruff/src/rules/flake8_bandit/mod.rs
  crates/ruff/src/rules/flake8_bandit/rules/mod.rs
  crates/ruff/src/rules/flake8_bandit/rules/suspicious_function_call.rs
  crates/ruff/src/rules/flake8_bandit/snapshots/ruff__rules__flake8_bandit__tests__S301_S301.py.snap
  crates/ruff/src/rules/flake8_bandit/snapshots/ruff__rules__flake8_bandit__tests__S312_S312.py.snap
  ruff.schema.json
Labels: rule

#3654 Avoid `RUF007` fixes for more than two arguments
  crates/ruff/resources/test/fixtures/ruff/RUF007.py
  crates/ruff/src/checkers/ast/mod.rs
  crates/ruff/src/rules/ruff/rules/pairwise_over_zipped.rs
  crates/ruff/src/rules/ruff/snapshots/ruff__rules__ruff__tests__ruff_pairwise_over_zipped.snap
Labels: bug

#3664 Remove linked issue from `flake8-django`
  README.md
  docs/faq.md
Labels: documentation

#3669 Allow `pairwise` diagnostics for `zip(..., strict=True)`
  crates/ruff/resources/test/fixtures/ruff/RUF007.py
  crates/ruff/src/checkers/ast/mod.rs
  crates/ruff/src/rules/ruff/rules/pairwise_over_zipped.rs
  crates/ruff/src/rules/ruff/snapshots/ruff__rules__ruff__tests__ruff_pairwise_over_zipped.snap
Labels: bug

#3670 Refactor out common exemption-parsing logic
  crates/ruff/src/checkers/noqa.rs
  crates/ruff/src/noqa.rs
Labels: internal

#3688 Avoid nested loops in missing_whitespace
  crates/ruff/src/rules/pycodestyle/rules/missing_whitespace.rs
Labels: performance

#3455 Expand the scope of useless-expression (B018)
  crates/ruff/resources/test/fixtures/flake8_bugbear/B018.py
  crates/ruff/src/checkers/ast/mod.rs
  crates/ruff/src/rules/flake8_bugbear/rules/useless_comparison.rs
  crates/ruff/src/rules/flake8_bugbear/rules/useless_expression.rs
  crates/ruff/src/rules/flake8_bugbear/snapshots/ruff__rules__flake8_bugbear__tests__B018_B018.py.snap
  crates/ruff/src/rules/flake8_simplify/snapshots/ruff__rules__flake8_simplify__tests__SIM401_SIM401.py.snap
  crates/ruff/src/rules/pyflakes/snapshots/ruff__rules__pyflakes__tests__F841_F841_0.py.snap
  crates/ruff_python_ast/src/helpers.rs
Labels: rule

#3698 Avoid parsing `ForwardRef` contents as type references
  crates/ruff/resources/test/fixtures/pyflakes/F821_13.py
  crates/ruff/src/checkers/ast/mod.rs
  crates/ruff/src/rules/pyflakes/mod.rs
  crates/ruff/src/rules/pyflakes/snapshots/ruff__rules__pyflakes__tests__F821_F821_13.py.snap
  crates/ruff_python_ast/src/typing.rs
Labels: bug

#3718 Allow aliased `logging` module as a logger candidate
  crates/ruff/resources/test/fixtures/flake8_logging_format/G001.py
  crates/ruff/src/rules/flake8_blind_except/rules.rs
  crates/ruff/src/rules/flake8_logging_format/rules.rs
  crates/ruff/src/rules/flake8_logging_format/snapshots/ruff__rules__flake8_logging_format__tests__G001.py.snap
  crates/ruff/src/rules/pylint/rules/logging.rs
  crates/ruff/src/rules/tryceratops/helpers.rs
  crates/ruff/src/rules/tryceratops/rules/error_instead_of_exception.rs
  crates/ruff/src/rules/tryceratops/rules/verbose_log_message.rs
  crates/ruff_python_ast/src/helpers.rs
Labels: rule

#3729 [`flake8-pyi`] Add autofix for `PYI014`
  crates/ruff/src/rules/flake8_pyi/rules/simple_defaults.rs
  crates/ruff/src/rules/flake8_pyi/snapshots/ruff__rules__flake8_pyi__tests__PYI011_PYI011.pyi.snap
  crates/ruff/src/rules/flake8_pyi/snapshots/ruff__rules__flake8_pyi__tests__PYI014_PYI014.pyi.snap
Labels: rule

#3728 [`flake8-pyi`] Implement `PYI015`
  crates/ruff/resources/test/fixtures/flake8_pyi/PYI015.py
  crates/ruff/resources/test/fixtures/flake8_pyi/PYI015.pyi
  crates/ruff/src/checkers/ast/mod.rs
  crates/ruff/src/codes.rs
  crates/ruff/src/registry.rs
  crates/ruff/src/rules/flake8_pyi/mod.rs
  crates/ruff/src/rules/flake8_pyi/rules/mod.rs
  crates/ruff/src/rules/flake8_pyi/rules/simple_defaults.rs
  crates/ruff/src/rules/flake8_pyi/snapshots/ruff__rules__flake8_pyi__tests__PYI015_PYI015.py.snap
  crates/ruff/src/rules/flake8_pyi/snapshots/ruff__rules__flake8_pyi__tests__PYI015_PYI015.pyi.snap
  ruff.schema.json
Labels: rule

#3725 Improve add_rule.py and add_plugin.py scripts
  .github/workflows/ci.yaml
  scripts/_utils.py
  scripts/add_plugin.py
  scripts/add_rule.py
Labels: internal

#3733 Add a note on `src`
  docs/faq.md
Labels: documentation, isort

#3731 [`pydocstyle`] Implement autofix for `D403`
  crates/ruff/resources/test/fixtures/pydocstyle/D403.py
  crates/ruff/src/rules/pydocstyle/mod.rs
  crates/ruff/src/rules/pydocstyle/rules/capitalized.rs
  crates/ruff/src/rules/pydocstyle/snapshots/ruff__rules__pydocstyle__tests__D403_D403.py.snap
Labels: autofix

#3739 Use `wild::args()` and add `wild` as a dependency
  Cargo.lock
  crates/ruff_cli/Cargo.toml
  crates/ruff_cli/src/bin/ruff.rs
Labels: cli

#3740 Fix SIM222 and SIM223 false negative
  crates/ruff/resources/test/fixtures/flake8_simplify/SIM222.py
  crates/ruff/resources/test/fixtures/flake8_simplify/SIM223.py
  crates/ruff/src/rules/flake8_simplify/rules/ast_bool_op.rs
  crates/ruff/src/rules/flake8_simplify/snapshots/ruff__rules__flake8_simplify__tests__SIM222_SIM222.py.snap
  crates/ruff/src/rules/flake8_simplify/snapshots/ruff__rules__flake8_simplify__tests__SIM223_SIM223.py.snap
Labels: rule

#3753 Move `fix::FixMode` to `flags::FixMode`
  crates/ruff/src/fix.rs
  crates/ruff/src/lib.rs
  crates/ruff/src/settings/flags.rs
  crates/ruff_cli/src/commands/run.rs
  crates/ruff_cli/src/commands/run_stdin.rs
  crates/ruff_cli/src/diagnostics.rs
  crates/ruff_cli/src/lib.rs
  crates/ruff_cli/src/printer.rs
Labels: internal

#3771 Include `with` statements in complexity calculation
  crates/ruff/src/rules/mccabe/rules.rs
Labels: bug

#3773 Set parents even in same-line cases
  crates/ruff/src/checkers/ast/mod.rs
  crates/ruff/src/checkers/noqa.rs
  crates/ruff/src/noqa.rs
  crates/ruff/src/rules/pyflakes/snapshots/ruff__rules__pyflakes__tests__F401_F401_11.py.snap
  crates/ruff/src/rules/pyflakes/snapshots/ruff__rules__pyflakes__tests__F401_F401_5.py.snap
  crates/ruff/src/rules/pyflakes/snapshots/ruff__rules__pyflakes__tests__F401_F401_6.py.snap
  crates/ruff/src/rules/pyflakes/snapshots/ruff__rules__pyflakes__tests__F401_F401_7.py.snap
  crates/ruff/src/rules/pyflakes/snapshots/ruff__rules__pyflakes__tests__F401_F401_9.py.snap
  crates/ruff/src/rules/ruff/snapshots/ruff__rules__ruff__tests__ruf100_1.snap
Labels: internal

#3775 Rename `end_of_statement` to `end_of_last_statement`
  crates/ruff/src/rules/flake8_return/helpers.rs
  crates/ruff/src/rules/flake8_return/rules.rs
  crates/ruff_python_ast/src/helpers.rs
Labels: internal

#3789 Clarify order of `pre-commit` hooks
  docs/usage.md
Labels: documentation

#3785 Implement `flake8-gettext`
  LICENSE
  README.md
  crates/ruff/resources/test/fixtures/flake8_gettext/INT001.py
  crates/ruff/resources/test/fixtures/flake8_gettext/INT002.py
  crates/ruff/resources/test/fixtures/flake8_gettext/INT003.py
  crates/ruff/src/checkers/ast/mod.rs
  crates/ruff/src/codes.rs
  crates/ruff/src/registry.rs
  crates/ruff/src/rules/flake8_gettext/mod.rs
  crates/ruff/src/rules/flake8_gettext/rules.rs
  crates/ruff/src/rules/flake8_gettext/settings.rs
  crates/ruff/src/rules/flake8_gettext/snapshots/ruff__rules__flake8_gettext__tests__f-string-in-get-text-func-call_INT001.py.snap
  crates/ruff/src/rules/flake8_gettext/snapshots/ruff__rules__flake8_gettext__tests__format-in-get-text-func-call_INT002.py.snap
  crates/ruff/src/rules/flake8_gettext/snapshots/ruff__rules__flake8_gettext__tests__printf-in-get-text-func-call_INT003.py.snap
  crates/ruff/src/rules/mod.rs
  crates/ruff/src/settings/configuration.rs
  crates/ruff/src/settings/defaults.rs
  crates/ruff/src/settings/mod.rs
  crates/ruff/src/settings/options.rs
  crates/ruff_wasm/src/lib.rs
  docs/faq.md
  ruff.schema.json
Labels: plugin

#3790 Enumerate all codes in default configuration example
  README.md
  docs/configuration.md
Labels: documentation

#3800 Add flymake-ruff to docs
  docs/editor-integrations.md
Labels: documentation

#3796 Allow `TID252` to fix all valid module paths
  crates/ruff/resources/test/fixtures/flake8_tidy_imports/TID252/my_package/sublib/api/application.py
  crates/ruff/resources/test/fixtures/flake8_tidy_imports/TID252/my_package/sublib/protocol/UpperCaseModule.py
  crates/ruff/src/rules/flake8_tidy_imports/relative_imports.rs
  crates/ruff/src/rules/flake8_tidy_imports/snapshots/ruff__rules__flake8_tidy_imports__relative_imports__tests__ban_parent_imports_package.snap
Labels: bug

#3802 Improve robustness of argument removal for `encode` calls
  crates/ruff/resources/test/fixtures/pyupgrade/UP012.py
  crates/ruff/src/rules/pyupgrade/rules/unnecessary_encode_utf8.rs
  crates/ruff/src/rules/pyupgrade/snapshots/ruff__rules__pyupgrade__tests__UP012.py.snap
Labels: bug

#3732 Ignore `collapsible-if` violations for `if False:` and `if True:`
  crates/ruff/resources/test/fixtures/flake8_simplify/SIM102.py
  crates/ruff/src/rules/flake8_simplify/rules/ast_if.rs
  crates/ruff/src/rules/flake8_simplify/snapshots/ruff__rules__flake8_simplify__tests__SIM102_SIM102.py.snap
Labels: rule

#3824 Extend `unncessary-generator-any-all` to set comprehensions
  crates/ruff/resources/test/fixtures/flake8_pie/PIE802.py
  crates/ruff/src/rules/flake8_pie/rules.rs
  crates/ruff/src/rules/flake8_pie/snapshots/ruff__rules__flake8_pie__tests__PIE802_PIE802.py.snap
Labels: rule

#3834 Move keyword checks into `is_identifier`
  crates/ruff/src/rules/flake8_bugbear/rules/getattr_with_constant.rs
  crates/ruff/src/rules/flake8_bugbear/rules/setattr_with_constant.rs
  crates/ruff/src/rules/flake8_pie/rules.rs
  crates/ruff/src/rules/flake8_tidy_imports/relative_imports.rs
  crates/ruff/src/rules/pyupgrade/rules/convert_named_tuple_functional_to_class.rs
  crates/ruff/src/rules/pyupgrade/rules/convert_typed_dict_functional_to_class.rs
  crates/ruff/src/rules/pyupgrade/rules/printf_string_formatting.rs
  crates/ruff_python_stdlib/src/identifiers.rs
  crates/ruff_python_stdlib/src/keyword.rs
Labels: internal
