Repository astral-sh/ruff, pull requests merged in 2023-07, with the labels that each got.

#5467 Detect consecutive, non-newline-delimited NumPy sections
  crates/ruff/resources/test/fixtures/pydocstyle/D410.py
  crates/ruff/src/checkers/ast/mod.rs
  crates/ruff/src/docstrings/sections.rs
  crates/ruff/src/rules/pydocstyle/mod.rs
  crates/ruff/src/rules/pydocstyle/snapshots/ruff__rules__pydocstyle__tests__D410_D410.py.snap
Labels: bug, docstring

#5468 [`numpy`] Add `numpy-deprecated-function` (NPY003)
  crates/ruff/resources/test/fixtures/numpy/NPY002.py
  crates/ruff/resources/test/fixtures/numpy/NPY003.py
  crates/ruff/src/checkers/ast/mod.rs
  crates/ruff/src/codes.rs
  crates/ruff/src/rules/numpy/mod.rs
  crates/ruff/src/rules/numpy/rules/deprecated_function.rs
  crates/ruff/src/rules/numpy/rules/legacy_random.rs
  crates/ruff/src/rules/numpy/rules/mod.rs
  crates/ruff/src/rules/numpy/snapshots/ruff__rules__numpy__tests__numpy-deprecated-function_NPY003.py.snap
  crates/ruff/src/rules/numpy/snapshots/ruff__rules__numpy__tests__numpy-legacy-random_NPY002.py.snap
Labels: rule

#5469 [`flake8-django`] Skip duplicate violations in `DJ012`
  crates/ruff/resources/test/fixtures/flake8_django/DJ012.py
  crates/ruff/src/rules/flake8_django/rules/unordered_body_content_in_model.rs
  crates/ruff/src/rules/flake8_django/snapshots/ruff__rules__flake8_django__tests__DJ012_DJ012.py.snap
Labels: rule

#5470 [`pyupgrade`] Restore the `keep-runtime-typing` setting
  BREAKING_CHANGES.md
  crates/ruff/src/checkers/ast/mod.rs
  crates/ruff/src/rules/numpy/snapshots/ruff__rules__numpy__tests__numpy-deprecated-function_NPY003.py.snap
  crates/ruff/src/rules/pyupgrade/mod.rs
  crates/ruff/src/rules/pyupgrade/settings.rs
  crates/ruff/src/rules/pyupgrade/snapshots/ruff__rules__pyupgrade__tests__future_annotations_keep_runtime_typing_p310.snap
  crates/ruff/src/rules/pyupgrade/snapshots/ruff__rules__pyupgrade__tests__future_annotations_keep_runtime_typing_p37.snap
  crates/ruff/src/settings/configuration.rs
  crates/ruff/src/settings/defaults.rs
  crates/ruff/src/settings/mod.rs
  crates/ruff/src/settings/options.rs
  crates/ruff_wasm/src/lib.rs
  ruff.schema.json
Labels: configuration

#5298 [`perflint`] Add `PERF401` and `PERF402` rules
  crates/ruff/resources/test/fixtures/perflint/PERF401.py
  crates/ruff/resources/test/fixtures/perflint/PERF402.py
  crates/ruff/src/checkers/ast/mod.rs
  crates/ruff/src/codes.rs
  crates/ruff/src/rules/perflint/mod.rs
  crates/ruff/src/rules/perflint/rules/incorrect_dict_iterator.rs
  crates/ruff/src/rules/perflint/rules/manual_list_comprehension.rs
  crates/ruff/src/rules/perflint/rules/manual_list_copy.rs
  crates/ruff/src/rules/perflint/rules/mod.rs
  crates/ruff/src/rules/perflint/rules/unnecessary_list_cast.rs
  crates/ruff/src/rules/perflint/snapshots/ruff__rules__perflint__tests__PERF401_PERF401.py.snap
  crates/ruff/src/rules/perflint/snapshots/ruff__rules__perflint__tests__PERF402_PERF402.py.snap
  ruff.schema.json
  scripts/check_docs_formatted.py
  scripts/update_ambiguous_characters.py
Labels: rule

#5472 Reorganize some `flake8-pyi` rules
  crates/ruff/resources/test/fixtures/flake8_pyi/PYI002.py
  crates/ruff/resources/test/fixtures/flake8_pyi/PYI002.pyi
  crates/ruff/src/checkers/ast/mod.rs
  crates/ruff/src/rules/flake8_pyi/rules/bad_version_info_comparison.rs
  crates/ruff/src/rules/flake8_pyi/rules/complex_if_statement_in_stub.rs
  crates/ruff/src/rules/flake8_pyi/rules/mod.rs
  crates/ruff/src/rules/flake8_pyi/rules/unrecognized_platform.rs
  crates/ruff/src/rules/flake8_pyi/rules/unrecognized_version_info.rs
  crates/ruff/src/rules/flake8_pyi/snapshots/ruff__rules__flake8_pyi__tests__PYI002_PYI002.pyi.snap
  crates/ruff/src/rules/flake8_pyi/snapshots/ruff__rules__flake8_pyi__tests__PYI005_PYI005.pyi.snap
Labels: internal

#5480 Audit `remove_argument` usages to use end-of-function
  crates/ruff/resources/test/fixtures/pandas_vet/PD002.py
  crates/ruff/src/checkers/ast/mod.rs
  crates/ruff/src/rules/flake8_django/rules/model_without_dunder_str.rs
  crates/ruff/src/rules/flake8_django/snapshots/ruff__rules__flake8_django__tests__DJ008_DJ008.py.snap
  crates/ruff/src/rules/flake8_pytest_style/rules/fixture.rs
  crates/ruff/src/rules/pandas_vet/fixes.rs
  crates/ruff/src/rules/pandas_vet/mod.rs
  crates/ruff/src/rules/pandas_vet/rules/inplace_argument.rs
  crates/ruff/src/rules/pandas_vet/rules/pd_merge.rs
  crates/ruff/src/rules/pandas_vet/snapshots/ruff__rules__pandas_vet__tests__PD002_PD002.py.snap
  crates/ruff/src/rules/pyupgrade/rules/replace_stdout_stderr.rs
  crates/ruff/src/rules/pyupgrade/rules/unnecessary_class_parentheses.rs
  crates/ruff/src/rules/pyupgrade/rules/useless_object_inheritance.rs
Labels: internal

#5482 Remove some additional manual iterator matches
  crates/ruff/src/checkers/ast/mod.rs
  crates/ruff/src/rules/flake8_bandit/rules/request_with_no_cert_validation.rs
  crates/ruff/src/rules/flake8_django/rules/nullable_model_string_field.rs
  crates/ruff_python_semantic/src/analyze/function_type.rs
  crates/ruff_python_stdlib/src/identifiers.rs
  crates/ruff_python_stdlib/src/keyword.rs
Labels: internal, performance

#5484 Refine some `perflint` rules
  crates/ruff/resources/test/fixtures/perflint/PERF401.py
  crates/ruff/resources/test/fixtures/perflint/PERF402.py
  crates/ruff/src/checkers/ast/mod.rs
  crates/ruff/src/rules/perflint/rules/manual_list_comprehension.rs
  crates/ruff/src/rules/perflint/rules/manual_list_copy.rs
  crates/ruff/src/rules/perflint/snapshots/ruff__rules__perflint__tests__PERF401_PERF401.py.snap
  crates/ruff/src/rules/perflint/snapshots/ruff__rules__perflint__tests__PERF402_PERF402.py.snap
Labels: rule

#5490 Allow `Final` assignments in stubs
  crates/ruff/resources/test/fixtures/flake8_pyi/PYI015.py
  crates/ruff/resources/test/fixtures/flake8_pyi/PYI015.pyi
  crates/ruff/src/rules/flake8_pyi/rules/simple_defaults.rs
Labels: bug

#5506 Fix eval detection for suspicious-eval-usage
  crates/ruff/resources/test/fixtures/flake8_bandit/S307.py
  crates/ruff/src/checkers/ast/mod.rs
  crates/ruff/src/rules/flake8_bandit/mod.rs
  crates/ruff/src/rules/flake8_bandit/rules/exec_used.rs
  crates/ruff/src/rules/flake8_bandit/rules/suspicious_function_call.rs
  crates/ruff/src/rules/flake8_bandit/snapshots/ruff__rules__flake8_bandit__tests__S102_S102.py.snap
  crates/ruff/src/rules/flake8_bandit/snapshots/ruff__rules__flake8_bandit__tests__S307_S307.py.snap
Labels: bug

#5507 Update documentation to list double-quote preference first
  crates/ruff/src/rules/flake8_quotes/rules/from_tokens.rs
  crates/ruff/src/rules/flake8_quotes/settings.rs
  ruff.schema.json
Labels: documentation

#5508 Avoid PERF rules for iteration-dependent assignments
  crates/ruff/resources/test/fixtures/perflint/PERF401.py
  crates/ruff/resources/test/fixtures/perflint/PERF402.py
  crates/ruff/src/rules/perflint/rules/manual_list_comprehension.rs
  crates/ruff/src/rules/perflint/rules/manual_list_copy.rs
Labels: bug

#5501 [`pylint`] Implement Pylint `typevar-name-mismatch` (`C0132`)
  crates/ruff/resources/test/fixtures/pylint/type_param_name_mismatch.py
  crates/ruff/src/checkers/ast/mod.rs
  crates/ruff/src/codes.rs
  crates/ruff/src/rules/pylint/mod.rs
  crates/ruff/src/rules/pylint/rules/mod.rs
  crates/ruff/src/rules/pylint/rules/type_param_name_mismatch.rs
  crates/ruff/src/rules/pylint/snapshots/ruff__rules__pylint__tests__PLC0132_type_param_name_mismatch.py.snap
  ruff.schema.json
Labels: rule

#5511 Avoid returning first-match for rule prefixes
  crates/ruff/src/registry.rs
  crates/ruff_cli/src/commands/rule.rs
Labels: bug

#5059 Add `ruff rule --all` subcommand (with JSON output)
  crates/ruff_cli/src/args.rs
  crates/ruff_cli/src/commands/rule.rs
  crates/ruff_cli/src/lib.rs
  docs/configuration.md
Labels: cli

#5513 Add .ipynb_checkpoints, .pyenv, .pytest_cache, and .vscode to default excludes
  BREAKING_CHANGES.md
  crates/ruff/src/settings/defaults.rs
Labels: breaking, cli

#5518 Refactor the `unnecessary-map` (`C417`) implementation
  crates/ruff/resources/test/fixtures/flake8_comprehensions/C417.py
  crates/ruff/src/rules/flake8_comprehensions/fixes.rs
  crates/ruff/src/rules/flake8_comprehensions/rules/unnecessary_map.rs
  crates/ruff/src/rules/flake8_comprehensions/snapshots/ruff__rules__flake8_comprehensions__tests__C417_C417.py.snap
Labels: internal

#5522 Add some additional users to the README
  README.md
Labels: documentation

#5520 Avoid triggering `unnecessary-map` (`C417`) for late-bound lambdas
  crates/ruff/resources/test/fixtures/flake8_comprehensions/C417.py
  crates/ruff/src/rules/flake8_comprehensions/rules/unnecessary_map.rs
  crates/ruff/src/rules/flake8_comprehensions/snapshots/ruff__rules__flake8_comprehensions__tests__C417_C417.py.snap
Labels: bug

#5524 Avoid triggering DTZ001-006 when using `.astimezone()`
  crates/ruff/resources/test/fixtures/flake8_datetimez/DTZ001.py
  crates/ruff/resources/test/fixtures/flake8_datetimez/DTZ002.py
  crates/ruff/resources/test/fixtures/flake8_datetimez/DTZ003.py
  crates/ruff/resources/test/fixtures/flake8_datetimez/DTZ004.py
  crates/ruff/resources/test/fixtures/flake8_datetimez/DTZ005.py
  crates/ruff/resources/test/fixtures/flake8_datetimez/DTZ006.py
  crates/ruff/src/rules/flake8_datetimez/rules/call_datetime_fromtimestamp.rs
  crates/ruff/src/rules/flake8_datetimez/rules/call_datetime_now_without_tzinfo.rs
  crates/ruff/src/rules/flake8_datetimez/rules/call_datetime_today.rs
  crates/ruff/src/rules/flake8_datetimez/rules/call_datetime_utcfromtimestamp.rs
  crates/ruff/src/rules/flake8_datetimez/rules/call_datetime_utcnow.rs
  crates/ruff/src/rules/flake8_datetimez/rules/call_datetime_without_tzinfo.rs
  crates/ruff/src/rules/flake8_datetimez/rules/helpers.rs
  crates/ruff/src/rules/flake8_datetimez/rules/mod.rs
  crates/ruff/src/rules/flake8_datetimez/snapshots/ruff__rules__flake8_datetimez__tests__DTZ001_DTZ001.py.snap
  crates/ruff/src/rules/flake8_datetimez/snapshots/ruff__rules__flake8_datetimez__tests__DTZ002_DTZ002.py.snap
  crates/ruff/src/rules/flake8_datetimez/snapshots/ruff__rules__flake8_datetimez__tests__DTZ003_DTZ003.py.snap
  crates/ruff/src/rules/flake8_datetimez/snapshots/ruff__rules__flake8_datetimez__tests__DTZ004_DTZ004.py.snap
  crates/ruff/src/rules/flake8_datetimez/snapshots/ruff__rules__flake8_datetimez__tests__DTZ005_DTZ005.py.snap
  crates/ruff/src/rules/flake8_datetimez/snapshots/ruff__rules__flake8_datetimez__tests__DTZ006_DTZ006.py.snap
Labels: bug

#5517 [`pylint`] Implement Pylint `typevar-double-variance` (`C0131`)
  crates/ruff/resources/test/fixtures/pylint/type_bivariance.py
  crates/ruff/src/checkers/ast/mod.rs
  crates/ruff/src/codes.rs
  crates/ruff/src/rules/pylint/helpers.rs
  crates/ruff/src/rules/pylint/mod.rs
  crates/ruff/src/rules/pylint/rules/mod.rs
  crates/ruff/src/rules/pylint/rules/type_bivariance.rs
  crates/ruff/src/rules/pylint/rules/type_param_name_mismatch.rs
  crates/ruff/src/rules/pylint/snapshots/ruff__rules__pylint__tests__PLC0131_type_bivariance.py.snap
  ruff.schema.json
Labels: rule

#5536 Enable attribute lookups via semantic model
  crates/ruff/resources/test/fixtures/flake8_raise/RSE102.py
  crates/ruff/src/checkers/ast/mod.rs
  crates/ruff/src/renamer.rs
  crates/ruff/src/rules/flake8_raise/rules/unnecessary_paren_on_raise_exception.rs
  crates/ruff/src/rules/flake8_raise/snapshots/ruff__rules__flake8_raise__tests__unnecessary-paren-on-raise-exception_RSE102.py.snap
  crates/ruff_python_semantic/src/binding.rs
  crates/ruff_python_semantic/src/model.rs
Labels: bug

#5538 Avoid syntax errors when rewriting str(dict) in f-strings
  crates/ruff/resources/test/fixtures/ruff/RUF010.py
  crates/ruff/src/rules/pylint/rules/type_bivariance.rs
  crates/ruff/src/rules/pylint/rules/type_param_name_mismatch.rs
  crates/ruff/src/rules/ruff/rules/explicit_f_string_type_conversion.rs
  crates/ruff/src/rules/ruff/snapshots/ruff__rules__ruff__tests__RUF010_RUF010.py.snap
Labels: bug

#5540 Use Insiders version of `mkdocs-material`
  .github/workflows/ci.yaml
  .github/workflows/docs.yaml
  docs/requirements-insiders.txt
  docs/requirements.txt
Labels: documentation

#5535 Add debug-based snapshot tests for noqa directive parsing
  crates/ruff/src/noqa.rs
  crates/ruff/src/snapshots/ruff__noqa__tests__noqa_all.snap
  crates/ruff/src/snapshots/ruff__noqa__tests__noqa_all_case_insensitive.snap
  crates/ruff/src/snapshots/ruff__noqa__tests__noqa_all_multi_space.snap
  crates/ruff/src/snapshots/ruff__noqa__tests__noqa_all_no_space.snap
  crates/ruff/src/snapshots/ruff__noqa__tests__noqa_code.snap
  crates/ruff/src/snapshots/ruff__noqa__tests__noqa_code_case_insensitive.snap
  crates/ruff/src/snapshots/ruff__noqa__tests__noqa_code_multi_space.snap
  crates/ruff/src/snapshots/ruff__noqa__tests__noqa_code_no_space.snap
  crates/ruff/src/snapshots/ruff__noqa__tests__noqa_codes.snap
  crates/ruff/src/snapshots/ruff__noqa__tests__noqa_codes_case_insensitive.snap
  crates/ruff/src/snapshots/ruff__noqa__tests__noqa_codes_multi_space.snap
  crates/ruff/src/snapshots/ruff__noqa__tests__noqa_codes_no_space.snap
  crates/ruff/src/snapshots/ruff__noqa__tests__noqa_leading_space.snap
  crates/ruff/src/snapshots/ruff__noqa__tests__noqa_trailing_space.snap
Labels: internal

#5543 Remove `Directive::None` variant
  crates/ruff/src/checkers/noqa.rs
  crates/ruff/src/noqa.rs
  crates/ruff/src/snapshots/ruff__noqa__tests__noqa_all.snap
  crates/ruff/src/snapshots/ruff__noqa__tests__noqa_all_case_insensitive.snap
  crates/ruff/src/snapshots/ruff__noqa__tests__noqa_code.snap
  crates/ruff/src/snapshots/ruff__noqa__tests__noqa_code_case_insensitive.snap
  crates/ruff/src/snapshots/ruff__noqa__tests__noqa_codes.snap
  crates/ruff/src/snapshots/ruff__noqa__tests__noqa_codes_case_insensitive.snap
  crates/ruff/src/snapshots/ruff__noqa__tests__noqa_leading_space.snap
  crates/ruff/src/snapshots/ruff__noqa__tests__noqa_trailing_space.snap
Labels: internal

#5544 Add separate configuration for MkDocs Insiders plugins
  .github/workflows/ci.yaml
  .github/workflows/docs.yaml
  CONTRIBUTING.md
  crates/ruff_dev/src/generate_options.rs
  mkdocs.insiders.yml
  mkdocs.template.yml
Labels: documentation

#5546 Move `Directive` fields behind accessor methods
  crates/ruff/src/checkers/noqa.rs
  crates/ruff/src/noqa.rs
Labels: internal

#5547 Remove Directive's dependency on Locator
  crates/ruff/src/noqa.rs
Labels: internal

#5548 Replace stat mapping with match statement
  crates/ruff/src/rules/flake8_bandit/rules/bad_file_permissions.rs
Labels: internal

#5560 Add httpx into the `Who's Using Ruff?` section
  README.md
Labels: documentation

#5558 Try statements have a body: Fix formatter instability
  crates/ruff_python_ast/src/node.rs
  crates/ruff_python_formatter/resources/test/fixtures/ruff/statement/try.py
  crates/ruff_python_formatter/src/comments/placement.rs
Labels: formatter

#5563 docs: add user
  README.md
Labels: documentation

#5479 Add documentation to the `S1XX` rules
  crates/ruff/src/rules/flake8_bandit/rules/bad_file_permissions.rs
  crates/ruff/src/rules/flake8_bandit/rules/exec_used.rs
  crates/ruff/src/rules/flake8_bandit/rules/hardcoded_bind_all_interfaces.rs
  crates/ruff/src/rules/flake8_bandit/rules/hardcoded_password_default.rs
  crates/ruff/src/rules/flake8_bandit/rules/hardcoded_password_func_arg.rs
  crates/ruff/src/rules/flake8_bandit/rules/hardcoded_password_string.rs
  crates/ruff/src/rules/flake8_bandit/rules/hardcoded_tmp_directory.rs
  crates/ruff/src/rules/flake8_bandit/rules/request_without_timeout.rs
  crates/ruff/src/rules/flake8_bandit/rules/try_except_continue.rs
  crates/ruff/src/rules/flake8_bandit/rules/try_except_pass.rs
Labels: documentation

#5473 Support globbing in `isort` options
  crates/ruff/src/rules/isort/categorize.rs
  crates/ruff/src/rules/isort/mod.rs
  crates/ruff/src/rules/isort/settings.rs
  crates/ruff/src/rules/isort/snapshots/ruff__rules__isort__tests__glob_1_separate_subpackage_first_and_third_party_imports.py.snap
  crates/ruff/src/settings/mod.rs
Labels: isort, configuration

#5575 Differentiate between runtime and typing-time annotations
  crates/ruff/src/checkers/ast/mod.rs
  crates/ruff/src/rules/flake8_future_annotations/snapshots/ruff__rules__flake8_future_annotations__tests__edge_case.py.snap
  crates/ruff/src/rules/flake8_future_annotations/snapshots/ruff__rules__flake8_future_annotations__tests__fa102_no_future_import_uses_lowercase.py.snap
  crates/ruff/src/rules/flake8_future_annotations/snapshots/ruff__rules__flake8_future_annotations__tests__fa102_no_future_import_uses_union.py.snap
  crates/ruff/src/rules/flake8_future_annotations/snapshots/ruff__rules__flake8_future_annotations__tests__fa102_no_future_import_uses_union_inner.py.snap
  crates/ruff_python_semantic/src/model.rs
Labels: bug

#5565 Introduce `parenthesized` helper
  crates/ruff_python_formatter/src/expression/expr_call.rs
  crates/ruff_python_formatter/src/expression/expr_dict.rs
  crates/ruff_python_formatter/src/expression/expr_list.rs
  crates/ruff_python_formatter/src/expression/expr_set.rs
  crates/ruff_python_formatter/src/expression/expr_tuple.rs
  crates/ruff_python_formatter/src/expression/parentheses.rs
  crates/ruff_python_formatter/src/other/arguments.rs
Labels: internal, formatter

#5570 Implement PYI030: Unnecessary literal union
  crates/ruff/resources/test/fixtures/flake8_pyi/PYI030.py
  crates/ruff/resources/test/fixtures/flake8_pyi/PYI030.pyi
  crates/ruff/src/checkers/ast/mod.rs
  crates/ruff/src/codes.rs
  crates/ruff/src/rules/flake8_pyi/mod.rs
  crates/ruff/src/rules/flake8_pyi/rules/mod.rs
  crates/ruff/src/rules/flake8_pyi/rules/unnecessary_literal_union.rs
  crates/ruff/src/rules/flake8_pyi/snapshots/ruff__rules__flake8_pyi__tests__PYI030_PYI030.py.snap
  crates/ruff/src/rules/flake8_pyi/snapshots/ruff__rules__flake8_pyi__tests__PYI030_PYI030.pyi.snap
  ruff.schema.json
Labels: rule

#5589 Fix CI by downgrading to cargo insta 1.29.0
  .github/workflows/ci.yaml
  crates/ruff_python_resolver/src/lib.rs
  ruff.schema.json
Labels: internal

#5578 Only run pyproject.toml lint rules when enabled
  crates/ruff/src/pyproject_toml.rs
  crates/ruff/src/registry.rs
  crates/ruff/src/rules/ruff/mod.rs
  crates/ruff_cli/src/diagnostics.rs
Labels: bug

#5571 Emit warnings for invalid `# noqa` directives
  crates/ruff/src/checkers/noqa.rs
  crates/ruff/src/noqa.rs
  crates/ruff/src/snapshots/ruff__noqa__tests__flake8_exemption_all.snap
  crates/ruff/src/snapshots/ruff__noqa__tests__flake8_exemption_all_case_insensitive.snap
  crates/ruff/src/snapshots/ruff__noqa__tests__flake8_exemption_all_no_space.snap
  crates/ruff/src/snapshots/ruff__noqa__tests__flake8_exemption_codes.snap
  crates/ruff/src/snapshots/ruff__noqa__tests__noqa_all.snap
  crates/ruff/src/snapshots/ruff__noqa__tests__noqa_all_case_insensitive.snap
  crates/ruff/src/snapshots/ruff__noqa__tests__noqa_all_leading_comment.snap
  crates/ruff/src/snapshots/ruff__noqa__tests__noqa_all_multi_space.snap
  crates/ruff/src/snapshots/ruff__noqa__tests__noqa_all_no_space.snap
  crates/ruff/src/snapshots/ruff__noqa__tests__noqa_all_trailing_comment.snap
  crates/ruff/src/snapshots/ruff__noqa__tests__noqa_code.snap
  crates/ruff/src/snapshots/ruff__noqa__tests__noqa_code_case_insensitive.snap
  crates/ruff/src/snapshots/ruff__noqa__tests__noqa_code_leading_comment.snap
  crates/ruff/src/snapshots/ruff__noqa__tests__noqa_code_multi_space.snap
  crates/ruff/src/snapshots/ruff__noqa__tests__noqa_code_no_space.snap
  crates/ruff/src/snapshots/ruff__noqa__tests__noqa_code_trailing_comment.snap
  crates/ruff/src/snapshots/ruff__noqa__tests__noqa_codes.snap
  crates/ruff/src/snapshots/ruff__noqa__tests__noqa_codes_case_insensitive.snap
  crates/ruff/src/snapshots/ruff__noqa__tests__noqa_codes_leading_comment.snap
  crates/ruff/src/snapshots/ruff__noqa__tests__noqa_codes_multi_space.snap
  crates/ruff/src/snapshots/ruff__noqa__tests__noqa_codes_no_space.snap
  crates/ruff/src/snapshots/ruff__noqa__tests__noqa_codes_trailing_comment.snap
  crates/ruff/src/snapshots/ruff__noqa__tests__noqa_invalid_codes.snap
  crates/ruff/src/snapshots/ruff__noqa__tests__noqa_leading_space.snap
  crates/ruff/src/snapshots/ruff__noqa__tests__noqa_trailing_space.snap
  crates/ruff/src/snapshots/ruff__noqa__tests__ruff_exemption_all.snap
  crates/ruff/src/snapshots/ruff__noqa__tests__ruff_exemption_all_case_insensitive.snap
  crates/ruff/src/snapshots/ruff__noqa__tests__ruff_exemption_all_no_space.snap
  crates/ruff/src/snapshots/ruff__noqa__tests__ruff_exemption_codes.snap
Labels: noqa

#5618 Support individual codes on `# flake8: noqa` directives
  crates/ruff/src/noqa.rs
  crates/ruff/src/snapshots/ruff__noqa__tests__flake8_exemption_codes.snap
Labels: noqa

#5623 Refactor isort directive skips to use iterators
  crates/ruff/resources/test/fixtures/isort/skip.py
  crates/ruff/resources/test/fixtures/isort/split.py
  crates/ruff/src/rules/isort/block.rs
  crates/ruff/src/rules/isort/snapshots/ruff__rules__isort__tests__skip.py.snap
  crates/ruff/src/rules/isort/snapshots/ruff__rules__isort__tests__split.py.snap
Labels: bug

#5634 Improve PERF203 example in docs
  crates/ruff/src/rules/perflint/rules/try_except_in_loop.rs
Labels: documentation

#5439 docs: show nursery icon for nursery rules
  crates/ruff_dev/src/generate_rules_table.rs
Labels: documentation

#5636 Render full-width tables in rules reference
  docs/stylesheets/extra.css
Labels: documentation

#5637 Add a link to the nursery; tweak icons
  crates/ruff/src/rules/perflint/rules/try_except_in_loop.rs
  crates/ruff_dev/src/generate_rules_table.rs
  docs/faq.md
Labels: documentation

#5638 Support autofix for some multiline `str.format` calls
  crates/ruff/resources/test/fixtures/pyupgrade/UP032_0.py
  crates/ruff/src/checkers/ast/mod.rs
  crates/ruff/src/rules/pyupgrade/rules/f_strings.rs
  crates/ruff/src/rules/pyupgrade/snapshots/ruff__rules__pyupgrade__tests__UP032_0.py.snap
Labels: autofix

#5629 Add documentation to `pandas-vet` rules
  crates/ruff/src/rules/pandas_vet/rules/assignment_to_df.rs
  crates/ruff/src/rules/pandas_vet/rules/attr.rs
  crates/ruff/src/rules/pandas_vet/rules/call.rs
  crates/ruff/src/rules/pandas_vet/rules/pd_merge.rs
  crates/ruff/src/rules/pandas_vet/rules/subscript.rs
Labels: documentation

#5651 [`pylint`] Implement Pylint `typevar-name-incorrect-variance` (`C0105`)
  crates/ruff/resources/test/fixtures/pylint/type_name_incorrect_variance.py
  crates/ruff/src/checkers/ast/mod.rs
  crates/ruff/src/codes.rs
  crates/ruff/src/rules/pylint/mod.rs
  crates/ruff/src/rules/pylint/rules/mod.rs
  crates/ruff/src/rules/pylint/rules/type_name_incorrect_variance.rs
  crates/ruff/src/rules/pylint/snapshots/ruff__rules__pylint__tests__PLC0105_type_name_incorrect_variance.py.snap
  ruff.schema.json
Labels: rule

#5549 Implement `UnnecessaryListAllocationForFirstElement`
  crates/ruff/resources/test/fixtures/ruff/RUF015.py
  crates/ruff/src/checkers/ast/mod.rs
  crates/ruff/src/codes.rs
  crates/ruff/src/rules/ruff/mod.rs
  crates/ruff/src/rules/ruff/rules/mod.rs
  crates/ruff/src/rules/ruff/rules/unnecessary_iterable_allocation_for_first_element.rs
  crates/ruff/src/rules/ruff/snapshots/ruff__rules__ruff__tests__RUF015_RUF015.py.snap
  ruff.schema.json
Labels: rule

#5659 Audit some `SemanticModel#is_builtin` usages
  crates/ruff/src/rules/flake8_blind_except/rules/blind_except.rs
  crates/ruff/src/rules/flake8_simplify/rules/open_file_with_context_handler.rs
  crates/ruff/src/rules/pylint/rules/property_with_parameters.rs
  crates/ruff/src/rules/pylint/rules/sys_exit_alias.rs
  crates/ruff/src/rules/pyupgrade/rules/native_literals.rs
  crates/ruff/src/rules/pyupgrade/rules/redundant_open_modes.rs
Labels: internal

#5595 Format `raise` statement
  crates/ruff_python_formatter/resources/test/fixtures/ruff/expression/tuple.py
  crates/ruff_python_formatter/resources/test/fixtures/ruff/statement/raise.py
  crates/ruff_python_formatter/src/comments/mod.rs
  crates/ruff_python_formatter/src/expression/expr_tuple.rs
  crates/ruff_python_formatter/src/statement/stmt_raise.rs
  crates/ruff_python_formatter/tests/snapshots/black_compatibility@py_311__pep_654_style.py.snap
  crates/ruff_python_formatter/tests/snapshots/black_compatibility@simple_cases__fmtonoff.py.snap
  crates/ruff_python_formatter/tests/snapshots/black_compatibility@simple_cases__function.py.snap
  crates/ruff_python_formatter/tests/snapshots/black_compatibility@simple_cases__remove_except_parens.py.snap
  crates/ruff_python_formatter/tests/snapshots/format@expression__tuple.py.snap
  crates/ruff_python_formatter/tests/snapshots/format@statement__raise.py.snap
Labels: formatter

#5670 Run nightly Clippy over the Ruff repo
  crates/ruff/src/autofix/edits.rs
  crates/ruff/src/checkers/ast/mod.rs
  crates/ruff/src/directives.rs
  crates/ruff/src/message/azure.rs
  crates/ruff/src/message/github.rs
  crates/ruff/src/message/json.rs
  crates/ruff/src/message/json_lines.rs
  crates/ruff/src/message/junit.rs
  crates/ruff/src/message/pylint.rs
  crates/ruff/src/rules/flake8_bandit/rules/shell_injection.rs
  crates/ruff/src/rules/flake8_bandit/settings.rs
  crates/ruff/src/rules/flake8_bugbear/rules/reuse_of_groupby_generator.rs
  crates/ruff/src/rules/flake8_comprehensions/fixes.rs
  crates/ruff/src/rules/flake8_django/rules/all_with_model_form.rs
  crates/ruff/src/rules/flake8_django/rules/exclude_with_model_form.rs
  crates/ruff/src/rules/flake8_django/rules/model_without_dunder_str.rs
  crates/ruff/src/rules/flake8_django/rules/nullable_model_string_field.rs
  crates/ruff/src/rules/flake8_django/rules/unordered_body_content_in_model.rs
  crates/ruff/src/rules/flake8_gettext/settings.rs
  crates/ruff/src/rules/flake8_quotes/rules/from_tokens.rs
  crates/ruff/src/rules/flake8_todos/rules/todos.rs
  crates/ruff/src/rules/flake8_type_checking/helpers.rs
  crates/ruff/src/rules/isort/order.rs
  crates/ruff/src/rules/pycodestyle/rules/not_tests.rs
  crates/ruff/src/rules/pyupgrade/rules/lru_cache_with_maxsize_none.rs
  crates/ruff/src/rules/pyupgrade/rules/lru_cache_without_parameters.rs
  crates/ruff/src/settings/configuration.rs
  crates/ruff/src/settings/options_base.rs
  crates/ruff_cli/src/printer.rs
  crates/ruff_diagnostics/src/fix.rs
  crates/ruff_formatter/src/arguments.rs
  crates/ruff_macros/src/config.rs
  crates/ruff_python_ast/src/source_code/indexer.rs
  crates/ruff_python_ast/src/types.rs
  crates/ruff_python_formatter/generate.py
  crates/ruff_python_formatter/src/comments/mod.rs
  crates/ruff_python_formatter/src/generated.rs
  crates/ruff_python_formatter/src/module/mod.rs
  crates/ruff_python_formatter/src/statement/mod.rs
  crates/ruff_python_formatter/src/statement/stmt_function_def.rs
Labels: internal

#5669 [`flake8-bugbear`] Implement `re-sub-positional-args` (`B034`)
  crates/ruff/resources/test/fixtures/flake8_bugbear/B034.py
  crates/ruff/src/checkers/ast/mod.rs
  crates/ruff/src/codes.rs
  crates/ruff/src/rules/flake8_bugbear/mod.rs
  crates/ruff/src/rules/flake8_bugbear/rules/mod.rs
  crates/ruff/src/rules/flake8_bugbear/rules/re_sub_positional_args.rs
  crates/ruff/src/rules/flake8_bugbear/snapshots/ruff__rules__flake8_bugbear__tests__B034_B034.py.snap
  crates/ruff/src/rules/pylint/rules/type_name_incorrect_variance.rs
  ruff.schema.json
Labels: rule

#5654 Format `ExpressionStarred` nodes
  crates/ruff_python_formatter/resources/test/fixtures/ruff/expression/starred.py
  crates/ruff_python_formatter/src/comments/mod.rs
  crates/ruff_python_formatter/src/comments/placement.rs
  crates/ruff_python_formatter/src/comments/visitor.rs
  crates/ruff_python_formatter/src/expression/expr_starred.rs
  crates/ruff_python_formatter/tests/snapshots/black_compatibility@miscellaneous__decorators.py.snap
  crates/ruff_python_formatter/tests/snapshots/black_compatibility@py_310__starred_for_target.py.snap
  crates/ruff_python_formatter/tests/snapshots/black_compatibility@py_311__pep_654.py.snap
  crates/ruff_python_formatter/tests/snapshots/black_compatibility@py_311__pep_654_style.py.snap
  crates/ruff_python_formatter/tests/snapshots/black_compatibility@py_38__pep_572.py.snap
  crates/ruff_python_formatter/tests/snapshots/black_compatibility@py_38__python38.py.snap
  crates/ruff_python_formatter/tests/snapshots/black_compatibility@simple_cases__comments6.py.snap
  crates/ruff_python_formatter/tests/snapshots/black_compatibility@simple_cases__expression.py.snap
  crates/ruff_python_formatter/tests/snapshots/black_compatibility@simple_cases__fmtonoff.py.snap
  crates/ruff_python_formatter/tests/snapshots/format@expression__starred.py.snap
  crates/ruff_python_formatter/tests/snapshots/format@statement__with.py.snap
Labels: formatter

#5600 format ExprListComp
  crates/ruff_python_formatter/resources/test/fixtures/ruff/statement/list_comp.py
  crates/ruff_python_formatter/src/comments/placement.rs
  crates/ruff_python_formatter/src/expression/expr_list_comp.rs
  crates/ruff_python_formatter/src/other/comprehension.rs
  crates/ruff_python_formatter/tests/snapshots/black_compatibility@py_37__python37.py.snap
  crates/ruff_python_formatter/tests/snapshots/black_compatibility@py_38__pep_572.py.snap
  crates/ruff_python_formatter/tests/snapshots/black_compatibility@simple_cases__comments2.py.snap
  crates/ruff_python_formatter/tests/snapshots/black_compatibility@simple_cases__comments3.py.snap
  crates/ruff_python_formatter/tests/snapshots/black_compatibility@simple_cases__expression.py.snap
  crates/ruff_python_formatter/tests/snapshots/black_compatibility@simple_cases__power_op_spacing.py.snap
  crates/ruff_python_formatter/tests/snapshots/black_compatibility@simple_cases__slices.py.snap
  crates/ruff_python_formatter/tests/snapshots/format@expression__binary.py.snap
  crates/ruff_python_formatter/tests/snapshots/format@statement__list_comp.py.snap
Labels: formatter

#5169 Format `delete` statement
  crates/ruff_python_formatter/resources/test/fixtures/ruff/statement/delete.py
  crates/ruff_python_formatter/src/statement/stmt_delete.rs
  crates/ruff_python_formatter/tests/snapshots/format@statement__delete.py.snap
Labels: formatter

#5596 Extend formatter IR to support Black's expression formatting
  crates/ruff_formatter/src/builders.rs
  crates/ruff_formatter/src/format_element/document.rs
  crates/ruff_formatter/src/format_element/tag.rs
  crates/ruff_formatter/src/printer/mod.rs
  crates/ruff_python_formatter/src/comments/debug.rs
Labels: formatter

#5608 Prefer expanding parenthesized expressions before operands
  crates/ruff_python_formatter/src/builders.rs
  crates/ruff_python_formatter/src/comments/format.rs
  crates/ruff_python_formatter/src/context.rs
  crates/ruff_python_formatter/src/expression/binary_like.rs
  crates/ruff_python_formatter/src/expression/expr_bin_op.rs
  crates/ruff_python_formatter/src/expression/expr_bool_op.rs
  crates/ruff_python_formatter/src/expression/expr_compare.rs
  crates/ruff_python_formatter/src/expression/expr_if_exp.rs
  crates/ruff_python_formatter/src/expression/expr_subscript.rs
  crates/ruff_python_formatter/src/expression/mod.rs
  crates/ruff_python_formatter/src/expression/parentheses.rs
  crates/ruff_python_formatter/src/other/arguments.rs
  crates/ruff_python_formatter/tests/snapshots/black_compatibility@simple_cases__composition.py.snap
  crates/ruff_python_formatter/tests/snapshots/black_compatibility@simple_cases__composition_no_trailing_comma.py.snap
  crates/ruff_python_formatter/tests/snapshots/black_compatibility@simple_cases__empty_lines.py.snap
  crates/ruff_python_formatter/tests/snapshots/black_compatibility@simple_cases__function_trailing_comma.py.snap
  crates/ruff_python_formatter/tests/snapshots/black_compatibility@simple_cases__remove_await_parens.py.snap
  crates/ruff_python_formatter/tests/snapshots/black_compatibility@simple_cases__torture.py.snap
  crates/ruff_python_formatter/tests/snapshots/black_compatibility@simple_cases__trailing_comma_optional_parens1.py.snap
  crates/ruff_python_formatter/tests/snapshots/black_compatibility@simple_cases__trailing_comma_optional_parens2.py.snap
  crates/ruff_python_formatter/tests/snapshots/black_compatibility@simple_cases__trailing_comma_optional_parens3.py.snap
  crates/ruff_python_formatter/tests/snapshots/black_compatibility@simple_cases__trailing_commas_in_leading_parts.py.snap
  crates/ruff_python_formatter/tests/snapshots/format@expression__binary.py.snap
  crates/ruff_python_formatter/tests/snapshots/format@expression__compare.py.snap
  crates/ruff_python_formatter/tests/snapshots/format@expression__unary.py.snap
  crates/ruff_python_formatter/tests/snapshots/format@statement__raise.py.snap
Labels: formatter

#5609 Remove `mode` from `BestFitting`
  crates/ruff_formatter/src/builders.rs
  crates/ruff_formatter/src/format_element.rs
  crates/ruff_formatter/src/format_element/document.rs
  crates/ruff_formatter/src/printer/mod.rs
Labels: formatter

#5643 Pass `FormatContext` to `NeedsParentheses`
  crates/ruff_python_formatter/src/builders.rs
  crates/ruff_python_formatter/src/comments/format.rs
  crates/ruff_python_formatter/src/context.rs
  crates/ruff_python_formatter/src/expression/expr_attribute.rs
  crates/ruff_python_formatter/src/expression/expr_await.rs
  crates/ruff_python_formatter/src/expression/expr_bin_op.rs
  crates/ruff_python_formatter/src/expression/expr_bool_op.rs
  crates/ruff_python_formatter/src/expression/expr_call.rs
  crates/ruff_python_formatter/src/expression/expr_compare.rs
  crates/ruff_python_formatter/src/expression/expr_constant.rs
  crates/ruff_python_formatter/src/expression/expr_dict.rs
  crates/ruff_python_formatter/src/expression/expr_dict_comp.rs
  crates/ruff_python_formatter/src/expression/expr_formatted_value.rs
  crates/ruff_python_formatter/src/expression/expr_generator_exp.rs
  crates/ruff_python_formatter/src/expression/expr_if_exp.rs
  crates/ruff_python_formatter/src/expression/expr_joined_str.rs
  crates/ruff_python_formatter/src/expression/expr_lambda.rs
  crates/ruff_python_formatter/src/expression/expr_list.rs
  crates/ruff_python_formatter/src/expression/expr_list_comp.rs
  crates/ruff_python_formatter/src/expression/expr_name.rs
  crates/ruff_python_formatter/src/expression/expr_named_expr.rs
  crates/ruff_python_formatter/src/expression/expr_set.rs
  crates/ruff_python_formatter/src/expression/expr_set_comp.rs
  crates/ruff_python_formatter/src/expression/expr_slice.rs
  crates/ruff_python_formatter/src/expression/expr_starred.rs
  crates/ruff_python_formatter/src/expression/expr_subscript.rs
  crates/ruff_python_formatter/src/expression/expr_tuple.rs
  crates/ruff_python_formatter/src/expression/expr_unary_op.rs
  crates/ruff_python_formatter/src/expression/expr_yield.rs
  crates/ruff_python_formatter/src/expression/expr_yield_from.rs
  crates/ruff_python_formatter/src/expression/mod.rs
  crates/ruff_python_formatter/src/expression/parentheses.rs
  crates/ruff_python_formatter/src/other/arguments.rs
  crates/ruff_python_formatter/src/statement/stmt_class_def.rs
  crates/ruff_python_formatter/src/statement/stmt_expr.rs
  crates/ruff_python_formatter/src/statement/stmt_function_def.rs
  crates/ruff_python_formatter/src/statement/suite.rs
Labels: formatter

#5681 Print files that are slow to format
  crates/ruff_dev/src/format_dev.rs
Labels: formatter

#5661 Format `target: annotation = value?` expressions
  crates/ruff_python_formatter/resources/test/fixtures/black/simple_cases/skip_magic_trailing_comma.options.json
  crates/ruff_python_formatter/resources/test/fixtures/ruff/expression/annotated_assign.py
  crates/ruff_python_formatter/src/builders.rs
  crates/ruff_python_formatter/src/expression/expr_subscript.rs
  crates/ruff_python_formatter/src/expression/expr_tuple.rs
  crates/ruff_python_formatter/src/expression/mod.rs
  crates/ruff_python_formatter/src/expression/parentheses.rs
  crates/ruff_python_formatter/src/expression/string.rs
  crates/ruff_python_formatter/src/lib.rs
  crates/ruff_python_formatter/src/statement/stmt_ann_assign.rs
  crates/ruff_python_formatter/src/statement/stmt_assign.rs
  crates/ruff_python_formatter/src/statement/stmt_delete.rs
  crates/ruff_python_formatter/src/statement/stmt_function_def.rs
  crates/ruff_python_formatter/src/statement/stmt_import_from.rs
  crates/ruff_python_formatter/src/statement/stmt_with.rs
  crates/ruff_python_formatter/tests/fixtures.rs
  crates/ruff_python_formatter/tests/snapshots/black_compatibility@miscellaneous__debug_visitor.py.snap
  crates/ruff_python_formatter/tests/snapshots/black_compatibility@miscellaneous__force_pyi.py.snap
  crates/ruff_python_formatter/tests/snapshots/black_compatibility@miscellaneous__long_strings_flag_disabled.py.snap
  crates/ruff_python_formatter/tests/snapshots/black_compatibility@py_310__pattern_matching_extras.py.snap
  crates/ruff_python_formatter/tests/snapshots/black_compatibility@py_38__python38.py.snap
  crates/ruff_python_formatter/tests/snapshots/black_compatibility@simple_cases__expression.py.snap
  crates/ruff_python_formatter/tests/snapshots/black_compatibility@simple_cases__fmtonoff.py.snap
  crates/ruff_python_formatter/tests/snapshots/black_compatibility@simple_cases__function_trailing_comma.py.snap
  crates/ruff_python_formatter/tests/snapshots/black_compatibility@simple_cases__one_element_subscript.py.snap
  crates/ruff_python_formatter/tests/snapshots/black_compatibility@simple_cases__return_annotation_brackets.py.snap
  crates/ruff_python_formatter/tests/snapshots/black_compatibility@simple_cases__skip_magic_trailing_comma.py.snap
  crates/ruff_python_formatter/tests/snapshots/format@expression__annotated_assign.py.snap
Labels: formatter

#5689 Format `ModExpression`
  crates/ruff_python_formatter/src/module/mod_expression.rs
Labels: formatter

#5680 Improve comprehension line break beheavior
  crates/ruff_python_formatter/resources/test/fixtures/ruff/expression/list_comp.py
  crates/ruff_python_formatter/src/expression/expr_compare.rs
  crates/ruff_python_formatter/src/other/comprehension.rs
  crates/ruff_python_formatter/tests/snapshots/black_compatibility@py_37__python37.py.snap
  crates/ruff_python_formatter/tests/snapshots/black_compatibility@simple_cases__comments2.py.snap
  crates/ruff_python_formatter/tests/snapshots/black_compatibility@simple_cases__comments3.py.snap
  crates/ruff_python_formatter/tests/snapshots/black_compatibility@simple_cases__fmtskip5.py.snap
  crates/ruff_python_formatter/tests/snapshots/black_compatibility@simple_cases__function.py.snap
  crates/ruff_python_formatter/tests/snapshots/black_compatibility@simple_cases__power_op_spacing.py.snap
  crates/ruff_python_formatter/tests/snapshots/format@expression__call.py.snap
  crates/ruff_python_formatter/tests/snapshots/format@expression__list_comp.py.snap
Labels: formatter

#5683 Only omit optinal parens if the expression ends or starts with a parenthesized expression
  crates/ruff_python_formatter/src/expression/mod.rs
  crates/ruff_python_formatter/src/lib.rs
  crates/ruff_python_formatter/tests/snapshots/black_compatibility@simple_cases__trailing_comma_optional_parens1.py.snap
Labels: formatter

#5701 Misc. tweaks to bandit documentation
  crates/ruff/src/rules/flake8_bandit/rules/suspicious_function_call.rs
Labels: documentation

#5711 Handle right parens in join comma builder
  crates/ruff_python_formatter/src/builders.rs
  crates/ruff_python_formatter/src/expression/expr_call.rs
  crates/ruff_python_formatter/src/expression/expr_dict.rs
  crates/ruff_python_formatter/src/expression/expr_list.rs
  crates/ruff_python_formatter/src/expression/expr_tuple.rs
  crates/ruff_python_formatter/src/statement/stmt_class_def.rs
  crates/ruff_python_formatter/src/statement/stmt_delete.rs
  crates/ruff_python_formatter/src/statement/stmt_import_from.rs
  crates/ruff_python_formatter/src/statement/stmt_with.rs
  crates/ruff_python_formatter/tests/snapshots/black_compatibility@miscellaneous__long_strings_flag_disabled.py.snap
  crates/ruff_python_formatter/tests/snapshots/black_compatibility@py_38__pep_572.py.snap
Labels: formatter

#5720 Tweak hierarchy of benchmark docs
  CONTRIBUTING.md
Labels: documentation

#5715 Use shared `Cursor` across crates
  crates/ruff/src/checkers/ast/mod.rs
  crates/ruff_python_ast/src/identifier.rs
  crates/ruff_python_formatter/Cargo.toml
  crates/ruff_python_formatter/src/trivia.rs
  crates/ruff_python_whitespace/src/cursor.rs
  crates/ruff_python_whitespace/src/lib.rs
Labels: internal

#5716 Use `Cursor` for shebang parsing
  crates/ruff/src/checkers/physical_lines.rs
  crates/ruff/src/comments/mod.rs
  crates/ruff/src/comments/shebang.rs
  crates/ruff/src/comments/snapshots/ruff__comments__shebang__tests__shebang_end_of_line.snap
  crates/ruff/src/comments/snapshots/ruff__comments__shebang__tests__shebang_leading_space.snap
  crates/ruff/src/comments/snapshots/ruff__comments__shebang__tests__shebang_match.snap
  crates/ruff/src/comments/snapshots/ruff__comments__shebang__tests__shebang_non_match.snap
  crates/ruff/src/lib.rs
  crates/ruff/src/rules/flake8_executable/helpers.rs
  crates/ruff/src/rules/flake8_executable/rules/shebang_newline.rs
  crates/ruff/src/rules/flake8_executable/rules/shebang_not_executable.rs
  crates/ruff/src/rules/flake8_executable/rules/shebang_python.rs
  crates/ruff/src/rules/flake8_executable/rules/shebang_whitespace.rs
Labels: internal, performance

#5193 Implement Pylint `consider-using-in`
  crates/ruff/resources/test/fixtures/pylint/repeated_equality_comparison_target.py
  crates/ruff/src/checkers/ast/mod.rs
  crates/ruff/src/codes.rs
  crates/ruff/src/rules/pylint/mod.rs
  crates/ruff/src/rules/pylint/rules/mod.rs
  crates/ruff/src/rules/pylint/rules/repeated_equality_comparison_target.rs
  crates/ruff/src/rules/pylint/snapshots/ruff__rules__pylint__tests__PLR1714_repeated_equality_comparison_target.py.snap
  crates/ruff/src/rules/ruff/rules/invalid_index_type.rs
  ruff.schema.json
Labels: rule

#5723 Use Locator-based replacement rather than Generator for UP007
  crates/ruff/src/rules/pyupgrade/rules/use_pep604_annotation.rs
Labels: internal

#5730 Formatter: Better f-string dummy
  crates/ruff_python_formatter/src/expression/expr_joined_str.rs
  crates/ruff_python_formatter/tests/snapshots/black_compatibility@miscellaneous__debug_visitor.py.snap
  crates/ruff_python_formatter/tests/snapshots/black_compatibility@miscellaneous__docstring_preview_no_string_normalization.py.snap
  crates/ruff_python_formatter/tests/snapshots/black_compatibility@miscellaneous__long_strings_flag_disabled.py.snap
  crates/ruff_python_formatter/tests/snapshots/black_compatibility@miscellaneous__string_quotes.py.snap
  crates/ruff_python_formatter/tests/snapshots/black_compatibility@py_310__pattern_matching_generic.py.snap
  crates/ruff_python_formatter/tests/snapshots/black_compatibility@simple_cases__docstring_preview.py.snap
  crates/ruff_python_formatter/tests/snapshots/black_compatibility@simple_cases__fmtonoff.py.snap
  crates/ruff_python_formatter/tests/snapshots/black_compatibility@simple_cases__fstring.py.snap
  crates/ruff_python_formatter/tests/snapshots/black_compatibility@simple_cases__function.py.snap
  crates/ruff_python_formatter/tests/snapshots/black_compatibility@simple_cases__remove_newline_after_code_block_open.py.snap
  crates/ruff_python_formatter/tests/snapshots/black_compatibility@simple_cases__remove_parens.py.snap
  crates/ruff_python_formatter/tests/snapshots/black_compatibility@simple_cases__string_prefixes.py.snap
Labels: formatter

#5732 Fix `StmtAnnAssign` formatting by mirroring `StmtAssign`
  crates/ruff_python_formatter/resources/test/fixtures/ruff/statement/ann_assign.py
  crates/ruff_python_formatter/resources/test/fixtures/ruff/statement/aug_assign.py
  crates/ruff_python_formatter/src/statement/stmt_ann_assign.rs
  crates/ruff_python_formatter/tests/snapshots/format@statement__ann_assign.py.snap
  crates/ruff_python_formatter/tests/snapshots/format@statement__aug_assign.py.snap
Labels: formatter

#5601 Check for `Any` in other types for `ANN401`
  crates/ruff/resources/test/fixtures/flake8_annotations/annotation_presence.py
  crates/ruff/src/rules/flake8_annotations/rules/definition.rs
  crates/ruff/src/rules/flake8_annotations/snapshots/ruff__rules__flake8_annotations__tests__defaults.snap
  crates/ruff/src/rules/ruff/mod.rs
  crates/ruff/src/rules/ruff/rules/implicit_optional.rs
  crates/ruff/src/rules/ruff/snapshots/ruff__rules__ruff__tests__PY39_RUF013_RUF013_0.py.snap
  crates/ruff/src/rules/ruff/snapshots/ruff__rules__ruff__tests__RUF013_RUF013_0.py.snap
  crates/ruff/src/rules/ruff/typing.rs
  scripts/pyproject.toml
Labels: rule

#5717 Consider single element subscript expr for implicit optional
  crates/ruff/resources/test/fixtures/ruff/RUF013_0.py
  crates/ruff/src/rules/ruff/snapshots/ruff__rules__ruff__tests__PY39_RUF013_RUF013_0.py.snap
  crates/ruff/src/rules/ruff/snapshots/ruff__rules__ruff__tests__RUF013_RUF013_0.py.snap
  crates/ruff/src/rules/ruff/typing.rs
  crates/ruff/src/test.rs
Labels: rule

#5737 Update scripts/ecosystem_all_check.sh
  scripts/ecosystem_all_check.py
  scripts/ecosystem_all_check.sh
Labels: internal

#5721 Fix nested lists in CONTRIBUTING.md
  .markdownlint.yaml
  .pre-commit-config.yaml
  BREAKING_CHANGES.md
  CODE_OF_CONDUCT.md
  CONTRIBUTING.md
  README.md
  crates/flake8_to_ruff/README.md
  crates/ruff_python_formatter/README.md
  docs/configuration.md
  docs/faq.md
  playground/README.md
Labels: documentation

#5722 [`flake8-pyi`] Implement PYI041
  crates/ruff/resources/test/fixtures/flake8_pyi/PYI041.py
  crates/ruff/resources/test/fixtures/flake8_pyi/PYI041.pyi
  crates/ruff/src/checkers/ast/mod.rs
  crates/ruff/src/codes.rs
  crates/ruff/src/rules/flake8_pyi/mod.rs
  crates/ruff/src/rules/flake8_pyi/rules/mod.rs
  crates/ruff/src/rules/flake8_pyi/rules/redundant_numeric_union.rs
  crates/ruff/src/rules/flake8_pyi/snapshots/ruff__rules__flake8_pyi__tests__PYI041_PYI041.py.snap
  crates/ruff/src/rules/flake8_pyi/snapshots/ruff__rules__flake8_pyi__tests__PYI041_PYI041.pyi.snap
  ruff.schema.json
Labels: rule

#5741 Fix `Options` section of rule docs
  crates/ruff_dev/src/generate_docs.rs
Labels: documentation

#5744 Update table of content in CONTRIBUTING.md
  CONTRIBUTING.md
Labels: documentation

#5745 Add some additional Option links to the docs
  crates/ruff/src/rules/flake8_implicit_str_concat/rules/implicit.rs
  crates/ruff/src/rules/pycodestyle/rules/doc_line_too_long.rs
  crates/ruff/src/rules/pycodestyle/rules/line_too_long.rs
  crates/ruff/src/rules/pyupgrade/rules/use_pep585_annotation.rs
  crates/ruff/src/rules/pyupgrade/rules/use_pep604_annotation.rs
Labels: documentation

#5746 Fix the example for blank-line-before-class (D211)
  crates/ruff/src/rules/pydocstyle/rules/blank_before_after_class.rs
Labels: documentation

#5749 Ignore `Enum`-and-`str` subclasses for slots enforcement
  crates/ruff/resources/test/fixtures/flake8_slots/SLOT000.py
  crates/ruff/src/rules/flake8_slots/rules/no_slots_in_str_subclass.rs
Labels: bug

#5755 Avoid removing raw strings in comparison fixes
  crates/ruff/resources/test/fixtures/pycodestyle/E713.py
  crates/ruff/resources/test/fixtures/pycodestyle/E714.py
  crates/ruff/src/rules/pycodestyle/helpers.rs
  crates/ruff/src/rules/pycodestyle/rules/literal_comparisons.rs
  crates/ruff/src/rules/pycodestyle/rules/not_tests.rs
  crates/ruff/src/rules/pycodestyle/snapshots/ruff__rules__pycodestyle__tests__E714_E714.py.snap
Labels: bug

#5168 Format `assert` statement
  crates/ruff_python_formatter/resources/test/fixtures/ruff/statement/assert.py
  crates/ruff_python_formatter/src/statement/stmt_assert.rs
  crates/ruff_python_formatter/tests/snapshots/black_compatibility@miscellaneous__long_strings_flag_disabled.py.snap
  crates/ruff_python_formatter/tests/snapshots/black_compatibility@simple_cases__collections.py.snap
  crates/ruff_python_formatter/tests/snapshots/black_compatibility@simple_cases__composition.py.snap
  crates/ruff_python_formatter/tests/snapshots/black_compatibility@simple_cases__composition_no_trailing_comma.py.snap
  crates/ruff_python_formatter/tests/snapshots/black_compatibility@simple_cases__empty_lines.py.snap
  crates/ruff_python_formatter/tests/snapshots/black_compatibility@simple_cases__expression.py.snap
  crates/ruff_python_formatter/tests/snapshots/black_compatibility@simple_cases__fmtonoff.py.snap
  crates/ruff_python_formatter/tests/snapshots/black_compatibility@simple_cases__fmtonoff2.py.snap
  crates/ruff_python_formatter/tests/snapshots/black_compatibility@simple_cases__function.py.snap
  crates/ruff_python_formatter/tests/snapshots/black_compatibility@simple_cases__torture.py.snap
  crates/ruff_python_formatter/tests/snapshots/black_compatibility@simple_cases__trailing_commas_in_leading_parts.py.snap
  crates/ruff_python_formatter/tests/snapshots/format@statement__assert.py.snap
Labels: formatter

#5759 Add Regression test for #5605, where formatting `x[:,]` failed.
  crates/ruff_python_formatter/resources/test/fixtures/ruff/expression/slice.py
  crates/ruff_python_formatter/tests/snapshots/format@expression__slice.py.snap
Labels: formatter

#5761 Fix nested calls to `sorted` with differing arguments
  crates/ruff/resources/test/fixtures/flake8_comprehensions/C414.py
  crates/ruff/src/checkers/ast/mod.rs
  crates/ruff/src/rules/flake8_comprehensions/rules/unnecessary_double_cast_or_process.rs
  crates/ruff/src/rules/flake8_comprehensions/snapshots/ruff__rules__flake8_comprehensions__tests__C414_C414.py.snap
Labels: bug

#5738 Cover Black's `is_aritmetic_like` formatting
  crates/ruff_python_formatter/src/context.rs
  crates/ruff_python_formatter/src/expression/expr_await.rs
  crates/ruff_python_formatter/src/expression/expr_bin_op.rs
  crates/ruff_python_formatter/src/expression/expr_bool_op.rs
  crates/ruff_python_formatter/src/expression/expr_compare.rs
  crates/ruff_python_formatter/src/expression/expr_if_exp.rs
  crates/ruff_python_formatter/src/expression/expr_subscript.rs
  crates/ruff_python_formatter/src/expression/parentheses.rs
  crates/ruff_python_formatter/src/expression/string.rs
  crates/ruff_python_formatter/src/statement/stmt_class_def.rs
  crates/ruff_python_formatter/src/statement/stmt_expr.rs
  crates/ruff_python_formatter/tests/snapshots/black_compatibility@simple_cases__remove_await_parens.py.snap
  crates/ruff_python_formatter/tests/snapshots/format@expression__compare.py.snap
  crates/ruff_python_formatter/tests/snapshots/format@expression__string.py.snap
Labels: formatter

#5762 Misc. minor refactors to `incorrect-dict-iterator`
  crates/ruff/src/rules/perflint/rules/incorrect_dict_iterator.rs
  crates/ruff/src/rules/tryceratops/rules/reraise_no_cause.rs
Labels: internal

#5768 Move `Literal` flag detection into recurse phase
  crates/ruff/src/checkers/ast/mod.rs
  crates/ruff_python_semantic/src/analyze/typing.rs
  crates/ruff_python_stdlib/src/typing.rs
Labels: internal

#5769 Move lambda visitation into recurse phase
  crates/ruff/src/checkers/ast/mod.rs
Labels: internal

#5770 Handle name nodes prior to running rules
  crates/ruff/src/checkers/ast/mod.rs
Labels: internal

#5758 Parenthesize with statements
  crates/ruff_python_formatter/resources/test/fixtures/ruff/statement/with.py
  crates/ruff_python_formatter/src/builders.rs
  crates/ruff_python_formatter/src/comments/placement.rs
  crates/ruff_python_formatter/src/expression/expr_await.rs
  crates/ruff_python_formatter/src/expression/expr_bin_op.rs
  crates/ruff_python_formatter/src/expression/mod.rs
  crates/ruff_python_formatter/src/expression/parentheses.rs
  crates/ruff_python_formatter/src/lib.rs
  crates/ruff_python_formatter/src/other/with_item.rs
  crates/ruff_python_formatter/src/statement/stmt_with.rs
  crates/ruff_python_formatter/src/trivia.rs
  crates/ruff_python_formatter/tests/snapshots/black_compatibility@simple_cases__remove_await_parens.py.snap
  crates/ruff_python_formatter/tests/snapshots/format@statement__with.py.snap
Labels: formatter

#5782 Respect magic trailing comma for set expression
  crates/ruff_python_formatter/src/expression/expr_set.rs
  crates/ruff_python_formatter/tests/snapshots/black_compatibility@simple_cases__collections.py.snap
Labels: formatter

#5783 Lift `Expr::Subscript` value visit out of branches
  crates/ruff/src/checkers/ast/mod.rs
Labels: internal

#5766 Expand scope of `quoted-annotation` rule
  crates/ruff/resources/test/fixtures/pyupgrade/UP037_0.py
  crates/ruff/resources/test/fixtures/pyupgrade/UP037_1.py
  crates/ruff/src/checkers/ast/mod.rs
  crates/ruff/src/rules/pyupgrade/mod.rs
  crates/ruff/src/rules/pyupgrade/rules/quoted_annotation.rs
  crates/ruff/src/rules/pyupgrade/snapshots/ruff__rules__pyupgrade__tests__UP037.py.snap
  crates/ruff/src/rules/pyupgrade/snapshots/ruff__rules__pyupgrade__tests__UP037_0.py.snap
  crates/ruff/src/rules/pyupgrade/snapshots/ruff__rules__pyupgrade__tests__UP037_1.py.snap
Labels: rule

#5786 Include alias when formatting import-from structs
  crates/ruff/src/rules/isort/mod.rs
  crates/ruff/src/rules/isort/snapshots/ruff__rules__isort__tests__required_import_with_alias_comment.py.snap
  crates/ruff/src/rules/isort/snapshots/ruff__rules__isort__tests__required_import_with_alias_docstring.py.snap
  crates/ruff/src/rules/isort/snapshots/ruff__rules__isort__tests__required_import_with_alias_docstring.pyi.snap
  crates/ruff/src/rules/isort/snapshots/ruff__rules__isort__tests__required_import_with_alias_docstring_only.py.snap
  crates/ruff/src/rules/isort/snapshots/ruff__rules__isort__tests__required_import_with_alias_docstring_with_continuation.py.snap
  crates/ruff/src/rules/isort/snapshots/ruff__rules__isort__tests__required_import_with_alias_docstring_with_semicolon.py.snap
  crates/ruff/src/rules/isort/snapshots/ruff__rules__isort__tests__required_import_with_alias_empty.py.snap
  crates/ruff/src/rules/isort/snapshots/ruff__rules__isort__tests__required_import_with_alias_existing_import.py.snap
  crates/ruff/src/rules/isort/snapshots/ruff__rules__isort__tests__required_import_with_alias_multiline_docstring.py.snap
  crates/ruff/src/rules/isort/snapshots/ruff__rules__isort__tests__required_import_with_alias_off.py.snap
  crates/ruff_python_ast/src/imports.rs
Labels: bug, isort

#5793 Use `SmallVec#extend_from_slice` in lieu of `SmallVec#extend`
  crates/ruff_python_semantic/src/model.rs
Labels: internal, performance

#5788 Add autofix for B004
  crates/ruff/src/rules/flake8_bugbear/rules/unreliable_callable_check.rs
  crates/ruff/src/rules/flake8_bugbear/snapshots/ruff__rules__flake8_bugbear__tests__B004_B004.py.snap
Labels: autofix

#5710 Update ruff crate descriptions
  CONTRIBUTING.md
Labels: documentation

#5795 Use `semantic().global()` to power `global-statement` rule
  crates/ruff/resources/test/fixtures/pylint/global_statement.py
  crates/ruff/src/rules/pylint/rules/global_statement.rs
  crates/ruff/src/rules/pylint/snapshots/ruff__rules__pylint__tests__PLW0603_global_statement.py.snap
Labels: internal

#5796 Move except-handler flag into `visit_except_handler`
  crates/ruff/src/checkers/ast/mod.rs
Labels: internal

#5797 Remove `Identifier` usages for isolating exception names
  crates/ruff/src/checkers/ast/mod.rs
  crates/ruff/src/rules/flake8_bandit/rules/try_except_continue.rs
  crates/ruff/src/rules/flake8_bandit/rules/try_except_pass.rs
  crates/ruff/src/rules/flake8_builtins/helpers.rs
  crates/ruff/src/rules/flake8_builtins/rules/builtin_attribute_shadowing.rs
  crates/ruff/src/rules/flake8_builtins/rules/builtin_variable_shadowing.rs
  crates/ruff/src/rules/flake8_builtins/snapshots/ruff__rules__flake8_builtins__tests__A001_A001.py.snap
  crates/ruff/src/rules/flake8_builtins/snapshots/ruff__rules__flake8_builtins__tests__A001_A001.py_builtins_ignorelist.snap
  crates/ruff_python_ast/src/identifier.rs
Labels: internal

#5798 Use a match statement for builtin detection
  crates/ruff/src/checkers/ast/mod.rs
  crates/ruff/src/rules/flake8_builtins/helpers.rs
  crates/ruff_python_stdlib/src/builtins.rs
Labels: internal

#5816 Remove `TryIdentifier` trait
  crates/ruff/src/checkers/ast/mod.rs
  crates/ruff_python_ast/src/identifier.rs
Labels: internal

#5802 [`pandas-vet`] series constant series
  crates/ruff/resources/test/fixtures/pandas_vet/PD101.py
  crates/ruff/src/checkers/ast/mod.rs
  crates/ruff/src/codes.rs
  crates/ruff/src/rules/pandas_vet/mod.rs
  crates/ruff/src/rules/pandas_vet/rules/mod.rs
  crates/ruff/src/rules/pandas_vet/rules/nunique_constant_series_check.rs
  crates/ruff/src/rules/pandas_vet/snapshots/ruff__rules__pandas_vet__tests__PD101_PD101.py.snap
  ruff.schema.json
Labels: rule

#5805 Add documentation to the `S5XX` rules
  crates/ruff/src/checkers/ast/mod.rs
  crates/ruff/src/rules/flake8_bandit/rules/request_with_no_cert_validation.rs
  crates/ruff/src/rules/flake8_bandit/rules/snmp_insecure_version.rs
  crates/ruff/src/rules/flake8_bandit/rules/snmp_weak_cryptography.rs
  crates/ruff/src/rules/flake8_bandit/rules/unsafe_yaml_load.rs
  crates/ruff/src/rules/flake8_bandit/snapshots/ruff__rules__flake8_bandit__tests__S501_S501.py.snap
  crates/ruff/src/rules/flake8_bandit/snapshots/ruff__rules__flake8_bandit__tests__S508_S508.py.snap
Labels: documentation

#5817 Reduce unnecessary allocations for keyword detection
  crates/ruff/src/checkers/ast/mod.rs
  crates/ruff/src/rules/flake8_bandit/rules/jinja2_autoescape_false.rs
  crates/ruff/src/rules/flake8_bandit/rules/logging_config_insecure_listen.rs
  crates/ruff/src/rules/flake8_bandit/rules/request_with_no_cert_validation.rs
  crates/ruff/src/rules/flake8_bandit/rules/request_without_timeout.rs
  crates/ruff/src/rules/flake8_bandit/rules/snmp_insecure_version.rs
  crates/ruff/src/rules/flake8_bandit/snapshots/ruff__rules__flake8_bandit__tests__S113_S113.py.snap
  crates/ruff/src/rules/flake8_bandit/snapshots/ruff__rules__flake8_bandit__tests__S701_S701.py.snap
  crates/ruff/src/rules/flake8_bugbear/rules/no_explicit_stacklevel.rs
Labels: internal, performance

#5818 Include function name in `undocumented-param` message
  crates/ruff/src/rules/pydocstyle/rules/sections.rs
  crates/ruff/src/rules/pydocstyle/snapshots/ruff__rules__pydocstyle__tests__D417_sections.py.snap
  crates/ruff/src/rules/pydocstyle/snapshots/ruff__rules__pydocstyle__tests__d417_google.snap
  crates/ruff/src/rules/pydocstyle/snapshots/ruff__rules__pydocstyle__tests__d417_unspecified.snap
  crates/ruff_python_semantic/src/definition.rs
Labels: docstring

#5813 Add documentation to the `flake8-gettext` (`INT`) rules
  crates/ruff/src/checkers/ast/mod.rs
  crates/ruff/src/rules/flake8_gettext/mod.rs
  crates/ruff/src/rules/flake8_gettext/rules/f_string_in_gettext_func_call.rs
  crates/ruff/src/rules/flake8_gettext/rules/format_in_gettext_func_call.rs
  crates/ruff/src/rules/flake8_gettext/rules/is_gettext_func_call.rs
  crates/ruff/src/rules/flake8_gettext/rules/mod.rs
  crates/ruff/src/rules/flake8_gettext/rules/printf_in_gettext_func_call.rs
Labels: documentation

#5808 Format `AsyncFor`
  crates/ruff_python_formatter/src/statement/stmt_async_for.rs
  crates/ruff_python_formatter/src/statement/stmt_for.rs
  crates/ruff_python_formatter/tests/snapshots/black_compatibility@py_310__starred_for_target.py.snap
  crates/ruff_python_formatter/tests/snapshots/black_compatibility@simple_cases__fmtskip8.py.snap
Labels: formatter

#5827 Read black options in format_dev script
  .gitignore
  Cargo.lock
  crates/ruff_dev/Cargo.toml
  crates/ruff_dev/src/format_dev.rs
  crates/ruff_python_formatter/README.md
Labels: formatter

#5830 Upgrade playground dependencies
  playground/.prettierignore
  playground/index.html
  playground/package-lock.json
  playground/package.json
  playground/src/Editor/settings.ts
Labels: playground

#5731 Add a tool for shrinking failing examples
  Cargo.lock
  crates/ruff_dev/src/format_dev.rs
  crates/ruff_python_formatter/src/cli.rs
  crates/ruff_shrinking/Cargo.toml
  crates/ruff_shrinking/src/main.rs
Labels: internal

#5825 perf(formatter): Improve `is_expression_parenthesized` performance
  crates/ruff_python_formatter/src/expression/parentheses.rs
  crates/ruff_python_formatter/src/trivia.rs
Labels: formatter

#5861 Remove tag information from RustPython-Parser dependency
  Cargo.toml
  fuzz/Cargo.toml
Labels: internal

#5823 perf(formatter): Use memchar for faster back tokenization
  crates/ruff_python_whitespace/src/tokenizer.rs
Labels: performance, formatter

#5848 Remove suite body tracking from `SemanticModel`
  crates/ruff/src/checkers/ast/mod.rs
  crates/ruff/src/rules/flake8_simplify/rules/reimplemented_builtin.rs
  crates/ruff_python_ast/src/lib.rs
  crates/ruff_python_ast/src/traversal.rs
  crates/ruff_python_semantic/src/model.rs
Labels: internal

#5804 Format expr generator exp
  crates/ruff_python_formatter/resources/test/fixtures/ruff/expression/generator_exp.py
  crates/ruff_python_formatter/src/expression/expr_call.rs
  crates/ruff_python_formatter/src/expression/expr_generator_exp.rs
  crates/ruff_python_formatter/tests/snapshots/black_compatibility@conditional_expression.py.snap
  crates/ruff_python_formatter/tests/snapshots/black_compatibility@py_310__pattern_matching_generic.py.snap
  crates/ruff_python_formatter/tests/snapshots/black_compatibility@py_310__pep_572_py310.py.snap
  crates/ruff_python_formatter/tests/snapshots/black_compatibility@py_37__python37.py.snap
  crates/ruff_python_formatter/tests/snapshots/black_compatibility@py_38__pep_572.py.snap
  crates/ruff_python_formatter/tests/snapshots/black_compatibility@simple_cases__expression.py.snap
  crates/ruff_python_formatter/tests/snapshots/black_compatibility@simple_cases__slices.py.snap
  crates/ruff_python_formatter/tests/snapshots/format@expression__binary.py.snap
  crates/ruff_python_formatter/tests/snapshots/format@expression__generator_exp.py.snap
  crates/ruff_python_formatter/tests/snapshots/format@statement__with.py.snap
Labels: formatter

#5806 Format `lambda` expression
  crates/ruff_python_formatter/resources/test/fixtures/ruff/expression/lambda.py
  crates/ruff_python_formatter/src/expression/expr_lambda.rs
  crates/ruff_python_formatter/src/other/arguments.rs
  crates/ruff_python_formatter/tests/snapshots/black_compatibility@py_38__pep_570.py.snap
  crates/ruff_python_formatter/tests/snapshots/black_compatibility@py_38__pep_572.py.snap
  crates/ruff_python_formatter/tests/snapshots/black_compatibility@simple_cases__bracketmatch.py.snap
  crates/ruff_python_formatter/tests/snapshots/black_compatibility@simple_cases__expression.py.snap
  crates/ruff_python_formatter/tests/snapshots/black_compatibility@simple_cases__fmtonoff.py.snap
  crates/ruff_python_formatter/tests/snapshots/black_compatibility@simple_cases__function.py.snap
  crates/ruff_python_formatter/tests/snapshots/black_compatibility@simple_cases__power_op_spacing.py.snap
  crates/ruff_python_formatter/tests/snapshots/black_compatibility@simple_cases__remove_for_brackets.py.snap
  crates/ruff_python_formatter/tests/snapshots/black_compatibility@simple_cases__slices.py.snap
  crates/ruff_python_formatter/tests/snapshots/format@expression__lambda.py.snap
Labels: formatter

#5790 Omit tuple parentheses inside comprehensions
  crates/ruff_python_formatter/resources/test/fixtures/ruff/expression/dict_comp.py
  crates/ruff_python_formatter/src/expression/expr_tuple.rs
  crates/ruff_python_formatter/src/other/comprehension.rs
  crates/ruff_python_formatter/tests/snapshots/black_compatibility@simple_cases__expression.py.snap
  crates/ruff_python_formatter/tests/snapshots/format@expression__dict_comp.py.snap
  crates/ruff_python_formatter/tests/snapshots/format@expression__list_comp.py.snap
  crates/ruff_python_formatter/tests/snapshots/format@expression__set_comp.py.snap
Labels: formatter

#5838 playground: Add left panel and use brand colors
  playground/index.html
  playground/package.json
  playground/public/fonts/Alliance-PlattMedium.otf
  playground/public/fonts/Alliance-PlattMedium.woff
  playground/public/fonts/Alliance-PlattMedium.woff2
  playground/public/fonts/Alliance-PlattRegular.otf
  playground/public/fonts/Alliance-PlattRegular.woff
  playground/public/fonts/Alliance-PlattRegular.woff2
  playground/public/fonts/Alliance-TextMedium.otf
  playground/public/fonts/Alliance-TextMedium.woff
  playground/public/fonts/Alliance-TextMedium.woff2
  playground/public/fonts/Alliance-TextRegular.otf
  playground/public/fonts/Alliance-TextRegular.woff
  playground/public/fonts/Alliance-TextRegular.woff2
  playground/src/Editor/AstralButton.tsx
  playground/src/Editor/Editor.tsx
  playground/src/Editor/Header.tsx
  playground/src/Editor/Icons.tsx
  playground/src/Editor/RepoButton.tsx
  playground/src/Editor/ShareButton.tsx
  playground/src/Editor/SideBar.tsx
  playground/src/Editor/ThemeButton.tsx
  playground/src/index.css
  playground/tailwind.config.cjs
Labels: playground

#5859 playground: Add AST/Tokens/Formatter panels
  Cargo.lock
  crates/ruff_formatter/src/lib.rs
  crates/ruff_wasm/Cargo.toml
  crates/ruff_wasm/src/lib.rs
  crates/ruff_wasm/tests/api.rs
  playground/package-lock.json
  playground/package.json
  playground/src/Editor/Editor.tsx
  playground/src/Editor/Icons.tsx
  playground/src/Editor/MonacoThemes.tsx
  playground/src/Editor/PrimarySideBar.tsx
  playground/src/Editor/ResizeHandle.tsx
  playground/src/Editor/SecondaryPanel.tsx
  playground/src/Editor/SecondarySideBar.tsx
  playground/src/Editor/SettingsEditor.tsx
  playground/src/Editor/SideBar.tsx
  playground/src/Editor/SourceEditor.tsx
  playground/src/Editor/setupMonaco.tsx
  playground/src/main.tsx
Labels: playground

#5880 Type alias stub for formatter
  crates/ruff_python_formatter/resources/test/fixtures/black/py_312/type_aliases.py
  crates/ruff_python_formatter/resources/test/fixtures/black/py_312/type_aliases.py.expect
  crates/ruff_python_formatter/resources/test/fixtures/black/py_312/type_params.py
  crates/ruff_python_formatter/resources/test/fixtures/black/py_312/type_params.py.expect
  crates/ruff_python_formatter/resources/test/fixtures/black/simple_cases/comments2.py
  crates/ruff_python_formatter/resources/test/fixtures/black/simple_cases/comments2.py.expect
  crates/ruff_python_formatter/resources/test/fixtures/black/simple_cases/ignore_pyi.py
  crates/ruff_python_formatter/resources/test/fixtures/black/simple_cases/ignore_pyi.py.expect
  crates/ruff_python_formatter/resources/test/fixtures/black/simple_cases/multiline_consecutive_open_parentheses_ignore.py
  crates/ruff_python_formatter/resources/test/fixtures/black/simple_cases/multiline_consecutive_open_parentheses_ignore.py.expect
  crates/ruff_python_formatter/resources/test/fixtures/import_black_tests.py
  crates/ruff_python_formatter/resources/test/fixtures/ruff/statement/type_alias.py
  crates/ruff_python_formatter/src/generated.rs
  crates/ruff_python_formatter/src/statement/mod.rs
  crates/ruff_python_formatter/src/statement/stmt_type_alias.rs
  crates/ruff_python_formatter/tests/snapshots/black_compatibility@py_312__type_aliases.py.snap
  crates/ruff_python_formatter/tests/snapshots/black_compatibility@py_312__type_params.py.snap
  crates/ruff_python_formatter/tests/snapshots/black_compatibility@simple_cases__comments2.py.snap
  crates/ruff_python_formatter/tests/snapshots/black_compatibility@simple_cases__ignore_pyi.py.snap
  crates/ruff_python_formatter/tests/snapshots/black_compatibility@simple_cases__multiline_consecutive_open_parentheses_ignore.py.snap
  crates/ruff_python_formatter/tests/snapshots/format@statement__type_alias.py.snap
Labels: formatter

#5889 Add missing backtick to B034 documentation
  crates/ruff/src/rules/flake8_bugbear/rules/re_sub_positional_args.rs
Labels: documentation

#5890 Fix incorrect reference in `extend-immutable-calls` documentation
  crates/ruff/src/checkers/ast/mod.rs
  crates/ruff/src/rules/flake8_bugbear/rules/function_call_in_argument_default.rs
  crates/ruff/src/rules/flake8_bugbear/rules/mod.rs
  crates/ruff/src/rules/flake8_bugbear/settings.rs
  crates/ruff/src/rules/pyflakes/settings.rs
  ruff.schema.json
Labels: documentation

#5897 Remove `__all__` enforcement rules out of binding phase
  crates/ruff/src/checkers/ast/mod.rs
  crates/ruff/src/rules/flake8_bugbear/rules/function_call_in_argument_default.rs
  crates/ruff/src/rules/pylint/rules/invalid_all_format.rs
  crates/ruff/src/rules/pylint/rules/invalid_all_object.rs
  crates/ruff_python_ast/src/all.rs
  crates/ruff_python_semantic/src/binding.rs
Labels: internal

#5844 [`flake8-pyi`] Implement PYI026
  crates/ruff/resources/test/fixtures/flake8_pyi/PYI026.py
  crates/ruff/resources/test/fixtures/flake8_pyi/PYI026.pyi
  crates/ruff/src/checkers/ast/mod.rs
  crates/ruff/src/codes.rs
  crates/ruff/src/rules/flake8_pyi/mod.rs
  crates/ruff/src/rules/flake8_pyi/rules/simple_defaults.rs
  crates/ruff/src/rules/flake8_pyi/snapshots/ruff__rules__flake8_pyi__tests__PYI026_PYI026.py.snap
  crates/ruff/src/rules/flake8_pyi/snapshots/ruff__rules__flake8_pyi__tests__PYI026_PYI026.pyi.snap
  ruff.schema.json
Labels: rule

#5835 [`flake8-use-pathlib`] Implement `os-path-getsize` and `os-path-get(a|m|c)-time` (`PTH202-205`)
  crates/ruff/resources/test/fixtures/flake8_use_pathlib/PTH202.py
  crates/ruff/resources/test/fixtures/flake8_use_pathlib/PTH203.py
  crates/ruff/resources/test/fixtures/flake8_use_pathlib/PTH204.py
  crates/ruff/resources/test/fixtures/flake8_use_pathlib/PTH205.py
  crates/ruff/src/checkers/ast/mod.rs
  crates/ruff/src/codes.rs
  crates/ruff/src/rules/flake8_use_pathlib/mod.rs
  crates/ruff/src/rules/flake8_use_pathlib/rules/mod.rs
  crates/ruff/src/rules/flake8_use_pathlib/rules/os_path_getatime.rs
  crates/ruff/src/rules/flake8_use_pathlib/rules/os_path_getctime.rs
  crates/ruff/src/rules/flake8_use_pathlib/rules/os_path_getmtime.rs
  crates/ruff/src/rules/flake8_use_pathlib/rules/os_path_getsize.rs
  crates/ruff/src/rules/flake8_use_pathlib/rules/path_constructor_current_directory.rs
  crates/ruff/src/rules/flake8_use_pathlib/rules/replaceable_by_pathlib.rs
  crates/ruff/src/rules/flake8_use_pathlib/snapshots/ruff__rules__flake8_use_pathlib__tests__PTH202_PTH202.py.snap
  crates/ruff/src/rules/flake8_use_pathlib/snapshots/ruff__rules__flake8_use_pathlib__tests__PTH203_PTH203.py.snap
  crates/ruff/src/rules/flake8_use_pathlib/snapshots/ruff__rules__flake8_use_pathlib__tests__PTH204_PTH204.py.snap
  crates/ruff/src/rules/flake8_use_pathlib/snapshots/ruff__rules__flake8_use_pathlib__tests__PTH205_PTH205.py.snap
  ruff.schema.json
Labels: rule

#5868 Add `flake8-fixme` documentation
  crates/ruff/src/rules/flake8_fixme/rules/todos.rs
  crates/ruff/src/rules/flake8_fixme/snapshots/ruff__rules__flake8_fixme__tests__line-contains-fixme_T00.py.snap
  crates/ruff/src/rules/flake8_fixme/snapshots/ruff__rules__flake8_fixme__tests__line-contains-hack_T00.py.snap
  crates/ruff/src/rules/flake8_fixme/snapshots/ruff__rules__flake8_fixme__tests__line-contains-todo_T00.py.snap
  crates/ruff/src/rules/flake8_fixme/snapshots/ruff__rules__flake8_fixme__tests__line-contains-xxx_T00.py.snap
Labels: documentation

#5904 Move undefined deletions into post-model-building pass
  crates/ruff/src/checkers/ast/mod.rs
  crates/ruff_python_semantic/src/model.rs
  crates/ruff_python_semantic/src/reference.rs
Labels: internal

#5906 Playground: Fix escaped quotes handling
  crates/ruff_formatter/src/format_element/document.rs
  playground/src/Editor/setupMonaco.tsx
Labels: playground

#5898 Extend shrinking script to also remove tokens and characters
  crates/ruff_shrinking/src/main.rs
Labels: internal

#5912 Avoid line break before `for` in comprehension if outer expression expands
  crates/ruff_python_formatter/resources/test/fixtures/ruff/expression/dict_comp.py
  crates/ruff_python_formatter/resources/test/fixtures/ruff/expression/list_comp.py
  crates/ruff_python_formatter/resources/test/fixtures/ruff/expression/set_comp.py
  crates/ruff_python_formatter/src/expression/expr_dict_comp.rs
  crates/ruff_python_formatter/src/expression/expr_list_comp.rs
  crates/ruff_python_formatter/src/expression/expr_set_comp.rs
  crates/ruff_python_formatter/tests/snapshots/format@expression__binary.py.snap
  crates/ruff_python_formatter/tests/snapshots/format@expression__dict_comp.py.snap
  crates/ruff_python_formatter/tests/snapshots/format@expression__list_comp.py.snap
  crates/ruff_python_formatter/tests/snapshots/format@expression__set_comp.py.snap
Labels: formatter

#5922 Improve slice formatting
  crates/ruff_python_formatter/resources/test/fixtures/ruff/expression/slice.py
  crates/ruff_python_formatter/src/expression/expr_slice.rs
  crates/ruff_python_formatter/tests/snapshots/black_compatibility@simple_cases__expression.py.snap
  crates/ruff_python_formatter/tests/snapshots/black_compatibility@simple_cases__fmtonoff.py.snap
  crates/ruff_python_formatter/tests/snapshots/black_compatibility@simple_cases__function.py.snap
  crates/ruff_python_formatter/tests/snapshots/black_compatibility@simple_cases__slices.py.snap
  crates/ruff_python_formatter/tests/snapshots/format@expression__slice.py.snap
Labels: formatter

#5895 [`flake8-pyi`] Implement PYI017
  crates/ruff/resources/test/fixtures/flake8_pyi/PYI017.py
  crates/ruff/resources/test/fixtures/flake8_pyi/PYI017.pyi
  crates/ruff/src/checkers/ast/mod.rs
  crates/ruff/src/codes.rs
  crates/ruff/src/rules/flake8_pyi/mod.rs
  crates/ruff/src/rules/flake8_pyi/rules/complex_assignment_in_stub.rs
  crates/ruff/src/rules/flake8_pyi/rules/mod.rs
  crates/ruff/src/rules/flake8_pyi/snapshots/ruff__rules__flake8_pyi__tests__PYI017_PYI017.py.snap
  crates/ruff/src/rules/flake8_pyi/snapshots/ruff__rules__flake8_pyi__tests__PYI017_PYI017.pyi.snap
  ruff.schema.json
Labels: rule

#5928 Move undefined-local into a post-model-building pass
  crates/ruff/resources/test/fixtures/pyflakes/F823.py
  crates/ruff/src/checkers/ast/mod.rs
  crates/ruff/src/rules/pyflakes/rules/undefined_local.rs
  crates/ruff/src/rules/pyflakes/snapshots/ruff__rules__pyflakes__tests__F823_F823.py.snap
Labels: internal

#5934 Close unclosed code block in documentation
  crates/ruff/src/rules/pylint/rules/bad_str_strip_call.rs
Labels: documentation

#5815 Add documentation for the pathlib rules
  crates/ruff/src/rules/flake8_use_pathlib/rules/os_path_getatime.rs
  crates/ruff/src/rules/flake8_use_pathlib/rules/os_path_getctime.rs
  crates/ruff/src/rules/flake8_use_pathlib/rules/os_path_getmtime.rs
  crates/ruff/src/rules/flake8_use_pathlib/rules/os_path_getsize.rs
  crates/ruff/src/rules/flake8_use_pathlib/rules/replaceable_by_pathlib.rs
  crates/ruff/src/rules/flake8_use_pathlib/violations.rs
Labels: documentation

#5938 Remove some unnecessary lifetime annotations
  crates/ruff/src/rules/flake8_pie/rules/duplicate_class_field_definition.rs
  crates/ruff/src/rules/flake8_pie/rules/non_unique_enums.rs
  crates/ruff/src/rules/flake8_pyi/rules/ellipsis_in_non_empty_class_body.rs
  crates/ruff/src/rules/flake8_pyi/rules/pass_in_class_body.rs
  crates/ruff/src/rules/pylint/rules/useless_return.rs
Labels: internal

#5915 Document formatter error shrinking
  crates/ruff_shrinking/src/main.rs
Labels: formatter

#5921 Format `ExprYield`/`ExprYieldFrom`
  crates/ruff_python_formatter/resources/test/fixtures/ruff/expression/yield.py
  crates/ruff_python_formatter/resources/test/fixtures/ruff/expression/yield_from.py
  crates/ruff_python_formatter/src/expression/expr_yield.rs
  crates/ruff_python_formatter/src/expression/expr_yield_from.rs
  crates/ruff_python_formatter/tests/snapshots/black_compatibility@miscellaneous__debug_visitor.py.snap
  crates/ruff_python_formatter/tests/snapshots/black_compatibility@miscellaneous__long_strings_flag_disabled.py.snap
  crates/ruff_python_formatter/tests/snapshots/black_compatibility@py_38__python38.py.snap
  crates/ruff_python_formatter/tests/snapshots/black_compatibility@simple_cases__expression.py.snap
  crates/ruff_python_formatter/tests/snapshots/black_compatibility@simple_cases__fmtonoff.py.snap
  crates/ruff_python_formatter/tests/snapshots/black_compatibility@simple_cases__function.py.snap
  crates/ruff_python_formatter/tests/snapshots/black_compatibility@simple_cases__remove_await_parens.py.snap
  crates/ruff_python_formatter/tests/snapshots/format@expression__yield.py.snap
  crates/ruff_python_formatter/tests/snapshots/format@expression__yield_from.py.snap
Labels: formatter

#5944 Fix formatting lambda with empty arguments
  Cargo.lock
  Cargo.toml
  crates/ruff_python_formatter/resources/test/fixtures/ruff/expression/lambda.py
  crates/ruff_python_formatter/tests/snapshots/format@expression__lambda.py.snap
  fuzz/Cargo.toml
Labels: formatter

#5950 Fix RustPython rev to main branch
  Cargo.lock
  Cargo.toml
  fuzz/Cargo.toml
Labels: internal

#5962 Move nonlocal-without-binding out of binding step
  crates/ruff/src/checkers/ast/mod.rs
Labels: internal

#5964 Avoid collapsing `elif` and `else` branches during import sorting
  crates/ruff/resources/test/fixtures/isort/if_elif_else.py
  crates/ruff/resources/test/fixtures/isort/match_case.py
  crates/ruff/src/rules/isort/block.rs
  crates/ruff/src/rules/isort/mod.rs
  crates/ruff/src/rules/isort/snapshots/ruff__rules__isort__tests__if_elif_else.py.snap
  crates/ruff/src/rules/isort/snapshots/ruff__rules__isort__tests__match_case.py.snap
Labels: bug
