Repository astral-sh/ruff, pull requests merged in 2024-03, with the labels that each got.

#10140 [`pylint`] Implement `singledispatch-method` (`E1519`)
  crates/ruff_linter/resources/test/fixtures/pylint/singledispatch_method.py
  crates/ruff_linter/src/checkers/ast/analyze/deferred_scopes.rs
  crates/ruff_linter/src/codes.rs
  crates/ruff_linter/src/rules/flake8_type_checking/helpers.rs
  crates/ruff_linter/src/rules/pylint/mod.rs
  crates/ruff_linter/src/rules/pylint/rules/mod.rs
  crates/ruff_linter/src/rules/pylint/rules/singledispatch_method.rs
  crates/ruff_linter/src/rules/pylint/snapshots/ruff_linter__rules__pylint__tests__PLE1519_singledispatch_method.py.snap
  ruff.schema.json
Labels: rule, preview

#10176 [`pylint`] Implement `useless-exception-statement` (`W0133`)
  crates/ruff_linter/resources/test/fixtures/pylint/useless_exception_statement.py
  crates/ruff_linter/src/checkers/ast/analyze/statement.rs
  crates/ruff_linter/src/codes.rs
  crates/ruff_linter/src/rules/pylint/mod.rs
  crates/ruff_linter/src/rules/pylint/rules/mod.rs
  crates/ruff_linter/src/rules/pylint/rules/useless_exception_statement.rs
  crates/ruff_linter/src/rules/pylint/snapshots/ruff_linter__rules__pylint__tests__PLW0133_useless_exception_statement.py.snap
  ruff.schema.json
Labels: rule, preview

#10149 Implement isort's `default-section` setting
  crates/ruff/tests/snapshots/show_settings__display_default_settings.snap
  crates/ruff_linter/resources/test/fixtures/isort/default_section_user_defined.py
  crates/ruff_linter/resources/test/fixtures/isort/no_standard_library.py
  crates/ruff_linter/src/rules/flake8_type_checking/rules/typing_only_runtime_import.rs
  crates/ruff_linter/src/rules/isort/categorize.rs
  crates/ruff_linter/src/rules/isort/mod.rs
  crates/ruff_linter/src/rules/isort/settings.rs
  crates/ruff_linter/src/rules/isort/snapshots/ruff_linter__rules__isort__tests__default_section_can_map_to_user_defined_section_default_section_user_defined.py.snap
  crates/ruff_linter/src/rules/isort/snapshots/ruff_linter__rules__isort__tests__no_standard_library_no_standard_library.py.snap
  crates/ruff_workspace/src/options.rs
  ruff.schema.json
Labels: isort, configuration

#10178 Fix RUF028 not allowing `# fmt: skip` on match cases
  crates/ruff_linter/resources/test/fixtures/ruff/RUF028.py
  crates/ruff_linter/src/rules/ruff/rules/invalid_formatter_suppression_comment.rs
  crates/ruff_linter/src/rules/ruff/snapshots/ruff_linter__rules__ruff__tests__RUF028_RUF028.py.snap
Labels: bug

#10180 Remove indico ecosystem override
  python/ruff-ecosystem/ruff_ecosystem/defaults.py
Labels: ci

#10182 Fix broken documentation links affected by namespace changes in lint rules
  crates/ruff_linter/src/rules/ruff/rules/ambiguous_unicode_character.rs
  docs/faq.md
  docs/linter.md
Labels: documentation

#10183 CLI: Color entire line in Diffs
  crates/ruff_linter/src/source_kind.rs
Labels: cli

#10190 Removed unused variable in `TRY300`'s example
  crates/ruff_linter/src/rules/tryceratops/rules/try_consider_else.rs
Labels: documentation

#10194 Check for use of `debugpy` and `ptvsd` debug modules (#10177)
  crates/ruff_linter/resources/test/fixtures/flake8_debugger/T100.py
  crates/ruff_linter/src/rules/flake8_debugger/rules/debugger.rs
  crates/ruff_linter/src/rules/flake8_debugger/snapshots/ruff_linter__rules__flake8_debugger__tests__T100_T100.py.snap
Labels: rule

#10197 Update README.md, add Kraken Tech
  README.md
Labels: documentation

#10204 Run `cargo update`
  Cargo.lock
Labels: internal

#10203 Respect external codes in file-level exemptions
  crates/ruff/tests/lint.rs
  crates/ruff_linter/src/checkers/noqa.rs
  crates/ruff_linter/src/linter.rs
  crates/ruff_linter/src/noqa.rs
Labels: bug, suppression

#10206 Avoid false-positives for parens-on-raise with `futures.exception()`
  crates/ruff_linter/resources/test/fixtures/flake8_raise/RSE102.py
  crates/ruff_linter/src/rules/flake8_raise/rules/unnecessary_paren_on_raise_exception.rs
  crates/ruff_linter/src/rules/flake8_raise/snapshots/ruff_linter__rules__flake8_raise__tests__unnecessary-paren-on-raise-exception_RSE102.py.snap
Labels: bug

#10209 Skip another invalid notebook in the OpenAI repository
  python/ruff-ecosystem/ruff_ecosystem/defaults.py
Labels: ci

#10213 Remove unneeded lifetime bounds
  crates/ruff_linter/src/checkers/ast/mod.rs
  crates/ruff_linter/src/rules/flake8_bugbear/rules/loop_variable_overrides_iterator.rs
  crates/ruff_linter/src/rules/flake8_bugbear/rules/reuse_of_groupby_generator.rs
  crates/ruff_linter/src/rules/flake8_pytest_style/rules/assertion.rs
  crates/ruff_linter/src/rules/flake8_pytest_style/rules/fixture.rs
  crates/ruff_linter/src/rules/flake8_pytest_style/rules/patch.rs
  crates/ruff_linter/src/rules/isort/block.rs
  crates/ruff_linter/src/rules/perflint/rules/unnecessary_list_cast.rs
  crates/ruff_linter/src/rules/pylint/rules/unnecessary_lambda.rs
  crates/ruff_linter/src/rules/tryceratops/rules/raise_within_try.rs
  crates/ruff_linter/src/rules/tryceratops/rules/type_check_without_type_error.rs
  crates/ruff_linter/src/rules/tryceratops/rules/verbose_raise.rs
  crates/ruff_python_ast/src/helpers.rs
Labels: internal

#10220 Remove trailing space from `CapWords` message
  crates/ruff/tests/lint.rs
  crates/ruff_linter/src/rules/pep8_naming/rules/invalid_class_name.rs
  crates/ruff_linter/src/rules/pep8_naming/snapshots/ruff_linter__rules__pep8_naming__tests__N801_N801.py.snap
  crates/ruff_linter/src/rules/pep8_naming/snapshots/ruff_linter__rules__pep8_naming__tests__ignore_names_N801_N801.py.snap
Labels: bug

#10218 `docs`: update docker release version
  docs/installation.md
Labels: documentation

#10215 [`pep8_naming`] Add fixes `N804` and `N805`
  crates/ruff_linter/resources/test/fixtures/pep8_naming/N804.py
  crates/ruff_linter/resources/test/fixtures/pep8_naming/N805.py
  crates/ruff_linter/src/checkers/ast/analyze/deferred_scopes.rs
  crates/ruff_linter/src/checkers/ast/analyze/statement.rs
  crates/ruff_linter/src/rules/pep8_naming/rules/invalid_first_argument_name.rs
  crates/ruff_linter/src/rules/pep8_naming/rules/invalid_first_argument_name_for_class_method.rs
  crates/ruff_linter/src/rules/pep8_naming/rules/invalid_first_argument_name_for_method.rs
  crates/ruff_linter/src/rules/pep8_naming/rules/mod.rs
  crates/ruff_linter/src/rules/pep8_naming/snapshots/ruff_linter__rules__pep8_naming__tests__N804_N804.py.snap
  crates/ruff_linter/src/rules/pep8_naming/snapshots/ruff_linter__rules__pep8_naming__tests__N805_N805.py.snap
  crates/ruff_linter/src/rules/pep8_naming/snapshots/ruff_linter__rules__pep8_naming__tests__classmethod_decorators.snap
  crates/ruff_linter/src/rules/pep8_naming/snapshots/ruff_linter__rules__pep8_naming__tests__ignore_names_N804_N804.py.snap
  crates/ruff_linter/src/rules/pep8_naming/snapshots/ruff_linter__rules__pep8_naming__tests__ignore_names_N805_N805.py.snap
  crates/ruff_linter/src/rules/pep8_naming/snapshots/ruff_linter__rules__pep8_naming__tests__staticmethod_decorators.snap
Labels: fixes

#10221 Refine SemanticModel lifetime bounds
  crates/ruff_linter/src/rules/flake8_type_checking/imports.rs
  crates/ruff_linter/src/rules/pyflakes/rules/unused_import.rs
  crates/ruff_python_semantic/src/binding.rs
  crates/ruff_python_semantic/src/definition.rs
  crates/ruff_python_semantic/src/globals.rs
  crates/ruff_python_semantic/src/model.rs
  crates/ruff_python_semantic/src/scope.rs
Labels: internal

#9587 [`pylint`] - add fix for unary expressions in `PLC2801`
  crates/ruff_linter/resources/test/fixtures/pylint/unnecessary_dunder_call.py
  crates/ruff_linter/src/rules/pylint/rules/unnecessary_dunder_call.rs
  crates/ruff_linter/src/rules/pylint/snapshots/ruff_linter__rules__pylint__tests__PLC2801_unnecessary_dunder_call.py.snap
Labels: fixes

#10150 Make `--config` and `--isolated` global flags
  crates/ruff/src/args.rs
  crates/ruff/src/commands/format.rs
  crates/ruff/src/commands/format_stdin.rs
  crates/ruff/src/lib.rs
  crates/ruff/src/resolve.rs
  crates/ruff/tests/version.rs
  crates/ruff_dev/src/format_dev.rs
  crates/ruff_dev/src/main.rs
  crates/ruff_linter/src/logging.rs
  docs/configuration.md
Labels: cli

#10219 Move shell expansion into `--config` lookup
  crates/ruff/src/args.rs
  crates/ruff/src/resolve.rs
  crates/ruff/tests/format.rs
  crates/ruff/tests/lint.rs
Labels: bug, cli

#10233 docs: fix a rustdoc typo in C409 rule
  crates/ruff_linter/src/rules/flake8_comprehensions/rules/unnecessary_literal_within_tuple_call.rs
Labels: documentation

#10168 Improve documentation of the preview mode
  docs/preview.md
Labels: documentation

#10096 [`pycodestyle`] Respect `isort` settings in blank line rules (`E3*`)
  crates/ruff_linter/resources/test/fixtures/pycodestyle/.editorconfig
  crates/ruff_linter/resources/test/fixtures/pycodestyle/E30_isort.py
  crates/ruff_linter/src/checkers/tokens.rs
  crates/ruff_linter/src/rules/pycodestyle/mod.rs
  crates/ruff_linter/src/rules/pycodestyle/rules/blank_lines.rs
  crates/ruff_linter/src/rules/pycodestyle/snapshots/ruff_linter__rules__pycodestyle__tests__E303_E30.py.snap
  crates/ruff_linter/src/rules/pycodestyle/snapshots/ruff_linter__rules__pycodestyle__tests__blank_lines_top_level_isort_compatibility-lines-after(-1)-between(0).snap
  crates/ruff_linter/src/rules/pycodestyle/snapshots/ruff_linter__rules__pycodestyle__tests__blank_lines_top_level_isort_compatibility-lines-after(0)-between(0).snap
  crates/ruff_linter/src/rules/pycodestyle/snapshots/ruff_linter__rules__pycodestyle__tests__blank_lines_top_level_isort_compatibility-lines-after(1)-between(1).snap
  crates/ruff_linter/src/rules/pycodestyle/snapshots/ruff_linter__rules__pycodestyle__tests__blank_lines_top_level_isort_compatibility-lines-after(4)-between(4).snap
  crates/ruff_linter/src/rules/pycodestyle/snapshots/ruff_linter__rules__pycodestyle__tests__too_many_blank_lines_isort_compatibility-lines-after(-1)-between(0).snap
  crates/ruff_linter/src/rules/pycodestyle/snapshots/ruff_linter__rules__pycodestyle__tests__too_many_blank_lines_isort_compatibility-lines-after(0)-between(0).snap
  crates/ruff_linter/src/rules/pycodestyle/snapshots/ruff_linter__rules__pycodestyle__tests__too_many_blank_lines_isort_compatibility-lines-after(1)-between(1).snap
  crates/ruff_linter/src/rules/pycodestyle/snapshots/ruff_linter__rules__pycodestyle__tests__too_many_blank_lines_isort_compatibility-lines-after(4)-between(4).snap
  crates/ruff_python_codegen/src/stylist.rs
  crates/ruff_source_file/src/locator.rs
Labels: bug, preview

#10098 [`pycodestyle`]: Make blank lines in typing stub files optional (`E3*`)
  crates/ruff_linter/resources/test/fixtures/pycodestyle/E30.pyi
  crates/ruff_linter/resources/test/fixtures/pycodestyle/E30_isort.pyi
  crates/ruff_linter/src/checkers/tokens.rs
  crates/ruff_linter/src/rules/pycodestyle/mod.rs
  crates/ruff_linter/src/rules/pycodestyle/rules/blank_lines.rs
  crates/ruff_linter/src/rules/pycodestyle/snapshots/ruff_linter__rules__pycodestyle__tests__blank_lines_E301_typing_stub.snap
  crates/ruff_linter/src/rules/pycodestyle/snapshots/ruff_linter__rules__pycodestyle__tests__blank_lines_E302_typing_stub.snap
  crates/ruff_linter/src/rules/pycodestyle/snapshots/ruff_linter__rules__pycodestyle__tests__blank_lines_E303_typing_stub.snap
  crates/ruff_linter/src/rules/pycodestyle/snapshots/ruff_linter__rules__pycodestyle__tests__blank_lines_E304_typing_stub.snap
  crates/ruff_linter/src/rules/pycodestyle/snapshots/ruff_linter__rules__pycodestyle__tests__blank_lines_E305_typing_stub.snap
  crates/ruff_linter/src/rules/pycodestyle/snapshots/ruff_linter__rules__pycodestyle__tests__blank_lines_E306_typing_stub.snap
  crates/ruff_linter/src/rules/pycodestyle/snapshots/ruff_linter__rules__pycodestyle__tests__blank_lines_typing_stub_isort.snap
Labels: bug, preview

#10244 Add encoding when opening files in generate_mkdocs.py
  scripts/generate_mkdocs.py
Labels: internal

#10214 refactor: Use `QualifiedName` for `Imported::call_path`
  Cargo.lock
  crates/ruff_linter/src/checkers/ast/mod.rs
  crates/ruff_linter/src/renamer.rs
  crates/ruff_linter/src/rules/flake8_debugger/rules/debugger.rs
  crates/ruff_linter/src/rules/flake8_import_conventions/rules/unconventional_import_alias.rs
  crates/ruff_linter/src/rules/flake8_pyi/rules/unaliased_collections_abc_set_import.rs
  crates/ruff_linter/src/rules/flake8_type_checking/rules/runtime_import_in_type_checking_block.rs
  crates/ruff_linter/src/rules/flake8_type_checking/rules/typing_only_runtime_import.rs
  crates/ruff_linter/src/rules/pandas_vet/helpers.rs
  crates/ruff_linter/src/rules/pyflakes/rules/unused_import.rs
  crates/ruff_linter/src/rules/pylint/rules/import_private_name.rs
  crates/ruff_linter/src/rules/ruff/typing.rs
  crates/ruff_python_ast/Cargo.toml
  crates/ruff_python_ast/src/name.rs
  crates/ruff_python_semantic/Cargo.toml
  crates/ruff_python_semantic/src/analyze/typing.rs
  crates/ruff_python_semantic/src/binding.rs
  crates/ruff_python_semantic/src/model.rs
Labels: internal

#10238 [`pyupgrade`] Generate diagnostic for all valid f-string conversions regardless of line-length (`UP032`)
  crates/ruff_linter/src/rules/pyupgrade/rules/f_strings.rs
  crates/ruff_linter/src/rules/pyupgrade/snapshots/ruff_linter__rules__pyupgrade__tests__UP032_0.py.snap
  crates/ruff_linter/src/rules/pyupgrade/snapshots/ruff_linter__rules__pyupgrade__tests__UP032_1.py.snap
  crates/ruff_linter/src/rules/pyupgrade/snapshots/ruff_linter__rules__pyupgrade__tests__UP032_2.py.snap
Labels: rule

#10249 Fix `ruff-action` documentation to consistently use `args` instead of `options`
  docs/integrations.md
Labels: documentation

#8613 Tweak `E712` docs
  crates/ruff_linter/src/rules/pycodestyle/rules/literal_comparisons.rs
  crates/ruff_linter/src/rules/pycodestyle/snapshots/ruff_linter__rules__pycodestyle__tests__E712_E712.py.snap
  crates/ruff_linter/src/rules/pycodestyle/snapshots/ruff_linter__rules__pycodestyle__tests__constant_literals.snap
Labels: documentation

#10257 Set maturin version in `release.yaml`
  .github/workflows/release.yaml
Labels: release

#10265 Avoid repeating function calls in f-string conversions
  crates/ruff_linter/resources/test/fixtures/pyupgrade/UP032_0.py
  crates/ruff_linter/src/rules/pyupgrade/rules/f_strings.rs
  crates/ruff_linter/src/rules/pyupgrade/snapshots/ruff_linter__rules__pyupgrade__tests__UP032_0.py.snap
Labels: bug

#10269 Assert the parser is at augmented assign token
  crates/ruff_python_parser/resources/invalid/statements/invalid_assignment_targets.py
  crates/ruff_python_parser/resources/invalid/statements/invalid_augmented_assignment_target.py
  crates/ruff_python_parser/resources/valid/statement/augmented_assignment.py
  crates/ruff_python_parser/src/parser/mod.rs
  crates/ruff_python_parser/src/parser/statement.rs
  crates/ruff_python_parser/tests/snapshots/invalid_syntax@statements__invalid_assignment_targets.py.snap
  crates/ruff_python_parser/tests/snapshots/invalid_syntax@statements__invalid_augmented_assignment_target.py.snap
  crates/ruff_python_parser/tests/snapshots/valid_syntax@statement__augmented_assignment.py.snap
Labels: parser

#10263 [`pyupgrade`] Allow fixes for f-string rule regardless of line length (`UP032`)
  crates/ruff_linter/src/checkers/ast/analyze/expression.rs
  crates/ruff_linter/src/fix/edits.rs
  crates/ruff_linter/src/rules/pyupgrade/rules/f_strings.rs
  crates/ruff_linter/src/rules/pyupgrade/snapshots/ruff_linter__rules__pyupgrade__tests__UP032_0.py.snap
Labels: fixes

#10270 Encapsulate `Program` fields
  crates/ruff_python_parser/src/parser/mod.rs
  crates/ruff_python_parser/tests/fixtures.rs
Labels: parser

#10285 Treat `typing.Annotated` subscripts as type definitions
  crates/ruff_linter/resources/test/fixtures/pyflakes/F401_23.py
  crates/ruff_linter/src/checkers/ast/mod.rs
  crates/ruff_linter/src/rules/pyflakes/mod.rs
  crates/ruff_linter/src/rules/pyflakes/snapshots/ruff_linter__rules__pyflakes__tests__F401_F401_23.py.snap
Labels: bug

#10254 Include actual conditions in E712 diagnostics
  crates/ruff_linter/src/rules/pycodestyle/rules/literal_comparisons.rs
  crates/ruff_linter/src/rules/pycodestyle/snapshots/ruff_linter__rules__pycodestyle__tests__E712_E712.py.snap
  crates/ruff_linter/src/rules/pycodestyle/snapshots/ruff_linter__rules__pycodestyle__tests__constant_literals.snap
Labels: rule

#10287 Rename to include "token" in method name
  crates/ruff_python_parser/src/parser/expression.rs
  crates/ruff_python_parser/src/parser/mod.rs
  crates/ruff_python_parser/src/parser/pattern.rs
  crates/ruff_python_parser/src/parser/progress.rs
  crates/ruff_python_parser/src/parser/statement.rs
Labels: parser

#10297 Fix trailing kwargs end of line comment after slash
  crates/ruff_python_formatter/resources/test/fixtures/ruff/statement/function.py
  crates/ruff_python_formatter/src/other/parameters.rs
  crates/ruff_python_formatter/tests/snapshots/format@statement__function.py.snap
Labels: bug, formatter

#10271 Remove deprecated parsing list functions
  crates/ruff_python_formatter/src/other/f_string_element.rs
  crates/ruff_python_parser/src/parser/expression.rs
  crates/ruff_python_parser/src/parser/mod.rs
  crates/ruff_python_parser/src/parser/pattern.rs
  crates/ruff_python_parser/src/parser/statement.rs
Labels: parser

#10288 Improve various assignment target error
  crates/ruff_python_parser/src/error.rs
  crates/ruff_python_parser/src/parser/expression.rs
  crates/ruff_python_parser/src/parser/helpers.rs
  crates/ruff_python_parser/src/parser/statement.rs
Labels: parser

#10293 Remove `skip_until` parser method
  crates/ruff_python_parser/src/parser/mod.rs
  crates/ruff_python_parser/src/parser/pattern.rs
  crates/ruff_python_parser/src/parser/statement.rs
Labels: parser

#10296 Refactor with statement formatting to have explicit layouts
  crates/ruff_python_formatter/src/builders.rs
  crates/ruff_python_formatter/src/other/arguments.rs
  crates/ruff_python_formatter/src/other/commas.rs
  crates/ruff_python_formatter/src/other/with_item.rs
  crates/ruff_python_formatter/src/statement/stmt_with.rs
Labels: internal, formatter

#10274 Fix unstable with-items formatting
  crates/ruff_python_formatter/resources/test/fixtures/ruff/statement/with.py
  crates/ruff_python_formatter/resources/test/fixtures/ruff/statement/with_39.py
  crates/ruff_python_formatter/src/other/with_item.rs
  crates/ruff_python_formatter/src/statement/stmt_with.rs
  crates/ruff_python_formatter/tests/snapshots/format@statement__with.py.snap
  crates/ruff_python_formatter/tests/snapshots/format@statement__with_39.py.snap
Labels: bug, formatter

#10276 Formatter: Improve single-with item formatting for Python 3.8 or older
  crates/ruff_python_formatter/resources/test/fixtures/ruff/statement/with.py
  crates/ruff_python_formatter/src/other/with_item.rs
  crates/ruff_python_formatter/src/preview.rs
  crates/ruff_python_formatter/src/statement/stmt_with.rs
  crates/ruff_python_formatter/tests/snapshots/format@statement__with.py.snap
Labels: formatter, preview

#10304 Bump version to v0.3.2
  CHANGELOG.md
  Cargo.lock
  README.md
  crates/ruff/Cargo.toml
  crates/ruff_linter/Cargo.toml
  crates/ruff_shrinking/Cargo.toml
  docs/integrations.md
  pyproject.toml
  scripts/benchmarks/pyproject.toml
Labels: release

#10158 `ruff server` - A new built-in LSP for Ruff, written in Rust
  Cargo.lock
  Cargo.toml
  crates/ruff/Cargo.toml
  crates/ruff/src/args.rs
  crates/ruff/src/commands/mod.rs
  crates/ruff/src/commands/server.rs
  crates/ruff/src/lib.rs
  crates/ruff_formatter/src/lib.rs
  crates/ruff_server/Cargo.toml
  crates/ruff_server/README.md
  crates/ruff_server/resources/test/fixtures/pandas_html.py
  crates/ruff_server/src/edit.rs
  crates/ruff_server/src/edit/document.rs
  crates/ruff_server/src/edit/range.rs
  crates/ruff_server/src/format.rs
  crates/ruff_server/src/lib.rs
  crates/ruff_server/src/lint.rs
  crates/ruff_server/src/server.rs
  crates/ruff_server/src/server/api.rs
  crates/ruff_server/src/server/api/notifications.rs
  crates/ruff_server/src/server/api/notifications/cancel.rs
  crates/ruff_server/src/server/api/notifications/did_change.rs
  crates/ruff_server/src/server/api/notifications/did_change_configuration.rs
  crates/ruff_server/src/server/api/notifications/did_change_workspace.rs
  crates/ruff_server/src/server/api/notifications/did_close.rs
  crates/ruff_server/src/server/api/notifications/did_open.rs
  crates/ruff_server/src/server/api/requests.rs
  crates/ruff_server/src/server/api/requests/code_action.rs
  crates/ruff_server/src/server/api/requests/diagnostic.rs
  crates/ruff_server/src/server/api/requests/format.rs
  crates/ruff_server/src/server/api/requests/format_range.rs
  crates/ruff_server/src/server/api/traits.rs
  crates/ruff_server/src/server/client.rs
  crates/ruff_server/src/server/schedule.rs
  crates/ruff_server/src/server/schedule/task.rs
  crates/ruff_server/src/server/schedule/thread.rs
  crates/ruff_server/src/server/schedule/thread/pool.rs
  crates/ruff_server/src/server/schedule/thread/priority.rs
  crates/ruff_server/src/session.rs
  crates/ruff_server/src/session/types.rs
  crates/ruff_server/tests/document.rs
  crates/ruff_server/tests/snapshots/document__delete_lines_pandas_html.snap
  crates/ruff_source_file/src/line_index.rs
  crates/ruff_source_file/src/locator.rs
  docs/configuration.md
Labels: preview

#10313 [`flake8-bandit`] Implement upstream updates for `S311`, `S324` and `S605`
  crates/ruff_linter/resources/test/fixtures/flake8_bandit/S311.py
  crates/ruff_linter/resources/test/fixtures/flake8_bandit/S324.py
  crates/ruff_linter/resources/test/fixtures/flake8_bandit/S605.py
  crates/ruff_linter/src/rules/flake8_bandit/mod.rs
  crates/ruff_linter/src/rules/flake8_bandit/rules/hashlib_insecure_hash_functions.rs
  crates/ruff_linter/src/rules/flake8_bandit/rules/shell_injection.rs
  crates/ruff_linter/src/rules/flake8_bandit/rules/suspicious_function_call.rs
  crates/ruff_linter/src/rules/flake8_bandit/snapshots/ruff_linter__rules__flake8_bandit__tests__S311_S311.py.snap
  crates/ruff_linter/src/rules/flake8_bandit/snapshots/ruff_linter__rules__flake8_bandit__tests__S324_S324.py.snap
  crates/ruff_linter/src/rules/flake8_bandit/snapshots/ruff_linter__rules__flake8_bandit__tests__S605_S605.py.snap
Labels: rule

#10315 [`pycodestyle`] Do not trigger `E225` and `E275` when the next token is a ')'
  crates/ruff_linter/resources/test/fixtures/pycodestyle/E2_syntax_error.py
  crates/ruff_linter/src/rules/pycodestyle/mod.rs
  crates/ruff_linter/src/rules/pycodestyle/rules/logical_lines/missing_whitespace_after_keyword.rs
  crates/ruff_linter/src/rules/pycodestyle/rules/logical_lines/missing_whitespace_around_operator.rs
  crates/ruff_linter/src/rules/pycodestyle/snapshots/ruff_linter__rules__pycodestyle__tests__white_space_syntax_error_compatibility.snap
Labels: bug

#10305 Add release script
  CONTRIBUTING.md
  scripts/release/bump.sh
  scripts/release/requirements.in
  scripts/release/requirements.txt
Labels: internal

#10341 F821, F822: fix false positive for `.pyi` files; add more test coverage for `.pyi` files
  crates/ruff_linter/resources/test/fixtures/pyflakes/F821_11.pyi
  crates/ruff_linter/resources/test/fixtures/pyflakes/F821_26.py
  crates/ruff_linter/resources/test/fixtures/pyflakes/F821_26.pyi
  crates/ruff_linter/resources/test/fixtures/pyflakes/F821_27.py
  crates/ruff_linter/resources/test/fixtures/pyflakes/F821_5.pyi
  crates/ruff_linter/resources/test/fixtures/pyflakes/F822_0.pyi
  crates/ruff_linter/src/checkers/ast/mod.rs
  crates/ruff_linter/src/rules/pyflakes/mod.rs
  crates/ruff_linter/src/rules/pyflakes/snapshots/ruff_linter__rules__pyflakes__tests__F821_F821_11.pyi.snap
  crates/ruff_linter/src/rules/pyflakes/snapshots/ruff_linter__rules__pyflakes__tests__F821_F821_26.py.snap
  crates/ruff_linter/src/rules/pyflakes/snapshots/ruff_linter__rules__pyflakes__tests__F821_F821_26.pyi.snap
  crates/ruff_linter/src/rules/pyflakes/snapshots/ruff_linter__rules__pyflakes__tests__F821_F821_27.py.snap
  crates/ruff_linter/src/rules/pyflakes/snapshots/ruff_linter__rules__pyflakes__tests__F821_F821_5.pyi.snap
  crates/ruff_linter/src/rules/pyflakes/snapshots/ruff_linter__rules__pyflakes__tests__F822_F822_0.pyi.snap
Labels: bug

#10346 Wrap expressions in parentheses when negating
  crates/ruff_linter/resources/test/fixtures/flake8_comprehensions/C413.py
  crates/ruff_linter/src/cst/helpers.rs
  crates/ruff_linter/src/rules/flake8_comprehensions/snapshots/ruff_linter__rules__flake8_comprehensions__tests__C413_C413.py.snap
  crates/ruff_linter/src/rules/flake8_pytest_style/snapshots/ruff_linter__rules__flake8_pytest_style__tests__PT018.snap
Labels: bug

#10348 [`pylint`] Avoid false-positive slot non-assignment for `__dict__` (`PLE0237`)
  crates/ruff_linter/resources/test/fixtures/pylint/non_slot_assignment.py
  crates/ruff_linter/src/rules/pylint/rules/non_slot_assignment.rs
Labels: bug

#10316 [`flake8-bandit`]: Implement `S610` rule
  crates/ruff_linter/resources/test/fixtures/flake8_bandit/S610.py
  crates/ruff_linter/src/checkers/ast/analyze/expression.rs
  crates/ruff_linter/src/codes.rs
  crates/ruff_linter/src/rules/flake8_bandit/mod.rs
  crates/ruff_linter/src/rules/flake8_bandit/rules/django_extra.rs
  crates/ruff_linter/src/rules/flake8_bandit/rules/mod.rs
  crates/ruff_linter/src/rules/flake8_bandit/snapshots/ruff_linter__rules__flake8_bandit__tests__S610_S610.py.snap
  ruff.schema.json
Labels: rule, preview

#10292 [`pycodestyle`] Implement `redundant-backslash` (`E502`)
  crates/ruff_linter/resources/test/fixtures/pycodestyle/E502.py
  crates/ruff_linter/src/checkers/logical_lines.rs
  crates/ruff_linter/src/codes.rs
  crates/ruff_linter/src/linter.rs
  crates/ruff_linter/src/registry.rs
  crates/ruff_linter/src/rules/pycodestyle/mod.rs
  crates/ruff_linter/src/rules/pycodestyle/rules/logical_lines/mod.rs
  crates/ruff_linter/src/rules/pycodestyle/rules/logical_lines/redundant_backslash.rs
  crates/ruff_linter/src/rules/pycodestyle/snapshots/ruff_linter__rules__pycodestyle__tests__preview__E502_E502.py.snap
  crates/ruff_workspace/src/pyproject.rs
  ruff.schema.json
  scripts/check_docs_formatted.py
Labels: rule, preview

#10243 [`pycodestyle`] Implement `blank-line-at-end-of-file` (`W391`)
  .gitattributes
  crates/ruff_linter/resources/test/fixtures/pycodestyle/W391_0.py
  crates/ruff_linter/resources/test/fixtures/pycodestyle/W391_1.py
  crates/ruff_linter/resources/test/fixtures/pycodestyle/W391_2.py
  crates/ruff_linter/resources/test/fixtures/pycodestyle/W391_3.py
  crates/ruff_linter/resources/test/fixtures/pycodestyle/W391_4.py
  crates/ruff_linter/src/checkers/tokens.rs
  crates/ruff_linter/src/codes.rs
  crates/ruff_linter/src/registry.rs
  crates/ruff_linter/src/rules/pycodestyle/mod.rs
  crates/ruff_linter/src/rules/pycodestyle/rules/missing_newline_at_end_of_file.rs
  crates/ruff_linter/src/rules/pycodestyle/rules/mod.rs
  crates/ruff_linter/src/rules/pycodestyle/rules/too_many_newlines_at_end_of_file.rs
  crates/ruff_linter/src/rules/pycodestyle/snapshots/ruff_linter__rules__pycodestyle__tests__preview__W391_W391_0.py.snap
  crates/ruff_linter/src/rules/pycodestyle/snapshots/ruff_linter__rules__pycodestyle__tests__preview__W391_W391_1.py.snap
  crates/ruff_linter/src/rules/pycodestyle/snapshots/ruff_linter__rules__pycodestyle__tests__preview__W391_W391_2.py.snap
  crates/ruff_linter/src/rules/pycodestyle/snapshots/ruff_linter__rules__pycodestyle__tests__preview__W391_W391_3.py.snap
  crates/ruff_linter/src/rules/pycodestyle/snapshots/ruff_linter__rules__pycodestyle__tests__preview__W391_W391_4.py.snap
  ruff.schema.json
  scripts/check_docs_formatted.py
Labels: rule, preview

#10353 Fix typo in docs snippt -> snippet
  crates/ruff_workspace/src/options.rs
  ruff.schema.json
Labels: documentation

#10362 F821: Fix false negatives in `.py` files when `from __future__ import annotations` is active
  crates/ruff_linter/resources/test/fixtures/pyflakes/F821_27.py
  crates/ruff_linter/src/checkers/ast/mod.rs
  crates/ruff_linter/src/rules/pyflakes/snapshots/ruff_linter__rules__pyflakes__tests__F821_F821_27.py.snap
Labels: bug, linter

#10364 Add test case for `F401` in `__init__` files
  crates/ruff_linter/src/rules/pyflakes/mod.rs
  crates/ruff_linter/src/rules/pyflakes/snapshots/ruff_linter__rules__pyflakes__tests__init.snap
Labels: testing

#10371 Gate f-string struct size test for Rustc < 1.76
  crates/ruff_python_ast/src/nodes.rs
Labels: testing

#10370 Sort hash maps in `Settings` display
  crates/ruff/tests/snapshots/show_settings__display_default_settings.snap
  crates/ruff_linter/src/rules/flake8_import_conventions/mod.rs
  crates/ruff_linter/src/rules/flake8_import_conventions/rules/banned_import_alias.rs
  crates/ruff_linter/src/rules/flake8_import_conventions/settings.rs
  crates/ruff_linter/src/rules/flake8_tidy_imports/settings.rs
  crates/ruff_linter/src/rules/isort/mod.rs
  crates/ruff_linter/src/rules/isort/settings.rs
  crates/ruff_linter/src/rules/pydocstyle/settings.rs
  crates/ruff_linter/src/rules/pylint/settings.rs
  crates/ruff_linter/src/settings/mod.rs
  crates/ruff_workspace/src/options.rs
  ruff.schema.json
Labels: bug

#10376 Avoid `TRIO115` if the argument is a variable
  crates/ruff_linter/resources/test/fixtures/flake8_trio/TRIO115.py
  crates/ruff_linter/src/rules/flake8_trio/rules/zero_sleep_call.rs
  crates/ruff_linter/src/rules/flake8_trio/snapshots/ruff_linter__rules__flake8_trio__tests__TRIO115_TRIO115.py.snap
Labels: bug

#10309 Add methods to iter over f-string elements
  crates/ruff_linter/src/rules/ruff/rules/missing_fstring_syntax.rs
  crates/ruff_linter/src/rules/tryceratops/rules/raise_vanilla_args.rs
  crates/ruff_python_ast/src/nodes.rs
  crates/ruff_python_formatter/src/other/f_string.rs
Labels: internal

#10377 [`pylint`] Implement `invalid-bool-return-type` (`E304`)
  crates/ruff_linter/resources/test/fixtures/pylint/invalid_return_type_bool.py
  crates/ruff_linter/src/checkers/ast/analyze/statement.rs
  crates/ruff_linter/src/codes.rs
  crates/ruff_linter/src/rules/pylint/mod.rs
  crates/ruff_linter/src/rules/pylint/rules/invalid_bool_return.rs
  crates/ruff_linter/src/rules/pylint/rules/mod.rs
  crates/ruff_linter/src/rules/pylint/snapshots/ruff_linter__rules__pylint__tests__PLE0304_invalid_return_type_bool.py.snap
  ruff.schema.json
Labels: rule

#10217 `docs`: remove `.` from check and format commands
  README.md
  docs/formatter.md
  docs/installation.md
  docs/linter.md
  docs/tutorial.md
Labels: documentation

#10387 Avoid removing shadowed imports that point to different symbols
  crates/ruff_linter/resources/test/fixtures/pyflakes/F811_28.py
  crates/ruff_linter/src/checkers/ast/analyze/deferred_scopes.rs
  crates/ruff_linter/src/rules/pyflakes/mod.rs
  crates/ruff_linter/src/rules/pyflakes/snapshots/ruff_linter__rules__pyflakes__tests__F811_F811_1.py.snap
  crates/ruff_linter/src/rules/pyflakes/snapshots/ruff_linter__rules__pyflakes__tests__F811_F811_12.py.snap
  crates/ruff_linter/src/rules/pyflakes/snapshots/ruff_linter__rules__pyflakes__tests__F811_F811_2.py.snap
  crates/ruff_linter/src/rules/pyflakes/snapshots/ruff_linter__rules__pyflakes__tests__F811_F811_23.py.snap
  crates/ruff_linter/src/rules/pyflakes/snapshots/ruff_linter__rules__pyflakes__tests__F811_F811_28.py.snap
Labels: bug

#10383 Unify enums used for internal representation of quoting style
  Cargo.lock
  crates/ruff_linter/src/checkers/ast/mod.rs
  crates/ruff_linter/src/rules/flake8_quotes/settings.rs
  crates/ruff_linter/src/rules/pydocstyle/rules/triple_quotes.rs
  crates/ruff_python_ast/src/nodes.rs
  crates/ruff_python_ast/src/str.rs
  crates/ruff_python_codegen/src/generator.rs
  crates/ruff_python_codegen/src/lib.rs
  crates/ruff_python_codegen/src/stylist.rs
  crates/ruff_python_formatter/src/context.rs
  crates/ruff_python_formatter/src/string/docstring.rs
  crates/ruff_python_formatter/src/string/mod.rs
  crates/ruff_python_formatter/src/string/normalize.rs
  crates/ruff_python_literal/Cargo.toml
  crates/ruff_python_literal/src/escape.rs
  crates/ruff_python_parser/src/string_token_flags.rs
Labels: internal

#10365 Remove `F401` fix for `__init__` imports by default and allow opt-in to unsafe fix
  crates/ruff/tests/snapshots/integration_test__rule_f401.snap
  crates/ruff/tests/snapshots/show_settings__display_default_settings.snap
  crates/ruff_linter/src/rules/pyflakes/mod.rs
  crates/ruff_linter/src/rules/pyflakes/rules/unused_import.rs
  crates/ruff_linter/src/rules/pyflakes/snapshots/ruff_linter__rules__pyflakes__tests__init.snap
  crates/ruff_linter/src/rules/pyflakes/snapshots/ruff_linter__rules__pyflakes__tests__init_unused_import_opt_in_to_fix.snap
  crates/ruff_linter/src/settings/mod.rs
  crates/ruff_workspace/src/configuration.rs
  crates/ruff_workspace/src/options.rs
  ruff.schema.json
Labels: rule

#10393 Use ruff.toml format in README
  README.md
Labels: documentation

#8631 Indicated Successful Check
  crates/ruff/src/printer.rs
  crates/ruff/tests/integration_test.rs
  crates/ruff/tests/lint.rs
Labels: cli

#10394 [`pylint`] Include builtin warnings in useless-exception-statement (`PLW0133`)
  crates/ruff_linter/resources/test/fixtures/pylint/useless_exception_statement.py
  crates/ruff_linter/src/rules/pylint/rules/useless_exception_statement.rs
  crates/ruff_linter/src/rules/pylint/snapshots/ruff_linter__rules__pylint__tests__PLW0133_useless_exception_statement.py.snap
  crates/ruff_linter/src/rules/tryceratops/rules/type_check_without_type_error.rs
  crates/ruff_python_stdlib/src/builtins.rs
Labels: rule

#10372 Remove f-string `UnclosedLbrace` error checking from the lexer
  crates/ruff_python_parser/resources/invalid/expressions/unclosed_fstring_lbrace.py
  crates/ruff_python_parser/src/lexer.rs
  crates/ruff_python_parser/tests/snapshots/invalid_syntax@expressions__unclosed_fstring_lbrace.py.snap
Labels: parser

#10385 Use string flags to mark it as invalid
  crates/ruff_python_ast/src/nodes.rs
  crates/ruff_python_parser/src/parser/expression.rs
  crates/ruff_python_parser/src/string.rs
Labels: parser

#10386 Remove `Expr::Invalid`
  crates/ruff_linter/src/checkers/ast/analyze/expression.rs
  crates/ruff_linter/src/checkers/ast/mod.rs
  crates/ruff_linter/src/rules/flake8_bugbear/rules/function_uses_loop_variable.rs
  crates/ruff_linter/src/rules/pyupgrade/rules/use_pep604_annotation.rs
  crates/ruff_linter/src/rules/refurb/rules/bit_count.rs
  crates/ruff_linter/src/rules/ruff/rules/invalid_formatter_suppression_comment.rs
  crates/ruff_python_ast/src/comparable.rs
  crates/ruff_python_ast/src/expression.rs
  crates/ruff_python_ast/src/helpers.rs
  crates/ruff_python_ast/src/node.rs
  crates/ruff_python_ast/src/nodes.rs
  crates/ruff_python_ast/src/relocate.rs
  crates/ruff_python_ast/src/visitor.rs
  crates/ruff_python_ast/src/visitor/preorder.rs
  crates/ruff_python_ast/src/visitor/transformer.rs
  crates/ruff_python_codegen/src/generator.rs
  crates/ruff_python_formatter/src/expression/expr_invalid.rs
  crates/ruff_python_formatter/src/expression/mod.rs
  crates/ruff_python_formatter/src/generated.rs
  crates/ruff_python_formatter/src/range.rs
  crates/ruff_python_parser/src/lalrpop/invalid.rs
  crates/ruff_python_parser/src/parser/expression.rs
  crates/ruff_python_parser/src/parser/pattern.rs
  crates/ruff_python_parser/src/parser/statement.rs
  crates/ruff_python_parser/src/parser/tests/parser.rs
  crates/ruff_python_parser/src/parser/tests/snapshots/ruff_python_parser__parser__tests__parser__tests__parse_match_stmt.snap
  crates/ruff_python_parser/tests/snapshots/invalid_syntax@expressions__emoji_identifiers.py.snap
  crates/ruff_python_parser/tests/snapshots/invalid_syntax@expressions__unclosed_fstring_lbrace.py.snap
  crates/ruff_python_parser/tests/snapshots/invalid_syntax@statements__assignment_missing_target.py.snap
  crates/ruff_python_parser/tests/snapshots/invalid_syntax@statements__assignment_missing_value.py.snap
  crates/ruff_python_parser/tests/snapshots/invalid_syntax@statements__if_elif.py.snap
  crates/ruff_python_semantic/src/analyze/type_inference.rs
Labels: parser

#10400 [`pylint`] Extend docs and test in `invalid-str-return-type` (`E307`)
  crates/ruff_linter/resources/test/fixtures/pylint/invalid_return_type_str.py
  crates/ruff_linter/src/rules/pylint/rules/invalid_str_return.rs
  crates/ruff_linter/src/rules/pylint/snapshots/ruff_linter__rules__pylint__tests__PLE0307_invalid_return_type_str.py.snap
Labels: documentation

#10311 Use `ExprFString` for `StringLike::FString` variant
  crates/ruff_linter/resources/test/fixtures/flake8_bandit/S104.py
  crates/ruff_linter/resources/test/fixtures/flake8_bandit/S108.py
  crates/ruff_linter/resources/test/fixtures/flake8_pyi/PYI053.pyi
  crates/ruff_linter/resources/test/fixtures/ruff/confusables.py
  crates/ruff_linter/src/checkers/ast/mod.rs
  crates/ruff_linter/src/rules/flake8_bandit/rules/hardcoded_bind_all_interfaces.rs
  crates/ruff_linter/src/rules/flake8_bandit/rules/hardcoded_tmp_directory.rs
  crates/ruff_linter/src/rules/flake8_bandit/snapshots/ruff_linter__rules__flake8_bandit__tests__S104_S104.py.snap
  crates/ruff_linter/src/rules/flake8_bandit/snapshots/ruff_linter__rules__flake8_bandit__tests__S108_S108.py.snap
  crates/ruff_linter/src/rules/flake8_bandit/snapshots/ruff_linter__rules__flake8_bandit__tests__S108_extend.snap
  crates/ruff_linter/src/rules/flake8_pyi/rules/string_or_bytes_too_long.rs
  crates/ruff_linter/src/rules/flake8_pyi/snapshots/ruff_linter__rules__flake8_pyi__tests__PYI053_PYI053.pyi.snap
  crates/ruff_linter/src/rules/ruff/rules/ambiguous_unicode_character.rs
  crates/ruff_linter/src/rules/ruff/snapshots/ruff_linter__rules__ruff__tests__confusables.snap
  crates/ruff_linter/src/rules/ruff/snapshots/ruff_linter__rules__ruff__tests__preview_confusables.snap
  crates/ruff_python_ast/src/expression.rs
Labels: internal

#10382 [`pycodestyle`] Do not ignore lines before the first logical line in blank lines rules.
  crates/ruff_linter/resources/test/fixtures/pycodestyle/E302_first_line_docstring.py
  crates/ruff_linter/resources/test/fixtures/pycodestyle/E302_first_line_expression.py
  crates/ruff_linter/resources/test/fixtures/pycodestyle/E302_first_line_function.py
  crates/ruff_linter/resources/test/fixtures/pycodestyle/E302_first_line_statement.py
  crates/ruff_linter/resources/test/fixtures/pycodestyle/E303_first_line_comment.py
  crates/ruff_linter/resources/test/fixtures/pycodestyle/E303_first_line_docstring.py
  crates/ruff_linter/resources/test/fixtures/pycodestyle/E303_first_line_expression.py
  crates/ruff_linter/resources/test/fixtures/pycodestyle/E303_first_line_statement.py
  crates/ruff_linter/src/rules/pycodestyle/mod.rs
  crates/ruff_linter/src/rules/pycodestyle/rules/blank_lines.rs
  crates/ruff_linter/src/rules/pycodestyle/snapshots/ruff_linter__rules__pycodestyle__tests__E302_E302_first_line_docstring.py.snap
  crates/ruff_linter/src/rules/pycodestyle/snapshots/ruff_linter__rules__pycodestyle__tests__E302_E302_first_line_expression.py.snap
  crates/ruff_linter/src/rules/pycodestyle/snapshots/ruff_linter__rules__pycodestyle__tests__E302_E302_first_line_function.py.snap
  crates/ruff_linter/src/rules/pycodestyle/snapshots/ruff_linter__rules__pycodestyle__tests__E302_E302_first_line_statement.py.snap
  crates/ruff_linter/src/rules/pycodestyle/snapshots/ruff_linter__rules__pycodestyle__tests__E303_E303_first_line_comment.py.snap
  crates/ruff_linter/src/rules/pycodestyle/snapshots/ruff_linter__rules__pycodestyle__tests__E303_E303_first_line_docstring.py.snap
  crates/ruff_linter/src/rules/pycodestyle/snapshots/ruff_linter__rules__pycodestyle__tests__E303_E303_first_line_expression.py.snap
  crates/ruff_linter/src/rules/pycodestyle/snapshots/ruff_linter__rules__pycodestyle__tests__E303_E303_first_line_statement.py.snap
Labels: bug

#10395 [RUF008] Make it clearer that a mutable default in a dataclass is only valid if it is typed as a ClassVar
  crates/ruff_linter/src/rules/ruff/rules/mutable_dataclass_default.rs
Labels: documentation

#10415 Track conditional deletions in the semantic model
  crates/ruff_linter/resources/test/fixtures/pylint/global_variable_not_assigned.py
  crates/ruff_linter/src/checkers/ast/analyze/deferred_scopes.rs
  crates/ruff_linter/src/checkers/ast/mod.rs
  crates/ruff_linter/src/renamer.rs
  crates/ruff_linter/src/rules/flake8_type_checking/rules/runtime_import_in_type_checking_block.rs
  crates/ruff_linter/src/rules/flake8_type_checking/rules/typing_only_runtime_import.rs
  crates/ruff_linter/src/rules/pylint/rules/non_ascii_name.rs
  crates/ruff_python_semantic/src/binding.rs
  crates/ruff_python_semantic/src/model.rs
  crates/ruff_python_semantic/src/reference.rs
Labels: bug

#10413 Allow trailing ellipsis in `typing.TYPE_CHECKING`
  crates/ruff_linter/resources/test/fixtures/flake8_pie/PIE790.py
  crates/ruff_linter/src/rules/flake8_pie/rules/unnecessary_placeholder.rs
Labels: bug

#10419 [`flake8_comprehensions`] Handled special case for `C400` which also matches `C416`
  crates/ruff_linter/resources/test/fixtures/flake8_comprehensions/C400.py
  crates/ruff_linter/src/rules/flake8_comprehensions/rules/unnecessary_generator_list.rs
  crates/ruff_linter/src/rules/flake8_comprehensions/snapshots/ruff_linter__rules__flake8_comprehensions__tests__C400_C400.py.snap
Labels: rule

#10425 Bump version to 0.3.3
  CHANGELOG.md
  Cargo.lock
  README.md
  crates/ruff/Cargo.toml
  crates/ruff_linter/Cargo.toml
  crates/ruff_shrinking/Cargo.toml
  docs/integrations.md
  pyproject.toml
  scripts/benchmarks/pyproject.toml
Labels: internal

#10435 Add `repos/` to the gitignore
  .gitignore
Labels: internal

#10428 [`pylint`] Implement `singledispatchmethod-function` (`PLE5120`)
  crates/ruff_linter/resources/test/fixtures/pylint/singledispatchmethod_function.py
  crates/ruff_linter/src/checkers/ast/analyze/deferred_scopes.rs
  crates/ruff_linter/src/codes.rs
  crates/ruff_linter/src/rules/pylint/mod.rs
  crates/ruff_linter/src/rules/pylint/rules/mod.rs
  crates/ruff_linter/src/rules/pylint/rules/singledispatchmethod_function.rs
  crates/ruff_linter/src/rules/pylint/snapshots/ruff_linter__rules__pylint__tests__PLE1520_singledispatchmethod_function.py.snap
  ruff.schema.json
Labels: rule, preview

#10437 [`flake8-bugbear`] Allow tuples of exceptions (`B030`)
  crates/ruff_linter/resources/test/fixtures/flake8_bugbear/B030.py
  crates/ruff_linter/src/rules/flake8_bugbear/rules/except_with_non_exception_classes.rs
  crates/ruff_linter/src/rules/flake8_bugbear/snapshots/ruff_linter__rules__flake8_bugbear__tests__B030_B030.py.snap
Labels: bug

#10407 [`pylint`] Implement `nonlocal-and-global` (`E115`)
  crates/ruff_linter/resources/test/fixtures/pylint/nonlocal_and_global.py
  crates/ruff_linter/src/checkers/ast/analyze/statement.rs
  crates/ruff_linter/src/codes.rs
  crates/ruff_linter/src/rules/pylint/mod.rs
  crates/ruff_linter/src/rules/pylint/rules/mod.rs
  crates/ruff_linter/src/rules/pylint/rules/nonlocal_and_global.rs
  crates/ruff_linter/src/rules/pylint/snapshots/ruff_linter__rules__pylint__tests__PLE0115_nonlocal_and_global.py.snap
  ruff.schema.json
Labels: rule, preview

#10441 Fix pylint upstream categories not showing in docs
  crates/ruff_dev/src/generate_rules_table.rs
  crates/ruff_linter/src/upstream_categories.rs
Labels: bug

#10412 Apply NFKC normalization to unicode identifiers in the lexer
  Cargo.lock
  Cargo.toml
  crates/ruff_linter/resources/test/fixtures/pyflakes/F821_28.py
  crates/ruff_linter/src/rules/pyflakes/mod.rs
  crates/ruff_linter/src/rules/pyflakes/snapshots/ruff_linter__rules__pyflakes__tests__F821_F821_28.py.snap
  crates/ruff_python_formatter/src/expression/expr_name.rs
  crates/ruff_python_parser/Cargo.toml
  crates/ruff_python_parser/src/lexer.rs
  crates/ruff_python_parser/src/token.rs
Labels: parser

#10460 Add Nokia to "Who's Using Ruff?"
  README.md
Labels: documentation

#10398 `ruff server` default to current working directory in environments without any root directories or workspaces
  crates/ruff_server/src/server.rs
Labels: server

#10452 Remove long `Iterator::chain` sequence in `RuleCodePrefix::iter`
  crates/ruff_macros/src/map_codes.rs
Labels: internal

#10422 Spruce up docs for flake8-pyi rules
  crates/ruff_linter/src/rules/flake8_pyi/rules/any_eq_ne_annotation.rs
  crates/ruff_linter/src/rules/flake8_pyi/rules/collections_named_tuple.rs
  crates/ruff_linter/src/rules/flake8_pyi/rules/complex_assignment_in_stub.rs
  crates/ruff_linter/src/rules/flake8_pyi/rules/complex_if_statement_in_stub.rs
  crates/ruff_linter/src/rules/flake8_pyi/rules/exit_annotations.rs
  crates/ruff_linter/src/rules/flake8_pyi/rules/future_annotations_in_stub.rs
  crates/ruff_linter/src/rules/flake8_pyi/rules/iter_method_return_iterable.rs
  crates/ruff_linter/src/rules/flake8_pyi/rules/no_return_argument_annotation.rs
  crates/ruff_linter/src/rules/flake8_pyi/rules/non_empty_stub_body.rs
  crates/ruff_linter/src/rules/flake8_pyi/rules/non_self_return_type.rs
  crates/ruff_linter/src/rules/flake8_pyi/rules/numeric_literal_too_long.rs
  crates/ruff_linter/src/rules/flake8_pyi/rules/pass_in_class_body.rs
  crates/ruff_linter/src/rules/flake8_pyi/rules/pass_statement_stub_body.rs
  crates/ruff_linter/src/rules/flake8_pyi/rules/prefix_type_params.rs
  crates/ruff_linter/src/rules/flake8_pyi/rules/quoted_annotation_in_stub.rs
  crates/ruff_linter/src/rules/flake8_pyi/rules/redundant_literal_union.rs
  crates/ruff_linter/src/rules/flake8_pyi/rules/redundant_numeric_union.rs
Labels: documentation

#10461 [`flake8-pytest-style`] Add automatic fix for `pytest-parametrize-values-wrong-type` (`PT007`)
  crates/ruff_linter/resources/test/fixtures/flake8_pytest_style/PT007.py
  crates/ruff_linter/src/rules/flake8_pytest_style/rules/parametrize.rs
  crates/ruff_linter/src/rules/flake8_pytest_style/snapshots/ruff_linter__rules__flake8_pytest_style__tests__PT007_list_of_lists.snap
  crates/ruff_linter/src/rules/flake8_pytest_style/snapshots/ruff_linter__rules__flake8_pytest_style__tests__PT007_list_of_tuples.snap
  crates/ruff_linter/src/rules/flake8_pytest_style/snapshots/ruff_linter__rules__flake8_pytest_style__tests__PT007_tuple_of_lists.snap
  crates/ruff_linter/src/rules/flake8_pytest_style/snapshots/ruff_linter__rules__flake8_pytest_style__tests__PT007_tuple_of_tuples.snap
Labels: fixes

#10399 `ruff server` sets worker thread pool size based on the user's available cores
  Cargo.lock
  Cargo.toml
  crates/ruff/Cargo.toml
  crates/ruff/src/args.rs
  crates/ruff/src/commands/server.rs
  crates/ruff/src/lib.rs
  crates/ruff_server/src/server.rs
  crates/ruff_server/src/server/schedule.rs
  crates/ruff_server/src/server/schedule/thread/pool.rs
Labels: server

#10464 Avoid code comment detection in PEP 723 script tags
  crates/ruff_linter/resources/test/fixtures/eradicate/ERA001.py
  crates/ruff_linter/src/rules/eradicate/rules/commented_out_code.rs
  crates/ruff_linter/src/rules/eradicate/snapshots/ruff_linter__rules__eradicate__tests__ERA001_ERA001.py.snap
Labels: bug

#10467 Clarify `extend-select` documentation
  crates/ruff_workspace/src/options.rs
Labels: documentation

#10406 Fix string parsing error ranges
  crates/ruff_python_parser/src/snapshots/ruff_python_parser__string__tests__invalid_byte_literal_error.snap
  crates/ruff_python_parser/src/snapshots/ruff_python_parser__string__tests__invalid_unicode_literal.snap
  crates/ruff_python_parser/src/snapshots/ruff_python_parser__string__tests__invalid_unicode_name_error.snap
  crates/ruff_python_parser/src/snapshots/ruff_python_parser__string__tests__missing_unicode_lbrace_error.snap
  crates/ruff_python_parser/src/snapshots/ruff_python_parser__string__tests__missing_unicode_rbrace_error.snap
  crates/ruff_python_parser/src/string.rs
Labels: parser

#10475 Remove unused dependencies
  Cargo.lock
  Cargo.toml
  crates/ruff/Cargo.toml
  crates/ruff_dev/Cargo.toml
  crates/ruff_formatter/Cargo.toml
  crates/ruff_linter/Cargo.toml
  crates/ruff_notebook/Cargo.toml
  crates/ruff_python_literal/Cargo.toml
  crates/ruff_python_trivia/Cargo.toml
  crates/ruff_server/Cargo.toml
  crates/ruff_source_file/Cargo.toml
  crates/ruff_workspace/Cargo.toml
Labels: internal

#10474 Remove unreachable error case while f-string parsing
  crates/ruff_python_parser/src/string.rs
Labels: parser

#10478 Avoid failures due to non-deterministic binding ordering
  crates/ruff_linter/resources/test/fixtures/flake8_logging/LOG009.py
  crates/ruff_linter/resources/test/fixtures/pyupgrade/UP017.py
  crates/ruff_linter/resources/test/fixtures/refurb/FURB163.py
  crates/ruff_linter/resources/test/fixtures/ruff/RUF013_0.py
  crates/ruff_linter/resources/test/fixtures/ruff/RUF013_1.py
  crates/ruff_linter/resources/test/fixtures/ruff/RUF013_3.py
  crates/ruff_linter/resources/test/fixtures/tryceratops/TRY400.py
  crates/ruff_linter/src/rules/flake8_logging/snapshots/ruff_linter__rules__flake8_logging__tests__LOG009_LOG009.py.snap
  crates/ruff_linter/src/rules/pyupgrade/snapshots/ruff_linter__rules__pyupgrade__tests__datetime_utc_alias_py311.snap
  crates/ruff_linter/src/rules/refurb/snapshots/ruff_linter__rules__refurb__tests__FURB163_FURB163.py.snap
  crates/ruff_linter/src/rules/ruff/mod.rs
  crates/ruff_linter/src/rules/ruff/snapshots/ruff_linter__rules__ruff__tests__PY39_RUF013_RUF013_0.py.snap
  crates/ruff_linter/src/rules/ruff/snapshots/ruff_linter__rules__ruff__tests__PY39_RUF013_RUF013_1.py.snap
  crates/ruff_linter/src/rules/ruff/snapshots/ruff_linter__rules__ruff__tests__RUF013_RUF013_0.py.snap
  crates/ruff_linter/src/rules/ruff/snapshots/ruff_linter__rules__ruff__tests__RUF013_RUF013_1.py.snap
  crates/ruff_linter/src/rules/ruff/snapshots/ruff_linter__rules__ruff__tests__RUF013_RUF013_3.py.snap
  crates/ruff_linter/src/rules/tryceratops/snapshots/ruff_linter__rules__tryceratops__tests__error-instead-of-exception_TRY400.py.snap
Labels: testing

#10481 Allow SPDX license headers to exceed the line length
  crates/ruff_linter/resources/test/fixtures/pycodestyle/E501.py
  crates/ruff_linter/src/rules/pycodestyle/overlong.rs
  crates/ruff_linter/src/rules/pycodestyle/rules/line_too_long.rs
Labels: rule

#10486 Use `TokenId` to track parser progress
  crates/ruff_python_parser/src/parser/mod.rs
  crates/ruff_python_parser/src/parser/progress.rs
Labels: parser

#10488 Fix error message for rule C400
  crates/ruff_linter/src/rules/flake8_comprehensions/rules/unnecessary_generator_list.rs
  crates/ruff_linter/src/rules/flake8_comprehensions/snapshots/ruff_linter__rules__flake8_comprehensions__tests__C400_C400.py.snap
Labels: documentation

#10489 Simplify formatting of strings by using flags from the AST nodes
  Cargo.lock
  crates/ruff_linter/src/rules/pylint/rules/bad_string_format_character.rs
  crates/ruff_linter/src/rules/pylint/rules/bad_string_format_type.rs
  crates/ruff_linter/src/rules/pyupgrade/rules/printf_string_formatting.rs
  crates/ruff_python_ast/src/nodes.rs
  crates/ruff_python_formatter/Cargo.toml
  crates/ruff_python_formatter/src/other/bytes_literal.rs
  crates/ruff_python_formatter/src/other/f_string.rs
  crates/ruff_python_formatter/src/other/f_string_element.rs
  crates/ruff_python_formatter/src/other/string_literal.rs
  crates/ruff_python_formatter/src/string/any.rs
  crates/ruff_python_formatter/src/string/docstring.rs
  crates/ruff_python_formatter/src/string/mod.rs
  crates/ruff_python_formatter/src/string/normalize.rs
  crates/ruff_python_parser/src/lexer.rs
  crates/ruff_python_parser/src/lexer/fstring.rs
  crates/ruff_python_parser/src/lib.rs
  crates/ruff_python_parser/src/python.lalrpop
  crates/ruff_python_parser/src/python.rs
  crates/ruff_python_parser/src/string.rs
  crates/ruff_python_parser/src/string_token_flags.rs
  crates/ruff_python_parser/src/token.rs
Labels: internal, formatter

#10490 Error recovery for unparenthesized gen expr in with item
  crates/ruff_python_parser/src/parser/expression.rs
  crates/ruff_python_parser/src/parser/statement.rs
  crates/ruff_python_parser/tests/snapshots/invalid_syntax@statements__with__ambiguous_lpar_with_items.py.snap
Labels: parser

#10418 Update with item parsing to avoid infinite lookaheads
  crates/ruff_python_parser/resources/invalid/statements/with/ambiguous_lpar_with_items.py
  crates/ruff_python_parser/resources/invalid/statements/with/empty_with_items.py
  crates/ruff_python_parser/resources/invalid/statements/with/unclosed_ambiguous_lpar.py
  crates/ruff_python_parser/resources/invalid/statements/with/unclosed_ambiguous_lpar_eof.py
  crates/ruff_python_parser/resources/valid/statement/ambiguous_lpar_with_items.py
  crates/ruff_python_parser/src/parser/expression.rs
  crates/ruff_python_parser/src/parser/mod.rs
  crates/ruff_python_parser/src/parser/statement.rs
  crates/ruff_python_parser/src/parser/tests/snapshots/ruff_python_parser__parser__tests__parser__tests__parse_with_stmt.snap
  crates/ruff_python_parser/tests/snapshots/invalid_syntax@statements__with__ambiguous_lpar_with_items.py.snap
  crates/ruff_python_parser/tests/snapshots/invalid_syntax@statements__with__empty_with_items.py.snap
  crates/ruff_python_parser/tests/snapshots/invalid_syntax@statements__with__unclosed_ambiguous_lpar.py.snap
  crates/ruff_python_parser/tests/snapshots/invalid_syntax@statements__with__unclosed_ambiguous_lpar_eof.py.snap
  crates/ruff_python_parser/tests/snapshots/valid_syntax@statement__ambiguous_lpar_with_items.py.snap
Labels: parser

#10492 Fix instable formatting for trailing subscribt end-of-line comment
  crates/ruff_python_formatter/resources/test/fixtures/ruff/expression/subscript.py
  crates/ruff_python_formatter/src/comments/placement.rs
  crates/ruff_python_formatter/tests/snapshots/format@expression__subscript.py.snap
Labels: bug, formatter

#10443 Remove `peek_nth`, only allow 1 lookahead
  crates/ruff_python_parser/src/parser/expression.rs
  crates/ruff_python_parser/src/parser/mod.rs
  crates/ruff_python_parser/src/parser/pattern.rs
  crates/ruff_python_parser/src/parser/statement.rs
  crates/ruff_python_parser/src/token_source.rs
Labels: parser

#10496 Fix subscript comment placement with parenthesized value
  crates/ruff_python_formatter/resources/test/fixtures/ruff/expression/subscript.py
  crates/ruff_python_formatter/src/comments/placement.rs
  crates/ruff_python_formatter/tests/snapshots/format@expression__subscript.py.snap
Labels: internal, formatter

#10491 Avoid incorrect tuple transformation in single-element case (`C409`)
  crates/ruff_linter/resources/test/fixtures/flake8_comprehensions/C409.py
  crates/ruff_linter/src/rules/flake8_comprehensions/rules/unnecessary_literal_within_tuple_call.rs
  crates/ruff_linter/src/rules/flake8_comprehensions/snapshots/ruff_linter__rules__flake8_comprehensions__tests__C409_C409.py.snap
Labels: bug

#10401 [`pylint`] Implement `nan-comparison` (`PLW0117`)
  crates/ruff_linter/resources/test/fixtures/pylint/nan_comparison.py
  crates/ruff_linter/src/checkers/ast/analyze/expression.rs
  crates/ruff_linter/src/codes.rs
  crates/ruff_linter/src/rules/pylint/mod.rs
  crates/ruff_linter/src/rules/pylint/rules/mod.rs
  crates/ruff_linter/src/rules/pylint/rules/nan_comparison.rs
  crates/ruff_linter/src/rules/pylint/snapshots/ruff_linter__rules__pylint__tests__PLW0117_nan_comparison.py.snap
  ruff.schema.json
Labels: rule, preview

#10484 Add a formatting step using `mdformat` as part of `generate_mkdocs.py`
  docs/requirements-insiders.txt
  docs/requirements.txt
  scripts/_mdformat_utils.py
  scripts/generate_mkdocs.py
Labels: documentation

#10498 Add missing `Options` references to blank line docs
  crates/ruff_linter/src/rules/pycodestyle/rules/blank_lines.rs
Labels: documentation

#10500 Update number of implemented rules to "over 800"
  README.md
  docs/faq.md
  docs/tutorial.md
Labels: documentation

#10502 chore: remove repetitive words
  crates/ruff_dev/src/format_dev.rs
  crates/ruff_python_formatter/src/context.rs
  crates/ruff_python_parser/src/parser.rs
  crates/ruff_workspace/src/resolver.rs
Labels: internal

#10469 Fix `E231` bug: Inconsistent catch compared to pycodestyle, such as when dict nested in list
  crates/ruff_linter/resources/test/fixtures/pycodestyle/E23.py
  crates/ruff_linter/src/rules/pycodestyle/rules/logical_lines/missing_whitespace.rs
  crates/ruff_linter/src/rules/pycodestyle/snapshots/ruff_linter__rules__pycodestyle__tests__E231_E23.py.snap
Labels: bug

#10494 Spruce up docs for flake8-pyi rules (part 2)
  crates/ruff_linter/src/rules/flake8_pyi/rules/simple_defaults.rs
  crates/ruff_linter/src/rules/flake8_pyi/rules/string_or_bytes_too_long.rs
  crates/ruff_linter/src/rules/flake8_pyi/rules/type_alias_naming.rs
  crates/ruff_linter/src/rules/flake8_pyi/rules/unnecessary_literal_union.rs
  crates/ruff_linter/src/rules/flake8_pyi/rules/unnecessary_type_union.rs
  crates/ruff_linter/src/rules/flake8_pyi/rules/unrecognized_platform.rs
  crates/ruff_linter/src/rules/flake8_pyi/rules/unrecognized_version_info.rs
  crates/ruff_linter/src/rules/flake8_pyi/rules/unsupported_method_call_on_all.rs
  crates/ruff_linter/src/rules/flake8_pyi/rules/unused_private_type_definition.rs
Labels: documentation

#10510 Update Rust to v1.77
  crates/ruff/src/commands/check.rs
  crates/ruff/src/panic.rs
  crates/ruff/tests/integration_test.rs
  crates/ruff_linter/src/checkers/imports.rs
  crates/ruff_linter/src/fix/edits.rs
  crates/ruff_linter/src/importer/insertion.rs
  crates/ruff_linter/src/rules/flake8_bandit/rules/hardcoded_password_string.rs
  crates/ruff_linter/src/rules/flake8_django/rules/unordered_body_content_in_model.rs
  crates/ruff_linter/src/rules/flake8_import_conventions/rules/unconventional_import_alias.rs
  crates/ruff_linter/src/rules/flake8_pyi/rules/redundant_literal_union.rs
  crates/ruff_linter/src/rules/flake8_pytest_style/rules/helpers.rs
  crates/ruff_linter/src/rules/flake8_simplify/rules/ast_bool_op.rs
  crates/ruff_linter/src/rules/flake8_simplify/rules/reimplemented_builtin.rs
  crates/ruff_linter/src/rules/flake8_tidy_imports/rules/relative_imports.rs
  crates/ruff_linter/src/rules/isort/categorize.rs
  crates/ruff_linter/src/rules/isort/sorting.rs
  crates/ruff_linter/src/rules/pycodestyle/rules/doc_line_too_long.rs
  crates/ruff_linter/src/rules/pylint/rules/import_self.rs
  crates/ruff_linter/src/rules/pyupgrade/rules/f_strings.rs
  crates/ruff_linter/src/rules/pyupgrade/rules/printf_string_formatting.rs
  crates/ruff_linter/src/rules/ruff/rules/invalid_formatter_suppression_comment.rs
  crates/ruff_linter/src/rules/ruff/rules/pairwise_over_zipped.rs
  crates/ruff_linter/src/test.rs
  crates/ruff_python_ast/src/helpers.rs
  crates/ruff_python_formatter/src/pattern/pattern_match_mapping.rs
  rust-toolchain.toml
Labels: internal

#10499 Docs: Link inline settings when not part of options section
  crates/ruff_dev/src/generate_docs.rs
Labels: bug, documentation

#10212 [`refurb`] Implement `list_assign_reversed` lint (FURB187)
  crates/ruff_linter/resources/test/fixtures/refurb/FURB187.py
  crates/ruff_linter/src/checkers/ast/analyze/statement.rs
  crates/ruff_linter/src/codes.rs
  crates/ruff_linter/src/rules/refurb/mod.rs
  crates/ruff_linter/src/rules/refurb/rules/list_assign_reversed.rs
  crates/ruff_linter/src/rules/refurb/rules/mod.rs
  crates/ruff_linter/src/rules/refurb/snapshots/ruff_linter__rules__refurb__tests__FURB187_FURB187.py.snap
  ruff.schema.json
Labels: rule

#10514 Rename `list-reassign-reversed` to `list-reverse-copy`
  crates/ruff_linter/src/checkers/ast/analyze/statement.rs
  crates/ruff_linter/src/codes.rs
  crates/ruff_linter/src/rules/refurb/mod.rs
  crates/ruff_linter/src/rules/refurb/rules/list_reverse_copy.rs
  crates/ruff_linter/src/rules/refurb/rules/mod.rs
Labels: rule

#10515 Bump version to v0.3.4
  CHANGELOG.md
  Cargo.lock
  README.md
  crates/ruff/Cargo.toml
  crates/ruff_linter/Cargo.toml
  crates/ruff_shrinking/Cargo.toml
  docs/integrations.md
  pyproject.toml
  scripts/benchmarks/pyproject.toml
Labels: release

#10404 Automatic configuration reloading for `ruff server`
  crates/ruff_server/src/server.rs
  crates/ruff_server/src/server/api.rs
  crates/ruff_server/src/server/api/notifications.rs
  crates/ruff_server/src/server/api/notifications/did_change_watched_files.rs
  crates/ruff_server/src/session.rs
Labels: server

#10518 Improve error message, recover from unary add
  crates/ruff_python_parser/resources/invalid/statements/match/unary_add_usage.py
  crates/ruff_python_parser/src/error.rs
  crates/ruff_python_parser/src/parser/expression.rs
  crates/ruff_python_parser/src/parser/mod.rs
  crates/ruff_python_parser/src/parser/pattern.rs
  crates/ruff_python_parser/tests/snapshots/invalid_syntax@statements__match__invalid_class_pattern.py.snap
  crates/ruff_python_parser/tests/snapshots/invalid_syntax@statements__match__invalid_lhs_or_rhs_pattern.py.snap
  crates/ruff_python_parser/tests/snapshots/invalid_syntax@statements__match__unary_add_usage.py.snap
Labels: parser

#10523 Avoid dropping node from `as` pattern
  crates/ruff_python_parser/resources/invalid/statements/match/as_pattern_0.py
  crates/ruff_python_parser/resources/invalid/statements/match/as_pattern_1.py
  crates/ruff_python_parser/resources/invalid/statements/match/as_pattern_2.py
  crates/ruff_python_parser/resources/invalid/statements/match/as_pattern_3.py
  crates/ruff_python_parser/src/parser/pattern.rs
  crates/ruff_python_parser/src/parser/recovery.rs
  crates/ruff_python_parser/tests/snapshots/invalid_syntax@statements__match__as_pattern_0.py.snap
  crates/ruff_python_parser/tests/snapshots/invalid_syntax@statements__match__as_pattern_1.py.snap
  crates/ruff_python_parser/tests/snapshots/invalid_syntax@statements__match__as_pattern_2.py.snap
  crates/ruff_python_parser/tests/snapshots/invalid_syntax@statements__match__as_pattern_3.py.snap
Labels: parser

#10525 Track ranges of names inside `__all__` definitions
  crates/ruff_linter/src/checkers/ast/analyze/definitions.rs
  crates/ruff_linter/src/checkers/ast/mod.rs
  crates/ruff_linter/src/rules/pyflakes/snapshots/ruff_linter__rules__pyflakes__tests__F405_F405.py.snap
  crates/ruff_linter/src/rules/pyflakes/snapshots/ruff_linter__rules__pyflakes__tests__F822_F822_0.py.snap
  crates/ruff_linter/src/rules/pyflakes/snapshots/ruff_linter__rules__pyflakes__tests__F822_F822_0.pyi.snap
  crates/ruff_linter/src/rules/pyflakes/snapshots/ruff_linter__rules__pyflakes__tests__F822_F822_1.py.snap
  crates/ruff_python_ast/src/all.rs
  crates/ruff_python_semantic/src/binding.rs
  crates/ruff_python_semantic/src/definition.rs
Labels: bug, fixes

#10529 Respect Unicode characters in import sorting
  crates/ruff_linter/resources/test/fixtures/isort/unicode.py
  crates/ruff_linter/src/rules/isort/annotate.rs
  crates/ruff_linter/src/rules/isort/mod.rs
  crates/ruff_linter/src/rules/isort/snapshots/ruff_linter__rules__isort__tests__unicode.py.snap
Labels: bug, isort

#10527 Correctly handle references in `__all__` definitions when renaming symbols in autofixes
  crates/ruff_linter/resources/test/fixtures/flake8_pyi/PYI025_1.py
  crates/ruff_linter/resources/test/fixtures/flake8_pyi/PYI025_1.pyi
  crates/ruff_linter/resources/test/fixtures/flake8_pyi/PYI025_2.py
  crates/ruff_linter/resources/test/fixtures/flake8_pyi/PYI025_2.pyi
  crates/ruff_linter/src/checkers/ast/mod.rs
  crates/ruff_linter/src/renamer.rs
  crates/ruff_linter/src/rules/flake8_import_conventions/rules/unconventional_import_alias.rs
  crates/ruff_linter/src/rules/flake8_pyi/mod.rs
  crates/ruff_linter/src/rules/flake8_pyi/rules/unaliased_collections_abc_set_import.rs
  crates/ruff_linter/src/rules/flake8_pyi/snapshots/ruff_linter__rules__flake8_pyi__tests__PYI025_PYI025_1.py.snap
  crates/ruff_linter/src/rules/flake8_pyi/snapshots/ruff_linter__rules__flake8_pyi__tests__PYI025_PYI025_1.pyi.snap
  crates/ruff_linter/src/rules/flake8_pyi/snapshots/ruff_linter__rules__flake8_pyi__tests__PYI025_PYI025_2.py.snap
  crates/ruff_linter/src/rules/flake8_pyi/snapshots/ruff_linter__rules__flake8_pyi__tests__PYI025_PYI025_2.pyi.snap
  crates/ruff_linter/src/rules/pep8_naming/rules/invalid_first_argument_name.rs
  crates/ruff_python_semantic/src/model.rs
  crates/ruff_python_semantic/src/reference.rs
Labels: bug, fixes, linter

#10530 Add `PlasmaPy` to ecosystem checks
  python/ruff-ecosystem/ruff_ecosystem/defaults.py
Labels: ci

#10532 Fix `PT014` autofix for last item in list
  crates/ruff_linter/resources/test/fixtures/flake8_pytest_style/PT014.py
  crates/ruff_linter/src/rules/flake8_pytest_style/rules/parametrize.rs
  crates/ruff_linter/src/rules/flake8_pytest_style/snapshots/ruff_linter__rules__flake8_pytest_style__tests__PT014.snap
Labels: bug

#10312 Move `Q001-3` to AST based checker
  crates/ruff_linter/src/checkers/ast/analyze/string_like.rs
  crates/ruff_linter/src/checkers/tokens.rs
  crates/ruff_linter/src/registry.rs
  crates/ruff_linter/src/rules/flake8_quotes/rules/check_string_quotes.rs
  crates/ruff_linter/src/rules/flake8_quotes/snapshots/ruff_linter__rules__flake8_quotes__tests__require_docstring_doubles_over_docstring_singles_mixed_quotes_class_var_1.py.snap
  crates/ruff_linter/src/rules/flake8_quotes/snapshots/ruff_linter__rules__flake8_quotes__tests__require_docstring_doubles_over_docstring_singles_mixed_quotes_class_var_2.py.snap
  crates/ruff_linter/src/rules/flake8_quotes/snapshots/ruff_linter__rules__flake8_quotes__tests__require_docstring_doubles_over_docstring_singles_mixed_quotes_module_singleline_var_1.py.snap
  crates/ruff_linter/src/rules/flake8_quotes/snapshots/ruff_linter__rules__flake8_quotes__tests__require_docstring_doubles_over_docstring_singles_mixed_quotes_module_singleline_var_2.py.snap
Labels: internal

#10545 [`E402`] Allow cell magics before an import
  crates/ruff_linter/resources/test/fixtures/pycodestyle/E402.ipynb
  crates/ruff_linter/src/checkers/ast/mod.rs
  crates/ruff_linter/src/rules/pycodestyle/snapshots/ruff_linter__rules__pycodestyle__tests__E402_E402.ipynb.snap
Labels: rule

#10543 Refactor `package_roots` for readability.
  crates/ruff_workspace/src/resolver.rs
Labels: internal

#10547 Mark PYI025 fix as safe in more cases for stub files
  crates/ruff_linter/resources/test/fixtures/flake8_pyi/PYI025_3.py
  crates/ruff_linter/resources/test/fixtures/flake8_pyi/PYI025_3.pyi
  crates/ruff_linter/src/rules/flake8_pyi/mod.rs
  crates/ruff_linter/src/rules/flake8_pyi/rules/unaliased_collections_abc_set_import.rs
  crates/ruff_linter/src/rules/flake8_pyi/snapshots/ruff_linter__rules__flake8_pyi__tests__PYI025_PYI025_1.pyi.snap
  crates/ruff_linter/src/rules/flake8_pyi/snapshots/ruff_linter__rules__flake8_pyi__tests__PYI025_PYI025_3.py.snap
  crates/ruff_linter/src/rules/flake8_pyi/snapshots/ruff_linter__rules__flake8_pyi__tests__PYI025_PYI025_3.pyi.snap
Labels: fixes

#10539 [`flake8-bugbear`] Avoid false positive for usage after `continue` (`B031`)
  crates/ruff_linter/resources/test/fixtures/flake8_bugbear/B031.py
  crates/ruff_linter/src/rules/flake8_bugbear/rules/reuse_of_groupby_generator.rs
  crates/ruff_linter/src/rules/flake8_bugbear/snapshots/ruff_linter__rules__flake8_bugbear__tests__B031_B031.py.snap
Labels: bug

#10533 [`refurb`] Implement `verbose-decimal-constructor` (`FURB157`)
  crates/ruff_linter/resources/test/fixtures/refurb/FURB157.py
  crates/ruff_linter/src/checkers/ast/analyze/expression.rs
  crates/ruff_linter/src/codes.rs
  crates/ruff_linter/src/rules/refurb/mod.rs
  crates/ruff_linter/src/rules/refurb/rules/mod.rs
  crates/ruff_linter/src/rules/refurb/rules/verbose_decimal_constructor.rs
  crates/ruff_linter/src/rules/refurb/snapshots/ruff_linter__rules__refurb__tests__FURB157_FURB157.py.snap
  ruff.schema.json
Labels: rule, preview

#10551 Document use of anonymous assignment in `useless-expression`
  crates/ruff_linter/src/rules/flake8_bugbear/rules/useless_expression.rs
Labels: documentation

#10541 Nested namespace packages support
  CONTRIBUTING.md
  crates/ruff_linter/src/packaging.rs
  crates/ruff_workspace/src/options.rs
  crates/ruff_workspace/src/resolver.rs
  ruff.schema.json
Labels: isort

#10548 Move `Q004` to AST based checker
  crates/ruff_linter/src/checkers/ast/analyze/string_like.rs
  crates/ruff_linter/src/checkers/tokens.rs
  crates/ruff_linter/src/rules/flake8_quotes/helpers.rs
  crates/ruff_linter/src/rules/flake8_quotes/mod.rs
  crates/ruff_linter/src/rules/flake8_quotes/rules/avoidable_escaped_quote.rs
  crates/ruff_linter/src/rules/flake8_quotes/rules/mod.rs
  crates/ruff_linter/src/rules/flake8_quotes/rules/unnecessary_escaped_quote.rs
Labels: internal

#10291 [`pycodestyle`] Avoid blank line rules for the first logical line in cell
  crates/ruff_linter/resources/test/fixtures/pycodestyle/E30.ipynb
  crates/ruff_linter/src/checkers/tokens.rs
  crates/ruff_linter/src/rules/pycodestyle/mod.rs
  crates/ruff_linter/src/rules/pycodestyle/rules/blank_lines.rs
  crates/ruff_linter/src/rules/pycodestyle/snapshots/ruff_linter__rules__pycodestyle__tests__blank_lines_E301_notebook.snap
  crates/ruff_linter/src/rules/pycodestyle/snapshots/ruff_linter__rules__pycodestyle__tests__blank_lines_E302_notebook.snap
  crates/ruff_linter/src/rules/pycodestyle/snapshots/ruff_linter__rules__pycodestyle__tests__blank_lines_E303_notebook.snap
  crates/ruff_linter/src/rules/pycodestyle/snapshots/ruff_linter__rules__pycodestyle__tests__blank_lines_E304_notebook.snap
  crates/ruff_linter/src/rules/pycodestyle/snapshots/ruff_linter__rules__pycodestyle__tests__blank_lines_E305_notebook.snap
  crates/ruff_linter/src/rules/pycodestyle/snapshots/ruff_linter__rules__pycodestyle__tests__blank_lines_E306_notebook.snap
Labels: rule

#10568 Use expr range for invalid node
  crates/ruff_python_parser/resources/invalid/statements/match/as_pattern_4.py
  crates/ruff_python_parser/src/parser/pattern.rs
  crates/ruff_python_parser/tests/snapshots/invalid_syntax@statements__match__as_pattern_4.py.snap
Labels: parser

#10564 Select more rules for typeshed in the ecosystem checks
  python/ruff-ecosystem/ruff_ecosystem/defaults.py
Labels: ci

#10566 [`Pylint`] Fixed false-positive on the rule `PLW1641` (`eq-without-hash`)
  crates/ruff_linter/resources/test/fixtures/pylint/eq_without_hash.py
  crates/ruff_linter/src/rules/pylint/rules/eq_without_hash.rs
Labels: bug

#10567 Switch from dependabot to renovate
  .github/dependabot.yml
  .github/renovate.json5
Labels: ci

#10585 Ignore `Q000`, `Q001` when string is inside forward ref
  crates/ruff_linter/resources/test/fixtures/flake8_quotes/singles.py
  crates/ruff_linter/src/rules/flake8_quotes/rules/check_string_quotes.rs
  crates/ruff_linter/src/rules/flake8_quotes/snapshots/ruff_linter__rules__flake8_quotes__tests__require_doubles_over_singles.py.snap
Labels: bug

#10587 Put flake8-logging next to the other flake8 plugins in registry
  crates/ruff_linter/src/registry.rs
Labels: documentation

#10591 Fix list markup: blank line required
  crates/ruff_workspace/src/options.rs
  ruff.schema.json
Labels: documentation

#10596 [`flake8-comprehensions`] Handled special case for `C401` which also matches `C416`
  crates/ruff_linter/resources/test/fixtures/flake8_comprehensions/C401.py
  crates/ruff_linter/src/rules/flake8_comprehensions/rules/unnecessary_generator_set.rs
  crates/ruff_linter/src/rules/flake8_comprehensions/snapshots/ruff_linter__rules__flake8_comprehensions__tests__C401_C401.py.snap
Labels: rule

#10565 High-level project overview and contributing guide for `ruff server`
  crates/ruff_server/CONTRIBUTING.md
  crates/ruff_server/README.md
Labels: documentation
