Repository astral-sh/ruff, pull requests merged in 2024-02, with the labels that each got.

#9752 Use fake rules for testing deprecation and removal infrastructure
  crates/ruff/tests/integration_test.rs
  crates/ruff_linter/src/codes.rs
  crates/ruff_linter/src/linter.rs
  crates/ruff_linter/src/rules/ruff/rules/test_rules.rs
  crates/ruff_workspace/src/configuration.rs
Labels: internal

#9754 Add tests for redirected rules
  crates/ruff/tests/integration_test.rs
  crates/ruff_linter/src/codes.rs
  crates/ruff_linter/src/linter.rs
  crates/ruff_linter/src/rule_redirects.rs
  crates/ruff_linter/src/rules/ruff/rules/test_rules.rs
  crates/ruff_workspace/src/configuration.rs
Labels: internal

#9755 Redirect `TRY200` to `B904`
  crates/ruff_linter/resources/test/fixtures/tryceratops/TRY200.py
  crates/ruff_linter/src/checkers/ast/analyze/except_handler.rs
  crates/ruff_linter/src/codes.rs
  crates/ruff_linter/src/rule_redirects.rs
  crates/ruff_linter/src/rules/tryceratops/mod.rs
  crates/ruff_linter/src/rules/tryceratops/rules/reraise_no_cause.rs
  crates/ruff_linter/src/rules/tryceratops/snapshots/ruff_linter__rules__tryceratops__tests__reraise-no-cause_TRY200.py.snap
Labels: rule

#9756 Redirect `PHG001` to `S307` and `PGH002` to `G010`
  crates/ruff_linter/resources/test/fixtures/pygrep_hooks/PGH001_0.py
  crates/ruff_linter/resources/test/fixtures/pygrep_hooks/PGH001_1.py
  crates/ruff_linter/resources/test/fixtures/pygrep_hooks/PGH002_0.py
  crates/ruff_linter/resources/test/fixtures/pygrep_hooks/PGH002_1.py
  crates/ruff_linter/src/checkers/ast/analyze/expression.rs
  crates/ruff_linter/src/codes.rs
  crates/ruff_linter/src/rule_redirects.rs
  crates/ruff_linter/src/rule_selector.rs
  crates/ruff_linter/src/rules/pygrep_hooks/mod.rs
  crates/ruff_linter/src/rules/pygrep_hooks/rules/deprecated_log_warn.rs
  crates/ruff_linter/src/rules/pygrep_hooks/rules/no_eval.rs
  crates/ruff_linter/src/rules/pygrep_hooks/snapshots/ruff_linter__rules__pygrep_hooks__tests__PGH001_PGH001_0.py.snap
  crates/ruff_linter/src/rules/pygrep_hooks/snapshots/ruff_linter__rules__pygrep_hooks__tests__PGH001_PGH001_1.py.snap
  crates/ruff_linter/src/rules/pygrep_hooks/snapshots/ruff_linter__rules__pygrep_hooks__tests__PGH002_PGH002_0.py.snap
  crates/ruff_linter/src/rules/pygrep_hooks/snapshots/ruff_linter__rules__pygrep_hooks__tests__PGH002_PGH002_1.py.snap
  ruff.schema.json
Labels: rule

#9758 Restore RUF011 documentation
  crates/ruff/tests/integration_test.rs
  crates/ruff_linter/src/codes.rs
  crates/ruff_linter/src/rule_selector.rs
  crates/ruff_linter/src/rules/ruff/rules/mod.rs
  crates/ruff_linter/src/rules/ruff/rules/static_key_dict_comprehension.rs
  crates/ruff_workspace/src/configuration.rs
Labels: internal

#9759 Remove stale preview documentation from stabilized rule behaviors
  crates/ruff_linter/src/rules/flake8_simplify/rules/ast_expr.rs
  crates/ruff_linter/src/rules/flake8_simplify/rules/key_in_dict.rs
  crates/ruff_linter/src/rules/pycodestyle/rules/module_import_not_at_top_of_file.rs
Labels: documentation

#9760 Use consistent method to detect preview enablement
  crates/ruff_linter/src/rules/pyflakes/rules/invalid_literal_comparisons.rs
  crates/ruff_linter/src/rules/pyflakes/rules/unused_variable.rs
Labels: internal

#9763 Fix issue where output format mode would not change to `full` if preview mode was set in configuration file
  crates/ruff/src/lib.rs
  crates/ruff/tests/integration_test.rs
Labels: bug

#9768 Move `adjust_indentation` to a shared home
  crates/ruff_linter/src/fix/edits.rs
  crates/ruff_linter/src/rules/flake8_return/rules/function.rs
  crates/ruff_linter/src/rules/pylint/rules/collapsible_else_if.rs
  crates/ruff_linter/src/rules/pylint/rules/useless_else_on_loop.rs
  crates/ruff_linter/src/rules/pyupgrade/fixes.rs
  crates/ruff_linter/src/rules/pyupgrade/rules/outdated_version_block.rs
Labels: internal

#9771 Fix references to deprecated `ANN` rules in changelog
  CHANGELOG.md
Labels: documentation

#9774 Fixed example code in weak_cryptographic_key.rs
  crates/ruff_linter/src/rules/flake8_bandit/rules/weak_cryptographic_key.rs
Labels: documentation

#9782 add pytest to who's using ruff
  README.md
Labels: documentation

#9784 Made hyperlink on homepage correctly redirect to GitHub
  scripts/generate_mkdocs.py
Labels: documentation

#9776 [flake8-bugbear][B006] remove outdated comment
  crates/ruff_linter/src/rules/flake8_bugbear/rules/mutable_argument_default.rs
Labels: documentation

#9773 Use `AhoCorasick` to speed up quote match
  Cargo.lock
  crates/ruff_linter/src/checkers/ast/mod.rs
  crates/ruff_linter/src/rules/pyupgrade/rules/f_strings.rs
  crates/ruff_python_ast/Cargo.toml
  crates/ruff_python_ast/src/str.rs
Labels: performance

#9787 `README.md`: add missing "your" in support section, add alt text to Astral logo
  README.md
Labels: documentation

#9751 Range formatting: Fix invalid syntax after parenthesizing expression
  crates/ruff_formatter/src/builders.rs
  crates/ruff_formatter/src/format_element/document.rs
  crates/ruff_formatter/src/format_extensions.rs
  crates/ruff_formatter/src/lib.rs
  crates/ruff_formatter/src/printer/mod.rs
  crates/ruff_formatter/src/printer/printer_options/mod.rs
  crates/ruff_python_formatter/resources/test/fixtures/ruff/range_formatting/end_of_file.py
  crates/ruff_python_formatter/resources/test/fixtures/ruff/range_formatting/parentheses.py
  crates/ruff_python_formatter/resources/test/fixtures/ruff/range_formatting/regressions.py
  crates/ruff_python_formatter/src/comments/format.rs
  crates/ruff_python_formatter/src/expression/expr_number_literal.rs
  crates/ruff_python_formatter/src/expression/mod.rs
  crates/ruff_python_formatter/src/lib.rs
  crates/ruff_python_formatter/src/options.rs
  crates/ruff_python_formatter/src/other/identifier.rs
  crates/ruff_python_formatter/src/range.rs
  crates/ruff_python_formatter/src/statement/suite.rs
  crates/ruff_python_formatter/src/string/docstring.rs
  crates/ruff_python_formatter/src/string/mod.rs
  crates/ruff_python_formatter/src/verbatim.rs
  crates/ruff_python_formatter/tests/snapshots/format@range_formatting__end_of_file.py.snap
  crates/ruff_python_formatter/tests/snapshots/format@range_formatting__parentheses.py.snap
  crates/ruff_python_formatter/tests/snapshots/format@range_formatting__regressions.py.snap
  crates/ruff_text_size/src/size.rs
Labels: internal, formatter

#9769 Skip LibCST parsing for standard dedent adjustments
  crates/ruff_linter/resources/test/fixtures/pyupgrade/UP036_0.py
  crates/ruff_linter/src/fix/edits.rs
  crates/ruff_linter/src/rules/flake8_return/rules/function.rs
  crates/ruff_linter/src/rules/pycodestyle/rules/trailing_whitespace.rs
  crates/ruff_linter/src/rules/pylint/rules/collapsible_else_if.rs
  crates/ruff_linter/src/rules/pylint/rules/useless_else_on_loop.rs
  crates/ruff_linter/src/rules/pyupgrade/rules/outdated_version_block.rs
  crates/ruff_linter/src/rules/pyupgrade/snapshots/ruff_linter__rules__pyupgrade__tests__UP036_0.py.snap
  crates/ruff_python_index/src/fstring_ranges.rs
  crates/ruff_python_index/src/multiline_ranges.rs
  crates/ruff_python_trivia/src/comment_ranges.rs
  crates/ruff_python_trivia/src/textwrap.rs
Labels: performance

#9775 Track top-level module imports in the semantic model
  crates/ruff_linter/src/checkers/ast/analyze/expression.rs
  crates/ruff_linter/src/checkers/ast/mod.rs
  crates/ruff_linter/src/rules/flake8_2020/rules/name_or_attribute.rs
  crates/ruff_linter/src/rules/flake8_async/rules/blocking_os_call.rs
  crates/ruff_linter/src/rules/flake8_bandit/rules/bad_file_permissions.rs
  crates/ruff_linter/src/rules/flake8_bandit/rules/django_raw_sql.rs
  crates/ruff_linter/src/rules/flake8_bandit/rules/logging_config_insecure_listen.rs
  crates/ruff_linter/src/rules/flake8_bandit/rules/tarfile_unsafe_members.rs
  crates/ruff_linter/src/rules/flake8_bugbear/rules/re_sub_positional_args.rs
  crates/ruff_linter/src/rules/flake8_datetimez/rules/call_date_fromtimestamp.rs
  crates/ruff_linter/src/rules/flake8_datetimez/rules/call_date_today.rs
  crates/ruff_linter/src/rules/flake8_datetimez/rules/call_datetime_fromtimestamp.rs
  crates/ruff_linter/src/rules/flake8_datetimez/rules/call_datetime_now_without_tzinfo.rs
  crates/ruff_linter/src/rules/flake8_datetimez/rules/call_datetime_strptime_without_zone.rs
  crates/ruff_linter/src/rules/flake8_datetimez/rules/call_datetime_today.rs
  crates/ruff_linter/src/rules/flake8_datetimez/rules/call_datetime_utcfromtimestamp.rs
  crates/ruff_linter/src/rules/flake8_datetimez/rules/call_datetime_utcnow.rs
  crates/ruff_linter/src/rules/flake8_datetimez/rules/call_datetime_without_tzinfo.rs
  crates/ruff_linter/src/rules/flake8_django/rules/all_with_model_form.rs
  crates/ruff_linter/src/rules/flake8_django/rules/exclude_with_model_form.rs
  crates/ruff_linter/src/rules/flake8_django/rules/locals_in_render_function.rs
  crates/ruff_linter/src/rules/flake8_django/rules/model_without_dunder_str.rs
  crates/ruff_linter/src/rules/flake8_django/rules/non_leading_receiver_decorator.rs
  crates/ruff_linter/src/rules/flake8_django/rules/nullable_model_string_field.rs
  crates/ruff_linter/src/rules/flake8_django/rules/unordered_body_content_in_model.rs
  crates/ruff_linter/src/rules/flake8_logging/rules/direct_logger_instantiation.rs
  crates/ruff_linter/src/rules/flake8_logging/rules/invalid_get_logger_argument.rs
  crates/ruff_linter/src/rules/flake8_logging/rules/undocumented_warn.rs
  crates/ruff_linter/src/rules/flake8_pyi/rules/collections_named_tuple.rs
  crates/ruff_linter/src/rules/flake8_simplify/rules/ast_expr.rs
  crates/ruff_linter/src/rules/flake8_tidy_imports/rules/banned_api.rs
  crates/ruff_linter/src/rules/flake8_trio/rules/async_function_with_timeout.rs
  crates/ruff_linter/src/rules/flake8_trio/rules/sync_call.rs
  crates/ruff_linter/src/rules/flake8_trio/rules/timeout_without_await.rs
  crates/ruff_linter/src/rules/flake8_trio/rules/unneeded_sleep.rs
  crates/ruff_linter/src/rules/flake8_trio/rules/zero_sleep_call.rs
  crates/ruff_linter/src/rules/flake8_use_pathlib/rules/os_sep_split.rs
  crates/ruff_linter/src/rules/numpy/rules/deprecated_function.rs
  crates/ruff_linter/src/rules/numpy/rules/deprecated_type_alias.rs
  crates/ruff_linter/src/rules/numpy/rules/legacy_random.rs
  crates/ruff_linter/src/rules/numpy/rules/numpy_2_0_deprecation.rs
  crates/ruff_linter/src/rules/pandas_vet/rules/attr.rs
  crates/ruff_linter/src/rules/pandas_vet/rules/read_table.rs
  crates/ruff_linter/src/rules/pep8_naming/rules/non_lowercase_variable_in_function.rs
  crates/ruff_linter/src/rules/pylint/rules/invalid_envvar_default.rs
  crates/ruff_linter/src/rules/pylint/rules/invalid_envvar_value.rs
  crates/ruff_linter/src/rules/pylint/rules/subprocess_popen_preexec_fn.rs
  crates/ruff_linter/src/rules/pylint/rules/subprocess_run_without_check.rs
  crates/ruff_linter/src/rules/pyupgrade/rules/deprecated_mock_import.rs
  crates/ruff_linter/src/rules/pyupgrade/rules/replace_stdout_stderr.rs
  crates/ruff_linter/src/rules/pyupgrade/rules/replace_universal_newlines.rs
  crates/ruff_linter/src/rules/pyupgrade/rules/typing_text_str_alias.rs
  crates/ruff_linter/src/rules/refurb/rules/regex_flag_alias.rs
  crates/ruff_python_semantic/src/analyze/typing.rs
  crates/ruff_python_semantic/src/model.rs
Labels: performance

#9797 Update max-pos-args example to max-positional-args.
  crates/ruff_workspace/src/options.rs
Labels: documentation

#9728 Implement RUF027: `Missing F-String Syntax` lint
  crates/ruff_linter/resources/test/fixtures/ruff/RUF027.py
  crates/ruff_linter/src/checkers/ast/analyze/expression.rs
  crates/ruff_linter/src/codes.rs
  crates/ruff_linter/src/rules/ruff/mod.rs
  crates/ruff_linter/src/rules/ruff/rules/missing_fstring_syntax.rs
  crates/ruff_linter/src/rules/ruff/rules/mod.rs
  crates/ruff_linter/src/rules/ruff/snapshots/ruff_linter__rules__ruff__tests__RUF027_RUF027.py.snap
  ruff.schema.json
Labels: rule

#9802 Add our own ignored-names abstractions
  crates/ruff_linter/src/rules/pep8_naming/mod.rs
  crates/ruff_linter/src/rules/pep8_naming/rules/camelcase_imported_as_acronym.rs
  crates/ruff_linter/src/rules/pep8_naming/rules/camelcase_imported_as_constant.rs
  crates/ruff_linter/src/rules/pep8_naming/rules/camelcase_imported_as_lowercase.rs
  crates/ruff_linter/src/rules/pep8_naming/rules/constant_imported_as_non_constant.rs
  crates/ruff_linter/src/rules/pep8_naming/rules/dunder_function_name.rs
  crates/ruff_linter/src/rules/pep8_naming/rules/error_suffix_on_exception_name.rs
  crates/ruff_linter/src/rules/pep8_naming/rules/invalid_argument_name.rs
  crates/ruff_linter/src/rules/pep8_naming/rules/invalid_class_name.rs
  crates/ruff_linter/src/rules/pep8_naming/rules/invalid_first_argument_name_for_class_method.rs
  crates/ruff_linter/src/rules/pep8_naming/rules/invalid_first_argument_name_for_method.rs
  crates/ruff_linter/src/rules/pep8_naming/rules/invalid_function_name.rs
  crates/ruff_linter/src/rules/pep8_naming/rules/invalid_module_name.rs
  crates/ruff_linter/src/rules/pep8_naming/rules/lowercase_imported_as_non_lowercase.rs
  crates/ruff_linter/src/rules/pep8_naming/rules/mixed_case_variable_in_class_scope.rs
  crates/ruff_linter/src/rules/pep8_naming/rules/mixed_case_variable_in_global_scope.rs
  crates/ruff_linter/src/rules/pep8_naming/rules/non_lowercase_variable_in_function.rs
  crates/ruff_linter/src/rules/pep8_naming/settings.rs
  crates/ruff_workspace/src/options.rs
Labels: performance

#9800 Short-circuit typing matches based on imports
  crates/ruff_linter/src/rules/flake8_boolean_trap/rules/boolean_type_hint_positional_argument.rs
  crates/ruff_linter/src/rules/flake8_pyi/rules/prefix_type_params.rs
  crates/ruff_linter/src/rules/flake8_type_checking/helpers.rs
  crates/ruff_linter/src/rules/pep8_naming/helpers.rs
  crates/ruff_linter/src/rules/pylint/rules/redefined_loop_name.rs
  crates/ruff_linter/src/rules/pylint/rules/type_bivariance.rs
  crates/ruff_linter/src/rules/pylint/rules/type_name_incorrect_variance.rs
  crates/ruff_linter/src/rules/pylint/rules/type_param_name_mismatch.rs
  crates/ruff_linter/src/rules/ruff/rules/helpers.rs
  crates/ruff_python_semantic/src/analyze/typing.rs
  crates/ruff_python_semantic/src/model.rs
Labels: performance

#9815 Run dunder method rule on methods directly
  crates/ruff_linter/src/checkers/ast/analyze/definitions.rs
  crates/ruff_linter/src/checkers/ast/analyze/statement.rs
  crates/ruff_linter/src/rules/pylint/rules/bad_dunder_method_name.rs
Labels: internal

#9818 Remove LibCST-based fixer for `C403`
  crates/ruff_linter/resources/test/fixtures/flake8_comprehensions/C403.py
  crates/ruff_linter/src/checkers/ast/analyze/expression.rs
  crates/ruff_linter/src/rules/flake8_comprehensions/fixes.rs
  crates/ruff_linter/src/rules/flake8_comprehensions/rules/unnecessary_collection_call.rs
  crates/ruff_linter/src/rules/flake8_comprehensions/rules/unnecessary_list_comprehension_set.rs
  crates/ruff_linter/src/rules/flake8_comprehensions/snapshots/ruff_linter__rules__flake8_comprehensions__tests__C403_C403.py.snap
Labels: fixes

#9819 Remove CST-based fixers for `C400`, `C401`, `C410`, and `C418`
  crates/ruff_linter/resources/test/fixtures/flake8_comprehensions/C410.py
  crates/ruff_linter/src/checkers/ast/analyze/expression.rs
  crates/ruff_linter/src/rules/flake8_comprehensions/fixes.rs
  crates/ruff_linter/src/rules/flake8_comprehensions/rules/unnecessary_generator_list.rs
  crates/ruff_linter/src/rules/flake8_comprehensions/rules/unnecessary_generator_set.rs
  crates/ruff_linter/src/rules/flake8_comprehensions/rules/unnecessary_list_comprehension_set.rs
  crates/ruff_linter/src/rules/flake8_comprehensions/rules/unnecessary_literal_within_dict_call.rs
  crates/ruff_linter/src/rules/flake8_comprehensions/rules/unnecessary_literal_within_list_call.rs
  crates/ruff_linter/src/rules/flake8_comprehensions/snapshots/ruff_linter__rules__flake8_comprehensions__tests__C410_C410.py.snap
Labels: fixes

#9821 Remove CST-based fixers for `C405` and `C409`
  crates/ruff_linter/resources/test/fixtures/flake8_comprehensions/C409.py
  crates/ruff_linter/src/checkers/ast/analyze/expression.rs
  crates/ruff_linter/src/rules/flake8_comprehensions/fixes.rs
  crates/ruff_linter/src/rules/flake8_comprehensions/rules/unnecessary_literal_set.rs
  crates/ruff_linter/src/rules/flake8_comprehensions/rules/unnecessary_literal_within_tuple_call.rs
  crates/ruff_linter/src/rules/flake8_comprehensions/snapshots/ruff_linter__rules__flake8_comprehensions__tests__C409_C409.py.snap
Labels: fixes

#9822 Remove CST-based fixer for `C408`
  crates/ruff_linter/resources/test/fixtures/flake8_comprehensions/C408.py
  crates/ruff_linter/src/checkers/ast/analyze/expression.rs
  crates/ruff_linter/src/rules/flake8_comprehensions/fixes.rs
  crates/ruff_linter/src/rules/flake8_comprehensions/rules/unnecessary_collection_call.rs
  crates/ruff_linter/src/rules/flake8_comprehensions/snapshots/ruff_linter__rules__flake8_comprehensions__tests__C408_C408.py.snap
  crates/ruff_linter/src/rules/flake8_comprehensions/snapshots/ruff_linter__rules__flake8_comprehensions__tests__C408_C408.py_allow_dict_calls_with_keyword_arguments.snap
Labels: fixes

#9813 Don't trim last empty line in docstrings
  crates/ruff_python_formatter/resources/test/fixtures/ruff/docstring_newlines.py
  crates/ruff_python_formatter/src/string/docstring.rs
  crates/ruff_python_formatter/tests/snapshots/format@docstring_newlines.py.snap
Labels: bug, formatter

#9725 Preview Style: Format module level docstring
  crates/ruff_python_formatter/resources/test/fixtures/ruff/quote_style.py
  crates/ruff_python_formatter/src/preview.rs
  crates/ruff_python_formatter/src/statement/suite.rs
  crates/ruff_python_formatter/tests/snapshots/black_compatibility@cases__module_docstring_2.py.snap
  crates/ruff_python_formatter/tests/snapshots/format@quote_style.py.snap
Labels: bug, formatter, preview

#9791 Drop `__get__` and `__set__` from `unnecessary-dunder-call`
  crates/ruff_linter/resources/test/fixtures/pylint/unnecessary_dunder_call.py
  crates/ruff_linter/src/rules/pylint/rules/unnecessary_dunder_call.rs
  crates/ruff_linter/src/rules/pylint/snapshots/ruff_linter__rules__pylint__tests__PLC2801_unnecessary_dunder_call.py.snap
Labels: bug

#9834 Revert "Use publicly available Apple Silicon runners (#9726)"
  .github/workflows/release.yaml
Labels: bug, release

#9838 Fix default for `max-positional-args`
  crates/ruff_workspace/src/options.rs
Labels: documentation

#9733 Add `--range` option to `ruff format`
  crates/ruff/src/args.rs
  crates/ruff/src/cache.rs
  crates/ruff/src/commands/format.rs
  crates/ruff/src/commands/format_stdin.rs
  crates/ruff/tests/format.rs
  crates/ruff_source_file/src/line_index.rs
  docs/configuration.md
Labels: formatter

#9836 Implement `AnyNode`/`AnyNodeRef` for `FStringFormatSpec`
  crates/ruff_python_ast/src/node.rs
  crates/ruff_python_formatter/src/range.rs
Labels: internal

#9843 Bump version to v0.2.1
  CHANGELOG.md
  Cargo.lock
  README.md
  crates/ruff/Cargo.toml
  crates/ruff_linter/Cargo.toml
  crates/ruff_shrinking/Cargo.toml
  docs/integrations.md
  pyproject.toml
  scripts/benchmarks/pyproject.toml
Labels: release

#9839 Mention a related setting in C408 description
  crates/ruff_linter/src/rules/flake8_comprehensions/rules/unnecessary_collection_call.rs
Labels: documentation

#9850 ruff-ecosystem: Add indico/indico repo
  python/ruff-ecosystem/ruff_ecosystem/defaults.py
Labels: internal

#9837 Index multiline f-strings
  crates/ruff_linter/resources/test/fixtures/pycodestyle/W291.py
  crates/ruff_linter/src/rules/flake8_quotes/rules/avoidable_escaped_quote.rs
  crates/ruff_linter/src/rules/pycodestyle/rules/invalid_escape_sequence.rs
  crates/ruff_linter/src/rules/pycodestyle/snapshots/ruff_linter__rules__pycodestyle__tests__W291_W291.py.snap
  crates/ruff_python_index/src/multiline_ranges.rs
  crates/ruff_python_parser/src/lexer.rs
  crates/ruff_python_parser/src/python.lalrpop
  crates/ruff_python_parser/src/python.rs
  crates/ruff_python_parser/src/snapshots/ruff_python_parser__lexer__tests__fstring.snap
  crates/ruff_python_parser/src/snapshots/ruff_python_parser__lexer__tests__fstring_comments.snap
  crates/ruff_python_parser/src/snapshots/ruff_python_parser__lexer__tests__fstring_conversion.snap
  crates/ruff_python_parser/src/snapshots/ruff_python_parser__lexer__tests__fstring_escape.snap
  crates/ruff_python_parser/src/snapshots/ruff_python_parser__lexer__tests__fstring_escape_braces.snap
  crates/ruff_python_parser/src/snapshots/ruff_python_parser__lexer__tests__fstring_escape_raw.snap
  crates/ruff_python_parser/src/snapshots/ruff_python_parser__lexer__tests__fstring_expression_multiline.snap
  crates/ruff_python_parser/src/snapshots/ruff_python_parser__lexer__tests__fstring_multiline.snap
  crates/ruff_python_parser/src/snapshots/ruff_python_parser__lexer__tests__fstring_named_unicode.snap
  crates/ruff_python_parser/src/snapshots/ruff_python_parser__lexer__tests__fstring_named_unicode_raw.snap
  crates/ruff_python_parser/src/snapshots/ruff_python_parser__lexer__tests__fstring_nested.snap
  crates/ruff_python_parser/src/snapshots/ruff_python_parser__lexer__tests__fstring_parentheses.snap
  crates/ruff_python_parser/src/snapshots/ruff_python_parser__lexer__tests__fstring_single_quote_escape_mac_eol.snap
  crates/ruff_python_parser/src/snapshots/ruff_python_parser__lexer__tests__fstring_single_quote_escape_unix_eol.snap
  crates/ruff_python_parser/src/snapshots/ruff_python_parser__lexer__tests__fstring_single_quote_escape_windows_eol.snap
  crates/ruff_python_parser/src/snapshots/ruff_python_parser__lexer__tests__fstring_with_format_spec.snap
  crates/ruff_python_parser/src/snapshots/ruff_python_parser__lexer__tests__fstring_with_ipy_escape_command.snap
  crates/ruff_python_parser/src/snapshots/ruff_python_parser__lexer__tests__fstring_with_multiline_format_spec.snap
  crates/ruff_python_parser/src/snapshots/ruff_python_parser__lexer__tests__fstring_with_named_expression.snap
  crates/ruff_python_parser/src/snapshots/ruff_python_parser__lexer__tests__fstring_with_nul_char.snap
  crates/ruff_python_parser/src/token.rs
Labels: linter

#9849 Ignore builtins when detecting missing f-strings
  crates/ruff_linter/resources/test/fixtures/ruff/RUF027.py
  crates/ruff_linter/src/rules/ruff/rules/missing_fstring_syntax.rs
  crates/ruff_linter/src/rules/ruff/snapshots/ruff_linter__rules__ruff__tests__RUF027_RUF027.py.snap
Labels: bug

#9853 Use `memchr` for tab-indentation detection
  crates/ruff_linter/src/checkers/tokens.rs
  crates/ruff_linter/src/rules/pycodestyle/rules/tab_indentation.rs
Labels: performance

#9859 Respect `async with` in `timeout-without-await`
  crates/ruff_linter/resources/test/fixtures/flake8_trio/TRIO100.py
  crates/ruff_linter/src/rules/flake8_trio/snapshots/ruff_linter__rules__flake8_trio__tests__TRIO100_TRIO100.py.snap
  crates/ruff_python_ast/src/helpers.rs
Labels: bug

#9867 Improve trailing comma rule performance
  crates/ruff_linter/src/rules/flake8_commas/rules/trailing_commas.rs
Labels: performance

#9866 Make show-settings filters directory-agnostic
  crates/ruff/src/commands/show_settings.rs
  crates/ruff/tests/show_settings.rs
  crates/ruff/tests/snapshots/show_settings__display_default_settings.snap
  crates/ruff_linter/src/settings/mod.rs
  crates/ruff_workspace/src/settings.rs
Labels: bug

#9862 Add more NPY002 violations
  crates/ruff_linter/resources/test/fixtures/numpy/NPY002.py
  crates/ruff_linter/src/rules/numpy/rules/legacy_random.rs
  crates/ruff_linter/src/rules/numpy/snapshots/ruff_linter__rules__numpy__tests__numpy-legacy-random_NPY002.py.snap
Labels: rule

#9874 Fix typo in option name: `output_format` -> `output-format`
  crates/ruff_workspace/src/options.rs
Labels: documentation

#9879 Add a note regarding ignore-without-code
  crates/ruff_linter/src/rules/pygrep_hooks/rules/blanket_type_ignore.rs
Labels: documentation

#9886 Fix list formatting in documention
  crates/ruff_linter/src/rules/ruff/rules/missing_fstring_syntax.rs
Labels: documentation

#9887 Detect `mark_safe` usages in decorators
  crates/ruff_linter/resources/test/fixtures/flake8_bandit/S308.py
  crates/ruff_linter/src/checkers/ast/analyze/statement.rs
  crates/ruff_linter/src/rules/flake8_bandit/mod.rs
  crates/ruff_linter/src/rules/flake8_bandit/rules/suspicious_function_call.rs
  crates/ruff_linter/src/rules/flake8_bandit/snapshots/ruff_linter__rules__flake8_bandit__tests__S308_S308.py.snap
Labels: rule

#9865 RUF027 no longer has false negatives with string literals inside of method calls
  crates/ruff_linter/resources/test/fixtures/ruff/RUF027.py
  crates/ruff_linter/resources/test/fixtures/ruff/RUF027_0.py
  crates/ruff_linter/resources/test/fixtures/ruff/RUF027_1.py
  crates/ruff_linter/src/rules/ruff/mod.rs
  crates/ruff_linter/src/rules/ruff/rules/missing_fstring_syntax.rs
  crates/ruff_linter/src/rules/ruff/snapshots/ruff_linter__rules__ruff__tests__RUF027_RUF027.py.snap
  crates/ruff_linter/src/rules/ruff/snapshots/ruff_linter__rules__ruff__tests__RUF027_RUF027_0.py.snap
  crates/ruff_linter/src/rules/ruff/snapshots/ruff_linter__rules__ruff__tests__RUF027_RUF027_1.py.snap
Labels: rule

#9888 Use `memchr` for string lexing
  crates/ruff_python_parser/src/lexer.rs
  crates/ruff_python_parser/src/lexer/cursor.rs
Labels: performance

#9896 Corrected Path symlink method name (PTH114)
  crates/ruff_linter/src/rules/flake8_use_pathlib/violations.rs
Labels: documentation

#9897 Use Rust 1.76
  Cargo.lock
  crates/ruff_formatter/src/printer/line_suffixes.rs
  crates/ruff_python_ast/Cargo.toml
  crates/ruff_python_ast/src/nodes.rs
  crates/ruff_python_parser/src/parser.rs
  rust-toolchain.toml
Labels: internal

#9266 [`pycodestyle`] Add blank line(s) rules (`E301`, `E302`, `E303`, `E304`, `E305`, `E306`)
  crates/ruff_linter/resources/test/fixtures/pycodestyle/E30.py
  crates/ruff_linter/src/checkers/logical_lines.rs
  crates/ruff_linter/src/checkers/tokens.rs
  crates/ruff_linter/src/codes.rs
  crates/ruff_linter/src/linter.rs
  crates/ruff_linter/src/registry.rs
  crates/ruff_linter/src/rules/pycodestyle/mod.rs
  crates/ruff_linter/src/rules/pycodestyle/rules/blank_lines.rs
  crates/ruff_linter/src/rules/pycodestyle/rules/mod.rs
  crates/ruff_linter/src/rules/pycodestyle/snapshots/ruff_linter__rules__pycodestyle__tests__E301_E30.py.snap
  crates/ruff_linter/src/rules/pycodestyle/snapshots/ruff_linter__rules__pycodestyle__tests__E302_E30.py.snap
  crates/ruff_linter/src/rules/pycodestyle/snapshots/ruff_linter__rules__pycodestyle__tests__E303_E30.py.snap
  crates/ruff_linter/src/rules/pycodestyle/snapshots/ruff_linter__rules__pycodestyle__tests__E304_E30.py.snap
  crates/ruff_linter/src/rules/pycodestyle/snapshots/ruff_linter__rules__pycodestyle__tests__E305_E30.py.snap
  crates/ruff_linter/src/rules/pycodestyle/snapshots/ruff_linter__rules__pycodestyle__tests__E306_E30.py.snap
  crates/ruff_workspace/src/configuration.rs
  ruff.schema.json
  scripts/check_docs_formatted.py
Labels: rule, preview

#9885 Reduce `Result<Tok, LexicalError>` size by using `Box<str>` instead of `String`
  crates/ruff_linter/src/rules/flake8_pytest_style/rules/parametrize.rs
  crates/ruff_linter/src/rules/flake8_simplify/rules/ast_expr.rs
  crates/ruff_linter/src/rules/flynt/rules/static_join_to_fstring.rs
  crates/ruff_linter/src/rules/pycodestyle/rules/invalid_escape_sequence.rs
  crates/ruff_linter/src/rules/pylint/rules/unspecified_encoding.rs
  crates/ruff_linter/src/rules/pyupgrade/fixes.rs
  crates/ruff_linter/src/rules/ruff/rules/sequence_sorting.rs
  crates/ruff_python_ast/src/comparable.rs
  crates/ruff_python_ast/src/nodes.rs
  crates/ruff_python_formatter/src/lib.rs
  crates/ruff_python_formatter/src/range.rs
  crates/ruff_python_formatter/tests/normalizer.rs
  crates/ruff_python_parser/src/function.rs
  crates/ruff_python_parser/src/invalid.rs
  crates/ruff_python_parser/src/lexer.rs
  crates/ruff_python_parser/src/parser.rs
  crates/ruff_python_parser/src/python.lalrpop
  crates/ruff_python_parser/src/python.rs
  crates/ruff_python_parser/src/soft_keywords.rs
  crates/ruff_python_parser/src/string.rs
  crates/ruff_python_parser/src/token.rs
  fuzz/fuzz_targets/ruff_parse_simple.rs
Labels: performance

#9901 Filter out test rules in `RuleSelector` JSON schema
  .github/workflows/ci.yaml
  crates/ruff_linter/src/rule_selector.rs
Labels: internal

#9902 Fix clippy unused variable warning
  crates/ruff_linter/src/rule_selector.rs
Labels: internal

#9894 [`pydocstyle-D405`] Allow using `parameters` as a sub-section header
  crates/ruff_linter/resources/test/fixtures/pydocstyle/sections.py
  crates/ruff_linter/src/docstrings/sections.rs
  crates/ruff_linter/src/rules/pydocstyle/snapshots/ruff_linter__rules__pydocstyle__tests__D214_sections.py.snap
  crates/ruff_linter/src/rules/pydocstyle/snapshots/ruff_linter__rules__pydocstyle__tests__D406_sections.py.snap
  crates/ruff_linter/src/rules/pydocstyle/snapshots/ruff_linter__rules__pydocstyle__tests__D407_sections.py.snap
  crates/ruff_linter/src/rules/pydocstyle/snapshots/ruff_linter__rules__pydocstyle__tests__D409_sections.py.snap
  crates/ruff_linter/src/rules/pydocstyle/snapshots/ruff_linter__rules__pydocstyle__tests__D413_sections.py.snap
Labels: bug, docstring

#9907 Fix `E30X` panics on blank lines with trailing white spaces
  crates/ruff_linter/resources/test/fixtures/pycodestyle/E30.py
  crates/ruff_linter/src/rules/pycodestyle/rules/blank_lines.rs
  crates/ruff_linter/src/rules/pycodestyle/snapshots/ruff_linter__rules__pycodestyle__tests__E301_E30.py.snap
  crates/ruff_linter/src/rules/pycodestyle/snapshots/ruff_linter__rules__pycodestyle__tests__E302_E30.py.snap
  crates/ruff_linter/src/rules/pycodestyle/snapshots/ruff_linter__rules__pycodestyle__tests__E303_E30.py.snap
  crates/ruff_linter/src/rules/pycodestyle/snapshots/ruff_linter__rules__pycodestyle__tests__E304_E30.py.snap
  crates/ruff_linter/src/rules/pycodestyle/snapshots/ruff_linter__rules__pycodestyle__tests__E305_E30.py.snap
  crates/ruff_linter/src/rules/pycodestyle/snapshots/ruff_linter__rules__pycodestyle__tests__E306_E30.py.snap
Labels: bug

#9905 Respect duplicates when rewriting type aliases
  crates/ruff_linter/resources/test/fixtures/pyupgrade/UP040.py
  crates/ruff_linter/src/rules/pyupgrade/rules/use_pep695_type_alias.rs
  crates/ruff_linter/src/rules/pyupgrade/snapshots/ruff_linter__rules__pyupgrade__tests__UP040.py.snap
Labels: bug

#9916 Update pyproject-toml to 0.9
  Cargo.lock
  Cargo.toml
Labels: internal

#9903 Use `usize` instead of `TextSize` for `indent_len`
  crates/ruff_python_formatter/src/string/docstring.rs
Labels: internal

#9914 Corrected PTH203–PTH205 rule descriptions
  crates/ruff_linter/src/rules/flake8_use_pathlib/rules/os_path_getatime.rs
  crates/ruff_linter/src/rules/flake8_use_pathlib/rules/os_path_getctime.rs
  crates/ruff_linter/src/rules/flake8_use_pathlib/rules/os_path_getmtime.rs
Labels: documentation

#9884 Remove unnecessary string cloning from the parser
  Cargo.lock
  Cargo.toml
  crates/ruff_linter/src/rules/flake8_bandit/rules/hardcoded_bind_all_interfaces.rs
  crates/ruff_linter/src/rules/flynt/helpers.rs
  crates/ruff_python_ast/src/comparable.rs
  crates/ruff_python_ast/src/nodes.rs
  crates/ruff_python_parser/Cargo.toml
  crates/ruff_python_parser/src/lib.rs
  crates/ruff_python_parser/src/python.lalrpop
  crates/ruff_python_parser/src/python.rs
  crates/ruff_python_parser/src/string.rs
Labels: parser

#9793 RUF022, RUF023: Ensure closing parentheses for multiline sequences are always on their own line
  crates/ruff_linter/resources/test/fixtures/ruff/RUF022.py
  crates/ruff_linter/resources/test/fixtures/ruff/RUF023.py
  crates/ruff_linter/src/rules/ruff/rules/sequence_sorting.rs
  crates/ruff_linter/src/rules/ruff/snapshots/ruff_linter__rules__ruff__tests__RUF022_RUF022.py.snap
  crates/ruff_linter/src/rules/ruff/snapshots/ruff_linter__rules__ruff__tests__RUF023_RUF023.py.snap
Labels: rule

#9917 Run `cargo update`
  Cargo.lock
Labels: internal

#9599 Allow arbitrary configuration options to be overridden via the CLI
  Cargo.lock
  crates/ruff/Cargo.toml
  crates/ruff/src/args.rs
  crates/ruff/src/commands/add_noqa.rs
  crates/ruff/src/commands/check.rs
  crates/ruff/src/commands/check_stdin.rs
  crates/ruff/src/commands/format.rs
  crates/ruff/src/commands/format_stdin.rs
  crates/ruff/src/commands/show_files.rs
  crates/ruff/src/commands/show_settings.rs
  crates/ruff/src/lib.rs
  crates/ruff/src/resolve.rs
  crates/ruff/tests/format.rs
  crates/ruff/tests/lint.rs
  crates/ruff_dev/src/format_dev.rs
  crates/ruff_linter/src/settings/types.rs
  crates/ruff_wasm/src/lib.rs
  crates/ruff_workspace/src/configuration.rs
  crates/ruff_workspace/src/options.rs
  crates/ruff_workspace/src/resolver.rs
  docs/configuration.md
Labels: cli

#9921 Migrate to `nextest`
  .github/workflows/ci.yaml
  CONTRIBUTING.md
Labels: internal

#9924 docs: add mdformat-ruff to integrations.md
  docs/integrations.md
Labels: documentation

#9929 Fixed nextest install line in CONTRIBUTING.md
  CONTRIBUTING.md
Labels: documentation

#9939 Run doctests as part of CI pipeline
  .config/nextest.toml
  .github/workflows/ci.yaml
  crates/ruff_benchmark/Cargo.toml
  crates/ruff_diagnostics/Cargo.toml
  crates/ruff_index/Cargo.toml
  crates/ruff_macros/src/lib.rs
  crates/ruff_notebook/Cargo.toml
  crates/ruff_python_codegen/Cargo.toml
  crates/ruff_python_formatter/Cargo.toml
  crates/ruff_python_index/Cargo.toml
  crates/ruff_python_literal/Cargo.toml
  crates/ruff_python_resolver/Cargo.toml
  crates/ruff_python_semantic/Cargo.toml
  crates/ruff_wasm/Cargo.toml
Labels: ci

#9922 Stabilize quote-style `preserve`
  crates/ruff_python_formatter/src/options.rs
  crates/ruff_python_formatter/src/other/string_literal.rs
  crates/ruff_python_formatter/src/string/mod.rs
  crates/ruff_python_formatter/tests/snapshots/format@quote_style.py.snap
  crates/ruff_workspace/src/configuration.rs
  crates/ruff_workspace/src/options.rs
  ruff.schema.json
Labels: cli, formatter

#9915 Docstring formatting: Preserve tab indentation when using `indent-style=tabs`
  crates/ruff_python_formatter/resources/test/fixtures/ruff/.editorconfig
  crates/ruff_python_formatter/resources/test/fixtures/ruff/docstring_tab_indentation.options.json
  crates/ruff_python_formatter/resources/test/fixtures/ruff/docstring_tab_indentation.py
  crates/ruff_python_formatter/src/string/docstring.rs
  crates/ruff_python_formatter/tests/snapshots/format@docstring_tab_indentation.py.snap
Labels: formatter

#9952 [`flake8-pyi`] Ignore 'unused' private type dicts in class scopes
  crates/ruff_linter/resources/test/fixtures/flake8_pyi/PYI049.py
  crates/ruff_linter/resources/test/fixtures/flake8_pyi/PYI049.pyi
  crates/ruff_linter/src/checkers/ast/analyze/deferred_scopes.rs
  crates/ruff_linter/src/rules/flake8_pyi/snapshots/ruff_linter__rules__flake8_pyi__tests__PYI049_PYI049.py.snap
  crates/ruff_linter/src/rules/flake8_pyi/snapshots/ruff_linter__rules__flake8_pyi__tests__PYI049_PYI049.pyi.snap
Labels: rule

#9955 [`perflint`] Catch a wider range of mutations in `PERF101`
  crates/ruff_linter/resources/test/fixtures/perflint/PERF101.py
  crates/ruff_linter/src/rules/perflint/rules/unnecessary_list_cast.rs
  crates/ruff_linter/src/rules/perflint/snapshots/ruff_linter__rules__perflint__tests__PERF101_PERF101.py.snap
  crates/ruff_python_ast/src/helpers.rs
Labels: bug

#9953 Use non-parenthesized range for `DebugText`
  crates/ruff_python_codegen/src/generator.rs
  crates/ruff_python_parser/src/parser.rs
  crates/ruff_python_parser/src/python.lalrpop
  crates/ruff_python_parser/src/python.rs
  crates/ruff_python_parser/src/snapshots/ruff_python_parser__parser__tests__fstrings.snap
Labels: bug, parser

#9956 [`pylint`] Avoid suggesting set rewrites for non-hashable types
  crates/ruff_linter/resources/test/fixtures/pylint/literal_membership.py
  crates/ruff_linter/src/rules/pylint/rules/literal_membership.rs
  crates/ruff_linter/src/rules/pylint/snapshots/ruff_linter__rules__pylint__tests__PLR6201_literal_membership.py.snap
  crates/ruff_python_semantic/src/analyze/typing.rs
Labels: bug

#9957 Disable top-level docstring formatting for notebooks
  crates/ruff_python_formatter/resources/test/fixtures/ruff/notebook_docstring.options.json
  crates/ruff_python_formatter/resources/test/fixtures/ruff/notebook_docstring.py
  crates/ruff_python_formatter/src/range.rs
  crates/ruff_python_formatter/src/statement/suite.rs
  crates/ruff_python_formatter/tests/snapshots/format@notebook_docstring.py.snap
Labels: bug, formatter, notebook

#9959 Rename semantic model flag to `MODULE_DOCSTRING_BOUNDARY`
  crates/ruff_linter/src/checkers/ast/mod.rs
  crates/ruff_python_semantic/src/model.rs
Labels: internal

#9963 unused_imports/F401: Explain when imports are preserved
  crates/ruff/tests/snapshots/integration_test__explain_status_codes_f401.snap
  crates/ruff_linter/src/rules/pyflakes/rules/unused_import.rs
Labels: documentation

#9964 `PLR2004`: Accept 0.0 and 1.0 as common magic values
  crates/ruff_linter/resources/test/fixtures/pylint/magic_value_comparison.py
  crates/ruff_linter/src/rules/pylint/rules/magic_value_comparison.rs
  crates/ruff_linter/src/rules/pylint/snapshots/ruff_linter__rules__pylint__tests__PLR2004_magic_value_comparison.py.snap
  crates/ruff_linter/src/rules/pylint/snapshots/ruff_linter__rules__pylint__tests__allow_magic_value_types.snap
Labels: bug

#9968 Remove symbol from type-matching API
  crates/ruff_linter/src/rules/flake8_async/rules/open_sleep_or_subprocess_call.rs
  crates/ruff_linter/src/rules/flake8_simplify/rules/enumerate_for_loop.rs
  crates/ruff_python_semantic/src/analyze/typing.rs
Labels: internal

#9880 [`refurb`] Implement `readlines_in_for` lint (FURB129)
  crates/ruff_linter/resources/test/fixtures/refurb/FURB129.py
  crates/ruff_linter/src/checkers/ast/analyze/comprehension.rs
  crates/ruff_linter/src/checkers/ast/analyze/statement.rs
  crates/ruff_linter/src/codes.rs
  crates/ruff_linter/src/rules/refurb/mod.rs
  crates/ruff_linter/src/rules/refurb/rules/mod.rs
  crates/ruff_linter/src/rules/refurb/rules/readlines_in_for.rs
  crates/ruff_linter/src/rules/refurb/snapshots/ruff_linter__rules__refurb__tests__FURB129_FURB129.py.snap
  crates/ruff_python_semantic/src/analyze/typing.rs
  ruff.schema.json
Labels: rule

#9700 Don't forget to set your cpu to performance mode
  CONTRIBUTING.md
Labels: internal

#9960 Make semantic model aware of docstring
  crates/ruff_linter/src/checkers/ast/mod.rs
  crates/ruff_python_semantic/src/model.rs
Labels: docstring

#9969 Respect tuple assignments in typing analyzer
  crates/ruff_linter/resources/test/fixtures/refurb/FURB129.py
  crates/ruff_linter/src/rules/refurb/snapshots/ruff_linter__rules__refurb__tests__FURB129_FURB129.py.snap
  crates/ruff_python_semantic/src/analyze/typing.rs
Labels: bug

#9970 Run isort CRLF tests
  crates/ruff_linter/src/rules/isort/mod.rs
  crates/ruff_linter/src/rules/isort/snapshots/ruff_linter__rules__isort__tests__line_ending_crlf.py.snap
  crates/ruff_linter/src/rules/isort/snapshots/ruff_linter__rules__isort__tests__line_ending_lf.py.snap
Labels: internal

#9973 Add example demonstrating that `fmt: skip` on expression level is not supported
  docs/formatter.md
Labels: documentation

#9976 Expand `asyncio-dangling-task` (`RUF006`) to include `new_event_loop`
  crates/ruff_linter/resources/test/fixtures/ruff/RUF006.py
  crates/ruff_linter/src/rules/ruff/rules/asyncio_dangling_task.rs
  crates/ruff_linter/src/rules/ruff/snapshots/ruff_linter__rules__ruff__tests__RUF006_RUF006.py.snap
Labels: rule

#9979 Use name directly in RUF006
  crates/ruff_linter/src/rules/ruff/rules/asyncio_dangling_task.rs
Labels: internal

#9981 Use atomic write when persisting cache
  crates/ruff/Cargo.toml
  crates/ruff/src/cache.rs
Labels: bug, cli

#9987 split string module
  crates/ruff_python_formatter/src/string/any.rs
  crates/ruff_python_formatter/src/string/docstring.rs
  crates/ruff_python_formatter/src/string/mod.rs
  crates/ruff_python_formatter/src/string/normalize.rs
Labels: internal

#9996 Fix SIM113 false positive with async for loops
  crates/ruff_linter/resources/test/fixtures/flake8_simplify/SIM113.py
  crates/ruff_linter/src/rules/flake8_simplify/rules/enumerate_for_loop.rs
Labels: bug

#9642 Preview minimal f-string formatting
  crates/ruff_python_formatter/resources/test/fixtures/ruff/expression/fstring.options.json
  crates/ruff_python_formatter/resources/test/fixtures/ruff/expression/fstring.py
  crates/ruff_python_formatter/resources/test/fixtures/ruff/expression/fstring_py312.options.json
  crates/ruff_python_formatter/resources/test/fixtures/ruff/expression/fstring_py312.py
  crates/ruff_python_formatter/src/builders.rs
  crates/ruff_python_formatter/src/comments/placement.rs
  crates/ruff_python_formatter/src/context.rs
  crates/ruff_python_formatter/src/expression/expr_f_string.rs
  crates/ruff_python_formatter/src/options.rs
  crates/ruff_python_formatter/src/other/f_string.rs
  crates/ruff_python_formatter/src/other/f_string_element.rs
  crates/ruff_python_formatter/src/other/mod.rs
  crates/ruff_python_formatter/src/preview.rs
  crates/ruff_python_formatter/src/string/mod.rs
  crates/ruff_python_formatter/src/string/normalize.rs
  crates/ruff_python_formatter/src/verbatim.rs
  crates/ruff_python_formatter/tests/snapshots/black_compatibility@cases__preview_long_strings.py.snap
  crates/ruff_python_formatter/tests/snapshots/black_compatibility@cases__preview_long_strings__regression.py.snap
  crates/ruff_python_formatter/tests/snapshots/format@expression__fstring.py.snap
  crates/ruff_python_formatter/tests/snapshots/format@expression__fstring_py312.py.snap
Labels: formatter, preview

#9990 Fix panic on RUF027
  crates/ruff_linter/resources/test/fixtures/ruff/RUF027_0.py
  crates/ruff_linter/resources/test/fixtures/ruff/RUF027_2.py
  crates/ruff_linter/src/rules/ruff/mod.rs
  crates/ruff_linter/src/rules/ruff/rules/missing_fstring_syntax.rs
  crates/ruff_linter/src/rules/ruff/snapshots/ruff_linter__rules__ruff__tests__RUF027_RUF027_0.py.snap
  crates/ruff_linter/src/rules/ruff/snapshots/ruff_linter__rules__ruff__tests__RUF027_RUF027_2.py.snap
Labels: bug

#10007 docs: Formatter compatibility warning for D207 and D300
  crates/ruff_linter/src/rules/pydocstyle/rules/indent.rs
  crates/ruff_linter/src/rules/pydocstyle/rules/triple_quotes.rs
Labels: documentation

#9993 Move `RUF001`, `RUF002` to AST checker
  crates/ruff_linter/src/checkers/ast/analyze/string_like.rs
  crates/ruff_linter/src/checkers/tokens.rs
  crates/ruff_linter/src/registry.rs
  crates/ruff_linter/src/rules/ruff/rules/ambiguous_unicode_character.rs
Labels: internal

#10018 Bump version to v0.2.2
  CHANGELOG.md
  Cargo.lock
  README.md
  crates/ruff/Cargo.toml
  crates/ruff_linter/Cargo.toml
  crates/ruff_shrinking/Cargo.toml
  docs/integrations.md
  pyproject.toml
  scripts/benchmarks/pyproject.toml
Labels: release

#10027 Allow boolean positionals in `__post_init__`
  crates/ruff_linter/resources/test/fixtures/flake8_boolean_trap/FBT.py
  crates/ruff_linter/src/rules/flake8_boolean_trap/helpers.rs
Labels: bug

#10048 Add Micha as owner to formatter and parser
  .github/CODEOWNERS
Labels: internal

#10049 Do multiline string test for W293 too
  crates/ruff_linter/resources/test/fixtures/pycodestyle/W293.py
  crates/ruff_linter/src/rules/pycodestyle/rules/trailing_whitespace.rs
  crates/ruff_linter/src/rules/pycodestyle/snapshots/ruff_linter__rules__pycodestyle__tests__W293_W293.py.snap
Labels: bug

#9845 [`pylint`] Add PLE1141 `DictIterMissingItems`
  crates/ruff_linter/resources/test/fixtures/pylint/dict_iter_missing_items.py
  crates/ruff_linter/src/checkers/ast/analyze/statement.rs
  crates/ruff_linter/src/codes.rs
  crates/ruff_linter/src/rules/pylint/mod.rs
  crates/ruff_linter/src/rules/pylint/rules/dict_iter_missing_items.rs
  crates/ruff_linter/src/rules/pylint/rules/mod.rs
  crates/ruff_linter/src/rules/pylint/snapshots/ruff_linter__rules__pylint__tests__PLE1141_dict_iter_missing_items.py.snap
  ruff.schema.json
Labels: rule

#10064 Fix ecosystem
  .github/workflows/ci.yaml
Labels: ci

#10057 feat(ERA001): detect single-line code for try:, except:, etc.
  crates/ruff_linter/resources/test/fixtures/eradicate/ERA001.py
  crates/ruff_linter/src/rules/eradicate/detection.rs
  crates/ruff_linter/src/rules/eradicate/snapshots/ruff_linter__rules__eradicate__tests__ERA001_ERA001.py.snap
Labels: rule

#10066 [`pycodestyle`] Allow `os.environ` modifications between imports (`E402`)
  crates/ruff_linter/resources/test/fixtures/pycodestyle/E402_2.py
  crates/ruff_linter/src/checkers/ast/mod.rs
  crates/ruff_linter/src/rules/pycodestyle/mod.rs
  crates/ruff_linter/src/rules/pycodestyle/rules/module_import_not_at_top_of_file.rs
  crates/ruff_linter/src/rules/pycodestyle/snapshots/ruff_linter__rules__pycodestyle__tests__E402_E402_2.py.snap
  crates/ruff_linter/src/rules/pycodestyle/snapshots/ruff_linter__rules__pycodestyle__tests__preview__E402_E402_2.py.snap
  crates/ruff_python_semantic/src/analyze/imports.rs
Labels: rule, preview

#10054 Omit repeated equality comparison for sys
  crates/ruff_linter/resources/test/fixtures/pylint/repeated_equality_comparison.py
  crates/ruff_linter/src/rules/pylint/rules/repeated_equality_comparison.rs
Labels: bug

#10075 Added Image Augmentation library Albumentations (13k stars) to Readme to "Who is using Ruff" section
  README.md
Labels: internal

#10065 Allow © in copyright notices
  crates/ruff/tests/snapshots/show_settings__display_default_settings.snap
  crates/ruff_linter/src/rules/flake8_copyright/mod.rs
  crates/ruff_linter/src/rules/flake8_copyright/settings.rs
  crates/ruff_linter/src/rules/flake8_copyright/snapshots/ruff_linter__rules__flake8_copyright__tests__notice_with_unicode_c.snap
  crates/ruff_workspace/src/options.rs
  ruff.schema.json
Labels: bug

#10091 Respect runtime-required decorators for function signatures
  crates/ruff_linter/src/checkers/ast/annotation.rs
  crates/ruff_linter/src/checkers/ast/mod.rs
  crates/ruff_linter/src/rules/flake8_type_checking/snapshots/ruff_linter__rules__flake8_type_checking__tests__typing-only-standard-library-import_runtime_evaluated_decorators_3.py.snap
Labels: bug

#10080 Set PowerPC Page Size to 64KB
  .github/workflows/release.yaml
Labels: bug

#10100 Refactor trailing comma rule into explicit check and state update code
  crates/ruff_linter/src/rules/flake8_commas/rules/trailing_commas.rs
Labels: internal

#10104 Upgrade upload/download artifact actions in CI.yaml workflow
  .github/workflows/ci.yaml
Labels: ci

#10119 FString formatting: remove fstring handling in `normalize_string`
  crates/ruff_python_formatter/src/other/f_string_element.rs
  crates/ruff_python_formatter/src/string/normalize.rs
Labels: internal

#10118 [`ruff`] Avoid f-string false positives in `gettext` calls (`RUF027`)
  crates/ruff_linter/resources/test/fixtures/ruff/RUF027_1.py
  crates/ruff_linter/src/rules/ruff/rules/missing_fstring_syntax.rs
Labels: bug

#10121 Add cold attribute to less likely printer queue branches
  crates/ruff_formatter/src/printer/queue.rs
Labels: performance, formatter

#10105 Upgrade upload/download artifact actions in release workflow
  .github/workflows/release.yaml
Labels: ci

#10129 Add Alex Waygood as a CODEOWNER for flake8-pyi
  .github/CODEOWNERS
Labels: internal

#10134 Upgrade codspeed-criterion for perf boost
  Cargo.lock
  Cargo.toml
Labels: ci

#10136 docs: fix pycodestyle.max-line-length link
  crates/ruff_workspace/src/options.rs
  ruff.schema.json
Labels: documentation

#10090 Add package name to requirements-insiders.txt
  docs/requirements-insiders.txt
Labels: internal

#10135 Explicitly ban overriding `extend` as part of a --config flag
  crates/ruff/src/args.rs
  crates/ruff/tests/lint.rs
Labels: configuration, cli

#10116 Perf: Skip string normalization when possible
  crates/ruff_python_formatter/src/other/f_string.rs
  crates/ruff_python_formatter/src/other/f_string_element.rs
  crates/ruff_python_formatter/src/string/normalize.rs
Labels: performance, formatter

#10148 [`ruff`] Expand rule for `list(iterable).pop(0)` idiom (`RUF015`)
  crates/ruff_linter/resources/test/fixtures/ruff/RUF015.py
  crates/ruff_linter/src/checkers/ast/analyze/expression.rs
  crates/ruff_linter/src/rules/ruff/rules/unnecessary_iterable_allocation_for_first_element.rs
  crates/ruff_linter/src/rules/ruff/snapshots/ruff_linter__rules__ruff__tests__RUF015_RUF015.py.snap
Labels: rule

#10144 Remove "Beta" Label from formatter documentation
  crates/ruff_python_formatter/README.md
  docs/formatter.md
  playground/src/Editor/SecondarySideBar.tsx
Labels: documentation

#10093 Remove `build` from the default exclusion list
  crates/ruff/tests/snapshots/show_settings__display_default_settings.snap
  crates/ruff_workspace/src/options.rs
  crates/ruff_workspace/src/settings.rs
Labels: breaking, configuration

#10154 [`flake8-bandit`] Remove `suspicious-lxml-import` (`S410`)
  crates/ruff_linter/src/codes.rs
  crates/ruff_linter/src/rules/flake8_bandit/rules/suspicious_imports.rs
  ruff.schema.json
Labels: rule, breaking

#10155 Fix the ecosystem check
  scripts/formatter_ecosystem_checks.sh
Labels: ci

#10152 [`flake8-bugbear`] Avoid adding default initializers to stubs (`B006`)
  crates/ruff_linter/src/rules/flake8_bugbear/rules/mutable_argument_default.rs
  crates/ruff_linter/src/rules/flake8_bugbear/snapshots/ruff_linter__rules__flake8_bugbear__tests__B006_B006_1.py.snap
  crates/ruff_linter/src/rules/flake8_bugbear/snapshots/ruff_linter__rules__flake8_bugbear__tests__B006_B006_2.py.snap
  crates/ruff_linter/src/rules/flake8_bugbear/snapshots/ruff_linter__rules__flake8_bugbear__tests__B006_B006_3.py.snap
  crates/ruff_linter/src/rules/flake8_bugbear/snapshots/ruff_linter__rules__flake8_bugbear__tests__B006_B006_B008.py.snap
  crates/ruff_linter/src/rules/flake8_bugbear/snapshots/ruff_linter__rules__flake8_bugbear__tests__extend_immutable_calls_arg_annotation.snap
Labels: bug

#9899 Implement RUF028 to detect useless formatter suppression comments
  crates/ruff_linter/resources/test/fixtures/ruff/RUF028.py
  crates/ruff_linter/src/checkers/ast/analyze/module.rs
  crates/ruff_linter/src/checkers/noqa.rs
  crates/ruff_linter/src/codes.rs
  crates/ruff_linter/src/fix/edits.rs
  crates/ruff_linter/src/rules/ruff/mod.rs
  crates/ruff_linter/src/rules/ruff/rules/invalid_formatter_suppression_comment.rs
  crates/ruff_linter/src/rules/ruff/rules/mod.rs
  crates/ruff_linter/src/rules/ruff/rules/suppression_comment_visitor.rs
  crates/ruff_linter/src/rules/ruff/snapshots/ruff_linter__rules__ruff__tests__RUF028_RUF028.py.snap
  crates/ruff_python_ast/src/helpers.rs
  crates/ruff_python_ast/src/node.rs
  crates/ruff_python_formatter/src/comments/debug.rs
  crates/ruff_python_formatter/src/comments/format.rs
  crates/ruff_python_formatter/src/comments/mod.rs
  crates/ruff_python_formatter/src/comments/placement.rs
  crates/ruff_python_formatter/src/comments/visitor.rs
  crates/ruff_python_formatter/src/lib.rs
  crates/ruff_python_formatter/src/other/decorator.rs
  crates/ruff_python_formatter/src/other/parameters.rs
  crates/ruff_python_formatter/src/statement/clause.rs
  crates/ruff_python_formatter/src/statement/stmt_ann_assign.rs
  crates/ruff_python_formatter/src/statement/stmt_assert.rs
  crates/ruff_python_formatter/src/statement/stmt_assign.rs
  crates/ruff_python_formatter/src/statement/stmt_aug_assign.rs
  crates/ruff_python_formatter/src/statement/stmt_break.rs
  crates/ruff_python_formatter/src/statement/stmt_continue.rs
  crates/ruff_python_formatter/src/statement/stmt_delete.rs
  crates/ruff_python_formatter/src/statement/stmt_expr.rs
  crates/ruff_python_formatter/src/statement/stmt_global.rs
  crates/ruff_python_formatter/src/statement/stmt_import.rs
  crates/ruff_python_formatter/src/statement/stmt_import_from.rs
  crates/ruff_python_formatter/src/statement/stmt_ipy_escape_command.rs
  crates/ruff_python_formatter/src/statement/stmt_nonlocal.rs
  crates/ruff_python_formatter/src/statement/stmt_pass.rs
  crates/ruff_python_formatter/src/statement/stmt_raise.rs
  crates/ruff_python_formatter/src/statement/stmt_return.rs
  crates/ruff_python_formatter/src/statement/stmt_type_alias.rs
  crates/ruff_python_trivia/src/comments.rs
  crates/ruff_python_trivia/src/lib.rs
  ruff.schema.json
Labels: rule, preview

#9639 Ruff 2024.2 style
  crates/ruff/tests/format.rs
  crates/ruff_python_formatter/src/comments/format.rs
  crates/ruff_python_formatter/src/context.rs
  crates/ruff_python_formatter/src/expression/binary_like.rs
  crates/ruff_python_formatter/src/other/arguments.rs
  crates/ruff_python_formatter/src/other/f_string_element.rs
  crates/ruff_python_formatter/src/other/with_item.rs
  crates/ruff_python_formatter/src/preview.rs
  crates/ruff_python_formatter/src/statement/clause.rs
  crates/ruff_python_formatter/src/statement/stmt_ann_assign.rs
  crates/ruff_python_formatter/src/statement/stmt_assign.rs
  crates/ruff_python_formatter/src/statement/stmt_aug_assign.rs
  crates/ruff_python_formatter/src/statement/stmt_type_alias.rs
  crates/ruff_python_formatter/src/statement/stmt_with.rs
  crates/ruff_python_formatter/src/statement/suite.rs
  crates/ruff_python_formatter/src/string/normalize.rs
  crates/ruff_python_formatter/tests/snapshots/black_compatibility@cases__comments5.py.snap
  crates/ruff_python_formatter/tests/snapshots/black_compatibility@cases__fmtonoff.py.snap
  crates/ruff_python_formatter/tests/snapshots/black_compatibility@cases__fmtonoff5.py.snap
  crates/ruff_python_formatter/tests/snapshots/black_compatibility@cases__function.py.snap
  crates/ruff_python_formatter/tests/snapshots/black_compatibility@cases__long_strings_flag_disabled.py.snap
  crates/ruff_python_formatter/tests/snapshots/black_compatibility@cases__pep_572_remove_parens.py.snap
  crates/ruff_python_formatter/tests/snapshots/black_compatibility@cases__power_op_newline.py.snap
  crates/ruff_python_formatter/tests/snapshots/black_compatibility@cases__python39.py.snap
  crates/ruff_python_formatter/tests/snapshots/black_compatibility@cases__stub.pyi.snap
  crates/ruff_python_formatter/tests/snapshots/black_compatibility@cases__torture.py.snap
  crates/ruff_python_formatter/tests/snapshots/black_compatibility@miscellaneous__force_pyi.py.snap
  crates/ruff_python_formatter/tests/snapshots/black_compatibility@miscellaneous__force_pyi.pyi.snap
  crates/ruff_python_formatter/tests/snapshots/black_compatibility@raw_docstring.py.snap
  crates/ruff_python_formatter/tests/snapshots/format@docstring_code_examples.py.snap
  crates/ruff_python_formatter/tests/snapshots/format@expression__optional_parentheses_comments.py.snap
  crates/ruff_python_formatter/tests/snapshots/format@expression__string.py.snap
  crates/ruff_python_formatter/tests/snapshots/format@fmt_on_off__trailing_comments.py.snap
  crates/ruff_python_formatter/tests/snapshots/format@multiline_string_deviations.py.snap
  crates/ruff_python_formatter/tests/snapshots/format@newlines.py.snap
  crates/ruff_python_formatter/tests/snapshots/format@notebook_docstring.py.snap
  crates/ruff_python_formatter/tests/snapshots/format@preview.py.snap
  crates/ruff_python_formatter/tests/snapshots/format@quote_style.py.snap
  crates/ruff_python_formatter/tests/snapshots/format@statement__ann_assign.py.snap
  crates/ruff_python_formatter/tests/snapshots/format@statement__assign.py.snap
  crates/ruff_python_formatter/tests/snapshots/format@statement__class_definition.py.snap
  crates/ruff_python_formatter/tests/snapshots/format@statement__function.py.snap
  crates/ruff_python_formatter/tests/snapshots/format@statement__long_type_annotations.py.snap
  crates/ruff_python_formatter/tests/snapshots/format@statement__return_annotation.py.snap
  crates/ruff_python_formatter/tests/snapshots/format@statement__top_level.py.snap
  crates/ruff_python_formatter/tests/snapshots/format@statement__with.py.snap
  crates/ruff_python_formatter/tests/snapshots/format@stub_files__suite.pyi.snap
Labels: breaking, formatter

#10164 Fix ecosystem check for indico
  python/ruff-ecosystem/ruff_ecosystem/defaults.py
Labels: ci

#10167 Fix mkdocs local link
  CONTRIBUTING.md
Labels: internal

#10162 [`pydocstyle`] Trim whitespace when removing blank lines after section (`D413`)
  crates/ruff_linter/resources/test/fixtures/pydocstyle/D413.py
  crates/ruff_linter/src/rules/pydocstyle/rules/sections.rs
  crates/ruff_linter/src/rules/pydocstyle/snapshots/ruff_linter__rules__pydocstyle__tests__D413_D413.py.snap
  crates/ruff_linter/src/rules/pydocstyle/snapshots/ruff_linter__rules__pydocstyle__tests__D413_sections.py.snap
Labels: fixes

#10169 Deprecate `ruff <path>` `ruff --explain`, `ruff --clean` and `ruff --generate-shell-completion`
  crates/ruff/src/lib.rs
  crates/ruff/src/main.rs
  crates/ruff/tests/deprecation.rs
  crates/ruff/tests/integration_test.rs
  crates/ruff/tests/lint.rs
  crates/ruff/tests/snapshots/integration_test__rule_f401.snap
Labels: breaking, cli

#10170 Remove deprecated CLI option `--format`
  crates/ruff/src/args.rs
  crates/ruff/src/lib.rs
Labels: breaking, cli

#9961 Use a Discord icon rather than a text link
  README.md
Labels: documentation

#10173 Fix the sorting of the schema submited to schemastore
  scripts/update_schemastore.py
Labels: ci
