Repository astral-sh/ruff, pull requests merged in 2024-01, with the labels that each got.

#9313 [flake8-pyi] Implement PYI058
  crates/ruff_linter/resources/test/fixtures/flake8_pyi/PYI058.py
  crates/ruff_linter/resources/test/fixtures/flake8_pyi/PYI058.pyi
  crates/ruff_linter/src/checkers/ast/analyze/statement.rs
  crates/ruff_linter/src/codes.rs
  crates/ruff_linter/src/rules/flake8_pyi/mod.rs
  crates/ruff_linter/src/rules/flake8_pyi/rules/bad_generator_return_type.rs
  crates/ruff_linter/src/rules/flake8_pyi/rules/mod.rs
  crates/ruff_linter/src/rules/flake8_pyi/snapshots/ruff_linter__rules__flake8_pyi__tests__PYI058_PYI058.py.snap
  crates/ruff_linter/src/rules/flake8_pyi/snapshots/ruff_linter__rules__flake8_pyi__tests__PYI058_PYI058.pyi.snap
  ruff.schema.json
Labels: rule, preview

#9345 Short rule messages should not end with a period
  crates/ruff_linter/src/rules/flake8_comprehensions/rules/unnecessary_comprehension_any_all.rs
  crates/ruff_linter/src/rules/flake8_comprehensions/snapshots/ruff_linter__rules__flake8_comprehensions__tests__C419_C419.py.snap
  crates/ruff_linter/src/rules/ruff/rules/invalid_index_type.rs
  crates/ruff_linter/src/rules/ruff/snapshots/ruff_linter__rules__ruff__tests__RUF016_RUF016.py.snap
Labels: cli

#9347 [S507] fix doc recommended fix
  crates/ruff_linter/src/rules/flake8_bandit/rules/ssh_no_host_key_verification.rs
Labels: bug, documentation

#9346 Fix typos found by codespell
  crates/ruff_linter/resources/test/fixtures/flake8_simplify/SIM117.py
  crates/ruff_linter/resources/test/fixtures/pyupgrade/UP040.py
  crates/ruff_linter/src/rules/flake8_simplify/snapshots/ruff_linter__rules__flake8_simplify__tests__SIM117_SIM117.py.snap
  crates/ruff_linter/src/rules/pyupgrade/snapshots/ruff_linter__rules__pyupgrade__tests__UP040.py.snap
  crates/ruff_python_formatter/resources/test/fixtures/black/cases/line_ranges_basic.py
  crates/ruff_python_formatter/resources/test/fixtures/black/cases/line_ranges_basic.py.expect
  crates/ruff_python_formatter/resources/test/fixtures/black/cases/pep604_union_types_line_breaks.py
  crates/ruff_python_formatter/resources/test/fixtures/black/cases/pep604_union_types_line_breaks.py.expect
  crates/ruff_python_formatter/resources/test/fixtures/import_black_tests.py
  crates/ruff_python_formatter/resources/test/fixtures/ruff/docstring_code_examples.py
  crates/ruff_python_formatter/src/expression/binary_like.rs
  crates/ruff_python_formatter/src/string/mod.rs
  crates/ruff_python_formatter/tests/snapshots/black_compatibility@cases__line_ranges_basic.py.snap
  crates/ruff_python_formatter/tests/snapshots/black_compatibility@cases__pep604_union_types_line_breaks.py.snap
  crates/ruff_python_formatter/tests/snapshots/format@docstring_code_examples.py.snap
Labels: documentation

#9351 Document PERF102 fix unsafety
  crates/ruff_linter/src/rules/perflint/rules/incorrect_dict_iterator.rs
Labels: documentation

#9333 Make all dependencies workspace dependencies
  Cargo.lock
  Cargo.toml
  crates/ruff_benchmark/Cargo.toml
  crates/ruff_cache/Cargo.toml
  crates/ruff_cli/Cargo.toml
  crates/ruff_dev/Cargo.toml
  crates/ruff_formatter/Cargo.toml
  crates/ruff_index/Cargo.toml
  crates/ruff_linter/Cargo.toml
  crates/ruff_notebook/Cargo.toml
  crates/ruff_python_ast/Cargo.toml
  crates/ruff_python_formatter/Cargo.toml
  crates/ruff_python_index/Cargo.toml
  crates/ruff_python_literal/Cargo.toml
  crates/ruff_python_parser/Cargo.toml
  crates/ruff_python_resolver/Cargo.toml
  crates/ruff_shrinking/Cargo.toml
  crates/ruff_text_size/Cargo.toml
  crates/ruff_wasm/Cargo.toml
  crates/ruff_workspace/Cargo.toml
Labels: internal

#9360 Bump version to 0.1.10
  CHANGELOG.md
  Cargo.lock
  README.md
  crates/ruff_cli/Cargo.toml
  crates/ruff_linter/Cargo.toml
  crates/ruff_shrinking/Cargo.toml
  docs/integrations.md
  pyproject.toml
  scripts/benchmarks/pyproject.toml
Labels: release

#9364 Add fix safety note for yield-in-for-loop
  crates/ruff_linter/src/rules/pyupgrade/rules/yield_in_for_loop.rs
Labels: documentation

#9367 Check path string properly
  python/ruff/__main__.py
Labels: bug

#9257 [pylint] - implement `super-without-brackets`/`W0245`
  crates/ruff_linter/resources/test/fixtures/pylint/super_without_brackets.py
  crates/ruff_linter/src/checkers/ast/analyze/expression.rs
  crates/ruff_linter/src/codes.rs
  crates/ruff_linter/src/rules/pylint/mod.rs
  crates/ruff_linter/src/rules/pylint/rules/mod.rs
  crates/ruff_linter/src/rules/pylint/rules/super_without_brackets.rs
  crates/ruff_linter/src/rules/pylint/snapshots/ruff_linter__rules__pylint__tests__PLW0245_super_without_brackets.py.snap
  ruff.schema.json
Labels: rule, preview

#9369 Disable the fuzzer CI job
  .github/workflows/ci.yaml
Labels: ci

#9370 Bump version to 0.1.11
  CHANGELOG.md
  Cargo.lock
  README.md
  crates/ruff_cli/Cargo.toml
  crates/ruff_linter/Cargo.toml
  crates/ruff_shrinking/Cargo.toml
  docs/integrations.md
  pyproject.toml
  scripts/benchmarks/pyproject.toml
Labels: release

#9371 Add CERN/Indico to "Who's Using Ruff?"
  README.md
Labels: documentation

#9375 Minor fuzzer improvements
  fuzz/init-fuzzer.sh
  fuzz/reinit-fuzzer.sh
Labels: fuzzer

#9376 Avoid infinite loop in constant vs. `None` comparisons
  crates/ruff_linter/resources/test/fixtures/pycodestyle/E711.py
  crates/ruff_linter/src/rules/pycodestyle/rules/literal_comparisons.rs
Labels: bug, fuzzer

#9377 Handle raises with implicit alternate branches
  crates/ruff_linter/resources/test/fixtures/flake8_annotations/auto_return_type.py
  crates/ruff_linter/src/rules/flake8_annotations/helpers.rs
  crates/ruff_linter/src/rules/flake8_annotations/snapshots/ruff_linter__rules__flake8_annotations__tests__auto_return_type.snap
  crates/ruff_linter/src/rules/flake8_annotations/snapshots/ruff_linter__rules__flake8_annotations__tests__auto_return_type_py38.snap
  crates/ruff_python_semantic/src/analyze/terminal.rs
Labels: bug

#9382 Respect multi-segment submodule imports when resolving qualified names
  crates/ruff_linter/src/rules/flake8_pyi/snapshots/ruff_linter__rules__flake8_pyi__tests__PYI058_PYI058.py.snap
  crates/ruff_linter/src/rules/flake8_pyi/snapshots/ruff_linter__rules__flake8_pyi__tests__PYI058_PYI058.pyi.snap
  crates/ruff_python_semantic/src/model.rs
Labels: bug

#9383 Misc. small tweaks from perusing modules
  crates/ruff_linter/src/upstream_categories.rs
  crates/ruff_python_ast/src/all.rs
  crates/ruff_python_ast/src/stmt_if.rs
  crates/ruff_python_semantic/src/definition.rs
Labels: internal

#9166 [`pylint`] Implement `unnecessary-dunder-call` (`C2801`)
  crates/ruff_linter/resources/test/fixtures/pylint/unnecessary_dunder_call.py
  crates/ruff_linter/src/checkers/ast/analyze/expression.rs
  crates/ruff_linter/src/codes.rs
  crates/ruff_linter/src/rules/pylint/helpers.rs
  crates/ruff_linter/src/rules/pylint/mod.rs
  crates/ruff_linter/src/rules/pylint/rules/bad_dunder_method_name.rs
  crates/ruff_linter/src/rules/pylint/rules/mod.rs
  crates/ruff_linter/src/rules/pylint/rules/unnecessary_dunder_call.rs
  crates/ruff_linter/src/rules/pylint/snapshots/ruff_linter__rules__pylint__tests__PLC2801_unnecessary_dunder_call.py.snap
  ruff.schema.json
Labels: rule, preview

#8831 [`flake8-bandit`] Implement `S4XX` suspicious import rules
  crates/ruff_linter/resources/test/fixtures/flake8_bandit/S401.py
  crates/ruff_linter/resources/test/fixtures/flake8_bandit/S402.py
  crates/ruff_linter/resources/test/fixtures/flake8_bandit/S403.py
  crates/ruff_linter/resources/test/fixtures/flake8_bandit/S404.py
  crates/ruff_linter/resources/test/fixtures/flake8_bandit/S405.py
  crates/ruff_linter/resources/test/fixtures/flake8_bandit/S406.py
  crates/ruff_linter/resources/test/fixtures/flake8_bandit/S407.py
  crates/ruff_linter/resources/test/fixtures/flake8_bandit/S408.py
  crates/ruff_linter/resources/test/fixtures/flake8_bandit/S409.py
  crates/ruff_linter/resources/test/fixtures/flake8_bandit/S410.py
  crates/ruff_linter/resources/test/fixtures/flake8_bandit/S411.py
  crates/ruff_linter/resources/test/fixtures/flake8_bandit/S412.py
  crates/ruff_linter/resources/test/fixtures/flake8_bandit/S413.py
  crates/ruff_linter/resources/test/fixtures/flake8_bandit/S415.py
  crates/ruff_linter/src/checkers/ast/analyze/statement.rs
  crates/ruff_linter/src/codes.rs
  crates/ruff_linter/src/rules/flake8_bandit/mod.rs
  crates/ruff_linter/src/rules/flake8_bandit/rules/mod.rs
  crates/ruff_linter/src/rules/flake8_bandit/rules/suspicious_imports.rs
  crates/ruff_linter/src/rules/flake8_bandit/snapshots/ruff_linter__rules__flake8_bandit__tests__S401_S401.py.snap
  crates/ruff_linter/src/rules/flake8_bandit/snapshots/ruff_linter__rules__flake8_bandit__tests__S402_S402.py.snap
  crates/ruff_linter/src/rules/flake8_bandit/snapshots/ruff_linter__rules__flake8_bandit__tests__S403_S403.py.snap
  crates/ruff_linter/src/rules/flake8_bandit/snapshots/ruff_linter__rules__flake8_bandit__tests__S404_S404.py.snap
  crates/ruff_linter/src/rules/flake8_bandit/snapshots/ruff_linter__rules__flake8_bandit__tests__S405_S405.py.snap
  crates/ruff_linter/src/rules/flake8_bandit/snapshots/ruff_linter__rules__flake8_bandit__tests__S406_S406.py.snap
  crates/ruff_linter/src/rules/flake8_bandit/snapshots/ruff_linter__rules__flake8_bandit__tests__S407_S407.py.snap
  crates/ruff_linter/src/rules/flake8_bandit/snapshots/ruff_linter__rules__flake8_bandit__tests__S408_S408.py.snap
  crates/ruff_linter/src/rules/flake8_bandit/snapshots/ruff_linter__rules__flake8_bandit__tests__S409_S409.py.snap
  crates/ruff_linter/src/rules/flake8_bandit/snapshots/ruff_linter__rules__flake8_bandit__tests__S410_S410.py.snap
  crates/ruff_linter/src/rules/flake8_bandit/snapshots/ruff_linter__rules__flake8_bandit__tests__S411_S411.py.snap
  crates/ruff_linter/src/rules/flake8_bandit/snapshots/ruff_linter__rules__flake8_bandit__tests__S412_S412.py.snap
  crates/ruff_linter/src/rules/flake8_bandit/snapshots/ruff_linter__rules__flake8_bandit__tests__S413_S413.py.snap
  crates/ruff_linter/src/rules/flake8_bandit/snapshots/ruff_linter__rules__flake8_bandit__tests__S415_S415.py.snap
  ruff.schema.json
Labels: rule, preview

#9384 [`flake8-bandit`] Add `S504` `SslWithNoVersion` rule
  crates/ruff_linter/resources/test/fixtures/flake8_bandit/S504.py
  crates/ruff_linter/src/checkers/ast/analyze/expression.rs
  crates/ruff_linter/src/codes.rs
  crates/ruff_linter/src/registry/rule_set.rs
  crates/ruff_linter/src/rules/flake8_bandit/mod.rs
  crates/ruff_linter/src/rules/flake8_bandit/rules/mod.rs
  crates/ruff_linter/src/rules/flake8_bandit/rules/ssl_with_no_version.rs
  crates/ruff_linter/src/rules/flake8_bandit/rules/suspicious_imports.rs
  crates/ruff_linter/src/rules/flake8_bandit/snapshots/ruff_linter__rules__flake8_bandit__tests__S504_S504.py.snap
  ruff.schema.json
Labels: rule, preview

#9385 [docs] - Fix admonition hyperlink colouring
  docs/stylesheets/extra.css
Labels: documentation

#9386 Add missing preview link
  crates/ruff_linter/src/rules/pycodestyle/rules/imports.rs
Labels: documentation

#9387 Add cell indexes to all diagnostics
  crates/ruff_linter/resources/test/fixtures/pyflakes/F402.ipynb
  crates/ruff_linter/src/checkers/ast/analyze/deferred_scopes.rs
  crates/ruff_linter/src/checkers/ast/mod.rs
  crates/ruff_linter/src/linter.rs
  crates/ruff_linter/src/rules/pyflakes/mod.rs
  crates/ruff_linter/src/rules/pyflakes/rules/imports.rs
  crates/ruff_linter/src/rules/pyflakes/rules/redefined_while_unused.rs
  crates/ruff_linter/src/rules/pyflakes/snapshots/ruff_linter__rules__pyflakes__tests__F402_F402.ipynb.snap
  crates/ruff_linter/src/rules/pylint/rules/load_before_global_declaration.rs
  crates/ruff_source_file/src/lib.rs
Labels: bug

#9359 Generate deterministic ids when formatting notebooks
  Cargo.lock
  crates/ruff_notebook/Cargo.toml
  crates/ruff_notebook/src/notebook.rs
Labels: formatter

#9392 Fix `ibis` ecosystem branch
  python/ruff-ecosystem/ruff_ecosystem/defaults.py
Labels: ci

#9293 Add jupyter notebooks to ecosystem checks
  python/ruff-ecosystem/ruff_ecosystem/defaults.py
Labels: ci

#9395 Allow `# fmt: skip` with interspersed same-line comments
  crates/ruff_python_formatter/resources/test/fixtures/ruff/fmt_skip/reason.py
  crates/ruff_python_formatter/src/comments/mod.rs
  crates/ruff_python_formatter/tests/snapshots/black_compatibility@cases__preview_single_line_format_skip_with_multiple_comments.py.snap
  crates/ruff_python_formatter/tests/snapshots/format@fmt_skip__reason.py.snap
Labels: formatter

#9390 [`flake8-bandit`] Implement `S502` `SslInsecureVersion` rule
  crates/ruff_linter/resources/test/fixtures/flake8_bandit/S502.py
  crates/ruff_linter/src/checkers/ast/analyze/expression.rs
  crates/ruff_linter/src/codes.rs
  crates/ruff_linter/src/rules/flake8_bandit/mod.rs
  crates/ruff_linter/src/rules/flake8_bandit/rules/mod.rs
  crates/ruff_linter/src/rules/flake8_bandit/rules/ssl_insecure_version.rs
  crates/ruff_linter/src/rules/flake8_bandit/snapshots/ruff_linter__rules__flake8_bandit__tests__S502_S502.py.snap
  ruff.schema.json
Labels: rule, preview

#9391 [`flake8-bandit`] Implement `S503` `SslWithBadDefaults` rule
  crates/ruff_linter/resources/test/fixtures/flake8_bandit/S503.py
  crates/ruff_linter/src/checkers/ast/analyze/statement.rs
  crates/ruff_linter/src/codes.rs
  crates/ruff_linter/src/rules/flake8_bandit/mod.rs
  crates/ruff_linter/src/rules/flake8_bandit/rules/mod.rs
  crates/ruff_linter/src/rules/flake8_bandit/rules/ssl_with_bad_defaults.rs
  crates/ruff_linter/src/rules/flake8_bandit/snapshots/ruff_linter__rules__flake8_bandit__tests__S503_S503.py.snap
  ruff.schema.json
Labels: rule, preview

#9402 Fix minor typos
  CONTRIBUTING.md
Labels: documentation

#9399 homogenize PLR0914 message to match other PLR 09XX rules and pylint message
  crates/ruff_linter/src/rules/pylint/rules/too_many_locals.rs
  crates/ruff_linter/src/rules/pylint/snapshots/ruff_linter__rules__pylint__tests__too_many_locals.snap
Labels: bug

#9404 Remove an unwrap from `unnecessary_literal_union.rs`
  crates/ruff_linter/src/rules/flake8_pyi/rules/unnecessary_literal_union.rs
  crates/ruff_linter/src/rules/flake8_pyi/rules/unnecessary_type_union.rs
Labels: internal

#9408 Use transformed source code for diagnostic locations
  crates/ruff_cli/src/diagnostics.rs
  crates/ruff_cli/tests/integration_test.rs
  crates/ruff_linter/src/rules/pycodestyle/rules/missing_newline_at_end_of_file.rs
Labels: bug

#9409 Use `DisplayParseError` for stdin parser errors
  crates/ruff_cli/src/diagnostics.rs
  crates/ruff_cli/tests/integration_test.rs
  crates/ruff_linter/src/logging.rs
Labels: bug

#9411 Support variable keys in static dictionary key rule
  crates/ruff_linter/resources/test/fixtures/ruff/RUF011.py
  crates/ruff_linter/src/checkers/ast/analyze/expression.rs
  crates/ruff_linter/src/rules/ruff/rules/static_key_dict_comprehension.rs
  crates/ruff_linter/src/rules/ruff/snapshots/ruff_linter__rules__ruff__tests__RUF011_RUF011.py.snap
  crates/ruff_python_ast/src/helpers.rs
Labels: rule

#9413 Add size hints to string parser
  crates/ruff_python_parser/src/string.rs
Labels: performance

#9414 Use `comment_ranges` for isort directive extraction
  crates/ruff_linter/src/directives.rs
Labels: performance

#9416 Include subscripts and attributes in static key rule
  crates/ruff_linter/resources/test/fixtures/ruff/RUF011.py
  crates/ruff_linter/src/rules/ruff/rules/static_key_dict_comprehension.rs
  crates/ruff_linter/src/rules/ruff/snapshots/ruff_linter__rules__ruff__tests__RUF011_RUF011.py.snap
Labels: rule

#9427 Disambiguate argument descriptors from section headers
  crates/ruff_linter/resources/test/fixtures/pydocstyle/D417.py
  crates/ruff_linter/resources/test/fixtures/pydocstyle/sections.py
  crates/ruff_linter/src/docstrings/sections.rs
  crates/ruff_linter/src/rules/pydocstyle/snapshots/ruff_linter__rules__pydocstyle__tests__D214_sections.py.snap
  crates/ruff_linter/src/rules/pydocstyle/snapshots/ruff_linter__rules__pydocstyle__tests__D407_sections.py.snap
  crates/ruff_linter/src/rules/pydocstyle/snapshots/ruff_linter__rules__pydocstyle__tests__D414_sections.py.snap
  crates/ruff_linter/src/rules/pydocstyle/snapshots/ruff_linter__rules__pydocstyle__tests__d417_google.snap
  crates/ruff_linter/src/rules/pydocstyle/snapshots/ruff_linter__rules__pydocstyle__tests__d417_unspecified.snap
Labels: bug, docstring

#9396 Parenthesize breaking named expressions in match guards
  crates/ruff_python_formatter/resources/test/fixtures/ruff/statement/match.py
  crates/ruff_python_formatter/src/expression/expr_named_expr.rs
  crates/ruff_python_formatter/tests/snapshots/format@statement__match.py.snap
Labels: bug, formatter

#9437 Use Rust 1.75 toolchain
  crates/ruff_cli/src/cache.rs
  crates/ruff_cli/src/commands/rule.rs
  crates/ruff_dev/src/format_dev.rs
  crates/ruff_linter/src/rules/flake8_comprehensions/fixes.rs
  crates/ruff_linter/src/rules/flake8_pie/rules/multiple_starts_ends_with.rs
  crates/ruff_linter/src/rules/flake8_simplify/rules/ast_bool_op.rs
  crates/ruff_linter/src/rules/flake8_simplify/rules/ast_expr.rs
  crates/ruff_linter/src/rules/pylint/rules/bad_str_strip_call.rs
  crates/ruff_linter/src/rules/pyupgrade/rules/native_literals.rs
  crates/ruff_linter/src/rules/pyupgrade/rules/unpacked_list_comprehension.rs
  crates/ruff_linter/src/rules/refurb/rules/isinstance_type_none.rs
  crates/ruff_python_ast/src/imports.rs
  crates/ruff_python_ast/src/nodes.rs
  crates/ruff_python_literal/src/escape.rs
  crates/ruff_python_parser/src/lexer.rs
  crates/ruff_python_resolver/src/import_result.rs
  rust-toolchain.toml
Labels: internal

#9418 Don't flag `redefined-while-unused` in if branches
  crates/ruff_linter/resources/test/fixtures/pyflakes/F811_27.py
  crates/ruff_linter/src/checkers/ast/analyze/deferred_scopes.rs
  crates/ruff_linter/src/rules/pyflakes/mod.rs
  crates/ruff_linter/src/rules/pyflakes/snapshots/ruff_linter__rules__pyflakes__tests__F811_F811_27.py.snap
  crates/ruff_python_semantic/src/model.rs
Labels: rule

#9440 Add rule to enforce parentheses in `a or b and c`
  crates/ruff_linter/resources/test/fixtures/ruff/RUF021.py
  crates/ruff_linter/src/checkers/ast/analyze/expression.rs
  crates/ruff_linter/src/codes.rs
  crates/ruff_linter/src/rules/ruff/mod.rs
  crates/ruff_linter/src/rules/ruff/rules/mod.rs
  crates/ruff_linter/src/rules/ruff/rules/parenthesize_logical_operators.rs
  crates/ruff_linter/src/rules/ruff/snapshots/ruff_linter__rules__ruff__tests__RUF021_RUF021.py.snap
  ruff.schema.json
Labels: rule, preview

#9446 Skip extra settings resolution when namespace packages are empty
  crates/ruff_workspace/src/resolver.rs
Labels: internal

#9445 Add some additional Python 3.12 typing members to `deprecated-import`
  crates/ruff_linter/resources/test/fixtures/pyupgrade/UP035.py
  crates/ruff_linter/src/rules/pyupgrade/rules/deprecated_import.rs
  crates/ruff_linter/src/rules/pyupgrade/snapshots/ruff_linter__rules__pyupgrade__tests__UP035.py.snap
Labels: rule

#9449 [RUF021]: Add an autofix
  crates/ruff_linter/resources/test/fixtures/ruff/RUF021.py
  crates/ruff_linter/src/rules/ruff/rules/parenthesize_logical_operators.rs
  crates/ruff_linter/src/rules/ruff/snapshots/ruff_linter__rules__ruff__tests__RUF021_RUF021.py.snap
Labels: rule, autofix

#9243 Hug multiline-strings preview style
  crates/ruff_formatter/src/printer/mod.rs
  crates/ruff_python_formatter/resources/test/fixtures/ruff/multiline_string_deviations.py
  crates/ruff_python_formatter/src/expression/binary_like.rs
  crates/ruff_python_formatter/src/expression/expr_bin_op.rs
  crates/ruff_python_formatter/src/expression/expr_bytes_literal.rs
  crates/ruff_python_formatter/src/expression/expr_compare.rs
  crates/ruff_python_formatter/src/expression/expr_f_string.rs
  crates/ruff_python_formatter/src/expression/expr_string_literal.rs
  crates/ruff_python_formatter/src/expression/mod.rs
  crates/ruff_python_formatter/src/expression/parentheses.rs
  crates/ruff_python_formatter/src/other/arguments.rs
  crates/ruff_python_formatter/src/preview.rs
  crates/ruff_python_formatter/src/string/mod.rs
  crates/ruff_python_formatter/tests/snapshots/black_compatibility@cases__preview_multiline_strings.py.snap
  crates/ruff_python_formatter/tests/snapshots/format@docstring_code_examples.py.snap
  crates/ruff_python_formatter/tests/snapshots/format@multiline_string_deviations.py.snap
Labels: formatter, preview

#9455 Update Black Tests
  crates/ruff_python_formatter/resources/test/fixtures/black/cases/class_blank_parentheses.py.expect
  crates/ruff_python_formatter/resources/test/fixtures/black/cases/conditional_expression.py
  crates/ruff_python_formatter/resources/test/fixtures/black/cases/conditional_expression.py.expect
  crates/ruff_python_formatter/resources/test/fixtures/black/cases/line_ranges_basic.py
  crates/ruff_python_formatter/resources/test/fixtures/black/cases/line_ranges_basic.py.expect
  crates/ruff_python_formatter/resources/test/fixtures/black/cases/module_docstring_2.py
  crates/ruff_python_formatter/resources/test/fixtures/black/cases/module_docstring_2.py.expect
  crates/ruff_python_formatter/resources/test/fixtures/black/cases/nested_stub.pyi
  crates/ruff_python_formatter/resources/test/fixtures/black/cases/nested_stub.pyi.expect
  crates/ruff_python_formatter/resources/test/fixtures/black/cases/pep604_union_types_line_breaks.py
  crates/ruff_python_formatter/resources/test/fixtures/black/cases/pep604_union_types_line_breaks.py.expect
  crates/ruff_python_formatter/resources/test/fixtures/black/cases/preview_allow_empty_first_line.py
  crates/ruff_python_formatter/resources/test/fixtures/black/cases/preview_allow_empty_first_line.py.expect
  crates/ruff_python_formatter/resources/test/fixtures/black/cases/preview_dummy_implementations.py
  crates/ruff_python_formatter/resources/test/fixtures/black/cases/preview_dummy_implementations.py.expect
  crates/ruff_python_formatter/resources/test/fixtures/black/cases/preview_form_feeds.py.expect
  crates/ruff_python_formatter/resources/test/fixtures/black/cases/preview_no_blank_line_before_docstring.py
  crates/ruff_python_formatter/resources/test/fixtures/black/cases/preview_no_blank_line_before_docstring.py.expect
  crates/ruff_python_formatter/resources/test/fixtures/black/cases/preview_pep_572.py.expect
  crates/ruff_python_formatter/tests/snapshots/black_compatibility@cases__class_blank_parentheses.py.snap
  crates/ruff_python_formatter/tests/snapshots/black_compatibility@cases__conditional_expression.py.snap
  crates/ruff_python_formatter/tests/snapshots/black_compatibility@cases__line_ranges_basic.py.snap
  crates/ruff_python_formatter/tests/snapshots/black_compatibility@cases__module_docstring_2.py.snap
  crates/ruff_python_formatter/tests/snapshots/black_compatibility@cases__nested_stub.pyi.snap
  crates/ruff_python_formatter/tests/snapshots/black_compatibility@cases__pep604_union_types_line_breaks.py.snap
  crates/ruff_python_formatter/tests/snapshots/black_compatibility@cases__preview_allow_empty_first_line.py.snap
  crates/ruff_python_formatter/tests/snapshots/black_compatibility@cases__preview_form_feeds.py.snap
  crates/ruff_python_formatter/tests/snapshots/black_compatibility@cases__preview_pep_572.py.snap
Labels: internal, formatter

#9469 Avoid allocating during implicit concatenated string formatting
  crates/ruff_python_formatter/src/string/mod.rs
Labels: internal, formatter

#9473 docs: fix typo in formatter.md
  docs/formatter.md
Labels: documentation

#9462 Restrict `builtin-attribute-shadowing` to actual shadowed references
  crates/ruff_linter/resources/test/fixtures/flake8_builtins/A003.py
  crates/ruff_linter/src/checkers/ast/analyze/deferred_scopes.rs
  crates/ruff_linter/src/checkers/ast/analyze/expression.rs
  crates/ruff_linter/src/checkers/ast/analyze/statement.rs
  crates/ruff_linter/src/rules/flake8_builtins/rules/builtin_attribute_shadowing.rs
  crates/ruff_linter/src/rules/flake8_builtins/snapshots/ruff_linter__rules__flake8_builtins__tests__A003_A003.py.snap
  crates/ruff_linter/src/rules/flake8_builtins/snapshots/ruff_linter__rules__flake8_builtins__tests__A003_A003.py_builtins_ignorelist.snap
  crates/ruff_python_semantic/src/model.rs
Labels: rule

#9466 Remove type parameter from `parse_*` methods
  crates/ruff_benchmark/benches/linter.rs
  crates/ruff_python_ast/tests/preorder.rs
  crates/ruff_python_ast/tests/visitor.rs
  crates/ruff_python_formatter/src/cli.rs
  crates/ruff_python_formatter/src/comments/mod.rs
  crates/ruff_python_formatter/src/lib.rs
  crates/ruff_python_formatter/src/string/docstring.rs
  crates/ruff_python_index/src/comment_ranges.rs
  crates/ruff_python_parser/src/invalid.rs
  crates/ruff_python_parser/src/lib.rs
  crates/ruff_python_parser/src/parser.rs
  crates/ruff_python_parser/src/token_source.rs
  crates/ruff_python_trivia/src/comment_ranges.rs
Labels: internal, parser

#9460 [`flake8-simplify`] Implement `SIM911`
  crates/ruff_linter/resources/test/fixtures/flake8_simplify/SIM911.py
  crates/ruff_linter/src/checkers/ast/analyze/expression.rs
  crates/ruff_linter/src/codes.rs
  crates/ruff_linter/src/rules/flake8_simplify/rules/mod.rs
  crates/ruff_linter/src/rules/flake8_simplify/rules/zip_dict_keys_and_values.rs
  ruff.schema.json
Labels: rule, preview

#9475 Bump version to v0.1.12
  CHANGELOG.md
  Cargo.lock
  README.md
  crates/ruff_cli/Cargo.toml
  crates/ruff_linter/Cargo.toml
  crates/ruff_shrinking/Cargo.toml
  docs/integrations.md
  pyproject.toml
  scripts/benchmarks/pyproject.toml
Labels: release

#9480 Include base pyproject when initializing cache settings
  crates/ruff_workspace/src/resolver.rs
Labels: bug

#9463 Remove `unreachable-code` feature
  crates/ruff_linter/Cargo.toml
  crates/ruff_linter/resources/test/fixtures/ruff/RUF014.py
  crates/ruff_linter/src/checkers/ast/analyze/statement.rs
  crates/ruff_linter/src/codes.rs
  crates/ruff_linter/src/rule_selector.rs
  crates/ruff_linter/src/rules/ruff/mod.rs
  crates/ruff_linter/src/rules/ruff/rules/mod.rs
  crates/ruff_linter/src/rules/ruff/rules/snapshots/ruff_linter__rules__ruff__rules__unreachable__tests__assert.py.md.snap
  crates/ruff_linter/src/rules/ruff/rules/snapshots/ruff_linter__rules__ruff__rules__unreachable__tests__async-for.py.md.snap
  crates/ruff_linter/src/rules/ruff/rules/snapshots/ruff_linter__rules__ruff__rules__unreachable__tests__for.py.md.snap
  crates/ruff_linter/src/rules/ruff/rules/snapshots/ruff_linter__rules__ruff__rules__unreachable__tests__if.py.md.snap
  crates/ruff_linter/src/rules/ruff/rules/snapshots/ruff_linter__rules__ruff__rules__unreachable__tests__match.py.md.snap
  crates/ruff_linter/src/rules/ruff/rules/snapshots/ruff_linter__rules__ruff__rules__unreachable__tests__raise.py.md.snap
  crates/ruff_linter/src/rules/ruff/rules/snapshots/ruff_linter__rules__ruff__rules__unreachable__tests__simple.py.md.snap
  crates/ruff_linter/src/rules/ruff/rules/snapshots/ruff_linter__rules__ruff__rules__unreachable__tests__while.py.md.snap
  crates/ruff_linter/src/rules/ruff/rules/unreachable.rs
  crates/ruff_linter/src/rules/ruff/snapshots/ruff_linter__rules__ruff__tests__RUF014_RUF014.py.snap
  crates/ruff_workspace/src/configuration.rs
Labels: internal

#9484 Account for possibly-empty f-string values in truthiness logic
  crates/ruff_linter/resources/test/fixtures/flake8_simplify/SIM222.py
  crates/ruff_linter/resources/test/fixtures/flake8_simplify/SIM223.py
  crates/ruff_linter/src/rules/flake8_simplify/snapshots/ruff_linter__rules__flake8_simplify__tests__SIM222_SIM222.py.snap
  crates/ruff_linter/src/rules/flake8_simplify/snapshots/ruff_linter__rules__flake8_simplify__tests__SIM223_SIM223.py.snap
  crates/ruff_python_ast/src/helpers.rs
Labels: bug

#9485 (🐞) Add the missing period in error message
  crates/ruff_linter/src/rules/pylint/rules/unnecessary_dunder_call.rs
Labels: bug

#9492 Fix message for __aenter__ in PLC2801
  crates/ruff_linter/src/rules/pylint/rules/unnecessary_dunder_call.rs
Labels: bug

#9483 Add `--extension` support to the formatter
  crates/ruff_cli/src/args.rs
  crates/ruff_cli/src/commands/format.rs
  crates/ruff_cli/src/commands/format_stdin.rs
  crates/ruff_cli/src/diagnostics.rs
  crates/ruff_cli/tests/format.rs
  crates/ruff_cli/tests/lint.rs
  crates/ruff_linter/src/settings/mod.rs
  crates/ruff_linter/src/settings/types.rs
  crates/ruff_workspace/src/configuration.rs
  crates/ruff_workspace/src/settings.rs
  docs/configuration.md
Labels: cli

#9495 Limit inplace diagnostics to methods that accept inplace
  crates/ruff_linter/resources/test/fixtures/pandas_vet/PD002.py
  crates/ruff_linter/src/rules/pandas_vet/rules/inplace_argument.rs
  crates/ruff_linter/src/rules/pandas_vet/snapshots/ruff_linter__rules__pandas_vet__tests__PD002_PD002.py.snap
Labels: bug

#9464 `--show-settings` displays active settings in a far more readable format
  crates/ruff_cli/src/commands/show_settings.rs
  crates/ruff_cli/tests/show_settings.rs
  crates/ruff_cli/tests/snapshots/show_settings__display_default_settings.snap
  crates/ruff_formatter/src/lib.rs
  crates/ruff_linter/src/line_width.rs
  crates/ruff_linter/src/registry/rule_set.rs
  crates/ruff_linter/src/rules/flake8_annotations/settings.rs
  crates/ruff_linter/src/rules/flake8_bandit/settings.rs
  crates/ruff_linter/src/rules/flake8_bugbear/settings.rs
  crates/ruff_linter/src/rules/flake8_builtins/settings.rs
  crates/ruff_linter/src/rules/flake8_comprehensions/settings.rs
  crates/ruff_linter/src/rules/flake8_copyright/settings.rs
  crates/ruff_linter/src/rules/flake8_errmsg/settings.rs
  crates/ruff_linter/src/rules/flake8_gettext/settings.rs
  crates/ruff_linter/src/rules/flake8_implicit_str_concat/settings.rs
  crates/ruff_linter/src/rules/flake8_import_conventions/settings.rs
  crates/ruff_linter/src/rules/flake8_pytest_style/settings.rs
  crates/ruff_linter/src/rules/flake8_quotes/settings.rs
  crates/ruff_linter/src/rules/flake8_self/settings.rs
  crates/ruff_linter/src/rules/flake8_tidy_imports/settings.rs
  crates/ruff_linter/src/rules/flake8_type_checking/settings.rs
  crates/ruff_linter/src/rules/flake8_unused_arguments/settings.rs
  crates/ruff_linter/src/rules/isort/categorize.rs
  crates/ruff_linter/src/rules/isort/settings.rs
  crates/ruff_linter/src/rules/mccabe/settings.rs
  crates/ruff_linter/src/rules/pep8_naming/settings.rs
  crates/ruff_linter/src/rules/pycodestyle/settings.rs
  crates/ruff_linter/src/rules/pydocstyle/settings.rs
  crates/ruff_linter/src/rules/pyflakes/settings.rs
  crates/ruff_linter/src/rules/pylint/settings.rs
  crates/ruff_linter/src/rules/pyupgrade/settings.rs
  crates/ruff_linter/src/rules/ruff/mod.rs
  crates/ruff_linter/src/settings/fix_safety_table.rs
  crates/ruff_linter/src/settings/mod.rs
  crates/ruff_linter/src/settings/rule_table.rs
  crates/ruff_linter/src/settings/types.rs
  crates/ruff_python_formatter/src/options.rs
  crates/ruff_workspace/src/configuration.rs
  crates/ruff_workspace/src/settings.rs
Labels: cli

#9494 [`ruff`] Avoid treating named expressions as static keys (`RUF011`)
  crates/ruff_linter/resources/test/fixtures/ruff/RUF011.py
  crates/ruff_linter/src/rules/flake8_bugbear/rules/unused_loop_control_variable.rs
  crates/ruff_linter/src/rules/ruff/rules/static_key_dict_comprehension.rs
  crates/ruff_linter/src/rules/ruff/snapshots/ruff_linter__rules__ruff__tests__RUF011_RUF011.py.snap
  crates/ruff_python_ast/src/helpers.rs
Labels: bug

#9496 Ignore unnecessary dunder calls within dunder definitions
  crates/ruff_linter/resources/test/fixtures/pylint/unnecessary_dunder_call.py
  crates/ruff_linter/src/rules/pylint/rules/unnecessary_dunder_call.rs
  crates/ruff_linter/src/rules/pylint/snapshots/ruff_linter__rules__pylint__tests__PLC2801_unnecessary_dunder_call.py.snap
Labels: bug

#9502 fix(docs): admonition in dark mode
  docs/stylesheets/extra.css
Labels: documentation

#9506 Use the `LinterSettings`'s tab size when expanding indent
  crates/ruff_linter/src/checkers/logical_lines.rs
Labels: linter

#9403 update emacs integration section to include `emacs-ruff-format`
  docs/integrations.md
Labels: documentation

#7777 [`flake8-simplify`] Implement `enumerate-for-loop` (`SIM113`)
  crates/ruff_linter/resources/test/fixtures/flake8_simplify/SIM113.py
  crates/ruff_linter/src/checkers/ast/analyze/deferred_for_loops.rs
  crates/ruff_linter/src/checkers/ast/analyze/statement.rs
  crates/ruff_linter/src/codes.rs
  crates/ruff_linter/src/rules/flake8_simplify/mod.rs
  crates/ruff_linter/src/rules/flake8_simplify/rules/ast_bool_op.rs
  crates/ruff_linter/src/rules/flake8_simplify/rules/enumerate_for_loop.rs
  crates/ruff_linter/src/rules/flake8_simplify/rules/mod.rs
  crates/ruff_linter/src/rules/flake8_simplify/snapshots/ruff_linter__rules__flake8_simplify__tests__SIM113_SIM113.py.snap
  crates/ruff_linter/src/rules/flake8_trio/rules/zero_sleep_call.rs
  crates/ruff_python_ast/src/traversal.rs
  crates/ruff_python_semantic/src/analyze/typing.rs
  crates/ruff_python_semantic/src/scope.rs
  ruff.schema.json
Labels: rule, preview

#9515 [`flake8-simplify`] Avoid some more `enumerate-for-loop` false positives (`SIM113`)
  crates/ruff_linter/resources/test/fixtures/flake8_simplify/SIM113.py
  crates/ruff_linter/src/rules/flake8_simplify/rules/enumerate_for_loop.rs
Labels: bug

#9510 [`flake8-bugbear`] Add fix for `duplicate-value` (`B033`)
  crates/ruff_linter/resources/test/fixtures/flake8_bugbear/B033.py
  crates/ruff_linter/src/checkers/ast/analyze/expression.rs
  crates/ruff_linter/src/rules/flake8_bugbear/mod.rs
  crates/ruff_linter/src/rules/flake8_bugbear/rules/duplicate_value.rs
  crates/ruff_linter/src/rules/flake8_bugbear/snapshots/ruff_linter__rules__flake8_bugbear__tests__B033_B033.py.snap
  crates/ruff_linter/src/rules/flake8_bugbear/snapshots/ruff_linter__rules__flake8_bugbear__tests__preview__B033_B033.py.snap
Labels: autofix, preview

#9516 [`refurb`] Implement `regex-flag-alias` with fix (`FURB167`)
  crates/ruff_linter/resources/test/fixtures/refurb/FURB167.py
  crates/ruff_linter/src/checkers/ast/analyze/expression.rs
  crates/ruff_linter/src/codes.rs
  crates/ruff_linter/src/rules/refurb/mod.rs
  crates/ruff_linter/src/rules/refurb/rules/mod.rs
  crates/ruff_linter/src/rules/refurb/rules/regex_flag_alias.rs
  crates/ruff_linter/src/rules/refurb/snapshots/ruff_linter__rules__refurb__tests__FURB167_FURB167.py.snap
  ruff.schema.json
Labels: rule, preview

#9529 add the "__prepare__" method to the list of recognized dunder method
  crates/ruff_linter/resources/test/fixtures/pylint/bad_dunder_method_name.py
  crates/ruff_linter/src/rules/pylint/helpers.rs
Labels: bug

#9530 Bump `tj-actions/changed-files` to v41
  .github/workflows/ci.yaml
Labels: internal

#9533 Move `is_tuple_parenthesized` from the formatter to `ruff_python_ast`
  crates/ruff_python_ast/src/nodes.rs
  crates/ruff_python_formatter/src/comments/placement.rs
  crates/ruff_python_formatter/src/expression/expr_tuple.rs
  crates/ruff_python_formatter/src/expression/mod.rs
Labels: internal

#9535 Update contributing docs to use `cargo bench -p ruff_benchmark`
  CONTRIBUTING.md
  crates/ruff_benchmark/README.md
Labels: documentation

#9540 Visit deferred lambdas before type definitions
  crates/ruff_linter/resources/test/fixtures/pyflakes/F401_21.py
  crates/ruff_linter/src/checkers/ast/mod.rs
  crates/ruff_linter/src/rules/pyflakes/mod.rs
  crates/ruff_linter/src/rules/pyflakes/snapshots/ruff_linter__rules__pyflakes__tests__F401_F401_21.py.snap
Labels: bug

#9538 Ignore preview status for fixable and unfixable selectors
  crates/ruff_cli/tests/integration_test.rs
  crates/ruff_workspace/src/configuration.rs
Labels: bug, configuration

#9519 [`pygrep_hooks`] Add fix for `deprecated-log-warn` (`PGH002`)
  crates/ruff_linter/src/rules/pygrep_hooks/mod.rs
  crates/ruff_linter/src/rules/pygrep_hooks/rules/deprecated_log_warn.rs
  crates/ruff_linter/src/rules/pygrep_hooks/snapshots/ruff_linter__rules__pygrep_hooks__tests__PGH002_PGH002_1.py.snap
  crates/ruff_linter/src/rules/pygrep_hooks/snapshots/ruff_linter__rules__pygrep_hooks__tests__preview__PGH002_PGH002_1.py.snap
Labels: preview

#9520 [`tryceratops`] Add fix for `error-instead-of-exception` (`TRY400`)
  crates/ruff_linter/src/rules/tryceratops/mod.rs
  crates/ruff_linter/src/rules/tryceratops/rules/error_instead_of_exception.rs
  crates/ruff_linter/src/rules/tryceratops/snapshots/ruff_linter__rules__tryceratops__tests__error-instead-of-exception_TRY400.py.snap
  crates/ruff_linter/src/rules/tryceratops/snapshots/ruff_linter__rules__tryceratops__tests__preview__TRY400_TRY400.py.snap
  crates/ruff_python_semantic/src/analyze/logging.rs
Labels: autofix, preview

#5920 [`pylint`] Implement `import-private-name` (`C2701`)
  crates/ruff_linter/__init__.py
  crates/ruff_linter/resources/__init__.py
  crates/ruff_linter/resources/test/__init__.py
  crates/ruff_linter/resources/test/fixtures/__init__.py
  crates/ruff_linter/resources/test/fixtures/pylint/import_private_name/__init__.py
  crates/ruff_linter/resources/test/fixtures/pylint/import_private_name/sibling_module/__init__.py
  crates/ruff_linter/resources/test/fixtures/pylint/import_private_name/submodule/__init__.py
  crates/ruff_linter/resources/test/fixtures/pylint/import_private_name/submodule/__main__.py
  crates/ruff_linter/resources/test/fixtures/pylint/import_private_name/submodule/subsubmodule/__init__.py
  crates/ruff_linter/src/checkers/ast/analyze/deferred_scopes.rs
  crates/ruff_linter/src/codes.rs
  crates/ruff_linter/src/rules/pylint/mod.rs
  crates/ruff_linter/src/rules/pylint/rules/import_private_name.rs
  crates/ruff_linter/src/rules/pylint/rules/mod.rs
  crates/ruff_linter/src/rules/pylint/snapshots/ruff_linter__rules__pylint__tests__PLC2701_import_private_name__submodule____main__.py.snap
  ruff.schema.json
Labels: rule, preview

#9532 Add an explicit fast path for whitespace to `is_identifier_continuation`
  crates/ruff_python_parser/src/lexer.rs
  crates/ruff_python_stdlib/src/identifiers.rs
  crates/ruff_python_trivia/src/tokenizer.rs
Labels: performance, parser

#9547 Revert "[`pylint`] Implement `import-private-name` (`C2701`)"
  crates/ruff_linter/__init__.py
  crates/ruff_linter/resources/__init__.py
  crates/ruff_linter/resources/test/__init__.py
  crates/ruff_linter/resources/test/fixtures/__init__.py
  crates/ruff_linter/resources/test/fixtures/pylint/import_private_name/__init__.py
  crates/ruff_linter/resources/test/fixtures/pylint/import_private_name/sibling_module/__init__.py
  crates/ruff_linter/resources/test/fixtures/pylint/import_private_name/submodule/__init__.py
  crates/ruff_linter/resources/test/fixtures/pylint/import_private_name/submodule/__main__.py
  crates/ruff_linter/resources/test/fixtures/pylint/import_private_name/submodule/subsubmodule/__init__.py
  crates/ruff_linter/src/checkers/ast/analyze/deferred_scopes.rs
  crates/ruff_linter/src/codes.rs
  crates/ruff_linter/src/rules/pylint/mod.rs
  crates/ruff_linter/src/rules/pylint/rules/import_private_name.rs
  crates/ruff_linter/src/rules/pylint/rules/mod.rs
  crates/ruff_linter/src/rules/pylint/snapshots/ruff_linter__rules__pylint__tests__PLC2701_import_private_name__submodule____main__.py.snap
  ruff.schema.json
Labels: rule

#9553 [`pylint`] (Re-)Implement `import-private-name` (`C2701`)
  crates/ruff_linter/__init__.py
  crates/ruff_linter/resources/__init__.py
  crates/ruff_linter/resources/test/__init__.py
  crates/ruff_linter/resources/test/fixtures/__init__.py
  crates/ruff_linter/resources/test/fixtures/pylint/import_private_name/__init__.py
  crates/ruff_linter/resources/test/fixtures/pylint/import_private_name/sibling_module/__init__.py
  crates/ruff_linter/resources/test/fixtures/pylint/import_private_name/submodule/__init__.py
  crates/ruff_linter/resources/test/fixtures/pylint/import_private_name/submodule/__main__.py
  crates/ruff_linter/resources/test/fixtures/pylint/import_private_name/submodule/subsubmodule/__init__.py
  crates/ruff_linter/src/checkers/ast/analyze/deferred_scopes.rs
  crates/ruff_linter/src/codes.rs
  crates/ruff_linter/src/rules/pylint/mod.rs
  crates/ruff_linter/src/rules/pylint/rules/import_private_name.rs
  crates/ruff_linter/src/rules/pylint/rules/mod.rs
  crates/ruff_linter/src/rules/pylint/snapshots/ruff_linter__rules__pylint__tests__PLC2701_import_private_name__submodule____main__.py.snap
  ruff.schema.json
Labels: rule, preview

#9555 Add instructions on using `noqa` with isort rules
  docs/linter.md
Labels: documentation

#9558 Make `ruff` the default binary
  crates/ruff/Cargo.toml
Labels: internal

#9565 Documentation update for URL giving 'page not found'
  CONTRIBUTING.md
Labels: documentation

#9566 [flake8-pyi] Fix PYI047 false negatives on PEP-695 type aliases
  crates/ruff_linter/resources/test/fixtures/flake8_pyi/PYI047.py
  crates/ruff_linter/resources/test/fixtures/flake8_pyi/PYI047.pyi
  crates/ruff_linter/src/rules/flake8_pyi/rules/unused_private_type_definition.rs
  crates/ruff_linter/src/rules/flake8_pyi/snapshots/ruff_linter__rules__flake8_pyi__tests__PYI047_PYI047.py.snap
  crates/ruff_linter/src/rules/flake8_pyi/snapshots/ruff_linter__rules__flake8_pyi__tests__PYI047_PYI047.pyi.snap
Labels: rule

#9563 [`pylint`] Exclude `self` and `cls` when counting method arguments
  crates/ruff_linter/resources/test/fixtures/pylint/too_many_positional.py
  crates/ruff_linter/src/rules/pylint/rules/too_many_positional.rs
  crates/ruff_linter/src/rules/pylint/snapshots/ruff_linter__rules__pylint__tests__PLR0917_too_many_positional.py.snap
Labels: rule

#9567 [flake8-pyi] Fix PYI049 false negatives on call-based TypedDicts
  crates/ruff_linter/resources/test/fixtures/flake8_pyi/PYI049.py
  crates/ruff_linter/resources/test/fixtures/flake8_pyi/PYI049.pyi
  crates/ruff_linter/src/rules/flake8_pyi/rules/unused_private_type_definition.rs
  crates/ruff_linter/src/rules/flake8_pyi/snapshots/ruff_linter__rules__flake8_pyi__tests__PYI049_PYI049.py.snap
  crates/ruff_linter/src/rules/flake8_pyi/snapshots/ruff_linter__rules__flake8_pyi__tests__PYI049_PYI049.pyi.snap
Labels: rule

#9546 Approximate tokens len
  crates/ruff_benchmark/benches/formatter.rs
  crates/ruff_python_index/src/comment_ranges.rs
  crates/ruff_python_parser/src/lib.rs
  crates/ruff_python_parser/src/parser.rs
  crates/ruff_wasm/src/lib.rs
Labels: internal

#9580 [`flake8-blind-except`] Document exceptions to `blind-except` rule
  crates/ruff_linter/src/rules/flake8_blind_except/rules/blind_except.rs
Labels: documentation

#9581 Bump version to v0.1.14
  CHANGELOG.md
  Cargo.lock
  README.md
  crates/ruff/Cargo.toml
  crates/ruff_linter/Cargo.toml
  crates/ruff_shrinking/Cargo.toml
  docs/integrations.md
  pyproject.toml
  scripts/benchmarks/pyproject.toml
Labels: release

#9545 [`pylint`] Implement `potential-index-error` (`PLE0643`)
  crates/ruff_linter/resources/test/fixtures/pylint/potential_index_error.py
  crates/ruff_linter/src/checkers/ast/analyze/expression.rs
  crates/ruff_linter/src/codes.rs
  crates/ruff_linter/src/rules/pylint/mod.rs
  crates/ruff_linter/src/rules/pylint/rules/mod.rs
  crates/ruff_linter/src/rules/pylint/rules/potential_index_error.rs
  crates/ruff_linter/src/rules/pylint/snapshots/ruff_linter__rules__pylint__tests__PLE0643_potential_index_error.py.snap
  ruff.schema.json
Labels: rule, preview

#9593 Always unset the `required-version` option during ecosystem checks
  python/ruff-ecosystem/ruff_ecosystem/projects.py
Labels: internal, ci

#9598 Docs: fix isort rule code
  docs/linter.md
Labels: documentation

#9590 [`pylint`] Add fix for `useless-else-on-loop` (`PLW0120`)
  crates/ruff_linter/resources/test/fixtures/pylint/useless_else_on_loop.py
  crates/ruff_linter/src/rules/pylint/mod.rs
  crates/ruff_linter/src/rules/pylint/rules/useless_else_on_loop.rs
  crates/ruff_linter/src/rules/pylint/snapshots/ruff_linter__rules__pylint__tests__PLW0120_useless_else_on_loop.py.snap
  crates/ruff_linter/src/rules/pylint/snapshots/ruff_linter__rules__pylint__tests__preview__PLW0120_useless_else_on_loop.py.snap
  crates/ruff_linter/src/rules/pyupgrade/mod.rs
Labels: autofix, preview

#9600 Split pycodestyle import rules into separate files
  crates/ruff_linter/src/rules/pycodestyle/rules/mod.rs
  crates/ruff_linter/src/rules/pycodestyle/rules/module_import_not_at_top_of_file.rs
  crates/ruff_linter/src/rules/pycodestyle/rules/multiple_imports_on_one_line.rs
Labels: internal

#9518 [`pycodestyle`] Add fix for `multiple-imports-on-one-line` (`E401`)
  crates/ruff_linter/resources/test/fixtures/pycodestyle/E40.py
  crates/ruff_linter/src/rules/pycodestyle/mod.rs
  crates/ruff_linter/src/rules/pycodestyle/rules/multiple_imports_on_one_line.rs
  crates/ruff_linter/src/rules/pycodestyle/snapshots/ruff_linter__rules__pycodestyle__tests__E401_E40.py.snap
  crates/ruff_linter/src/rules/pycodestyle/snapshots/ruff_linter__rules__pycodestyle__tests__E402_E40.py.snap
  crates/ruff_linter/src/rules/pycodestyle/snapshots/ruff_linter__rules__pycodestyle__tests__preview__E401_E40.py.snap
Labels: autofix, preview

#9603 Include global `--config` when determining namespace packages
  crates/ruff_workspace/src/resolver.rs
Labels: bug

#9597 [`ruff`] Implement `mutable-fromkeys-value` (`RUF024`)
  crates/ruff_linter/resources/test/fixtures/ruff/RUF024.py
  crates/ruff_linter/src/checkers/ast/analyze/expression.rs
  crates/ruff_linter/src/codes.rs
  crates/ruff_linter/src/rules/ruff/mod.rs
  crates/ruff_linter/src/rules/ruff/rules/mod.rs
  crates/ruff_linter/src/rules/ruff/rules/mutable_fromkeys_value.rs
  crates/ruff_linter/src/rules/ruff/snapshots/ruff_linter__rules__ruff__tests__RUF024_RUF024.py.snap
  ruff.schema.json
Labels: rule, preview

#9602 Corrected code block hyperlink
  crates/ruff_linter/src/rules/pylint/rules/import_private_name.rs
Labels: documentation

#9591 [`flake8-simplify`] Add fix for `if-with-same-arms` (`SIM114`)
  crates/ruff_linter/resources/test/fixtures/flake8_simplify/SIM114.py
  crates/ruff_linter/src/checkers/ast/analyze/statement.rs
  crates/ruff_linter/src/rules/flake8_simplify/mod.rs
  crates/ruff_linter/src/rules/flake8_simplify/rules/if_with_same_arms.rs
  crates/ruff_linter/src/rules/flake8_simplify/snapshots/ruff_linter__rules__flake8_simplify__tests__SIM114_SIM114.py.snap
  crates/ruff_linter/src/rules/flake8_simplify/snapshots/ruff_linter__rules__flake8_simplify__tests__preview__SIM114_SIM114.py.snap
Labels: autofix, preview

#9564 Add a rule/autofix to sort `__slots__` and `__match_args__`
  crates/ruff_linter/resources/test/fixtures/ruff/RUF022.py
  crates/ruff_linter/resources/test/fixtures/ruff/RUF023.py
  crates/ruff_linter/src/checkers/ast/analyze/statement.rs
  crates/ruff_linter/src/codes.rs
  crates/ruff_linter/src/rules/ruff/mod.rs
  crates/ruff_linter/src/rules/ruff/rules/mod.rs
  crates/ruff_linter/src/rules/ruff/rules/sequence_sorting.rs
  crates/ruff_linter/src/rules/ruff/rules/sort_dunder_all.rs
  crates/ruff_linter/src/rules/ruff/rules/sort_dunder_slots.rs
  crates/ruff_linter/src/rules/ruff/snapshots/ruff_linter__rules__ruff__tests__RUF023_RUF023.py.snap
  ruff.schema.json
Labels: rule

#9619 [`flake8-simplify`] Support inverted returns in `needless-bool` (`SIM103`)
  crates/ruff_linter/src/rules/flake8_simplify/rules/needless_bool.rs
  crates/ruff_linter/src/rules/flake8_simplify/snapshots/ruff_linter__rules__flake8_simplify__tests__SIM103_SIM103.py.snap
Labels: bug

#9622 Fix the input for black's line ranges test file
  crates/ruff_python_formatter/resources/test/fixtures/black/cases/line_ranges_basic.py
  crates/ruff_python_formatter/resources/test/fixtures/black/cases/line_ranges_diff_edge_case.py
  crates/ruff_python_formatter/resources/test/fixtures/black/cases/line_ranges_fmt_off.py
  crates/ruff_python_formatter/resources/test/fixtures/black/cases/line_ranges_fmt_off_decorator.py
  crates/ruff_python_formatter/resources/test/fixtures/black/cases/line_ranges_fmt_off_overlap.py
  crates/ruff_python_formatter/resources/test/fixtures/black/cases/line_ranges_imports.py
  crates/ruff_python_formatter/resources/test/fixtures/black/cases/line_ranges_imports.py.expect
  crates/ruff_python_formatter/resources/test/fixtures/black/cases/line_ranges_indentation.py
  crates/ruff_python_formatter/resources/test/fixtures/black/cases/line_ranges_two_passes.py
  crates/ruff_python_formatter/resources/test/fixtures/black/cases/line_ranges_unwrapping.py
  crates/ruff_python_formatter/resources/test/fixtures/import_black_tests.py
  crates/ruff_python_formatter/tests/snapshots/black_compatibility@cases__line_ranges_basic.py.snap
  crates/ruff_python_formatter/tests/snapshots/black_compatibility@cases__line_ranges_diff_edge_case.py.snap
  crates/ruff_python_formatter/tests/snapshots/black_compatibility@cases__line_ranges_fmt_off.py.snap
  crates/ruff_python_formatter/tests/snapshots/black_compatibility@cases__line_ranges_fmt_off_decorator.py.snap
  crates/ruff_python_formatter/tests/snapshots/black_compatibility@cases__line_ranges_fmt_off_overlap.py.snap
  crates/ruff_python_formatter/tests/snapshots/black_compatibility@cases__line_ranges_indentation.py.snap
  crates/ruff_python_formatter/tests/snapshots/black_compatibility@cases__line_ranges_two_passes.py.snap
  crates/ruff_python_formatter/tests/snapshots/black_compatibility@cases__line_ranges_unwrapping.py.snap
Labels: internal, formatter

#9613 [`ruff`] Detect unnecessary `dict` comprehensions for iterables (`RUF025`)
  crates/ruff_linter/resources/test/fixtures/ruff/RUF025.py
  crates/ruff_linter/src/checkers/ast/analyze/expression.rs
  crates/ruff_linter/src/codes.rs
  crates/ruff_linter/src/rules/flake8_executable/snapshots/ruff_linter__rules__flake8_executable__tests__EXE001_1.py.snap
  crates/ruff_linter/src/rules/flake8_executable/snapshots/ruff_linter__rules__flake8_executable__tests__EXE002_1.py.snap
  crates/ruff_linter/src/rules/ruff/mod.rs
  crates/ruff_linter/src/rules/ruff/rules/mod.rs
  crates/ruff_linter/src/rules/ruff/rules/unnecessary_dict_comprehension_for_iterable.rs
  crates/ruff_linter/src/rules/ruff/snapshots/ruff_linter__rules__ruff__tests__RUF025_RUF025.py.snap
  ruff.schema.json
Labels: rule, preview

#9623 [`pylint`] Implement `assigning-non-slot` (`E0237`)
  crates/ruff_linter/resources/test/fixtures/pylint/non_slot_assignment.py
  crates/ruff_linter/src/checkers/ast/analyze/statement.rs
  crates/ruff_linter/src/codes.rs
  crates/ruff_linter/src/rules/pylint/mod.rs
  crates/ruff_linter/src/rules/pylint/rules/mod.rs
  crates/ruff_linter/src/rules/pylint/rules/non_slot_assignment.rs
  crates/ruff_linter/src/rules/pylint/snapshots/ruff_linter__rules__pylint__tests__PLE0237_non_slot_assignment.py.snap
  ruff.schema.json
Labels: rule, preview

#9631 Update SchemaStore script to install npm dependencies
  scripts/update_schemastore.py
Labels: bug, internal

#9632 Generate custom JSON schema for dynamic setting
  crates/ruff_python_formatter/src/options.rs
  ruff.schema.json
Labels: bug

#9633 help: enable auto-wrapping of help output
  Cargo.lock
  crates/ruff/Cargo.toml
  crates/ruff_dev/Cargo.toml
  crates/ruff_dev/src/generate_cli_help.rs
  docs/configuration.md
Labels: cli

#9636 [`flake8-return`] Take `NoReturn` annotation into account when analyzing implicit returns
  crates/ruff_linter/resources/test/fixtures/flake8_return/RET503.py
  crates/ruff_linter/src/rules/flake8_return/rules/function.rs
  crates/ruff_linter/src/rules/flake8_return/snapshots/ruff_linter__rules__flake8_return__tests__RET503_RET503.py.snap
Labels: bug

#9172 [`pylint`] Implement `too-many-nested-blocks` (`PLR1702`)
  crates/ruff_linter/resources/test/fixtures/pylint/too_many_nested_blocks.py
  crates/ruff_linter/src/checkers/ast/analyze/statement.rs
  crates/ruff_linter/src/codes.rs
  crates/ruff_linter/src/rules/pylint/mod.rs
  crates/ruff_linter/src/rules/pylint/rules/mod.rs
  crates/ruff_linter/src/rules/pylint/rules/too_many_nested_blocks.rs
  crates/ruff_linter/src/rules/pylint/settings.rs
  crates/ruff_linter/src/rules/pylint/snapshots/ruff_linter__rules__pylint__tests__PLR1702_too_many_nested_blocks.py.snap
  crates/ruff_workspace/src/options.rs
  ruff.schema.json
Labels: rule, preview

#9643 Delete `is_node_with_body` method
  crates/ruff_python_ast/src/node.rs
Labels: internal

#9637 Preserve indent around multiline strings
  crates/ruff_python_formatter/src/expression/mod.rs
  crates/ruff_python_formatter/src/expression/parentheses.rs
  crates/ruff_python_formatter/src/other/arguments.rs
  crates/ruff_python_formatter/tests/snapshots/black_compatibility@cases__preview_multiline_strings.py.snap
Labels: formatter, preview

#9649 Avoid rendering display-only rules as fixable
  crates/ruff_linter/src/rules/eradicate/rules/commented_out_code.rs
  crates/ruff_linter/src/test.rs
Labels: bug

#9650 Add Pydantic's `BaseConfig` to default-copy list
  crates/ruff_linter/resources/test/fixtures/ruff/RUF012.py
  crates/ruff_linter/src/rules/ruff/rules/helpers.rs
Labels: bug

#9651 [`ruff`] Guard against use of `default_factory` as a keyword argument (`RUF026`)
  crates/ruff_linter/resources/test/fixtures/ruff/RUF026.py
  crates/ruff_linter/src/checkers/ast/analyze/expression.rs
  crates/ruff_linter/src/codes.rs
  crates/ruff_linter/src/rules/ruff/mod.rs
  crates/ruff_linter/src/rules/ruff/rules/default_factory_kwarg.rs
  crates/ruff_linter/src/rules/ruff/rules/mod.rs
  crates/ruff_linter/src/rules/ruff/snapshots/ruff_linter__rules__ruff__tests__RUF026_RUF026.py.snap
  ruff.schema.json
Labels: rule, preview

#9654 [`pydocstyle`] Re-implement `last-line-after-section` (`D413`)
  crates/ruff_linter/resources/test/fixtures/pydocstyle/D413.py
  crates/ruff_linter/src/rules/pydocstyle/mod.rs
  crates/ruff_linter/src/rules/pydocstyle/rules/sections.rs
  crates/ruff_linter/src/rules/pydocstyle/snapshots/ruff_linter__rules__pydocstyle__tests__D413_D413.py.snap
  crates/ruff_linter/src/rules/pydocstyle/snapshots/ruff_linter__rules__pydocstyle__tests__D413_sections.py.snap
Labels: bug, docstring

#9657 Avoid panic when fixing inlined else blocks
  crates/ruff_linter/resources/test/fixtures/flake8_return/RET505.py
  crates/ruff_linter/src/rules/flake8_return/rules/function.rs
  crates/ruff_linter/src/rules/flake8_return/snapshots/ruff_linter__rules__flake8_return__tests__RET505_RET505.py.snap
  crates/ruff_linter/src/rules/flake8_return/snapshots/ruff_linter__rules__flake8_return__tests__preview__RET505_RET505.py.snap
Labels: bug

#9661 [`flake8-pie`] Omit bound tuples passed to `.startswith` or `.endswith`
  crates/ruff_linter/resources/test/fixtures/flake8_pie/PIE810.py
  crates/ruff_linter/src/rules/flake8_pie/rules/multiple_starts_ends_with.rs
  crates/ruff_linter/src/rules/flake8_pie/snapshots/ruff_linter__rules__flake8_pie__tests__PIE810_PIE810.py.snap
Labels: bug, autofix

#9653 Detect automagic-like assignments in notebooks
  crates/ruff_linter/src/linter.rs
  crates/ruff_linter/src/snapshots/ruff_linter__linter__tests__undefined_name.snap
  crates/ruff_notebook/resources/test/fixtures/jupyter/cell/automagic_assignment.json
  crates/ruff_notebook/resources/test/fixtures/jupyter/undefined_name.ipynb
  crates/ruff_notebook/src/cell.rs
  crates/ruff_notebook/src/notebook.rs
Labels: bug

#9674 Set source type: Stub for black tests with options
  crates/ruff_python_formatter/resources/test/fixtures/black/cases/nested_stub.options.json
  crates/ruff_python_formatter/resources/test/fixtures/black/cases/preview_long_dict_values.py
  crates/ruff_python_formatter/resources/test/fixtures/black/cases/preview_long_dict_values.py.expect
  crates/ruff_python_formatter/resources/test/fixtures/black/cases/walrus_in_dict.options.json
  crates/ruff_python_formatter/resources/test/fixtures/black/cases/walrus_in_dict.py
  crates/ruff_python_formatter/resources/test/fixtures/black/cases/walrus_in_dict.py.expect
  crates/ruff_python_formatter/resources/test/fixtures/import_black_tests.py
  crates/ruff_python_formatter/tests/snapshots/black_compatibility@cases__nested_stub.pyi.snap
  crates/ruff_python_formatter/tests/snapshots/black_compatibility@cases__preview_long_dict_values.py.snap
Labels: internal, formatter

#9678 [`flake8-pytest-style`] Add fix safety documentation for `duplicate-parameterize-test-cases`
  crates/ruff_linter/src/rules/flake8_pytest_style/rules/parametrize.rs
Labels: documentation

#9676 [`pycodestyle`] Allow `dtype` comparisons in `type-comparison`
  crates/ruff_linter/resources/test/fixtures/pycodestyle/E721.py
  crates/ruff_linter/src/rules/pycodestyle/rules/type_comparison.rs
  crates/ruff_linter/src/rules/pycodestyle/snapshots/ruff_linter__rules__pycodestyle__tests__preview__E721_E721.py.snap
Labels: bug

#9677 Document `literal-membership` fix safety conditions
  crates/ruff_linter/src/rules/pylint/rules/literal_membership.rs
Labels: documentation

#9679 [`flake8-pyi`] Mark `unaliased-collections-abc-set-import` fix as safe
  crates/ruff_linter/src/rules/flake8_pyi/rules/unaliased_collections_abc_set_import.rs
  crates/ruff_linter/src/rules/flake8_pyi/snapshots/ruff_linter__rules__flake8_pyi__tests__PYI025_PYI025.py.snap
  crates/ruff_linter/src/rules/flake8_pyi/snapshots/ruff_linter__rules__flake8_pyi__tests__PYI025_PYI025.pyi.snap
Labels: autofix, preview

#9428 Recategorize `static-key-dict-comprehension` from `RUF011` to `B035`
  crates/ruff_linter/resources/test/fixtures/flake8_bugbear/B035.py
  crates/ruff_linter/src/checkers/ast/analyze/expression.rs
  crates/ruff_linter/src/codes.rs
  crates/ruff_linter/src/rule_redirects.rs
  crates/ruff_linter/src/rules/flake8_bugbear/mod.rs
  crates/ruff_linter/src/rules/flake8_bugbear/rules/mod.rs
  crates/ruff_linter/src/rules/flake8_bugbear/rules/static_key_dict_comprehension.rs
  crates/ruff_linter/src/rules/flake8_bugbear/snapshots/ruff_linter__rules__flake8_bugbear__tests__B035_B035.py.snap
  crates/ruff_linter/src/rules/ruff/mod.rs
  crates/ruff_linter/src/rules/ruff/rules/mod.rs
  ruff.schema.json
Labels: rule

#9682 Error if the NURSERY selector is used with preview
  crates/ruff/tests/integration_test.rs
  crates/ruff_workspace/src/configuration.rs
Labels: preview

#9688 Avoid marking `InitVar` as a typing-only annotation
  crates/ruff_linter/resources/test/fixtures/flake8_type_checking/init_var.py
  crates/ruff_linter/src/checkers/ast/mod.rs
  crates/ruff_linter/src/rules/flake8_type_checking/helpers.rs
  crates/ruff_linter/src/rules/flake8_type_checking/mod.rs
  crates/ruff_linter/src/rules/flake8_type_checking/snapshots/ruff_linter__rules__flake8_type_checking__tests__strict_typing-only-standard-library-import_init_var.py.snap
  crates/ruff_linter/src/rules/flake8_type_checking/snapshots/ruff_linter__rules__flake8_type_checking__tests__strict_typing-only-third-party-import_strict.py.snap
  crates/ruff_linter/src/rules/flake8_type_checking/snapshots/ruff_linter__rules__flake8_type_checking__tests__typing-only-standard-library-import_init_var.py.snap
Labels: bug

#9690 Bump version to v0.1.15
  CHANGELOG.md
  Cargo.lock
  README.md
  crates/ruff/Cargo.toml
  crates/ruff_linter/Cargo.toml
  crates/ruff_shrinking/Cargo.toml
  docs/integrations.md
  pyproject.toml
  scripts/benchmarks/pyproject.toml
Labels: release

#9693 Remove empty section from changelog
  CHANGELOG.md
Labels: internal

#9687 Replace `--show-source` and `--no-show-source` with `--output_format=<full|concise>`
  crates/ruff/src/args.rs
  crates/ruff/src/lib.rs
  crates/ruff/src/printer.rs
  crates/ruff/tests/deprecation.rs
  crates/ruff/tests/integration_test.rs
  crates/ruff/tests/lint.rs
  crates/ruff/tests/snapshots/show_settings__display_default_settings.snap
  crates/ruff_linter/src/settings/types.rs
  crates/ruff_workspace/src/configuration.rs
  crates/ruff_workspace/src/options.rs
  crates/ruff_workspace/src/settings.rs
  docs/configuration.md
  ruff.schema.json
Labels: cli

#9694 [`pylint`] Show verbatim constant in `magic-value-comparison` (`PLR2004`)
  crates/ruff_linter/resources/test/fixtures/pylint/magic_value_comparison.py
  crates/ruff_linter/src/rules/pylint/rules/magic_value_comparison.rs
  crates/ruff_linter/src/rules/pylint/snapshots/ruff_linter__rules__pylint__tests__PLR2004_magic_value_comparison.py.snap
  crates/ruff_linter/src/rules/pylint/snapshots/ruff_linter__rules__pylint__tests__allow_magic_value_types.snap
Labels: bug

#9699 Show source-type in formatter snapshot tests with options
  crates/ruff_python_formatter/tests/fixtures.rs
  crates/ruff_python_formatter/tests/snapshots/format@blank_line_before_class_docstring.py.snap
  crates/ruff_python_formatter/tests/snapshots/format@docstring.py.snap
  crates/ruff_python_formatter/tests/snapshots/format@docstring_code_examples.py.snap
  crates/ruff_python_formatter/tests/snapshots/format@docstring_code_examples_crlf.py.snap
  crates/ruff_python_formatter/tests/snapshots/format@docstring_code_examples_dynamic_line_width.py.snap
  crates/ruff_python_formatter/tests/snapshots/format@expression__bytes.py.snap
  crates/ruff_python_formatter/tests/snapshots/format@expression__string.py.snap
  crates/ruff_python_formatter/tests/snapshots/format@fmt_on_off__fmt_off_docstring.py.snap
  crates/ruff_python_formatter/tests/snapshots/format@fmt_on_off__indent.py.snap
  crates/ruff_python_formatter/tests/snapshots/format@fmt_on_off__mixed_space_and_tab.py.snap
  crates/ruff_python_formatter/tests/snapshots/format@preview.py.snap
  crates/ruff_python_formatter/tests/snapshots/format@quote_style.py.snap
  crates/ruff_python_formatter/tests/snapshots/format@skip_magic_trailing_comma.py.snap
  crates/ruff_python_formatter/tests/snapshots/format@statement__assignment_split_value_first.py.snap
  crates/ruff_python_formatter/tests/snapshots/format@statement__with.py.snap
  crates/ruff_python_formatter/tests/snapshots/format@statement__with_39.py.snap
  crates/ruff_python_formatter/tests/snapshots/format@tab_width.py.snap
Labels: internal, formatter

#9704 [`flake8-simplify`] - Fix syntax error in autofix (`SIM114`)
  crates/ruff_linter/resources/test/fixtures/flake8_simplify/SIM114.py
  crates/ruff_linter/src/rules/flake8_simplify/rules/if_with_same_arms.rs
  crates/ruff_linter/src/rules/flake8_simplify/snapshots/ruff_linter__rules__flake8_simplify__tests__SIM114_SIM114.py.snap
  crates/ruff_linter/src/rules/flake8_simplify/snapshots/ruff_linter__rules__flake8_simplify__tests__preview__SIM114_SIM114.py.snap
Labels: bug, autofix

#9706 [`pylint`] Add `__mro_entries__` to known dunder methods (`PLW3201`)
  crates/ruff_linter/resources/test/fixtures/pylint/bad_dunder_method_name.py
  crates/ruff_linter/src/rules/pylint/helpers.rs
Labels: bug

#9708 Always request the concise output format during ecosystem checks
  python/ruff-ecosystem/ruff_ecosystem/projects.py
Labels: ci

#9705 [`flake8-return`] - fix indentation syntax error (`RET505`)
  crates/ruff_linter/resources/test/fixtures/flake8_return/RET505.py
  crates/ruff_linter/src/rules/flake8_return/rules/function.rs
  crates/ruff_linter/src/rules/flake8_return/snapshots/ruff_linter__rules__flake8_return__tests__RET505_RET505.py.snap
  crates/ruff_linter/src/rules/flake8_return/snapshots/ruff_linter__rules__flake8_return__tests__preview__RET505_RET505.py.snap
Labels: bug, autofix

#9695 Remove the NURSERY selector from the json schema
  crates/ruff_linter/src/rule_selector.rs
  ruff.schema.json
Labels: breaking

#9709 Add timeouts to all CI jobs
  .github/workflows/ci.yaml
Labels: ci

#9698 RUF022, RUF023: never add two trailing commas to the end of a sequence
  crates/ruff_linter/resources/test/fixtures/ruff/RUF022.py
  crates/ruff_linter/resources/test/fixtures/ruff/RUF023.py
  crates/ruff_linter/src/rules/ruff/rules/sequence_sorting.rs
  crates/ruff_linter/src/rules/ruff/snapshots/ruff_linter__rules__ruff__tests__RUF022_RUF022.py.snap
  crates/ruff_linter/src/rules/ruff/snapshots/ruff_linter__rules__ruff__tests__RUF023_RUF023.py.snap
Labels: bug, autofix

#9703 [`flake8-async`] Take `pathlib.Path` into account when analyzing async functions
  crates/ruff_linter/resources/test/fixtures/flake8_async/ASYNC101.py
  crates/ruff_linter/src/rules/flake8_async/rules/open_sleep_or_subprocess_call.rs
  crates/ruff_linter/src/rules/flake8_async/snapshots/ruff_linter__rules__flake8_async__tests__ASYNC101_ASYNC101.py.snap
Labels: bug

#9155 Implement `blank_line_after_nested_stub_class` preview style
  crates/ruff_python_formatter/resources/test/fixtures/ruff/stub_files/blank_line_after_nested_stub_class.options.json
  crates/ruff_python_formatter/resources/test/fixtures/ruff/stub_files/blank_line_after_nested_stub_class.pyi
  crates/ruff_python_formatter/resources/test/fixtures/ruff/stub_files/blank_line_after_nested_stub_class_eof.options.json
  crates/ruff_python_formatter/resources/test/fixtures/ruff/stub_files/blank_line_after_nested_stub_class_eof.pyi
  crates/ruff_python_formatter/src/comments/format.rs
  crates/ruff_python_formatter/src/preview.rs
  crates/ruff_python_formatter/src/statement/stmt_class_def.rs
  crates/ruff_python_formatter/src/statement/stmt_function_def.rs
  crates/ruff_python_formatter/src/statement/suite.rs
  crates/ruff_python_formatter/tests/snapshots/black_compatibility@cases__nested_stub.pyi.snap
  crates/ruff_python_formatter/tests/snapshots/format@stub_files__blank_line_after_nested_stub_class.pyi.snap
  crates/ruff_python_formatter/tests/snapshots/format@stub_files__blank_line_after_nested_stub_class_eof.pyi.snap
  crates/ruff_python_formatter/tests/snapshots/format@stub_files__suite.pyi.snap
Labels: formatter, preview

#9712 Stabilize some rules for v0.2.0 release
  crates/ruff_linter/src/codes.rs
  crates/ruff_linter/src/rules/flake8_simplify/snapshots/ruff_linter__rules__flake8_simplify__tests__preview__SIM114_SIM114.py.snap
  crates/ruff_workspace/src/configuration.rs
Labels: rule

#9735 Update README.md by adding `ivy` repository to the who's using Ruff section
  README.md
Labels: documentation

#9736 Excludes upload and download artifact dependencies from dependabot
  .github/dependabot.yml
Labels: ci

#9726 Use publicly available Apple Silicon runners
  .github/workflows/release.yaml
Labels: release

#9734 Support `IfExp` with dual string arms in `invalid-envvar-default`
  crates/ruff_linter/resources/test/fixtures/pylint/invalid_envvar_default.py
  crates/ruff_linter/src/rules/pylint/rules/invalid_envvar_default.rs
  crates/ruff_linter/src/rules/pylint/snapshots/ruff_linter__rules__pylint__tests__PLW1508_invalid_envvar_default.py.snap
Labels: bug

#9744 Removing trailing whitespace inside multiline strings is unsafe
  crates/ruff_linter/resources/test/fixtures/pycodestyle/W291.py
  crates/ruff_linter/src/rules/pycodestyle/mod.rs
  crates/ruff_linter/src/rules/pycodestyle/rules/trailing_whitespace.rs
  crates/ruff_linter/src/rules/pycodestyle/snapshots/ruff_linter__rules__pycodestyle__tests__W291_W291.py.snap
  crates/ruff_python_index/src/indexer.rs
  crates/ruff_python_index/src/lib.rs
  crates/ruff_python_index/src/multiline_ranges.rs
Labels: bug
