Repository astral-sh/ruff, pull requests merged in 2024-05, with the labels that each got.

#11213 [red-knot] Remove `Clone` from `Files`
  crates/red_knot/src/db.rs
  crates/red_knot/src/files.rs
  crates/red_knot/src/main.rs
  crates/red_knot/src/program/mod.rs
  crates/red_knot/src/watch.rs
Labels: internal

#11225 `ruff server` reads from a configuration TOML file in the user configuration directory if no local configuration exists
  crates/ruff_server/src/session/workspace/ruff_settings.rs
Labels: server

#11230 Rename variable to `indent_width` to match docs
  crates/ruff_linter/src/rules/pycodestyle/rules/logical_lines/indentation.rs
Labels: internal

#11224 `ruff server` respects `per-file-ignores` configuration
  crates/ruff_server/src/fix.rs
  crates/ruff_server/src/lint.rs
  crates/ruff_server/src/server/api/diagnostics.rs
  crates/ruff_server/src/server/api/requests/code_action_resolve.rs
  crates/ruff_server/src/server/api/requests/execute_command.rs
Labels: bug, server

#11241 Make libc a platform specific dependency
  crates/ruff_server/Cargo.toml
Labels: internal

#11234 Remove ImportMap
  crates/ruff/src/cache.rs
  crates/ruff/src/commands/check.rs
  crates/ruff/src/diagnostics.rs
  crates/ruff_linter/src/checkers/imports.rs
  crates/ruff_linter/src/linter.rs
  crates/ruff_linter/src/rules/pyflakes/mod.rs
  crates/ruff_linter/src/test.rs
  crates/ruff_python_ast/src/imports.rs
  crates/ruff_server/src/lint.rs
  crates/ruff_wasm/src/lib.rs
  fuzz/fuzz_targets/ruff_formatter_validity.rs
Labels: internal

#11251 Avoid allocations for isort module names
  crates/ruff_linter/src/checkers/ast/analyze/definitions.rs
  crates/ruff_linter/src/checkers/ast/analyze/statement.rs
  crates/ruff_linter/src/rules/flake8_annotations/helpers.rs
  crates/ruff_linter/src/rules/isort/types.rs
  crates/ruff_python_ast/src/helpers.rs
Labels: performance

#11240 Remove num-cpus dependency
  Cargo.lock
  Cargo.toml
  crates/ruff/Cargo.toml
  crates/ruff/src/lib.rs
Labels: internal

#11255 Rephrase rationale for `pytest-incorrect-pytest-import`
  crates/ruff_linter/src/rules/flake8_pytest_style/rules/imports.rs
  crates/ruff_linter/src/rules/flake8_pytest_style/snapshots/ruff_linter__rules__flake8_pytest_style__tests__PT013.snap
Labels: documentation

#11222 `ruff server` no longer hangs after shutdown
  crates/ruff_server/src/message.rs
  crates/ruff_server/src/server.rs
  crates/ruff_server/src/server/client.rs
  crates/ruff_server/src/server/connection.rs
  crates/ruff_server/src/server/schedule.rs
Labels: server

#11257 Remove trailing reference section
  crates/ruff_linter/src/rules/refurb/rules/reimplemented_operator.rs
Labels: documentation

#11256 [red-knot] resolve class members
  crates/red_knot/src/symbols.rs
  crates/red_knot/src/types.rs
  crates/red_knot/src/types/infer.rs
Labels: internal

#11268 Remove unnecessary check for RUF020 enabled
  crates/ruff_linter/src/checkers/ast/analyze/expression.rs
Labels: internal

#11270 [`refurb`] Ignore methods in `reimplemented-operator` (`FURB118`)
  crates/ruff_linter/resources/test/fixtures/refurb/FURB118.py
  crates/ruff_linter/src/rules/flake8_unused_arguments/rules/unused_arguments.rs
  crates/ruff_linter/src/rules/pep8_naming/rules/invalid_first_argument_name.rs
  crates/ruff_linter/src/rules/pylint/rules/bad_staticmethod_argument.rs
  crates/ruff_linter/src/rules/pylint/rules/no_self_use.rs
  crates/ruff_linter/src/rules/pylint/rules/singledispatch_method.rs
  crates/ruff_linter/src/rules/pylint/rules/singledispatchmethod_function.rs
  crates/ruff_linter/src/rules/pylint/rules/super_without_brackets.rs
  crates/ruff_linter/src/rules/refurb/rules/reimplemented_operator.rs
  crates/ruff_linter/src/rules/refurb/snapshots/ruff_linter__rules__refurb__tests__FURB118_FURB118.py.snap
Labels: rule, preview

#11271 Use function range for `reimplemented-operator` diagnostics
  crates/ruff_linter/src/rules/refurb/rules/reimplemented_operator.rs
  crates/ruff_linter/src/rules/refurb/snapshots/ruff_linter__rules__refurb__tests__FURB118_FURB118.py.snap
Labels: rule, preview

#11272 Remove remaining `ruff_shrinking` references
  .github/workflows/ci.yaml
  crates/ruff_python_formatter/CONTRIBUTING.md
  crates/ruff_python_formatter/shrink_formatter_errors.py
  pyproject.toml
Labels: internal

#11274 Bump version to v0.4.3
  CHANGELOG.md
  Cargo.lock
  README.md
  crates/ruff/Cargo.toml
  crates/ruff_linter/Cargo.toml
  docs/integrations.md
  pyproject.toml
  scripts/benchmarks/pyproject.toml
Labels: release

#11275 Change `hardcoded-tmp-directory-extend` example to follow the schema
  crates/ruff_workspace/src/options.rs
Labels: documentation

#11283 Expand tildes when resolving Ruff server configuration file
  Cargo.lock
  crates/ruff_server/Cargo.toml
  crates/ruff_server/src/session/settings.rs
  crates/ruff_server/src/session/workspace/ruff_settings.rs
Labels: bug, server

#11284 Use shared `is_stub` in unused argument rules
  crates/ruff_linter/src/rules/flake8_unused_arguments/helpers.rs
  crates/ruff_linter/src/rules/flake8_unused_arguments/mod.rs
  crates/ruff_linter/src/rules/flake8_unused_arguments/rules/unused_arguments.rs
  crates/ruff_linter/src/rules/pylint/rules/no_self_use.rs
Labels: internal

#11266 `ruff server`: Editor settings are used by default if no file-based configuration exists
  crates/ruff_server/src/session/workspace/ruff_settings.rs
Labels: bug, server

#11286 Create snapshot tests for `--add-noqa`
  crates/ruff/tests/lint.rs
Labels: server, testing

#11287 Allow `set(True)` for boolean traps
  crates/ruff_linter/src/rules/flake8_boolean_trap/helpers.rs
Labels: rule

#11291 Fix `ruff server` hanging after Neovim closes
  crates/ruff_server/src/server.rs
Labels: bug, server

#11285 Touch-up error messages in server file discovery
  crates/ruff_server/src/session/settings.rs
  crates/ruff_server/src/session/workspace/ruff_settings.rs
Labels: internal, server

#11301 Respect logged and re-raised expressions in nested statements
  crates/ruff_linter/resources/test/fixtures/flake8_blind_except/BLE.py
  crates/ruff_linter/src/rules/flake8_blind_except/rules/blind_except.rs
  crates/ruff_linter/src/rules/tryceratops/rules/verbose_raise.rs
Labels: bug

#11304 Fix 'MarkVerbatimCommentsAsFormattedVisitor' is unused warning in release builds
  crates/ruff_python_formatter/src/comments/mod.rs
Labels: internal

#11311 Add globbing to isort sections docs
  clippy.toml
  crates/ruff_workspace/src/options.rs
  ruff.schema.json
Labels: documentation

#11312 [`flake8-bugbear`] Ignore enum classes in `cached-instance-method` (`B019`)
  crates/ruff_linter/resources/test/fixtures/flake8_bugbear/B019.py
  crates/ruff_linter/src/checkers/ast/analyze/statement.rs
  crates/ruff_linter/src/rules/flake8_bugbear/rules/cached_instance_method.rs
Labels: rule

#11267 Refactor the `ExprDict` node
  crates/ruff_linter/src/checkers/ast/mod.rs
  crates/ruff_linter/src/rules/flake8_bandit/rules/django_extra.rs
  crates/ruff_linter/src/rules/flake8_logging_format/rules/logging_call.rs
  crates/ruff_linter/src/rules/flake8_pie/rules/reimplemented_container_builtin.rs
  crates/ruff_linter/src/rules/flake8_pie/rules/unnecessary_dict_kwargs.rs
  crates/ruff_linter/src/rules/flake8_pie/rules/unnecessary_spread.rs
  crates/ruff_linter/src/rules/flake8_pyi/rules/simple_defaults.rs
  crates/ruff_linter/src/rules/flake8_simplify/rules/yoda_conditions.rs
  crates/ruff_linter/src/rules/pyflakes/rules/repeated_keys.rs
  crates/ruff_linter/src/rules/pyflakes/rules/strings.rs
  crates/ruff_linter/src/rules/pylint/rules/bad_string_format_type.rs
  crates/ruff_linter/src/rules/pylint/rules/dict_iter_missing_items.rs
  crates/ruff_linter/src/rules/pylint/rules/non_slot_assignment.rs
  crates/ruff_linter/src/rules/pylint/rules/repeated_keyword_argument.rs
  crates/ruff_linter/src/rules/pyupgrade/rules/convert_typed_dict_functional_to_class.rs
  crates/ruff_linter/src/rules/pyupgrade/rules/printf_string_formatting.rs
  crates/ruff_linter/src/rules/ruff/rules/sort_dunder_slots.rs
  crates/ruff_python_ast/src/comparable.rs
  crates/ruff_python_ast/src/helpers.rs
  crates/ruff_python_ast/src/node.rs
  crates/ruff_python_ast/src/nodes.rs
  crates/ruff_python_ast/src/visitor.rs
  crates/ruff_python_ast/src/visitor/transformer.rs
  crates/ruff_python_codegen/src/generator.rs
  crates/ruff_python_formatter/src/expression/expr_dict.rs
  crates/ruff_python_formatter/src/expression/mod.rs
  crates/ruff_python_parser/src/parser/expression.rs
  crates/ruff_python_parser/src/parser/recovery.rs
  crates/ruff_python_parser/tests/snapshots/invalid_syntax@expressions__dict__double_star.py.snap
  crates/ruff_python_parser/tests/snapshots/invalid_syntax@expressions__dict__double_star_comprehension.py.snap
  crates/ruff_python_parser/tests/snapshots/invalid_syntax@expressions__dict__missing_closing_brace_0.py.snap
  crates/ruff_python_parser/tests/snapshots/invalid_syntax@expressions__dict__missing_closing_brace_1.py.snap
  crates/ruff_python_parser/tests/snapshots/invalid_syntax@expressions__dict__missing_closing_brace_2.py.snap
  crates/ruff_python_parser/tests/snapshots/invalid_syntax@expressions__dict__named_expression_0.py.snap
  crates/ruff_python_parser/tests/snapshots/invalid_syntax@expressions__dict__named_expression_1.py.snap
  crates/ruff_python_parser/tests/snapshots/invalid_syntax@expressions__dict__recover.py.snap
  crates/ruff_python_parser/tests/snapshots/invalid_syntax@expressions__set__recover.py.snap
  crates/ruff_python_parser/tests/snapshots/invalid_syntax@invalid_del_target.py.snap
  crates/ruff_python_parser/tests/snapshots/invalid_syntax@params_var_keyword_with_default.py.snap
  crates/ruff_python_parser/tests/snapshots/invalid_syntax@statements__invalid_assignment_targets.py.snap
  crates/ruff_python_parser/tests/snapshots/invalid_syntax@statements__invalid_augmented_assignment_target.py.snap
  crates/ruff_python_parser/tests/snapshots/invalid_syntax@statements__match__as_pattern_3.py.snap
  crates/ruff_python_parser/tests/snapshots/invalid_syntax@statements__match__invalid_lhs_or_rhs_pattern.py.snap
  crates/ruff_python_parser/tests/snapshots/valid_syntax@expressions__await.py.snap
  crates/ruff_python_parser/tests/snapshots/valid_syntax@expressions__call.py.snap
  crates/ruff_python_parser/tests/snapshots/valid_syntax@expressions__dictionary.py.snap
  crates/ruff_python_parser/tests/snapshots/valid_syntax@expressions__f_string.py.snap
  crates/ruff_python_parser/tests/snapshots/valid_syntax@expressions__list.py.snap
  crates/ruff_python_parser/tests/snapshots/valid_syntax@expressions__set.py.snap
  crates/ruff_python_parser/tests/snapshots/valid_syntax@expressions__yield.py.snap
  crates/ruff_python_parser/tests/snapshots/valid_syntax@expressions__yield_from.py.snap
  crates/ruff_python_parser/tests/snapshots/valid_syntax@statement__match.py.snap
Labels: internal

#11324 Tell renovate not to try to update GitHub runners
  .github/renovate.json5
Labels: ci

#11321 Consider with statements for too many branches lint
  crates/ruff_linter/resources/test/fixtures/pylint/too_many_branches.py
  crates/ruff_linter/src/rules/pylint/rules/too_many_branches.rs
  crates/ruff_linter/src/rules/pylint/snapshots/ruff_linter__rules__pylint__tests__PLR0912_too_many_branches.py.snap
Labels: bug

#11330 Move all module from the AST to the semantic crate
  crates/ruff_linter/src/checkers/ast/analyze/definitions.rs
  crates/ruff_linter/src/checkers/ast/mod.rs
  crates/ruff_python_ast/src/lib.rs
  crates/ruff_python_semantic/src/all.rs
  crates/ruff_python_semantic/src/binding.rs
  crates/ruff_python_semantic/src/definition.rs
  crates/ruff_python_semantic/src/lib.rs
Labels: internal

#11327 [red-knot] fix re-hashing in Files and SymbolTable
  crates/red_knot/src/files.rs
  crates/red_knot/src/symbols.rs
Labels: internal

#11341 Make B024 and B027 documentation more nuanced
  crates/ruff_linter/src/rules/flake8_bugbear/rules/abstract_base_class.rs
Labels: documentation

#11339 [red-knot] Remove `<Db: SemanticDb>` contraints in favor of dynamic dispatch
  crates/red_knot/src/db.rs
  crates/red_knot/src/lint.rs
  crates/red_knot/src/main.rs
  crates/red_knot/src/module.rs
  crates/red_knot/src/parse.rs
  crates/red_knot/src/program/check.rs
  crates/red_knot/src/program/mod.rs
  crates/red_knot/src/source.rs
  crates/red_knot/src/symbols.rs
  crates/red_knot/src/types.rs
  crates/red_knot/src/types/infer.rs
Labels: internal

#11346 Simplify arithmetic operation in logical lines checker
  crates/ruff_linter/src/checkers/logical_lines.rs
Labels: internal

#11288 [`pylint`] Detect `pathlib.Path.open` calls in `unspecified-encoding` (`PLW1514`)
  crates/ruff_linter/resources/test/fixtures/pylint/unspecified_encoding.py
  crates/ruff_linter/src/rules/pylint/rules/unspecified_encoding.rs
  crates/ruff_linter/src/rules/pylint/snapshots/ruff_linter__rules__pylint__tests__PLW1514_unspecified_encoding.py.snap
  crates/ruff_linter/src/rules/pylint/snapshots/ruff_linter__rules__pylint__tests__unspecified_encoding_python39_or_lower.snap
Labels: rule, preview

#11282 [red-knot] @override lint rule
  crates/red_knot/src/lint.rs
  crates/red_knot/src/symbols.rs
  crates/red_knot/src/types.rs
  crates/red_knot/src/types/infer.rs
Labels: internal

#11352 Bump version to v0.4.4
  CHANGELOG.md
  Cargo.lock
  README.md
  crates/ruff/Cargo.toml
  crates/ruff_linter/Cargo.toml
  docs/integrations.md
  pyproject.toml
  scripts/benchmarks/pyproject.toml
Labels: release

#11354 Allow clippy map-unwrap-or
  Cargo.toml
Labels: internal

#11356 Use `u64` instead of `i64` in Int type
  crates/ruff_linter/src/rules/pyupgrade/rules/native_literals.rs
  crates/ruff_python_ast/src/helpers.rs
  crates/ruff_python_ast/src/int.rs
  crates/ruff_python_parser/src/lexer.rs
  crates/ruff_python_parser/src/snapshots/ruff_python_parser__lexer__tests__numbers.snap
Labels: internal

#11362 [pyflakes] Update docs to describe WAI behavior (F541)
  crates/ruff_linter/src/rules/pyflakes/rules/f_string_missing_placeholders.rs
  scripts/check_docs_formatted.py
Labels: documentation

#11265 Split `add_noqa` process into distinctive edit generation and edit application stages
  crates/ruff/tests/lint.rs
  crates/ruff_linter/src/lib.rs
  crates/ruff_linter/src/noqa.rs
Labels: linter

#11372 [`flake8-pie`] Preserve parentheses in `unnecessary-dict-kwargs`
  crates/ruff_linter/resources/test/fixtures/flake8_pie/PIE804.py
  crates/ruff_linter/src/rules/flake8_pie/rules/unnecessary_dict_kwargs.rs
  crates/ruff_linter/src/rules/flake8_pie/snapshots/ruff_linter__rules__flake8_pie__tests__PIE804_PIE804.py.snap
Labels: bug, fixes

#11276 `ruff server`: Support `noqa` comment code action
  crates/ruff_server/src/lint.rs
  crates/ruff_server/src/server/api/requests/code_action.rs
  crates/ruff_server/src/session/settings.rs
Labels: server

#11376 Avoid `TCH005` for `if` stmt with `elif`/`else` block
  crates/ruff_linter/resources/test/fixtures/flake8_type_checking/TCH005.py
  crates/ruff_linter/src/checkers/ast/analyze/statement.rs
  crates/ruff_linter/src/rules/flake8_type_checking/rules/empty_type_checking_block.rs
  crates/ruff_linter/src/rules/flake8_type_checking/snapshots/ruff_linter__rules__flake8_type_checking__tests__empty-type-checking-block_TCH005.py.snap
Labels: bug

#11377 Avoid `PLE0237` for property with setter
  crates/ruff_linter/resources/test/fixtures/pylint/non_slot_assignment.py
  crates/ruff_linter/src/rules/pylint/rules/non_slot_assignment.rs
Labels: bug

#11381 Reword `future-rewritable-type-annotation` (`FA100`) message
  crates/ruff_linter/src/rules/flake8_future_annotations/rules/future_rewritable_type_annotation.rs
  crates/ruff_linter/src/rules/flake8_future_annotations/snapshots/ruff_linter__rules__flake8_future_annotations__tests__edge_case.py.snap
  crates/ruff_linter/src/rules/flake8_future_annotations/snapshots/ruff_linter__rules__flake8_future_annotations__tests__from_typing_import.py.snap
  crates/ruff_linter/src/rules/flake8_future_annotations/snapshots/ruff_linter__rules__flake8_future_annotations__tests__from_typing_import_many.py.snap
  crates/ruff_linter/src/rules/flake8_future_annotations/snapshots/ruff_linter__rules__flake8_future_annotations__tests__import_typing.py.snap
  crates/ruff_linter/src/rules/flake8_future_annotations/snapshots/ruff_linter__rules__flake8_future_annotations__tests__import_typing_as.py.snap
Labels: rule

#11392 Get `cargo shear` passing
  Cargo.lock
  Cargo.toml
  crates/red_knot/Cargo.toml
  crates/ruff/Cargo.toml
  crates/ruff_formatter/Cargo.toml
  crates/ruff_python_ast/Cargo.toml
  crates/ruff_python_formatter/Cargo.toml
  crates/ruff_python_trivia/Cargo.toml
  crates/ruff_workspace/Cargo.toml
Labels: internal

#11393 Add `cargo shear` to CI
  .github/workflows/ci.yaml
Labels: internal

#11405 Rename `AnyStringKind` -> `AnyStringFlags`
  crates/ruff_linter/src/directives.rs
  crates/ruff_linter/src/rules/flake8_quotes/helpers.rs
  crates/ruff_linter/src/rules/flake8_quotes/rules/avoidable_escaped_quote.rs
  crates/ruff_linter/src/rules/flake8_quotes/rules/unnecessary_escaped_quote.rs
  crates/ruff_linter/src/rules/pycodestyle/rules/invalid_escape_sequence.rs
  crates/ruff_linter/src/rules/pylint/rules/bad_string_format_character.rs
  crates/ruff_linter/src/rules/pylint/rules/bad_string_format_type.rs
  crates/ruff_linter/src/rules/pyupgrade/rules/printf_string_formatting.rs
  crates/ruff_python_ast/src/nodes.rs
  crates/ruff_python_codegen/src/stylist.rs
  crates/ruff_python_formatter/src/other/f_string.rs
  crates/ruff_python_formatter/src/other/f_string_element.rs
  crates/ruff_python_formatter/src/string/any.rs
  crates/ruff_python_formatter/src/string/docstring.rs
  crates/ruff_python_formatter/src/string/mod.rs
  crates/ruff_python_formatter/src/string/normalize.rs
  crates/ruff_python_index/src/multiline_ranges.rs
  crates/ruff_python_parser/src/lexer.rs
  crates/ruff_python_parser/src/lexer/fstring.rs
  crates/ruff_python_parser/src/parser/expression.rs
  crates/ruff_python_parser/src/snapshots/ruff_python_parser__lexer__tests__empty_fstrings.snap
  crates/ruff_python_parser/src/snapshots/ruff_python_parser__lexer__tests__escape_unicode_name.snap
  crates/ruff_python_parser/src/snapshots/ruff_python_parser__lexer__tests__fstring.snap
  crates/ruff_python_parser/src/snapshots/ruff_python_parser__lexer__tests__fstring_comments.snap
  crates/ruff_python_parser/src/snapshots/ruff_python_parser__lexer__tests__fstring_conversion.snap
  crates/ruff_python_parser/src/snapshots/ruff_python_parser__lexer__tests__fstring_escape.snap
  crates/ruff_python_parser/src/snapshots/ruff_python_parser__lexer__tests__fstring_escape_braces.snap
  crates/ruff_python_parser/src/snapshots/ruff_python_parser__lexer__tests__fstring_escape_raw.snap
  crates/ruff_python_parser/src/snapshots/ruff_python_parser__lexer__tests__fstring_expression_multiline.snap
  crates/ruff_python_parser/src/snapshots/ruff_python_parser__lexer__tests__fstring_multiline.snap
  crates/ruff_python_parser/src/snapshots/ruff_python_parser__lexer__tests__fstring_named_unicode.snap
  crates/ruff_python_parser/src/snapshots/ruff_python_parser__lexer__tests__fstring_named_unicode_raw.snap
  crates/ruff_python_parser/src/snapshots/ruff_python_parser__lexer__tests__fstring_nested.snap
  crates/ruff_python_parser/src/snapshots/ruff_python_parser__lexer__tests__fstring_parentheses.snap
  crates/ruff_python_parser/src/snapshots/ruff_python_parser__lexer__tests__fstring_prefix.snap
  crates/ruff_python_parser/src/snapshots/ruff_python_parser__lexer__tests__fstring_single_quote_escape_mac_eol.snap
  crates/ruff_python_parser/src/snapshots/ruff_python_parser__lexer__tests__fstring_single_quote_escape_unix_eol.snap
  crates/ruff_python_parser/src/snapshots/ruff_python_parser__lexer__tests__fstring_single_quote_escape_windows_eol.snap
  crates/ruff_python_parser/src/snapshots/ruff_python_parser__lexer__tests__fstring_with_format_spec.snap
  crates/ruff_python_parser/src/snapshots/ruff_python_parser__lexer__tests__fstring_with_ipy_escape_command.snap
  crates/ruff_python_parser/src/snapshots/ruff_python_parser__lexer__tests__fstring_with_lambda_expression.snap
  crates/ruff_python_parser/src/snapshots/ruff_python_parser__lexer__tests__fstring_with_multiline_format_spec.snap
  crates/ruff_python_parser/src/snapshots/ruff_python_parser__lexer__tests__fstring_with_named_expression.snap
  crates/ruff_python_parser/src/snapshots/ruff_python_parser__lexer__tests__fstring_with_nul_char.snap
  crates/ruff_python_parser/src/snapshots/ruff_python_parser__lexer__tests__non_logical_newline_in_string_continuation.snap
  crates/ruff_python_parser/src/snapshots/ruff_python_parser__lexer__tests__string.snap
  crates/ruff_python_parser/src/snapshots/ruff_python_parser__lexer__tests__string_continuation_with_mac_eol.snap
  crates/ruff_python_parser/src/snapshots/ruff_python_parser__lexer__tests__string_continuation_with_unix_eol.snap
  crates/ruff_python_parser/src/snapshots/ruff_python_parser__lexer__tests__string_continuation_with_windows_eol.snap
  crates/ruff_python_parser/src/snapshots/ruff_python_parser__lexer__tests__triple_quoted_mac_eol.snap
  crates/ruff_python_parser/src/snapshots/ruff_python_parser__lexer__tests__triple_quoted_unix_eol.snap
  crates/ruff_python_parser/src/snapshots/ruff_python_parser__lexer__tests__triple_quoted_windows_eol.snap
  crates/ruff_python_parser/src/string.rs
  crates/ruff_python_parser/src/token.rs
Labels: internal

#11395 Add a note on `--preview` to the README
  README.md
Labels: documentation

#11407 Move sub-crates to workspace dependencies
  Cargo.toml
  crates/red_knot/Cargo.toml
  crates/ruff/Cargo.toml
  crates/ruff_benchmark/Cargo.toml
  crates/ruff_cache/Cargo.toml
  crates/ruff_dev/Cargo.toml
  crates/ruff_diagnostics/Cargo.toml
  crates/ruff_formatter/Cargo.toml
  crates/ruff_index/Cargo.toml
  crates/ruff_linter/Cargo.toml
  crates/ruff_macros/Cargo.toml
  crates/ruff_notebook/Cargo.toml
  crates/ruff_python_ast/Cargo.toml
  crates/ruff_python_ast_integration_tests/Cargo.toml
  crates/ruff_python_codegen/Cargo.toml
  crates/ruff_python_formatter/Cargo.toml
  crates/ruff_python_index/Cargo.toml
  crates/ruff_python_literal/Cargo.toml
  crates/ruff_python_parser/Cargo.toml
  crates/ruff_python_semantic/Cargo.toml
  crates/ruff_python_trivia/Cargo.toml
  crates/ruff_python_trivia_integration_tests/Cargo.toml
  crates/ruff_server/Cargo.toml
  crates/ruff_source_file/Cargo.toml
  crates/ruff_wasm/Cargo.toml
  crates/ruff_workspace/Cargo.toml
Labels: internal

#11406 Avoid lexer usage in `PLE1300` and `PLE1307`
  crates/ruff_linter/src/checkers/ast/analyze/expression.rs
  crates/ruff_linter/src/rules/pylint/rules/bad_string_format_character.rs
  crates/ruff_linter/src/rules/pylint/rules/bad_string_format_type.rs
Labels: internal

#11399 Add `Iterator` impl for `StringLike` parts
  crates/ruff_linter/src/rules/flake8_quotes/rules/avoidable_escaped_quote.rs
  crates/ruff_linter/src/rules/flake8_quotes/rules/check_string_quotes.rs
  crates/ruff_linter/src/rules/flake8_quotes/rules/unnecessary_escaped_quote.rs
  crates/ruff_linter/src/rules/ruff/rules/ambiguous_unicode_character.rs
  crates/ruff_python_ast/src/expression.rs
Labels: internal

#11400 Create a newtype wrapper around `Vec<FStringElement>`
  crates/ruff_linter/src/rules/flake8_bandit/rules/hardcoded_bind_all_interfaces.rs
  crates/ruff_linter/src/rules/flake8_bandit/rules/hardcoded_tmp_directory.rs
  crates/ruff_linter/src/rules/flake8_datetimez/rules/call_datetime_strptime_without_zone.rs
  crates/ruff_linter/src/rules/flake8_quotes/rules/avoidable_escaped_quote.rs
  crates/ruff_linter/src/rules/flake8_quotes/rules/unnecessary_escaped_quote.rs
  crates/ruff_linter/src/rules/flynt/rules/static_join_to_fstring.rs
  crates/ruff_linter/src/rules/ruff/rules/ambiguous_unicode_character.rs
  crates/ruff_linter/src/rules/ruff/rules/missing_fstring_syntax.rs
  crates/ruff_linter/src/rules/tryceratops/rules/raise_vanilla_args.rs
  crates/ruff_python_ast/src/node.rs
  crates/ruff_python_ast/src/nodes.rs
  crates/ruff_python_ast/src/visitor.rs
  crates/ruff_python_ast/src/visitor/transformer.rs
  crates/ruff_python_formatter/src/other/f_string.rs
  crates/ruff_python_parser/src/parser/expression.rs
Labels: internal

#11402 Move `W605` to the AST checker
  crates/ruff_linter/src/checkers/ast/analyze/string_like.rs
  crates/ruff_linter/src/checkers/tokens.rs
  crates/ruff_linter/src/registry.rs
  crates/ruff_linter/src/rules/pycodestyle/rules/invalid_escape_sequence.rs
  crates/ruff_python_ast/src/expression.rs
Labels: internal

#11410 Implement `IntoIterator` for `FStringElements`
  crates/ruff_linter/src/rules/pycodestyle/rules/invalid_escape_sequence.rs
  crates/ruff_python_ast/src/node.rs
  crates/ruff_python_ast/src/nodes.rs
  crates/ruff_python_ast/src/visitor.rs
  crates/ruff_python_ast/src/visitor/transformer.rs
Labels: internal

#11409 Remove some hardcoded modules from `generate_known_standard_library.py`
  crates/ruff_python_stdlib/src/sys.rs
  scripts/generate_known_standard_library.py
Labels: internal

#11353 Improve the `update_schemastore` script
  scripts/pyproject.toml
  scripts/update_schemastore.py
Labels: internal

#11417 Use `tokenize` for linter benchmark
  crates/ruff_benchmark/benches/linter.rs
Labels: internal

#11361 Add `Tokens` newtype wrapper, `TokenKind` iterator
  crates/ruff_linter/src/importer/insertion.rs
  crates/ruff_linter/src/linter.rs
  crates/ruff_linter/src/rules/pyflakes/mod.rs
  crates/ruff_linter/src/test.rs
  crates/ruff_python_parser/src/lib.rs
  crates/ruff_python_parser/src/token.rs
  crates/ruff_python_trivia_integration_tests/tests/block_comments.rs
  crates/ruff_server/src/lint.rs
  crates/ruff_wasm/src/lib.rs
Labels: internal, parser

#11418 Use `TokenKind` in `doc_lines_from_tokens`
  crates/ruff_linter/src/doc_lines.rs
  crates/ruff_linter/src/linter.rs
Labels: internal

#11419 Use `TokenKind` in blank lines checker
  crates/ruff_linter/src/checkers/tokens.rs
  crates/ruff_linter/src/rules/pycodestyle/rules/blank_lines.rs
Labels: internal

#11420 Move most of token-based rules to use `TokenKind`
  crates/ruff_linter/src/checkers/tokens.rs
  crates/ruff_linter/src/rules/flake8_commas/rules/trailing_commas.rs
  crates/ruff_linter/src/rules/flake8_implicit_str_concat/rules/implicit.rs
  crates/ruff_linter/src/rules/pycodestyle/rules/compound_statements.rs
  crates/ruff_linter/src/rules/pycodestyle/rules/too_many_newlines_at_end_of_file.rs
  crates/ruff_linter/src/rules/pylint/rules/invalid_string_characters.rs
Labels: internal

#11424 Move `UP034` to use `TokenKind` instead of `Tok`
  crates/ruff_linter/src/checkers/tokens.rs
  crates/ruff_linter/src/rules/pyupgrade/rules/extraneous_parentheses.rs
Labels: internal

#11425 Move string-prefix enumerations to a separate submodule
  crates/ruff_linter/src/rules/flake8_simplify/rules/ast_expr.rs
  crates/ruff_python_ast/src/lib.rs
  crates/ruff_python_ast/src/nodes.rs
  crates/ruff_python_ast/src/str_prefix.rs
  crates/ruff_python_formatter/src/string/mod.rs
  crates/ruff_python_formatter/src/string/normalize.rs
  crates/ruff_python_parser/src/lexer.rs
Labels: internal

#11434 Update CONTRIBUTING.md to reflect the new parser
  CONTRIBUTING.md
Labels: documentation

#11437 Regenerate sys.rs with stdlibs==2024.5.15
  crates/ruff_python_stdlib/src/sys.rs
Labels: isort

#11423 Clearly indicate what is counted as a branch
  crates/ruff_linter/src/rules/pylint/rules/too_many_branches.rs
Labels: documentation

#11438 Add `--output-format` to `ruff config` CLI
  crates/ruff/src/args.rs
  crates/ruff/src/commands/config.rs
  crates/ruff/src/lib.rs
  crates/ruff/tests/config.rs
  crates/ruff_workspace/src/options_base.rs
Labels: cli

#11440 Fix broken comment in `too-many-branches`
  crates/ruff_linter/src/rules/pylint/rules/too_many_branches.rs
Labels: internal

#11444 Remove leftover marker tokens
  crates/ruff_python_parser/src/token.rs
Labels: internal

#11445 Include soft keywords for `is_keyword` check
  crates/ruff_linter/src/rules/pycodestyle/rules/logical_lines/missing_whitespace_after_keyword.rs
  crates/ruff_linter/src/rules/pycodestyle/rules/logical_lines/missing_whitespace_around_operator.rs
  crates/ruff_linter/src/rules/pycodestyle/rules/logical_lines/mod.rs
  crates/ruff_linter/src/rules/pycodestyle/rules/logical_lines/whitespace_around_keywords.rs
  crates/ruff_python_parser/src/token.rs
  crates/ruff_python_parser/tests/snapshots/invalid_syntax@ann_assign_stmt_type_alias_annotation.py.snap
  crates/ruff_python_parser/tests/snapshots/invalid_syntax@comprehension_missing_for_after_async.py.snap
Labels: internal

#11462 Remove example from `tab-indentation`
  crates/ruff_linter/src/rules/pycodestyle/rules/tab_indentation.rs
  scripts/check_docs_formatted.py
Labels: documentation

#11464 Respect operator precedence in `FURB110`
  crates/ruff_linter/resources/test/fixtures/refurb/FURB110.py
  crates/ruff_linter/src/rules/refurb/rules/if_exp_instead_of_or_operator.rs
  crates/ruff_linter/src/rules/refurb/snapshots/ruff_linter__rules__refurb__tests__FURB110_FURB110.py.snap
Labels: bug

#11465 Treat escaped newline as valid sequence
  crates/ruff_linter/resources/test/fixtures/pycodestyle/W605_0.py
  crates/ruff_linter/src/rules/pycodestyle/rules/invalid_escape_sequence.rs
  crates/ruff_linter/src/rules/pycodestyle/snapshots/ruff_linter__rules__pycodestyle__tests__W605_W605_0.py.snap
Labels: bug

#11466 Remove comma from ecosystem checks
  python/ruff-ecosystem/ruff_ecosystem/defaults.py
  scripts/check_ecosystem.py
Labels: internal

#11470 Fix windows-ci failure
  .github/workflows/ci.yaml
Labels: internal

#11468 Add some new projects to the ecosystem CI
  python/ruff-ecosystem/ruff_ecosystem/defaults.py
Labels: internal

#11469 Fix division by zero error in ecosystem check
  python/ruff-ecosystem/ruff_ecosystem/check.py
Labels: internal

#11446 Consider soft keywords for `E27` rules
  crates/ruff_linter/resources/test/fixtures/pycodestyle/E27.py
  crates/ruff_linter/src/rules/pycodestyle/rules/logical_lines/missing_whitespace_after_keyword.rs
  crates/ruff_linter/src/rules/pycodestyle/rules/logical_lines/mod.rs
  crates/ruff_linter/src/rules/pycodestyle/rules/logical_lines/whitespace_around_keywords.rs
  crates/ruff_linter/src/rules/pycodestyle/snapshots/ruff_linter__rules__pycodestyle__tests__E271_E27.py.snap
  crates/ruff_linter/src/rules/pycodestyle/snapshots/ruff_linter__rules__pycodestyle__tests__E273_E27.py.snap
  crates/ruff_linter/src/rules/pycodestyle/snapshots/ruff_linter__rules__pycodestyle__tests__E275_E27.py.snap
Labels: rule

#11442 Use lookahead to resolve `type` soft keyword
  crates/ruff_python_parser/src/parser/mod.rs
  crates/ruff_python_parser/src/parser/statement.rs
  crates/ruff_python_parser/src/token_source.rs
Labels: parser

#11443 Use speculative parsing for `match` statement
  crates/ruff_python_parser/src/parser/expression.rs
  crates/ruff_python_parser/src/parser/statement.rs
Labels: parser

#11414 Avoid flagging `__future__` annotations as required for non-evaluated type annotations
  crates/ruff_linter/resources/test/fixtures/flake8_future_annotations/ok_quoted_type.py
  crates/ruff_linter/src/checkers/ast/analyze/expression.rs
  crates/ruff_linter/src/rules/flake8_future_annotations/mod.rs
  crates/ruff_linter/src/rules/flake8_future_annotations/snapshots/ruff_linter__rules__flake8_future_annotations__tests__fa102_no_future_import_uses_lowercase.py.snap
  crates/ruff_linter/src/rules/flake8_future_annotations/snapshots/ruff_linter__rules__flake8_future_annotations__tests__fa102_no_future_import_uses_union.py.snap
  crates/ruff_linter/src/rules/flake8_future_annotations/snapshots/ruff_linter__rules__flake8_future_annotations__tests__fa102_no_future_import_uses_union_inner.py.snap
  crates/ruff_linter/src/rules/flake8_future_annotations/snapshots/ruff_linter__rules__flake8_future_annotations__tests__fa102_ok_quoted_type.py.snap
Labels: bug

#11483 Clarify motivation for E713 and E714
  crates/ruff_linter/src/rules/pycodestyle/rules/not_tests.rs
Labels: documentation

#11206 `ruff server`: Support Jupyter Notebook (`*.ipynb`) files
  Cargo.lock
  Cargo.toml
  crates/ruff_notebook/src/cell.rs
  crates/ruff_notebook/src/notebook.rs
  crates/ruff_server/Cargo.toml
  crates/ruff_server/src/edit.rs
  crates/ruff_server/src/edit/document.rs
  crates/ruff_server/src/edit/notebook.rs
  crates/ruff_server/src/edit/range.rs
  crates/ruff_server/src/fix.rs
  crates/ruff_server/src/format.rs
  crates/ruff_server/src/lib.rs
  crates/ruff_server/src/lint.rs
  crates/ruff_server/src/server.rs
  crates/ruff_server/src/server/api.rs
  crates/ruff_server/src/server/api/diagnostics.rs
  crates/ruff_server/src/server/api/notifications.rs
  crates/ruff_server/src/server/api/notifications/cancel.rs
  crates/ruff_server/src/server/api/notifications/did_change.rs
  crates/ruff_server/src/server/api/notifications/did_change_notebook.rs
  crates/ruff_server/src/server/api/notifications/did_change_watched_files.rs
  crates/ruff_server/src/server/api/notifications/did_change_workspace.rs
  crates/ruff_server/src/server/api/notifications/did_close.rs
  crates/ruff_server/src/server/api/notifications/did_close_notebook.rs
  crates/ruff_server/src/server/api/notifications/did_open.rs
  crates/ruff_server/src/server/api/notifications/did_open_notebook.rs
  crates/ruff_server/src/server/api/requests/code_action.rs
  crates/ruff_server/src/server/api/requests/code_action_resolve.rs
  crates/ruff_server/src/server/api/requests/diagnostic.rs
  crates/ruff_server/src/server/api/requests/execute_command.rs
  crates/ruff_server/src/server/api/requests/format.rs
  crates/ruff_server/src/server/api/requests/format_range.rs
  crates/ruff_server/src/server/api/requests/hover.rs
  crates/ruff_server/src/session.rs
  crates/ruff_server/src/session/index.rs
  crates/ruff_server/src/session/index/ruff_settings.rs
  crates/ruff_server/src/session/settings.rs
  crates/ruff_server/src/session/workspace.rs
  crates/ruff_server/tests/document.rs
Labels: server

#11487 [`pylint`] Remove `try` body from branch counting
  crates/ruff_linter/resources/test/fixtures/pylint/too_many_branches.py
  crates/ruff_linter/src/rules/pylint/rules/too_many_branches.rs
  crates/ruff_linter/src/rules/pylint/snapshots/ruff_linter__rules__pylint__tests__PLR0912_too_many_branches.py.snap
Labels: bug

#11484 fixes invalid rule from hyphen
  scripts/add_rule.py
Labels: internal

#11488 [`pylint`] Ignore `__slots__` with dynamic values
  crates/ruff_linter/resources/test/fixtures/pylint/non_slot_assignment.py
  crates/ruff_linter/src/rules/pylint/rules/non_slot_assignment.rs
Labels: bug

#11489 Simplify Neovim docs for the LSP setup
  docs/integrations.md
Labels: documentation

#11490 Avoid multiline quotes warning with `quote-style = preserve`
  crates/ruff/src/commands/format.rs
  crates/ruff/tests/format.rs
Labels: formatter

#11495 Move `has_comments` to `CommentRanges`
  crates/ruff_linter/src/rules/flake8_pytest_style/rules/assertion.rs
  crates/ruff_linter/src/rules/flake8_simplify/rules/ast_bool_op.rs
  crates/ruff_linter/src/rules/flake8_simplify/rules/if_else_block_instead_of_dict_get.rs
  crates/ruff_linter/src/rules/flake8_simplify/rules/if_else_block_instead_of_if_exp.rs
  crates/ruff_linter/src/rules/flake8_simplify/rules/needless_bool.rs
  crates/ruff_linter/src/rules/flake8_simplify/rules/suppressible_exception.rs
  crates/ruff_linter/src/rules/pylint/rules/nested_min_max.rs
  crates/ruff_linter/src/rules/ruff/rules/collection_literal_concatenation.rs
  crates/ruff_python_index/src/indexer.rs
  crates/ruff_python_trivia/src/comment_ranges.rs
Labels: internal

#11493 `ruff.applyFormat` now formats an entire notebook document
  crates/ruff_server/src/server/api/requests/execute_command.rs
  crates/ruff_server/src/server/api/requests/format.rs
Labels: notebook, server

#11492 Fix automatic configuration reloading for text and notebook documents
  crates/ruff_server/src/server.rs
  crates/ruff_server/src/server/api/notifications/did_change_watched_files.rs
  crates/ruff_server/src/session.rs
  crates/ruff_server/src/session/index.rs
Labels: bug, server

#11485 Mark quotes as unnecessary for non-evaluated annotations
  crates/ruff/tests/integration_test.rs
  crates/ruff_linter/resources/test/fixtures/pyupgrade/UP037_0.py
  crates/ruff_linter/resources/test/fixtures/pyupgrade/UP037_1.py
  crates/ruff_linter/src/checkers/ast/mod.rs
  crates/ruff_linter/src/rules/pyupgrade/mod.rs
  crates/ruff_linter/src/rules/pyupgrade/rules/quoted_annotation.rs
  crates/ruff_linter/src/rules/pyupgrade/snapshots/ruff_linter__rules__pyupgrade__tests__UP037_0.py.snap
  crates/ruff_linter/src/rules/pyupgrade/snapshots/ruff_linter__rules__pyupgrade__tests__UP037_1.py.snap
Labels: rule

#11497 `ruff server`: Fix multiple issues with Neovim and Helix
  crates/ruff_server/resources/test/fixtures/settings/global_only.json
  crates/ruff_server/src/lint.rs
  crates/ruff_server/src/server.rs
  crates/ruff_server/src/session.rs
  crates/ruff_server/src/session/index.rs
  crates/ruff_server/src/session/index/ruff_settings.rs
  crates/ruff_server/src/session/settings.rs
Labels: bug, configuration, server

#11499 Update documentation for `ruff server` with new migration guide
  crates/ruff_server/README.md
  crates/ruff_server/assets/nativeServer.png
  crates/ruff_server/docs/MIGRATION.md
  crates/ruff_server/docs/setup/HELIX.md
Labels: documentation, server

#11500 Minor edits to `ruff server` docs
  crates/ruff_server/README.md
  crates/ruff_server/docs/MIGRATION.md
Labels: documentation

#11502 Bump version to `v0.4.5`
  CHANGELOG.md
  Cargo.lock
  README.md
  crates/ruff/Cargo.toml
  crates/ruff_linter/Cargo.toml
  docs/integrations.md
  pyproject.toml
  scripts/benchmarks/pyproject.toml
Labels: release

#11513 Use `Importer` available on `Checker`
  crates/ruff_linter/src/rules/flake8_future_annotations/rules/future_required_type_annotation.rs
Labels: internal

#11498 [flake8-async] Sleep with >24 hour interval should usually sleep forever (ASYNC116)
  crates/ruff_linter/resources/test/fixtures/flake8_async/ASYNC116.py
  crates/ruff_linter/src/checkers/ast/analyze/expression.rs
  crates/ruff_linter/src/codes.rs
  crates/ruff_linter/src/rules/flake8_async/mod.rs
  crates/ruff_linter/src/rules/flake8_async/rules/mod.rs
  crates/ruff_linter/src/rules/flake8_async/rules/sleep_forever_call.rs
  crates/ruff_linter/src/rules/flake8_async/snapshots/ruff_linter__rules__flake8_async__tests__ASYNC116_ASYNC116.py.snap
  ruff.schema.json
Labels: rule, preview

#11523 Treat all `singledispatch` arguments as runtime-required
  crates/ruff_linter/resources/test/fixtures/flake8_type_checking/singledispatch.py
  crates/ruff_linter/src/checkers/ast/mod.rs
  crates/ruff_linter/src/rules/flake8_type_checking/snapshots/ruff_linter__rules__flake8_type_checking__tests__typing-only-third-party-import_singledispatch.py.snap
Labels: bug

#11526 `ruff server`: An empty code action filter no longer returns notebook source actions
  crates/ruff_server/src/server/api/requests/code_action.rs
Labels: bug, server

#11521 Consider match-case stmts for `C901`, `PLR0912`, and `PLR0915`
  crates/ruff_linter/src/rules/mccabe/rules/function_is_too_complex.rs
  crates/ruff_linter/src/rules/pylint/rules/too_many_branches.rs
  crates/ruff_linter/src/rules/pylint/rules/too_many_statements.rs
Labels: rule

#11543 [`flake8-2020`] fix minor typo in `YTT301` documentation
  crates/ruff_linter/src/rules/flake8_2020/rules/subscript.rs
Labels: documentation

#11528 Add missing functions to NumPy 2.0 migration rule
  crates/ruff_linter/resources/test/fixtures/numpy/NPY201.py
  crates/ruff_linter/src/rules/numpy/rules/numpy_2_0_deprecation.rs
  crates/ruff_linter/src/rules/numpy/snapshots/ruff_linter__rules__numpy__tests__numpy2-deprecation_NPY201.py.snap
Labels: rule

#11535 `ruff server` correctly treats `.pyi` files as stub files
  crates/ruff_server/src/session/index.rs
Labels: bug, server

#11546 [`flake8-self`] Ignore sunder accesses in `flake8-self` rule
  crates/ruff_linter/resources/test/fixtures/flake8_self/SLF001.py
  crates/ruff_linter/src/rules/flake8_self/rules/private_member_access.rs
Labels: rule

#11537 `ruff server` searches for configuration in parent directories
  crates/ruff_server/src/session/index/ruff_settings.rs
Labels: configuration, server

#11530 [`pyupgrade`] lint TypeAliasType in UP040
  crates/ruff_linter/resources/test/fixtures/pyupgrade/UP040.py
  crates/ruff_linter/src/checkers/ast/analyze/statement.rs
  crates/ruff_linter/src/rules/pyupgrade/rules/use_pep695_type_alias.rs
  crates/ruff_linter/src/rules/pyupgrade/snapshots/ruff_linter__rules__pyupgrade__tests__UP040.py.snap
Labels: rule

#11550 Create intermediary directories for `--output-file`
  crates/ruff/src/lib.rs
Labels: bug

#11533 Avoid owned token data in sequence sorting
  crates/ruff_linter/src/rules/ruff/rules/sequence_sorting.rs
  crates/ruff_linter/src/rules/ruff/rules/sort_dunder_all.rs
  crates/ruff_linter/src/rules/ruff/rules/sort_dunder_slots.rs
Labels: internal

#11524 Remove empty strings when converting to f-string (`UP032`)
  crates/ruff_linter/src/rules/pyupgrade/rules/f_strings.rs
  crates/ruff_linter/src/rules/pyupgrade/snapshots/ruff_linter__rules__pyupgrade__tests__UP032_0.py.snap
Labels: rule

#11519 Adds recommended extension settings for vscode
  .vscode/extensions.json
  .vscode/settings.json
  CONTRIBUTING.md
Labels: internal

#11564 Implement a common trait for the string flags
  crates/ruff_linter/src/directives.rs
  crates/ruff_linter/src/rules/flake8_quotes/helpers.rs
  crates/ruff_linter/src/rules/flake8_quotes/rules/avoidable_escaped_quote.rs
  crates/ruff_linter/src/rules/flake8_quotes/rules/unnecessary_escaped_quote.rs
  crates/ruff_linter/src/rules/pylint/rules/bad_string_format_character.rs
  crates/ruff_linter/src/rules/pylint/rules/bad_string_format_type.rs
  crates/ruff_linter/src/rules/pyupgrade/rules/printf_string_formatting.rs
  crates/ruff_python_ast/src/nodes.rs
  crates/ruff_python_codegen/src/stylist.rs
  crates/ruff_python_formatter/src/other/f_string.rs
  crates/ruff_python_formatter/src/other/f_string_element.rs
  crates/ruff_python_formatter/src/string/any.rs
  crates/ruff_python_formatter/src/string/docstring.rs
  crates/ruff_python_formatter/src/string/mod.rs
  crates/ruff_python_formatter/src/string/normalize.rs
  crates/ruff_python_index/src/multiline_ranges.rs
  crates/ruff_python_parser/src/lexer.rs
  crates/ruff_python_parser/src/lexer/fstring.rs
  crates/ruff_python_parser/src/string.rs
  crates/ruff_python_parser/src/token.rs
Labels: internal

#11566 Use default settings if initialization options is empty or not provided
  crates/ruff_server/resources/test/fixtures/settings/global_only.json
  crates/ruff_server/src/session/settings.rs
Labels: bug, server

#11570 Update `FStringElements` to deref to a slice
  crates/ruff_python_ast/src/nodes.rs
  crates/ruff_python_parser/src/parser/expression.rs
Labels: internal

#11474 Consider soft keyword for various parsing logic
  crates/ruff_python_parser/resources/inline/ok/except_stmt_as_name_soft_keyword.py
  crates/ruff_python_parser/resources/inline/ok/from_import_soft_keyword_module_name.py
  crates/ruff_python_parser/resources/inline/ok/import_as_name_soft_keyword.py
  crates/ruff_python_parser/resources/inline/ok/match_as_pattern_soft_keyword.py
  crates/ruff_python_parser/resources/inline/ok/match_attr_pattern_soft_keyword.py
  crates/ruff_python_parser/src/parser/expression.rs
  crates/ruff_python_parser/src/parser/mod.rs
  crates/ruff_python_parser/src/parser/pattern.rs
  crates/ruff_python_parser/src/parser/statement.rs
  crates/ruff_python_parser/tests/snapshots/invalid_syntax@statements__match__as_pattern_4.py.snap
  crates/ruff_python_parser/tests/snapshots/valid_syntax@except_stmt_as_name_soft_keyword.py.snap
  crates/ruff_python_parser/tests/snapshots/valid_syntax@from_import_soft_keyword_module_name.py.snap
  crates/ruff_python_parser/tests/snapshots/valid_syntax@import_as_name_soft_keyword.py.snap
  crates/ruff_python_parser/tests/snapshots/valid_syntax@match_as_pattern_soft_keyword.py.snap
  crates/ruff_python_parser/tests/snapshots/valid_syntax@match_attr_pattern_soft_keyword.py.snap
Labels: parser

#11475 Use struct fields in `TokenValue` enum
  crates/ruff_python_parser/src/lexer.rs
  crates/ruff_python_parser/src/parser/expression.rs
  crates/ruff_python_parser/src/parser/pattern.rs
Labels: internal

#11571 Rename document module to text_document
  crates/ruff_server/src/edit.rs
  crates/ruff_server/src/edit/text_document.rs
Labels: internal

#11494 Update parser API to merge lexing and parsing
  Cargo.lock
  crates/ruff_python_parser/Cargo.toml
  crates/ruff_python_parser/src/lexer.rs
  crates/ruff_python_parser/src/lib.rs
  crates/ruff_python_parser/src/parser/mod.rs
  crates/ruff_python_parser/src/parser/tests.rs
  crates/ruff_python_parser/src/string.rs
  crates/ruff_python_parser/src/token_source.rs
  crates/ruff_python_parser/src/typing.rs
  crates/ruff_python_parser/tests/fixtures.rs
Labels: parser

#11551 Respect excludes in `ruff server` configuration discovery
  Cargo.lock
  crates/ruff_server/Cargo.toml
  crates/ruff_server/src/session/index/ruff_settings.rs
Labels: bug, server

#11565 Consider irrefutable pattern similar to `if .. else` for `C901`
  crates/ruff_linter/src/rules/mccabe/rules/function_is_too_complex.rs
  crates/ruff_python_ast/src/nodes.rs
Labels: rule

#11575 Avoid recommending context manager in `__enter__` implementations
  crates/ruff_linter/resources/test/fixtures/flake8_simplify/SIM115.py
  crates/ruff_linter/src/rules/flake8_simplify/rules/open_file_with_context_handler.rs
Labels: bug

#11511 Replace most usages of `lex_starts_at` with `Tokens`
  crates/ruff_linter/src/checkers/ast/analyze/expression.rs
  crates/ruff_linter/src/checkers/ast/analyze/statement.rs
  crates/ruff_linter/src/checkers/ast/mod.rs
  crates/ruff_linter/src/checkers/imports.rs
  crates/ruff_linter/src/importer/insertion.rs
  crates/ruff_linter/src/importer/mod.rs
  crates/ruff_linter/src/linter.rs
  crates/ruff_linter/src/rules/flake8_type_checking/rules/typing_only_runtime_import.rs
  crates/ruff_linter/src/rules/isort/annotate.rs
  crates/ruff_linter/src/rules/isort/helpers.rs
  crates/ruff_linter/src/rules/isort/mod.rs
  crates/ruff_linter/src/rules/isort/rules/add_required_imports.rs
  crates/ruff_linter/src/rules/isort/rules/organize_imports.rs
  crates/ruff_linter/src/rules/pyflakes/rules/unused_variable.rs
  crates/ruff_linter/src/rules/pyupgrade/fixes.rs
  crates/ruff_linter/src/rules/pyupgrade/rules/deprecated_import.rs
  crates/ruff_linter/src/rules/pyupgrade/rules/f_strings.rs
  crates/ruff_linter/src/rules/pyupgrade/rules/printf_string_formatting.rs
  crates/ruff_linter/src/rules/pyupgrade/rules/redundant_open_modes.rs
  crates/ruff_linter/src/rules/pyupgrade/rules/unnecessary_encode_utf8.rs
  crates/ruff_linter/src/rules/ruff/rules/sequence_sorting.rs
  crates/ruff_linter/src/rules/ruff/rules/sort_dunder_all.rs
  crates/ruff_linter/src/rules/ruff/rules/sort_dunder_slots.rs
  crates/ruff_python_parser/src/lib.rs
Labels: internal

#11515 Replace `lex_starts_at` with `Tokens` in the formatter
  crates/ruff_benchmark/benches/formatter.rs
  crates/ruff_python_formatter/src/cli.rs
  crates/ruff_python_formatter/src/context.rs
  crates/ruff_python_formatter/src/lib.rs
  crates/ruff_python_formatter/src/range.rs
  crates/ruff_python_formatter/src/statement/suite.rs
  crates/ruff_python_formatter/src/string/docstring.rs
  crates/ruff_python_formatter/src/verbatim.rs
  crates/ruff_python_parser/src/lib.rs
  crates/ruff_wasm/src/lib.rs
Labels: internal, formatter

#11572 Make `ruff_notebook` a workspace dependency in `ruff_server`
  crates/ruff_server/Cargo.toml
Labels: internal

#11576 Remove some unused `pub` functions
  Cargo.lock
  Cargo.toml
  crates/ruff_formatter/src/lib.rs
  crates/ruff_linter/src/directives.rs
  crates/ruff_linter/src/rules/isort/categorize.rs
  crates/ruff_python_ast/src/name.rs
  crates/ruff_python_ast/src/nodes.rs
  crates/ruff_python_ast/src/traversal.rs
  crates/ruff_python_literal/Cargo.toml
  crates/ruff_python_literal/src/cformat.rs
  crates/ruff_python_literal/src/escape.rs
  crates/ruff_python_literal/src/float.rs
  crates/ruff_python_parser/src/lib.rs
  crates/ruff_python_semantic/src/scope.rs
Labels: internal

#11548 [`flake8-bandit`] `request-without-timeout` should warn for `requests.request`
  crates/ruff_linter/src/rules/flake8_bandit/rules/request_without_timeout.rs
  python/ruff-ecosystem/ruff_ecosystem/check.py
Labels: rule

#11584 Propagate reads on global variables
  crates/ruff_linter/src/checkers/ast/mod.rs
  crates/ruff_linter/src/renamer.rs
  crates/ruff_linter/src/rules/pandas_vet/helpers.rs
  crates/ruff_linter/src/rules/pylint/rules/non_ascii_name.rs
  crates/ruff_python_semantic/src/binding.rs
  crates/ruff_python_semantic/src/model.rs
Labels: bug

#11585 Bump version to v0.4.6
  CHANGELOG.md
  Cargo.lock
  README.md
  crates/ruff/Cargo.toml
  crates/ruff_linter/Cargo.toml
  docs/integrations.md
  pyproject.toml
  scripts/benchmarks/pyproject.toml
Labels: release

#11416 [redknot] add module type and attribute lookup for some types
  crates/red_knot/src/types.rs
  crates/red_knot/src/types/infer.rs
Labels: internal

#11325 [`flake8-pyi`] Implement `PYI064`
  crates/ruff_linter/resources/test/fixtures/flake8_pyi/PYI064.py
  crates/ruff_linter/resources/test/fixtures/flake8_pyi/PYI064.pyi
  crates/ruff_linter/src/checkers/ast/analyze/statement.rs
  crates/ruff_linter/src/codes.rs
  crates/ruff_linter/src/rules/flake8_pyi/mod.rs
  crates/ruff_linter/src/rules/flake8_pyi/rules/mod.rs
  crates/ruff_linter/src/rules/flake8_pyi/rules/redundant_final_literal.rs
  crates/ruff_linter/src/rules/flake8_pyi/snapshots/ruff_linter__rules__flake8_pyi__tests__PYI064_PYI064.py.snap
  crates/ruff_linter/src/rules/flake8_pyi/snapshots/ruff_linter__rules__flake8_pyi__tests__PYI064_PYI064.pyi.snap
  crates/ruff_python_ast/src/helpers.rs
  ruff.schema.json
Labels: rule, preview

#11541 [`flake8-pyi`] Implement `PYI066`
  crates/ruff_linter/resources/test/fixtures/flake8_pyi/PYI006.pyi
  crates/ruff_linter/resources/test/fixtures/flake8_pyi/PYI066.py
  crates/ruff_linter/resources/test/fixtures/flake8_pyi/PYI066.pyi
  crates/ruff_linter/src/checkers/ast/analyze/statement.rs
  crates/ruff_linter/src/codes.rs
  crates/ruff_linter/src/rules/flake8_pyi/mod.rs
  crates/ruff_linter/src/rules/flake8_pyi/rules/bad_version_info_comparison.rs
  crates/ruff_linter/src/rules/flake8_pyi/snapshots/ruff_linter__rules__flake8_pyi__tests__PYI006_PYI006.pyi.snap
  crates/ruff_linter/src/rules/flake8_pyi/snapshots/ruff_linter__rules__flake8_pyi__tests__PYI066_PYI066.py.snap
  crates/ruff_linter/src/rules/flake8_pyi/snapshots/ruff_linter__rules__flake8_pyi__tests__PYI066_PYI066.pyi.snap
  ruff.schema.json
Labels: rule, preview

#11590 Respect file exclusions in `ruff server`
  crates/ruff_server/src/fix.rs
  crates/ruff_server/src/lint.rs
  crates/ruff_server/src/server/api/diagnostics.rs
  crates/ruff_server/src/server/api/requests/code_action.rs
  crates/ruff_server/src/server/api/requests/code_action_resolve.rs
  crates/ruff_server/src/server/api/requests/execute_command.rs
  crates/ruff_server/src/server/api/requests/format.rs
  crates/ruff_server/src/server/api/requests/format_range.rs
  crates/ruff_server/src/session/index.rs
  crates/ruff_server/src/session/index/ruff_settings.rs
  crates/ruff_workspace/src/resolver.rs
Labels: bug, server

#11529 Update token-based rules to use `Tokens`
  crates/ruff_linter/src/checkers/tokens.rs
  crates/ruff_linter/src/linter.rs
  crates/ruff_linter/src/rules/flake8_commas/rules/trailing_commas.rs
  crates/ruff_linter/src/rules/flake8_implicit_str_concat/rules/implicit.rs
  crates/ruff_linter/src/rules/pycodestyle/rules/blank_lines.rs
  crates/ruff_linter/src/rules/pycodestyle/rules/compound_statements.rs
  crates/ruff_linter/src/rules/pycodestyle/rules/too_many_newlines_at_end_of_file.rs
  crates/ruff_linter/src/rules/pyupgrade/rules/extraneous_parentheses.rs
  crates/ruff_python_parser/src/lexer.rs
Labels: internal

#11562 Replace `lex` usages
  crates/ruff_dev/src/print_tokens.rs
  crates/ruff_linter/src/rules/pyflakes/rules/invalid_literal_comparisons.rs
  crates/ruff_python_trivia_integration_tests/tests/simple_tokenizer.rs
  crates/ruff_wasm/src/lib.rs
Labels: internal

#11563 Update lexer to only emit the `TokenKind`
  crates/ruff_python_parser/src/lexer.rs
  crates/ruff_python_parser/src/token_source.rs
Labels: internal

#11578 Implement `TokenFlags` stored on each `Token`
  crates/ruff_python_ast/src/str_prefix.rs
  crates/ruff_python_parser/src/lexer.rs
  crates/ruff_python_parser/src/lexer/fstring.rs
  crates/ruff_python_parser/src/parser/expression.rs
  crates/ruff_python_parser/src/token_source.rs
Labels: parser

#11596 Reduce extensive use of `snapshot.query`
  crates/ruff_server/src/fix.rs
  crates/ruff_server/src/lint.rs
  crates/ruff_server/src/server/api/diagnostics.rs
  crates/ruff_server/src/server/api/requests/code_action.rs
  crates/ruff_server/src/server/api/requests/code_action_resolve.rs
  crates/ruff_server/src/server/api/requests/execute_command.rs
  crates/ruff_server/src/server/api/requests/format.rs
  crates/ruff_server/src/server/api/requests/format_range.rs
Labels: internal

#11591 Use `CommentRanges` from the parsed output
  crates/ruff_linter/src/checkers/filesystem.rs
  crates/ruff_linter/src/checkers/imports.rs
  crates/ruff_linter/src/checkers/physical_lines.rs
  crates/ruff_linter/src/checkers/tokens.rs
  crates/ruff_linter/src/directives.rs
  crates/ruff_linter/src/linter.rs
  crates/ruff_linter/src/rules/eradicate/rules/commented_out_code.rs
  crates/ruff_linter/src/rules/flake8_bugbear/rules/zip_without_explicit_strict.rs
  crates/ruff_linter/src/rules/flake8_executable/rules/mod.rs
  crates/ruff_linter/src/rules/flake8_no_pep420/rules/implicit_namespace_package.rs
  crates/ruff_linter/src/rules/flake8_pie/rules/unnecessary_dict_kwargs.rs
  crates/ruff_linter/src/rules/flake8_pyi/rules/generic_not_last_base_class.rs
  crates/ruff_linter/src/rules/flake8_pyi/rules/type_comment_in_stub.rs
  crates/ruff_linter/src/rules/flake8_pytest_style/rules/assertion.rs
  crates/ruff_linter/src/rules/flake8_pytest_style/rules/parametrize.rs
  crates/ruff_linter/src/rules/flake8_simplify/rules/ast_bool_op.rs
  crates/ruff_linter/src/rules/flake8_simplify/rules/ast_ifexp.rs
  crates/ruff_linter/src/rules/flake8_simplify/rules/ast_with.rs
  crates/ruff_linter/src/rules/flake8_simplify/rules/collapsible_if.rs
  crates/ruff_linter/src/rules/flake8_simplify/rules/if_else_block_instead_of_dict_get.rs
  crates/ruff_linter/src/rules/flake8_simplify/rules/if_else_block_instead_of_if_exp.rs
  crates/ruff_linter/src/rules/flake8_simplify/rules/if_with_same_arms.rs
  crates/ruff_linter/src/rules/flake8_simplify/rules/key_in_dict.rs
  crates/ruff_linter/src/rules/flake8_simplify/rules/needless_bool.rs
  crates/ruff_linter/src/rules/flake8_simplify/rules/suppressible_exception.rs
  crates/ruff_linter/src/rules/flake8_todos/rules/todos.rs
  crates/ruff_linter/src/rules/isort/comments.rs
  crates/ruff_linter/src/rules/isort/rules/organize_imports.rs
  crates/ruff_linter/src/rules/pandas_vet/rules/inplace_argument.rs
  crates/ruff_linter/src/rules/pycodestyle/overlong.rs
  crates/ruff_linter/src/rules/pycodestyle/rules/doc_line_too_long.rs
  crates/ruff_linter/src/rules/pycodestyle/rules/line_too_long.rs
  crates/ruff_linter/src/rules/pycodestyle/rules/literal_comparisons.rs
  crates/ruff_linter/src/rules/pycodestyle/rules/not_tests.rs
  crates/ruff_linter/src/rules/pyflakes/rules/repeated_keys.rs
  crates/ruff_linter/src/rules/pyflakes/rules/unused_variable.rs
  crates/ruff_linter/src/rules/pygrep_hooks/rules/blanket_type_ignore.rs
  crates/ruff_linter/src/rules/pylint/rules/empty_comment.rs
  crates/ruff_linter/src/rules/pylint/rules/if_stmt_min_max.rs
  crates/ruff_linter/src/rules/pylint/rules/nested_min_max.rs
  crates/ruff_linter/src/rules/pylint/rules/subprocess_run_without_check.rs
  crates/ruff_linter/src/rules/pylint/rules/unspecified_encoding.rs
  crates/ruff_linter/src/rules/pyupgrade/rules/f_strings.rs
  crates/ruff_linter/src/rules/pyupgrade/rules/unnecessary_coding_comment.rs
  crates/ruff_linter/src/rules/pyupgrade/rules/yield_in_for_loop.rs
  crates/ruff_linter/src/rules/refurb/rules/if_exp_instead_of_or_operator.rs
  crates/ruff_linter/src/rules/refurb/rules/repeated_append.rs
  crates/ruff_linter/src/rules/refurb/rules/single_item_membership_test.rs
  crates/ruff_linter/src/rules/ruff/rules/collection_literal_concatenation.rs
  crates/ruff_linter/src/rules/ruff/rules/invalid_formatter_suppression_comment.rs
  crates/ruff_linter/src/rules/ruff/rules/parenthesize_logical_operators.rs
  crates/ruff_linter/src/rules/ruff/rules/quadratic_list_summation.rs
  crates/ruff_linter/src/rules/ruff/rules/test_rules.rs
  crates/ruff_linter/src/rules/ruff/rules/unnecessary_key_check.rs
  crates/ruff_server/src/lint.rs
Labels: internal

#11592 Update `Stylist`, `Indexer` to use tokens from parsed output
  crates/ruff_linter/src/checkers/physical_lines.rs
  crates/ruff_linter/src/directives.rs
  crates/ruff_linter/src/doc_lines.rs
  crates/ruff_linter/src/fix/edits.rs
  crates/ruff_linter/src/importer/insertion.rs
  crates/ruff_linter/src/linter.rs
  crates/ruff_linter/src/rules/pyflakes/mod.rs
  crates/ruff_linter/src/test.rs
  crates/ruff_python_codegen/src/lib.rs
  crates/ruff_python_codegen/src/stylist.rs
  crates/ruff_python_index/src/comment_ranges.rs
  crates/ruff_python_index/src/fstring_ranges.rs
  crates/ruff_python_index/src/indexer.rs
  crates/ruff_python_index/src/lib.rs
  crates/ruff_python_index/src/multiline_ranges.rs
  crates/ruff_python_parser/src/lexer.rs
  crates/ruff_python_trivia_integration_tests/tests/block_comments.rs
  crates/ruff_server/src/lint.rs
  crates/ruff_wasm/src/lib.rs
Labels: internal

#11486 [flake8-pyi] Implement PYI057
  crates/ruff_linter/resources/test/fixtures/flake8_pyi/PYI057.py
  crates/ruff_linter/resources/test/fixtures/flake8_pyi/PYI057.pyi
  crates/ruff_linter/src/checkers/ast/analyze/expression.rs
  crates/ruff_linter/src/checkers/ast/analyze/statement.rs
  crates/ruff_linter/src/codes.rs
  crates/ruff_linter/src/rules/flake8_pyi/mod.rs
  crates/ruff_linter/src/rules/flake8_pyi/rules/bytestring_usage.rs
  crates/ruff_linter/src/rules/flake8_pyi/rules/mod.rs
  crates/ruff_linter/src/rules/flake8_pyi/snapshots/ruff_linter__rules__flake8_pyi__tests__PYI057_PYI057.py.snap
  crates/ruff_linter/src/rules/flake8_pyi/snapshots/ruff_linter__rules__flake8_pyi__tests__PYI057_PYI057.pyi.snap
  ruff.schema.json
Labels: rule, preview

#11589 Windows: Statically linked C runtime
  .cargo/config.toml
Labels: windows

#11601 docs: Minor formatting typo in F401 example.
  crates/ruff/tests/snapshots/integration_test__rule_f401.snap
  crates/ruff_linter/src/rules/pyflakes/rules/unused_import.rs
Labels: internal

#11598 use owned ast and tokens in bench
  crates/ruff_benchmark/benches/linter.rs
  crates/ruff_linter/src/linter.rs
  crates/ruff_server/src/session/settings.rs
Labels: internal

#11370 fix(F822): add option to enable F822 in __init__.py files
  crates/ruff_linter/src/checkers/ast/mod.rs
  crates/ruff_linter/src/rules/pyflakes/mod.rs
  crates/ruff_linter/src/rules/pyflakes/rules/undefined_export.rs
  crates/ruff_linter/src/rules/pyflakes/snapshots/ruff_linter__rules__pyflakes__tests__preview__F822___init__.py.snap
Labels: preview

#11607 [`flake8-comprehension`] Strip parentheses around generators in C400
  crates/ruff_linter/resources/test/fixtures/flake8_comprehensions/C400.py
  crates/ruff_linter/src/rules/flake8_comprehensions/rules/unnecessary_generator_list.rs
  crates/ruff_linter/src/rules/flake8_comprehensions/snapshots/ruff_linter__rules__flake8_comprehensions__tests__C400_C400.py.snap
Labels: bug, fixes
