Repository astral-sh/ruff, pull requests merged in 2025-06, with the labels that each got.

#18238 [ty] Fix multithreading related hangs and panics
  Cargo.lock
  Cargo.toml
  crates/ty_python_semantic/resources/primer/bad.txt
  crates/ty_python_semantic/src/types.rs
  fuzz/Cargo.toml
Labels: bug, ty

#18351 [ty] Ensure `Literal` types are considered assignable to anything their `Instance` supertypes are assignable to
  crates/ty_python_semantic/resources/mdtest/type_properties/is_assignable_to.md
  crates/ty_python_semantic/src/types.rs
Labels: ty

#18414 [ty] Fix server hang after shutdown request
  crates/ty_server/src/lib.rs
  crates/ty_server/src/server.rs
  crates/ty_server/src/server/api.rs
  crates/ty_server/src/server/api/requests.rs
  crates/ty_server/src/server/api/requests/shutdown.rs
  crates/ty_server/src/server/api/traits.rs
  crates/ty_server/src/server/connection.rs
  crates/ty_server/src/server/main_loop.rs
  crates/ty_server/src/server/schedule/task.rs
  crates/ty_server/src/session.rs
Labels: server, ty

#18271 [`fastapi`] Avoid false positive for class dependencies (`FAST003`)
  crates/ruff_linter/resources/test/fixtures/fastapi/FAST003.py
  crates/ruff_linter/src/rules/fastapi/rules/fastapi_unused_path_parameter.rs
  crates/ruff_linter/src/rules/fastapi/snapshots/ruff_linter__rules__fastapi__tests__fast-api-unused-path-parameter_FAST003.py.snap
Labels: rule

#18401 Infer `list[T]` for starred target in unpacking
  crates/ty_python_semantic/resources/mdtest/attributes.md
  crates/ty_python_semantic/resources/mdtest/unpacking.md
  crates/ty_python_semantic/src/types/unpacker.rs
Labels: ty

#18324 Update editor setup docs about Neovim and Vim
  docs/editors/setup.md
Labels: documentation

#18425 Use ty's completions in playground
  crates/ty_wasm/src/lib.rs
  playground/package-lock.json
  playground/ty/src/Editor/Editor.tsx
Labels: playground, ty

#18360 [ty] Create separate `FunctionLiteral` and `FunctionType` types
  crates/ty/docs/rules.md
  crates/ty_python_semantic/src/types.rs
  crates/ty_python_semantic/src/types/call/bind.rs
  crates/ty_python_semantic/src/types/class.rs
  crates/ty_python_semantic/src/types/context.rs
  crates/ty_python_semantic/src/types/diagnostic.rs
  crates/ty_python_semantic/src/types/display.rs
  crates/ty_python_semantic/src/types/function.rs
  crates/ty_python_semantic/src/types/infer.rs
  crates/ty_python_semantic/src/types/narrow.rs
  crates/ty_python_semantic/src/types/protocol_class.rs
  crates/ty_python_semantic/src/types/signatures.rs
Labels: internal, ty

#18446 [ty] Minor cleanup for `site-packages` discovery logic
  crates/ty_python_semantic/src/site_packages.rs
Labels: internal, ty

#18382 [ty] Argument type expansion for overload call evaluation
  crates/ty_python_semantic/resources/mdtest/call/overloads.md
  crates/ty_python_semantic/src/types/call/arguments.rs
  crates/ty_python_semantic/src/types/call/bind.rs
Labels: ty

#18451 [ty] Add tests for empty list/tuple unpacking
  crates/ty_python_semantic/resources/mdtest/unpacking.md
Labels: testing, ty

#18453 [ty] Add meta-type tests for legavy TypeVars
  crates/ty_python_semantic/resources/mdtest/generics/legacy/variables.md
Labels: testing, ty

#18455 [ty] ty_ide: Hotfix for `expression_scope_id` panics
  _typos.toml
  crates/ty_ide/src/completion.rs
  crates/ty_python_semantic/src/semantic_index.rs
  crates/ty_python_semantic/src/semantic_model.rs
Labels: server, ty

#18465 [ty] Only calculate information for unresolved-reference subdiagnostic if we know we'll emit the diagnostic
  crates/ty/docs/rules.md
  crates/ty_python_semantic/resources/mdtest/snapshots/attributes.md_-_Attributes_-_Invalid_access_to_at…_(5457445ffed43a87).snap
  crates/ty_python_semantic/src/types/diagnostic.rs
  crates/ty_python_semantic/src/types/infer.rs
Labels: internal, performance, ty

#18041 [ty] type narrowing by attribute/subscript assignments
  crates/ty_project/resources/test/corpus/sub_exprs_not_found_in_evaluate_expr_compare.py
  crates/ty_python_semantic/resources/mdtest/attributes.md
  crates/ty_python_semantic/resources/mdtest/descriptor_protocol.md
  crates/ty_python_semantic/resources/mdtest/narrow/assignment.md
  crates/ty_python_semantic/resources/mdtest/narrow/conditionals/nested.md
  crates/ty_python_semantic/src/dunder_all.rs
  crates/ty_python_semantic/src/lib.rs
  crates/ty_python_semantic/src/place.rs
  crates/ty_python_semantic/src/semantic_index.rs
  crates/ty_python_semantic/src/semantic_index/ast_ids.rs
  crates/ty_python_semantic/src/semantic_index/builder.rs
  crates/ty_python_semantic/src/semantic_index/definition.rs
  crates/ty_python_semantic/src/semantic_index/expression.rs
  crates/ty_python_semantic/src/semantic_index/narrowing_constraints.rs
  crates/ty_python_semantic/src/semantic_index/place.rs
  crates/ty_python_semantic/src/semantic_index/predicate.rs
  crates/ty_python_semantic/src/semantic_index/symbol.rs
  crates/ty_python_semantic/src/semantic_index/use_def.rs
  crates/ty_python_semantic/src/semantic_index/use_def/place_state.rs
  crates/ty_python_semantic/src/semantic_index/visibility_constraints.rs
  crates/ty_python_semantic/src/semantic_model.rs
  crates/ty_python_semantic/src/types.rs
  crates/ty_python_semantic/src/types/call/bind.rs
  crates/ty_python_semantic/src/types/class.rs
  crates/ty_python_semantic/src/types/context.rs
  crates/ty_python_semantic/src/types/display.rs
  crates/ty_python_semantic/src/types/function.rs
  crates/ty_python_semantic/src/types/ide_support.rs
  crates/ty_python_semantic/src/types/infer.rs
  crates/ty_python_semantic/src/types/instance.rs
  crates/ty_python_semantic/src/types/narrow.rs
  crates/ty_python_semantic/src/types/property_tests/type_generation.rs
  crates/ty_python_semantic/src/types/protocol_class.rs
  crates/ty_python_semantic/src/types/signatures.rs
  crates/ty_python_semantic/src/types/slots.rs
  crates/ty_python_semantic/src/types/subclass_of.rs
  crates/ty_python_semantic/src/types/unpacker.rs
  crates/ty_python_semantic/src/unpack.rs
Labels: ty

#18457 [ty] Fix `--python` argument for Windows, and improve error messages for bad `--python` arguments
  crates/ruff/tests/analyze_graph.rs
  crates/ruff_graph/src/db.rs
  crates/ty/tests/cli.rs
  crates/ty_project/src/metadata/options.rs
  crates/ty_python_semantic/src/module_resolver/resolver.rs
  crates/ty_python_semantic/src/program.rs
  crates/ty_python_semantic/src/site_packages.rs
  crates/ty_test/src/lib.rs
Labels: ty

#18471 Combine lint and syntax error handling
  crates/ruff_server/src/lint.rs
  crates/ruff_wasm/src/lib.rs
Labels: internal, diagnostics

#18468 [ty] IDE: add support for `object.<CURSOR>` completions
  crates/ty_ide/src/completion.rs
  crates/ty_python_semantic/src/semantic_model.rs
  crates/ty_python_semantic/src/types.rs
  crates/ty_python_semantic/src/types/ide_support.rs
  crates/ty_server/src/server.rs
  playground/ty/src/Editor/Editor.tsx
Labels: server, ty

#18480 [ty] Fix completion order in playground
  playground/ty/src/Editor/Editor.tsx
Labels: playground, ty

#18489 [ty] remove unnecessary Either
  crates/ty_python_semantic/src/types/infer.rs
Labels: ty

#18483 [ty] Track the origin of the `environment.python` setting for better error messages
  Cargo.lock
  crates/ruff/tests/analyze_graph.rs
  crates/ty/tests/cli.rs
  crates/ty_project/src/metadata/options.rs
  crates/ty_project/src/metadata/value.rs
  crates/ty_python_semantic/Cargo.toml
  crates/ty_python_semantic/src/module_resolver/resolver.rs
  crates/ty_python_semantic/src/program.rs
  crates/ty_python_semantic/src/site_packages.rs
Labels: ty

#18430 [ty] Unify `Type::is_subtype_of()` and `Type::is_assignable_to()`
  crates/ty_python_semantic/resources/mdtest/intersection_types.md
  crates/ty_python_semantic/resources/mdtest/protocols.md
  crates/ty_python_semantic/resources/mdtest/type_properties/is_assignable_to.md
  crates/ty_python_semantic/src/types.rs
  crates/ty_python_semantic/src/types/class.rs
  crates/ty_python_semantic/src/types/class_base.rs
  crates/ty_python_semantic/src/types/function.rs
  crates/ty_python_semantic/src/types/generics.rs
  crates/ty_python_semantic/src/types/instance.rs
  crates/ty_python_semantic/src/types/signatures.rs
  crates/ty_python_semantic/src/types/subclass_of.rs
Labels: ty

#18531 [ty] Enable more corpus tests
  crates/ty_project/tests/check.rs
Labels: testing, ty

#18532 Treat `ty: ` comments as pragma comments
  crates/ruff_python_formatter/resources/test/fixtures/ruff/trailing_comments.py
  crates/ruff_python_formatter/tests/snapshots/format@trailing_comments.py.snap
  crates/ruff_python_trivia/src/pragmas.rs
Labels: rule, formatter

#18535 [ty] Fix panic when trying to pull types for attribute expressions inside `Literal` type expressions
  crates/ty_project/resources/test/corpus/literal_slices.py
  crates/ty_project/tests/check.rs
  crates/ty_python_semantic/src/types/infer.rs
Labels: ty

#18538 [ty] Introduce and use `System::env_var` for better test isolation
  crates/ruff_db/src/system.rs
  crates/ruff_db/src/system/os.rs
  crates/ty_project/src/metadata/options.rs
  crates/ty_server/src/system.rs
Labels: testing, ty

#18542 Add trailing space around `readlines`
  crates/ruff_linter/resources/test/fixtures/refurb/FURB129.py
  crates/ruff_linter/src/rules/refurb/rules/readlines_in_for.rs
  crates/ruff_linter/src/rules/refurb/snapshots/ruff_linter__rules__refurb__tests__FURB129_FURB129.py.snap
  crates/ruff_linter/src/rules/refurb/snapshots/ruff_linter__rules__refurb__tests__preview__FURB129_FURB129.py.snap
Labels: bug, fixes

#18543 [ty] Add hints to `invalid-type-form` for common mistakes
  crates/ty_python_semantic/resources/mdtest/annotations/annotated.md
  crates/ty_python_semantic/resources/mdtest/annotations/callable.md
  crates/ty_python_semantic/resources/mdtest/annotations/invalid.md
  crates/ty_python_semantic/resources/mdtest/snapshots/invalid.md_-_Tests_for_invalid_ty…_-_Diagnostics_for_comm…_-_List-literal_used_wh…_(f80dbf5dd571c940).snap
  crates/ty_python_semantic/resources/mdtest/snapshots/invalid.md_-_Tests_for_invalid_ty…_-_Diagnostics_for_comm…_-_Tuple-literal_used_w…_(f61204fc81905069).snap
  crates/ty_python_semantic/src/types/diagnostic.rs
  crates/ty_python_semantic/src/types/infer.rs
Labels: ty

#18573 Refactor fix in `readlines-in-for`
  crates/ruff_linter/resources/test/fixtures/refurb/FURB129.py
  crates/ruff_linter/src/rules/refurb/rules/readlines_in_for.rs
  crates/ruff_linter/src/rules/refurb/snapshots/ruff_linter__rules__refurb__tests__FURB129_FURB129.py.snap
  crates/ruff_linter/src/rules/refurb/snapshots/ruff_linter__rules__refurb__tests__preview__FURB129_FURB129.py.snap
Labels: internal

#18534 [ty] Fix panic when trying to pull types for subscript expressions inside `Callable` type expressions
  crates/ty_project/resources/test/corpus/callable_with_concatenate.py
  crates/ty_project/tests/check.rs
  crates/ty_python_semantic/resources/mdtest/annotations/callable.md
  crates/ty_python_semantic/src/types/infer.rs
Labels: ty

#18551 `ruff/__main__.py`: Remove unnecessary `os.fsdecode`
  python/ruff/__main__.py
Labels: internal

#18515 [pyupgrade] Stabilize private-type-parameter (UP049)
  crates/ruff_linter/src/codes.rs
Labels: rule

#18592 [`refurb`] Parenthesize lambda and ternary expressions in iter (`FURB122`, `FURB142`)
  crates/ruff_linter/resources/test/fixtures/refurb/FURB122.py
  crates/ruff_linter/resources/test/fixtures/refurb/FURB142.py
  crates/ruff_linter/src/rules/refurb/rules/for_loop_set_mutations.rs
  crates/ruff_linter/src/rules/refurb/rules/for_loop_writes.rs
  crates/ruff_linter/src/rules/refurb/rules/helpers.rs
  crates/ruff_linter/src/rules/refurb/snapshots/ruff_linter__rules__refurb__tests__FURB122_FURB122.py.snap
  crates/ruff_linter/src/rules/refurb/snapshots/ruff_linter__rules__refurb__tests__FURB142_FURB142.py.snap
Labels: bug, fixes

#18517 [`flake8-logging`] Stabilize `exc-info-outside-except-handler` (`LOG014`)
  crates/ruff_linter/src/codes.rs
Labels: rule

#18540 [ty] Add support for global __debug__ constant
  crates/ty_python_semantic/resources/mdtest/scopes/global-constants.md
  crates/ty_python_semantic/src/place.rs
Labels: ty

#18428 [`flake8-return`] Fix `RET504` autofix generating a syntax error
  crates/ruff_linter/resources/test/fixtures/flake8_return/RET504.py
  crates/ruff_linter/src/rules/flake8_return/rules/function.rs
  crates/ruff_linter/src/rules/flake8_return/snapshots/ruff_linter__rules__flake8_return__tests__RET504_RET504.py.snap
Labels: bug, fixes

#18550 [ty] Infer the Python version from `--python=<system installation>` on Unix
  Cargo.lock
  crates/ruff_python_ast/Cargo.toml
  crates/ruff_python_ast/src/python_version.rs
  crates/ty/docs/cli.md
  crates/ty/docs/configuration.md
  crates/ty/src/args.rs
  crates/ty/tests/cli/python_environment.rs
  crates/ty_project/src/metadata/options.rs
  crates/ty_python_semantic/src/module_resolver/resolver.rs
  crates/ty_python_semantic/src/module_resolver/typeshed.rs
  crates/ty_python_semantic/src/program.rs
  crates/ty_python_semantic/src/util/diagnostics.rs
  ty.schema.json
Labels: ty

#18636 Update salsa
  Cargo.lock
  Cargo.toml
  fuzz/Cargo.toml
Labels: ty

#18478 [`pyupgrade`] Fix `super(__class__, self)` detection in UP008 (super-call-with-parameters)
  crates/ruff_linter/resources/test/fixtures/pyupgrade/UP008.py
  crates/ruff_linter/src/rules/pyupgrade/rules/super_call_with_parameters.rs
  crates/ruff_linter/src/rules/pyupgrade/snapshots/ruff_linter__rules__pyupgrade__tests__UP008.py.snap
Labels: rule

#18539 [ty] Pull types on synthesized Python files created by mdtest
  Cargo.lock
  crates/ty_python_semantic/Cargo.toml
  crates/ty_python_semantic/resources/mdtest/annotations/any.md
  crates/ty_python_semantic/resources/mdtest/annotations/callable.md
  crates/ty_python_semantic/resources/mdtest/type_api.md
  crates/ty_python_semantic/resources/mdtest/type_qualifiers/classvar.md
  crates/ty_python_semantic/resources/mdtest/type_qualifiers/final.md
  crates/ty_python_semantic/src/lib.rs
  crates/ty_python_semantic/src/pull_types.rs
  crates/ty_python_semantic/src/types/infer.rs
  crates/ty_python_semantic/tests/corpus.rs
  crates/ty_test/Cargo.toml
  crates/ty_test/src/lib.rs
  crates/ty_test/src/parser.rs
Labels: testing, ty

#18617 [`flake8-bandit`] Remove `suspicious-xmle-tree-usage` (`S320`)
  crates/ruff_linter/src/codes.rs
  crates/ruff_linter/src/rules/flake8_bandit/rules/suspicious_function_call.rs
  ruff.schema.json
Labels: rule, breaking

#18623 Centralize client options validation
  crates/ruff_server/src/lib.rs
  crates/ruff_server/src/server.rs
  crates/ruff_server/src/session.rs
  crates/ruff_server/src/session/index.rs
  crates/ruff_server/src/session/index/ruff_settings.rs
  crates/ruff_server/src/session/options.rs
  crates/ruff_server/src/session/settings.rs
  crates/ruff_server/src/workspace.rs
  crates/ruff_server/tests/notebook.rs
Labels: server

#18479 [`pycodestyle`] Fix `E731` autofix creating a syntax error for expressions spanned across multiple lines
  crates/ruff_linter/resources/test/fixtures/pycodestyle/E731.py
  crates/ruff_linter/src/rules/pycodestyle/rules/lambda_assignment.rs
  crates/ruff_linter/src/rules/pycodestyle/snapshots/ruff_linter__rules__pycodestyle__tests__E731_E731.py.snap
Labels: bug, fixes

#18408 Fix false positive in for mutations in return statements (B909)
  crates/ruff_linter/resources/test/fixtures/flake8_bugbear/B909.py
  crates/ruff_linter/src/rules/flake8_bugbear/rules/loop_iterator_mutation.rs
Labels: rule

#18670 [ty] Avoid accessing class literal with incorrect AST
  crates/ty_python_semantic/src/types/class.rs
  crates/ty_python_semantic/src/types/diagnostic.rs
Labels: ty

#18673 Fix `\r` and `\r\n` handling in t- and f-string debug texts
  .gitattributes
  crates/ruff_python_formatter/resources/test/fixtures/ruff/.editorconfig
  crates/ruff_python_formatter/resources/test/fixtures/ruff/f-string-carriage-return-newline.py
  crates/ruff_python_formatter/src/other/interpolated_string_element.rs
  crates/ruff_python_formatter/tests/normalizer.rs
  crates/ruff_python_formatter/tests/snapshots/format@f-string-carriage-return-newline.py.snap
Labels: bug, formatter

#18702 [ty] Correctly label typeshed-sync PRs
  .github/workflows/sync_typeshed.yaml
Labels: ci, ty

#18311 [`flake8-pyi`] Fix `custom-typevar-for-self` with string annotations (`PYI019`)
  crates/ruff_linter/resources/test/fixtures/flake8_pyi/PYI019_0.py
  crates/ruff_linter/resources/test/fixtures/flake8_pyi/PYI019_0.pyi
  crates/ruff_linter/src/rules/flake8_pyi/rules/custom_type_var_for_self.rs
  crates/ruff_linter/src/rules/flake8_pyi/snapshots/ruff_linter__rules__flake8_pyi__tests__PYI019_PYI019_0.py.snap
  crates/ruff_linter/src/rules/flake8_pyi/snapshots/ruff_linter__rules__flake8_pyi__tests__PYI019_PYI019_0.pyi.snap
Labels: rule

#17368 [`ruff`] Check for non-context-manager use of `pytest.raises`, `pytest.warns`, and `pytest.deprecated_call` (`RUF061`)
  crates/ruff_linter/resources/test/fixtures/ruff/RUF061_deprecated_call.py
  crates/ruff_linter/resources/test/fixtures/ruff/RUF061_raises.py
  crates/ruff_linter/resources/test/fixtures/ruff/RUF061_warns.py
  crates/ruff_linter/src/checkers/ast/analyze/expression.rs
  crates/ruff_linter/src/codes.rs
  crates/ruff_linter/src/rules/ruff/mod.rs
  crates/ruff_linter/src/rules/ruff/rules/legacy_form_pytest_raises.rs
  crates/ruff_linter/src/rules/ruff/rules/mod.rs
  crates/ruff_linter/src/rules/ruff/snapshots/ruff_linter__rules__ruff__tests__RUF061_RUF061_deprecated_call.py.snap
  crates/ruff_linter/src/rules/ruff/snapshots/ruff_linter__rules__ruff__tests__RUF061_RUF061_raises.py.snap
  crates/ruff_linter/src/rules/ruff/snapshots/ruff_linter__rules__ruff__tests__RUF061_RUF061_warns.py.snap
  ruff.schema.json
Labels: rule, preview

#18711 [ty] Use more parallelism when running corpus tests
  crates/ty_python_semantic/tests/corpus.rs
Labels: testing, ty

#18687 [ty] allow `T: Never` as subtype of `Never`
  crates/ty_python_semantic/resources/mdtest/type_compendium/never.md
  crates/ty_python_semantic/resources/mdtest/type_properties/materialization.md
  crates/ty_python_semantic/src/types.rs
Labels: ty

#18645 [`refurb`] Make the fix for `FURB163` unsafe for `log2`, `log10`, `*args`, and deleted comments
  crates/ruff_linter/resources/test/fixtures/refurb/FURB163.py
  crates/ruff_linter/src/rules/refurb/rules/redundant_log_base.rs
  crates/ruff_linter/src/rules/refurb/snapshots/ruff_linter__rules__refurb__tests__FURB163_FURB163.py.snap
Labels: fixes

#18665 [pylint] Fix `PLW0128` to check assignment targets in square brackets and after asterisks
  crates/ruff_linter/resources/test/fixtures/pylint/redeclared_assigned_name.py
  crates/ruff_linter/src/rules/pylint/rules/redeclared_assigned_name.rs
  crates/ruff_linter/src/rules/pylint/snapshots/ruff_linter__rules__pylint__tests__PLW0128_redeclared_assigned_name.py.snap
Labels: bug, rule

#18707 [ty] Fix panic when attempting to provide autocompletions for an instance of a class that assigns attributes to `self[0]`
  crates/ty_ide/src/completion.rs
  crates/ty_python_semantic/src/semantic_index/builder.rs
  crates/ty_python_semantic/src/semantic_index/place.rs
  crates/ty_python_semantic/src/types/ide_support.rs
Labels: bug, ty

#18704 Hug closing `}` when f-string expression has a format specifier
  crates/ruff_python_formatter/resources/test/fixtures/ruff/expression/fstring.py
  crates/ruff_python_formatter/resources/test/fixtures/ruff/expression/tstring.py
  crates/ruff_python_formatter/src/comments/placement.rs
  crates/ruff_python_formatter/src/context.rs
  crates/ruff_python_formatter/src/other/interpolated_string.rs
  crates/ruff_python_formatter/src/other/interpolated_string_element.rs
  crates/ruff_python_formatter/src/string/normalize.rs
  crates/ruff_python_formatter/tests/snapshots/black_compatibility@cases__pep_701.py.snap
  crates/ruff_python_formatter/tests/snapshots/format@expression__fstring.py.snap
  crates/ruff_python_formatter/tests/snapshots/format@expression__tstring.py.snap
  crates/ty_python_semantic/src/python_platform.rs
Labels: bug, formatter

#18230 [ty] Add `python.ty.disableLanguageServices` config
  crates/ty_server/src/lib.rs
  crates/ty_server/src/server.rs
  crates/ty_server/src/server/api/requests/completion.rs
  crates/ty_server/src/server/api/requests/goto_type_definition.rs
  crates/ty_server/src/server/api/requests/hover.rs
  crates/ty_server/src/server/api/requests/inlay_hints.rs
  crates/ty_server/src/session.rs
  crates/ty_server/src/session/index.rs
  crates/ty_server/src/session/options.rs
  crates/ty_server/src/session/settings.rs
Labels: server, ty

#18642 [ty] Fix panics when pulling types for various special forms that have the wrong number of parameters
  crates/ty_python_semantic/resources/mdtest/annotations/any.md
  crates/ty_python_semantic/resources/mdtest/type_api.md
  crates/ty_python_semantic/src/types/diagnostic.rs
  crates/ty_python_semantic/src/types/infer.rs
Labels: bug, ty

#18705 [ty] Offer "Did you mean...?" suggestions for unresolved `from` imports and unresolved attributes
  _typos.toml
  crates/ty/docs/rules.md
  crates/ty_python_semantic/resources/mdtest/attributes.md
  crates/ty_python_semantic/resources/mdtest/import/basic.md
  crates/ty_python_semantic/resources/mdtest/snapshots/attributes.md_-_Attributes_-_Suggestions_for_obvi…_(bf7b28ef99f0ec16).snap
  crates/ty_python_semantic/resources/mdtest/snapshots/basic.md_-_Structures_-_`from`_import_that_h…_(3caffc60d8390adf).snap
  crates/ty_python_semantic/src/semantic_model.rs
  crates/ty_python_semantic/src/types.rs
  crates/ty_python_semantic/src/types/all_members.rs
  crates/ty_python_semantic/src/types/call/bind.rs
  crates/ty_python_semantic/src/types/class.rs
  crates/ty_python_semantic/src/types/diagnostic.rs
  crates/ty_python_semantic/src/types/diagnostic/levenshtein.rs
  crates/ty_python_semantic/src/types/infer.rs
Labels: ty, diagnostics

#18721 Revert "[ty] Offer "Did you mean...?" suggestions for unresolved `from` imports and unresolved attributes (#18705)"
  _typos.toml
  crates/ty/docs/rules.md
  crates/ty_python_semantic/resources/mdtest/attributes.md
  crates/ty_python_semantic/resources/mdtest/import/basic.md
  crates/ty_python_semantic/resources/mdtest/snapshots/attributes.md_-_Attributes_-_Suggestions_for_obvi…_(bf7b28ef99f0ec16).snap
  crates/ty_python_semantic/resources/mdtest/snapshots/basic.md_-_Structures_-_`from`_import_that_h…_(3caffc60d8390adf).snap
  crates/ty_python_semantic/src/semantic_model.rs
  crates/ty_python_semantic/src/types.rs
  crates/ty_python_semantic/src/types/call/bind.rs
  crates/ty_python_semantic/src/types/class.rs
  crates/ty_python_semantic/src/types/diagnostic.rs
  crates/ty_python_semantic/src/types/diagnostic/levenshtein.rs
  crates/ty_python_semantic/src/types/ide_support.rs
  crates/ty_python_semantic/src/types/infer.rs
Labels: ty

#18663 [ty] fix 'BitwiseAnd' bug
  crates/ty_python_semantic/resources/mdtest/binary/booleans.md
  crates/ty_python_semantic/src/types/infer.rs
Labels: ty

#18718 Use updated pre-commit id
  README.md
Labels: documentation

#18685 [ty] Anchor all exclude patterns
  crates/ty/docs/configuration.md
  crates/ty/src/args.rs
  crates/ty/tests/cli/file_selection.rs
  crates/ty_project/src/glob.rs
  crates/ty_project/src/glob/exclude.rs
  crates/ty_project/src/glob/include.rs
  crates/ty_project/src/glob/portable.rs
  crates/ty_project/src/metadata/options.rs
  crates/ty_project/src/metadata/value.rs
  ty.schema.json
Labels: configuration, ty

#18714 [ty] Add more benchmarks
  .github/actionlint.yaml
  .github/workflows/ci.yaml
  Cargo.lock
  Cargo.toml
  crates/ruff_benchmark/Cargo.toml
  crates/ruff_benchmark/benches/ty.rs
  crates/ruff_benchmark/benches/ty_walltime.rs
  crates/ruff_benchmark/src/lib.rs
  crates/ruff_benchmark/src/real_world_projects.rs
  crates/ruff_db/src/lib.rs
  crates/ruff_db/src/system/test.rs
  crates/ty_project/src/lib.rs
Labels: testing, ty

#18758 Run ty benchmarks when `ruff_benchmark` changes
  .github/workflows/ci.yaml
Labels: testing, ty

#18780 Mark `RET501` fix unsafe if comments are inside
  crates/ruff_linter/resources/test/fixtures/flake8_return/RET501.py
  crates/ruff_linter/src/rules/flake8_return/rules/function.rs
  crates/ruff_linter/src/rules/flake8_return/snapshots/ruff_linter__rules__flake8_return__tests__RET501_RET501.py.snap
Labels: fixes

#18541 Add lint rule for calling chmod with non-octal integers
  crates/ruff_linter/resources/test/fixtures/ruff/RUF064.py
  crates/ruff_linter/src/checkers/ast/analyze/expression.rs
  crates/ruff_linter/src/codes.rs
  crates/ruff_linter/src/rules/ruff/mod.rs
  crates/ruff_linter/src/rules/ruff/rules/mod.rs
  crates/ruff_linter/src/rules/ruff/rules/non_octal_permissions.rs
  crates/ruff_linter/src/rules/ruff/snapshots/ruff_linter__rules__ruff__tests__RUF064_RUF064.py.snap
  ruff.schema.json
Labels: rule

#18779 Enforce `pytest` import for decorators
  crates/ruff_linter/resources/test/fixtures/flake8_pytest_style/PT023.py
  crates/ruff_linter/src/rules/flake8_pytest_style/rules/fixture.rs
  crates/ruff_linter/src/rules/flake8_pytest_style/rules/helpers.rs
  crates/ruff_linter/src/rules/flake8_pytest_style/rules/marks.rs
  crates/ruff_linter/src/rules/flake8_pytest_style/snapshots/ruff_linter__rules__flake8_pytest_style__tests__PT023_default.snap
  crates/ruff_linter/src/rules/flake8_pytest_style/snapshots/ruff_linter__rules__flake8_pytest_style__tests__PT023_parentheses.snap
Labels: bug

#18755 [`flake8-bugbear`] Mark autofix for `B004` as unsafe if the `hasattr` call expr contains comments
  crates/ruff_linter/resources/test/fixtures/flake8_bugbear/B004.py
  crates/ruff_linter/src/rules/flake8_bugbear/rules/unreliable_callable_check.rs
  crates/ruff_linter/src/rules/flake8_bugbear/snapshots/ruff_linter__rules__flake8_bugbear__tests__B004_B004.py.snap
Labels: fixes

#18753 [`flake8-async`] Mark autofix for `ASYNC115` as unsafe if the call expression contains comments
  crates/ruff_linter/resources/test/fixtures/flake8_async/ASYNC115.py
  crates/ruff_linter/src/rules/flake8_async/rules/async_zero_sleep.rs
  crates/ruff_linter/src/rules/flake8_async/snapshots/ruff_linter__rules__flake8_async__tests__ASYNC115_ASYNC115.py.snap
Labels: fixes

#18792 [`flake8-pytest-style`] Mark autofix for `PT001` and `PT023` as unsafe if there's comments in the decorator
  crates/ruff_linter/resources/test/fixtures/flake8_pytest_style/PT001.py
  crates/ruff_linter/resources/test/fixtures/flake8_pytest_style/PT023.py
  crates/ruff_linter/src/rules/flake8_pytest_style/rules/fixture.rs
  crates/ruff_linter/src/rules/flake8_pytest_style/rules/marks.rs
  crates/ruff_linter/src/rules/flake8_pytest_style/snapshots/ruff_linter__rules__flake8_pytest_style__tests__PT001_default.snap
  crates/ruff_linter/src/rules/flake8_pytest_style/snapshots/ruff_linter__rules__flake8_pytest_style__tests__PT023_default.snap
Labels: bug, fixes

#18666 unnecessary_dict_kwargs doc - a note on type checking benefits
  crates/ruff_linter/src/rules/flake8_pie/rules/unnecessary_dict_kwargs.rs
Labels: documentation

#18809 [ty] Add support for `@staticmethod`s
  crates/ty_python_semantic/resources/mdtest/call/methods.md
  crates/ty_python_semantic/resources/mdtest/descriptor_protocol.md
  crates/ty_python_semantic/resources/mdtest/overloads.md
  crates/ty_python_semantic/src/types/call/bind.rs
  crates/ty_python_semantic/src/types/class.rs
  crates/ty_python_semantic/src/types/function.rs
  crates/ty_python_semantic/src/types/infer.rs
Labels: ty

#18719 [ty] ecosystem-analyzer workflow
  .github/workflows/ty-ecosystem-analyzer.yaml
Labels: ci, ty, ecosystem-analyzer

#18819 [ty] Use `HashTable` in `PlaceTable`
  crates/ty_python_semantic/src/semantic_index.rs
  crates/ty_python_semantic/src/semantic_index/place.rs
Labels: internal, ty

#16885 [`pylint`] Avoid flattening nested `min`/`max` when outer call has single argument (`PLW3301`)
  crates/ruff_linter/resources/test/fixtures/pylint/nested_min_max.py
  crates/ruff_linter/src/rules/pylint/rules/nested_min_max.rs
Labels: bug, rule

#18794 [`flake8-simplify`] Fix false negatives for shadowed bindings (`SIM910`, `SIM911`)
  crates/ruff_linter/resources/test/fixtures/flake8_simplify/SIM910.py
  crates/ruff_linter/resources/test/fixtures/flake8_simplify/SIM911.py
  crates/ruff_linter/src/rules/flake8_simplify/mod.rs
  crates/ruff_linter/src/rules/flake8_simplify/rules/ast_expr.rs
  crates/ruff_linter/src/rules/flake8_simplify/rules/zip_dict_keys_and_values.rs
  crates/ruff_linter/src/rules/flake8_simplify/snapshots/ruff_linter__rules__flake8_simplify__tests__SIM910_SIM910.py.snap
  crates/ruff_linter/src/rules/flake8_simplify/snapshots/ruff_linter__rules__flake8_simplify__tests__SIM911_SIM911.py.snap
Labels: bug

#18829 [`flake8-pie`] Small docs fix to `PIE794`
  crates/ruff_linter/src/rules/flake8_pie/rules/duplicate_class_field_definition.rs
Labels: documentation

#18637 [`flake8_pyi`] Fix `PYI041`'s fix causing TypeError with `None | None | ...`
  crates/ruff_linter/resources/test/fixtures/flake8_pyi/PYI041_1.py
  crates/ruff_linter/resources/test/fixtures/flake8_pyi/PYI041_1.pyi
  crates/ruff_linter/resources/test/fixtures/flake8_pyi/PYI041_2.py
  crates/ruff_linter/src/rules/flake8_pyi/mod.rs
  crates/ruff_linter/src/rules/flake8_pyi/rules/redundant_numeric_union.rs
  crates/ruff_linter/src/rules/flake8_pyi/snapshots/ruff_linter__rules__flake8_pyi__tests__PYI041_PYI041.py.snap
  crates/ruff_linter/src/rules/flake8_pyi/snapshots/ruff_linter__rules__flake8_pyi__tests__PYI041_PYI041_1.py.snap
  crates/ruff_linter/src/rules/flake8_pyi/snapshots/ruff_linter__rules__flake8_pyi__tests__PYI041_PYI041_1.pyi.snap
  crates/ruff_linter/src/rules/flake8_pyi/snapshots/ruff_linter__rules__flake8_pyi__tests__PYI041_PYI041_2.py.snap
Labels: bug, fixes

#18831 Docs normalization
  crates/ruff_linter/src/rules/fastapi/rules/fastapi_redundant_response_model.rs
  crates/ruff_linter/src/rules/flake8_builtins/rules/builtin_import_shadowing.rs
  crates/ruff_linter/src/rules/flake8_pie/rules/duplicate_class_field_definition.rs
  crates/ruff_linter/src/rules/flake8_pyi/rules/custom_type_var_for_self.rs
  crates/ruff_linter/src/rules/flake8_pytest_style/rules/assertion.rs
  crates/ruff_linter/src/rules/flake8_return/rules/function.rs
  crates/ruff_linter/src/rules/flake8_simplify/rules/ast_with.rs
  crates/ruff_linter/src/rules/flake8_simplify/rules/reimplemented_builtin.rs
  crates/ruff_linter/src/rules/flynt/rules/static_join_to_fstring.rs
  crates/ruff_linter/src/rules/pycodestyle/rules/ambiguous_variable_name.rs
  crates/ruff_linter/src/rules/pycodestyle/rules/trailing_whitespace.rs
  crates/ruff_linter/src/rules/pycodestyle/rules/whitespace_after_decorator.rs
  crates/ruff_linter/src/rules/pylint/rules/dict_index_missing_items.rs
  crates/ruff_linter/src/rules/pylint/rules/missing_maxsplit_arg.rs
  crates/ruff_linter/src/rules/pylint/rules/nan_comparison.rs
  crates/ruff_linter/src/rules/pylint/rules/redeclared_assigned_name.rs
  crates/ruff_linter/src/rules/pylint/rules/redefined_argument_from_local.rs
  crates/ruff_linter/src/rules/pylint/rules/unnecessary_dunder_call.rs
  crates/ruff_linter/src/rules/pyupgrade/rules/replace_str_enum.rs
  crates/ruff_linter/src/rules/refurb/rules/implicit_cwd.rs
  crates/ruff_linter/src/rules/refurb/rules/regex_flag_alias.rs
  crates/ruff_linter/src/rules/ruff/rules/decimal_from_float_literal.rs
  crates/ruff_linter/src/rules/ruff/rules/invalid_formatter_suppression_comment.rs
  crates/ruff_linter/src/rules/ruff/rules/unnecessary_round.rs
Labels: documentation

#18600 [ty] Homogeneous and mixed tuples
  crates/ty/docs/rules.md
  crates/ty_python_semantic/resources/mdtest/assignment/annotations.md
  crates/ty_python_semantic/resources/mdtest/attributes.md
  crates/ty_python_semantic/resources/mdtest/binary/tuples.md
  crates/ty_python_semantic/resources/mdtest/generics/legacy/functions.md
  crates/ty_python_semantic/resources/mdtest/generics/pep695/functions.md
  crates/ty_python_semantic/resources/mdtest/narrow/complex_target.md
  crates/ty_python_semantic/resources/mdtest/narrow/type_guards.md
  crates/ty_python_semantic/resources/mdtest/subscript/tuple.md
  crates/ty_python_semantic/resources/mdtest/type_compendium/tuple.md
  crates/ty_python_semantic/resources/mdtest/type_properties/is_assignable_to.md
  crates/ty_python_semantic/resources/mdtest/type_properties/is_fully_static.md
  crates/ty_python_semantic/resources/mdtest/type_properties/is_subtype_of.md
  crates/ty_python_semantic/resources/primer/bad.txt
  crates/ty_python_semantic/resources/primer/good.txt
  crates/ty_python_semantic/src/types.rs
  crates/ty_python_semantic/src/types/call/arguments.rs
  crates/ty_python_semantic/src/types/call/bind.rs
  crates/ty_python_semantic/src/types/class.rs
  crates/ty_python_semantic/src/types/class_base.rs
  crates/ty_python_semantic/src/types/diagnostic.rs
  crates/ty_python_semantic/src/types/display.rs
  crates/ty_python_semantic/src/types/generics.rs
  crates/ty_python_semantic/src/types/ide_support.rs
  crates/ty_python_semantic/src/types/infer.rs
  crates/ty_python_semantic/src/types/instance.rs
  crates/ty_python_semantic/src/types/narrow.rs
  crates/ty_python_semantic/src/types/property_tests/type_generation.rs
  crates/ty_python_semantic/src/types/slots.rs
  crates/ty_python_semantic/src/types/tuple.rs
  crates/ty_python_semantic/src/types/unpacker.rs
  crates/ty_python_semantic/src/util/subscript.rs
Labels: ty, ecosystem-analyzer

#18850 [ty] Add Tanjun benchmark
  crates/ruff_benchmark/benches/ty_walltime.rs
Labels: testing, ty

#18832 [`pylint`] Mark `PLE0241` autofix as unsafe if there's comments in the base classes
  crates/ruff_linter/resources/test/fixtures/pylint/duplicate_bases.py
  crates/ruff_linter/src/rules/pylint/rules/duplicate_bases.rs
  crates/ruff_linter/src/rules/pylint/snapshots/ruff_linter__rules__pylint__tests__PLE0241_duplicate_bases.py.snap
Labels: bug, fixes

#18827 [ty] Support `--python=<symlink to executable>`
  crates/ty/tests/cli/main.rs
  crates/ty/tests/cli/python_environment.rs
  crates/ty_python_semantic/src/site_packages.rs
Labels: bug, ty

#18858 [`refurb`] Mark `FURB129` autofix as unsafe if there's comments in the `readlines` call
  crates/ruff_linter/resources/test/fixtures/refurb/FURB129.py
  crates/ruff_linter/src/rules/refurb/rules/readlines_in_for.rs
  crates/ruff_linter/src/rules/refurb/snapshots/ruff_linter__rules__refurb__tests__FURB129_FURB129.py.snap
Labels: bug, fixes

#18870 Clarify PEP 8 relationship to whitespace-around-operator rules
  crates/ruff_linter/src/rules/pycodestyle/rules/logical_lines/missing_whitespace_around_operator.rs
Labels: documentation

#18871 Remove extra dot in rule documentation
  crates/ruff_linter/src/rules/pylint/rules/duplicate_bases.rs
  crates/ty_test/src/config.rs
Labels: documentation

#18782 [`flake8-pytest-style`] PT001/PT023 fix makes syntax error on parenthesized decorator
  crates/ruff_linter/resources/test/fixtures/flake8_pytest_style/PT001.py
  crates/ruff_linter/resources/test/fixtures/flake8_pytest_style/PT023.py
  crates/ruff_linter/src/rules/flake8_pytest_style/rules/fixture.rs
  crates/ruff_linter/src/rules/flake8_pytest_style/rules/marks.rs
  crates/ruff_linter/src/rules/flake8_pytest_style/snapshots/ruff_linter__rules__flake8_pytest_style__tests__PT001_default.snap
  crates/ruff_linter/src/rules/flake8_pytest_style/snapshots/ruff_linter__rules__flake8_pytest_style__tests__PT023_default.snap
Labels: bug, fixes

#18803 [`perflint`] Fix `PERF101` autofix creating a syntax error and mark autofix as unsafe if there are comments in the `list` call expr
  crates/ruff_linter/resources/test/fixtures/perflint/PERF101.py
  crates/ruff_linter/src/rules/perflint/rules/unnecessary_list_cast.rs
  crates/ruff_linter/src/rules/perflint/snapshots/ruff_linter__rules__perflint__tests__PERF101_PERF101.py.snap
Labels: bug, fixes

#18213 [`flake8-simplify`] Preserve original behavior for `except ()` and bare `except` (`SIM105`)
  crates/ruff_linter/resources/test/fixtures/flake8_simplify/SIM105_0.py
  crates/ruff_linter/src/rules/flake8_simplify/rules/suppressible_exception.rs
  crates/ruff_linter/src/rules/flake8_simplify/snapshots/ruff_linter__rules__flake8_simplify__tests__SIM105_SIM105_0.py.snap
Labels: bug, fixes

#18898 [ty] Include imported sub-modules as attributes on modules for completions
  crates/ty_ide/src/completion.rs
  crates/ty_python_semantic/src/module_name.rs
  crates/ty_python_semantic/src/types/ide_support.rs
Labels: server, ty

#18897 [ty] Avoid duplicate diagnostic in unpacking
  crates/ty_python_semantic/resources/mdtest/unpacking.md
  crates/ty_python_semantic/src/types/infer.rs
Labels: bug, ty, ecosystem-analyzer

#18900 [ty] Respect the gradual guarantee when narrowing using `isinstance()` and `issubclass()`
  crates/ty_python_semantic/resources/mdtest/narrow/isinstance.md
  crates/ty_python_semantic/resources/mdtest/narrow/issubclass.md
  crates/ty_python_semantic/src/types/narrow.rs
Labels: ty

#18910 Consider virtual path for various server actions
  crates/ruff_server/src/fix.rs
  crates/ruff_server/src/format.rs
  crates/ruff_server/src/lint.rs
  crates/ruff_server/src/server/api/requests/format.rs
  crates/ruff_server/src/server/api/requests/format_range.rs
Labels: server

#18760 [ty] Rename `src.root` setting to `environment.root`
  crates/ruff_db/src/diagnostic/mod.rs
  crates/ruff_macros/src/combine.rs
  crates/ty/docs/configuration.md
  crates/ty/src/args.rs
  crates/ty/tests/cli/python_environment.rs
  crates/ty_project/src/metadata/options.rs
  ty.schema.json
Labels: configuration, ty

#18913 [ty] Change `environment.root` to accept multiple paths
  crates/ty/docs/configuration.md
  crates/ty/tests/cli/python_environment.rs
  crates/ty_project/src/metadata/options.rs
  ty.schema.json
Labels: configuration, ty

#18915 py-fuzzer: allow relative executable paths
  python/py-fuzzer/fuzz.py
Labels: internal

#18763 [`flake8-use-pathlib`] Add autofix for `PTH202`
  crates/ruff_linter/resources/test/fixtures/flake8_use_pathlib/PTH202.py
  crates/ruff_linter/resources/test/fixtures/flake8_use_pathlib/PTH202_2.py
  crates/ruff_linter/src/checkers/ast/analyze/expression.rs
  crates/ruff_linter/src/preview.rs
  crates/ruff_linter/src/rules/flake8_use_pathlib/mod.rs
  crates/ruff_linter/src/rules/flake8_use_pathlib/rules/os_path_getsize.rs
  crates/ruff_linter/src/rules/flake8_use_pathlib/rules/replaceable_by_pathlib.rs
  crates/ruff_linter/src/rules/flake8_use_pathlib/snapshots/ruff_linter__rules__flake8_use_pathlib__tests__PTH202_PTH202.py.snap
  crates/ruff_linter/src/rules/flake8_use_pathlib/snapshots/ruff_linter__rules__flake8_use_pathlib__tests__PTH202_PTH202_2.py.snap
  crates/ruff_linter/src/rules/flake8_use_pathlib/snapshots/ruff_linter__rules__flake8_use_pathlib__tests__preview__PTH202_PTH202.py.snap
  crates/ruff_linter/src/rules/flake8_use_pathlib/snapshots/ruff_linter__rules__flake8_use_pathlib__tests__preview__PTH202_PTH202_2.py.snap
Labels: fixes, preview

#18923 Fix link typo in ty's CONTRIBUTING.md
  crates/ty/CONTRIBUTING.md
Labels: documentation

#18901 [ty] Add property test generators for variable-length tuples
  crates/ty_python_semantic/resources/mdtest/type_compendium/tuple.md
  crates/ty_python_semantic/src/types.rs
  crates/ty_python_semantic/src/types/call/bind.rs
  crates/ty_python_semantic/src/types/class.rs
  crates/ty_python_semantic/src/types/infer.rs
  crates/ty_python_semantic/src/types/property_tests/type_generation.rs
  crates/ty_python_semantic/src/types/tuple.rs
Labels: ty

#18929 [`docs`] Typo fix for playground
  playground/README.md
Labels: documentation, internal

#18924 [Internal] Use more `report_diagnostic_if_enabled`
  crates/ruff_linter/src/checkers/ast/analyze/expression.rs
  crates/ruff_linter/src/checkers/ast/analyze/statement.rs
  crates/ruff_linter/src/checkers/ast/analyze/unresolved_references.rs
  crates/ruff_linter/src/checkers/ast/mod.rs
  crates/ruff_linter/src/rules/flake8_2020/rules/compare.rs
  crates/ruff_linter/src/rules/flake8_bandit/rules/shell_injection.rs
  crates/ruff_linter/src/rules/flake8_logging_format/rules/logging_call.rs
  crates/ruff_linter/src/rules/flake8_pyi/rules/bad_version_info_comparison.rs
  crates/ruff_linter/src/rules/flake8_pyi/rules/unrecognized_platform.rs
  crates/ruff_linter/src/rules/flake8_pyi/rules/unrecognized_version_info.rs
  crates/ruff_linter/src/rules/pydocstyle/rules/not_empty.rs
  crates/ruff_linter/src/rules/pydocstyle/rules/not_missing.rs
  crates/ruff_linter/src/rules/pydocstyle/rules/sections.rs
Labels: internal

#18925 [`refurb`] Detect more exotic float literals in `FURB164`
  crates/ruff_linter/resources/test/fixtures/refurb/FURB164.py
  crates/ruff_linter/src/rules/refurb/rules/unnecessary_from_float.rs
  crates/ruff_linter/src/rules/refurb/snapshots/ruff_linter__rules__refurb__tests__FURB164_FURB164.py.snap
Labels: bug, rule

#18866 [`perflint`] Fix false negative in `PERF401`
  crates/ruff_linter/resources/test/fixtures/perflint/PERF403.py
  crates/ruff_linter/src/rules/perflint/rules/manual_dict_comprehension.rs
  crates/ruff_linter/src/rules/perflint/snapshots/ruff_linter__rules__perflint__tests__PERF403_PERF403.py.snap
  crates/ruff_linter/src/rules/perflint/snapshots/ruff_linter__rules__perflint__tests__preview__PERF403_PERF403.py.snap
Labels: bug, rule

#18903 [`flake8-future-annotations`] Add autofix (`FA100`)
  crates/ruff_linter/src/rules/flake8_future_annotations/rules/future_rewritable_type_annotation.rs
  crates/ruff_linter/src/rules/flake8_future_annotations/snapshots/ruff_linter__rules__flake8_future_annotations__tests__edge_case.py.snap
  crates/ruff_linter/src/rules/flake8_future_annotations/snapshots/ruff_linter__rules__flake8_future_annotations__tests__from_typing_import.py.snap
  crates/ruff_linter/src/rules/flake8_future_annotations/snapshots/ruff_linter__rules__flake8_future_annotations__tests__from_typing_import_many.py.snap
  crates/ruff_linter/src/rules/flake8_future_annotations/snapshots/ruff_linter__rules__flake8_future_annotations__tests__import_typing.py.snap
  crates/ruff_linter/src/rules/flake8_future_annotations/snapshots/ruff_linter__rules__flake8_future_annotations__tests__import_typing_as.py.snap
Labels: fixes

#18936 [`pylint`] Allow fix with comments and document performance implications (`PLW3301`)
  crates/ruff_linter/resources/test/fixtures/pylint/nested_min_max.py
  crates/ruff_linter/src/rules/pylint/rules/nested_min_max.rs
  crates/ruff_linter/src/rules/pylint/snapshots/ruff_linter__rules__pylint__tests__PLW3301_nested_min_max.py.snap
Labels: documentation, rule

#18937 [ty] Move search path resolution to `Options::to_program_settings`
  crates/ruff/tests/analyze_graph.rs
  crates/ruff_graph/src/db.rs
  crates/ty/tests/cli/main.rs
  crates/ty/tests/cli/python_environment.rs
  crates/ty/tests/file_watching.rs
  crates/ty_ide/src/inlay_hints.rs
  crates/ty_ide/src/lib.rs
  crates/ty_project/src/db.rs
  crates/ty_project/src/db/changes.rs
  crates/ty_project/src/lib.rs
  crates/ty_project/src/metadata.rs
  crates/ty_project/src/metadata/options.rs
  crates/ty_project/src/metadata/value.rs
  crates/ty_python_semantic/src/db.rs
  crates/ty_python_semantic/src/lib.rs
  crates/ty_python_semantic/src/module_resolver/mod.rs
  crates/ty_python_semantic/src/module_resolver/path.rs
  crates/ty_python_semantic/src/module_resolver/resolver.rs
  crates/ty_python_semantic/src/module_resolver/testing.rs
  crates/ty_python_semantic/src/module_resolver/typeshed.rs
  crates/ty_python_semantic/src/program.rs
  crates/ty_python_semantic/src/site_packages.rs
  crates/ty_python_semantic/tests/corpus.rs
  crates/ty_test/src/assertion.rs
  crates/ty_test/src/lib.rs
  crates/ty_test/src/matcher.rs
  crates/ty_wasm/src/lib.rs
  fuzz/fuzz_targets/ty_check_invalid_syntax.rs
Labels: internal, ty

#18942 [ty] Add subdiagnostic about empty bodies in more cases
  crates/ty_python_semantic/resources/mdtest/snapshots/return_type.md_-_Function_return_type_-_Invalid_return_type_(a91e0c67519cd77f).snap
  crates/ty_python_semantic/src/types/diagnostic.rs
Labels: ty, diagnostics

#18947 [`playground`] Add ruff logo docs link to Header.tsx
  playground/shared/src/Header.tsx
Labels: playground

#18839 [`pyflakes`] Mark `F504`/`F522`/`F523` autofix as unsafe if there's a call with side effect
  crates/ruff_linter/resources/test/fixtures/pyflakes/F504.py
  crates/ruff_linter/resources/test/fixtures/pyflakes/F522.py
  crates/ruff_linter/resources/test/fixtures/pyflakes/F523.py
  crates/ruff_linter/src/rules/pyflakes/rules/strings.rs
  crates/ruff_linter/src/rules/pyflakes/snapshots/ruff_linter__rules__pyflakes__tests__F504_F504.py.snap
  crates/ruff_linter/src/rules/pyflakes/snapshots/ruff_linter__rules__pyflakes__tests__F522_F522.py.snap
  crates/ruff_linter/src/rules/pyflakes/snapshots/ruff_linter__rules__pyflakes__tests__F523_F523.py.snap
Labels: fixes

#18750 [ty] Infer nonlocal types as unions of all reachable bindings
  crates/ty_python_semantic/resources/mdtest/declaration/error.md
  crates/ty_python_semantic/resources/mdtest/public_types.md
  crates/ty_python_semantic/resources/mdtest/scopes/builtin.md
  crates/ty_python_semantic/resources/mdtest/scopes/eager.md
  crates/ty_python_semantic/resources/mdtest/statically_known_branches.md
  crates/ty_python_semantic/resources/mdtest/terminal_statements.md
  crates/ty_python_semantic/resources/mdtest/unreachable.md
  crates/ty_python_semantic/src/place.rs
  crates/ty_python_semantic/src/semantic_index.rs
  crates/ty_python_semantic/src/semantic_index/use_def.rs
  crates/ty_python_semantic/src/semantic_index/use_def/place_state.rs
  crates/ty_python_semantic/src/types.rs
  crates/ty_python_semantic/src/types/class.rs
  crates/ty_python_semantic/src/types/ide_support.rs
  crates/ty_python_semantic/src/types/infer.rs
  crates/ty_python_semantic/src/types/protocol_class.rs
  crates/ty_python_semantic/src/types/signatures.rs
Labels: ty, ecosystem-analyzer

#18954 [ty] Prevent union builder construction for just one declaration
  crates/ty_python_semantic/src/place.rs
Labels: internal, performance, ty

#18938 [ty] Move venv and conda env discovery to `SearchPath::from_settings`
  crates/ruff/tests/analyze_graph.rs
  crates/ruff_benchmark/benches/ty.rs
  crates/ruff_benchmark/benches/ty_walltime.rs
  crates/ruff_benchmark/src/real_world_projects.rs
  crates/ruff_db/Cargo.toml
  crates/ruff_graph/src/db.rs
  crates/ty/tests/cli/main.rs
  crates/ty_project/src/combine.rs
  crates/ty_project/src/metadata/options.rs
  crates/ty_python_semantic/src/lib.rs
  crates/ty_python_semantic/src/module_resolver/resolver.rs
  crates/ty_python_semantic/src/module_resolver/testing.rs
  crates/ty_python_semantic/src/program.rs
  crates/ty_test/src/lib.rs
Labels: internal, ty

#18690 [`ruff`] Fix false positives and negatives in `RUF010`
  crates/ruff_linter/resources/test/fixtures/ruff/RUF010.py
  crates/ruff_linter/src/cst/matchers.rs
  crates/ruff_linter/src/rules/ruff/rules/explicit_f_string_type_conversion.rs
  crates/ruff_linter/src/rules/ruff/snapshots/ruff_linter__rules__ruff__tests__RUF010_RUF010.py.snap
Labels: bug, rule

#18678 [`pylint`] Fix `PLW0108` autofix introducing a syntax error when the lambda's body contains an assignment expression
  crates/ruff_linter/resources/test/fixtures/pylint/unnecessary_lambda.py
  crates/ruff_linter/src/rules/pylint/rules/unnecessary_lambda.rs
  crates/ruff_linter/src/rules/pylint/snapshots/ruff_linter__rules__pylint__tests__PLW0108_unnecessary_lambda.py.snap
Labels: bug, fixes

#18970 [`pylint`] Fix `PLC0415` example
  crates/ruff_linter/src/rules/pylint/rules/import_outside_top_level.rs
Labels: documentation

#18975 [`flake8-async`] Make `ASYNC110` example error out-of-the-box
  crates/ruff_linter/src/rules/flake8_async/rules/async_busy_wait.rs
Labels: documentation

#18974 [`flake8-annotations`] Make `ANN401` example error out-of-the-box
  crates/ruff_linter/src/rules/flake8_annotations/rules/definition.rs
Labels: documentation

#18979 [ty] Add micro-benchmark for #711
  crates/ruff_benchmark/benches/ty.rs
Labels: internal, performance, ty

#18981 [ty] Simplify `KnownClass::check_call()` and `KnownFunction::check_call()`
  crates/ty_python_semantic/src/types/class.rs
  crates/ty_python_semantic/src/types/function.rs
  crates/ty_python_semantic/src/types/infer.rs
Labels: internal, ty

#18982 [ty] Add builtins to completions derived from scope
  crates/ty_ide/src/completion.rs
  crates/ty_python_semantic/src/lib.rs
  crates/ty_python_semantic/src/semantic_model.rs
  crates/ty_server/src/server/api/requests/completion.rs
  crates/ty_wasm/src/lib.rs
Labels: server, ty

#18986 [ty] Fix playground
  playground/ty/src/Editor/Editor.tsx
Labels: playground, ty

#18946 Convert `OldDiagnostic::noqa_code` to an `Option<String>`
  Cargo.lock
  crates/ruff/src/printer.rs
  crates/ruff_linter/Cargo.toml
  crates/ruff_linter/src/checkers/noqa.rs
  crates/ruff_linter/src/codes.rs
  crates/ruff_linter/src/fix/mod.rs
  crates/ruff_linter/src/linter.rs
  crates/ruff_linter/src/message/azure.rs
  crates/ruff_linter/src/message/github.rs
  crates/ruff_linter/src/message/gitlab.rs
  crates/ruff_linter/src/message/json.rs
  crates/ruff_linter/src/message/junit.rs
  crates/ruff_linter/src/message/mod.rs
  crates/ruff_linter/src/message/pylint.rs
  crates/ruff_linter/src/message/rdjson.rs
  crates/ruff_linter/src/message/sarif.rs
  crates/ruff_linter/src/message/text.rs
  crates/ruff_linter/src/noqa.rs
  crates/ruff_linter/src/rules/pyflakes/mod.rs
  crates/ruff_linter/src/test.rs
  crates/ruff_server/src/lint.rs
  crates/ruff_wasm/src/lib.rs
Labels: internal, diagnostics

#18987 [ty] Make tuple instantiations sound
  crates/ty_python_semantic/resources/mdtest/expression/len.md
  crates/ty_python_semantic/resources/mdtest/type_compendium/tuple.md
  crates/ty_python_semantic/src/types.rs
  crates/ty_python_semantic/src/types/call/bind.rs
  crates/ty_python_semantic/src/types/class.rs
  crates/ty_python_semantic/src/types/infer.rs
Labels: ty

#18948 [ty] Support variable-length tuples in unpacking assignments
  crates/ty_python_semantic/resources/mdtest/snapshots/unpacking.md_-_Unpacking_-_Too_few_values_to_un…_(cef19e6b2b58e6a3).snap
  crates/ty_python_semantic/resources/mdtest/unpacking.md
  crates/ty_python_semantic/src/types.rs
  crates/ty_python_semantic/src/types/builder.rs
  crates/ty_python_semantic/src/types/call/arguments.rs
  crates/ty_python_semantic/src/types/generics.rs
  crates/ty_python_semantic/src/types/infer.rs
  crates/ty_python_semantic/src/types/instance.rs
  crates/ty_python_semantic/src/types/narrow.rs
  crates/ty_python_semantic/src/types/tuple.rs
  crates/ty_python_semantic/src/types/unpacker.rs
Labels: ty

#19001 [ty] Reduce 'complex_constrained_attributes_2' runtime
  crates/ruff_benchmark/benches/ty.rs
Labels: internal, performance, ty

#19011 Update Rust toolchain to 1.88 and MSRV to 1.86
  Cargo.lock
  Cargo.toml
  crates/ruff/Cargo.toml
  crates/ruff/tests/lint.rs
  crates/ruff/tests/show_settings.rs
  crates/ruff_annotate_snippets/src/renderer/display_list.rs
  crates/ruff_db/src/diagnostic/render.rs
  crates/ruff_db/src/lib.rs
  crates/ruff_db/src/system/walk_directory.rs
  crates/ruff_graph/src/db.rs
  crates/ruff_index/src/vec.rs
  crates/ruff_python_formatter/src/db.rs
  crates/ruff_python_formatter/src/lib.rs
  crates/ruff_server/src/server/schedule/thread/priority.rs
  crates/ty/src/lib.rs
  crates/ty/tests/file_watching.rs
  crates/ty_ide/src/completion.rs
  crates/ty_ide/src/db.rs
  crates/ty_ide/src/goto.rs
  crates/ty_ide/src/hover.rs
  crates/ty_ide/src/inlay_hints.rs
  crates/ty_ide/src/lib.rs
  crates/ty_project/src/db.rs
  crates/ty_project/src/lib.rs
  crates/ty_project/src/metadata/options.rs
  crates/ty_project/src/walk.rs
  crates/ty_project/src/watch/project_watcher.rs
  crates/ty_python_semantic/src/db.rs
  crates/ty_python_semantic/src/dunder_all.rs
  crates/ty_python_semantic/src/module_resolver/path.rs
  crates/ty_python_semantic/src/module_resolver/resolver.rs
  crates/ty_python_semantic/src/place.rs
  crates/ty_python_semantic/src/program.rs
  crates/ty_python_semantic/src/pull_types.rs
  crates/ty_python_semantic/src/semantic_index.rs
  crates/ty_python_semantic/src/semantic_index/builder.rs
  crates/ty_python_semantic/src/semantic_index/re_exports.rs
  crates/ty_python_semantic/src/semantic_model.rs
  crates/ty_python_semantic/src/suppression.rs
  crates/ty_python_semantic/src/types.rs
  crates/ty_python_semantic/src/types/call/bind.rs
  crates/ty_python_semantic/src/types/class.rs
  crates/ty_python_semantic/src/types/context.rs
  crates/ty_python_semantic/src/types/definition.rs
  crates/ty_python_semantic/src/types/function.rs
  crates/ty_python_semantic/src/types/infer.rs
  crates/ty_python_semantic/src/types/narrow.rs
  crates/ty_python_semantic/src/types/string_annotation.rs
  crates/ty_python_semantic/src/types/tuple.rs
  crates/ty_python_semantic/tests/corpus.rs
  crates/ty_server/src/document/location.rs
  crates/ty_server/src/document/range.rs
  crates/ty_server/src/server/api/diagnostics.rs
  crates/ty_server/src/server/schedule/thread/priority.rs
  crates/ty_test/src/db.rs
  crates/ty_test/src/lib.rs
  crates/ty_wasm/src/lib.rs
  fuzz/fuzz_targets/ty_check_invalid_syntax.rs
  rust-toolchain.toml
Labels: internal

#18973 [ty] Print salsa memory usage totals in mypy primer CI runs
  .github/workflows/mypy_primer.yaml
  crates/ty/src/lib.rs
  crates/ty_project/src/db.rs
Labels: testing, ty

#18847 [ty] Improve protocol member type checking and relation handling
  crates/ty_python_semantic/resources/mdtest/annotations/callable.md
  crates/ty_python_semantic/resources/mdtest/generics/legacy/classes.md
  crates/ty_python_semantic/resources/mdtest/narrow/hasattr.md
  crates/ty_python_semantic/resources/mdtest/protocols.md
  crates/ty_python_semantic/resources/mdtest/type_properties/is_disjoint_from.md
  crates/ty_python_semantic/src/types.rs
  crates/ty_python_semantic/src/types/instance.rs
  crates/ty_python_semantic/src/types/narrow.rs
  crates/ty_python_semantic/src/types/protocol_class.rs
Labels: ty

#19022 Minor code simplification
  crates/ruff_linter/src/checkers/ast/mod.rs
Labels: internal

#18998 [ty] Eagerly simplify 'True' and 'False' constraints
  crates/ty_python_semantic/resources/mdtest/narrow/while.md
  crates/ty_python_semantic/src/semantic_index/builder.rs
  crates/ty_python_semantic/src/semantic_index/predicate.rs
  crates/ty_python_semantic/src/semantic_index/reachability_constraints.rs
  crates/ty_python_semantic/src/semantic_index/use_def.rs
  crates/ty_python_semantic/src/semantic_index/use_def/place_state.rs
Labels: ty

#19017 [`flake8-bandit`] Make `S201` example error out-of-the-box
  crates/ruff_linter/src/rules/flake8_bandit/rules/flask_debug_true.rs
Labels: documentation

#18988 [`Airflow`] Make `AIR302` example error out-of-the-box
  crates/ruff_linter/src/rules/airflow/rules/moved_to_provider_in_3.rs
Labels: documentation

#19046 Bump CodSpeed to v3
  Cargo.lock
  Cargo.toml
Labels: internal

#18682 [`pyupgrade`] Avoid PEP-604 unions with `typing.NamedTuple` (`UP007`, `UP045`)
  crates/ruff_linter/resources/test/fixtures/pyupgrade/UP007.py
  crates/ruff_linter/resources/test/fixtures/pyupgrade/UP045.py
  crates/ruff_linter/src/rules/pyupgrade/rules/use_pep604_annotation.rs
  crates/ruff_linter/src/rules/pyupgrade/snapshots/ruff_linter__rules__pyupgrade__tests__UP007.py.snap
Labels: rule
