Repository astral-sh/ruff, pull requests merged in 2025-05, with the labels that each got.

#17709 [`flake8-use-pathlib`] Fix `PTH116` false positive when `stat` is passed a file descriptor
  crates/ruff_linter/resources/test/fixtures/flake8_use_pathlib/full_name.py
  crates/ruff_linter/src/rules/flake8_use_pathlib/rules/replaceable_by_pathlib.rs
Labels: bug, rule

#17756 [red-knot] Cache source type during semanic index building
  crates/red_knot_python_semantic/src/semantic_index/builder.rs
Labels: red-knot

#17757 [red-knot] Increase durability of read-only `File` fields
  crates/ruff_db/src/files.rs
Labels: red-knot

#17717 [`red-knot`] Allow subclasses of Any to be assignable to Callable types
  crates/red_knot_python_semantic/resources/mdtest/annotations/any.md
  crates/red_knot_python_semantic/src/types.rs
  crates/red_knot_python_semantic/src/types/class.rs
Labels: red-knot

#17764 Improve messages outputted by py-fuzzer
  python/py-fuzzer/fuzz.py
Labels: internal, testing

#17712 [`flake8-use-pathlib`] Fix `PTH104`false positive when `rename` is passed a file descriptor
  crates/ruff_linter/resources/test/fixtures/flake8_use_pathlib/full_name.py
  crates/ruff_linter/src/rules/flake8_use_pathlib/rules/replaceable_by_pathlib.rs
  crates/ruff_linter/src/rules/flake8_use_pathlib/snapshots/ruff_linter__rules__flake8_use_pathlib__tests__full_name.py.snap
Labels: bug, rule

#17766 Bump 0.11.8
  CHANGELOG.md
  Cargo.lock
  README.md
  crates/ruff/Cargo.toml
  crates/ruff_linter/Cargo.toml
  crates/ruff_wasm/Cargo.toml
  docs/integrations.md
  docs/tutorial.md
  pyproject.toml
  scripts/benchmarks/pyproject.toml
Labels: release

#17743 Allow passing a virtual environment to `ruff analyze graph`
  crates/ruff/src/args.rs
  crates/ruff/src/commands/analyze_graph.rs
  crates/ruff/tests/analyze_graph.rs
  crates/ruff_graph/src/db.rs
Labels: analyze

#17762 [red-knot] More informative hover-types for assignments
  crates/red_knot_ide/src/hover.rs
  crates/red_knot_python_semantic/src/types/infer.rs
Labels: red-knot

#17774 Fix module name in ASYNC110, 115, and 116 fixes
  crates/ruff_linter/src/rules/flake8_async/helpers.rs
  crates/ruff_linter/src/rules/flake8_async/snapshots/ruff_linter__rules__flake8_async__tests__ASYNC110_ASYNC110.py.snap
  crates/ruff_linter/src/rules/flake8_async/snapshots/ruff_linter__rules__flake8_async__tests__ASYNC115_ASYNC115.py.snap
  crates/ruff_linter/src/rules/flake8_async/snapshots/ruff_linter__rules__flake8_async__tests__ASYNC116_ASYNC116.py.snap
Labels: bug, fixes

#17786 doc: Add link to `check-typed-exception` from `S110` and `S112`
  crates/ruff_linter/src/rules/flake8_bandit/rules/try_except_continue.rs
  crates/ruff_linter/src/rules/flake8_bandit/rules/try_except_pass.rs
Labels: documentation

#17769 [red-knot] Implicit instance attributes in generic methods
  crates/red_knot_project/resources/test/corpus/88_regression_generic_method_with_nested_function.py
  crates/red_knot_python_semantic/resources/mdtest/attributes.md
  crates/red_knot_python_semantic/src/semantic_index.rs
  crates/red_knot_python_semantic/src/semantic_index/builder.rs
Labels: red-knot

#17787 [red-knot] Fix panic for `tuple[x[y]]` string annotation
  crates/red_knot_project/resources/test/corpus/95_annotation_string_tuple.py
  crates/red_knot_python_semantic/resources/primer/bad.txt
  crates/red_knot_python_semantic/resources/primer/good.txt
  crates/red_knot_python_semantic/src/types/infer.rs
Labels: red-knot

#17788 [red-knot] Refactor: no mutability in call APIs
  crates/red_knot_python_semantic/src/types.rs
  crates/red_knot_python_semantic/src/types/call/arguments.rs
  crates/red_knot_python_semantic/src/types/call/bind.rs
  crates/red_knot_python_semantic/src/types/class.rs
  crates/red_knot_python_semantic/src/types/infer.rs
Labels: red-knot

#17721 [red-knot] Legacy generic classes
  crates/red_knot_python_semantic/resources/mdtest/annotations/stdlib_typing_aliases.md
  crates/red_knot_python_semantic/resources/mdtest/annotations/unsupported_special_forms.md
  crates/red_knot_python_semantic/resources/mdtest/attributes.md
  crates/red_knot_python_semantic/resources/mdtest/call/methods.md
  crates/red_knot_python_semantic/resources/mdtest/decorators.md
  crates/red_knot_python_semantic/resources/mdtest/directives/cast.md
  crates/red_knot_python_semantic/resources/mdtest/exception/except_star.md
  crates/red_knot_python_semantic/resources/mdtest/expression/lambda.md
  crates/red_knot_python_semantic/resources/mdtest/function/parameters.md
  crates/red_knot_python_semantic/resources/mdtest/generics/builtins.md
  crates/red_knot_python_semantic/resources/mdtest/generics/legacy/classes.md
  crates/red_knot_python_semantic/resources/mdtest/generics/legacy/functions.md
  crates/red_knot_python_semantic/resources/mdtest/generics/legacy/variables.md
  crates/red_knot_python_semantic/resources/mdtest/generics/pep695/classes.md
  crates/red_knot_python_semantic/resources/mdtest/generics/pep695/functions.md
  crates/red_knot_python_semantic/resources/mdtest/generics/pep695/variables.md
  crates/red_knot_python_semantic/resources/mdtest/generics/pep695/variance.md
  crates/red_knot_python_semantic/resources/mdtest/literal/collections/dictionary.md
  crates/red_knot_python_semantic/resources/mdtest/protocols.md
  crates/red_knot_python_semantic/resources/mdtest/scopes/moduletype_attrs.md
  crates/red_knot_python_semantic/resources/mdtest/snapshots/functions.md_-_Generic_functions___Legacy_syntax_-_Inferring_a_bound_typevar.snap
  crates/red_knot_python_semantic/resources/mdtest/snapshots/functions.md_-_Generic_functions___Legacy_syntax_-_Inferring_a_constrained_typevar.snap
  crates/red_knot_python_semantic/resources/mdtest/snapshots/functions.md_-_Generic_functions___PEP_695_syntax_-_Inferring_a_bound_typevar.snap
  crates/red_knot_python_semantic/resources/mdtest/snapshots/functions.md_-_Generic_functions___PEP_695_syntax_-_Inferring_a_constrained_typevar.snap
  crates/red_knot_python_semantic/resources/mdtest/subscript/tuple.md
  crates/red_knot_python_semantic/resources/mdtest/type_properties/is_assignable_to.md
  crates/red_knot_python_semantic/resources/primer/bad.txt
  crates/red_knot_python_semantic/resources/primer/good.txt
  crates/red_knot_python_semantic/src/types.rs
  crates/red_knot_python_semantic/src/types/call/bind.rs
  crates/red_knot_python_semantic/src/types/class.rs
  crates/red_knot_python_semantic/src/types/class_base.rs
  crates/red_knot_python_semantic/src/types/diagnostic.rs
  crates/red_knot_python_semantic/src/types/display.rs
  crates/red_knot_python_semantic/src/types/generics.rs
  crates/red_knot_python_semantic/src/types/infer.rs
  crates/red_knot_python_semantic/src/types/known_instance.rs
  crates/red_knot_python_semantic/src/types/type_ordering.rs
  crates/red_knot_vendored/knot_extensions/knot_extensions.pyi
  knot.schema.json
Labels: red-knot

#17803 [red-knot] add tracing of salsa events in mdtests
  Cargo.lock
  crates/red_knot_test/Cargo.toml
  crates/red_knot_test/src/db.rs
Labels: red-knot

#17795 [red-knot] Distinguish fully static protocols from non-fully-static protocols
  crates/red_knot_python_semantic/resources/mdtest/generics/pep695/functions.md
  crates/red_knot_python_semantic/resources/mdtest/protocols.md
  crates/red_knot_python_semantic/src/types.rs
  crates/red_knot_python_semantic/src/types/call/bind.rs
  crates/red_knot_python_semantic/src/types/class.rs
  crates/red_knot_python_semantic/src/types/diagnostic.rs
  crates/red_knot_python_semantic/src/types/display.rs
  crates/red_knot_python_semantic/src/types/instance.rs
  crates/red_knot_python_semantic/src/types/protocol_class.rs
Labels: red-knot

#17810 [red-knot] Add tests asserting that subclasses of `Any` are assignable to arbitrary protocol types
  crates/red_knot_python_semantic/resources/mdtest/annotations/any.md
Labels: testing, red-knot

#17661 [`refurb`] Fix false positive for float and complex numbers in `FURB116`
  crates/ruff_linter/resources/test/fixtures/refurb/FURB116.py
  crates/ruff_linter/src/rules/refurb/rules/fstring_number_format.rs
Labels: bug, fixes

#17813 [red-knot] Minor simplifications to `types/display.rs`
  crates/red_knot_python_semantic/src/types/display.rs
Labels: red-knot

#17783 Add regression test for parent `noqa`
  crates/ruff/tests/lint.rs
Labels: internal

#17809 [red-knot] Synthesize a `__call__` attribute for Callable types
  crates/red_knot_python_semantic/resources/mdtest/annotations/callable.md
  crates/red_knot_python_semantic/resources/mdtest/protocols.md
  crates/red_knot_python_semantic/src/types.rs
Labels: red-knot

#17808 [red-knot] Recurse into the types of protocol members when normalizing a protocol's interface
  crates/red_knot_python_semantic/resources/mdtest/protocols.md
  crates/red_knot_python_semantic/src/types/instance.rs
  crates/red_knot_python_semantic/src/types/protocol_class.rs
Labels: red-knot

#17823 Fix missing `combine` call for `lint.typing-extensions` setting
  crates/ruff/tests/lint.rs
  crates/ruff_workspace/src/configuration.rs
Labels: bug, configuration

#17831 Ignore PRs labeled with `ty` for Ruff changelog
  pyproject.toml
Labels: release

#17830 Introduce `TY_MAX_PARALLELISM` environment variable
  crates/ruff_db/src/lib.rs
  crates/ruff_db/src/system/os.rs
  crates/ty/docs/tracing.md
  crates/ty/src/main.rs
Labels: ty

#17848 [ty] Minor typo in environment variable name
  crates/ty/docs/tracing.md
Labels: internal, ty

#17849 [ty] Fix standalone expression type retrieval in presence of cycles
  crates/ty_project/resources/test/corpus/88_regression_issue_17792.py
  crates/ty_python_semantic/src/types/infer.rs
Labels: ty

#17862 [ty] ecosystem: Activate running on 'materialize'
  crates/ty_python_semantic/resources/primer/bad.txt
  crates/ty_python_semantic/resources/primer/good.txt
Labels: ty

#17801 [`flake8-bandit`] Mark tuples of string literals as trusted input in `S603`
  crates/ruff_linter/resources/test/fixtures/flake8_bandit/S603.py
  crates/ruff_linter/src/rules/flake8_bandit/rules/shell_injection.rs
  crates/ruff_linter/src/rules/flake8_bandit/snapshots/ruff_linter__rules__flake8_bandit__tests__S603_S603.py.snap
Labels: rule, preview

#17754 [semantic-syntax-tests] for for `InvalidStarExpression`, `DuplicateMatchKey`, and `DuplicateMatchClassAttribute`
  crates/ruff_linter/src/linter.rs
  crates/ruff_linter/src/snapshots/ruff_linter__linter__tests__semantic_syntax_error_DuplicateMatchClassAttribute_duplicate_match_class_attribute_3.10.snap
  crates/ruff_linter/src/snapshots/ruff_linter__linter__tests__semantic_syntax_error_DuplicateMatchKey_duplicate_match_key_3.10.snap
  crates/ruff_linter/src/snapshots/ruff_linter__linter__tests__semantic_syntax_error_InvalidStarExpression_invalid_star_expression_3.10.snap
  crates/ruff_linter/src/snapshots/ruff_linter__linter__tests__semantic_syntax_error_InvalidStarExpression_invalid_star_expression_for_3.10.snap
  crates/ruff_linter/src/snapshots/ruff_linter__linter__tests__semantic_syntax_error_InvalidStarExpression_invalid_star_expression_yield_3.10.snap
  crates/ty_python_semantic/resources/mdtest/diagnostics/semantic_syntax_errors.md
Labels: testing

#17785 [semantic-syntax-tests] Add test fixtures for AwaitOutsideAsync
  crates/ruff_linter/resources/test/fixtures/syntax_errors/async_comprehension.py
  crates/ruff_linter/resources/test/fixtures/syntax_errors/await_outside_async_function.py
  crates/ruff_linter/src/linter.rs
  crates/ruff_linter/src/snapshots/ruff_linter__linter__tests__async_comprehension.py.snap
  crates/ruff_linter/src/snapshots/ruff_linter__linter__tests__await_outside_async_function.py.snap
Labels: testing

#17833 [ty] add cycle handling for FunctionType::signature query
  crates/ty_python_semantic/resources/mdtest/cycle.md
  crates/ty_python_semantic/src/types.rs
  crates/ty_python_semantic/src/types/signatures.rs
Labels: ty

#17834 [ty] add passing projects to primer
  crates/ty_python_semantic/resources/primer/bad.txt
  crates/ty_python_semantic/resources/primer/good.txt
Labels: ty

#17869 [ty] Increase worker-thread stack size
  crates/ty/src/main.rs
  crates/ty/tests/cli.rs
Labels: ty

#17865 [ty] Specialize bound methods and nominal instances
  crates/ty_python_semantic/resources/mdtest/decorators.md
  crates/ty_python_semantic/resources/mdtest/generics/legacy/classes.md
  crates/ty_python_semantic/resources/mdtest/generics/pep695/classes.md
  crates/ty_python_semantic/src/types.rs
  crates/ty_python_semantic/src/types/class.rs
  crates/ty_python_semantic/src/types/instance.rs
Labels: ty

#17871 [ty] Fix false-positive `[invalid-return-type]` diagnostics on generator functions
  crates/ty_python_semantic/resources/mdtest/function/return_type.md
  crates/ty_python_semantic/resources/mdtest/snapshots/return_type.md_-_Function_return_type_-_Generator_functions.snap
  crates/ty_python_semantic/src/semantic_index.rs
  crates/ty_python_semantic/src/semantic_index/builder.rs
  crates/ty_python_semantic/src/semantic_index/symbol.rs
  crates/ty_python_semantic/src/types/class.rs
  crates/ty_python_semantic/src/types/diagnostic.rs
  crates/ty_python_semantic/src/types/infer.rs
Labels: ty

#17872 [ty] Don't require default typevars when specializing
  crates/ty_python_semantic/resources/mdtest/generics/legacy/classes.md
  crates/ty_python_semantic/resources/mdtest/generics/pep695/classes.md
  crates/ty_python_semantic/src/types/call/bind.rs
  crates/ty_python_semantic/src/types/generics.rs
  crates/ty_python_semantic/src/types/infer.rs
Labels: ty

#17630 [red-knot] fix narrowing in nested scopes
  crates/ty_python_semantic/resources/mdtest/narrow/conditionals/nested.md
  crates/ty_python_semantic/src/semantic_index.rs
  crates/ty_python_semantic/src/semantic_index/builder.rs
  crates/ty_python_semantic/src/semantic_index/narrowing_constraints.rs
  crates/ty_python_semantic/src/semantic_index/use_def.rs
  crates/ty_python_semantic/src/semantic_index/use_def/symbol_state.rs
  crates/ty_python_semantic/src/symbol.rs
  crates/ty_python_semantic/src/types/infer.rs
  crates/ty_python_semantic/src/types/narrow.rs
Labels: ty

#17873 [ty] Do not emit errors if enums or NamedTuples constructed using functional syntax are used in type expressions
  crates/ty_python_semantic/resources/mdtest/annotations/unsupported_special_types.md
  crates/ty_python_semantic/src/types.rs
Labels: ty

#17875 Update code of conduct email address
  CODE_OF_CONDUCT.md
Labels: documentation

#17855 Show a warning at the end of the diagnostic list if there are any fatal warnings
  crates/ruff_db/src/diagnostic/mod.rs
  crates/ty/src/main.rs
Labels: ty

#17881 Fixup wording of fatal error warning
  crates/ty/src/main.rs
Labels: ty

#17857 Allowlist play.ty.dev
  playground/api/src/index.ts
Labels: playground

#17860 Update favicon and URL for playground
  playground/shared/src/Header.tsx
  playground/ty/index.html
  playground/ty/public/favicon-16x16.png
  playground/ty/public/favicon-32x32.png
  playground/ty/public/favicon.ico
  playground/ty/src/Playground.tsx
Labels: playground, ty

#17885 Generalize special-casing for enums constructed with the functional syntax
  crates/ty_python_semantic/resources/mdtest/annotations/unsupported_special_types.md
  crates/ty_python_semantic/src/types.rs
  crates/ty_python_semantic/src/types/infer.rs
Labels: ty

#17886 [ty] Fix duplicate diagnostics for unresolved module when an `import from` statement imports multiple members
  crates/ty/tests/cli.rs
  crates/ty_python_semantic/resources/mdtest/call/union.md
  crates/ty_python_semantic/resources/mdtest/import/basic.md
  crates/ty_python_semantic/resources/mdtest/import/errors.md
  crates/ty_python_semantic/resources/mdtest/import/star.md
  crates/ty_python_semantic/resources/mdtest/mdtest_custom_typeshed.md
  crates/ty_python_semantic/resources/mdtest/mro.md
  crates/ty_python_semantic/resources/mdtest/snapshots/basic.md_-_Structures_-_Multiple_objects_imported_from_an_unresolved_module.snap
  crates/ty_python_semantic/resources/mdtest/snapshots/basic.md_-_Structures_-_Unresolvable_module_import.snap
  crates/ty_python_semantic/resources/mdtest/snapshots/basic.md_-_Structures_-_Unresolvable_submodule_imports.snap
  crates/ty_python_semantic/resources/mdtest/snapshots/unresolved_import.md_-_Unresolved_import_diagnostics_-_An_unresolvable_import_that_does_not_use_`from`.snap
  crates/ty_python_semantic/resources/mdtest/snapshots/unresolved_import.md_-_Unresolved_import_diagnostics_-_Using_`from`_with_an_unknown_current_module.snap
  crates/ty_python_semantic/resources/mdtest/snapshots/unresolved_import.md_-_Unresolved_import_diagnostics_-_Using_`from`_with_an_unknown_nested_module.snap
  crates/ty_python_semantic/resources/mdtest/snapshots/unresolved_import.md_-_Unresolved_import_diagnostics_-_Using_`from`_with_an_unresolvable_module.snap
  crates/ty_python_semantic/resources/mdtest/snapshots/unresolved_import.md_-_Unresolved_import_diagnostics_-_Using_`from`_with_too_many_leading_dots.snap
  crates/ty_python_semantic/src/types/infer.rs
  crates/ty_wasm/tests/api.rs
Labels: ty

#17866 Update `ty version` to use parent Git repository information
  crates/ty/build.rs
  crates/ty/src/version.rs
Labels: ty

#17868 Parse `dist-workspace.toml` for version
  crates/ty/build.rs
  crates/ty/src/version.rs
Labels: ty

#17888 Display `ty version` for `ty --version` and `ty -V`
  crates/ty/Cargo.toml
  crates/ty/src/args.rs
  crates/ty/src/version.rs
Labels: ty

#17529 Default to latest supported Python version for version-related syntax errors
  crates/ruff/src/cache.rs
  crates/ruff/tests/lint.rs
  crates/ruff_linter/src/checkers/ast/mod.rs
  crates/ruff_linter/src/linter.rs
  crates/ruff_linter/src/rules/fastapi/mod.rs
  crates/ruff_linter/src/rules/flake8_annotations/mod.rs
  crates/ruff_linter/src/rules/flake8_async/mod.rs
  crates/ruff_linter/src/rules/flake8_bugbear/mod.rs
  crates/ruff_linter/src/rules/flake8_builtins/mod.rs
  crates/ruff_linter/src/rules/flake8_future_annotations/mod.rs
  crates/ruff_linter/src/rules/flake8_pyi/mod.rs
  crates/ruff_linter/src/rules/flake8_type_checking/mod.rs
  crates/ruff_linter/src/rules/perflint/mod.rs
  crates/ruff_linter/src/rules/pyflakes/mod.rs
  crates/ruff_linter/src/rules/pyupgrade/mod.rs
  crates/ruff_linter/src/rules/ruff/mod.rs
  crates/ruff_linter/src/settings/mod.rs
  crates/ruff_linter/src/test.rs
  crates/ruff_server/src/lint.rs
  crates/ruff_wasm/src/lib.rs
  crates/ruff_wasm/tests/api.rs
  crates/ruff_workspace/src/configuration.rs
Labels: preview

#17891 update the repository for ty
  crates/ty/Cargo.toml
Labels: internal, ty

#17874 [ty] Add minimal docs for a few lints
  crates/ty_python_semantic/src/types/diagnostic.rs
  ty.schema.json
Labels: documentation, ty

#17892 [ty] Propagate specializations to ancestor base classes
  crates/ty_python_semantic/resources/mdtest/annotations/stdlib_typing_aliases.md
  crates/ty_python_semantic/resources/mdtest/generics/legacy/classes.md
  crates/ty_python_semantic/resources/mdtest/generics/pep695/classes.md
  crates/ty_python_semantic/src/types.rs
  crates/ty_python_semantic/src/types/class.rs
  crates/ty_python_semantic/src/types/class_base.rs
  crates/ty_python_semantic/src/types/generics.rs
  crates/ty_python_semantic/src/types/mro.rs
Labels: ty

#17889 Update class literal display to use `<class 'Foo'>` style
  crates/ty_python_semantic/resources/mdtest/annotations/annotated.md
  crates/ty_python_semantic/resources/mdtest/annotations/any.md
  crates/ty_python_semantic/resources/mdtest/annotations/stdlib_typing_aliases.md
  crates/ty_python_semantic/resources/mdtest/annotations/unsupported_special_forms.md
  crates/ty_python_semantic/resources/mdtest/attributes.md
  crates/ty_python_semantic/resources/mdtest/binary/classes.md
  crates/ty_python_semantic/resources/mdtest/binary/custom.md
  crates/ty_python_semantic/resources/mdtest/binary/instances.md
  crates/ty_python_semantic/resources/mdtest/boundness_declaredness/public.md
  crates/ty_python_semantic/resources/mdtest/call/builtins.md
  crates/ty_python_semantic/resources/mdtest/call/methods.md
  crates/ty_python_semantic/resources/mdtest/class/super.md
  crates/ty_python_semantic/resources/mdtest/dataclasses.md
  crates/ty_python_semantic/resources/mdtest/descriptor_protocol.md
  crates/ty_python_semantic/resources/mdtest/exception/control_flow.md
  crates/ty_python_semantic/resources/mdtest/expression/attribute.md
  crates/ty_python_semantic/resources/mdtest/generics/legacy/classes.md
  crates/ty_python_semantic/resources/mdtest/generics/legacy/variables.md
  crates/ty_python_semantic/resources/mdtest/generics/pep695/classes.md
  crates/ty_python_semantic/resources/mdtest/generics/pep695/variables.md
  crates/ty_python_semantic/resources/mdtest/import/basic.md
  crates/ty_python_semantic/resources/mdtest/import/builtins.md
  crates/ty_python_semantic/resources/mdtest/import/conventions.md
  crates/ty_python_semantic/resources/mdtest/import/errors.md
  crates/ty_python_semantic/resources/mdtest/import/relative.md
  crates/ty_python_semantic/resources/mdtest/import/star.md
  crates/ty_python_semantic/resources/mdtest/import/tracking.md
  crates/ty_python_semantic/resources/mdtest/metaclass.md
  crates/ty_python_semantic/resources/mdtest/mro.md
  crates/ty_python_semantic/resources/mdtest/narrow/conditionals/eq.md
  crates/ty_python_semantic/resources/mdtest/narrow/issubclass.md
  crates/ty_python_semantic/resources/mdtest/narrow/truthiness.md
  crates/ty_python_semantic/resources/mdtest/narrow/type.md
  crates/ty_python_semantic/resources/mdtest/protocols.md
  crates/ty_python_semantic/resources/mdtest/scopes/moduletype_attrs.md
  crates/ty_python_semantic/resources/mdtest/scopes/unbound.md
  crates/ty_python_semantic/resources/mdtest/snapshots/attribute_assignment.md_-_Attribute_assignment_-_Possibly-unbound_attributes.snap
  crates/ty_python_semantic/resources/mdtest/snapshots/attribute_assignment.md_-_Attribute_assignment_-_Pure_instance_attributes.snap
  crates/ty_python_semantic/resources/mdtest/snapshots/attribute_assignment.md_-_Attribute_assignment_-_Setting_attributes_on_union_types.snap
  crates/ty_python_semantic/resources/mdtest/snapshots/attribute_assignment.md_-_Attribute_assignment_-_Unknown_attributes.snap
  crates/ty_python_semantic/resources/mdtest/stubs/class.md
  crates/ty_python_semantic/resources/mdtest/subscript/class.md
  crates/ty_python_semantic/resources/mdtest/subscript/tuple.md
  crates/ty_python_semantic/resources/mdtest/type_api.md
  crates/ty_python_semantic/resources/mdtest/type_of/basic.md
  crates/ty_python_semantic/resources/mdtest/type_of/typing_dot_Type.md
  crates/ty_python_semantic/resources/mdtest/unary/custom.md
  crates/ty_python_semantic/src/types/display.rs
Labels: ty

#17879 [ty] Support `generate-shell-completion`
  Cargo.lock
  crates/ty/Cargo.toml
  crates/ty/src/args.rs
  crates/ty/src/main.rs
Labels: ty

#17880 [ty] Protocols: Fixpoint iteration for fully-static check
  crates/ty_python_semantic/resources/mdtest/protocols.md
  crates/ty_python_semantic/src/types/call/bind.rs
  crates/ty_python_semantic/src/types/display.rs
  crates/ty_python_semantic/src/types/instance.rs
  crates/ty_python_semantic/src/types/protocol_class.rs
Labels: ty

#17648 [`pyupgrade`] Add spaces between tokens as necessary to avoid syntax errors in `UP018` autofix
  crates/ruff_linter/resources/test/fixtures/pyupgrade/UP018.py
  crates/ruff_linter/src/rules/pyupgrade/rules/native_literals.rs
  crates/ruff_linter/src/rules/pyupgrade/snapshots/ruff_linter__rules__pyupgrade__tests__UP018.py.snap
Labels: bug, fixes

#17895 Update salsa
  Cargo.lock
  Cargo.toml
  fuzz/Cargo.toml
Labels: ty

#17835 [ty] Detect overloads decorated with `@dataclass_transform`
  crates/ty_python_semantic/resources/mdtest/dataclass_transform.md
  crates/ty_python_semantic/src/types/call/bind.rs
  crates/ty_python_semantic/src/types/infer.rs
Labels: ty

#17920 Clean up some Ruff references in the ty server
  crates/ty_server/src/document.rs
  crates/ty_server/src/document/notebook.rs
  crates/ty_server/src/server.rs
  crates/ty_server/src/server/api.rs
  crates/ty_server/src/server/api/traits.rs
  crates/ty_server/src/server/schedule.rs
  crates/ty_server/src/server/schedule/thread/pool.rs
  crates/ty_server/src/session/settings.rs
Labels: internal, ty

#17910 [ty] fix assigning a typevar to a union with itself
  crates/ty_python_semantic/resources/mdtest/generics/pep695/variables.md
  crates/ty_python_semantic/src/types.rs
Labels: ty

#17924 Add link to `ty` issue tracker
  .github/ISSUE_TEMPLATE/config.yml
Labels: internal

#17921 Make completions an opt-in LSP feature
  crates/ty_ide/src/completion.rs
  crates/ty_server/src/server.rs
  crates/ty_server/src/session.rs
  crates/ty_server/src/session/settings.rs
Labels: server, ty

#17912 [ty] Add basic file watching to server
  crates/ty_server/src/server.rs
  crates/ty_server/src/server/api.rs
  crates/ty_server/src/server/api/notifications.rs
  crates/ty_server/src/server/api/notifications/did_change_watched_files.rs
  crates/ty_server/src/server/schedule.rs
  crates/ty_server/src/session.rs
  crates/ty_server/src/session/capabilities.rs
Labels: server, ty

#17926 [ty] Sort collected diagnostics before snapshotting them in mdtest
  crates/ruff_db/src/diagnostic/mod.rs
  crates/ty_project/src/lib.rs
  crates/ty_python_semantic/resources/mdtest/snapshots/for.md_-_For_loops_-_With_non-callable_iterator.snap
  crates/ty_python_semantic/resources/mdtest/snapshots/functions.md_-_Generic_functions___Legacy_syntax_-_Inferring_a_bound_typevar.snap
  crates/ty_python_semantic/resources/mdtest/snapshots/functions.md_-_Generic_functions___Legacy_syntax_-_Inferring_a_constrained_typevar.snap
  crates/ty_python_semantic/resources/mdtest/snapshots/functions.md_-_Generic_functions___PEP_695_syntax_-_Inferring_a_bound_typevar.snap
  crates/ty_python_semantic/resources/mdtest/snapshots/functions.md_-_Generic_functions___PEP_695_syntax_-_Inferring_a_constrained_typevar.snap
  crates/ty_python_semantic/resources/mdtest/snapshots/mro.md_-_Method_Resolution_Order_tests_-_`__bases__`_lists_with_duplicate_bases.snap
  crates/ty_python_semantic/resources/mdtest/snapshots/overloads.md_-_Overloads_-_Invalid_-_Inconsistent_decorators_-_`@classmethod`.snap
  crates/ty_python_semantic/resources/mdtest/snapshots/overloads.md_-_Overloads_-_Invalid_-_Inconsistent_decorators_-_`@final`.snap
  crates/ty_python_semantic/resources/mdtest/snapshots/protocols.md_-_Protocols_-_Calls_to_protocol_classes.snap
  crates/ty_test/src/lib.rs
Labels: ty

#17922 [ty] Ensure that `T` is disjoint from `~T` even when `T` is a TypeVar
  crates/ty_python_semantic/resources/mdtest/generics/pep695/variables.md
  crates/ty_python_semantic/src/types.rs
Labels: ty

#17893 [parser] Flag single unparenthesized generator expr with trailing comma in arguments.
  crates/ruff_python_parser/resources/inline/err/args_unparenthesized_generator.py
  crates/ruff_python_parser/resources/inline/ok/args_unparenthesized_generator.py
  crates/ruff_python_parser/src/parser/expression.rs
  crates/ruff_python_parser/src/parser/mod.rs
  crates/ruff_python_parser/tests/snapshots/invalid_syntax@args_unparenthesized_generator.py.snap
  crates/ruff_python_parser/tests/snapshots/valid_syntax@args_unparenthesized_generator.py.snap
Labels: bug, parser

#17928 Add instructions on how to upgrade to a newer Rust version
  CONTRIBUTING.md
Labels: documentation

#17825 [`pylint`] add fix safety section (`PLC2801`)
  crates/ruff_linter/src/rules/pylint/rules/unnecessary_dunder_call.rs
Labels: documentation

#17927 [ty] Check base classes when determining subtyping etc for generic aliases
  crates/ty_python_semantic/resources/mdtest/generics/legacy/variance.md
  crates/ty_python_semantic/resources/mdtest/generics/pep695/variance.md
  crates/ty_python_semantic/resources/mdtest/type_properties/is_subtype_of.md
  crates/ty_python_semantic/src/types.rs
  crates/ty_python_semantic/src/types/class.rs
Labels: ty

#17930 [ty] Recognise functions containing `yield from` expressions as being generator functions
  crates/ty_python_semantic/resources/mdtest/function/return_type.md
  crates/ty_python_semantic/resources/mdtest/snapshots/return_type.md_-_Function_return_type_-_Generator_functions.snap
  crates/ty_python_semantic/src/semantic_index/builder.rs
Labels: ty

#17689 Support `typing.Self` in methods
  crates/ty_python_semantic/resources/mdtest/annotations/self.md
  crates/ty_python_semantic/resources/mdtest/annotations/unsupported_special_forms.md
  crates/ty_python_semantic/resources/mdtest/call/constructor.md
  crates/ty_python_semantic/src/types.rs
  crates/ty_python_semantic/src/types/infer.rs
  crates/ty_python_semantic/src/types/known_instance.rs
Labels: ty

#17943 Update ty metadata
  crates/ty/Cargo.toml
Labels: ty

#17946 [`airflow`] Fix `SQLTableCheckOperator` typo (`AIR302`)
  crates/ruff_linter/resources/test/fixtures/airflow/AIR302_common_sql.py
  crates/ruff_linter/src/rules/airflow/rules/moved_to_provider_in_3.rs
  crates/ruff_linter/src/rules/airflow/snapshots/ruff_linter__rules__airflow__tests__AIR302_AIR302_common_sql.py.snap
Labels: rule, preview

#17637 [ty] Implement `global` handling and `load-before-global-declaration` syntax error
  crates/ty_python_semantic/resources/mdtest/diagnostics/semantic_syntax_errors.md
  crates/ty_python_semantic/resources/mdtest/scopes/global.md
  crates/ty_python_semantic/src/semantic_index.rs
  crates/ty_python_semantic/src/semantic_index/builder.rs
  crates/ty_python_semantic/src/types/infer.rs
Labels: ty

#17952 Update the schemastore script to match changes in ty
  scripts/update_schemastore.py
Labels: internal

#17953 [ty] Generate and add rules table
  .pre-commit-config.yaml
  Cargo.lock
  crates/ruff_dev/Cargo.toml
  crates/ruff_dev/src/generate_all.rs
  crates/ruff_dev/src/generate_ty_rules.rs
  crates/ruff_dev/src/main.rs
  crates/ty/docs/rules.md
  crates/ty_python_semantic/src/types/diagnostic.rs
  ty.schema.json
Labels: documentation, ty

#17938 [ty] Default to latest supported python version
  crates/ruff_db/src/lib.rs
  crates/ruff_python_ast/src/python_version.rs
  crates/ty/tests/cli.rs
  crates/ty_ide/src/inlay_hints.rs
  crates/ty_ide/src/lib.rs
  crates/ty_project/src/metadata/options.rs
  crates/ty_project/src/metadata/pyproject.rs
  crates/ty_python_semantic/src/types/class.rs
Labels: cli, ty

#17934 [ty] Ignore `possibly-unresolved-reference` by default
  .github/mypy-primer-ty.toml
  .github/workflows/mypy_primer.yaml
  crates/ty/docs/rules.md
  crates/ty/tests/cli.rs
  crates/ty_python_semantic/resources/mdtest/snapshots/for.md_-_For_loops_-_With_non-callable_iterator.snap
  crates/ty_python_semantic/src/lint.rs
  crates/ty_python_semantic/src/types/diagnostic.rs
  crates/ty_test/src/db.rs
  ty.schema.json
Labels: configuration, ty

#17936 [ty] Change default severity for `unbound-reference` to `error`
  crates/ty/docs/rules.md
  crates/ty/tests/cli.rs
  crates/ty_python_semantic/src/types/diagnostic.rs
  ty.schema.json
Labels: configuration, ty

#17948 [ty] Support extending `__all__` with a literal tuple or set as well as a literal list
  crates/ty_python_semantic/resources/mdtest/import/dunder_all.md
  crates/ty_python_semantic/src/dunder_all.rs
Labels: ty

#17784 Convert `Message::SyntaxError` to use `Diagnostic` internally
  Cargo.lock
  crates/ruff/src/cache.rs
  crates/ruff/src/diagnostics.rs
  crates/ruff_benchmark/benches/ty.rs
  crates/ruff_db/src/diagnostic/mod.rs
  crates/ruff_db/src/diagnostic/render.rs
  crates/ruff_db/src/lib.rs
  crates/ruff_linter/Cargo.toml
  crates/ruff_linter/src/message/azure.rs
  crates/ruff_linter/src/message/diff.rs
  crates/ruff_linter/src/message/github.rs
  crates/ruff_linter/src/message/gitlab.rs
  crates/ruff_linter/src/message/grouped.rs
  crates/ruff_linter/src/message/json.rs
  crates/ruff_linter/src/message/junit.rs
  crates/ruff_linter/src/message/mod.rs
  crates/ruff_linter/src/message/pylint.rs
  crates/ruff_linter/src/message/rdjson.rs
  crates/ruff_linter/src/message/sarif.rs
  crates/ruff_linter/src/message/text.rs
  crates/ruff_server/src/lint.rs
  crates/ruff_source_file/src/lib.rs
  crates/ruff_wasm/src/lib.rs
  crates/ty/src/main.rs
  crates/ty_ide/src/hover.rs
  crates/ty_ide/src/lib.rs
  crates/ty_project/src/db.rs
  crates/ty_python_semantic/src/types/context.rs
  crates/ty_server/src/server/api/requests/diagnostic.rs
  crates/ty_test/src/lib.rs
  crates/ty_wasm/src/lib.rs
Labels: diagnostics

#17962 [ty] Respect the gradual guarantee when reporting errors in resolving MROs
  crates/ty_python_semantic/resources/mdtest/mro.md
  crates/ty_python_semantic/src/types/mro.rs
Labels: ty

#17971 [ty] Report duplicate `Protocol` or `Generic` base classes with `[duplicate-base]`, not `[inconsistent-mro]`
  crates/ty_python_semantic/resources/mdtest/generics/legacy/classes.md
  crates/ty_python_semantic/resources/mdtest/protocols.md
  crates/ty_python_semantic/src/types/class_base.rs
  crates/ty_python_semantic/src/types/mro.rs
Labels: ty

#17947 [ty] Support extending `__all__` from an imported module even when the module is not an `ExprName` node
  crates/ty_python_semantic/resources/mdtest/import/dunder_all.md
  crates/ty_python_semantic/src/dunder_all.rs
  crates/ty_python_semantic/src/semantic_index.rs
  crates/ty_python_semantic/src/semantic_index/builder.rs
  crates/ty_python_semantic/src/types/infer.rs
Labels: ty

#17956 [ty] Handle typevars that have other typevars as a default
  crates/ty_python_semantic/resources/mdtest/attributes.md
  crates/ty_python_semantic/resources/mdtest/generics/legacy/variables.md
  crates/ty_python_semantic/resources/mdtest/generics/pep695/variables.md
  crates/ty_python_semantic/src/types.rs
  crates/ty_python_semantic/src/types/call/bind.rs
  crates/ty_python_semantic/src/types/class.rs
  crates/ty_python_semantic/src/types/class_base.rs
  crates/ty_python_semantic/src/types/generics.rs
  crates/ty_python_semantic/src/types/infer.rs
  crates/ty_python_semantic/src/types/instance.rs
  crates/ty_python_semantic/src/types/signatures.rs
Labels: ty

#17958 [ty] Remove `SliceLiteral` type variant
  crates/ty_python_semantic/resources/mdtest/type_properties/is_assignable_to.md
  crates/ty_python_semantic/resources/mdtest/type_properties/is_subtype_of.md
  crates/ty_python_semantic/src/types.rs
  crates/ty_python_semantic/src/types/class.rs
  crates/ty_python_semantic/src/types/class_base.rs
  crates/ty_python_semantic/src/types/display.rs
  crates/ty_python_semantic/src/types/infer.rs
  crates/ty_python_semantic/src/types/type_ordering.rs
Labels: ty

#17758 [ty] fix more ecosystem/fuzzer panics with fixpoint
  crates/ty_python_semantic/resources/mdtest/mro.md
  crates/ty_python_semantic/src/types/class.rs
  crates/ty_python_semantic/src/types/class_base.rs
  crates/ty_python_semantic/src/types/generics.rs
  crates/ty_python_semantic/src/types/infer.rs
  crates/ty_python_semantic/src/types/mro.rs
  python/py-fuzzer/fuzz.py
Labels: ty

#17903 [ty] primer updates
  crates/ty_python_semantic/resources/primer/bad.txt
  crates/ty_python_semantic/resources/primer/good.txt
Labels: ty

#17964 [ty] Update salsa
  Cargo.lock
  Cargo.toml
  crates/ruff_db/src/files.rs
  crates/ruff_db/src/files/file_root.rs
  crates/ruff_db/src/parsed.rs
  crates/ruff_graph/src/db.rs
  crates/ty_ide/src/db.rs
  crates/ty_project/src/db.rs
  crates/ty_project/src/lib.rs
  crates/ty_python_semantic/src/db.rs
  crates/ty_python_semantic/src/dunder_all.rs
  crates/ty_python_semantic/src/module_resolver/resolver.rs
  crates/ty_python_semantic/src/program.rs
  crates/ty_python_semantic/src/semantic_index.rs
  crates/ty_python_semantic/src/semantic_index/definition.rs
  crates/ty_python_semantic/src/semantic_index/expression.rs
  crates/ty_python_semantic/src/semantic_index/predicate.rs
  crates/ty_python_semantic/src/semantic_index/re_exports.rs
  crates/ty_python_semantic/src/suppression.rs
  crates/ty_python_semantic/src/symbol.rs
  crates/ty_python_semantic/src/types.rs
  crates/ty_python_semantic/src/types/call/bind.rs
  crates/ty_python_semantic/src/types/class.rs
  crates/ty_python_semantic/src/types/class_base.rs
  crates/ty_python_semantic/src/types/display.rs
  crates/ty_python_semantic/src/types/generics.rs
  crates/ty_python_semantic/src/types/infer.rs
  crates/ty_python_semantic/src/types/narrow.rs
  crates/ty_python_semantic/src/types/protocol_class.rs
  crates/ty_python_semantic/src/types/type_ordering.rs
  crates/ty_python_semantic/src/types/unpacker.rs
  crates/ty_python_semantic/src/unpack.rs
  crates/ty_test/src/db.rs
  fuzz/Cargo.toml
  fuzz/fuzz_targets/ty_check_invalid_syntax.rs
Labels: internal, ty

#17978 [ty] CLI reference
  .pre-commit-config.yaml
  Cargo.lock
  Cargo.toml
  crates/ruff_dev/Cargo.toml
  crates/ruff_dev/src/generate_all.rs
  crates/ruff_dev/src/generate_cli_help.rs
  crates/ruff_dev/src/generate_docs.rs
  crates/ruff_dev/src/generate_json_schema.rs
  crates/ruff_dev/src/generate_ty_cli_reference.rs
  crates/ruff_dev/src/generate_ty_options.rs
  crates/ruff_dev/src/generate_ty_rules.rs
  crates/ruff_dev/src/generate_ty_schema.rs
  crates/ruff_dev/src/main.rs
  crates/ruff_dev/src/print_ast.rs
  crates/ruff_dev/src/print_cst.rs
  crates/ruff_dev/src/print_tokens.rs
  crates/ruff_dev/src/round_trip.rs
  crates/ty/docs/cli.md
  crates/ty/src/args.rs
  crates/ty/src/lib.rs
  crates/ty/src/main.rs
Labels: documentation, ty

#17929 [ty] Recursive protocols
  crates/ty_python_semantic/resources/mdtest/protocols.md
  crates/ty_python_semantic/src/types.rs
  crates/ty_python_semantic/src/types/builder.rs
  crates/ty_python_semantic/src/types/instance.rs
  crates/ty_python_semantic/src/types/protocol_class.rs
  crates/ty_python_semantic/src/types/signatures.rs
Labels: ty

#17982 [ty] Display "All checks passed!" message in green
  crates/ty/src/lib.rs
Labels: ty

#17832 [ty] Understand classes that inherit from subscripted `Protocol[]` as generic
  crates/ruff_benchmark/benches/ty.rs
  crates/ty_python_semantic/resources/mdtest/annotations/self.md
  crates/ty_python_semantic/resources/mdtest/annotations/starred.md
  crates/ty_python_semantic/resources/mdtest/annotations/stdlib_typing_aliases.md
  crates/ty_python_semantic/resources/mdtest/annotations/unsupported_special_forms.md
  crates/ty_python_semantic/resources/mdtest/assignment/annotations.md
  crates/ty_python_semantic/resources/mdtest/attributes.md
  crates/ty_python_semantic/resources/mdtest/expression/lambda.md
  crates/ty_python_semantic/resources/mdtest/function/parameters.md
  crates/ty_python_semantic/resources/mdtest/generics/legacy/classes.md
  crates/ty_python_semantic/resources/mdtest/generics/legacy/variables.md
  crates/ty_python_semantic/resources/mdtest/generics/pep695/classes.md
  crates/ty_python_semantic/resources/mdtest/import/dunder_all.md
  crates/ty_python_semantic/resources/mdtest/literal/collections/list.md
  crates/ty_python_semantic/resources/mdtest/literal/collections/set.md
  crates/ty_python_semantic/resources/mdtest/named_tuple.md
  crates/ty_python_semantic/resources/mdtest/narrow/match.md
  crates/ty_python_semantic/resources/mdtest/protocols.md
  crates/ty_python_semantic/resources/mdtest/scopes/moduletype_attrs.md
  crates/ty_python_semantic/resources/mdtest/subscript/lists.md
  crates/ty_python_semantic/resources/mdtest/subscript/tuple.md
  crates/ty_python_semantic/resources/mdtest/type_properties/is_subtype_of.md
  crates/ty_python_semantic/resources/primer/bad.txt
  crates/ty_python_semantic/resources/primer/good.txt
  crates/ty_python_semantic/src/types.rs
  crates/ty_python_semantic/src/types/class.rs
  crates/ty_python_semantic/src/types/class_base.rs
  crates/ty_python_semantic/src/types/display.rs
  crates/ty_python_semantic/src/types/generics.rs
  crates/ty_python_semantic/src/types/infer.rs
  crates/ty_python_semantic/src/types/instance.rs
  crates/ty_python_semantic/src/types/known_instance.rs
  crates/ty_python_semantic/src/types/mro.rs
  crates/ty_python_semantic/src/types/protocol_class.rs
  crates/ty_python_semantic/src/types/type_ordering.rs
Labels: ty

#17913 [`airflow`] extend `AIR311` rules
  crates/ruff_linter/resources/test/fixtures/airflow/AIR311_names.py
  crates/ruff_linter/src/rules/airflow/rules/suggested_to_update_3_0.rs
  crates/ruff_linter/src/rules/airflow/snapshots/ruff_linter__rules__airflow__tests__AIR311_AIR311_names.py.snap
Labels: rule, preview

#17965 Add progress bar for `ty check`
  Cargo.lock
  crates/ruff_benchmark/benches/ty.rs
  crates/ty/Cargo.toml
  crates/ty/src/lib.rs
  crates/ty/tests/file_watching.rs
  crates/ty_project/src/db.rs
  crates/ty_project/src/files.rs
  crates/ty_project/src/lib.rs
  crates/ty_wasm/src/lib.rs
Labels: cli, ty

#17984 [ty] bottom-up improvement of diagnostic messages for union type function calls
  crates/ruff_benchmark/benches/ty.rs
  crates/ty_python_semantic/resources/mdtest/annotations/new_types.md
  crates/ty_python_semantic/resources/mdtest/call/annotation.md
  crates/ty_python_semantic/resources/mdtest/call/callable_instance.md
  crates/ty_python_semantic/resources/mdtest/call/constructor.md
  crates/ty_python_semantic/resources/mdtest/call/function.md
  crates/ty_python_semantic/resources/mdtest/call/getattr_static.md
  crates/ty_python_semantic/resources/mdtest/call/invalid_syntax.md
  crates/ty_python_semantic/resources/mdtest/call/methods.md
  crates/ty_python_semantic/resources/mdtest/call/subclass_of.md
  crates/ty_python_semantic/resources/mdtest/call/union.md
  crates/ty_python_semantic/resources/mdtest/decorators.md
  crates/ty_python_semantic/resources/mdtest/diagnostics/union_call.md
  crates/ty_python_semantic/resources/mdtest/doc/public_type_undeclared_symbols.md
  crates/ty_python_semantic/resources/mdtest/generics/legacy/classes.md
  crates/ty_python_semantic/resources/mdtest/generics/pep695/classes.md
  crates/ty_python_semantic/resources/mdtest/generics/scoping.md
  crates/ty_python_semantic/resources/mdtest/properties.md
  crates/ty_python_semantic/resources/mdtest/snapshots/functions.md_-_Generic_functions___Legacy_syntax_-_Inferring_a_bound_typevar.snap
  crates/ty_python_semantic/resources/mdtest/snapshots/functions.md_-_Generic_functions___Legacy_syntax_-_Inferring_a_constrained_typevar.snap
  crates/ty_python_semantic/resources/mdtest/snapshots/functions.md_-_Generic_functions___PEP_695_syntax_-_Inferring_a_bound_typevar.snap
  crates/ty_python_semantic/resources/mdtest/snapshots/functions.md_-_Generic_functions___PEP_695_syntax_-_Inferring_a_constrained_typevar.snap
  crates/ty_python_semantic/resources/mdtest/snapshots/invalid_argument_type.md_-_Invalid_argument_type_diagnostics_-_Basic.snap
  crates/ty_python_semantic/resources/mdtest/snapshots/invalid_argument_type.md_-_Invalid_argument_type_diagnostics_-_Calls_to_methods.snap
  crates/ty_python_semantic/resources/mdtest/snapshots/invalid_argument_type.md_-_Invalid_argument_type_diagnostics_-_Different_files.snap
  crates/ty_python_semantic/resources/mdtest/snapshots/invalid_argument_type.md_-_Invalid_argument_type_diagnostics_-_Different_source_order.snap
  crates/ty_python_semantic/resources/mdtest/snapshots/invalid_argument_type.md_-_Invalid_argument_type_diagnostics_-_Many_parameters.snap
  crates/ty_python_semantic/resources/mdtest/snapshots/invalid_argument_type.md_-_Invalid_argument_type_diagnostics_-_Many_parameters_across_multiple_lines.snap
  crates/ty_python_semantic/resources/mdtest/snapshots/invalid_argument_type.md_-_Invalid_argument_type_diagnostics_-_Many_parameters_with_multiple_invalid_arguments.snap
  crates/ty_python_semantic/resources/mdtest/snapshots/invalid_argument_type.md_-_Invalid_argument_type_diagnostics_-_Test_calling_a_function_whose_type_is_vendored_from_`typeshed`.snap
  crates/ty_python_semantic/resources/mdtest/snapshots/invalid_argument_type.md_-_Invalid_argument_type_diagnostics_-_Tests_for_a_variety_of_argument_types_-_Keyword_only_arguments.snap
  crates/ty_python_semantic/resources/mdtest/snapshots/invalid_argument_type.md_-_Invalid_argument_type_diagnostics_-_Tests_for_a_variety_of_argument_types_-_Mix_of_arguments.snap
  crates/ty_python_semantic/resources/mdtest/snapshots/invalid_argument_type.md_-_Invalid_argument_type_diagnostics_-_Tests_for_a_variety_of_argument_types_-_One_keyword_argument.snap
  crates/ty_python_semantic/resources/mdtest/snapshots/invalid_argument_type.md_-_Invalid_argument_type_diagnostics_-_Tests_for_a_variety_of_argument_types_-_Only_positional.snap
  crates/ty_python_semantic/resources/mdtest/snapshots/invalid_argument_type.md_-_Invalid_argument_type_diagnostics_-_Tests_for_a_variety_of_argument_types_-_Synthetic_arguments.snap
  crates/ty_python_semantic/resources/mdtest/snapshots/invalid_argument_type.md_-_Invalid_argument_type_diagnostics_-_Tests_for_a_variety_of_argument_types_-_Variadic_arguments.snap
  crates/ty_python_semantic/resources/mdtest/snapshots/invalid_argument_type.md_-_Invalid_argument_type_diagnostics_-_Tests_for_a_variety_of_argument_types_-_Variadic_keyword_arguments.snap
  crates/ty_python_semantic/resources/mdtest/snapshots/union_call.md_-_Calling_a_union_of_function_types_-_A_smaller_scale_example.snap
  crates/ty_python_semantic/resources/mdtest/snapshots/union_call.md_-_Calling_a_union_of_function_types_-_Multiple_variants_but_only_one_is_invalid.snap
  crates/ty_python_semantic/resources/mdtest/snapshots/union_call.md_-_Calling_a_union_of_function_types_-_Try_to_cover_all_possible_reasons_-_Cover_keyword_argument_related_reasons.snap
  crates/ty_python_semantic/resources/mdtest/snapshots/union_call.md_-_Calling_a_union_of_function_types_-_Try_to_cover_all_possible_reasons_-_Cover_non-keyword_related_reasons.snap
  crates/ty_python_semantic/src/types/call/bind.rs
Labels: ty, diagnostics

#17748 [semantic-syntax-tests] `IrrefutableCasePattern`, `SingleStarredAssignment`, `WriteToDebug`, `InvalidExpression`
  crates/ruff_linter/src/linter.rs
  crates/ruff_linter/src/snapshots/ruff_linter__linter__tests__semantic_syntax_error_InvalidExpression_invalid_expression_walrus_in_return_annotation_3.12.snap
  crates/ruff_linter/src/snapshots/ruff_linter__linter__tests__semantic_syntax_error_InvalidExpression_invalid_expression_yield_from_in_base_class_3.12.snap
  crates/ruff_linter/src/snapshots/ruff_linter__linter__tests__semantic_syntax_error_InvalidExpression_invalid_expression_yield_in_type_alias_3.12.snap
  crates/ruff_linter/src/snapshots/ruff_linter__linter__tests__semantic_syntax_error_InvalidExpression_invalid_expression_yield_in_type_param_3.12.snap
  crates/ruff_linter/src/snapshots/ruff_linter__linter__tests__semantic_syntax_error_IrrefutableCasePattern_irrefutable_case_pattern_capture_3.10.snap
  crates/ruff_linter/src/snapshots/ruff_linter__linter__tests__semantic_syntax_error_IrrefutableCasePattern_irrefutable_case_pattern_wildcard_3.10.snap
  crates/ruff_linter/src/snapshots/ruff_linter__linter__tests__semantic_syntax_error_SingleStarredAssignment_single_starred_assignment_3.10.snap
  crates/ruff_linter/src/snapshots/ruff_linter__linter__tests__semantic_syntax_error_WriteToDebug_write_to_debug_3.10.snap
  crates/ruff_linter/src/snapshots/ruff_linter__linter__tests__semantic_syntax_error_WriteToDebug_write_to_debug_class_type_param_3.12.snap
  crates/ruff_linter/src/snapshots/ruff_linter__linter__tests__semantic_syntax_error_WriteToDebug_write_to_debug_in_function_param_3.10.snap
  crates/ty_python_semantic/resources/mdtest/diagnostics/semantic_syntax_errors.md
Labels: testing

#17988 Fix typos
  crates/ruff_formatter/src/lib.rs
  crates/ruff_linter/resources/test/fixtures/perflint/PERF401.py
  crates/ruff_linter/src/rules/perflint/snapshots/ruff_linter__rules__perflint__tests__PERF401_PERF401.py.snap
  crates/ruff_linter/src/rules/perflint/snapshots/ruff_linter__rules__perflint__tests__preview__PERF401_PERF401.py.snap
  crates/ruff_python_ast/src/nodes.rs
  crates/ruff_python_ast/src/visitor.rs
  crates/ruff_python_ast/src/visitor/transformer.rs
  crates/ruff_python_parser/resources/invalid/expressions/parenthesized/tuple_starred_expr.py
  crates/ruff_python_parser/tests/snapshots/invalid_syntax@expressions__parenthesized__tuple_starred_expr.py.snap
  crates/ty_python_semantic/resources/mdtest/import/star.md
  crates/ty_python_semantic/resources/mdtest/statically_known_branches.md
  crates/ty_python_semantic/src/semantic_index/builder.rs
  crates/ty_python_semantic/src/types/call/arguments.rs
  crates/ty_python_semantic/src/types/context.rs
  crates/ty_python_semantic/src/types/infer.rs
Labels: internal

#17995 add test for typing_extensions.Self
  crates/ty_python_semantic/resources/mdtest/annotations/self.md
  crates/ty_python_semantic/src/types/known_instance.rs
Labels: internal

#17993 Exclude broken symlinks from `meson-python` ecosystem check
  python/ruff-ecosystem/ruff_ecosystem/defaults.py
Labels: testing

#17975 [ty] Add more tests for `NamedTuple`s
  crates/ty_python_semantic/resources/mdtest/named_tuple.md
Labels: testing, ty

#18001 [ty] Silence false positives for PEP-695 ParamSpec annotations
  crates/ty_python_semantic/resources/mdtest/annotations/callable.md
  crates/ty_python_semantic/src/types.rs
  crates/ty_python_semantic/src/types/class_base.rs
  crates/ty_python_semantic/src/types/infer.rs
  crates/ty_python_semantic/src/types/type_ordering.rs
Labels: ty

#17999 Skip S608 for expressionless f-strings
  crates/ruff_linter/resources/test/fixtures/flake8_bandit/S608.py
  crates/ruff_linter/src/rules/flake8_bandit/rules/hardcoded_sql_expression.rs
  crates/ruff_linter/src/rules/flake8_bandit/snapshots/ruff_linter__rules__flake8_bandit__tests__S608_S608.py.snap
Labels: rule

#17979 Link to the rules.md in the ty repository
  crates/ty/docs/configuration.md
  crates/ty_project/src/metadata/options.rs
  ty.schema.json
Labels: documentation, ty

#17991 [ty] Add basic support for non-virtual Python environments
  crates/ty_python_semantic/src/module_resolver/resolver.rs
  crates/ty_python_semantic/src/site_packages.rs
Labels: ty

#17996 [ty] Add test coverage for `PythonEnvironment::System` variants
  crates/ty_python_semantic/src/site_packages.rs
Labels: internal, testing, ty

#18003 [ty] Do not allow invalid virtual environments from discovered `.venv` or `VIRTUAL_ENV`
  crates/ty_python_semantic/src/site_packages.rs
Labels: ty

#18004 [ty] Remove generic types from the daily property test run (for now)
  crates/ty_python_semantic/src/types/property_tests/type_generation.rs
Labels: internal, testing, ty

#18015 [ty] Remove unused variants from various `Known*` enums
  crates/ty_python_semantic/src/module_resolver/module.rs
  crates/ty_python_semantic/src/types.rs
  crates/ty_python_semantic/src/types/class.rs
  crates/ty_python_semantic/src/types/class_base.rs
  crates/ty_python_semantic/src/types/infer.rs
  crates/ty_python_semantic/src/types/known_instance.rs
  crates/ty_python_semantic/src/types/type_ordering.rs
Labels: internal, ty

#18037 [ty] Remove brackets around option names
  crates/ruff_dev/src/generate_ty_options.rs
  crates/ty/docs/configuration.md
Labels: documentation, ty

#18040 [ty] Fix incorrect type of `src.root` in documentation
  crates/ty/docs/configuration.md
  crates/ty_project/src/metadata/options.rs
  ty.schema.json
Labels: documentation, ty

#18033 disable jemalloc on android
  crates/ruff/Cargo.toml
  crates/ruff/src/main.rs
Labels: cli

#18020 [ty] Apply function specialization to all overloads
  crates/ty_python_semantic/resources/mdtest/generics/legacy/classes.md
  crates/ty_python_semantic/resources/mdtest/generics/pep695/classes.md
  crates/ty_python_semantic/src/types.rs
  crates/ty_python_semantic/src/types/display.rs
  crates/ty_python_semantic/src/types/signatures.rs
Labels: ty

#17968 [`flake8-use-pathlib`] `PTH*` suppress diagnostic for all `os.*` functions that have the `dir_fd` parameter
  crates/ruff_linter/resources/test/fixtures/flake8_use_pathlib/PTH207.py
  crates/ruff_linter/resources/test/fixtures/flake8_use_pathlib/full_name.py
  crates/ruff_linter/src/rules/flake8_use_pathlib/rules/replaceable_by_pathlib.rs
  crates/ruff_linter/src/rules/flake8_use_pathlib/snapshots/ruff_linter__rules__flake8_use_pathlib__tests__PTH207_PTH207.py.snap
Labels: bug, rule

#17976 Implement a recursive check for RUF060
  crates/ruff_linter/resources/test/fixtures/ruff/RUF060.py
  crates/ruff_linter/src/rules/ruff/rules/in_empty_collection.rs
  crates/ruff_linter/src/rules/ruff/snapshots/ruff_linter__rules__ruff__tests__RUF060_RUF060.py.snap
Labels: rule, preview

#17878 [`pylint`] add fix safety section (`PLW3301`)
  crates/ruff_linter/src/rules/pylint/rules/nested_min_max.rs
Labels: documentation

#17887 [`airflow`] apply try catch guard to all AIR3 rules (`AIR3`)
  crates/ruff_linter/resources/test/fixtures/airflow/AIR301_names_try.py
  crates/ruff_linter/resources/test/fixtures/airflow/AIR302_try.py
  crates/ruff_linter/resources/test/fixtures/airflow/AIR311_try.py
  crates/ruff_linter/resources/test/fixtures/airflow/AIR312_try.py
  crates/ruff_linter/src/rules/airflow/helpers.rs
  crates/ruff_linter/src/rules/airflow/mod.rs
  crates/ruff_linter/src/rules/airflow/rules/moved_to_provider_in_3.rs
  crates/ruff_linter/src/rules/airflow/rules/removal_in_3.rs
  crates/ruff_linter/src/rules/airflow/rules/suggested_to_move_to_provider_in_3.rs
  crates/ruff_linter/src/rules/airflow/rules/suggested_to_update_3_0.rs
  crates/ruff_linter/src/rules/airflow/snapshots/ruff_linter__rules__airflow__tests__AIR302_AIR302_try.py.snap
  crates/ruff_linter/src/rules/airflow/snapshots/ruff_linter__rules__airflow__tests__AIR311_AIR311_names.py.snap
  crates/ruff_linter/src/rules/airflow/snapshots/ruff_linter__rules__airflow__tests__AIR311_AIR311_try.py.snap
  crates/ruff_linter/src/rules/airflow/snapshots/ruff_linter__rules__airflow__tests__AIR312_AIR312_try.py.snap
Labels: rule, preview

#18056 Update reference documentation for `--python-version`
  crates/ty/docs/cli.md
  crates/ty/src/args.rs
  crates/ty_test/src/config.rs
Labels: documentation, ty

#18053 [ty] Narrowing for `hasattr()`
  crates/ty_python_semantic/resources/mdtest/narrow/hasattr.md
  crates/ty_python_semantic/src/types.rs
  crates/ty_python_semantic/src/types/instance.rs
  crates/ty_python_semantic/src/types/narrow.rs
  crates/ty_python_semantic/src/types/protocol_class.rs
Labels: ty

#18055 [ty] Allow a class to inherit from an intersection if the intersection contains a dynamic type and the intersection is not disjoint from `type`
  crates/ty_python_semantic/resources/mdtest/mro.md
  crates/ty_python_semantic/src/types.rs
  crates/ty_python_semantic/src/types/class_base.rs
Labels: ty

#18060 [ty] Allow classes to inherit from `type[Any]` or `type[Unknown]`
  crates/ty_python_semantic/resources/mdtest/mro.md
  crates/ty_python_semantic/resources/mdtest/snapshots/mro.md_-_Method_Resolution_Order_tests_-_`__bases__`_lists_with_duplicate_bases.snap
  crates/ty_python_semantic/src/types.rs
  crates/ty_python_semantic/src/types/class_base.rs
  crates/ty_python_semantic/src/types/subclass_of.rs
Labels: ty

#18052 [ty] Induct into instances and subclasses when finding and applying generics
  crates/ruff_benchmark/benches/ty.rs
  crates/ty_python_semantic/resources/mdtest/annotations/self.md
  crates/ty_python_semantic/resources/mdtest/generics/legacy/functions.md
  crates/ty_python_semantic/resources/mdtest/generics/pep695/functions.md
  crates/ty_python_semantic/src/types.rs
  crates/ty_python_semantic/src/types/class.rs
  crates/ty_python_semantic/src/types/instance.rs
  crates/ty_python_semantic/src/types/protocol_class.rs
  crates/ty_python_semantic/src/types/subclass_of.rs
Labels: ty

#17998 [ty] Understand homogeneous tuple annotations
  crates/ty_python_semantic/resources/mdtest/annotations/starred.md
  crates/ty_python_semantic/resources/mdtest/annotations/unsupported_special_forms.md
  crates/ty_python_semantic/resources/mdtest/assignment/annotations.md
  crates/ty_python_semantic/resources/mdtest/attributes.md
  crates/ty_python_semantic/resources/mdtest/binary/instances.md
  crates/ty_python_semantic/resources/mdtest/binary/tuples.md
  crates/ty_python_semantic/resources/mdtest/call/builtins.md
  crates/ty_python_semantic/resources/mdtest/exception/basic.md
  crates/ty_python_semantic/resources/mdtest/function/parameters.md
  crates/ty_python_semantic/resources/mdtest/pep695_type_aliases.md
  crates/ty_python_semantic/resources/mdtest/subscript/tuple.md
  crates/ty_python_semantic/resources/mdtest/type_properties/is_assignable_to.md
  crates/ty_python_semantic/resources/mdtest/type_properties/is_disjoint_from.md
  crates/ty_python_semantic/resources/mdtest/type_properties/is_fully_static.md
  crates/ty_python_semantic/resources/mdtest/type_properties/is_subtype_of.md
  crates/ty_python_semantic/src/types.rs
  crates/ty_python_semantic/src/types/infer.rs
Labels: ty

#18021 [ty] Infer parameter specializations of generic aliases
  crates/ty_python_semantic/resources/mdtest/binary/tuples.md
  crates/ty_python_semantic/resources/mdtest/generics/legacy/functions.md
  crates/ty_python_semantic/resources/mdtest/generics/pep695/functions.md
  crates/ty_python_semantic/src/types.rs
  crates/ty_python_semantic/src/types/builder.rs
  crates/ty_python_semantic/src/types/class.rs
  crates/ty_python_semantic/src/types/class_base.rs
  crates/ty_python_semantic/src/types/display.rs
  crates/ty_python_semantic/src/types/generics.rs
  crates/ty_python_semantic/src/types/infer.rs
  crates/ty_python_semantic/src/types/instance.rs
  crates/ty_python_semantic/src/types/narrow.rs
  crates/ty_python_semantic/src/types/type_ordering.rs
Labels: ty

#18064 [ruff_python_ast] Fix redundant visitation of test expressions in elif clause statements
  crates/ruff_python_ast/src/visitor/transformer.rs
Labels: internal

#18018 [ty] Implement `DataClassInstance` protocol for dataclasses.
  crates/ty_python_semantic/resources/mdtest/dataclasses.md
  crates/ty_python_semantic/src/types.rs
  crates/ty_python_semantic/src/types/class.rs
Labels: ty

#18061 [ty] contribution guide
  .github/PULL_REQUEST_TEMPLATE.md
  CONTRIBUTING.md
  crates/ty/CONTRIBUTING.md
  crates/ty/README.md
Labels: documentation, ty

#18050 [ty] Improve diagnostics for `assert_type` and `assert_never`
  crates/ty_python_semantic/resources/mdtest/directives/assert_never.md
  crates/ty_python_semantic/resources/mdtest/directives/assert_type.md
  crates/ty_python_semantic/resources/mdtest/snapshots/assert_never.md_-_`assert_never`_-_Basic_functionality.snap
  crates/ty_python_semantic/resources/mdtest/snapshots/assert_type.md_-_`assert_type`_-_Basic.snap
  crates/ty_python_semantic/src/types/diagnostic.rs
  crates/ty_python_semantic/src/types/infer.rs
Labels: ty, diagnostics

#18068 [ty] Add a note to the diagnostic if a new builtin is used on an old Python version
  crates/ty/docs/rules.md
  crates/ty_python_semantic/resources/mdtest/diagnostics/unresolved_reference.md
  crates/ty_python_semantic/resources/mdtest/snapshots/unresolved_reference.md_-_Diagnostics_for_unresolved_references_-_New_builtin_used_on_old_Python_version.snap
  crates/ty_python_semantic/src/types/diagnostic.rs
Labels: ty, diagnostics

#18054 [ty] Infer parameter specializations of explicitly implemented generic protocols
  crates/ty_python_semantic/resources/mdtest/generics/legacy/functions.md
  crates/ty_python_semantic/resources/mdtest/generics/pep695/functions.md
  crates/ty_python_semantic/src/types.rs
  crates/ty_python_semantic/src/types/display.rs
  crates/ty_python_semantic/src/types/generics.rs
  crates/ty_python_semantic/src/types/instance.rs
Labels: ty

#18072 Use `https://ty.dev/rules` when linking to the rules table
  crates/ty/docs/configuration.md
  crates/ty_project/src/metadata/options.rs
  ty.schema.json
Labels: documentation, ty

#18076 [ty] Add benchmark for union of tuples
  crates/ruff_benchmark/benches/ty.rs
Labels: internal, performance, ty

#18077 [ty] Check assignments to implicit global symbols are assignable to the types declared on `types.ModuleType`
  crates/ty_python_semantic/resources/mdtest/scopes/moduletype_attrs.md
  crates/ty_python_semantic/src/symbol.rs
  crates/ty_python_semantic/src/types/infer.rs
Labels: bug, ty

#18078 [ty] Add cycle handling for unpacking targets
  crates/ty_python_semantic/resources/mdtest/cycle.md
  crates/ty_python_semantic/src/types/infer.rs
  crates/ty_python_semantic/src/types/unpacker.rs
Labels: bug, ty

#18084 [ty] Fix Inconsistent casing in diagnostic
  crates/ty_python_semantic/resources/mdtest/function/return_type.md
  crates/ty_python_semantic/resources/mdtest/generics/legacy/functions.md
  crates/ty_python_semantic/resources/mdtest/generics/pep695/functions.md
  crates/ty_python_semantic/resources/mdtest/snapshots/return_type.md_-_Function_return_type_-_Generator_functions_(d9ed06b61b14fd4c).snap
  crates/ty_python_semantic/resources/mdtest/snapshots/return_type.md_-_Function_return_type_-_Invalid_conditional_…_(94c036c5d3803ab2).snap
  crates/ty_python_semantic/resources/mdtest/snapshots/return_type.md_-_Function_return_type_-_Invalid_implicit_ret…_(393cb38bf7119649).snap
  crates/ty_python_semantic/resources/mdtest/snapshots/return_type.md_-_Function_return_type_-_Invalid_return_type_(a91e0c67519cd77f).snap
  crates/ty_python_semantic/resources/mdtest/snapshots/return_type.md_-_Function_return_type_-_Invalid_return_type_…_(c3a523878447af6b).snap
  crates/ty_python_semantic/src/types/diagnostic.rs
Labels: ty, diagnostics

#18087 [ty] Reduce log level of 'symbol .. (via star import) not found' log message
  crates/ty_python_semantic/src/semantic_index/visibility_constraints.rs
Labels: internal, ty

#18090 Remove double whitespace
  README.md
  docs/configuration.md
Labels: documentation

#18092 [ty] Do not look up `__init__` on instances
  crates/ty_python_semantic/resources/mdtest/attributes.md
  crates/ty_python_semantic/resources/mdtest/named_tuple.md
  crates/ty_python_semantic/src/types.rs
Labels: ty

#17650 [`flake8-pytest-style`] Don't recommend `usefixtures` for parametrize values in `PT019`
  crates/ruff_linter/resources/test/fixtures/flake8_pytest_style/PT019.py
  crates/ruff_linter/src/rules/flake8_pytest_style/rules/fixture.rs
  crates/ruff_linter/src/rules/flake8_pytest_style/snapshots/ruff_linter__rules__flake8_pytest_style__tests__PT019.snap
Labels: rule

#17933 [`pyupgrade`] Add `resource.error` as deprecated alias of `OSError` (`UP024`)
  crates/ruff_linter/resources/test/fixtures/pyupgrade/UP024_2.py
  crates/ruff_linter/src/rules/pyupgrade/rules/os_error_alias.rs
  crates/ruff_linter/src/rules/pyupgrade/snapshots/ruff_linter__rules__pyupgrade__tests__UP024_2.py.snap
Labels: rule

#17755 [`ruff`] add fix safety section (`RUF007`)
  crates/ruff_linter/src/rules/ruff/rules/zip_instead_of_pairwise.rs
Labels: documentation

#17941 [`airflow`] Get rid of `Replacement::Name` and replace them with `Replacement::AutoImport` for enabling auto fixing (`AIR301`, `AIR311`)
  crates/ruff_linter/resources/test/fixtures/airflow/AIR301_names.py
  crates/ruff_linter/src/rules/airflow/helpers.rs
  crates/ruff_linter/src/rules/airflow/rules/removal_in_3.rs
  crates/ruff_linter/src/rules/airflow/rules/suggested_to_update_3_0.rs
  crates/ruff_linter/src/rules/airflow/snapshots/ruff_linter__rules__airflow__tests__AIR301_AIR301_airflow_plugin.py.snap
  crates/ruff_linter/src/rules/airflow/snapshots/ruff_linter__rules__airflow__tests__AIR301_AIR301_args.py.snap
  crates/ruff_linter/src/rules/airflow/snapshots/ruff_linter__rules__airflow__tests__AIR301_AIR301_names.py.snap
Labels: rule, preview

#18073 [ty] improve diagnostics for failure to call overloaded function
  crates/ty_python_semantic/resources/mdtest/diagnostics/no_matching_overload.md
  crates/ty_python_semantic/resources/mdtest/snapshots/no_matching_overload…_-_No_matching_overload…_-_Call_to_function_wit…_(dd80c593d9136f35).snap
  crates/ty_python_semantic/resources/mdtest/snapshots/no_matching_overload…_-_No_matching_overload…_-_Call_to_function_wit…_(f66e3a8a3977c472).snap
  crates/ty_python_semantic/resources/mdtest/snapshots/no_matching_overload…_-_No_matching_overload…_-_Calls_to_overloaded_…_(3553d085684e16a0).snap
  crates/ty_python_semantic/resources/mdtest/snapshots/no_matching_overload…_-_No_matching_overload…_-_Calls_to_overloaded_…_(36814b28492c01d2).snap
  crates/ty_python_semantic/src/types.rs
  crates/ty_python_semantic/src/types/call/bind.rs
  crates/ty_python_semantic/src/types/signatures.rs
Labels: ty, diagnostics

#18095 Remove symlinks from the fuzz directory
  fuzz/.gitignore
  fuzz/README.md
  fuzz/corpus/red_knot_check_invalid_syntax
  fuzz/corpus/ruff_formatter_idempotency
  fuzz/corpus/ruff_formatter_validity
  fuzz/corpus/ruff_new_parser_equiv
  fuzz/corpus/ruff_parse_idempotency
  fuzz/corpus/ruff_parse_simple
  fuzz/init-fuzzer.sh
  fuzz/reinit-fuzzer.sh
Labels: internal

#18096 [ty] fix missing '>' in HTML anchor tags in CLI reference
  crates/ruff_dev/src/generate_ty_cli_reference.rs
  crates/ty/docs/cli.md
Labels: documentation, ty

#18062 [ty] Fix more generics-related TODOs
  crates/ty_python_semantic/resources/mdtest/exception/except_star.md
  crates/ty_python_semantic/src/types/class.rs
  crates/ty_python_semantic/src/types/infer.rs
Labels: ty

#18075 [`flake8-simplify`] Correct behavior for `str.split`/`rsplit` with `maxsplit=0` (`SIM905`)
  crates/ruff_linter/resources/test/fixtures/flake8_simplify/SIM905.py
  crates/ruff_linter/src/rules/flake8_simplify/rules/split_static_string.rs
  crates/ruff_linter/src/rules/flake8_simplify/snapshots/ruff_linter__rules__flake8_simplify__tests__SIM905_SIM905.py.snap
Labels: bug, fixes

#18103 [ty] mypy_primer: fix static-frame setup
  .github/workflows/mypy_primer.yaml
Labels: ci, ty
