Repository astral-sh/ruff, pull requests merged in 2025-07, with the labels that each got.

#19068 [ty] Eagerly evaluate more constraints based on the raw AST
  crates/ty_python_semantic/src/semantic_index/builder.rs
Labels: ty

#18955 [ty] Use all reachable bindings for instance attributes and deferred lookups
  crates/ty_python_semantic/resources/mdtest/attributes.md
  crates/ty_python_semantic/src/place.rs
  crates/ty_python_semantic/src/semantic_index.rs
  crates/ty_python_semantic/src/semantic_index/builder.rs
  crates/ty_python_semantic/src/types/class.rs
  crates/ty_python_semantic/src/types/infer.rs
  crates/ty_python_semantic/src/types/signatures.rs
Labels: ty, ecosystem-analyzer

#18899 [`ruff`] Fix syntax error introduced for an empty string followed by a u-prefixed string (`UP025`)
  crates/ruff_linter/resources/test/fixtures/pyupgrade/UP025.py
  crates/ruff_linter/src/rules/pyupgrade/rules/unicode_kind_prefix.rs
  crates/ruff_linter/src/rules/pyupgrade/snapshots/ruff_linter__rules__pyupgrade__tests__UP025.py.snap
Labels: bug, fixes

#19058 [`refurb`] Fix false positive on empty tuples (`FURB168`)
  crates/ruff_linter/resources/test/fixtures/refurb/FURB168.py
  crates/ruff_linter/src/rules/refurb/rules/isinstance_type_none.rs
Labels: bug, rule

#19072 Docs: Add Anki to Who's Using Ruff
  README.md
Labels: documentation, internal

#19073 Remove new codspeed dependencies
  Cargo.lock
  Cargo.toml
Labels: internal

#19074 [ty] Add some missing calls to `normalized_impl`
  crates/ty_python_semantic/src/types/generics.rs
  crates/ty_python_semantic/src/types/tuple.rs
Labels: internal, ty

#19083 [ty] Use better datetime format for server logs
  crates/ty_server/Cargo.toml
  crates/ty_server/src/logging.rs
Labels: internal, server, ty

#19079 [`flake8-pyi`] Make example error out-of-the-box (`PYI062`)
  crates/ruff_linter/src/rules/flake8_pyi/rules/duplicate_literal_member.rs
Labels: documentation

#19087 [ty] Adapt generate_ty_rules for MkDocs
  crates/ruff_dev/src/generate_ty_rules.rs
  crates/ty/docs/rules.md
Labels: documentation, internal, ty

#19089 Fix header levels in generated settings reference
  crates/ruff_dev/src/generate_ty_options.rs
  crates/ty/docs/configuration.md
Labels: documentation, ty

#19090 [ty] Fix link in generate_ty_rules
  crates/ruff_dev/src/generate_ty_rules.rs
  crates/ty/docs/rules.md
Labels: documentation, internal, ty

#19080 [`flake8-pyi`] Make example error out-of-the-box (`PYI059`)
  crates/ruff_linter/src/rules/flake8_pyi/rules/generic_not_last_base_class.rs
Labels: documentation

#19019 [ty] Remove `ScopedExpressionId`
  crates/ty_python_semantic/src/dunder_all.rs
  crates/ty_python_semantic/src/semantic_index/ast_ids.rs
  crates/ty_python_semantic/src/semantic_index/builder.rs
  crates/ty_python_semantic/src/semantic_model.rs
  crates/ty_python_semantic/src/types.rs
  crates/ty_python_semantic/src/types/class.rs
  crates/ty_python_semantic/src/types/infer.rs
  crates/ty_python_semantic/src/types/narrow.rs
  crates/ty_python_semantic/src/types/unpacker.rs
  crates/ty_python_semantic/src/unpack.rs
Labels: performance, ty

#19071 [ty] Allow declared-only class-level attributes to be accessed on the class
  crates/ty_python_semantic/resources/mdtest/attributes.md
  crates/ty_python_semantic/resources/mdtest/call/dunder.md
  crates/ty_python_semantic/resources/mdtest/dataclasses.md
  crates/ty_python_semantic/resources/mdtest/protocols.md
  crates/ty_python_semantic/resources/mdtest/type_qualifiers/classvar.md
  crates/ty_python_semantic/src/place.rs
Labels: ty, ecosystem-analyzer

#19026 [ty] Add subtyping between SubclassOf and CallableType
  crates/ty_python_semantic/resources/mdtest/type_properties/is_assignable_to.md
  crates/ty_python_semantic/resources/mdtest/type_properties/is_subtype_of.md
  crates/ty_python_semantic/src/types.rs
Labels: ty

#19117 [ty] Restructure/move dataclass tests
  crates/ty_python_semantic/resources/mdtest/dataclasses/dataclass_transform.md
  crates/ty_python_semantic/resources/mdtest/dataclasses/dataclasses.md
  crates/ty_python_semantic/resources/mdtest/snapshots/dataclasses.md_-_Dataclasses_-_`dataclasses.KW_ONLY…_(dd1b8f2f71487f16).snap
Labels: internal, testing, ty

#19113 [`flake8-simplify`] Make example error out-of-the-box (`SIM110`)
  crates/ruff_linter/src/rules/flake8_simplify/rules/reimplemented_builtin.rs
Labels: documentation

#19109 [`flake8-simplify`] Make example error out-of-the-box (`SIM113`)
  crates/ruff_linter/src/rules/flake8_simplify/rules/enumerate_for_loop.rs
Labels: documentation

#19106 [`flake8-quotes`] Make example error out-of-the-box (`Q003`)
  crates/ruff_linter/src/rules/flake8_quotes/rules/avoidable_escaped_quote.rs
Labels: documentation

#19104 [`flake8-pytest-style`] Make example error out-of-the-box (`PT023`)
  crates/ruff_linter/src/rules/flake8_pytest_style/rules/marks.rs
Labels: documentation

#19121 Filter private symbols from stubs if they are internal types
  crates/ty_ide/src/completion.rs
  crates/ty_python_semantic/src/lib.rs
  crates/ty_python_semantic/src/semantic_model.rs
  crates/ty_python_semantic/src/types/ide_support.rs
Labels: server, ty

#19126 Bump 0.12.2
  CHANGELOG.md
  Cargo.lock
  README.md
  crates/ruff/Cargo.toml
  crates/ruff_linter/Cargo.toml
  crates/ruff_wasm/Cargo.toml
  docs/integrations.md
  docs/tutorial.md
  pyproject.toml
  scripts/benchmarks/pyproject.toml
Labels: release

#19094 [ty] Rewrite `Type::any_over_type` using a new generalised `TypeVisitor` trait
  crates/ty_python_semantic/src/lib.rs
  crates/ty_python_semantic/src/types.rs
  crates/ty_python_semantic/src/types/class.rs
  crates/ty_python_semantic/src/types/class_base.rs
  crates/ty_python_semantic/src/types/cyclic.rs
  crates/ty_python_semantic/src/types/function.rs
  crates/ty_python_semantic/src/types/generics.rs
  crates/ty_python_semantic/src/types/instance.rs
  crates/ty_python_semantic/src/types/protocol_class.rs
  crates/ty_python_semantic/src/types/signatures.rs
  crates/ty_python_semantic/src/types/subclass_of.rs
  crates/ty_python_semantic/src/types/tuple.rs
  crates/ty_python_semantic/src/types/visitor.rs
Labels: internal, ty

#19130 [ty] Add into_callable method for Type
  crates/ty_python_semantic/src/types.rs
Labels: ty

#19139 [ty] detect cycles in Type::is_disjoint_from
  crates/ty_python_semantic/resources/mdtest/protocols.md
  crates/ty_python_semantic/src/types.rs
  crates/ty_python_semantic/src/types/cyclic.rs
  crates/ty_python_semantic/src/types/instance.rs
  crates/ty_python_semantic/src/types/protocol_class.rs
  crates/ty_python_semantic/src/types/subclass_of.rs
  crates/ty_python_semantic/src/types/tuple.rs
Labels: ty

#19124 Add Weblate to Who's Using Ruff
  README.md
Labels: documentation, internal

#19148 [ty] Add a `DateType` benchmark
  crates/ruff_benchmark/benches/ty.rs
Labels: performance, testing, ty

#19120 [ty] Fix descriptor lookups for most types that overlap with `None`
  crates/ty_python_semantic/resources/mdtest/annotations/callable.md
  crates/ty_python_semantic/resources/mdtest/call/methods.md
  crates/ty_python_semantic/resources/mdtest/descriptor_protocol.md
  crates/ty_python_semantic/src/types.rs
Labels: bug, ty

#18659 [ty] Implement equivalence for protocols with method members
  crates/ty_python_semantic/resources/mdtest/protocols.md
  crates/ty_python_semantic/resources/mdtest/type_properties/is_equivalent_to.md
  crates/ty_python_semantic/src/types.rs
  crates/ty_python_semantic/src/types/cyclic.rs
  crates/ty_python_semantic/src/types/function.rs
  crates/ty_python_semantic/src/types/instance.rs
  crates/ty_python_semantic/src/types/protocol_class.rs
  crates/ty_python_semantic/src/types/signatures.rs
Labels: ty

#19176 [ty] Re-enable multithreaded pydantic benchmark
  crates/ruff_benchmark/benches/ty_walltime.rs
Labels: internal, performance, ty

#19177 Rename to `SessionSnapshot`, move unwind assertion closer
  crates/ty_server/src/server/api.rs
  crates/ty_server/src/server/api/diagnostics.rs
  crates/ty_server/src/server/api/requests/workspace_diagnostic.rs
  crates/ty_server/src/server/api/traits.rs
  crates/ty_server/src/session.rs
Labels: internal

#19137 [ty] Add documentation for server traits
  crates/ruff_server/src/server/api.rs
  crates/ruff_server/src/server/api/traits.rs
  crates/ty_server/src/server/api/requests/diagnostic.rs
  crates/ty_server/src/server/api/traits.rs
Labels: internal, server

#19134 [ty] Add separate CI job for memory usage stats
  .github/workflows/mypy_primer.yaml
  .github/workflows/mypy_primer_comment.yaml
  crates/ty/src/lib.rs
  crates/ty_project/src/db.rs
  crates/ty_python_semantic/resources/primer/memory.txt
  scripts/mypy_primer.sh
Labels: ci, ty

#19103 [`flake8-pyi`] Make example error out-of-the-box (`PYI007`, `PYI008`)
  crates/ruff_linter/src/rules/flake8_pyi/rules/unrecognized_platform.rs
Labels: documentation

#18922 [`flake8-use-pathlib`] Add autofixes for `PTH203`, `PTH204`, `PTH205`
  crates/ruff_linter/resources/test/fixtures/flake8_use_pathlib/PTH203.py
  crates/ruff_linter/src/checkers/ast/analyze/expression.rs
  crates/ruff_linter/src/preview.rs
  crates/ruff_linter/src/rules/flake8_use_pathlib/helpers.rs
  crates/ruff_linter/src/rules/flake8_use_pathlib/mod.rs
  crates/ruff_linter/src/rules/flake8_use_pathlib/rules/os_path_getatime.rs
  crates/ruff_linter/src/rules/flake8_use_pathlib/rules/os_path_getctime.rs
  crates/ruff_linter/src/rules/flake8_use_pathlib/rules/os_path_getmtime.rs
  crates/ruff_linter/src/rules/flake8_use_pathlib/rules/os_path_getsize.rs
  crates/ruff_linter/src/rules/flake8_use_pathlib/rules/replaceable_by_pathlib.rs
  crates/ruff_linter/src/rules/flake8_use_pathlib/snapshots/ruff_linter__rules__flake8_use_pathlib__tests__PTH202_PTH202.py.snap
  crates/ruff_linter/src/rules/flake8_use_pathlib/snapshots/ruff_linter__rules__flake8_use_pathlib__tests__PTH202_PTH202_2.py.snap
  crates/ruff_linter/src/rules/flake8_use_pathlib/snapshots/ruff_linter__rules__flake8_use_pathlib__tests__PTH203_PTH203.py.snap
  crates/ruff_linter/src/rules/flake8_use_pathlib/snapshots/ruff_linter__rules__flake8_use_pathlib__tests__PTH204_PTH204.py.snap
  crates/ruff_linter/src/rules/flake8_use_pathlib/snapshots/ruff_linter__rules__flake8_use_pathlib__tests__PTH205_PTH205.py.snap
  crates/ruff_linter/src/rules/flake8_use_pathlib/snapshots/ruff_linter__rules__flake8_use_pathlib__tests__preview__PTH202_PTH202.py.snap
  crates/ruff_linter/src/rules/flake8_use_pathlib/snapshots/ruff_linter__rules__flake8_use_pathlib__tests__preview__PTH202_PTH202_2.py.snap
  crates/ruff_linter/src/rules/flake8_use_pathlib/snapshots/ruff_linter__rules__flake8_use_pathlib__tests__preview__PTH203_PTH203.py.snap
  crates/ruff_linter/src/rules/flake8_use_pathlib/snapshots/ruff_linter__rules__flake8_use_pathlib__tests__preview__PTH204_PTH204.py.snap
  crates/ruff_linter/src/rules/flake8_use_pathlib/snapshots/ruff_linter__rules__flake8_use_pathlib__tests__preview__PTH205_PTH205.py.snap
Labels: fixes, preview

#19111 [`flake8-simplify`] Make example error out-of-the-box (`SIM116`)
  crates/ruff_linter/src/rules/flake8_simplify/rules/if_else_block_instead_of_dict_lookup.rs
Labels: documentation

#19108 [ty] First cut at semantic token provider
  Cargo.lock
  crates/ty_ide/Cargo.toml
  crates/ty_ide/src/lib.rs
  crates/ty_ide/src/semantic_tokens.rs
  crates/ty_python_semantic/src/types.rs
  crates/ty_python_semantic/src/types/ide_support.rs
  crates/ty_server/src/server.rs
  crates/ty_server/src/server/api.rs
  crates/ty_server/src/server/api/requests.rs
  crates/ty_server/src/server/api/requests/semantic_tokens.rs
  crates/ty_server/src/server/api/requests/semantic_tokens_range.rs
  crates/ty_server/src/server/api/semantic_tokens.rs
  crates/ty_server/src/session/capabilities.rs
Labels: server, ty

#19195 [ty] Add an empty line to separate bullet points
  crates/ty/docs/configuration.md
  crates/ty_project/src/metadata/options.rs
  ty.schema.json
Labels: internal

#19203 [ty] Clarify diagnostic message
  crates/ty_python_semantic/resources/mdtest/attributes.md
  crates/ty_python_semantic/src/types/infer.rs
Labels: internal, ty

#19202 [ty] Add tests for dataclass fields annotated with `Final`
  crates/ty_python_semantic/resources/mdtest/dataclasses/dataclasses.md
  crates/ty_python_semantic/resources/mdtest/type_qualifiers/final.md
Labels: testing, ty

#19179 Rename `Diagnostic::syntax_error` methods, separate `Ord` implementation
  crates/ruff/src/cache.rs
  crates/ruff/src/commands/check.rs
  crates/ruff/src/commands/check_stdin.rs
  crates/ruff/src/diagnostics.rs
  crates/ruff_db/src/diagnostic/mod.rs
  crates/ruff_linter/src/checkers/ast/mod.rs
  crates/ruff_linter/src/fix/edits.rs
  crates/ruff_linter/src/fix/mod.rs
  crates/ruff_linter/src/linter.rs
  crates/ruff_linter/src/message/mod.rs
  crates/ruff_linter/src/noqa.rs
  crates/ruff_linter/src/pyproject_toml.rs
  crates/ruff_linter/src/rules/pyflakes/mod.rs
  crates/ruff_linter/src/test.rs
  crates/ruff_linter/src/violation.rs
  crates/ruff_server/src/lint.rs
  crates/ty_project/src/lib.rs
  crates/ty_python_semantic/src/types.rs
  crates/ty_test/src/lib.rs
Labels: internal

#19197 [ty] Conditionally defined dataclass fields
  crates/ty_python_semantic/resources/mdtest/dataclasses/dataclasses.md
  crates/ty_python_semantic/resources/mdtest/snapshots/dataclasses.md_-_Dataclasses_-_`dataclasses.KW_ONLY…_(dd1b8f2f71487f16).snap
  crates/ty_python_semantic/src/types/class.rs
Labels: ty

#19206 [ty] Do not report settings diagnostics in `check_file`
  crates/ty_project/src/lib.rs
Labels: server, ty

#19178 [ty] Enforce `typing.Final`
  crates/ty_python_semantic/resources/mdtest/snapshots/final.md_-_`typing.Final`_-_Full_diagnostics_(174fdd8134fb325b).snap
  crates/ty_python_semantic/resources/mdtest/type_qualifiers/final.md
  crates/ty_python_semantic/src/semantic_index/definition.rs
  crates/ty_python_semantic/src/semantic_index/use_def.rs
  crates/ty_python_semantic/src/types.rs
  crates/ty_python_semantic/src/types/infer.rs
Labels: ty, ecosystem-analyzer

#18949 [`pylint`] Update `missing-maxsplit-arg` docs and error to suggest proper usage (`PLC0207`)
  crates/ruff_linter/src/rules/pylint/rules/missing_maxsplit_arg.rs
  crates/ruff_linter/src/rules/pylint/snapshots/ruff_linter__rules__pylint__tests__PLC0207_missing_maxsplit_arg.py.snap
Labels: documentation

#19069 [ty] Fix panic for attribute expressions with empty value
  crates/ty_python_semantic/resources/corpus/88_regression_issue_738.py
  crates/ty_python_semantic/src/types/infer.rs
Labels: ty

#19140 [ty] `dataclasses.field` support
  crates/ty_python_semantic/resources/mdtest/dataclasses/fields.md
Labels: internal, testing, ty

#19192 [ty] Fix `ClassLiteral.into_callable` for dataclasses
  crates/ty_python_semantic/resources/mdtest/type_properties/is_subtype_of.md
  crates/ty_python_semantic/src/types/class.rs
Labels: ty

#19229 [ty] Merge `ty_macros` into `ruff_macros`
  Cargo.lock
  Cargo.toml
  crates/ruff_macros/src/env_vars.rs
  crates/ruff_macros/src/lib.rs
  crates/ty_macros/Cargo.toml
  crates/ty_macros/src/lib.rs
  crates/ty_static/Cargo.toml
  crates/ty_static/src/env_vars.rs
Labels: internal, ty

#19131 [`pyupgrade`] Keyword arguments in `super` should suppress the `UP008` fix
  crates/ruff_linter/resources/test/fixtures/pyupgrade/UP008.py
  crates/ruff_linter/src/rules/pyupgrade/rules/super_call_with_parameters.rs
  crates/ruff_linter/src/rules/pyupgrade/snapshots/ruff_linter__rules__pyupgrade__tests__UP008.py.snap
  crates/ruff_linter/src/rules/pyupgrade/snapshots/ruff_linter__rules__pyupgrade__tests__UP008.py__preview.snap
Labels: bug, fixes

#19251 [ty] Add completion kind to playground
  crates/ty_wasm/src/lib.rs
  playground/ty/src/Editor/Editor.tsx
Labels: playground, ty

#19252 [ty] Ecosystem analyzer: parallelize, fix race condition
  .github/workflows/ty-ecosystem-analyzer.yaml
Labels: ci, ty, ecosystem-analyzer

#19230 [ty] Optimize protocol subtyping by removing expensive and unnecessary equivalence check from the top of `Type::has_relation_to()`
  crates/ty_python_semantic/src/types.rs
  crates/ty_python_semantic/src/types/class.rs
Labels: performance, ty

#19257 [ty] Remove countme from salsa-structs
  Cargo.lock
  crates/ty/Cargo.toml
  crates/ty/src/lib.rs
  crates/ty_python_semantic/Cargo.toml
  crates/ty_python_semantic/src/semantic_index/builder.rs
  crates/ty_python_semantic/src/semantic_index/definition.rs
  crates/ty_python_semantic/src/semantic_index/expression.rs
  crates/ty_python_semantic/src/semantic_index/place.rs
  crates/ty_python_semantic/src/semantic_index/predicate.rs
  crates/ty_python_semantic/src/unpack.rs
Labels: internal, ty

#18433 [`flake8-return`] Fix false-positive for variables used inside nested functions in `RET504`
  crates/ruff_linter/resources/test/fixtures/flake8_return/RET504.py
  crates/ruff_linter/src/checkers/ast/analyze/bindings.rs
  crates/ruff_linter/src/checkers/ast/analyze/statement.rs
  crates/ruff_linter/src/rules/flake8_return/rules/function.rs
  crates/ruff_linter/src/rules/flake8_return/snapshots/ruff_linter__rules__flake8_return__tests__RET504_RET504.py.snap
  crates/ruff_python_semantic/src/model.rs
Labels: bug

#19265 Add simple integration tests for all output formats
  crates/ruff/tests/lint.rs
  crates/ruff/tests/snapshots/lint__output_format_azure.snap
  crates/ruff/tests/snapshots/lint__output_format_concise.snap
  crates/ruff/tests/snapshots/lint__output_format_full.snap
  crates/ruff/tests/snapshots/lint__output_format_github.snap
  crates/ruff/tests/snapshots/lint__output_format_gitlab.snap
  crates/ruff/tests/snapshots/lint__output_format_grouped.snap
  crates/ruff/tests/snapshots/lint__output_format_json-lines.snap
  crates/ruff/tests/snapshots/lint__output_format_json.snap
  crates/ruff/tests/snapshots/lint__output_format_junit.snap
  crates/ruff/tests/snapshots/lint__output_format_pylint.snap
  crates/ruff/tests/snapshots/lint__output_format_rdjson.snap
  crates/ruff/tests/snapshots/lint__output_format_sarif.snap
Labels: internal, testing

#19280 Filter `ruff_linter::VERSION` out of SARIF output tests
  crates/ruff/tests/lint.rs
  crates/ruff/tests/snapshots/lint__output_format_sarif.snap
Labels: internal, testing

#19270 Use structs for JSON serialization
  crates/ruff_db/src/diagnostic/mod.rs
  crates/ruff_linter/src/message/diff.rs
  crates/ruff_linter/src/message/json.rs
Labels: internal, diagnostics

#19222 Fix I002 import insertion after docstring with multiple string statements
  crates/ruff_linter/resources/test/fixtures/isort/required_imports/multiple_strings.py
  crates/ruff_linter/src/importer/insertion.rs
  crates/ruff_linter/src/rules/isort/mod.rs
  crates/ruff_linter/src/rules/isort/snapshots/ruff_linter__rules__isort__tests__required_imports_multiple_strings.py.snap
Labels: fixes

#19133 Render Azure, JSON, and JSON lines output with the new diagnostics
  Cargo.lock
  crates/ruff/src/lib.rs
  crates/ruff/src/printer.rs
  crates/ruff_db/Cargo.toml
  crates/ruff_db/src/diagnostic/mod.rs
  crates/ruff_db/src/diagnostic/render.rs
  crates/ruff_db/src/diagnostic/render/azure.rs
  crates/ruff_db/src/diagnostic/render/json.rs
  crates/ruff_db/src/diagnostic/render/json_lines.rs
  crates/ruff_db/src/diagnostic/render/snapshots/ruff_db__diagnostic__render__azure__tests__output.snap
  crates/ruff_db/src/diagnostic/render/snapshots/ruff_db__diagnostic__render__azure__tests__syntax_errors.snap
  crates/ruff_db/src/diagnostic/render/snapshots/ruff_db__diagnostic__render__json__tests__notebook_output.snap
  crates/ruff_db/src/diagnostic/render/snapshots/ruff_db__diagnostic__render__json__tests__output.snap
  crates/ruff_db/src/diagnostic/render/snapshots/ruff_db__diagnostic__render__json__tests__syntax_errors.snap
  crates/ruff_db/src/diagnostic/render/snapshots/ruff_db__diagnostic__render__json_lines__tests__notebook_output.snap
  crates/ruff_db/src/diagnostic/render/snapshots/ruff_db__diagnostic__render__json_lines__tests__output.snap
  crates/ruff_db/src/diagnostic/render/snapshots/ruff_db__diagnostic__render__json_lines__tests__syntax_errors.snap
  crates/ruff_linter/src/message/azure.rs
  crates/ruff_linter/src/message/json.rs
  crates/ruff_linter/src/message/json_lines.rs
  crates/ruff_linter/src/message/mod.rs
  crates/ruff_linter/src/message/rdjson.rs
  crates/ruff_server/src/lint.rs
  crates/ty/src/args.rs
  crates/ty/src/lib.rs
  crates/ty_project/src/metadata/options.rs
  crates/ty_project/src/metadata/settings.rs
  ty.schema.json
Labels: internal, diagnostics

#19296 [`pyupgrade`] Make example error out-of-the-box (`UP040`)
  crates/ruff_linter/src/rules/pyupgrade/rules/pep695/non_pep695_type_alias.rs
Labels: documentation

#19262 [ty] Handle configuration errors in LSP more gracefully
  crates/ty_server/src/server/main_loop.rs
  crates/ty_server/src/session.rs
  crates/ty_server/src/system.rs
Labels: server, ty

#19283 [ty] List all `enum` members
  crates/ty_python_semantic/resources/mdtest/enums.md
  crates/ty_python_semantic/src/types.rs
  crates/ty_python_semantic/src/types/call/bind.rs
  crates/ty_python_semantic/src/types/class.rs
  crates/ty_python_semantic/src/types/enums.rs
  crates/ty_python_semantic/src/types/function.rs
  crates/ty_vendored/ty_extensions/ty_extensions.pyi
Labels: testing, ty

#19025 [ty] Use an interval map for scopes by expression
  crates/ruff_python_ast/src/node_index.rs
  crates/ty_python_semantic/src/semantic_index.rs
  crates/ty_python_semantic/src/semantic_index/builder.rs
  crates/ty_python_semantic/src/semantic_model.rs
Labels: internal, ty

#19286 [ty] Fix handling of metaclasses in `object.<CURSOR>` completions
  crates/ty_ide/src/completion.rs
  crates/ty_python_semantic/src/types/ide_support.rs
Labels: server, ty

#19322 [ty] Add virtual files to the only project database
  crates/ty_server/src/server/api.rs
  crates/ty_server/src/server/api/diagnostics.rs
  crates/ty_server/src/server/api/notifications/did_change.rs
  crates/ty_server/src/server/api/notifications/did_open.rs
  crates/ty_server/src/server/api/notifications/did_open_notebook.rs
  crates/ty_server/src/session.rs
Labels: server, ty

#19311 [ty] Provide docstrings for stdlib APIs when hovering over them in an IDE
  .github/workflows/sync_typeshed.yaml
Labels: internal, ty

#19347 [ty] Make use of salsa `Lookup` when interning values
  crates/ty_python_semantic/src/semantic_index/builder.rs
  crates/ty_python_semantic/src/types.rs
  crates/ty_python_semantic/src/types/class.rs
  crates/ty_python_semantic/src/types/infer.rs
Labels: internal, ty

#19349 [ty] Add ecosystem-report workflow
  .github/workflows/ty-ecosystem-report.yaml
  .github/zizmor.yml
Labels: ci, ty

#19352 [ty] Use `Type::string_literal()` more
  crates/ty_python_semantic/src/types.rs
  crates/ty_python_semantic/src/types/display.rs
  crates/ty_python_semantic/src/types/infer.rs
Labels: internal, ty

#19353 [ty] Remove `ConnectionInitializer`
  crates/ty_server/src/lib.rs
  crates/ty_server/src/server.rs
  crates/ty_server/src/server/connection.rs
  crates/ty_server/src/server/main_loop.rs
Labels: internal, server, ty

#19340 Move Pylint rendering to `ruff_db`
  crates/ruff/src/printer.rs
  crates/ruff/tests/snapshots/lint__output_format_pylint.snap
  crates/ruff_db/src/diagnostic/mod.rs
  crates/ruff_db/src/diagnostic/render.rs
  crates/ruff_db/src/diagnostic/render/pylint.rs
  crates/ruff_db/src/diagnostic/render/snapshots/ruff_db__diagnostic__render__pylint__tests__output.snap
  crates/ruff_db/src/diagnostic/render/snapshots/ruff_db__diagnostic__render__pylint__tests__syntax_errors.snap
  crates/ruff_linter/src/message/mod.rs
  crates/ruff_linter/src/message/pylint.rs
  crates/ruff_linter/src/message/snapshots/ruff_linter__message__pylint__tests__syntax_errors.snap
  crates/ruff_source_file/src/line_index.rs
Labels: internal, diagnostics

#19360 Rework typeshed-sync workflow to also add docstrings for Windows- and MacOS-specific APIs
  .github/workflows/sync_typeshed.yaml
  scripts/codemod_docstrings.sh
Labels: ci, ty

#19367 Fix typeshed-sync workflow
  .github/workflows/sync_typeshed.yaml
  scripts/codemod_docstrings.sh
Labels: ci

#19344 [ty] lint on the `global` keyword if there's no explicit definition in the…
  crates/ty/docs/rules.md
  crates/ty_python_semantic/resources/mdtest/diagnostics/semantic_syntax_errors.md
  crates/ty_python_semantic/resources/mdtest/import/star.md
  crates/ty_python_semantic/resources/mdtest/scopes/global.md
  crates/ty_python_semantic/resources/mdtest/scopes/nonlocal.md
  crates/ty_python_semantic/src/types/diagnostic.rs
  crates/ty_python_semantic/src/types/infer.rs
  ty.schema.json
Labels: ty, ecosystem-analyzer

#19373 chore: Document Material for MkDocs Insiders limitations in CONTRIBUTING.md in more detail
  CONTRIBUTING.md
Labels: documentation, internal

#19336 [ty] fix a couple latent bugs uncovered during `nonlocal` work
  crates/ty_python_semantic/resources/mdtest/scopes/nonlocal.md
  crates/ty_python_semantic/src/types/infer.rs
Labels: ty, ecosystem-analyzer

#19379 [ty] use the name span rather than the statement span for unresolved `global` lints
  crates/ty_python_semantic/src/types/infer.rs
Labels: internal, ty

#19136 [`refurb`] `FURB164` fix should validate arguments and should usually be marked unsafe
  crates/ruff_linter/resources/test/fixtures/refurb/FURB164.py
  crates/ruff_linter/src/rules/refurb/rules/unnecessary_from_float.rs
  crates/ruff_linter/src/rules/refurb/snapshots/ruff_linter__rules__refurb__tests__FURB164_FURB164.py.snap
Labels: bug, fixes

#19304 [`pylint`] Detect indirect `pathlib.Path` usages for `unspecified-encoding` (PLW1514)
  crates/ruff_linter/resources/test/fixtures/pylint/unspecified_encoding.py
  crates/ruff_linter/src/rules/pylint/rules/unspecified_encoding.rs
  crates/ruff_linter/src/rules/pylint/snapshots/ruff_linter__rules__pylint__tests__PLW1514_unspecified_encoding.py.snap
Labels: rule, preview

#19388 [`flake8-use-pathlib`] Fix false negative on direct `Path()` instantiation (`PTH210`)
  crates/ruff_linter/resources/test/fixtures/flake8_use_pathlib/PTH210.py
  crates/ruff_linter/src/rules/flake8_use_pathlib/rules/invalid_pathlib_with_suffix.rs
  crates/ruff_linter/src/rules/flake8_use_pathlib/snapshots/ruff_linter__rules__flake8_use_pathlib__tests__PTH210_PTH210.py.snap
Labels: bug, rule

#19371 [ty] Initial implementation of declaration and definition providers.
  crates/ty_ide/src/goto.rs
  crates/ty_ide/src/goto_declaration.rs
  crates/ty_ide/src/goto_definition.rs
  crates/ty_ide/src/goto_type_definition.rs
  crates/ty_ide/src/lib.rs
  crates/ty_ide/src/stub_mapping.rs
  crates/ty_python_semantic/src/lib.rs
  crates/ty_python_semantic/src/semantic_index.rs
  crates/ty_python_semantic/src/semantic_index/definition.rs
  crates/ty_python_semantic/src/types.rs
  crates/ty_python_semantic/src/types/ide_support.rs
  crates/ty_server/src/server.rs
  crates/ty_server/src/server/api.rs
  crates/ty_server/src/server/api/requests.rs
  crates/ty_server/src/server/api/requests/goto_declaration.rs
  crates/ty_server/src/server/api/requests/goto_definition.rs
Labels: server, ty

#19393 [ty] Use `bitflags` for resolved client capabilities
  Cargo.lock
  crates/ty_server/Cargo.toml
  crates/ty_server/src/server/api/diagnostics.rs
  crates/ty_server/src/server/api/notifications/did_change_watched_files.rs
  crates/ty_server/src/server/api/requests/goto_declaration.rs
  crates/ty_server/src/server/api/requests/goto_definition.rs
  crates/ty_server/src/server/api/requests/goto_type_definition.rs
  crates/ty_server/src/server/api/requests/hover.rs
  crates/ty_server/src/server/api/requests/semantic_tokens.rs
  crates/ty_server/src/server/api/requests/semantic_tokens_range.rs
  crates/ty_server/src/server/api/requests/signature_help.rs
  crates/ty_server/src/session.rs
  crates/ty_server/src/session/capabilities.rs
Labels: internal, server, ty

#19335 [ty] publish settings diagnostics
  crates/ty_project/src/lib.rs
  crates/ty_server/src/server.rs
  crates/ty_server/src/server/api.rs
  crates/ty_server/src/server/api/diagnostics.rs
  crates/ty_server/src/server/api/notifications/did_change_watched_files.rs
  crates/ty_server/src/session.rs
Labels: server, ty, diagnostics

#19407 Canonicalize path before filtering
  crates/ruff/tests/lint.rs
Labels: internal

#19410 [ty] Shrink reachability constraints
  crates/ty_python_semantic/src/semantic_index/reachability_constraints.rs
Labels: ty

#19418 [ty] Fixed bug in semantic token provider for parameters.
  crates/ty_ide/src/semantic_tokens.rs
Labels: bug, server, ty

#19307 [ty] synthesize __setattr__ for frozen dataclasses
  crates/ty_python_semantic/resources/mdtest/attributes.md
  crates/ty_python_semantic/resources/mdtest/dataclasses/dataclasses.md
  crates/ty_python_semantic/src/types/class.rs
  crates/ty_python_semantic/src/types/infer.rs
Labels: ty

#19264 [ty] Track open files in the server
  crates/ruff_benchmark/benches/ty.rs
  crates/ruff_db/src/files.rs
  crates/ruff_graph/src/db.rs
  crates/ty_ide/src/db.rs
  crates/ty_project/src/db.rs
  crates/ty_project/src/files.rs
  crates/ty_project/src/lib.rs
  crates/ty_project/src/metadata.rs
  crates/ty_python_semantic/src/db.rs
  crates/ty_python_semantic/src/semantic_index/builder.rs
  crates/ty_python_semantic/src/types/context.rs
  crates/ty_python_semantic/tests/corpus.rs
  crates/ty_server/src/logging.rs
  crates/ty_server/src/server/api/notifications/did_close.rs
  crates/ty_server/src/server/api/notifications/did_open.rs
  crates/ty_server/src/server/api/requests/workspace_diagnostic.rs
  crates/ty_server/src/session.rs
  crates/ty_server/src/session/index.rs
  crates/ty_server/src/session/options.rs
  crates/ty_test/src/db.rs
  crates/ty_wasm/src/lib.rs
  fuzz/fuzz_targets/ty_check_invalid_syntax.rs
Labels: internal, server, ty

#19409 [ty] Reduce number of inline stored definitions per place
  Cargo.toml
  crates/ty_ide/src/lib.rs
  crates/ty_python_semantic/src/semantic_index/definition.rs
  crates/ty_python_semantic/src/semantic_index/place.rs
  crates/ty_python_semantic/src/semantic_index/use_def/place_state.rs
  crates/ty_python_semantic/src/suppression.rs
  crates/ty_python_semantic/src/types.rs
  crates/ty_python_semantic/src/types/call/bind.rs
  crates/ty_python_semantic/src/types/signatures.rs
Labels: ty

#19417 [ty] Added support for "go to definition" for attribute accesses and keyword arguments
  crates/ty_ide/src/goto.rs
  crates/ty_ide/src/goto_declaration.rs
  crates/ty_python_semantic/src/lib.rs
  crates/ty_python_semantic/src/types.rs
  crates/ty_python_semantic/src/types/ide_support.rs
Labels: server, ty

#19389 [ty] make `del x` force local resolution of `x` in the current scope
  crates/ty_python_semantic/resources/mdtest/del.md
  crates/ty_python_semantic/resources/mdtest/scopes/nonlocal.md
  crates/ty_python_semantic/src/semantic_index/builder.rs
  crates/ty_python_semantic/src/types/infer.rs
Labels: ty, ecosystem-analyzer

#19429 [ty] Avoid secondary tree traversal to get call expression for keyword arguments
  crates/ty_ide/src/find_node.rs
  crates/ty_ide/src/goto.rs
Labels: internal, ty

#18926 [`ruff`] Support byte strings (`RUF055`)
  crates/ruff_linter/resources/test/fixtures/ruff/RUF055_3.py
  crates/ruff_linter/src/rules/ruff/mod.rs
  crates/ruff_linter/src/rules/ruff/rules/unnecessary_regular_expression.rs
  crates/ruff_linter/src/rules/ruff/snapshots/ruff_linter__rules__ruff__tests__preview__RUF055_RUF055_3.py.snap
Labels: rule, preview

#19463 [ty] Avoid rechecking the entire project when changing the opened files
  crates/ty_project/src/lib.rs
Labels: server, ty

#19462 [ty] Implicit instance attributes declared `Final`
  crates/ty_python_semantic/resources/mdtest/type_qualifiers/final.md
  crates/ty_python_semantic/src/semantic_index/builder.rs
  crates/ty_python_semantic/src/types/class.rs
  crates/ty_python_semantic/src/types/infer.rs
Labels: ty, ecosystem-analyzer

#19472 [ty] Pass down specialization to generic dataclass bases
  crates/ty_python_semantic/resources/mdtest/dataclasses/dataclasses.md
  crates/ty_python_semantic/src/types/class.rs
Labels: bug, ty, ecosystem-analyzer

#19477 [ty] Detect illegal non-enum attribute accesses in Literal annotation
  crates/ty_python_semantic/resources/mdtest/annotations/literal.md
  crates/ty_python_semantic/src/types/enums.rs
  crates/ty_python_semantic/src/types/infer.rs
Labels: ty

#19480 [ty] Disallow `Final` in function parameter/return-type annotations
  crates/ty_python_semantic/resources/mdtest/type_qualifiers/final.md
  crates/ty_python_semantic/src/types/infer.rs
Labels: ty

#19471 [ty] Implement non-stdlib stub mapping for classes and functions
  Cargo.lock
  crates/ty_ide/Cargo.toml
  crates/ty_ide/src/goto_definition.rs
  crates/ty_ide/src/stub_mapping.rs
  crates/ty_python_semantic/src/lib.rs
  crates/ty_python_semantic/src/module_resolver/mod.rs
  crates/ty_python_semantic/src/module_resolver/path.rs
  crates/ty_python_semantic/src/module_resolver/resolver.rs
  crates/ty_python_semantic/src/types/ide_support.rs
Labels: server, ty

#19464 Move fix suggestion to subdiagnostic
  crates/ruff/src/cache.rs
  crates/ruff_db/src/diagnostic/mod.rs
  crates/ruff_db/src/diagnostic/render.rs
  crates/ruff_db/src/diagnostic/render/full.rs
  crates/ruff_db/src/diagnostic/render/json.rs
  crates/ruff_linter/src/message/mod.rs
  crates/ruff_linter/src/message/text.rs
  crates/ruff_linter/src/test.rs
  crates/ruff_server/src/lint.rs
  crates/ruff_wasm/src/lib.rs
  crates/ty_ide/src/goto_declaration.rs
  crates/ty_ide/src/goto_definition.rs
  crates/ty_ide/src/goto_type_definition.rs
  crates/ty_project/src/lib.rs
  crates/ty_project/src/metadata/options.rs
  crates/ty_python_semantic/src/types.rs
  crates/ty_python_semantic/src/types/call/bind.rs
  crates/ty_python_semantic/src/types/context.rs
  crates/ty_python_semantic/src/types/diagnostic.rs
  crates/ty_python_semantic/src/util/diagnostics.rs
Labels: internal, diagnostics

#19486 [ty] Support iterating over enums
  crates/ty_python_semantic/resources/mdtest/enums.md
  crates/ty_python_semantic/src/types/call/bind.rs
  crates/ty_python_semantic/src/types/class.rs
Labels: ty

#18996 [ty] Splat variadic arguments into parameter list
  crates/ty_ide/src/signature_help.rs
  crates/ty_python_semantic/resources/mdtest/call/function.md
  crates/ty_python_semantic/resources/mdtest/call/overloads.md
  crates/ty_python_semantic/resources/mdtest/narrow/type_guards.md
  crates/ty_python_semantic/src/types/call.rs
  crates/ty_python_semantic/src/types/call/arguments.rs
  crates/ty_python_semantic/src/types/call/bind.rs
  crates/ty_python_semantic/src/types/ide_support.rs
  crates/ty_python_semantic/src/types/infer.rs
  crates/ty_python_semantic/src/types/tuple.rs
Labels: ty

#19470 [ty] Use `ThinVec` for sub segments in `PlaceExpr`
  Cargo.lock
  Cargo.toml
  crates/ty_python_semantic/Cargo.toml
  crates/ty_python_semantic/src/semantic_index/place.rs
Labels: internal, ty

#19381 [ty] perform type narrowing for places marked `global` too
  crates/ty_python_semantic/resources/mdtest/scopes/global.md
  crates/ty_python_semantic/src/types/infer.rs
Labels: ty, ecosystem-analyzer

#19501 [ty] Invert `ty_ide` and `ty_project` dependency
  Cargo.lock
  crates/ty_ide/Cargo.toml
  crates/ty_ide/src/db.rs
  crates/ty_ide/src/inlay_hints.rs
  crates/ty_ide/src/lib.rs
  crates/ty_project/Cargo.toml
  crates/ty_project/src/db.rs
  crates/ty_project/src/lib.rs
  crates/ty_server/src/document/location.rs
Labels: internal, ty

#19503 [ty] Reachability analysis for `isinstance(…)` branches
  crates/ty_python_semantic/resources/mdtest/call/builtins.md
  crates/ty_python_semantic/resources/mdtest/exhaustiveness_checking.md
  crates/ty_python_semantic/src/types/function.rs
Labels: ty, ecosystem-analyzer

#19398 Move concise diagnostic rendering to `ruff_db`
  .github/workflows/ty-ecosystem-analyzer.yaml
  .github/workflows/ty-ecosystem-report.yaml
  crates/ruff/src/printer.rs
  crates/ruff_db/src/diagnostic/mod.rs
  crates/ruff_db/src/diagnostic/render.rs
  crates/ruff_db/src/diagnostic/render/concise.rs
  crates/ruff_db/src/diagnostic/stylesheet.rs
  crates/ruff_linter/src/message/text.rs
  crates/ty/tests/cli/file_selection.rs
  crates/ty/tests/cli/main.rs
Labels: internal, diagnostics, ecosystem-analyzer

#19405 [`pylint`] Handle empty comments after line continuation (`PLR2044`)
  crates/ruff_linter/resources/test/fixtures/pylint/empty_comment_line_continuation.py
  crates/ruff_linter/src/checkers/tokens.rs
  crates/ruff_linter/src/rules/pylint/mod.rs
  crates/ruff_linter/src/rules/pylint/rules/empty_comment.rs
  crates/ruff_linter/src/rules/pylint/snapshots/ruff_linter__rules__pylint__tests__PLR2044_empty_comment_line_continuation.py.snap
Labels: bug, fixes

#19432 [`pep8-naming`] Fix `N802` false positives for `CGIHTTPRequestHandler` and `SimpleHTTPRequestHandler`
  crates/ruff_linter/resources/test/fixtures/pep8_naming/N802.py
  crates/ruff_linter/src/rules/pep8_naming/rules/invalid_function_name.rs
  crates/ruff_linter/src/rules/pep8_naming/snapshots/ruff_linter__rules__pep8_naming__tests__N802_N802.py.snap
Labels: rule

#19325 [`perflint`] Parenthesize generator expressions (`PERF401`)
  crates/ruff_linter/resources/test/fixtures/perflint/PERF401.py
  crates/ruff_linter/src/rules/perflint/rules/manual_list_comprehension.rs
  crates/ruff_linter/src/rules/perflint/snapshots/ruff_linter__rules__perflint__tests__PERF401_PERF401.py.snap
  crates/ruff_linter/src/rules/perflint/snapshots/ruff_linter__rules__perflint__tests__preview__PERF401_PERF401.py.snap
Labels: bug, fixes

#19404 [`flake8-use-pathlib`] Add autofix for `PTH101`, `PTH104`, `PTH105`, `PTH121`
  crates/ruff_linter/resources/test/fixtures/flake8_use_pathlib/import_from.py
  crates/ruff_linter/src/checkers/ast/analyze/expression.rs
  crates/ruff_linter/src/codes.rs
  crates/ruff_linter/src/preview.rs
  crates/ruff_linter/src/rules/flake8_use_pathlib/helpers.rs
  crates/ruff_linter/src/rules/flake8_use_pathlib/rules/mod.rs
  crates/ruff_linter/src/rules/flake8_use_pathlib/rules/os_chmod.rs
  crates/ruff_linter/src/rules/flake8_use_pathlib/rules/os_path_samefile.rs
  crates/ruff_linter/src/rules/flake8_use_pathlib/rules/os_rename.rs
  crates/ruff_linter/src/rules/flake8_use_pathlib/rules/os_replace.rs
  crates/ruff_linter/src/rules/flake8_use_pathlib/rules/replaceable_by_pathlib.rs
  crates/ruff_linter/src/rules/flake8_use_pathlib/snapshots/ruff_linter__rules__flake8_use_pathlib__tests__full_name.py.snap
  crates/ruff_linter/src/rules/flake8_use_pathlib/snapshots/ruff_linter__rules__flake8_use_pathlib__tests__import_as.py.snap
  crates/ruff_linter/src/rules/flake8_use_pathlib/snapshots/ruff_linter__rules__flake8_use_pathlib__tests__import_from.py.snap
  crates/ruff_linter/src/rules/flake8_use_pathlib/snapshots/ruff_linter__rules__flake8_use_pathlib__tests__import_from_as.py.snap
  crates/ruff_linter/src/rules/flake8_use_pathlib/snapshots/ruff_linter__rules__flake8_use_pathlib__tests__preview_full_name.py.snap
  crates/ruff_linter/src/rules/flake8_use_pathlib/snapshots/ruff_linter__rules__flake8_use_pathlib__tests__preview_import_as.py.snap
  crates/ruff_linter/src/rules/flake8_use_pathlib/snapshots/ruff_linter__rules__flake8_use_pathlib__tests__preview_import_from.py.snap
  crates/ruff_linter/src/rules/flake8_use_pathlib/snapshots/ruff_linter__rules__flake8_use_pathlib__tests__preview_import_from_as.py.snap
  crates/ruff_linter/src/rules/flake8_use_pathlib/violations.rs
Labels: fixes, preview

#19475 [ty] Implemented partial support for "find references" language server feature.
  crates/ruff_python_ast/src/visitor/source_order.rs
  crates/ty_ide/src/find_node.rs
  crates/ty_ide/src/goto.rs
  crates/ty_ide/src/lib.rs
  crates/ty_ide/src/references.rs
  crates/ty_server/src/server.rs
  crates/ty_server/src/server/api.rs
  crates/ty_server/src/server/api/requests.rs
  crates/ty_server/src/server/api/requests/references.rs
  crates/ty_server/src/snapshots/ty_server__server__tests__initialization.snap
  crates/ty_server/src/snapshots/ty_server__server__tests__initialization_with_workspace.snap
Labels: server, ty

#19512 [ty] Fix narrowing and reachability of class patterns with arguments
  crates/ty_python_semantic/resources/mdtest/conditional/match.md
  crates/ty_python_semantic/src/semantic_index/builder.rs
  crates/ty_python_semantic/src/semantic_index/predicate.rs
  crates/ty_python_semantic/src/semantic_index/reachability_constraints.rs
  crates/ty_python_semantic/src/types/narrow.rs
Labels: bug, ty

#19496 [ty] Return a tuple spec from the iterator protocol
  crates/ty_python_semantic/resources/mdtest/call/function.md
  crates/ty_python_semantic/resources/mdtest/loops/for.md
  crates/ty_python_semantic/src/types.rs
  crates/ty_python_semantic/src/types/call/arguments.rs
  crates/ty_python_semantic/src/types/call/bind.rs
  crates/ty_python_semantic/src/types/class.rs
  crates/ty_python_semantic/src/types/generics.rs
  crates/ty_python_semantic/src/types/infer.rs
  crates/ty_python_semantic/src/types/tuple.rs
  crates/ty_python_semantic/src/types/unpacker.rs
Labels: ty

#19523 [ty] Rename type_api => ty_extensions
  crates/ty_python_semantic/resources/mdtest/call/function.md
  crates/ty_python_semantic/resources/mdtest/snapshots/ty_extensions.md_-_`ty_extensions`_-_Diagnostic_snapshots_(662547cd88c67f9f).snap
  crates/ty_python_semantic/resources/mdtest/ty_extensions.md
  crates/ty_python_semantic/src/types/infer.rs
Labels: internal, testing, ty

#19528 Bump 0.12.5
  CHANGELOG.md
  Cargo.lock
  README.md
  crates/ruff/Cargo.toml
  crates/ruff_linter/Cargo.toml
  crates/ruff_wasm/Cargo.toml
  docs/integrations.md
  docs/tutorial.md
  pyproject.toml
  scripts/benchmarks/pyproject.toml
Labels: release

#19065 [`ruff`] Offer fixes for `RUF039` in more cases
  crates/ruff_linter/resources/test/fixtures/ruff/RUF039.py
  crates/ruff_linter/resources/test/fixtures/ruff/RUF039_concat.py
  crates/ruff_linter/resources/test/fixtures/ruff/RUF039_py_version_sensitive.py
  crates/ruff_linter/src/rules/ruff/mod.rs
  crates/ruff_linter/src/rules/ruff/rules/unraw_re_pattern.rs
  crates/ruff_linter/src/rules/ruff/snapshots/ruff_linter__rules__ruff__tests__preview__RUF039_RUF039.py.snap
  crates/ruff_linter/src/rules/ruff/snapshots/ruff_linter__rules__ruff__tests__preview__RUF039_RUF039_concat.py.snap
  crates/ruff_linter/src/rules/ruff/snapshots/ruff_linter__rules__ruff__tests__preview__py37__RUF039_RUF039_py_version_sensitive.py.snap
  crates/ruff_linter/src/rules/ruff/snapshots/ruff_linter__rules__ruff__tests__preview__py38__RUF039_RUF039_py_version_sensitive.py.snap
Labels: fixes, preview

#19522 [ty] Move server tests as integration tests
  Cargo.lock
  crates/ty_server/Cargo.toml
  crates/ty_server/src/lib.rs
  crates/ty_server/src/logging.rs
  crates/ty_server/src/server.rs
  crates/ty_server/src/session.rs
  crates/ty_server/src/session/options.rs
  crates/ty_server/tests/e2e/initialize.rs
  crates/ty_server/tests/e2e/main.rs
  crates/ty_server/tests/e2e/publish_diagnostics.rs
  crates/ty_server/tests/e2e/pull_diagnostics.rs
  crates/ty_server/tests/e2e/snapshots/e2e__initialize__initialization.snap
  crates/ty_server/tests/e2e/snapshots/e2e__initialize__initialization_with_workspace.snap
  crates/ty_server/tests/e2e/snapshots/e2e__publish_diagnostics__on_did_open.snap
  crates/ty_server/tests/e2e/snapshots/e2e__pull_diagnostics__on_did_open.snap
Labels: server, testing, ty

#19534 [ty] Minor: fix incomplete docstring
  crates/ty_python_semantic/src/types.rs
Labels: internal, ty

#19549 [ty] Derive `Serialize` unconditionally on client options
  Cargo.lock
  crates/ty_server/Cargo.toml
  crates/ty_server/src/session/options.rs
  crates/ty_server/tests/e2e/main.rs
Labels: internal, ty

#19553 [ty] Add basic support for `dataclasses.field`
  crates/ty_python_semantic/resources/mdtest/dataclasses/fields.md
  crates/ty_python_semantic/src/types.rs
  crates/ty_python_semantic/src/types/call/bind.rs
  crates/ty_python_semantic/src/types/class.rs
  crates/ty_python_semantic/src/types/class_base.rs
  crates/ty_python_semantic/src/types/function.rs
  crates/ty_python_semantic/src/types/infer.rs
Labels: ty, ecosystem-analyzer

#19556 [ty] Add workflow to comment diagnostic diff for conformance tests
  .github/workflows/typing_conformance_comment.yaml
Labels: ci, ty, no-test

#19562 Add `TextEmitter::with_color` and disable colors in `unreadable_files` test
  crates/ruff/src/commands/check.rs
  crates/ruff_linter/src/message/text.rs
Labels: testing

#19520 [`flake8-blind-except`] Change `BLE001` to permit `logging.critical(..., exc_info=True)`.
  crates/ruff_linter/resources/test/fixtures/flake8_blind_except/BLE.py
  crates/ruff_linter/src/rules/flake8_blind_except/rules/blind_except.rs
  crates/ruff_linter/src/rules/flake8_blind_except/snapshots/ruff_linter__rules__flake8_blind_except__tests__BLE001_BLE.py.snap
Labels: rule

#19558 [ty] Don't include already-bound legacy typevars in function generic context
  crates/ty_python_semantic/resources/mdtest/generics/legacy/classes.md
  crates/ty_python_semantic/resources/mdtest/generics/pep695/classes.md
  crates/ty_python_semantic/resources/mdtest/generics/scoping.md
  crates/ty_python_semantic/src/types/call/bind.rs
  crates/ty_python_semantic/src/types/function.rs
  crates/ty_python_semantic/src/types/generics.rs
  crates/ty_python_semantic/src/types/signatures.rs
Labels: ty

#19557 [ty] Support stdlib files in playground
  crates/ty_wasm/src/lib.rs
  playground/ty/src/Editor/Chrome.tsx
  playground/ty/src/Editor/Editor.tsx
  playground/ty/src/Editor/Files.tsx
  playground/ty/src/Editor/SecondaryPanel.tsx
  playground/ty/src/Editor/VendoredFileBanner.tsx
  playground/ty/src/Playground.tsx
Labels: playground, ty

#19555 [ty] Add workflow to comment conformance tests diff
  .github/workflows/typing_conformance.yaml
Labels: ci, ty, no-test

#19499 Use PEP 639 license information for Ruff itself instead of classifier
  pyproject.toml
Labels: documentation

#19592 [ty] Fix "peek definition" in playground
  playground/ty/src/Editor/Editor.tsx
Labels: bug, playground

#19598 [ty] Remove `AssertUnwindSafe` from `BackgroundRequestHandler` api
  crates/ty_server/src/server/api.rs
  crates/ty_server/src/server/api/requests/workspace_diagnostic.rs
  crates/ty_server/src/server/api/requests/workspace_symbols.rs
  crates/ty_server/src/server/api/traits.rs
Labels: internal, server, ty

#19597 [ty] Minor: test isolation
  crates/ty_python_semantic/resources/mdtest/function/return_type.md
  crates/ty_python_semantic/resources/mdtest/snapshots/return_type.md_-_Function_return_type_-_Generator_functions_-_Asynchronous_(408134055c24a538).snap
  crates/ty_python_semantic/resources/mdtest/snapshots/return_type.md_-_Function_return_type_-_Generator_functions_-_Synchronous_(6a32ec69d15117b8).snap
Labels: internal, testing, ty

#19468 [`refurb`] Mark `int` and `bool` cases for `Decimal.from_float` as safe fixes in `FURB164` tests
  crates/ruff_linter/resources/test/fixtures/refurb/FURB164.py
  crates/ruff_linter/src/rules/refurb/rules/unnecessary_from_float.rs
  crates/ruff_linter/src/rules/refurb/snapshots/ruff_linter__rules__refurb__tests__FURB164_FURB164.py.snap
Labels: bug, fixes

#19387 [`pylint`] Implement auto-fix for `missing-maxsplit-arg` (`PLC0207`)
  crates/ruff_linter/src/rules/pylint/rules/missing_maxsplit_arg.rs
  crates/ruff_linter/src/rules/pylint/snapshots/ruff_linter__rules__pylint__tests__PLC0207_missing_maxsplit_arg.py.snap
Labels: fixes, preview

#19390 [`flake8-commas`] Add support for trailing comma checks in type parameter lists (`COM812`,`COM819`)
  crates/ruff_linter/resources/test/fixtures/flake8_commas/COM81.py
  crates/ruff_linter/src/checkers/tokens.rs
  crates/ruff_linter/src/preview.rs
  crates/ruff_linter/src/rules/flake8_commas/mod.rs
  crates/ruff_linter/src/rules/flake8_commas/rules/trailing_commas.rs
  crates/ruff_linter/src/rules/flake8_commas/snapshots/ruff_linter__rules__flake8_commas__tests__preview__COM81.py.snap
  crates/ruff_linter/src/rules/flake8_commas/snapshots/ruff_linter__rules__flake8_commas__tests__preview__COM81_syntax_error.py.snap
Labels: rule, preview

#19602 [ty] Don't panic with argument that doesn't actually implement Iterable
  crates/ty_python_semantic/src/types/call/bind.rs
Labels: ty

#19606 [ty] Bump docstring-adder pin
  scripts/codemod_docstrings.sh
Labels: ci, ty

#19608 Add `LinterContext::settings` to avoid passing separate settings
  crates/ruff_linter/src/checkers/ast/mod.rs
  crates/ruff_linter/src/checkers/tokens.rs
  crates/ruff_linter/src/linter.rs
  crates/ruff_linter/src/rules/eradicate/rules/commented_out_code.rs
  crates/ruff_linter/src/rules/flake8_commas/rules/trailing_commas.rs
  crates/ruff_linter/src/rules/flake8_implicit_str_concat/rules/implicit.rs
  crates/ruff_linter/src/rules/pycodestyle/rules/blank_lines.rs
  crates/ruff_linter/src/rules/ruff/rules/ambiguous_unicode_character.rs
Labels: internal

#19535 [ty] Fix empty spans following a line terminator and unprintable character spans in diagnostics
  Cargo.lock
  crates/ruff_db/Cargo.toml
  crates/ruff_db/src/diagnostic/mod.rs
  crates/ruff_db/src/diagnostic/render.rs
  crates/ruff_db/src/diagnostic/render/full.rs
  crates/ruff_linter/src/locator.rs
  crates/ruff_linter/src/message/text.rs
Labels: ty, diagnostics

#19615 [ty] Discard `Definition`s when normalizing `Signature`s
  crates/ty_python_semantic/src/types/signatures.rs
Labels: internal, ty

#19399 [`flake8-pyi`] Preserve inline comment in ellipsis removal (`PYI013`)
  crates/ruff_linter/resources/test/fixtures/flake8_pyi/PYI013.py
  crates/ruff_linter/resources/test/fixtures/flake8_pyi/PYI013.pyi
  crates/ruff_linter/src/rules/flake8_pyi/rules/ellipsis_in_non_empty_class_body.rs
  crates/ruff_linter/src/rules/flake8_pyi/snapshots/ruff_linter__rules__flake8_pyi__tests__PYI013_PYI013.py.snap
  crates/ruff_linter/src/rules/flake8_pyi/snapshots/ruff_linter__rules__flake8_pyi__tests__PYI013_PYI013.pyi.snap
Labels: bug, fixes

#19609 Add `Checker::context` method, deduplicate Unicode checks
  crates/ruff_linter/src/checkers/ast/mod.rs
  crates/ruff_linter/src/rules/ruff/rules/ambiguous_unicode_character.rs
Labels: internal

#19493 [ty] Synthesize precise `__getitem__` overloads for tuple subclasses
  crates/ty_python_semantic/resources/mdtest/subscript/tuple.md
  crates/ty_python_semantic/src/types/class.rs
Labels: ty

#19630 Fix copy and line separator colors in dark mode
  docs/stylesheets/extra.css
Labels: documentation

#19638 [ty] Update module resolution diagram to account for typeshed `VERSIONS` file
  crates/ty_python_semantic/src/module_resolver/import-resolution-diagram.dot
  crates/ty_python_semantic/src/module_resolver/import-resolution-diagram.svg
Labels: internal, ty

#19618 Always expand tabs to four spaces in diagnostics
  Cargo.lock
  crates/ruff_db/Cargo.toml
  crates/ruff_db/src/diagnostic/render.rs
  crates/ruff_db/src/diagnostic/render/full.rs
  crates/ruff_linter/src/message/text.rs
  crates/ruff_linter/src/rules/pycodestyle/snapshots/ruff_linter__rules__pycodestyle__tests__E101_E101.py.snap
  crates/ruff_linter/src/rules/pycodestyle/snapshots/ruff_linter__rules__pycodestyle__tests__E201_E20.py.snap
  crates/ruff_linter/src/rules/pycodestyle/snapshots/ruff_linter__rules__pycodestyle__tests__E202_E20.py.snap
  crates/ruff_linter/src/rules/pycodestyle/snapshots/ruff_linter__rules__pycodestyle__tests__E203_E20.py.snap
  crates/ruff_linter/src/rules/pycodestyle/snapshots/ruff_linter__rules__pycodestyle__tests__E223_E22.py.snap
  crates/ruff_linter/src/rules/pycodestyle/snapshots/ruff_linter__rules__pycodestyle__tests__E242_E24.py.snap
  crates/ruff_linter/src/rules/pycodestyle/snapshots/ruff_linter__rules__pycodestyle__tests__E271_E27.py.snap
  crates/ruff_linter/src/rules/pycodestyle/snapshots/ruff_linter__rules__pycodestyle__tests__E272_E27.py.snap
  crates/ruff_linter/src/rules/pycodestyle/snapshots/ruff_linter__rules__pycodestyle__tests__E273_E27.py.snap
  crates/ruff_linter/src/rules/pycodestyle/snapshots/ruff_linter__rules__pycodestyle__tests__E274_E27.py.snap
  crates/ruff_linter/src/rules/pycodestyle/snapshots/ruff_linter__rules__pycodestyle__tests__W191_W19.py.snap
  crates/ruff_linter/src/rules/ruff/snapshots/ruff_linter__rules__ruff__tests__preview__RUF054_RUF054.py.snap
Labels: diagnostics

#19434 [`ruff`] Parenthesize generator expressions in f-strings (`RUF010`)
  crates/ruff_linter/resources/test/fixtures/ruff/RUF010.py
  crates/ruff_linter/src/rules/ruff/rules/explicit_f_string_type_conversion.rs
  crates/ruff_linter/src/rules/ruff/snapshots/ruff_linter__rules__ruff__tests__RUF010_RUF010.py.snap
Labels: bug, fixes

#19634 [ty] Async for loops and async iterables
  crates/ty_python_semantic/resources/mdtest/comprehensions/basic.md
  crates/ty_python_semantic/resources/mdtest/diagnostics/semantic_syntax_errors.md
  crates/ty_python_semantic/resources/mdtest/loops/async_for.md
  crates/ty_python_semantic/resources/mdtest/snapshots/async_for.md_-_Async_-_Error_cases_-_No_`__aiter__`_metho…_(4fbd80e21774cc23).snap
  crates/ty_python_semantic/resources/mdtest/snapshots/async_for.md_-_Async_-_Error_cases_-_No_`__anext__`_metho…_(a0b186714127abee).snap
  crates/ty_python_semantic/resources/mdtest/snapshots/async_for.md_-_Async_-_Error_cases_-_Possibly_unbound_`__…_(42b1d61a2b7be1b5).snap
  crates/ty_python_semantic/resources/mdtest/snapshots/async_for.md_-_Async_-_Error_cases_-_Possibly_unbound_`__…_(74ad2f945cad6ed8).snap
  crates/ty_python_semantic/resources/mdtest/snapshots/async_for.md_-_Async_-_Error_cases_-_Synchronously_iterab…_(80fa705b1c61d982).snap
  crates/ty_python_semantic/resources/mdtest/snapshots/async_for.md_-_Async_-_Error_cases_-_Wrong_signature_for_…_(b614724363eec343).snap
  crates/ty_python_semantic/resources/mdtest/snapshots/async_for.md_-_Async_-_Error_cases_-_Wrong_signature_for_…_(e1f3e9275d0a367).snap
  crates/ty_python_semantic/resources/mdtest/snapshots/for.md_-_For_loops_-_Possibly_invalid_`__…_(c626bde8651b643a).snap
  crates/ty_python_semantic/resources/mdtest/snapshots/semantic_syntax_erro…_-_Semantic_syntax_erro…_-_`async`_comprehensio…_-_Python_3.10_(96aa8ec77d46553d).snap
  crates/ty_python_semantic/src/semantic_index/builder.rs
  crates/ty_python_semantic/src/types.rs
  crates/ty_python_semantic/src/types/infer.rs
  crates/ty_python_semantic/src/types/unpacker.rs
  crates/ty_python_semantic/src/unpack.rs
Labels: ty, ecosystem-analyzer

#19505 fix missing-required-imports introducing syntax error after dosctring ending with backslash
  crates/ruff_linter/resources/test/fixtures/isort/required_imports/docstring_followed_by_continuation.py
  crates/ruff_linter/src/importer/insertion.rs
  crates/ruff_linter/src/rules/isort/mod.rs
  crates/ruff_linter/src/rules/isort/snapshots/ruff_linter__rules__isort__tests__required_import_docstring_followed_by_continuation.py.snap
  crates/ruff_linter/src/rules/isort/snapshots/ruff_linter__rules__isort__tests__required_import_with_alias_docstring_followed_by_continuation.py.snap
Labels: bug, fixes
