Repository astral-sh/ruff, pull requests merged in 2025-08, with the labels that each got.

#19440 [`flake8-use-pathlib`] Expand `PTH201` to check all `PurePath` subclasses
  crates/ruff_linter/resources/test/fixtures/flake8_use_pathlib/PTH201.py
  crates/ruff_linter/src/rules/flake8_use_pathlib/helpers.rs
  crates/ruff_linter/src/rules/flake8_use_pathlib/mod.rs
  crates/ruff_linter/src/rules/flake8_use_pathlib/rules/path_constructor_current_directory.rs
  crates/ruff_linter/src/rules/flake8_use_pathlib/snapshots/ruff_linter__rules__flake8_use_pathlib__tests__preview__PTH201_PTH201.py.snap
Labels: rule, preview

#19682 [ty] Remove `Specialization::display` (full)
  crates/ty_python_semantic/src/types/display.rs
Labels: internal, ty

#19668 [ty] Improve `isinstance()` truthiness analysis for generic types
  crates/ty_python_semantic/resources/mdtest/call/builtins.md
  crates/ty_python_semantic/resources/mdtest/exhaustiveness_checking.md
  crates/ty_python_semantic/src/types/function.rs
Labels: ty

#19686 [ty] Initial test suite for `TypedDict`
  crates/ty_python_semantic/resources/mdtest/typed_dict.md
Labels: testing, ty

#19693 [ty] Correctly instantiate generic class that inherits `__init__` from generic base class
  crates/ty_python_semantic/resources/mdtest/generics/legacy/classes.md
  crates/ty_python_semantic/resources/mdtest/generics/pep695/classes.md
  crates/ty_python_semantic/src/types/class.rs
  crates/ty_python_semantic/src/types/signatures.rs
Labels: ty

#19710 [ty] Update salsa
  Cargo.lock
  Cargo.toml
  crates/ty/src/lib.rs
  crates/ty_project/src/db.rs
  crates/ty_project/src/files.rs
  fuzz/Cargo.toml
Labels: internal, ty

#19729 [ty] Add progress bar to watch
  crates/ty/src/lib.rs
  crates/ty/src/printer.rs
Labels: cli, ty

#19730 Revert "Update NPM Development dependencies"
  playground/api/package-lock.json
  playground/api/package.json
  playground/package-lock.json
  playground/package.json
Labels: internal

#19731 Don't flag `pyrefly` pragmas as unused code (`ERA001`)
  crates/ruff_linter/resources/test/fixtures/eradicate/ERA001.py
  crates/ruff_linter/src/rules/eradicate/detection.rs
Labels: rule

#19657 [ty] Implement streaming for workspace diagnostics
  crates/ty/src/lib.rs
  crates/ty/tests/cli/rule_selection.rs
  crates/ty_project/src/db.rs
  crates/ty_project/src/lib.rs
  crates/ty_server/src/lib.rs
  crates/ty_server/src/server.rs
  crates/ty_server/src/server/api.rs
  crates/ty_server/src/server/api/requests.rs
  crates/ty_server/src/server/api/requests/workspace_diagnostic.rs
  crates/ty_server/src/server/main_loop.rs
  crates/ty_server/src/session.rs
  crates/ty_server/src/session/capabilities.rs
  crates/ty_server/src/session/client.rs
  crates/ty_server/tests/e2e/main.rs
  crates/ty_server/tests/e2e/pull_diagnostics.rs
  crates/ty_server/tests/e2e/snapshots/e2e__pull_diagnostics__workspace_diagnostic_after_changes.snap
  crates/ty_server/tests/e2e/snapshots/e2e__pull_diagnostics__workspace_diagnostic_streaming_with_caching.snap
Labels: server, ty

#19697 [ty] Always refresh diagnostics after a watched files change
  crates/ty_server/src/server/api/notifications/did_change_watched_files.rs
Labels: bug, server, ty

#19712 [ty] clear the terminal screen in watch mode
  Cargo.lock
  crates/ty/Cargo.toml
  crates/ty/src/lib.rs
  crates/ty/src/printer.rs
Labels: cli, ty

#19689 [ty] Fix workspace diagnostics being recomputed
  crates/ty_server/src/server/api/requests/workspace_diagnostic.rs
  crates/ty_server/tests/e2e/main.rs
  crates/ty_server/tests/e2e/pull_diagnostics.rs
Labels: internal, ty

#19741 [ty] Infer `type[tuple[int, str]]` as the meta-type of `tuple[int, str]`
  crates/ty_python_semantic/resources/mdtest/attributes.md
  crates/ty_python_semantic/resources/mdtest/type_compendium/tuple.md
  crates/ty_python_semantic/src/types.rs
  crates/ty_python_semantic/src/types/class.rs
  crates/ty_python_semantic/src/types/ide_support.rs
  crates/ty_python_semantic/src/types/infer.rs
  crates/ty_python_semantic/src/types/tuple.rs
Labels: ty

#19749 [ty] Remove false positives when subscripting `Generic` or `Protocol` with a `ParamSpec` or `TypeVarTuple`
  crates/ty_python_semantic/resources/mdtest/type_properties/is_assignable_to.md
  crates/ty_python_semantic/src/types/infer.rs
Labels: ty

#19743 [ty] fix lookup order of class variables before they are defined
  crates/ty_python_semantic/resources/mdtest/narrow/conditionals/nested.md
  crates/ty_python_semantic/resources/mdtest/scopes/global.md
  crates/ty_python_semantic/src/types/infer.rs
Labels: ty

#19733 [ty] New `Type` variant for `TypedDict`
  Cargo.lock
  Cargo.toml
  crates/ty_python_semantic/resources/mdtest/ide_support/all_members.md
  crates/ty_python_semantic/resources/mdtest/type_properties/truthiness.md
  crates/ty_python_semantic/resources/mdtest/typed_dict.md
  crates/ty_python_semantic/src/semantic_model.rs
  crates/ty_python_semantic/src/types.rs
  crates/ty_python_semantic/src/types/class.rs
  crates/ty_python_semantic/src/types/class_base.rs
  crates/ty_python_semantic/src/types/display.rs
  crates/ty_python_semantic/src/types/function.rs
  crates/ty_python_semantic/src/types/ide_support.rs
  crates/ty_python_semantic/src/types/infer.rs
  crates/ty_python_semantic/src/types/mro.rs
  crates/ty_python_semantic/src/types/narrow.rs
  crates/ty_python_semantic/src/types/type_ordering.rs
  crates/ty_python_semantic/src/types/visitor.rs
  fuzz/Cargo.toml
Labels: ty, ecosystem-analyzer

#19756 [ty] Keep track of type qualifiers in stub declarations without right-hand side
  crates/ty_python_semantic/resources/mdtest/type_qualifiers/classvar.md
  crates/ty_python_semantic/src/types/infer.rs
Labels: bug, ty

#19760 [ty] Speedup the `known_class_doesnt_fallback_to_unknown_unexpectedly_on_low_python_version` test
  crates/ty_python_semantic/src/types/class.rs
Labels: testing, ty

#19758 [ty] Fix attribute access on `TypedDict`s
  crates/ty_ide/src/completion.rs
  crates/ty_python_semantic/resources/mdtest/ide_support/all_members.md
  crates/ty_python_semantic/resources/mdtest/typed_dict.md
  crates/ty_python_semantic/src/types.rs
  crates/ty_python_semantic/src/types/call/bind.rs
  crates/ty_python_semantic/src/types/ide_support.rs
  crates/ty_python_semantic/src/types/subclass_of.rs
Labels: ty

#19762 [ty] Improve effectiveness of `KnownClass` fast paths in `instance.rs`
  crates/ty_python_semantic/src/types/instance.rs
Labels: internal, ty

#19761 [ty] Fix merge base calculation for typing-conformance workflow
  .github/workflows/typing_conformance.yaml
Labels: ci, ty

#19411 [`flake8_import_conventions`] Avoid false positives for NFKC-normalized `__debug__` import aliases in ICN001
  Cargo.lock
  crates/ruff/tests/lint.rs
  crates/ruff_workspace/Cargo.toml
  crates/ruff_workspace/src/configuration.rs
  crates/ruff_workspace/src/options.rs
Labels: bug, fixes

#19787 [ty] Avoid warning for old settings schema too aggresively
  crates/ty_server/src/server.rs
  crates/ty_server/src/session.rs
  crates/ty_server/tests/e2e/initialize.rs
Labels: internal, server, ty

#19679 [`pylint`] Mark `PLC0207` fixes as unsafe when `*args` unpacking is present
  crates/ruff_linter/resources/test/fixtures/pylint/missing_maxsplit_arg.py
  crates/ruff_linter/src/rules/pylint/rules/missing_maxsplit_arg.rs
  crates/ruff_linter/src/rules/pylint/snapshots/ruff_linter__rules__pylint__tests__PLC0207_missing_maxsplit_arg.py.snap
Labels: bug, fixes

#19773 [ty] Avoid overcounting shared memory usage
  Cargo.lock
  Cargo.toml
  crates/ruff_db/Cargo.toml
  crates/ruff_db/src/parsed.rs
  crates/ruff_db/src/source.rs
  crates/ruff_memory_usage/Cargo.toml
  crates/ruff_memory_usage/src/lib.rs
  crates/ty_project/Cargo.toml
  crates/ty_project/src/db.rs
  crates/ty_project/src/lib.rs
  crates/ty_project/src/metadata/settings.rs
  crates/ty_python_semantic/Cargo.toml
  crates/ty_python_semantic/src/dunder_all.rs
  crates/ty_python_semantic/src/module_resolver/resolver.rs
  crates/ty_python_semantic/src/place.rs
  crates/ty_python_semantic/src/semantic_index.rs
  crates/ty_python_semantic/src/semantic_index/builder.rs
  crates/ty_python_semantic/src/semantic_index/re_exports.rs
  crates/ty_python_semantic/src/suppression.rs
  crates/ty_python_semantic/src/types.rs
  crates/ty_python_semantic/src/types/class.rs
  crates/ty_python_semantic/src/types/enums.rs
  crates/ty_python_semantic/src/types/function.rs
  crates/ty_python_semantic/src/types/infer.rs
  crates/ty_python_semantic/src/types/narrow.rs
  crates/ty_python_semantic/src/types/property_tests/type_generation.rs
  crates/ty_python_semantic/src/types/protocol_class.rs
  crates/ty_python_semantic/src/util/get_size.rs
  crates/ty_python_semantic/src/util/mod.rs
  fuzz/Cargo.toml
Labels: internal, ty

#19784 [ty] `typing.Self` is bound by the method, not the class
  crates/ty_ide/src/completion.rs
  crates/ty_python_semantic/resources/mdtest/annotations/self.md
  crates/ty_python_semantic/resources/mdtest/annotations/unsupported_special_forms.md
  crates/ty_python_semantic/resources/mdtest/generics/legacy/functions.md
  crates/ty_python_semantic/resources/mdtest/generics/pep695/functions.md
  crates/ty_python_semantic/resources/mdtest/named_tuple.md
  crates/ty_python_semantic/src/types.rs
  crates/ty_python_semantic/src/types/generics.rs
  crates/ty_python_semantic/src/types/infer.rs
Labels: ty, ecosystem-analyzer

#19794 [ty] Add support for using the test command emitted when a mdtest fails
  crates/ty_test/src/lib.rs
Labels: testing, ty

#19551 [ty] Implemented support for "rename" language server feature
  crates/ty_ide/src/goto.rs
  crates/ty_ide/src/goto_declaration.rs
  crates/ty_ide/src/goto_definition.rs
  crates/ty_ide/src/goto_references.rs
  crates/ty_ide/src/lib.rs
  crates/ty_ide/src/references.rs
  crates/ty_ide/src/rename.rs
  crates/ty_python_semantic/src/lib.rs
  crates/ty_python_semantic/src/types/ide_support.rs
  crates/ty_server/src/capabilities.rs
  crates/ty_server/src/server/api.rs
  crates/ty_server/src/server/api/requests.rs
  crates/ty_server/src/server/api/requests/prepare_rename.rs
  crates/ty_server/src/server/api/requests/rename.rs
  crates/ty_server/tests/e2e/snapshots/e2e__initialize__initialization.snap
  crates/ty_server/tests/e2e/snapshots/e2e__initialize__initialization_with_workspace.snap
Labels: server, ty

#19800 [ty] Add `ty.experimental.rename` server setting
  crates/ty_server/src/capabilities.rs
  crates/ty_server/src/server.rs
  crates/ty_server/src/session.rs
  crates/ty_server/src/session/options.rs
  crates/ty_server/src/session/settings.rs
  crates/ty_server/tests/e2e/initialize.rs
  crates/ty_server/tests/e2e/main.rs
  crates/ty_server/tests/e2e/snapshots/e2e__initialize__initialization.snap
  crates/ty_server/tests/e2e/snapshots/e2e__initialize__initialization_with_workspace.snap
Labels: configuration, server, ty

#19803 [ty] Add failing tests for tuple subclasses
  crates/ty_python_semantic/resources/mdtest/call/function.md
  crates/ty_python_semantic/resources/mdtest/generics/legacy/classes.md
  crates/ty_python_semantic/resources/mdtest/generics/pep695/classes.md
  crates/ty_python_semantic/resources/mdtest/subscript/tuple.md
  crates/ty_python_semantic/resources/mdtest/type_compendium/tuple.md
  crates/ty_python_semantic/resources/mdtest/type_properties/is_single_valued.md
  crates/ty_python_semantic/resources/mdtest/unpacking.md
Labels: testing, ty

#19780 [ty] Add `ty.inlayHints.variableTypes` server option
  crates/ty_ide/src/inlay_hints.rs
  crates/ty_ide/src/lib.rs
  crates/ty_server/src/server/api/requests/inlay_hints.rs
  crates/ty_server/src/session/options.rs
  crates/ty_server/src/session/settings.rs
  crates/ty_server/tests/e2e/inlay_hints.rs
  crates/ty_server/tests/e2e/main.rs
  crates/ty_wasm/src/lib.rs
Labels: configuration, server, ty

#19795 [ty] more cases for the class body global fallback
  crates/ty_python_semantic/resources/mdtest/narrow/assignment.md
  crates/ty_python_semantic/resources/mdtest/scopes/global.md
  crates/ty_python_semantic/resources/mdtest/scopes/unbound.md
  crates/ty_python_semantic/src/semantic_index/symbol.rs
  crates/ty_python_semantic/src/types/infer.rs
Labels: ty, ecosystem-analyzer

#19824 [ty] Improve performance of subtyping and assignability checks for protocols
  crates/ty_python_semantic/src/types/cyclic.rs
Labels: performance, ty

#19791 [ty] Implement module-level `__getattr__` support
  crates/ty_python_semantic/resources/mdtest/import/module_getattr.md
  crates/ty_python_semantic/src/types.rs
Labels: ty

#19529 [ty] Implement stdlib stub mapping
  crates/ty_project/src/metadata/options.rs
  crates/ty_python_semantic/src/module_resolver/mod.rs
  crates/ty_python_semantic/src/module_resolver/path.rs
  crates/ty_python_semantic/src/module_resolver/resolver.rs
  crates/ty_python_semantic/src/program.rs
  crates/ty_python_semantic/src/site_packages.rs
  crates/ty_test/src/lib.rs
Labels: server, ty

#19833 [ty] Handle cycles when finding implicit attributes
  crates/ty_python_semantic/src/types/class.rs
Labels: ty

#19832 Clean up unused rendering code in `ruff_linter`
  Cargo.lock
  crates/ruff_linter/Cargo.toml
  crates/ruff_linter/src/message/grouped.rs
  crates/ruff_linter/src/message/mod.rs
  crates/ruff_linter/src/message/snapshots/ruff_linter__message__grouped__tests__fix_status.snap
  crates/ruff_linter/src/message/snapshots/ruff_linter__message__grouped__tests__fix_status_unsafe.snap
  crates/ruff_linter/src/message/snapshots/ruff_linter__message__grouped__tests__show_source.snap
  crates/ruff_linter/src/message/text.rs
Labels: internal

#19839 Avoid underflow in default ranges before a BOM
  crates/ruff_db/src/diagnostic/render.rs
  crates/ruff_db/src/diagnostic/render/full.rs
Labels: internal

#19844 [ty] Add `static-frame` as a walltime benchmark
  crates/ruff_benchmark/benches/ty_walltime.rs
Labels: ci, ty

#19867 [ty] Short circuit `ReachabilityConstraints::analyze_single` for dynamic types
  crates/ty_python_semantic/resources/mdtest/function/return_type.md
  crates/ty_python_semantic/src/semantic_index/reachability_constraints.rs
Labels: performance, ty

#19669 [ty] Remove `Type::Tuple`
  crates/ty_python_semantic/resources/mdtest/call/function.md
  crates/ty_python_semantic/resources/mdtest/generics/legacy/classes.md
  crates/ty_python_semantic/resources/mdtest/generics/pep695/classes.md
  crates/ty_python_semantic/resources/mdtest/mdtest_custom_typeshed.md
  crates/ty_python_semantic/resources/mdtest/scopes/moduletype_attrs.md
  crates/ty_python_semantic/resources/mdtest/subscript/tuple.md
  crates/ty_python_semantic/resources/mdtest/type_compendium/tuple.md
  crates/ty_python_semantic/resources/mdtest/type_properties/is_single_valued.md
  crates/ty_python_semantic/resources/mdtest/unpacking.md
  crates/ty_python_semantic/src/semantic_model.rs
  crates/ty_python_semantic/src/types.rs
  crates/ty_python_semantic/src/types/builder.rs
  crates/ty_python_semantic/src/types/call/arguments.rs
  crates/ty_python_semantic/src/types/class.rs
  crates/ty_python_semantic/src/types/class_base.rs
  crates/ty_python_semantic/src/types/display.rs
  crates/ty_python_semantic/src/types/enums.rs
  crates/ty_python_semantic/src/types/function.rs
  crates/ty_python_semantic/src/types/generics.rs
  crates/ty_python_semantic/src/types/ide_support.rs
  crates/ty_python_semantic/src/types/infer.rs
  crates/ty_python_semantic/src/types/instance.rs
  crates/ty_python_semantic/src/types/narrow.rs
  crates/ty_python_semantic/src/types/property_tests/type_generation.rs
  crates/ty_python_semantic/src/types/tuple.rs
  crates/ty_python_semantic/src/types/type_ordering.rs
  crates/ty_python_semantic/src/types/visitor.rs
Labels: ty, ecosystem-analyzer

#19873 [ty] simplify CycleDetector::visit signature
  crates/ty_python_semantic/src/types.rs
  crates/ty_python_semantic/src/types/cyclic.rs
  crates/ty_python_semantic/src/types/protocol_class.rs
Labels: internal, ty

#19843 Update salsa to pull in tracked struct changes
  Cargo.lock
  Cargo.toml
  fuzz/Cargo.toml
Labels: internal, ty

#19790 [ty] Track heap usage of salsa structs
  Cargo.lock
  crates/ruff_db/src/file_revision.rs
  crates/ruff_db/src/files.rs
  crates/ruff_db/src/files/file_root.rs
  crates/ruff_db/src/files/path.rs
  crates/ruff_db/src/system/path.rs
  crates/ruff_memory_usage/Cargo.toml
  crates/ruff_memory_usage/src/lib.rs
  crates/ty_project/src/db.rs
  crates/ty_project/src/files.rs
  crates/ty_project/src/glob.rs
  crates/ty_project/src/glob/exclude.rs
  crates/ty_project/src/glob/include.rs
  crates/ty_project/src/lib.rs
  crates/ty_project/src/metadata.rs
  crates/ty_project/src/metadata/options.rs
  crates/ty_project/src/metadata/settings.rs
  crates/ty_project/src/metadata/value.rs
  crates/ty_project/src/walk.rs
  crates/ty_python_semantic/src/module_resolver/module.rs
  crates/ty_python_semantic/src/module_resolver/resolver.rs
  crates/ty_python_semantic/src/module_resolver/typeshed.rs
  crates/ty_python_semantic/src/program.rs
  crates/ty_python_semantic/src/python_platform.rs
  crates/ty_python_semantic/src/semantic_index/definition.rs
  crates/ty_python_semantic/src/semantic_index/expression.rs
  crates/ty_python_semantic/src/semantic_index/predicate.rs
  crates/ty_python_semantic/src/semantic_index/scope.rs
  crates/ty_python_semantic/src/types.rs
  crates/ty_python_semantic/src/types/class.rs
  crates/ty_python_semantic/src/types/function.rs
  crates/ty_python_semantic/src/types/generics.rs
  crates/ty_python_semantic/src/types/protocol_class.rs
  crates/ty_python_semantic/src/types/tuple.rs
  crates/ty_python_semantic/src/unpack.rs
Labels: internal, ty

#19872 [ty] Reduce memory usage of `TupleSpec` and `TupleType`
  crates/ty_python_semantic/src/types/infer.rs
  crates/ty_python_semantic/src/types/tuple.rs
Labels: ty

#19876 Fix `lint.future-annotations` link
  crates/ruff_linter/src/rules/pyupgrade/rules/quoted_annotation.rs
Labels: documentation

#19880 [ty] Remove unsafe `salsa::Update` implementations in `tuple.rs`
  crates/ty_python_semantic/src/types/tuple.rs
Labels: internal, ty

#19805 [ty] support recursive type aliases
  crates/ty_python_semantic/resources/mdtest/pep695_type_aliases.md
  crates/ty_python_semantic/src/semantic_model.rs
  crates/ty_python_semantic/src/types.rs
  crates/ty_python_semantic/src/types/builder.rs
  crates/ty_python_semantic/src/types/class.rs
  crates/ty_python_semantic/src/types/class_base.rs
  crates/ty_python_semantic/src/types/cyclic.rs
  crates/ty_python_semantic/src/types/display.rs
  crates/ty_python_semantic/src/types/function.rs
  crates/ty_python_semantic/src/types/generics.rs
  crates/ty_python_semantic/src/types/ide_support.rs
  crates/ty_python_semantic/src/types/infer.rs
  crates/ty_python_semantic/src/types/instance.rs
  crates/ty_python_semantic/src/types/narrow.rs
  crates/ty_python_semantic/src/types/protocol_class.rs
  crates/ty_python_semantic/src/types/subclass_of.rs
  crates/ty_python_semantic/src/types/tuple.rs
  crates/ty_python_semantic/src/types/type_ordering.rs
  crates/ty_python_semantic/src/types/visitor.rs
Labels: bug, ty

#19869 Don't cache files with diagnostics
  crates/ruff/src/cache.rs
  crates/ruff/src/diagnostics.rs
  crates/ruff_benchmark/benches/linter.rs
  crates/ruff_linter/src/linter.rs
  crates/ruff_macros/src/map_codes.rs
  fuzz/fuzz_targets/ruff_formatter_validity.rs
Labels: internal

#19894 [ty] Improve `sys.version_info` special casing
  crates/ty_python_semantic/resources/mdtest/subscript/tuple.md
  crates/ty_python_semantic/src/types/class.rs
  crates/ty_python_semantic/src/types/instance.rs
  crates/ty_python_semantic/src/types/tuple.rs
Labels: internal, ty

#19884 [ty] simplify return type of place_from_declarations
  crates/ty_python_semantic/resources/mdtest/annotations/invalid.md
  crates/ty_python_semantic/resources/mdtest/diagnostics/semantic_syntax_errors.md
  crates/ty_python_semantic/resources/mdtest/scopes/unbound.md
  crates/ty_python_semantic/src/place.rs
  crates/ty_python_semantic/src/types/class.rs
  crates/ty_python_semantic/src/types/enums.rs
  crates/ty_python_semantic/src/types/ide_support.rs
  crates/ty_python_semantic/src/types/infer.rs
  crates/ty_python_semantic/src/types/protocol_class.rs
  python/py-fuzzer/fuzz.py
Labels: ty

#19896 Add rule code to GitLab description
  crates/ruff/tests/snapshots/lint__output_format_gitlab.snap
  crates/ruff_linter/src/message/gitlab.rs
  crates/ruff_linter/src/message/snapshots/ruff_linter__message__gitlab__tests__output.snap
  crates/ruff_linter/src/message/snapshots/ruff_linter__message__gitlab__tests__syntax_errors.snap
Labels: diagnostics

#19898 [ty] resolve docstrings for modules
  crates/ty_ide/src/goto.rs
  crates/ty_ide/src/hover.rs
  crates/ty_python_semantic/src/semantic_index/definition.rs
  crates/ty_python_semantic/src/types/ide_support.rs
Labels: server, ty

#19888 [ty] fix deferred name loading in PEP695 generic classes/functions
  crates/ty_ide/src/hover.rs
  crates/ty_ide/src/inlay_hints.rs
  crates/ty_python_semantic/resources/corpus/cyclic_pep695_typevars.py
  crates/ty_python_semantic/resources/corpus/except_handler_with_Any_bound_typevar.py
  crates/ty_python_semantic/resources/mdtest/generics/legacy/variables.md
  crates/ty_python_semantic/resources/mdtest/generics/pep695/classes.md
  crates/ty_python_semantic/resources/mdtest/generics/pep695/variables.md
  crates/ty_python_semantic/resources/mdtest/protocols.md
  crates/ty_python_semantic/resources/mdtest/scopes/eager.md
  crates/ty_python_semantic/resources/mdtest/snapshots/union_call.md_-_Calling_a_union_of_f…_-_Try_to_cover_all_pos…_-_Cover_non-keyword_re…_(707b284610419a54).snap
  crates/ty_python_semantic/src/semantic_index.rs
  crates/ty_python_semantic/src/semantic_index/builder.rs
  crates/ty_python_semantic/src/semantic_index/definition.rs
  crates/ty_python_semantic/src/semantic_index/scope.rs
  crates/ty_python_semantic/src/types.rs
  crates/ty_python_semantic/src/types/call/bind.rs
  crates/ty_python_semantic/src/types/class.rs
  crates/ty_python_semantic/src/types/display.rs
  crates/ty_python_semantic/src/types/generics.rs
  crates/ty_python_semantic/src/types/infer.rs
  crates/ty_python_semantic/src/types/signatures.rs
  crates/ty_python_semantic/src/types/subclass_of.rs
Labels: ty

#19677 [ty] support `kw_only=True` for `dataclass()` and `field()`
  crates/ty_python_semantic/resources/mdtest/dataclasses/dataclass_transform.md
  crates/ty_python_semantic/resources/mdtest/dataclasses/dataclasses.md
  crates/ty_python_semantic/resources/mdtest/dataclasses/fields.md
  crates/ty_python_semantic/src/types.rs
  crates/ty_python_semantic/src/types/call/bind.rs
  crates/ty_python_semantic/src/types/class.rs
Labels: ty

#19900 [`pyflakes`] Add secondary annotation showing previous definition (`F811`)
  crates/ruff/tests/lint.rs
  crates/ruff_db/src/diagnostic/mod.rs
  crates/ruff_db/src/diagnostic/render.rs
  crates/ruff_linter/src/checkers/ast/mod.rs
  crates/ruff_linter/src/rules/pyflakes/rules/redefined_while_unused.rs
  crates/ruff_linter/src/rules/pyflakes/snapshots/ruff_linter__rules__pyflakes__tests__F811_F811_0.py.snap
  crates/ruff_linter/src/rules/pyflakes/snapshots/ruff_linter__rules__pyflakes__tests__F811_F811_1.py.snap
  crates/ruff_linter/src/rules/pyflakes/snapshots/ruff_linter__rules__pyflakes__tests__F811_F811_12.py.snap
  crates/ruff_linter/src/rules/pyflakes/snapshots/ruff_linter__rules__pyflakes__tests__F811_F811_15.py.snap
  crates/ruff_linter/src/rules/pyflakes/snapshots/ruff_linter__rules__pyflakes__tests__F811_F811_16.py.snap
  crates/ruff_linter/src/rules/pyflakes/snapshots/ruff_linter__rules__pyflakes__tests__F811_F811_17.py.snap
  crates/ruff_linter/src/rules/pyflakes/snapshots/ruff_linter__rules__pyflakes__tests__F811_F811_2.py.snap
  crates/ruff_linter/src/rules/pyflakes/snapshots/ruff_linter__rules__pyflakes__tests__F811_F811_21.py.snap
  crates/ruff_linter/src/rules/pyflakes/snapshots/ruff_linter__rules__pyflakes__tests__F811_F811_23.py.snap
  crates/ruff_linter/src/rules/pyflakes/snapshots/ruff_linter__rules__pyflakes__tests__F811_F811_26.py.snap
  crates/ruff_linter/src/rules/pyflakes/snapshots/ruff_linter__rules__pyflakes__tests__F811_F811_28.py.snap
  crates/ruff_linter/src/rules/pyflakes/snapshots/ruff_linter__rules__pyflakes__tests__F811_F811_29.pyi.snap
  crates/ruff_linter/src/rules/pyflakes/snapshots/ruff_linter__rules__pyflakes__tests__F811_F811_3.py.snap
  crates/ruff_linter/src/rules/pyflakes/snapshots/ruff_linter__rules__pyflakes__tests__F811_F811_30.py.snap
  crates/ruff_linter/src/rules/pyflakes/snapshots/ruff_linter__rules__pyflakes__tests__F811_F811_31.py.snap
  crates/ruff_linter/src/rules/pyflakes/snapshots/ruff_linter__rules__pyflakes__tests__F811_F811_32.py.snap
  crates/ruff_linter/src/rules/pyflakes/snapshots/ruff_linter__rules__pyflakes__tests__F811_F811_4.py.snap
  crates/ruff_linter/src/rules/pyflakes/snapshots/ruff_linter__rules__pyflakes__tests__F811_F811_5.py.snap
  crates/ruff_linter/src/rules/pyflakes/snapshots/ruff_linter__rules__pyflakes__tests__F811_F811_6.py.snap
  crates/ruff_linter/src/rules/pyflakes/snapshots/ruff_linter__rules__pyflakes__tests__F811_F811_8.py.snap
  crates/ruff_linter/src/rules/pyflakes/snapshots/ruff_linter__rules__pyflakes__tests__del_shadowed_global_import_in_local_scope.snap
  crates/ruff_linter/src/rules/pyflakes/snapshots/ruff_linter__rules__pyflakes__tests__del_shadowed_import_shadow_in_local_scope.snap
  crates/ruff_linter/src/rules/pyflakes/snapshots/ruff_linter__rules__pyflakes__tests__del_shadowed_local_import_in_local_scope.snap
  crates/ruff_linter/src/test.rs
Labels: diagnostics

#19913 [ty] Speedup project file discovery
  crates/ruff_db/src/files.rs
  crates/ty_project/src/db.rs
  crates/ty_project/src/walk.rs
Labels: performance, ty

#19902 [ty] Remove use of `ClassBase::try_from_type` from `super()` machinery
  crates/ty_python_semantic/resources/mdtest/class/super.md
  crates/ty_python_semantic/src/types.rs
Labels: ty

#19899 [ty] Synthesize read-only properties for all declared members on `NamedTuple` classes
  crates/ty_python_semantic/resources/mdtest/named_tuple.md
  crates/ty_python_semantic/src/types/class.rs
Labels: ty

#19711 [ty] Add diagnostics for invalid `await` expressions
  crates/ty/docs/rules.md
  crates/ty_python_semantic/resources/mdtest/diagnostics/invalid_await.md
  crates/ty_python_semantic/resources/mdtest/snapshots/invalid_await.md_-_Invalid_await_diagno…_-_Basic_(f15db7dc447d0795).snap
  crates/ty_python_semantic/resources/mdtest/snapshots/invalid_await.md_-_Invalid_await_diagno…_-_Custom_type_with_mis…_(9ce1ee3cd1c9c8d1).snap
  crates/ty_python_semantic/resources/mdtest/snapshots/invalid_await.md_-_Invalid_await_diagno…_-_Custom_type_with_pos…_(e3444b7a7f960d04).snap
  crates/ty_python_semantic/resources/mdtest/snapshots/invalid_await.md_-_Invalid_await_diagno…_-_Invalid_union_return…_(fedf62ffaca0f2d7).snap
  crates/ty_python_semantic/resources/mdtest/snapshots/invalid_await.md_-_Invalid_await_diagno…_-_Non-callable_`__awai…_(d78580fb6720e4ea).snap
  crates/ty_python_semantic/resources/mdtest/snapshots/invalid_await.md_-_Invalid_await_diagno…_-_`__await__`_definiti…_(15b05c126b6ae968).snap
  crates/ty_python_semantic/resources/mdtest/snapshots/invalid_await.md_-_Invalid_await_diagno…_-_`__await__`_definiti…_(ccb69f512135dd61).snap
  crates/ty_python_semantic/src/types.rs
  crates/ty_python_semantic/src/types/diagnostic.rs
  crates/ty_python_semantic/src/types/function.rs
  crates/ty_python_semantic/src/types/infer.rs
  ty.schema.json
Labels: ty

#19908 [ty] fix lazy snapshot sweeping in nested scopes
  crates/ty_python_semantic/resources/mdtest/narrow/conditionals/nested.md
  crates/ty_python_semantic/src/semantic_index.rs
  crates/ty_python_semantic/src/semantic_index/builder.rs
Labels: ty

#19926 [ty] Remove incorrect type narrowing for `if type(x) is C[int]`
  crates/ty_python_semantic/resources/mdtest/narrow/type.md
  crates/ty_python_semantic/src/types/narrow.rs
Labels: bug, ty

#19700 [`pycodestyle`] Make `E731` fix unsafe instead of display-only for class assignments
  crates/ruff_linter/src/rules/pycodestyle/rules/lambda_assignment.rs
  crates/ruff_linter/src/rules/pycodestyle/snapshots/ruff_linter__rules__pycodestyle__tests__E731_E731.py.snap
Labels: fixes

#19818 [`isort`] Handle multiple continuation lines after module docstring (`I002`)
  crates/ruff_linter/resources/test/fixtures/isort/required_imports/docstring_with_multiple_continuations.py
  crates/ruff_linter/src/importer/insertion.rs
  crates/ruff_linter/src/rules/isort/mod.rs
  crates/ruff_linter/src/rules/isort/snapshots/ruff_linter__rules__isort__tests__required_import_docstring_with_multiple_continuations.py.snap
  crates/ruff_linter/src/rules/isort/snapshots/ruff_linter__rules__isort__tests__required_import_with_alias_docstring_with_multiple_continuations.py.snap
Labels: bug, fixes

#19940 [ty] Fix error message for invalidly providing type arguments to `NamedTuple` when it occurs in a type expression
  crates/ty_python_semantic/resources/mdtest/named_tuple.md
  crates/ty_python_semantic/src/types/infer.rs
Labels: internal, ty

#19949 [ty] Remove unused code
  crates/ty_ide/src/lib.rs
  crates/ty_python_semantic/src/types.rs
  crates/ty_python_semantic/src/types/call/arguments.rs
  crates/ty_python_semantic/src/types/generics.rs
Labels: internal, ty

#19945 [ty] Detect `NamedTuple` classes where fields without default values follow fields with default values
  crates/ty/docs/rules.md
  crates/ty_python_semantic/resources/mdtest/named_tuple.md
  crates/ty_python_semantic/resources/mdtest/snapshots/named_tuple.md_-_`NamedTuple`_-_`typing.NamedTuple`_-_Definition_(bbf79630502e65e9).snap
  crates/ty_python_semantic/src/types/class.rs
  crates/ty_python_semantic/src/types/diagnostic.rs
  crates/ty_python_semantic/src/types/infer.rs
Labels: ty

#19950 [ty] Fix protocol interface inference for stub protocols and subprotocols
  crates/ty_python_semantic/resources/mdtest/protocols.md
  crates/ty_python_semantic/src/types/protocol_class.rs
Labels: bug, ty

#19975 [ty] Ask the LSP client to watch all project search paths
  crates/ty_server/src/capabilities.rs
  crates/ty_server/src/server/main_loop.rs
  crates/ty_server/src/session.rs
Labels: server, ty

#19979 [ty] introduce multiline pretty printer
  crates/ty_ide/src/hover.rs
  crates/ty_python_semantic/src/lib.rs
  crates/ty_python_semantic/src/types.rs
  crates/ty_python_semantic/src/types/display.rs
Labels: server, ty

#19994 [ty] Fix namespace packages that behave like partial stubs
  crates/ty_python_semantic/resources/mdtest/import/partial_stub_packages.md
  crates/ty_python_semantic/src/module_resolver/resolver.rs
Labels: bug, ty

#19770 [`pyupgrade`] Handle nested `Optional`s (`UP045`)
  crates/ruff/tests/lint.rs
  crates/ruff_linter/resources/test/fixtures/pyupgrade/UP045.py
  crates/ruff_linter/src/rules/pyupgrade/rules/use_pep604_annotation.rs
  crates/ruff_linter/src/rules/pyupgrade/snapshots/ruff_linter__rules__pyupgrade__tests__UP045.py.snap
Labels: bug, fixes

#19991 [ty] Fix server hang
  Cargo.lock
  Cargo.toml
  fuzz/Cargo.toml
Labels: bug, server, ty

#20007 `Option::unwrap` is now const
  crates/ruff_linter/src/rules/refurb/rules/hardcoded_string_charset.rs
  crates/ruff_source_file/src/line_index.rs
Labels: internal

#20002 [ty] correctly ignore field specifiers when not specified
  crates/ty_python_semantic/resources/mdtest/dataclasses/fields.md
  crates/ty_python_semantic/src/types.rs
  crates/ty_python_semantic/src/types/call/bind.rs
  crates/ty_python_semantic/src/types/class.rs
  crates/ty_python_semantic/src/types/function.rs
Labels: bug, ty

#19514 [`flake8-use-pathlib`] Add fixes for `PTH102` and `PTH103`
  crates/ruff_linter/resources/test/fixtures/flake8_use_pathlib/full_name.py
  crates/ruff_linter/src/checkers/ast/analyze/expression.rs
  crates/ruff_linter/src/codes.rs
  crates/ruff_linter/src/preview.rs
  crates/ruff_linter/src/rules/flake8_use_pathlib/helpers.rs
  crates/ruff_linter/src/rules/flake8_use_pathlib/rules/mod.rs
  crates/ruff_linter/src/rules/flake8_use_pathlib/rules/os_makedirs.rs
  crates/ruff_linter/src/rules/flake8_use_pathlib/rules/os_mkdir.rs
  crates/ruff_linter/src/rules/flake8_use_pathlib/rules/replaceable_by_pathlib.rs
  crates/ruff_linter/src/rules/flake8_use_pathlib/snapshots/ruff_linter__rules__flake8_use_pathlib__tests__full_name.py.snap
  crates/ruff_linter/src/rules/flake8_use_pathlib/snapshots/ruff_linter__rules__flake8_use_pathlib__tests__import_as.py.snap
  crates/ruff_linter/src/rules/flake8_use_pathlib/snapshots/ruff_linter__rules__flake8_use_pathlib__tests__import_from.py.snap
  crates/ruff_linter/src/rules/flake8_use_pathlib/snapshots/ruff_linter__rules__flake8_use_pathlib__tests__import_from_as.py.snap
  crates/ruff_linter/src/rules/flake8_use_pathlib/snapshots/ruff_linter__rules__flake8_use_pathlib__tests__preview_full_name.py.snap
  crates/ruff_linter/src/rules/flake8_use_pathlib/snapshots/ruff_linter__rules__flake8_use_pathlib__tests__preview_import_as.py.snap
  crates/ruff_linter/src/rules/flake8_use_pathlib/snapshots/ruff_linter__rules__flake8_use_pathlib__tests__preview_import_from.py.snap
  crates/ruff_linter/src/rules/flake8_use_pathlib/snapshots/ruff_linter__rules__flake8_use_pathlib__tests__preview_import_from_as.py.snap
  crates/ruff_linter/src/rules/flake8_use_pathlib/violations.rs
Labels: fixes, preview

#19769 [`pyupgrade`] Avoid reporting `__future__` features as unnecessary when they are used (`UP010`)
  crates/ruff_linter/resources/test/fixtures/pyupgrade/UP010_0.py
  crates/ruff_linter/resources/test/fixtures/pyupgrade/UP010_1.py
  crates/ruff_linter/src/checkers/ast/analyze/deferred_scopes.rs
  crates/ruff_linter/src/checkers/ast/analyze/statement.rs
  crates/ruff_linter/src/rules/pyupgrade/mod.rs
  crates/ruff_linter/src/rules/pyupgrade/rules/unnecessary_future_import.rs
  crates/ruff_linter/src/rules/pyupgrade/snapshots/ruff_linter__rules__pyupgrade__tests__UP010_0.py.snap
  crates/ruff_linter/src/rules/pyupgrade/snapshots/ruff_linter__rules__pyupgrade__tests__UP010_1.py.snap
Labels: bug, rule

#20015 [ty] Add link for namespaces being partial
  crates/ty_python_semantic/resources/mdtest/import/partial_stub_packages.md
Labels: documentation, ty

#20012 Fix rust feature activation
  crates/ruff_diagnostics/Cargo.toml
  crates/ruff_source_file/Cargo.toml
  crates/ruff_workspace/Cargo.toml
  crates/ty_project/Cargo.toml
Labels: testing

#19838 [ty] Perform assignability etc checks using new `Constraints` trait
  crates/ty_python_semantic/resources/mdtest/generics/pep695/variables.md
  crates/ty_python_semantic/src/types.rs
  crates/ty_python_semantic/src/types/class.rs
  crates/ty_python_semantic/src/types/class_base.rs
  crates/ty_python_semantic/src/types/constraints.rs
  crates/ty_python_semantic/src/types/cyclic.rs
  crates/ty_python_semantic/src/types/function.rs
  crates/ty_python_semantic/src/types/generics.rs
  crates/ty_python_semantic/src/types/instance.rs
  crates/ty_python_semantic/src/types/protocol_class.rs
  crates/ty_python_semantic/src/types/signatures.rs
  crates/ty_python_semantic/src/types/subclass_of.rs
  crates/ty_python_semantic/src/types/tuple.rs
Labels: ty

#20006 Move diff rendering to `ruff_db`
  Cargo.lock
  crates/ruff_db/Cargo.toml
  crates/ruff_db/src/diagnostic/mod.rs
  crates/ruff_db/src/diagnostic/render/full.rs
  crates/ruff_db/src/diagnostic/stylesheet.rs
  crates/ruff_linter/src/message/diff.rs
  crates/ruff_linter/src/message/grouped.rs
  crates/ruff_linter/src/message/mod.rs
  crates/ruff_linter/src/message/text.rs
  crates/ruff_source_file/src/line_index.rs
  crates/ty_server/src/server/api/requests/completion.rs
Labels: internal

#20013 [ty] fix GotoTargets for keyword args in nested function calls
  crates/ty_ide/src/find_node.rs
  crates/ty_ide/src/goto_definition.rs
  crates/ty_ide/src/selection_range.rs
Labels: server, ty

#20021 [ty] Fix incorrect docstring in call signature completion
  crates/ty_python_semantic/src/types/signatures.rs
Labels: bug, server, ty

#20022 [ty] Improve diagnostics for bad calls to functions
  crates/ty_python_semantic/resources/mdtest/diagnostics/missing_argument.md
  crates/ty_python_semantic/resources/mdtest/diagnostics/too_many_positionals.md
  crates/ty_python_semantic/resources/mdtest/diagnostics/unknown_argument.md
  crates/ty_python_semantic/resources/mdtest/snapshots/deprecated.md_-_Tests_for_the_`@depr…_-_Syntax_(142fa2948c3c6cf1).snap
  crates/ty_python_semantic/resources/mdtest/snapshots/invalid_argument_typ…_-_Invalid_argument_typ…_-_Calls_to_methods_(4b3b8695d519a02).snap
  crates/ty_python_semantic/resources/mdtest/snapshots/invalid_argument_typ…_-_Invalid_argument_typ…_-_Tests_for_a_variety_…_-_Synthetic_arguments_(4c09844bbbf47741).snap
  crates/ty_python_semantic/resources/mdtest/snapshots/missing_argument.md_-_Missing_argument_dia…_(f0811e84fcea1085).snap
  crates/ty_python_semantic/resources/mdtest/snapshots/too_many_positionals…_-_too-many-positional-…_(eafa522239b42502).snap
  crates/ty_python_semantic/resources/mdtest/snapshots/unknown_argument.md_-_Unknown_argument_dia…_(f419c2a8e2ce2412).snap
  crates/ty_python_semantic/src/types/call/bind.rs
Labels: ty, diagnostics

#20017 [ty] Close signature help after `)`
  crates/ty_ide/src/signature_help.rs
Labels: bug, server, ty

#20044 Fix incorrect lsp inlay hint type
  crates/ty_ide/src/lib.rs
  crates/ty_server/src/server/api/requests/inlay_hints.rs
  crates/ty_server/tests/e2e/inlay_hints.rs
  crates/ty_wasm/src/lib.rs
  playground/ty/src/Editor/Editor.tsx
Labels: server, ty

#20047 [ty] Add type as detail to completion items
  crates/ty_server/src/server/api/requests/completion.rs
  crates/ty_wasm/src/lib.rs
  playground/ty/src/Editor/Editor.tsx
Labels: server, ty

#20053 [ty] Remove duplicate global lint registry
  Cargo.lock
  crates/ruff_dev/Cargo.toml
  crates/ruff_dev/src/generate_ty_rules.rs
  crates/ty_project/src/db.rs
  crates/ty_project/src/lib.rs
  crates/ty_project/src/metadata/options.rs
Labels: internal, ty

#20079 [ty] Completely ignore typeshed's stub for `Any`
  crates/ty_python_semantic/resources/mdtest/annotations/any.md
  crates/ty_python_semantic/resources/mdtest/type_properties/is_assignable_to.md
  crates/ty_python_semantic/src/types.rs
  crates/ty_python_semantic/src/types/class.rs
  crates/ty_python_semantic/src/types/class_base.rs
  crates/ty_python_semantic/src/types/display.rs
  crates/ty_python_semantic/src/types/function.rs
  crates/ty_python_semantic/src/types/infer.rs
  crates/ty_python_semantic/src/types/instance.rs
  crates/ty_python_semantic/src/types/narrow.rs
  crates/ty_python_semantic/src/types/special_form.rs
  crates/ty_python_semantic/src/types/subclass_of.rs
Labels: ty

#20052 [ty] Refactor inlay hints structure to use separate parts
  crates/ty_ide/src/inlay_hints.rs
  crates/ty_ide/src/lib.rs
  crates/ty_server/src/server/api/requests/inlay_hints.rs
  crates/ty_server/tests/e2e/inlay_hints.rs
  crates/ty_wasm/src/lib.rs
Labels: internal, server, ty

#20103 [`flake8-use-pathlib`] Update links to the table showing the correspondence between `os` and `pathlib`
  crates/ruff_linter/src/rules/flake8_use_pathlib/rules/os_chmod.rs
  crates/ruff_linter/src/rules/flake8_use_pathlib/rules/os_getcwd.rs
  crates/ruff_linter/src/rules/flake8_use_pathlib/rules/os_makedirs.rs
  crates/ruff_linter/src/rules/flake8_use_pathlib/rules/os_mkdir.rs
  crates/ruff_linter/src/rules/flake8_use_pathlib/rules/os_path_basename.rs
  crates/ruff_linter/src/rules/flake8_use_pathlib/rules/os_path_dirname.rs
  crates/ruff_linter/src/rules/flake8_use_pathlib/rules/os_path_exists.rs
  crates/ruff_linter/src/rules/flake8_use_pathlib/rules/os_path_expanduser.rs
  crates/ruff_linter/src/rules/flake8_use_pathlib/rules/os_path_getatime.rs
  crates/ruff_linter/src/rules/flake8_use_pathlib/rules/os_path_getctime.rs
  crates/ruff_linter/src/rules/flake8_use_pathlib/rules/os_path_getmtime.rs
  crates/ruff_linter/src/rules/flake8_use_pathlib/rules/os_path_getsize.rs
  crates/ruff_linter/src/rules/flake8_use_pathlib/rules/os_path_isabs.rs
  crates/ruff_linter/src/rules/flake8_use_pathlib/rules/os_path_isdir.rs
  crates/ruff_linter/src/rules/flake8_use_pathlib/rules/os_path_isfile.rs
  crates/ruff_linter/src/rules/flake8_use_pathlib/rules/os_path_islink.rs
  crates/ruff_linter/src/rules/flake8_use_pathlib/rules/os_path_samefile.rs
  crates/ruff_linter/src/rules/flake8_use_pathlib/rules/os_readlink.rs
  crates/ruff_linter/src/rules/flake8_use_pathlib/rules/os_remove.rs
  crates/ruff_linter/src/rules/flake8_use_pathlib/rules/os_rename.rs
  crates/ruff_linter/src/rules/flake8_use_pathlib/rules/os_replace.rs
  crates/ruff_linter/src/rules/flake8_use_pathlib/rules/os_rmdir.rs
  crates/ruff_linter/src/rules/flake8_use_pathlib/rules/os_symlink.rs
  crates/ruff_linter/src/rules/flake8_use_pathlib/rules/os_unlink.rs
  crates/ruff_linter/src/rules/flake8_use_pathlib/violations.rs
Labels: documentation

#20055 [ty] don't eagerly unpack aliases in user-authored unions
  crates/ty_python_semantic/resources/mdtest/pep695_type_aliases.md
  crates/ty_python_semantic/src/types.rs
  crates/ty_python_semantic/src/types/builder.rs
  crates/ty_python_semantic/src/types/infer.rs
Labels: ty

#20114 [ty] Preserve qualifiers when accessing attributes on unions/intersections
  crates/ty_python_semantic/resources/mdtest/annotations/callable.md
  crates/ty_python_semantic/src/types.rs
Labels: ty

#20115 [`pyflakes`] Fix `allowed-unused-imports` matching for top-level modules (`F401`)
  crates/ruff_linter/resources/test/fixtures/pyflakes/F401_35.py
  crates/ruff_linter/src/rules/pyflakes/mod.rs
  crates/ruff_linter/src/rules/pyflakes/rules/unused_import.rs
  crates/ruff_linter/src/rules/pyflakes/snapshots/ruff_linter__rules__pyflakes__tests__f401_allowed_unused_imports_top_level_module.snap
Labels: bug

#20124 [ty] add cycle detection for find_legacy_typevars
  crates/ty_python_semantic/resources/mdtest/pep695_type_aliases.md
  crates/ty_python_semantic/src/types.rs
  crates/ty_python_semantic/src/types/class.rs
  crates/ty_python_semantic/src/types/cyclic.rs
  crates/ty_python_semantic/src/types/function.rs
  crates/ty_python_semantic/src/types/generics.rs
  crates/ty_python_semantic/src/types/instance.rs
  crates/ty_python_semantic/src/types/protocol_class.rs
  crates/ty_python_semantic/src/types/signatures.rs
  crates/ty_python_semantic/src/types/subclass_of.rs
  crates/ty_python_semantic/src/types/tuple.rs
Labels: ty

#20125 [ty] add support for cyclic legacy generic protocols
  crates/ty_python_semantic/resources/mdtest/protocols.md
  crates/ty_python_semantic/src/types.rs
Labels: ty

#20122 [`flake8-async`] Implement `blocking-input` rule (`ASYNC250`)
  crates/ruff_linter/resources/test/fixtures/flake8_async/ASYNC250.py
  crates/ruff_linter/src/checkers/ast/analyze/expression.rs
  crates/ruff_linter/src/codes.rs
  crates/ruff_linter/src/rules/flake8_async/mod.rs
  crates/ruff_linter/src/rules/flake8_async/rules/blocking_input.rs
  crates/ruff_linter/src/rules/flake8_async/rules/mod.rs
  crates/ruff_linter/src/rules/flake8_async/snapshots/ruff_linter__rules__flake8_async__tests__ASYNC250_ASYNC250.py.snap
  ruff.schema.json
Labels: rule, preview

#20108 [`pycodestyle`] Preserve return type annotation for `ParamSpec` (`E731`)
  crates/ruff_linter/resources/test/fixtures/pycodestyle/E731.py
  crates/ruff_linter/src/rules/pycodestyle/rules/lambda_assignment.rs
  crates/ruff_linter/src/rules/pycodestyle/snapshots/ruff_linter__rules__pycodestyle__tests__E731_E731.py.snap
Labels: fixes

#20109 [`ruff`] Fix false negative for empty f-strings in `deque` calls (`RUF037`)
  crates/ruff_linter/resources/test/fixtures/ruff/RUF037.py
  crates/ruff_linter/src/rules/ruff/rules/unnecessary_literal_within_deque_call.rs
  crates/ruff_linter/src/rules/ruff/snapshots/ruff_linter__rules__ruff__tests__RUF037_RUF037.py.snap
  crates/ruff_python_ast/src/helpers.rs
Labels: rule, preview

#19934 [`perflint`] Handle tuples in dictionary comprehensions (`PERF403`)
  crates/ruff_linter/resources/test/fixtures/perflint/PERF403.py
  crates/ruff_linter/src/rules/perflint/rules/manual_dict_comprehension.rs
  crates/ruff_linter/src/rules/perflint/snapshots/ruff_linter__rules__perflint__tests__PERF403_PERF403.py.snap
  crates/ruff_linter/src/rules/perflint/snapshots/ruff_linter__rules__perflint__tests__preview__PERF403_PERF403.py.snap
Labels: bug, fixes

#19997 [ty] Add constraint set implementation
  crates/ty_python_semantic/src/types.rs
  crates/ty_python_semantic/src/types/call/bind.rs
  crates/ty_python_semantic/src/types/class.rs
  crates/ty_python_semantic/src/types/constraints.rs
  crates/ty_python_semantic/src/types/display.rs
  crates/ty_python_semantic/src/types/instance.rs
  crates/ty_python_semantic/src/types/signatures.rs
Labels: ty

#20130 [ty] Unpack variadic argument type in specialization
  crates/ty_python_semantic/resources/mdtest/call/overloads.md
  crates/ty_python_semantic/src/types.rs
  crates/ty_python_semantic/src/types/call/bind.rs
  crates/ty_python_semantic/src/types/ide_support.rs
  crates/ty_python_semantic/src/types/infer.rs
Labels: ty

#20141 [ty] Improve disambiguation of types via fully qualified names
  crates/ty_python_semantic/resources/mdtest/function/return_type.md
  crates/ty_python_semantic/resources/mdtest/snapshots/return_type.md_-_Function_return_type_-_Invalid_return_type_(a91e0c67519cd77f).snap
  crates/ty_python_semantic/src/types/diagnostic.rs
  crates/ty_python_semantic/src/types/display.rs
Labels: ty, diagnostics

#20150 [ty] Better error message for attempting to assign to a read-only property
  crates/ty/docs/rules.md
  crates/ty_python_semantic/resources/mdtest/descriptor_protocol.md
  crates/ty_python_semantic/resources/mdtest/named_tuple.md
  crates/ty_python_semantic/resources/mdtest/snapshots/descriptor_protocol.…_-_Descriptor_protocol_-_Special_descriptors_-_Properties_with_no_s…_(176795bc1727dda7).snap
  crates/ty_python_semantic/src/types/call.rs
  crates/ty_python_semantic/src/types/call/bind.rs
  crates/ty_python_semantic/src/types/diagnostic.rs
  crates/ty_python_semantic/src/types/infer.rs
Labels: ty, diagnostics

#19919 Show fixes by default
  crates/ruff/src/printer.rs
  crates/ruff/tests/lint.rs
  crates/ruff_db/src/diagnostic/mod.rs
  crates/ruff_db/src/diagnostic/render.rs
  crates/ruff_db/src/diagnostic/render/concise.rs
  crates/ruff_db/src/diagnostic/render/full.rs
  crates/ruff_linter/src/message/text.rs
  crates/ruff_linter/src/rules/eradicate/snapshots/ruff_linter__rules__eradicate__tests__ERA001_ERA001.py.snap
  crates/ruff_linter/src/rules/flake8_pyi/snapshots/ruff_linter__rules__flake8_pyi__tests__PYI034_PYI034.py.snap
  crates/ruff_linter/src/rules/flake8_pyi/snapshots/ruff_linter__rules__flake8_pyi__tests__PYI034_PYI034.pyi.snap
  crates/ruff_linter/src/rules/flake8_pytest_style/snapshots/ruff_linter__rules__flake8_pytest_style__tests__PT028.snap
  crates/ruff_linter/src/rules/flake8_pytest_style/snapshots/ruff_linter__rules__flake8_pytest_style__tests__is_pytest_test.snap
  crates/ruff_linter/src/rules/pycodestyle/snapshots/ruff_linter__rules__pycodestyle__tests__E731_E731.py.snap
  crates/ruff_linter/src/rules/pyupgrade/snapshots/ruff_linter__rules__pyupgrade__tests__UP049_1.py.snap
  crates/ruff_linter/src/rules/refurb/snapshots/ruff_linter__rules__refurb__tests__FURB116_FURB116.py.snap
  crates/ruff_linter/src/rules/refurb/snapshots/ruff_linter__rules__refurb__tests__fstring_number_format_python_311.snap
  crates/ruff_linter/src/rules/ruff/snapshots/ruff_linter__rules__ruff__tests__ruf100_5.snap
  crates/ruff_linter/src/test.rs
Labels: cli, preview

#20147 [ty] ensure union normalization really normalizes
  crates/ty_python_semantic/resources/mdtest/pep695_type_aliases.md
  crates/ty_python_semantic/src/types.rs
  crates/ty_python_semantic/src/types/builder.rs
Labels: ty

#20156 [ty] Use `invalid-assignment` error code for invalid assignments to `ClassVar`s
  crates/ty_python_semantic/resources/mdtest/attributes.md
  crates/ty_python_semantic/resources/mdtest/diagnostics/attribute_assignment.md
  crates/ty_python_semantic/resources/mdtest/protocols.md
  crates/ty_python_semantic/resources/mdtest/snapshots/attribute_assignment…_-_Attribute_assignment_-_`ClassVar`s_(8d7cca27987b099d).snap
  crates/ty_python_semantic/resources/mdtest/type_qualifiers/classvar.md
  crates/ty_python_semantic/src/types/infer.rs
Labels: ty, diagnostics

#20158 Revert "[ty] Use `invalid-assignment` error code for invalid assignments to `ClassVar`s"
  crates/ty_python_semantic/resources/mdtest/attributes.md
  crates/ty_python_semantic/resources/mdtest/diagnostics/attribute_assignment.md
  crates/ty_python_semantic/resources/mdtest/protocols.md
  crates/ty_python_semantic/resources/mdtest/snapshots/attribute_assignment…_-_Attribute_assignment_-_`ClassVar`s_(8d7cca27987b099d).snap
  crates/ty_python_semantic/resources/mdtest/type_qualifiers/classvar.md
  crates/ty_python_semantic/src/types/infer.rs
Labels: ty

#20161 [ty] skip a slow seed in fuzzer
  crates/ty_python_semantic/src/types.rs
  python/py-fuzzer/fuzz.py
Labels: internal, ty

#20160 [ty] don't assume that deferred type inference means deferred name resolution
  crates/ty_python_semantic/resources/mdtest/classes.md
  crates/ty_python_semantic/src/types/infer.rs
Labels: ty

#20159 [ty] improve cycle-detection coverage for apply_type_mapping
  crates/ty_python_semantic/resources/mdtest/pep695_type_aliases.md
  crates/ty_python_semantic/src/types.rs
  crates/ty_python_semantic/src/types/function.rs
  crates/ty_python_semantic/src/types/protocol_class.rs
  crates/ty_python_semantic/src/types/signatures.rs
Labels: ty
