Repository astral-sh/ruff, pull requests merged in 2025-09, with the labels that each got.

#20190 [ty] Support `__init_subclass__`
  crates/ty_ide/src/completion.rs
  crates/ty_python_semantic/resources/mdtest/call/methods.md
  crates/ty_python_semantic/src/types.rs
  crates/ty_python_semantic/src/types/call/bind.rs
  crates/ty_python_semantic/src/types/class.rs
  crates/ty_python_semantic/src/types/function.rs
Labels: ty

#20192 [ty] `__class_getitem__` is a classmethod
  crates/ty_python_semantic/resources/mdtest/subscript/class.md
  crates/ty_python_semantic/src/types/function.rs
  crates/ty_python_semantic/src/types/infer.rs
Labels: ty

#20148 [ty] add more lsp tests for overloads
  crates/ty_ide/src/goto_declaration.rs
  crates/ty_ide/src/goto_definition.rs
  crates/ty_ide/src/hover.rs
  crates/ty_ide/src/signature_help.rs
Labels: internal, server, ty

#20014 [ty] Make initializer calls GotoTargets
  crates/ty_ide/src/goto.rs
  crates/ty_ide/src/goto_declaration.rs
  crates/ty_ide/src/goto_definition.rs
  crates/ty_ide/src/hover.rs
Labels: server, ty

#20209 [ty] Update ecosystem-analyzer
  .github/workflows/ty-ecosystem-analyzer.yaml
Labels: ci, ty, ecosystem-analyzer

#20210 [ty] Run ecosystem-analyzer in release mode
  .github/workflows/ty-ecosystem-analyzer.yaml
Labels: ci, ty, ecosystem-analyzer

#20051 [syntax-errors] Detect `yield from` inside async function
  crates/ruff_linter/resources/test/fixtures/syntax_errors/yield_from_in_async_function.py
  crates/ruff_linter/src/checkers/ast/analyze/expression.rs
  crates/ruff_linter/src/checkers/ast/mod.rs
  crates/ruff_linter/src/linter.rs
  crates/ruff_linter/src/rules/pylint/rules/yield_from_in_async_function.rs
  crates/ruff_linter/src/snapshots/ruff_linter__linter__tests__yield_from_in_async_function.py.snap
  crates/ruff_python_parser/resources/inline/err/yield_from_in_async_function.py
  crates/ruff_python_parser/src/semantic_errors.rs
  crates/ruff_python_parser/tests/fixtures.rs
  crates/ruff_python_parser/tests/snapshots/invalid_syntax@yield_from_in_async_function.py.snap
  crates/ty_python_semantic/resources/mdtest/annotations/invalid.md
Labels: ty

#20172 [`airflow`] Move `airflow.operators.postgres_operator.Mapping` from `AIR302` to `AIR301`
  crates/ruff_linter/resources/test/fixtures/airflow/AIR301_names.py
  crates/ruff_linter/src/rules/airflow/helpers.rs
  crates/ruff_linter/src/rules/airflow/rules/moved_to_provider_in_3.rs
  crates/ruff_linter/src/rules/airflow/rules/removal_in_3.rs
  crates/ruff_linter/src/rules/airflow/rules/suggested_to_move_to_provider_in_3.rs
  crates/ruff_linter/src/rules/airflow/snapshots/ruff_linter__rules__airflow__tests__AIR301_AIR301_names.py.snap
  crates/ruff_linter/src/rules/airflow/snapshots/ruff_linter__rules__airflow__tests__AIR302_AIR302_postgres.py.snap
Labels: rule, preview

#20216 Expose `Indentation` in `ruff_python_codegen`
  crates/ruff_python_codegen/src/lib.rs
Labels: internal

#20205 [ty] More tests for TypedDict
  crates/ty_python_semantic/resources/mdtest/typed_dict.md
Labels: testing, ty

#20221 [ty] Attribute access on top/bottom materializations
  crates/ty_python_semantic/resources/mdtest/type_properties/materialization.md
  crates/ty_python_semantic/src/place.rs
  crates/ty_python_semantic/src/types.rs
  crates/ty_python_semantic/src/types/builder.rs
  crates/ty_python_semantic/src/types/class.rs
  crates/ty_python_semantic/src/types/class_base.rs
  crates/ty_python_semantic/src/types/generics.rs
  crates/ty_python_semantic/src/types/instance.rs
  crates/ty_python_semantic/src/types/protocol_class.rs
  crates/ty_python_semantic/src/types/signatures.rs
  crates/ty_python_semantic/src/types/subclass_of.rs
  crates/ty_python_semantic/src/types/tuple.rs
  crates/ty_python_semantic/src/types/typed_dict.rs
Labels: ty

#20230 Stabilize `useless-class-metaclass-type` (`UP050`)
  crates/ruff_linter/src/codes.rs
Labels: rule

#20256 [ty] Narrow specialized generics using isinstance()
  crates/ty_python_semantic/resources/mdtest/exhaustiveness_checking.md
  crates/ty_python_semantic/resources/mdtest/narrow/isinstance.md
  crates/ty_python_semantic/src/types/class.rs
  crates/ty_python_semantic/src/types/narrow.rs
Labels: ty, ecosystem-analyzer

#20239 [ty] Reduce false positives for `ParamSpec`s and `TypeVarTuple`s
  crates/ty_python_semantic/resources/mdtest/annotations/unsupported_special_forms.md
  crates/ty_python_semantic/src/types/infer.rs
Labels: ty

#20260 [ty] Minor: 'can not' => cannot
  crates/ty_python_semantic/resources/mdtest/snapshots/typed_dict.md_-_`TypedDict`_-_Diagnostics_(e5289abf5c570c29).snap
  crates/ty_python_semantic/resources/mdtest/typed_dict.md
  crates/ty_python_semantic/src/types/typed_dict.rs
Labels: internal, ty

#20261 [ty] Cover full range of annotated assignments
  crates/ty_python_semantic/resources/mdtest/snapshots/named_tuple.md_-_`NamedTuple`_-_`typing.NamedTuple`_-_Definition_(bbf79630502e65e9).snap
  crates/ty_python_semantic/src/semantic_index/definition.rs
Labels: internal, ty, diagnostics

#20262 [ty] Add backreferences to TypedDict items in diagnostics
  crates/ty/docs/rules.md
  crates/ty_python_semantic/resources/mdtest/snapshots/typed_dict.md_-_`TypedDict`_-_Diagnostics_(e5289abf5c570c29).snap
  crates/ty_python_semantic/src/place.rs
  crates/ty_python_semantic/src/types/class.rs
  crates/ty_python_semantic/src/types/diagnostic.rs
  crates/ty_python_semantic/src/types/infer.rs
  crates/ty_python_semantic/src/types/typed_dict.rs
Labels: internal, ty, diagnostics

#20263 [ty] Include `python` folder in `environment.root` if it exists
  crates/ty/docs/configuration.md
  crates/ty/tests/cli/python_environment.rs
  crates/ty_project/src/metadata/options.rs
  ty.schema.json
Labels: ty

#19210 Remove deprecated macOS config file discovery
  crates/ruff_workspace/src/pyproject.rs
Labels: breaking, configuration

#19223 [`pandas-vet`] Remove `pandas-df-variable-name` (`PD901`)
  crates/ruff_linter/src/codes.rs
  crates/ruff_linter/src/rules/pandas_vet/rules/assignment_to_df.rs
  ruff.schema.json
Labels: breaking, do-not-merge

#20247 Stabilize `f-string-number-format` (`FURB116`)
  crates/ruff_linter/src/codes.rs
Labels: rule

#20253 Stabilize `pytest-raises-ambiguous-pattern` (`RUF043`)
  crates/ruff_linter/src/codes.rs
  crates/ruff_linter/src/rules/ruff/mod.rs
  crates/ruff_linter/src/rules/ruff/rules/pytest_raises_ambiguous_pattern.rs
  crates/ruff_linter/src/rules/ruff/snapshots/ruff_linter__rules__ruff__tests__RUF043_RUF043.py.snap
Labels: rule

#20259 [ty] propagate visitors and constraints through has_relation_in_invariant_position
  crates/ty_python_semantic/resources/mdtest/pep695_type_aliases.md
  crates/ty_python_semantic/src/types.rs
  crates/ty_python_semantic/src/types/generics.rs
Labels: ty

#20278 [ty] initial support for `slots=True` in dataclasses
  crates/ty_python_semantic/resources/mdtest/dataclasses/dataclasses.md
  crates/ty_python_semantic/resources/mdtest/instance_layout_conflict.md
  crates/ty_python_semantic/resources/mdtest/type_properties/is_disjoint_from.md
  crates/ty_python_semantic/src/types/class.rs
Labels: ty

#20290 CI: Eliminate warning in fuzz build workflow
  .github/workflows/ci.yaml
Labels: ci

#20286 [ty] Fall back to `object` for attribute access on synthesized protocols
  crates/ty_python_semantic/resources/mdtest/annotations/callable.md
  crates/ty_python_semantic/resources/mdtest/narrow/hasattr.md
  crates/ty_python_semantic/src/types.rs
  crates/ty_python_semantic/src/types/protocol_class.rs
Labels: ty

#20250 Stabilize the remaining Airflow rules
  crates/ruff_linter/src/codes.rs
  crates/ruff_linter/src/rules/airflow/rules/moved_to_provider_in_3.rs
  crates/ruff_linter/src/rules/airflow/rules/removal_in_3.rs
  crates/ruff_linter/src/rules/airflow/rules/suggested_to_update_3_0.rs
Labels: rule

#20301 [`pep8-naming`] Fix formatting of `__all__` (`N816`)
  crates/ruff_linter/src/rules/pep8_naming/rules/mixed_case_variable_in_global_scope.rs
Labels: documentation

#20304 [ty] Support "legacy" `typing.Self` in combination with PEP 695 generic contexts
  crates/ty_python_semantic/resources/mdtest/generics/pep695/functions.md
  crates/ty_python_semantic/src/types/generics.rs
  crates/ty_python_semantic/src/types/signatures.rs
Labels: ty

#19665 Add support for using uv as an alternative formatter backend
  .github/workflows/ci.yaml
  crates/ruff_formatter/src/lib.rs
  crates/ruff_formatter/src/printer/printer_options/mod.rs
  crates/ruff_python_formatter/src/options.rs
  crates/ruff_server/Cargo.toml
  crates/ruff_server/src/format.rs
  crates/ruff_server/src/server/api/requests/format.rs
  crates/ruff_server/src/server/api/requests/format_range.rs
  crates/ruff_server/src/session/index/ruff_settings.rs
  crates/ruff_server/src/session/options.rs
  crates/ruff_server/src/session/settings.rs
  docs/editors/settings.md
Labels: configuration, server

#20316 [ty] Add tests for protocols with generic method members
  crates/ty_python_semantic/resources/mdtest/protocols.md
Labels: testing, ty

#20309 Refactor diagnostic start|end location helpers
  crates/ruff_db/src/diagnostic/mod.rs
  crates/ruff_linter/src/message/github.rs
  crates/ruff_linter/src/message/grouped.rs
  crates/ruff_linter/src/message/sarif.rs
Labels: internal, diagnostics

#19424 [`pyupgrade`] Apply `UP008` only when the `__class__` cell exists
  crates/ruff_linter/resources/test/fixtures/pyupgrade/UP008.py
  crates/ruff_linter/src/rules/pyupgrade/rules/super_call_with_parameters.rs
  crates/ruff_linter/src/rules/pyupgrade/snapshots/ruff_linter__rules__pyupgrade__tests__UP008.py.snap
  crates/ruff_linter/src/rules/pyupgrade/snapshots/ruff_linter__rules__pyupgrade__tests__UP008.py__preview.snap
Labels: bug, fixes

#20306 [ty] Use partial-order-friendly representation of typevar constraints
  crates/ty_python_semantic/src/types/constraints.rs
Labels: internal, ty

#20321 Bump LibCST to 1.8.4
  Cargo.lock
  Cargo.toml
  crates/ruff_linter/src/rules/pyupgrade/rules/format_literals.rs
Labels: dependencies

#20317 [ty] `"foo".startswith` is not an instance of `types.MethodWrapperType`
  crates/ty_python_semantic/resources/mdtest/attributes.md
  crates/ty_python_semantic/resources/mdtest/call/str_startswith.md
  crates/ty_python_semantic/resources/mdtest/descriptor_protocol.md
  crates/ty_python_semantic/resources/mdtest/properties.md
  crates/ty_python_semantic/src/semantic_model.rs
  crates/ty_python_semantic/src/types.rs
  crates/ty_python_semantic/src/types/call/bind.rs
  crates/ty_python_semantic/src/types/class.rs
  crates/ty_python_semantic/src/types/class_base.rs
  crates/ty_python_semantic/src/types/display.rs
  crates/ty_python_semantic/src/types/function.rs
  crates/ty_python_semantic/src/types/ide_support.rs
  crates/ty_python_semantic/src/types/infer.rs
  crates/ty_python_semantic/src/types/narrow.rs
  crates/ty_python_semantic/src/types/type_ordering.rs
  crates/ty_python_semantic/src/types/visitor.rs
Labels: ty

#20324 [ty] Simplify unions of enum literals and subtypes thereof
  crates/ty_python_semantic/resources/mdtest/union_types.md
  crates/ty_python_semantic/src/types/builder.rs
Labels: ty

#20325 [ty] Use 'unknown' specialization for upper bound on Self
  crates/ty_python_semantic/resources/mdtest/annotations/self.md
  crates/ty_python_semantic/src/types.rs
Labels: bug, ty

#20336 Bump 0.13.0
  BREAKING_CHANGES.md
  CHANGELOG.md
  Cargo.lock
  README.md
  changelogs/0.12.x.md
  crates/ruff/Cargo.toml
  crates/ruff_linter/Cargo.toml
  crates/ruff_wasm/Cargo.toml
  docs/integrations.md
  docs/tutorial.md
  pyproject.toml
  scripts/benchmarks/pyproject.toml
Labels: release

#20329 [ty] Add more tests for special-cased builtin functions and methods
  crates/ty_python_semantic/resources/mdtest/call/methods.md
  crates/ty_python_semantic/src/types.rs
Labels: testing, ty

#20331 [ty] Ensure various special-cased builtin functions are understood as assignable to `Callable`
  crates/ty_python_semantic/resources/mdtest/call/methods.md
  crates/ty_python_semantic/src/types.rs
Labels: ty

#20413 [ty] Allow annotation expressions to be `ast::Attribute` nodes
  crates/ty_python_semantic/resources/mdtest/type_qualifiers/classvar.md
  crates/ty_python_semantic/src/types/infer/builder/annotation_expression.rs
Labels: ty

#20423 [ty] More constraint set simplifications via simpler constraint representation
  crates/ty_python_semantic/resources/mdtest/type_properties/constraints.md
  crates/ty_python_semantic/src/types.rs
  crates/ty_python_semantic/src/types/constraints.rs
  crates/ty_python_semantic/src/types/function.rs
  crates/ty_vendored/ty_extensions/ty_extensions.pyi
Labels: internal, ty

#20258 [ruff] Treat panics as fatal diagnostics, sort panics last
  crates/ruff/src/commands/check.rs
  crates/ruff/src/lib.rs
  crates/ruff/tests/lint.rs
  crates/ruff_db/src/diagnostic/mod.rs
  crates/ruff_linter/src/checkers/ast/mod.rs
  crates/ruff_linter/src/codes.rs
  crates/ruff_linter/src/linter.rs
  crates/ruff_linter/src/rules/ruff/rules/test_rules.rs
Labels: cli, diagnostics

#20166 [syntax-errors]: import from * only allowed at module scope (F406)
  crates/ruff_linter/src/checkers/ast/analyze/statement.rs
  crates/ruff_linter/src/checkers/ast/analyze/unresolved_references.rs
  crates/ruff_linter/src/checkers/ast/mod.rs
  crates/ruff_python_parser/resources/inline/err/import_from_star.py
  crates/ruff_python_parser/resources/inline/ok/import_from_star.py
  crates/ruff_python_parser/src/semantic_errors.rs
  crates/ruff_python_parser/tests/snapshots/invalid_syntax@import_from_star.py.snap
  crates/ruff_python_parser/tests/snapshots/valid_syntax@import_from_star.py.snap
  crates/ty_python_semantic/resources/mdtest/import/star.md
Labels: internal

#20359 [ty] no more diverging query cycles in type expressions
  crates/ty_python_semantic/resources/mdtest/implicit_type_aliases.md
  crates/ty_python_semantic/src/types.rs
  crates/ty_python_semantic/src/types/function.rs
  crates/ty_python_semantic/src/types/infer.rs
  crates/ty_python_semantic/src/types/infer/builder.rs
  crates/ty_python_semantic/src/types/infer/builder/type_expression.rs
  crates/ty_python_semantic/src/types/instance.rs
  crates/ty_python_semantic/src/types/protocol_class.rs
  crates/ty_python_semantic/src/types/visitor.rs
Labels: ty

#20311 [ty] infer `name` and `value` for enum members
  crates/ty_python_semantic/resources/mdtest/attributes.md
  crates/ty_python_semantic/resources/mdtest/enums.md
  crates/ty_python_semantic/src/lib.rs
  crates/ty_python_semantic/src/types.rs
  crates/ty_python_semantic/src/types/builder.rs
  crates/ty_python_semantic/src/types/call/bind.rs
  crates/ty_python_semantic/src/types/enums.rs
Labels: ty, ecosystem-analyzer

#20447 [ty] move graphql-core to good.txt
  crates/ty_python_semantic/resources/primer/bad.txt
  crates/ty_python_semantic/resources/primer/good.txt
Labels: internal, ty, ecosystem-analyzer

#20420 Simplify `Program` configuration for GitHub output
  crates/ruff/src/printer.rs
  crates/ruff_db/src/diagnostic/mod.rs
  crates/ruff_db/src/diagnostic/render.rs
  crates/ruff_db/src/diagnostic/render/github.rs
  crates/ruff_linter/src/message/text.rs
Labels: internal

#20452 [`flake8-use-pathlib`] A bit clean up `PTH100`
  crates/ruff_linter/src/rules/flake8_use_pathlib/rules/os_path_abspath.rs
Labels: internal

#20360 [ty] Infer more precise types for collection literals
  crates/ty_python_semantic/resources/mdtest/assignment/annotations.md
  crates/ty_python_semantic/resources/mdtest/del.md
  crates/ty_python_semantic/resources/mdtest/import/dunder_all.md
  crates/ty_python_semantic/resources/mdtest/literal/collections/list.md
  crates/ty_python_semantic/resources/mdtest/literal/collections/set.md
  crates/ty_python_semantic/resources/mdtest/narrow/conditionals/nested.md
  crates/ty_python_semantic/resources/mdtest/subscript/lists.md
  crates/ty_python_semantic/resources/mdtest/type_compendium/tuple.md
  crates/ty_python_semantic/resources/mdtest/unpacking.md
  crates/ty_python_semantic/src/types.rs
  crates/ty_python_semantic/src/types/class.rs
  crates/ty_python_semantic/src/types/diagnostic.rs
  crates/ty_python_semantic/src/types/function.rs
  crates/ty_python_semantic/src/types/infer.rs
  crates/ty_python_semantic/src/types/infer/builder.rs
  crates/ty_python_semantic/src/types/tuple.rs
Labels: ty, ecosystem-analyzer

#20465 [ty] Faster iteration on mdtests
  crates/ty_python_semantic/mdtest.py
Labels: internal, ty

#20434 Generator preferred quote style
  crates/ruff_python_codegen/src/generator.rs
Labels: internal

#20427 [`pyupgrade`] Fix false positive when class name is shadowed by local variable (`UP008`)
  crates/ruff_linter/resources/test/fixtures/pyupgrade/UP008.py
  crates/ruff_linter/src/rules/pyupgrade/rules/super_call_with_parameters.rs
Labels: bug, rule

#20279 [`refurb`] Mark `single-item-membership-test` fix as always unsafe (`FURB171`)
  crates/ruff_linter/resources/test/fixtures/refurb/FURB171_0.py
  crates/ruff_linter/resources/test/fixtures/refurb/FURB171_1.py
  crates/ruff_linter/src/rules/refurb/rules/single_item_membership_test.rs
  crates/ruff_linter/src/rules/refurb/snapshots/ruff_linter__rules__refurb__tests__FURB171_FURB171_0.py.snap
  crates/ruff_linter/src/rules/refurb/snapshots/ruff_linter__rules__refurb__tests__FURB171_FURB171_1.py.snap
Labels: fixes, preview

#20056 [`flake8-simplify`] Fix incorrect fix for positive `maxsplit` without separator (`SIM905`)
  crates/ruff_linter/resources/test/fixtures/flake8_simplify/SIM905.py
  crates/ruff_linter/src/rules/flake8_simplify/rules/split_static_string.rs
  crates/ruff_linter/src/rules/flake8_simplify/snapshots/ruff_linter__rules__flake8_simplify__tests__SIM905_SIM905.py.snap
  crates/ruff_linter/src/rules/flake8_simplify/snapshots/ruff_linter__rules__flake8_simplify__tests__preview__SIM905_SIM905.py.snap
Labels: bug, fixes

#20457 Exclude snapshots from vscode search results
  .vscode/settings.json
Labels: internal

#20437 Shard instrumented benchmark
  .github/workflows/ci.yaml
Labels: testing

#20467 [ty] Add some tricky test cases for the auto-import importer
  crates/ty_ide/src/importer.rs
Labels: server, testing, ty

#20484 [ty] Make auto-import work in the playground
  crates/ty_wasm/src/lib.rs
  playground/ty/src/Editor/Editor.tsx
Labels: playground, server, ty

#19942 [`ruff`] Add `logging-eager-conversion` (`RUF065`)
  crates/ruff_linter/resources/test/fixtures/ruff/RUF065.py
  crates/ruff_linter/src/checkers/ast/analyze/expression.rs
  crates/ruff_linter/src/codes.rs
  crates/ruff_linter/src/rules/flake8_logging_format/rules/logging_call.rs
  crates/ruff_linter/src/rules/ruff/mod.rs
  crates/ruff_linter/src/rules/ruff/rules/logging_eager_conversion.rs
  crates/ruff_linter/src/rules/ruff/rules/mod.rs
  crates/ruff_linter/src/rules/ruff/snapshots/ruff_linter__rules__ruff__tests__RUF065_RUF065.py.snap
  ruff.schema.json
Labels: rule, preview

#20481 [ty] Remove unnecessary `FileScopeId` to `ScopeId` conversion
  crates/ty_python_semantic/src/semantic_index/scope.rs
  crates/ty_python_semantic/src/types/class.rs
  crates/ty_python_semantic/src/types/display.rs
  crates/ty_python_semantic/src/types/infer/builder.rs
Labels: internal, ty

#20487 [ty] Update `get-size2`
  Cargo.lock
  Cargo.toml
  crates/ruff_db/src/system/path.rs
  crates/ruff_db/src/vendored/path.rs
Labels: internal, ty

#20526 [`playground`]: Fix non‑BMP code point handling in quick‑fixes and markers
  crates/ruff_wasm/README.md
  crates/ruff_wasm/src/lib.rs
  crates/ruff_wasm/tests/api.rs
  playground/ruff/src/Editor/Editor.tsx
Labels: playground

#20243 [syntax-errors]: multiple-starred-expressions (F622)
  crates/ruff_linter/src/checkers/ast/analyze/expression.rs
  crates/ruff_linter/src/checkers/ast/mod.rs
  crates/ruff_linter/src/rules/pyflakes/rules/starred_expressions.rs
  crates/ruff_python_parser/resources/inline/err/multiple_starred_assignment_target.py
  crates/ruff_python_parser/resources/inline/ok/multiple_starred_assignment_target.py
  crates/ruff_python_parser/src/semantic_errors.rs
  crates/ruff_python_parser/tests/snapshots/invalid_syntax@multiple_starred_assignment_target.py.snap
  crates/ruff_python_parser/tests/snapshots/valid_syntax@multiple_starred_assignment_target.py.snap
Labels: internal

#20010 [`flake8-pyi`] Avoid syntax error from conflict with `PIE790` (`PYI021`)
  crates/ruff_linter/resources/test/fixtures/flake8_pyi/PYI021_1.pyi
  crates/ruff_linter/src/checkers/ast/analyze/definitions.rs
  crates/ruff_linter/src/checkers/ast/analyze/suite.rs
  crates/ruff_linter/src/checkers/ast/mod.rs
  crates/ruff_linter/src/rules/flake8_pyi/mod.rs
  crates/ruff_linter/src/rules/flake8_pyi/rules/docstring_in_stubs.rs
  crates/ruff_linter/src/rules/flake8_pyi/snapshots/ruff_linter__rules__flake8_pyi__tests__pyi021_pie790_isolation_check.snap
Labels: bug

#20557 [ty] Explicitly test assignability/subtyping between unions of nominal types and protocols with method members
  crates/ty_python_semantic/resources/mdtest/protocols.md
Labels: testing, ty

#20567 Add 'Finding ways to help' to CONTRIBUTING.md
  CONTRIBUTING.md
Labels: documentation

#20575 Update rooster to 0.1.0
  scripts/release.sh
Labels: release

#20576 Bump 0.13.2
  CHANGELOG.md
  Cargo.lock
  README.md
  crates/ruff/Cargo.toml
  crates/ruff_linter/Cargo.toml
  crates/ruff_wasm/Cargo.toml
  docs/integrations.md
  docs/tutorial.md
  pyproject.toml
  scripts/benchmarks/pyproject.toml
Labels: release

#20547 [ty] Filter overloads using variadic parameters
  crates/ty_python_semantic/resources/mdtest/call/function.md
  crates/ty_python_semantic/resources/mdtest/call/overloads.md
  crates/ty_python_semantic/src/types/call/bind.rs
  crates/ty_python_semantic/src/types/tuple.rs
Labels: ty

#20577 [ty] Update salsa to fix hang when cycle head panics
  Cargo.lock
  Cargo.toml
  crates/ty/src/logging.rs
  fuzz/Cargo.toml
Labels: bug, ty

#20574 [`pylint`] Fix missing `max-nested-blocks` in settings display
  crates/ruff/tests/lint.rs
  crates/ruff/tests/snapshots/show_settings__display_default_settings.snap
  crates/ruff_linter/src/rules/pylint/settings.rs
Labels: bug

#20533 [ty] Change to BDD representation for constraint sets
  crates/ty_python_semantic/resources/mdtest/type_properties/constraints.md
  crates/ty_python_semantic/src/types/constraints.rs
  crates/ty_python_semantic/src/types/generics.rs
  crates/ty_python_semantic/src/types/infer/builder.rs
  crates/ty_python_semantic/src/types/signatures.rs
  crates/ty_python_semantic/src/types/tuple.rs
Labels: internal, ty

#20573 [ty] Add more tests for subtyping/assignability between two protocol types
  crates/ty_python_semantic/resources/mdtest/loops/for.md
  crates/ty_python_semantic/resources/mdtest/protocols.md
Labels: testing, ty

#20592 [ty] Fix subtyping for dynamic specializations
  crates/ty_python_semantic/resources/mdtest/exhaustiveness_checking.md
  crates/ty_python_semantic/resources/mdtest/generics/pep695/variance.md
  crates/ty_python_semantic/src/types/generics.rs
Labels: ty, ecosystem-analyzer

#20593 [ty] Simplify `Any | (Any & T)` to `Any`
  crates/ty_python_semantic/resources/mdtest/type_properties/is_equivalent_to.md
  crates/ty_python_semantic/src/types.rs
  crates/ty_python_semantic/src/types/builder.rs
Labels: ty, ecosystem-analyzer

#20591 [ty] Use `Top` materializations for `TypeIs` special form
  crates/ty_python_semantic/resources/mdtest/narrow/type_guards.md
  crates/ty_python_semantic/src/types/infer/builder/type_expression.rs
Labels: ty, ecosystem-analyzer

#20587 Fixed documentation for try_consider_else
  crates/ruff_linter/src/rules/tryceratops/rules/try_consider_else.rs
Labels: documentation

#20624 Add the *The Basics* title back to CONTRIBUTING.md
  CONTRIBUTING.md
Labels: documentation

#20603 [ty] Improve disambiguation of class names in diagnostics
  crates/ty_python_semantic/resources/mdtest/diagnostics/same_names.md
  crates/ty_python_semantic/resources/mdtest/public_types.md
  crates/ty_python_semantic/src/types.rs
  crates/ty_python_semantic/src/types/diagnostic.rs
  crates/ty_python_semantic/src/types/display.rs
  crates/ty_python_semantic/src/types/visitor.rs
Labels: ty, diagnostics

#20596 [ty] Apply type mappings to functions eagerly
  crates/ty_python_semantic/src/types.rs
  crates/ty_python_semantic/src/types/function.rs
  crates/ty_python_semantic/src/types/generics.rs
  crates/ty_python_semantic/src/types/infer/builder.rs
  crates/ty_python_semantic/src/types/signatures.rs
Labels: internal, ty, ecosystem-analyzer

#20626 [ty] Ecosystem analyzer: relax timeout thresholds
  .github/workflows/ty-ecosystem-analyzer.yaml
  .github/workflows/ty-ecosystem-report.yaml
Labels: ci, ty

#20630 [ty] Remove unnecessary `parsed_module()` calls
  crates/ty_python_semantic/src/types.rs
  crates/ty_python_semantic/src/types/generics.rs
  crates/ty_python_semantic/src/types/infer/builder.rs
Labels: internal, ty

#20629 [ty] Ensure first-party search paths always appear in a sensible order
  crates/ty/tests/cli/python_environment.rs
  crates/ty_project/src/metadata/options.rs
Labels: ty, diagnostics

#20642 [`cli`] Add conflict between `--add-noqa` and `--diff` options
  crates/ruff/src/args.rs
Labels: bug, fixes

#20563 [`airflow`]: rename `AutoImport` as `Rename` (internal)
  crates/ruff_linter/src/rules/airflow/helpers.rs
  crates/ruff_linter/src/rules/airflow/rules/moved_to_provider_in_3.rs
  crates/ruff_linter/src/rules/airflow/rules/removal_in_3.rs
  crates/ruff_linter/src/rules/airflow/rules/suggested_to_move_to_provider_in_3.rs
  crates/ruff_linter/src/rules/airflow/rules/suggested_to_update_3_0.rs
Labels: internal

#20634 [`pyupgrade`] Prevent infinite loop with `I002` and `UP026`
  crates/ruff_linter/resources/test/fixtures/pyupgrade/UP029_0.py
  crates/ruff_linter/resources/test/fixtures/pyupgrade/UP029_1.py
  crates/ruff_linter/src/rules/pyupgrade/mod.rs
  crates/ruff_linter/src/rules/pyupgrade/rules/unnecessary_builtin_import.rs
  crates/ruff_linter/src/rules/pyupgrade/snapshots/ruff_linter__rules__pyupgrade__tests__UP029_0.py.snap
  crates/ruff_linter/src/rules/pyupgrade/snapshots/ruff_linter__rules__pyupgrade__tests__UP029_1.py_skip_required_imports.snap
Labels: bug, fixes
