Repository astral-sh/ruff, pull requests merged in 2025-10, with the labels that each got.

#20650 [ty] Fix subtyping of invariant generics specialized with `Any`
  crates/ty_python_semantic/resources/mdtest/type_properties/is_subtype_of.md
  crates/ty_python_semantic/src/types/generics.rs
Labels: bug, ty

#20666 [`ty`] Reject renaming files to start with slash in Playground
  playground/ty/src/Playground.tsx
Labels: playground

#20518 [`pylint`] Clarify fix safety to include left-hand hashability (`PLR6201`)
  crates/ruff_linter/src/rules/pylint/rules/literal_membership.rs
Labels: documentation

#20606 [ty] `~T` should never be assignable to `T`
  crates/ty_python_semantic/resources/mdtest/generics/legacy/functions.md
  crates/ty_python_semantic/resources/mdtest/generics/pep695/functions.md
  crates/ty_python_semantic/src/types.rs
Labels: ty

#20612 [`flake8-annotations`] Fix return type annotations to handle shadowed builtin symbols (`ANN201`, `ANN202`, `ANN204`, `ANN205`, `ANN206`)
  crates/ruff_linter/resources/test/fixtures/flake8_annotations/shadowed_builtins.py
  crates/ruff_linter/src/rules/flake8_annotations/helpers.rs
  crates/ruff_linter/src/rules/flake8_annotations/mod.rs
  crates/ruff_linter/src/rules/flake8_annotations/rules/definition.rs
  crates/ruff_linter/src/rules/flake8_annotations/snapshots/ruff_linter__rules__flake8_annotations__tests__shadowed_builtins.snap
Labels: bug, fixes

#20675 [ty] improve base conda distinction from child conda
  crates/ty/docs/environment.md
  crates/ty/tests/cli/python_environment.rs
  crates/ty_python_semantic/src/site_packages.rs
  crates/ty_static/src/env_vars.rs
Labels: ty

#20602 [ty] Introduce `TypeRelation::Redundancy`
  crates/ty_python_semantic/resources/mdtest/type_properties/is_equivalent_to.md
  crates/ty_python_semantic/resources/mdtest/union_types.md
  crates/ty_python_semantic/src/types.rs
  crates/ty_python_semantic/src/types/builder.rs
  crates/ty_python_semantic/src/types/class.rs
  crates/ty_python_semantic/src/types/function.rs
  crates/ty_python_semantic/src/types/generics.rs
  crates/ty_python_semantic/src/types/subclass_of.rs
  crates/ty_python_semantic/src/types/tuple.rs
Labels: performance, ty, ecosystem-analyzer

#20647 [ty] Clean up inherited generic contexts
  crates/ruff_memory_usage/src/lib.rs
  crates/ty_python_semantic/src/types.rs
  crates/ty_python_semantic/src/types/call/bind.rs
  crates/ty_python_semantic/src/types/class.rs
  crates/ty_python_semantic/src/types/display.rs
  crates/ty_python_semantic/src/types/function.rs
  crates/ty_python_semantic/src/types/generics.rs
  crates/ty_python_semantic/src/types/infer/builder.rs
  crates/ty_python_semantic/src/types/signatures.rs
Labels: internal, ty, ecosystem-analyzer

#20661 [`ty`] Fix playground crashes when accessing vendored files with leading slashes
  playground/ty/src/Playground.tsx
Labels: playground

#20520 [`refurb`] Add fixes for `FURB101`, `FURB103`
  crates/ruff_linter/src/preview.rs
  crates/ruff_linter/src/rules/refurb/helpers.rs
  crates/ruff_linter/src/rules/refurb/mod.rs
  crates/ruff_linter/src/rules/refurb/rules/read_whole_file.rs
  crates/ruff_linter/src/rules/refurb/rules/write_whole_file.rs
  crates/ruff_linter/src/rules/refurb/snapshots/ruff_linter__rules__refurb__tests__FURB101_FURB101.py.snap
  crates/ruff_linter/src/rules/refurb/snapshots/ruff_linter__rules__refurb__tests__FURB103_FURB103.py.snap
  crates/ruff_linter/src/rules/refurb/snapshots/ruff_linter__rules__refurb__tests__preview_FURB101_FURB101.py.snap
  crates/ruff_linter/src/rules/refurb/snapshots/ruff_linter__rules__refurb__tests__preview_FURB103_FURB103.py.snap
  crates/ruff_linter/src/rules/refurb/snapshots/ruff_linter__rules__refurb__tests__write_whole_file_python_39.snap
Labels: fixes, preview

#20689 Refactor Rust lint test structure to use RuffTestFixture
  Cargo.lock
  crates/ruff/Cargo.toml
  crates/ruff/tests/cli/lint.rs
  crates/ruff/tests/cli/main.rs
  crates/ruff/tests/cli/snapshots/cli__lint__flake8_import_convention_unused_aliased_import.snap
  crates/ruff/tests/cli/snapshots/cli__lint__flake8_import_convention_unused_aliased_import_no_conflict.snap
  crates/ruff/tests/cli/snapshots/cli__lint__output_format_azure.snap
  crates/ruff/tests/cli/snapshots/cli__lint__output_format_concise.snap
  crates/ruff/tests/cli/snapshots/cli__lint__output_format_full.snap
  crates/ruff/tests/cli/snapshots/cli__lint__output_format_github.snap
  crates/ruff/tests/cli/snapshots/cli__lint__output_format_gitlab.snap
  crates/ruff/tests/cli/snapshots/cli__lint__output_format_grouped.snap
  crates/ruff/tests/cli/snapshots/cli__lint__output_format_json-lines.snap
  crates/ruff/tests/cli/snapshots/cli__lint__output_format_json.snap
  crates/ruff/tests/cli/snapshots/cli__lint__output_format_junit.snap
  crates/ruff/tests/cli/snapshots/cli__lint__output_format_pylint.snap
  crates/ruff/tests/cli/snapshots/cli__lint__output_format_rdjson.snap
  crates/ruff/tests/cli/snapshots/cli__lint__output_format_sarif.snap
  crates/ruff/tests/cli/snapshots/cli__lint__output_format_show_fixes_concise.snap
  crates/ruff/tests/cli/snapshots/cli__lint__output_format_show_fixes_full.snap
  crates/ruff/tests/cli/snapshots/cli__lint__output_format_show_fixes_grouped.snap
  crates/ruff/tests/cli/snapshots/cli__lint__warn_invalid_noqa_with_no_diagnostics.snap
  crates/ruff/tests/lint.rs
Labels: testing

#20741 Move --show-settings snapshots to separate files
  crates/ruff/tests/cli/lint.rs
  crates/ruff/tests/cli/snapshots/cli__lint__requires_python_extend_from_shared_config.snap
  crates/ruff/tests/cli/snapshots/cli__lint__requires_python_no_tool.snap
  crates/ruff/tests/cli/snapshots/cli__lint__requires_python_no_tool_preview_enabled.snap
  crates/ruff/tests/cli/snapshots/cli__lint__requires_python_no_tool_target_version_override.snap
  crates/ruff/tests/cli/snapshots/cli__lint__requires_python_pyproject_toml_above.snap
  crates/ruff/tests/cli/snapshots/cli__lint__requires_python_pyproject_toml_above_with_tool.snap
  crates/ruff/tests/cli/snapshots/cli__lint__requires_python_ruff_toml_above-2.snap
  crates/ruff/tests/cli/snapshots/cli__lint__requires_python_ruff_toml_above.snap
  crates/ruff/tests/cli/snapshots/cli__lint__requires_python_ruff_toml_no_target_fallback.snap
Labels: testing

#20740 [ty] Make `infer_method_information` less confusing
  crates/ty_python_semantic/src/types/signatures.rs
Labels: internal, ty

#20749 [ty] Infer better specializations of unions with `None` (etc)
  crates/ty_python_semantic/resources/mdtest/generics/pep695/functions.md
  crates/ty_python_semantic/src/types.rs
  crates/ty_python_semantic/src/types/generics.rs
Labels: ty, ecosystem-analyzer

#20751 Bump 0.14.0
  BREAKING_CHANGES.md
  CHANGELOG.md
  Cargo.lock
  README.md
  changelogs/0.13.x.md
  crates/ruff/Cargo.toml
  crates/ruff_linter/Cargo.toml
  crates/ruff_wasm/Cargo.toml
  docs/integrations.md
  docs/tutorial.md
  pyproject.toml
  scripts/benchmarks/pyproject.toml
Labels: release

#20695 [`flake8-bugbear`] Mark `B905` and `B912` fixes as unsafe
  crates/ruff_linter/src/rules/flake8_bugbear/rules/map_without_explicit_strict.rs
  crates/ruff_linter/src/rules/flake8_bugbear/rules/zip_without_explicit_strict.rs
  crates/ruff_linter/src/rules/flake8_bugbear/snapshots/ruff_linter__rules__flake8_bugbear__tests__B905.py.snap
  crates/ruff_linter/src/rules/flake8_bugbear/snapshots/ruff_linter__rules__flake8_bugbear__tests__preview__B912_B912.py.snap
Labels: fixes

#20525 [`ruff`] Suppress diagnostic for f-string interpolations with debug text (`RUF010`)
  crates/ruff_linter/resources/test/fixtures/ruff/RUF010.py
  crates/ruff_linter/src/rules/ruff/rules/explicit_f_string_type_conversion.rs
  crates/ruff_linter/src/rules/ruff/snapshots/ruff_linter__rules__ruff__tests__RUF010_RUF010.py.snap
Labels: bug

#20754 [ty] fix implicit Self on generic class with typevar default
  crates/ty_python_semantic/resources/mdtest/annotations/self.md
  crates/ty_python_semantic/src/types.rs
  crates/ty_python_semantic/src/types/signatures.rs
Labels: ty, ecosystem-analyzer

#20769 [ty] Do not re-export `ide_support` attributes from `types`
  crates/ty_ide/src/goto.rs
  crates/ty_ide/src/inlay_hints.rs
  crates/ty_ide/src/semantic_tokens.rs
  crates/ty_ide/src/signature_help.rs
  crates/ty_python_semantic/src/semantic_model.rs
  crates/ty_python_semantic/src/types.rs
  crates/ty_python_semantic/src/types/function.rs
Labels: internal, ty
